import {z} from 'zod';
import {connectionSchema,type ConnectionProfile} from '../../domain/connection';
import {deploymentContractSchema,type DeploymentContract} from '../../adapters/core/capabilities';
import {normalizeCoreBase} from '../../adapters/core/url';
const deploymentSchema=z.strictObject({schemaVersion:z.literal(1),connections:z.array(z.strictObject({profile:connectionSchema,contract:deploymentContractSchema})).max(20)});
export type RegisteredConnection={profile:ConnectionProfile;contract:DeploymentContract};
let cached:Promise<RegisteredConnection[]>|undefined;
export function loadRegisteredConnections(force=false):Promise<RegisteredConnection[]>{if(force)cached=undefined;return cached??=(async()=>{try{const response=await fetch('/studio-deployment.json',{method:'GET',credentials:'omit',redirect:'error',cache:'no-store',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(3000)});if(!response.ok||!response.headers.get('content-type')?.includes('application/json'))return [];const reader=response.body?.getReader();if(!reader)return [];let size=0,text='';const decoder=new TextDecoder('utf-8',{fatal:true});try{while(true){const part=await reader.read();if(part.done)break;size+=part.value.byteLength;if(size>65536){await reader.cancel();return [];}text+=decoder.decode(part.value,{stream:true});}text+=decoder.decode();}finally{reader.releaseLock();}const config=deploymentSchema.parse(JSON.parse(text));if(new Set(config.connections.map(e=>e.profile.id)).size!==config.connections.length)return [];const proxyTargets=new Map<string,string>();for(const {profile,contract}of config.connections){const upstream=normalizeCoreBase(profile.originSnapshot),proxy=normalizeCoreBase(profile.proxyBase);if(!upstream.ok||!proxy.ok||upstream.value!==profile.originSnapshot||proxy.value!==profile.proxyBase||contract.version!==profile.contractVersion)return [];if(proxyTargets.has(proxy.value)&&proxyTargets.get(proxy.value)!==upstream.value)return [];proxyTargets.set(proxy.value,upstream.value);}return config.connections;}catch{return [];}})();}
export function matchRegisteredConnection(profile:ConnectionProfile,registry:RegisteredConnection[]){return registry.find(entry=>entry.profile.originSnapshot===profile.originSnapshot&&entry.profile.proxyBase===profile.proxyBase&&entry.profile.contractVersion===profile.contractVersion);}
