import {useEffect,useState} from 'react';
import type {Project} from '../../domain/project';
import type {WorkspaceClient} from '../../infrastructure/api/workspace-client';
import {workspaceMessage} from '../../infrastructure/api/workspace-client';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
import {LocalLink} from '../../app/routes';
export function CloudProjectsPage({client,trashed=false}:{client:WorkspaceClient;trashed?:boolean}){
 const [projects,setProjects]=useState<Project[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[sort,setSort]=useState('updated'),[open,setOpen]=useState(false),[target,setTarget]=useState<Project>(),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[busy,setBusy]=useState(false);
 const reload=async()=>{setProjects(await client.listProjects(trashed));setLoading(false);};
 useEffect(()=>{let active=true;setLoading(true);void client.listProjects(trashed).then(rows=>{if(active){setProjects(rows);setLoading(false);}}).catch(e=>{if(active){setError(workspaceMessage(e));setLoading(false);}});return()=>{active=false;};},[client,trashed]);
 async function action(work:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');try{await work();await reload();}catch(e){setError(workspaceMessage(e));}finally{setBusy(false);}}
 async function save(){await action(async()=>{if(target)await client.patchProject(target.id,target.revision,{title,description});else await client.createProject({title,description});setOpen(false);});}
 const visible=projects.filter(p=>(p.title+' '+p.description+' '+p.tags.join(' ')).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):b.updatedAt-a.updatedAt);
 return <section className="card"><div className="actions"><h1>{trashed?'项目回收站':'项目'}</h1>{!trashed?<Button data-interaction-id="cloud:project:new" variant="primary" onClick={()=>{setTarget(undefined);setTitle('');setDescription('');setOpen(true);}}>新建项目</Button>:null}<Button data-interaction-id="cloud:project:reload" disabled={busy} onClick={()=>action(reload)}>重新加载项目</Button></div><div className="actions"><label>搜索项目<input data-interaction-id="cloud:project:search" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>排序<select data-interaction-id="cloud:project:sort" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated">最近更新</option><option value="title">名称</option></select></label></div>{error?<p className="banner error" role="alert">{error}</p>:null}{loading?<p>正在读取云端项目…</p>:visible.length?<ul className="cloud-project-list">{visible.map(p=><li className="card" key={p.id}><h2>{trashed?p.title:<LocalLink data-interaction-id="cloud:project:open" href={'/projects/'+p.id+'/canvas'}>{p.title}</LocalLink>}</h2><p>{p.description}</p><small>修订 {p.revision} · {new Date(p.updatedAt).toLocaleString()}</small><div className="actions">{trashed?<Button data-interaction-id="cloud:project:restore" disabled={busy} onClick={()=>action(()=>client.restoreProject(p.id,p.revision))}>恢复项目</Button>:<><Button data-interaction-id="cloud:project:rename" disabled={busy} onClick={()=>{setTarget(p);setTitle(p.title);setDescription(p.description);setOpen(true);}}>修改项目信息</Button><Button data-interaction-id="cloud:project:star" disabled={busy} onClick={()=>action(()=>client.patchProject(p.id,p.revision,{starred:!p.starred}))}>{p.starred?'取消星标':'星标'}</Button><Button data-interaction-id="cloud:project:archive" disabled={busy} onClick={()=>action(()=>client.patchProject(p.id,p.revision,{archived:!p.archived}))}>{p.archived?'取消归档':'归档'}</Button><Button data-interaction-id="cloud:project:trash" variant="danger" disabled={busy} onClick={()=>action(()=>client.trashProject(p.id,p.revision))}>移入回收站</Button></>}</div></li>)}</ul>:<p>{query?'没有匹配的项目':trashed?'回收站没有项目':'还没有项目'}</p>}<Dialog open={open} title={target?'修改项目信息':'新建项目'} dismissible={!busy} onClose={()=>setOpen(false)} footer={<><Button data-interaction-id="cloud:project:cancel" disabled={busy} onClick={()=>setOpen(false)}>取消</Button><Button data-interaction-id="cloud:project:save" variant="primary" busy={busy} disabled={!title.trim()||[...title].length>60} onClick={save}>{target?'保存项目信息':'创建项目'}</Button></>}><label>项目名称<input data-interaction-id="cloud:project:title" value={title} onChange={e=>setTitle(e.target.value)}/></label><label>项目说明<textarea data-interaction-id="cloud:project:description" value={description} onChange={e=>setDescription(e.target.value)}/></label>{error?<p role="alert">{error}</p>:null}</Dialog></section>;
}
