import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import type {CanvasNode} from '../../domain/graph';
import type {Asset} from '../../domain/asset';
import type {CloudVideoRecord} from '../../domain/cloud-video-run';
import type {CloudVideoCapability} from '../../domain/cloud-video-run';
import type {CapabilityProfile} from '../../domain/connection';
import type {ResultSourceRun} from '../../domain/graph-validation';
import type {GraphOperation} from '../../application/commands/registry';
import {workspaceMessage,type WorkspaceClient} from '../../infrastructure/api/workspace-client';
import {createCloudCanvasModel} from './cloud-canvas-model';
import {uploadCloudAsset} from './CloudAssetsPage';
import {CloudAssetPicker} from './CloudAssetPicker';
import {CloudCanvasSurface} from './CloudCanvasSurface';
import {CanvasToolbar} from '../canvas/CanvasToolbar';
import {nodeBounds} from '../canvas/geometry';
import {groupSelection,arrangeNodes,alignNodes,moveOperations} from '../canvas/group-layout';
import {copyNodes,pasteNodes,createBranch,branchSpec,type NodeClipboard} from '../canvas/branch-command';
import {ArrangePreview} from '../canvas/ArrangePreview';
import type {PositionPatch} from '../canvas/group-layout';
import {Button} from '../../ui/Button';
import {LocalLink,addNavigationGuard,useRoute} from '../../app/routes';
import {Dialog} from '../../ui/Dialog';
import {CloudVideoRunPanel} from './CloudVideoRunPanel';
import {CloudAgentPanel} from './CloudAgentPanel';
import {usePreferences} from '../settings/preferences-store';
const op=(type:GraphOperation['type'],payload:Record<string,unknown>):GraphOperation=>({id:crypto.randomUUID(),type,payload});
export function CloudCanvasPage({client,projectId}:{client:WorkspaceClient;projectId:string}){
 const preferences=usePreferences(),[videoSpecs,setVideoSpecs]=useState<CloudVideoCapability['videoSpecs']>([]),[capability,setCapability]=useState<CapabilityProfile>({contractVersion:'cloud-account-capability',verification:'unknown',textModels:[],videoModels:[],videoAliases:[],videoSpecs:[],workContext:false,continuation:false,imageGeneration:false,audioGeneration:false,cancelVideo:false,backup:false});
 const [model]=useState(()=>createCloudCanvasModel(projectId,client,{autosaveMs:1500})),state=useSyncExternalStore(model.subscribe,model.getState),graph=state.graph;
 const [assets,setAssets]=useState<Asset[]>([]),[runs,setRuns]=useState<ResultSourceRun[]>([]),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState(''),[tool,setTool]=useState<'select'|'pan'>('select'),[background,setBackground]=useState('dots'),[minimap,setMinimap]=useState(false),[sideOpen,setSideOpen]=useState(true),[outlineOpen,setOutlineOpen]=useState(true),[addOpen,setAddOpen]=useState(false),[modelName,setModelName]=useState(''),[source,setSource]=useState(''),[target,setTarget]=useState(''),[port,setPort]=useState<'text'|'image'|'video'>('text'),[discardOpen,setDiscardOpen]=useState(false),[patches,setPatches]=useState<PositionPatch[]|null>(null);
 const stageRef=useRef<HTMLDivElement>(null),[clipboard,setClipboard]=useState<NodeClipboard>();
 const busy=state.status==='saving'||state.status==='loading',canEdit=!busy&&state.status!=='failed';
 useEffect(()=>{void model.load();void client.listAssets().then(setAssets).catch(e=>setError(workspaceMessage(e)));return()=>model.dispose();},[client,model]);
 const route=useRoute(),focusedOnce=useRef(false);
 useEffect(()=>{if(focusedOnce.current||!graph)return;const nodeId=new URLSearchParams(route.split('?')[1]??'').get('node');if(!nodeId||!graph.nodes.some(node=>node.id===nodeId))return;focusedOnce.current=true;setSelected([nodeId]);fit([nodeId]);},[client,graph,route]);
 useEffect(()=>{let active=true;void client.videoCapability().then(value=>{if(active){setVideoSpecs(value.videoSpecs);setModelName(current=>current||value.model);setCapability({contractVersion:'cloud-account-capability',verification:value.verified?'reviewed':'unknown',textModels:[],videoModels:[...new Set([...value.videoSpecs.map(spec=>spec.modelId),value.model])],videoAliases:[],videoSpecs:value.videoSpecs,workContext:false,continuation:false,imageGeneration:false,audioGeneration:false,cancelVideo:false,backup:false,...(value.limits?{limits:value.limits}:{})});}}).catch(()=>{});return()=>{active=false;};},[client]);
 useEffect(()=>{let active=true;void client.modelConfigs().then(({configs})=>{if(active)setCapability(current=>({...current,textModels:configs.filter(config=>config.channel==='text').map(config=>config.model)}));}).catch(()=>{});return()=>{active=false;};},[client]);
 useEffect(()=>{let active=true;async function load(){try{const rows=await client.listTasks();if(active)setRuns(rows.filter((run):run is CloudVideoRecord=>run.kind==='video'&&run.projectId===projectId).map(run=>({id:run.id,projectId:run.projectId,nodeId:run.nodeId,resultAssetId:run.resultAssetId,executionState:run.executionState})));}catch{/* Lineage badges refresh on next save. */}}void load();const timer=setInterval(()=>{void load();},4000);return()=>{active=false;clearInterval(timer);};},[client,projectId]);
 useEffect(()=>{const before=(event:BeforeUnloadEvent)=>{if(model.getState().status!=='saved'){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',before);const remove=addNavigationGuard(()=>{if(model.getState().status==='saved')return true;setError('画布有未保存的输入，请先保存或明确放弃后再离开。');return false;});return()=>{window.removeEventListener('beforeunload',before);remove();};},[model]);
 function stage(operations:GraphOperation[]): void{setError('');try{model.stage(operations);}catch{setError('此修改暂未应用，请先重试保存或核对当前画布。');}}
 function tryStage(operations:GraphOperation[]): boolean{setError('');try{model.stage(operations);return true;}catch{setError('此修改暂未应用，请先重试保存或核对当前画布。');return false;}}
 async function commitOps(operations:GraphOperation[]): Promise<boolean>{
  setError('');
  try{model.stage(operations);}catch{setError('此修改暂未应用，请先重试保存或核对当前画布。');return false;}
  await model.save();
  for(let attempt=0;attempt<50&&model.getState().status==='saving';attempt++)await new Promise(resolve=>setTimeout(resolve,100));
  const ok=model.getState().status==='saved';
  if(!ok)setError('保存未完成 · 输入已保留，可重试保存。');
  return ok;
 }
 function add(type:'text'|'video-generation'|'asset',asset?:Asset){
  const id=crypto.randomUUID(),base={id,title:type==='text'?'文字':type==='asset'?asset!.title:'视频草稿',x:64+((graph?.nodes.length??0)%3)*380,y:64+Math.floor((graph?.nodes.length??0)/3)*440,locked:false};
  const available=videoSpecs.filter(spec=>spec.modelId===modelName.trim()),preferred=available.find(spec=>(preferences.defaultDuration===null||spec.durationSeconds===preferences.defaultDuration)&&(!preferences.defaultRatio||spec.ratio===preferences.defaultRatio));
  const node:CanvasNode=type==='text'?{...base,type,data:{kind:'text',text:'',referenceTokens:[]}}:type==='asset'?{...base,type,data:{kind:'asset',assetId:asset!.id}}:{...base,type,data:{kind:'video-generation',draft:preferred??available[0]??{modelId:modelName.trim()},inputBindings:[],stale:true}};
  stage([op('add_node',{node})]);setSelected([id]);setAddOpen(false);
 }
 function fit(ids?:string[]){if(!graph||!stageRef.current)return;const nodes=ids?graph.nodes.filter(n=>ids.includes(n.id)):graph.nodes;if(!nodes.length)return;const bounds=nodeBounds(nodes,graph),size=stageRef.current.getBoundingClientRect(),scale=Math.max(.25,Math.min(2,(size.width-80)/(bounds.right-bounds.left),(size.height-80)/(bounds.bottom-bounds.top)));model.viewport({x:40-bounds.left*scale,y:40-bounds.top*scale,scale});}
 async function files(values:File[]){try{const added:Asset[]=[];for(const file of values)added.push(await uploadCloudAsset(client,file));setAssets(await client.listAssets());for(const asset of added)add('asset',asset);}catch(e){setError(workspaceMessage(e));}}
 function branchTarget(){if(!graph||selected.length!==1)return undefined;const node=graph.nodes.find(n=>n.id===selected[0]);if(!node||node.locked)return undefined;const draft=branchSpec(graph,node.id,{defaultDraft:capability.videoSpecs[0]});return node&&draft?{node,draft}:undefined;}
 function alignSelected(mode:'left'|'top'|'horizontal-spacing'){if(!graph)return;const patches=alignNodes(graph,selected,mode);if(!patches.length){setError(mode==='horizontal-spacing'?'等间距需要至少三个可编辑节点。':'对齐需要至少两个可编辑节点。');return;}void commitOps(moveOperations(patches));}
 if(!graph)return <section className="card"><h1>云端画布</h1>{state.error?<p role="alert">{workspaceMessage(state.error)}</p>:<p>正在读取画布…</p>}<Button data-interaction-id="cloud:canvas:retry-load" onClick={()=>model.load(true)}>重新加载</Button></section>;
 const view=graph.viewport;
 const branch=branchTarget();
 return <section className="cloud-canvas-page"><div className="actions"><h1>{state.project?.title}</h1><LocalLink data-interaction-id="cloud:canvas:projects" href="/projects">返回项目</LocalLink><Button data-interaction-id="cloud:canvas:save" variant="primary" busy={busy} disabled={state.status==='saved'} onClick={()=>model.save()}>{state.status==='failed'?'重试保存':'保存到云端'}</Button><Button data-interaction-id="cloud:canvas:reload" disabled={busy} onClick={()=>state.status==='saved'?model.load():setDiscardOpen(true)}>重新加载画布</Button><span role="status">{state.status==='saved'?'已保存 · 云端修订 '+graph.revision:state.status==='saving'?'正在保存到云端…':state.status==='failed'?'保存未完成 · 输入已保留':'未保存'}</span></div>{error||state.error?<p role="alert" className="banner error">{error||workspaceMessage(state.error)}</p>:null}
 <CanvasToolbar scale={view.scale} onZoom={scale=>model.viewport({...view,scale})} tool={tool} onTool={setTool} onFit={()=>fit()} onLocate={()=>fit(selected)} selectedCount={selected.length} minimap={minimap} onMinimap={()=>setMinimap(!minimap)} background={background} onBackground={setBackground} onAdd={()=>setAddOpen(true)} canWrite={canEdit} onUndo={()=>{void model.history('undo');}} onRedo={()=>{void model.history('redo');}} canUndo={state.status==='saved'&&state.history.undoDepth>0} canRedo={state.status==='saved'&&state.history.redoDepth>0}/>
 <div className="actions"><Button data-interaction-id="cloud:canvas:add-text" disabled={!canEdit} onClick={()=>add('text')}>添加文字节点</Button><Button data-interaction-id="cloud:canvas:copy" disabled={!selected.length} onClick={()=>{setClipboard(copyNodes(graph,selected));}}>复制节点</Button><Button data-interaction-id="cloud:canvas:paste" disabled={!canEdit||!clipboard} onClick={()=>{if(clipboard)void commitOps(pasteNodes(clipboard,graph));}}>粘贴节点</Button><Button data-interaction-id="cloud:canvas:branch" disabled={!canEdit||!branch} title={!branch?'请选择一个可分支的文字或视频草稿节点。':undefined} onClick={()=>{if(branch)void commitOps(createBranch(graph,branch.node.id,{defaultDraft:branch.draft}));}}>复制为分支</Button><Button data-interaction-id="cloud:canvas:group" disabled={!canEdit||selected.length<2} onClick={()=>{try{stage(groupSelection(graph,selected,'分组'));}catch{setError('请选择至少两个可编辑节点进行分组。');}}}>创建分组</Button><Button data-interaction-id="cloud:canvas:arrange" disabled={!canEdit||!selected.length} onClick={()=>stage(arrangeNodes(graph,selected).map(p=>op('move_node',p)))}>整理选中</Button><Button data-interaction-id="cloud:canvas:align" disabled={!canEdit||selected.length<2} onClick={()=>alignSelected('left')}>对齐</Button><Button data-interaction-id="cloud:canvas:distribute" disabled={!canEdit||selected.length<3} onClick={()=>alignSelected('horizontal-spacing')}>等间距</Button><Button data-interaction-id="cloud:canvas:layout-preview" disabled={!canEdit||!selected.length} onClick={()=>setPatches(arrangeNodes(graph,selected))}>布局预览</Button><Button data-interaction-id="cloud:canvas:delete" disabled={!canEdit||!selected.length} onClick={()=>{const targets=selected.filter(nodeId=>!graph.nodes.find(n=>n.id===nodeId)?.locked);if(targets.length)void commitOps(targets.map(nodeId=>op('remove_node',{nodeId})));setSelected([]);}}>删除选中节点</Button><Button data-interaction-id="cloud:canvas:outline-toggle" aria-expanded={outlineOpen} onClick={()=>setOutlineOpen(open=>!open)}>{outlineOpen?'收起大纲':'展开大纲'}</Button><Button data-interaction-id="cloud:canvas:side-toggle" aria-expanded={sideOpen} onClick={()=>setSideOpen(open=>!open)}>{sideOpen?'收起侧栏':'展开侧栏'}</Button><label>导入素材<input data-interaction-id="cloud:canvas:files" type="file" multiple disabled={!canEdit} onChange={event=>{void files(Array.from(event.target.files??[]));event.target.value='';}}/></label></div>
 <div className={'canvas-main'+(sideOpen?'':' side-collapsed')+(outlineOpen?'':' outline-collapsed')}><div className="canvas-layout" onCompositionStartCapture={()=>model.setComposing(true)} onCompositionEndCapture={()=>model.setComposing(false)}>
 <CloudCanvasSurface client={client} graph={graph} selected={selected} setSelected={setSelected} canEdit={canEdit} saved={state.status==='saved'} assets={assets} runs={runs} capability={capability} stageRef={stageRef} tool={tool} setTool={setTool} background={background} minimap={minimap} clipboard={clipboard} setClipboard={setClipboard} stageOps={tryStage} commitOps={commitOps} onViewport={viewport=>model.viewport(viewport)} onError={setError} onSave={()=>model.save()} onUndo={()=>{void model.history('undo');}} onRedo={()=>{void model.history('redo');}} onFiles={values=>void files(values)} fit={ids=>fit(ids)}/>
 <aside className="canvas-outline"><h2>节点与连线</h2><ul>{graph.nodes.map(n=><li key={n.id}><label><input type="checkbox" data-interaction-id="cloud:canvas:outline-select" checked={selected.includes(n.id)} onChange={event=>setSelected(event.target.checked?[...selected,n.id]:selected.filter(id=>id!==n.id))}/>{n.title}</label></li>)}</ul><fieldset disabled={!canEdit}><legend>连接输入</legend><label>来源节点<select data-interaction-id="cloud:canvas:source" value={source} onChange={event=>setSource(event.target.value)}><option value="">请选择</option>{graph.nodes.filter(n=>['text','asset','result'].includes(n.type)).map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><label>视频草稿<select data-interaction-id="cloud:canvas:target" value={target} onChange={event=>setTarget(event.target.value)}><option value="">请选择</option>{graph.nodes.filter(n=>n.type==='video-generation').map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><label>输入类型<select data-interaction-id="cloud:canvas:port" value={port} onChange={event=>setPort(event.target.value as typeof port)}><option value="text">文字</option><option value="image">图片</option><option value="video">视频</option></select></label><Button data-interaction-id="cloud:canvas:connect" disabled={!source||!target} onClick={()=>stage([op('add_edge',{edge:{id:crypto.randomUUID(),sourceId:source,targetId:target,port,order:Math.max(-1,...graph.edges.filter(e=>e.targetId===target).map(e=>e.order))+1}})])}>连接节点</Button></fieldset>{graph.edges.map(e=><p key={e.id}>{e.port} · 输入 {e.order+1}<Button data-interaction-id="cloud:canvas:disconnect" disabled={!canEdit} onClick={()=>stage([op('remove_edge',{edgeId:e.id})])}>删除连线</Button></p>)}</aside></div>
 <aside className={'canvas-side'+(sideOpen?'':' side-hidden')} aria-label="视频生成与 Agent"><CloudVideoRunPanel client={client} graph={graph} selected={selected} saved={state.status==='saved'} canEdit={canEdit} stage={tryStage} onResultInserted={()=>{void model.load();void client.listAssets().then(setAssets).catch(e=>setError(workspaceMessage(e)));}}/>
 <CloudAgentPanel client={client} graph={graph} selected={selected} saved={state.status==='saved'} onApplied={()=>{void model.load();}}/></aside></div>
 <ArrangePreview graph={graph} patches={patches} onClose={()=>setPatches(null)} onApply={async()=>{if(patches)await commitOps(moveOperations(patches));setPatches(null);}}/>
 <Dialog open={addOpen} title="添加节点" onClose={()=>setAddOpen(false)}><Button data-interaction-id="cloud:canvas:dialog-text" onClick={()=>add('text')}>添加文字节点</Button><label>视频模型名称<input data-interaction-id="cloud:canvas:dialog-model" value={modelName} onChange={event=>setModelName(event.target.value)}/></label><Button data-interaction-id="cloud:canvas:add-video" disabled={!modelName.trim()} onClick={()=>add('video-generation')}>添加视频草稿</Button><CloudAssetPicker client={client} assets={assets} canWrite={canEdit} onPick={asset=>add('asset',asset)} onUploaded={()=>{void client.listAssets().then(setAssets).catch(e=>setError(workspaceMessage(e)));}}/></Dialog>
 <Dialog open={discardOpen} title="重新加载画布" onClose={()=>setDiscardOpen(false)} footer={<><Button data-interaction-id="cloud:canvas:keep" onClick={()=>setDiscardOpen(false)}>保留输入</Button><Button data-interaction-id="cloud:canvas:discard" variant="danger" onClick={async()=>{await model.load(true);setDiscardOpen(false);}}>放弃未保存输入并重新加载</Button></>}><p>当前输入尚未确认保存。重新加载会放弃本页未保存的修改。</p></Dialog></section>;
}
