import {useEffect,useRef,useState} from 'react';
import type {PromptDraft,PromptResultVersion} from '../../domain/prompt';
import type {Asset} from '../../domain/asset';
import {workspaceMessage,type WorkspaceClient} from '../../infrastructure/api/workspace-client';
import {PromptForm} from '../prompt-generation/PromptForm';
import {useCloudDraftGuard} from './use-cloud-draft-guard';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
import {CloudApplyPromptDialog} from './CloudApplyPromptDialog';
import type {CloudTask,CloudPromptPreview} from '../../domain/cloud-task';
import {ApiError} from '../../infrastructure/api/client';
import {cloudTaskStatus} from './CloudTasksPage';
import {CloudPromptInputSnapshot} from './CloudPromptInputSnapshot';
export function CloudPromptGeneratorPage({client,trashed=false}:{client:WorkspaceClient;trashed?:boolean}){
 const [drafts,setDrafts]=useState<PromptDraft[]>([]),[draft,setDraft]=useState<PromptDraft>(),[saved,setSaved]=useState<PromptDraft>(),[assets,setAssets]=useState<Asset[]>([]);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[snapshot,setSnapshot]=useState<PromptDraft>(),[discard,setDiscard]=useState(false);
 const [editing,setEditing]=useState<PromptResultVersion>(),[manual,setManual]=useState(''),[discardManual,setDiscardManual]=useState(false),[applying,setApplying]=useState<PromptResultVersion>();
 const [preview,setPreview]=useState<CloudPromptPreview>(),[fee,setFee]=useState(false),[unknown,setUnknown]=useState(false),[task,setTask]=useState<CloudTask>();
 const alive=useRef(true),composing=useRef(false),creation=useRef<string|undefined>(undefined);
 const dirty=!!draft&&JSON.stringify(draft)!==JSON.stringify(saved);
 const manualDirty=!!editing&&manual!==editing.finalPrompt;
 useCloudDraftGuard(dirty||manualDirty,()=>setError('写作草稿有未保存输入，请先保存或明确放弃后再离开。'));
 const accept=(value:PromptDraft)=>{if(alive.current){setDraft(value);setSaved(value);setDrafts(rows=>[value,...rows.filter(row=>row.id!==value.id)]);}};
 async function reload(){const rows=await client.listDrafts(trashed);if(alive.current){setDrafts(rows);const current=rows.find(row=>row.id===draft?.id)??rows[0];setDraft(current);setSaved(current);}}
 useEffect(()=>{let active=true;alive.current=true;void Promise.all([client.listDrafts(trashed),client.listAssets()]).then(([rows,media])=>{if(active){setDrafts(rows);setDraft(rows[0]);setSaved(rows[0]);setAssets(media);}}).catch(e=>{if(active)setError(workspaceMessage(e));});return()=>{active=false;alive.current=false;};},[client,trashed]);
 useEffect(()=>{let active=true;setTask(undefined);if(draft&&!trashed)void client.listTasks().then(rows=>{if(active)setTask(rows.filter((row):row is CloudTask=>row.kind==='prompt-optimize').find(row=>row.draftId===draft.id&&!row.historical));}).catch(e=>{if(active)setError(workspaceMessage(e));});return()=>{active=false;};},[client,draft?.id,trashed]);
 useEffect(()=>{if(!task||!['persisted','sending','response_received'].includes(task.executionState))return;let active=true,reading=false;const timer=setInterval(()=>{if(reading)return;reading=true;void client.readTask(task.id).then(current=>{if(active&&current.kind==='prompt-optimize')setTask(current);}).catch(e=>{if(active)setError(workspaceMessage(e));}).finally(()=>{reading=false;});},1000);return()=>{active=false;clearInterval(timer);};},[client,task?.id,task?.executionState]);
 useEffect(()=>{if(!task||!draft||task.draftId!==draft.id||task.executionState!=='succeeded'||draft.resultVersions.some(version=>version.id===task.resultVersionId))return;if(dirty){setMessage('AI 结果已保存。当前输入尚未保存，请保留输入后再重新加载结果。');return;}let active=true;void client.readDraft(task.draftId).then(value=>{if(active){accept(value);setMessage('AI 结果已保存');}}).catch(e=>{if(active)setError(workspaceMessage(e));});return()=>{active=false;};},[client,task?.id,task?.executionState,task?.resultVersionId,draft?.id,draft?.revision,dirty]);
 async function action(work:()=>Promise<void>){if(busy||composing.current)return;setBusy(true);setError('');setMessage('');try{await work();}catch(e){if(alive.current)setError(workspaceMessage(e));}finally{if(alive.current)setBusy(false);}}
 async function create(){if(dirty){setError('请先保存当前草稿，再新建草稿。');return;}await action(async()=>{creation.current??=crypto.randomUUID();const value=await client.createDraft({type:'video',userRequest:'',sceneId:'text',requestedSpec:{},audioPlan:'',lockedConstraints:[],references:[],ruleVersion:'studio-video-rules-v1'},creation.current);creation.current=undefined;accept(value);setMessage('草稿已保存');});}
 async function save(){if(!draft||!saved)return;await action(async()=>{const {id:_,revision:__,resultVersions:___,...fields}=draft;void _;void __;void ___;const value=await client.patchDraft(draft.id,saved.revision,fields);accept(value);setMessage('草稿已保存');});}
 async function compile(){if(!draft||dirty)return;await action(async()=>{accept(await client.compileDraft(draft.id,draft.revision));setMessage('规则整理结果已保存');});}
 async function saveManual(){if(!draft||!editing||!manual.trim())return;await action(async()=>{const {finalPrompt:_,shotPlan,improvements,warnings,suggestedSpec}=editing;void _;accept(await client.appendDraftResult(draft.id,draft.revision,{finalPrompt:manual,shotPlan,improvements,warnings,suggestedSpec}));if(alive.current){setEditing(undefined);setMessage('人工结果已保存为新版本');}});}
 const closeManual=()=>manualDirty?setDiscardManual(true):setEditing(undefined);
 async function prepareAI(){if(!draft||dirty)return;await action(async()=>{const {configs}=await client.modelConfigs(),config=configs.find(value=>value.channel==='text'&&value.hasKey);if(!config)throw new ApiError(422,'MODEL_CONFIG_REQUIRED');const value=await client.optimizationPreview(draft.id,draft.revision,config.revision,draft.references.map(reference=>reference.alias));if(alive.current){setPreview(value);setFee(false);setUnknown(false);}});}
 async function confirmAI(){if(!preview||!fee||preview.priorUnknownRunIds.length&&!unknown)return;await action(async()=>{const value=await client.optimizeDraft(preview.draftId,preview.id,unknown);if(alive.current){setTask(value);setPreview(undefined);setMessage('任务已保存，可在任务中心继续查看');}});}
 if(trashed)return <section className="card"><h1>写作草稿回收站</h1>{error?<p role="alert">{error}</p>:null}{drafts.length?drafts.map(row=><article key={row.id}><h2>{row.userRequest.slice(0,60)||'未命名草稿'}</h2><Button data-interaction-id="cloud:draft:restore" disabled={busy} onClick={()=>action(async()=>{await client.restoreDraft(row.id,row.revision);await reload();})}>恢复写作草稿</Button></article>):<p>回收站没有写作草稿</p>}</section>;
 return <section className="card"><div className="actions"><h1>视频提示词写作</h1><Button data-interaction-id="cloud:draft:new" busy={busy} onClick={create}>新建视频写作草稿</Button><Button data-interaction-id="cloud:draft:reload" disabled={busy} onClick={()=>dirty?setDiscard(true):action(reload)}>重新加载写作草稿</Button></div>
  {error?<p role="alert" className="banner error">{error}</p>:null}<p role="status">{message||(!draft?'尚未选择草稿':dirty?'输入尚未保存':'草稿已保存 · 修订 '+draft.revision)}</p>
  <label>选择写作草稿<select aria-label="选择写作草稿" data-interaction-id="cloud:draft:select" value={draft?.id??''} disabled={busy} onChange={event=>{if(dirty){setError('请先保存当前草稿，再切换草稿。');return;}const next=drafts.find(row=>row.id===event.target.value);setDraft(next);setSaved(next);setMessage('');}}><option value="">请选择</option>{drafts.map(row=><option key={row.id} value={row.id}>{row.userRequest.slice(0,40)||'未命名草稿'} · 修订 {row.revision}</option>)}</select></label>
  {draft?<><fieldset disabled={busy}><legend>写作输入</legend><PromptForm storage="cloud" draft={draft} assets={assets} availableIds={new Set(assets.map(asset=>asset.id))} onChange={patch=>{setDraft(current=>current?{...current,...patch}:current);setMessage('');}} onComposing={value=>{composing.current=value;}} contextTexts={[]} onChooseLibrary={async()=>{try{const media=await client.listAssets();if(alive.current){setAssets(media);setMessage('云端素材已重新加载');}}catch(e){if(alive.current)setError(workspaceMessage(e));}}}/></fieldset>
   <div className="actions"><Button data-interaction-id="cloud:draft:save" variant="primary" busy={busy} onClick={save}>保存写作草稿</Button><Button data-interaction-id="cloud:draft:compile" disabled={busy||dirty||!draft.userRequest.trim()} onClick={compile}>规则整理</Button><Button data-interaction-id="cloud:draft:ai-preview" disabled={busy||dirty||!draft.userRequest.trim()||!!task&&['persisted','sending','response_received'].includes(task.executionState)} onClick={prepareAI}>AI 优化</Button><Button data-interaction-id="cloud:draft:trash" disabled={busy||dirty} onClick={()=>action(async()=>{await client.trashDraft(draft.id,draft.revision);await reload();})}>移入写作草稿回收站</Button></div>{task?<p>{cloudTaskStatus(task)}{task.billingState==='pending_reconciliation'?' · 积分仍在核对，尚未确认最终扣费。':''}</p>:null}
   <p>规则整理根据当前输入编写候选文字；结果不会自动应用到画布或执行视频。</p><h2>结果历史</h2>{draft.resultVersions.length?[...draft.resultVersions].reverse().map(version=><article key={version.id} className="card"><h3>{version.origin==='local'?'规则整理':version.origin==='ai'?'AI 优化':'人工修订'} · 输入修订 {version.sourceRevision}</h3><p>{version.validationState==='valid'?'规则检查通过':'结果待检查'}</p><pre aria-label="结果正文">{version.finalPrompt}</pre>{version.warnings.map((warning,index)=><p key={index}>{warning}</p>)}<div className="actions"><Button data-interaction-id="cloud:draft:input-snapshot" disabled={busy} onClick={()=>action(async()=>{const input=await client.draftRevision(draft.id,version.sourceRevision);if(alive.current)setSnapshot(input);})}>查看输入快照</Button><Button data-interaction-id="cloud:draft:manual" disabled={busy||dirty} onClick={()=>{setEditing(version);setManual(version.finalPrompt);setError('');}}>人工修改结果</Button><Button data-interaction-id="cloud:draft:restore-result" disabled={busy||dirty} onClick={()=>action(async()=>{accept(await client.restoreDraftResult(draft.id,draft.revision,version.id));setMessage('历史结果已恢复为新的人工版本');})}>恢复此历史结果</Button><Button data-interaction-id="cloud:draft:apply" disabled={busy||dirty} onClick={()=>setApplying(version)}>应用此结果到画布</Button></div></article>):<p>尚无结果版本</p>}
  </>:<p>新建草稿后开始写作。</p>}
  <Dialog open={!!snapshot} title="历史输入快照" onClose={()=>setSnapshot(undefined)}><p>输入修订 {snapshot?.revision} · 规则 {snapshot?.ruleVersion}</p>{snapshot?<CloudPromptInputSnapshot input={snapshot}/>:null}</Dialog>
  <Dialog open={!!editing} title="人工修改写作结果" dismissible={!busy} onClose={closeManual} footer={<><Button data-interaction-id="cloud:draft:manual-cancel" disabled={busy} onClick={closeManual}>取消</Button><Button data-interaction-id="cloud:draft:manual-save" variant="primary" busy={busy} disabled={!manual.trim()} onClick={saveManual}>保存为新的人工结果</Button></>}><p>保存后保留原结果，并新增人工版本；应用前仍需检查规格、镜头和参考素材。</p><label>人工结果正文<textarea aria-label="人工结果正文" data-interaction-id="cloud:draft:manual-text" disabled={busy} value={manual} onChange={event=>setManual(event.target.value)}/></label>{error?<p role="alert">{error}</p>:null}</Dialog>
  <Dialog open={discardManual} title="放弃未保存人工结果" onClose={()=>setDiscardManual(false)} footer={<><Button data-interaction-id="cloud:draft:manual-keep" onClick={()=>setDiscardManual(false)}>继续修改</Button><Button data-interaction-id="cloud:draft:manual-discard" variant="danger" onClick={()=>{setEditing(undefined);setDiscardManual(false);}}>放弃人工修改</Button></>}><p>当前修改尚未保存，原结果仍保留。</p></Dialog>
  {draft&&applying?<CloudApplyPromptDialog client={client} draft={draft} version={applying} onClose={()=>setApplying(undefined)} onApplied={revision=>{setApplying(undefined);setMessage('写作结果已应用到云端画布 · 修订 '+revision);}}/>:null}
  <Dialog open={!!preview} title="确认 AI 文字优化" dismissible={!busy} onClose={()=>setPreview(undefined)} footer={<><Button data-interaction-id="cloud:draft:ai-cancel" disabled={busy} onClick={()=>setPreview(undefined)}>取消</Button><Button data-interaction-id="cloud:draft:ai-confirm" variant="primary" busy={busy} disabled={!fee||!!preview?.priorUnknownRunIds.length&&!unknown} onClick={confirmAI}>确认调用文字模型</Button></>}>
   <p>模型：{preview?.model}</p><p>地址：{preview?.apiBase} · 输入修订 {preview?.draftRevision} · 配置修订 {preview?.configRevision}</p><p>仅发送写作文字和已选择素材的描述，图片和视频原件不会上传。</p><p>参考别名：{preview?.referenceAliases.join('、')||'无'}</p><label><input data-interaction-id="cloud:draft:ai-fee" type="checkbox" disabled={busy} checked={fee} onChange={event=>setFee(event.target.checked)}/>我确认此文字调用可能收费</label>{preview?.priorUnknownRunIds.length?<><p>此前有 {preview.priorUnknownRunIds.length} 次调用结果未知，可能已经执行或扣费。</p><label><input data-interaction-id="cloud:draft:ai-unknown" type="checkbox" disabled={busy} checked={unknown} onChange={event=>setUnknown(event.target.checked)}/>我已核对未知调用，并确认再次调用的风险</label></>:null}{error?<p role="alert">{error}</p>:null}
  </Dialog>
  <Dialog open={discard} title="放弃未保存写作输入" onClose={()=>setDiscard(false)} footer={<><Button data-interaction-id="cloud:draft:keep" onClick={()=>setDiscard(false)}>保留输入</Button><Button data-interaction-id="cloud:draft:discard" variant="danger" onClick={()=>{setDiscard(false);void action(reload);}}>放弃输入并重新加载</Button></>}><p>当前输入尚未保存，重新加载会读取云端版本。</p></Dialog>
 </section>;
}
