import {useEffect,useRef,useState} from 'react';
import type {Graph} from '../../domain/graph';
import type {CloudAgentConversation,CloudAgentProposal,CloudAgentPreview,CloudAgentRun} from '../../domain/cloud-agent';
import {workspaceMessage,type WorkspaceClient} from '../../infrastructure/api/workspace-client';
import {ApiError} from '../../infrastructure/api/client';
import {useCloudDraftGuard} from './use-cloud-draft-guard';
import {cloudTaskStatus} from './CloudTasksPage';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
export function CloudAgentPanel({client,graph,selected,saved,onApplied}:{client:WorkspaceClient;graph:Graph;selected:string[];saved:boolean;onApplied:()=>void}){
 const [conversations,setConversations]=useState<CloudAgentConversation[]>([]),[conversation,setConversation]=useState<CloudAgentConversation>(),[title,setTitle]=useState('创作会话'),[body,setBody]=useState(''),[scope,setScope]=useState<'selection'|'project'>('project'),[grantOpen,setGrantOpen]=useState(false),[preview,setPreview]=useState<CloudAgentPreview>(),[fee,setFee]=useState(false),[unknown,setUnknown]=useState(false),[proposals,setProposals]=useState<CloudAgentProposal[]>([]),[runs,setRuns]=useState<CloudAgentRun[]>([]),[review,setReview]=useState<CloudAgentProposal>(),[operationIds,setOperationIds]=useState<string[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const alive=useRef(true),current=useRef(conversation),reading=useRef(false),epoch=useRef(0),newAttempt=useRef<{key:string;title:string}|undefined>(undefined),noteAttempt=useRef<{key:string;body:string;revision:number;context:CloudAgentConversation['notes'][number]['context']}|undefined>(undefined);current.current=conversation;
 useCloudDraftGuard(!!body,()=>setError('Agent 描述尚未保存，请先保存描述后再离开。'));
 function accept(value:CloudAgentConversation){if(alive.current){setConversation(value);setConversations(rows=>[value,...rows.filter(row=>row.id!==value.id)]);}}
 async function reload(){if(reading.current)return;reading.current=true;const version=epoch.current,id=current.current?.id;try{const rows=await client.listAgentConversations(graph.projectId),chosen=id?rows.find(row=>row.id===id):rows[0];const [suggestions,tasks]=chosen?await Promise.all([client.listAgentProposals(chosen.id),client.listTasks()]):[[],[]];if(alive.current&&version===epoch.current){setConversations(rows);setConversation(previous=>!previous?chosen:chosen&&chosen.id===previous.id&&chosen.revision>=previous.revision?chosen:previous);if(!current.current||current.current.id===chosen?.id){setProposals(suggestions);setRuns(tasks.filter((task):task is CloudAgentRun=>task.kind==='agent-advice'&&task.conversationId===chosen?.id));}}}catch(e){if(alive.current&&version===epoch.current)setError(workspaceMessage(e));}finally{reading.current=false;}}
 useEffect(()=>{alive.current=true;void reload();const timer=setInterval(()=>{void reload();},1500);return()=>{alive.current=false;clearInterval(timer);};},[client,graph.projectId]);
 async function action(work:()=>Promise<void>){if(busy)return;epoch.current++;setBusy(true);setError('');setMessage('');try{await work();}catch(e){if(alive.current)setError(workspaceMessage(e));}finally{if(alive.current)setBusy(false);}}
 async function create(){if(body){setError('请先保存当前描述，再新建会话。');return;}await action(async()=>{newAttempt.current??={key:crypto.randomUUID(),title:title.trim()};const attempt=newAttempt.current;try{accept(await client.createAgentConversation(graph.projectId,attempt.title,attempt.key));newAttempt.current=undefined;}catch(error){if(error instanceof ApiError&&['INVALID_REQUEST','TITLE_INVALID'].includes(error.code))newAttempt.current=undefined;throw error;}setProposals([]);setRuns([]);});}
 async function saveNote(){if(!conversation||!body.trim()||!saved)return;await action(async()=>{noteAttempt.current??={key:crypto.randomUUID(),body,revision:conversation.revision,context:{scope,nodeIds:scope==='project'?[]:[...selected],revision:graph.revision}};const attempt=noteAttempt.current;if(attempt.body!==body)throw Error('pending_note_save');try{const value=await client.saveAgentNote(conversation.id,attempt.revision,attempt.body,attempt.context,attempt.key);accept(value);noteAttempt.current=undefined;if(alive.current){setBody('');setMessage('描述已保存');}}catch(error){if(error instanceof ApiError&&['REVISION_CONFLICT','AGENT_SCOPE_INVALID','INVALID_REQUEST'].includes(error.code))noteAttempt.current=undefined;throw error;}});}
 async function authorize(){if(!conversation)return;await action(async()=>{const value=await client.grantAgent(conversation.id,conversation.revision,{scope,nodeIds:scope==='project'?[]:selected,access:'propose'});accept(value);if(alive.current){setGrantOpen(false);setMessage('范围授权已保存，有效期 10 分钟');}});}
 async function prepare(){if(!conversation||!saved)return;const description=body.trim()?body:conversation.notes.at(-1)?.body;if(!description)return;await action(async()=>{const {configs}=await client.modelConfigs(),config=configs.find(value=>value.channel==='text'&&value.hasKey);if(!config)throw new ApiError(422,'MODEL_CONFIG_REQUIRED');const value=await client.agentPreview(conversation.id,conversation.revision,graph.revision,config.revision,description);if(alive.current){setPreview(value);setFee(false);setUnknown(false);}});}
 async function confirm(){if(!preview||!fee||preview.priorUnknownRunIds.length&&!unknown)return;await action(async()=>{const task=await client.confirmAgent(preview.conversationId,preview.id,unknown);if(alive.current){setRuns(rows=>[task,...rows.filter(row=>row.id!==task.id)]);setPreview(undefined);setBody('');setMessage('建议请求已保存，结果会保留在云端');}});}
 async function decide(decision:'apply'|'reject'){if(!review)return;await action(async()=>{const value=await client.decideAgentProposal(review.id,review.revision,decision,decision==='apply'?operationIds:[]);if(alive.current){setProposals(rows=>rows.map(row=>row.id===value.id?value:row));setReview(undefined);setMessage(decision==='apply'?'选中修改已保存到画布':'提案拒绝记录已保存');if(decision==='apply')onApplied();}});}
 const activeGrant=!!conversation?.grant&&conversation.grant.access==='propose'&&conversation.grant.expiresAt>Date.now(),readonly=!!conversation?.historical;
 return <section className="card" aria-label="云端 Agent"><h2>云端 Agent</h2><p>使用当前账号的文字模型提出整理建议。建议和审阅记录保存在云端，生成视频需要另行确认。</p><label>新会话名称<input data-interaction-id="cloud:agent:title" value={title} disabled={busy||!!newAttempt.current} onChange={event=>setTitle(event.target.value)}/></label><div className="actions"><Button data-interaction-id="cloud:agent:new" disabled={busy||!title.trim()} onClick={create}>新建 Agent 会话</Button><Button data-interaction-id="cloud:agent:reload" disabled={busy} onClick={reload}>重新加载 Agent 记录</Button></div>
  <label>Agent 会话<select aria-label="Agent 会话" data-interaction-id="cloud:agent:conversation" value={conversation?.id??''} disabled={busy} onChange={event=>{if(body){setError('请先保存当前描述，再切换会话。');return;}epoch.current++;setConversation(conversations.find(row=>row.id===event.target.value));setProposals([]);setRuns([]);setError('');}}><option value="">请选择</option>{conversations.map(row=><option key={row.id} value={row.id}>{row.title}{row.historical?' · 只读历史':''}</option>)}</select></label>
  {conversation?<><p>{readonly?'导入的只读会话历史':activeGrant?'已授权范围内的建议，有效至 '+new Date(conversation.grant!.expiresAt).toLocaleTimeString():'尚未授权模型读取画布并提出建议'}</p><label>Agent 任务描述<textarea aria-label="Agent 任务描述" data-interaction-id="cloud:agent:body" disabled={busy||readonly||!!noteAttempt.current} value={body} onChange={event=>setBody(event.target.value)}/></label><label>Agent 读取范围<select data-interaction-id="cloud:agent:scope" value={scope} disabled={busy||readonly||!!noteAttempt.current} onChange={event=>setScope(event.target.value as typeof scope)}><option value="project">当前项目的节点</option><option value="selection">当前选中的节点</option></select></label><p>{scope==='project'?graph.nodes.length:selected.length} 个节点；只发送节点名称、类型、位置和文字，不上传素材原件。</p>
   <div className="actions"><Button data-interaction-id="cloud:agent:save-note" disabled={busy||readonly||!saved||!body.trim()} onClick={saveNote}>保存 Agent 描述</Button><Button data-interaction-id="cloud:agent:grant" disabled={busy||readonly||!saved||scope==='selection'&&!selected.length} onClick={()=>setGrantOpen(true)}>授权所选范围提出建议</Button><Button data-interaction-id="cloud:agent:revoke" disabled={busy||readonly||!conversation.grant} onClick={()=>action(async()=>{accept(await client.revokeAgent(conversation.id,conversation.revision));setMessage('范围授权已撤销，已发送请求仍可能产生费用');})}>撤销 Agent 授权</Button><Button data-interaction-id="cloud:agent:preview" disabled={busy||readonly||!saved||!activeGrant||!body.trim()&&!conversation.notes.length} onClick={prepare}>预览 Agent 建议请求</Button></div>
   <h3>描述历史</h3>{conversation.notes.map(note=><article key={note.id}><p>画布修订 {note.context.revision} · {new Date(note.createdAt).toLocaleString()}</p><pre>{note.body}</pre></article>)}
   <h3>模型建议与任务</h3>{runs.map(run=><article key={run.id}><p>{cloudTaskStatus(run)}</p>{run.message?<pre>{run.message}</pre>:null}{run.executionState==='response_unknown'?<p>调用结果未知，可能已经收费；不会自动再次发送。</p>:null}</article>)}<h3>提案与审阅记录</h3>{proposals.map(proposal=><article key={proposal.id}><p>{proposal.status==='proposed'?'待审阅':proposal.status==='applied'?'已应用':proposal.status==='rejected'?'已拒绝':'版本冲突'} · 画布修订 {proposal.baseRevision} · {proposal.operations.length} 项操作</p><p>{proposal.message}</p><Button data-interaction-id="cloud:agent:review" disabled={busy} onClick={()=>{setReview(proposal);setOperationIds([]);}}>审阅 Agent 提案</Button>{proposal.decisions.map((decision,index)=><p key={index}>{decision.decision==='applied'?'接受':'拒绝'} · {decision.operationIds.length} 项 · {new Date(decision.createdAt).toLocaleString()}</p>)}</article>)}</>:null}
  {error?<p role="alert">{error}</p>:null}{message?<p role="status">{message}</p>:null}
  <Dialog open={grantOpen} title="确认 Agent 范围授权" dismissible={!busy} onClose={()=>setGrantOpen(false)} footer={<><Button data-interaction-id="cloud:agent:grant-cancel" disabled={busy} onClick={()=>setGrantOpen(false)}>取消</Button><Button data-interaction-id="cloud:agent:grant-confirm" busy={busy} onClick={authorize}>确认范围授权</Button></>}><p>允许当前会话基于{scope==='project'?'当前项目的节点':'当前选中的节点'}提出文字或位置修改建议，有效期 10 分钟。每次模型请求另行确认费用，每项画布修改仍需审阅。</p><p>节点：{graph.nodes.filter(node=>scope==='project'||selected.includes(node.id)).map(node=>node.title).join('、')}</p></Dialog>
  <Dialog open={!!preview} title="确认 Agent 文字调用" dismissible={!busy} onClose={()=>setPreview(undefined)} footer={<><Button data-interaction-id="cloud:agent:call-cancel" disabled={busy} onClick={()=>setPreview(undefined)}>取消</Button><Button data-interaction-id="cloud:agent:call-confirm" variant="primary" busy={busy} disabled={!fee||!!preview?.priorUnknownRunIds.length&&!unknown} onClick={confirm}>确认调用并保存建议</Button></>}><p>模型：{preview?.model} · API：{preview?.apiBase}</p><pre>{preview?.inputSnapshot.description}</pre>{preview?.inputSnapshot.nodes.map(node=><article key={node.id}><h3>{node.title}</h3>{node.text?<pre>{node.text}</pre>:<p>仅发送类型和位置。</p>}</article>)}<label><input type="checkbox" data-interaction-id="cloud:agent:fee" checked={fee} disabled={busy} onChange={event=>setFee(event.target.checked)}/>我确认本次 Agent 文字调用可能收费</label>{preview?.priorUnknownRunIds.length?<label><input type="checkbox" data-interaction-id="cloud:agent:unknown" checked={unknown} disabled={busy} onChange={event=>setUnknown(event.target.checked)}/>我已核对未知调用，并确认再次调用的风险</label>:null}{error?<p role="alert">{error}</p>:null}</Dialog>
  <Dialog open={!!review} title="云端 Agent 提案审阅" width={960} dismissible={!busy} onClose={()=>setReview(undefined)} footer={<><Button data-interaction-id="cloud:agent:reject" disabled={busy||review?.status!=='proposed'||!!review?.historical} onClick={()=>decide('reject')}>拒绝 Agent 提案</Button><Button data-interaction-id="cloud:agent:apply" variant="primary" busy={busy} disabled={!saved||!activeGrant||!operationIds.length||review?.status!=='proposed'||!!review?.historical} onClick={()=>decide('apply')}>应用选中的 Agent 修改</Button></>}><p>基于画布修订 {review?.baseRevision}。勾选后将作为一次可撤销的画布修改保存。</p>{review?.operations.map(operation=>{const node=graph.nodes.find(value=>value.id===operation.payload.nodeId),patch=operation.payload.patch as {title?:string;data?:{text?:string}}|undefined;return <article key={operation.id}><label><input aria-label={'选择 Agent 操作 '+operation.id} data-interaction-id="cloud:agent:operation" type="checkbox" checked={operationIds.includes(operation.id)} disabled={busy||review.status!=='proposed'||!!review.historical} onChange={event=>setOperationIds(values=>event.target.checked?[...values,operation.id]:values.filter(value=>value!==operation.id))}/>{node?.title??'原节点'} · {operation.type==='move_node'?'移动位置':'修改文字'}</label>{operation.type==='move_node'?<p>位置：({node?.x}, {node?.y}) → ({String(operation.payload.x)}, {String(operation.payload.y)})</p>:<>{patch?.title?<p>标题：{node?.title} → {patch.title}</p>:null}{patch?.data?<><p>当前正文</p><pre>{node?.type==='text'?node.data.text:''}</pre><p>提案正文</p><pre>{patch.data.text}</pre></>:null}</>}</article>;})}{error?<p role="alert">{error}</p>:null}</Dialog>
 </section>;
}
