import {useEffect,useRef,useState} from 'react';
import type {PromptDraft,PromptResultVersion} from '../../domain/prompt';
import type {Asset} from '../../domain/asset';
import {workspaceMessage,type WorkspaceClient} from '../../infrastructure/api/workspace-client';
import {PromptForm} from '../prompt-generation/PromptForm';
import {useCloudDraftGuard} from './use-cloud-draft-guard';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
import {CloudApplyPromptDialog} from './CloudApplyPromptDialog';
import type {CloudTask,CloudPromptPreview} from '../../domain/cloud-task';
import {ApiError} from '../../infrastructure/api/client';
import {cloudTaskStatus} from './CloudTasksPage';
import {CloudPromptInputSnapshot} from './CloudPromptInputSnapshot';
import {triggerLocalDownload} from '../../ui/local-download';
export function CloudPromptGeneratorPage({client,trashed=false}:{client:WorkspaceClient;trashed?:boolean}){
 const [drafts,setDrafts]=useState<PromptDraft[]>([]),[draft,setDraft]=useState<PromptDraft>(),[saved,setSaved]=useState<PromptDraft>(),[assets,setAssets]=useState<Asset[]>([]);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[snapshot,setSnapshot]=useState<PromptDraft>(),[discard,setDiscard]=useState(false),[draftSelectEpoch,setDraftSelectEpoch]=useState(0);
 const [selectedId,setSelectedId]=useState<string>(),[centerText,setCenterText]=useState(''),[versionInput,setVersionInput]=useState<PromptDraft>(),[inputFailed,setInputFailed]=useState(false),[inspector,setInspector]=useState(true),[library,setLibrary]=useState<{title:string;source:string}>(),[libraryKey,setLibraryKey]=useState(''),[applying,setApplying]=useState<PromptResultVersion>(),[applyingMode,setApplyingMode]=useState<'text'|'video'|'flow'>('text');
 const [preview,setPreview]=useState<CloudPromptPreview>(),[fee,setFee]=useState(false),[unknown,setUnknown]=useState(false),[task,setTask]=useState<CloudTask>();
 const alive=useRef(true),composing=useRef(false),creation=useRef<string|undefined>(undefined),touched=useRef(false),wanted=useRef(typeof window==='undefined'?undefined:new URLSearchParams(window.location.search).get('draft')??undefined);
 const dirty=!!draft&&JSON.stringify(draft)!==JSON.stringify(saved);
 const versions=draft?.resultVersions??[],selected=versions.find(version=>version.id===selectedId)??versions[versions.length-1],manualDirty=!!selected&&centerText!==selected.finalPrompt;
 useCloudDraftGuard(dirty||manualDirty,()=>setError('写作草稿有未保存输入，请先保存或明确放弃后再离开。'));
 const accept=(value:PromptDraft)=>{if(alive.current){setDraft(value);setSaved(value);setDrafts(rows=>[value,...rows.filter(row=>row.id!==value.id)]);}};
 const pickDraft=(rows:PromptDraft[])=>{if(!wanted.current)return rows[0];const target=rows.find(row=>row.id===wanted.current);if(!target){setError('指定的写作草稿不存在或不属于当前账号；请从草稿列表重新选择，本页不会自动改用其他草稿。');return undefined;}return target;};
 const selectNewest=(value:PromptDraft)=>{const latest=value.resultVersions[value.resultVersions.length-1];if(latest){setSelectedId(latest.id);setCenterText(latest.finalPrompt);}};
 async function reload(){const rows=await client.listDrafts(trashed);if(alive.current){setDrafts(rows);const current=rows.find(row=>row.id===draft?.id)??pickDraft(rows),latest=current?.resultVersions[current.resultVersions.length-1];setDraft(current);setSaved(current);setSelectedId(latest?.id);setCenterText(latest?.finalPrompt??'');}}
 useEffect(()=>{let active=true;alive.current=true;void Promise.all([client.listDrafts(trashed),client.listAssets()]).then(([rows,media])=>{if(!active)return;setDrafts(rows);setAssets(media);if(touched.current)return;const current=pickDraft(rows);setDraft(current);setSaved(current);}).catch(e=>{if(active)setError(workspaceMessage(e));});return()=>{active=false;alive.current=false;};},[client,trashed]);
 useEffect(()=>{let active=true;setTask(undefined);if(draft&&!trashed)void client.listTasks().then(rows=>{if(active)setTask(rows.filter((row):row is CloudTask=>row.kind==='prompt-optimize').find(row=>row.draftId===draft.id&&!row.historical));}).catch(e=>{if(active)setError(workspaceMessage(e));});return()=>{active=false;};},[client,draft?.id,trashed]);
 useEffect(()=>{if(!task||!['persisted','sending','response_received'].includes(task.executionState))return;let active=true,reading=false;const timer=setInterval(()=>{if(reading)return;reading=true;void client.readTask(task.id).then(current=>{if(active&&current.kind==='prompt-optimize')setTask(current);}).catch(e=>{if(active)setError(workspaceMessage(e));}).finally(()=>{reading=false;});},1000);return()=>{active=false;clearInterval(timer);};},[client,task?.id,task?.executionState]);
 useEffect(()=>{if(!task||!draft||task.draftId!==draft.id||task.executionState!=='succeeded'||draft.resultVersions.some(version=>version.id===task.resultVersionId))return;if(dirty){setMessage('AI 结果已保存。当前输入尚未保存，请先保存或明确放弃改动，再重新加载结果；本次改动不会被覆盖。');return;}let active=true;void client.readDraft(task.draftId).then(value=>{if(!active)return;if(manualDirty){setDraft(value);setSaved(value);setMessage('AI 结果已保存。中央正文有未保存修改：请先保存为新的人工结果或明确放弃，再切换到该结果；正文不会被覆盖。');return;}accept(value);selectNewest(value);setMessage('AI 结果已保存');}).catch(e=>{if(active)setError(workspaceMessage(e));});return()=>{active=false;};},[client,task?.id,task?.executionState,task?.resultVersionId,draft?.id,draft?.revision,dirty,manualDirty]);
 useEffect(()=>{if(!draft)return;const current=draft.resultVersions[draft.resultVersions.length-1];if(!current)return;if(selectedId===undefined||!draft.resultVersions.some(version=>version.id===selectedId)){setSelectedId(current.id);setCenterText(current.finalPrompt);}},[draft?.id,draft?.resultVersions.length,selectedId]);
 useEffect(()=>{setVersionInput(undefined);setInputFailed(false);if(!draft||!selected)return;let active=true;void client.draftRevision(draft.id,selected.sourceRevision).then(value=>{if(active)setVersionInput(value);}).catch(()=>{if(active)setInputFailed(true);});return()=>{active=false;};},[client,draft?.id,selected?.id]);
 async function action(work:()=>Promise<void>){if(busy||composing.current)return;setBusy(true);setError('');setMessage('');try{await work();}catch(e){if(alive.current)setError(workspaceMessage(e));}finally{if(alive.current)setBusy(false);}}
 async function create(){if(dirty||manualDirty){setError('请先保存当前草稿与正文修改，再新建草稿。');return;}await action(async()=>{creation.current??=crypto.randomUUID();const value=await client.createDraft({type:'video',userRequest:'',sceneId:'text',requestedSpec:{},audioPlan:'',lockedConstraints:[],references:[],ruleVersion:'studio-video-rules-v1'},creation.current);creation.current=undefined;accept(value);touched.current=true;setMessage('草稿已保存');});}
 async function save(){if(!draft||!saved)return;await action(async()=>{const {id:_,revision:__,resultVersions:___,...fields}=draft;void _;void __;void ___;const value=await client.patchDraft(draft.id,saved.revision,fields);accept(value);setMessage('草稿已保存');});}
 async function compile(){if(!draft||dirty||manualDirty)return;await action(async()=>{const value=await client.compileDraft(draft.id,draft.revision);accept(value);selectNewest(value);setMessage('规则整理结果已保存');});}
 async function saveManual(){if(!draft||!selected||!manualDirty||!centerText.trim())return;await action(async()=>{const {shotPlan,improvements,warnings,suggestedSpec}=selected,value=await client.appendDraftResult(draft.id,draft.revision,{finalPrompt:centerText,shotPlan,improvements,warnings,suggestedSpec});accept(value);selectNewest(value);setMessage('人工结果已保存为新版本；AI 原结果保留');});}
 async function copyResult(){try{await navigator.clipboard.writeText(centerText);setMessage('已复制正文');}catch{setMessage('剪贴板权限被拒绝，请选中正文手动复制。');}}
 function exportResult(){if(!draft||!selected||manualDirty||!versionInput)return;try{triggerLocalDownload(new Blob([JSON.stringify({format:'aiwork-studio-prompt-result',schemaVersion:1,draftId:draft.id,resultVersionId:selected.id,sourceRevision:selected.sourceRevision,origin:selected.origin,validationState:selected.validationState,finalPrompt:selected.finalPrompt,shotPlan:selected.shotPlan,improvements:selected.improvements,warnings:selected.warnings,suggestedSpec:selected.suggestedSpec,source:{userRequest:versionInput.userRequest,sceneId:versionInput.sceneId,requestedSpec:versionInput.requestedSpec,audioPlan:versionInput.audioPlan,lockedConstraints:versionInput.lockedConstraints,references:versionInput.references}},null,2)],{type:'application/json'}),'AIWORK-写作结果.json');setMessage('已触发浏览器下载：AIWORK-写作结果.json');}catch{setError('导出失败：浏览器限制或结果超过限制；正文仍保留。');}}
 function openLibrary(){if(!draft||!selected||manualDirty||!versionInput)return;setLibrary({title:versionInput.userRequest.slice(0,40)||'写作结果',source:'写作结果 · 草稿 '+draft.id.slice(0,8)});setLibraryKey(current=>current||crypto.randomUUID());}
 async function saveLibrary(){if(!draft||!selected||!library||manualDirty||!versionInput)return;await action(async()=>{const entry=await client.createPrompt({title:library.title.trim()||'写作结果',body:selected.finalPrompt,tags:[],variables:[],source:library.source.trim()||'写作结果',license:'用户填写的来源与许可尚未核验',starred:false,draftId:draft.id,resultVersionId:selected.id},libraryKey||crypto.randomUUID());setLibraryKey('');if(alive.current){setLibrary(undefined);setMessage('已保存到提示词库 · 条目 '+entry.title);}});}
 async function prepareAI(){if(!draft||dirty)return;await action(async()=>{const {configs}=await client.modelConfigs(),config=configs.find(value=>value.channel==='text'&&value.hasKey);if(!config)throw new ApiError(422,'MODEL_CONFIG_REQUIRED');const value=await client.optimizationPreview(draft.id,draft.revision,config.revision,draft.references.map(reference=>reference.alias));if(alive.current){setPreview(value);setFee(false);setUnknown(false);}});}
 async function confirmAI(){if(!preview||!fee||preview.priorUnknownRunIds.length&&!unknown)return;await action(async()=>{const value=await client.optimizeDraft(preview.draftId,preview.id,unknown);if(alive.current){setTask(value);setPreview(undefined);setMessage('任务已保存，可在任务中心继续查看');}});}
 function openApply(version:PromptResultVersion,mode:'text'|'video'|'flow'){setApplyingMode(mode);setApplying(version);}
 if(trashed)return <section className="card"><h1>写作草稿回收站</h1>{error?<p role="alert">{error}</p>:null}{drafts.length?drafts.map(row=><article key={row.id}><h2>{row.userRequest.slice(0,60)||'未命名草稿'}</h2><Button data-interaction-id="cloud:draft:restore" disabled={busy} onClick={()=>action(async()=>{await client.restoreDraft(row.id,row.revision);await reload();})}>恢复写作草稿</Button></article>):<p>回收站没有写作草稿</p>}</section>;
 return <section className="card"><div className="actions"><h1>视频提示词写作</h1><Button data-interaction-id="cloud:draft:new" busy={busy} onClick={create}>新建视频写作草稿</Button><Button data-interaction-id="cloud:draft:reload" disabled={busy} onClick={()=>dirty||manualDirty?setDiscard(true):action(reload)}>重新加载写作草稿</Button></div>
  {error?<p role="alert" className="banner error">{error}</p>:null}<p role="status">{message||(!draft?'尚未选择草稿':dirty?'输入尚未保存':'草稿已保存 · 修订 '+draft.revision)}</p>
  {manualDirty?<p data-interaction-id="cloud:draft:manual-guard" className="banner warning">中央正文有未保存修改：保存为新的人工结果或明确放弃后，才能规则整理、切换草稿或加载迟到结果；原 AI 结果不受影响。</p>:null}
  <label>选择写作草稿<select key={draftSelectEpoch} aria-label="选择写作草稿" data-interaction-id="cloud:draft:select" value={draft?.id??''} disabled={busy} onChange={event=>{if(dirty||manualDirty){setError('请先保存当前草稿与中央正文修改，再切换草稿。');setDraftSelectEpoch(value=>value+1);return;}const next=drafts.find(row=>row.id===event.target.value);touched.current=true;setDraft(next);setSaved(next);setSelectedId(next?.resultVersions[next.resultVersions.length-1]?.id);setCenterText(next?.resultVersions[next.resultVersions.length-1]?.finalPrompt??'');setMessage('');}}><option value="">请选择</option>{drafts.map(row=><option key={row.id} value={row.id}>{row.userRequest.slice(0,40)||'未命名草稿'} · 修订 {row.revision}</option>)}</select></label>
  {draft?<><div className="cloud-prompt-workspace"><section className="cloud-prompt-pane pane-input" aria-label="写作输入"><h2>写作输入</h2><fieldset disabled={busy}><legend>写作输入</legend><PromptForm storage="cloud" draft={draft} assets={assets} availableIds={new Set(assets.map(asset=>asset.id))} onChange={patch=>{setDraft(current=>current?{...current,...patch}:current);setMessage('');}} onComposing={value=>{composing.current=value;}} contextTexts={[]} onChooseLibrary={async()=>{try{const media=await client.listAssets();if(alive.current){setAssets(media);setMessage('云端素材已重新加载');}}catch(e){if(alive.current)setError(workspaceMessage(e));}}}/></fieldset>
   <div className="actions"><Button data-interaction-id="cloud:draft:save" variant="primary" busy={busy} onClick={save}>保存写作草稿</Button><Button data-interaction-id="cloud:draft:compile" disabled={busy||dirty||manualDirty||!draft.userRequest.trim()} disabledReason={manualDirty?'中央正文有未保存修改：请先保存为新的人工结果或明确放弃，再规则整理。':dirty?'请先保存写作输入，再规则整理。':undefined} onClick={compile}>规则整理</Button><Button data-interaction-id="cloud:draft:ai-preview" disabled={busy||dirty||!draft.userRequest.trim()||!!task&&['persisted','sending','response_received'].includes(task.executionState)} onClick={prepareAI}>AI 优化</Button><Button data-interaction-id="cloud:draft:trash" disabled={busy||dirty||manualDirty} onClick={()=>action(async()=>{await client.trashDraft(draft.id,draft.revision);await reload();})}>移入写作草稿回收站</Button></div>{task?<p>{cloudTaskStatus(task)}{task.billingState==='pending_reconciliation'?' · 积分仍在核对，尚未确认最终扣费。':''}</p>:null}</section>
<section className="cloud-prompt-pane pane-result" aria-label="写作结果">
<h2>写作结果</h2>
{selected?<>
<p data-interaction-id="cloud:draft:result-origin">{selected.origin==='local'?'规则整理':selected.origin==='ai'?'AI 优化':selected.origin==='manual'?'人工修订':'历史结果'} · 输入修订 {selected.sourceRevision} · {selected.validationState==='valid'?'规则检查通过':'结果待检查'}</p>
<label>结果正文<textarea aria-label="结果正文" data-interaction-id="cloud:draft:result-text" disabled={busy} value={centerText} onChange={event=>{setCenterText(event.target.value);setMessage('');}}/></label>
{manualDirty?<p data-interaction-id="cloud:draft:result-dirty">正文已人工修改；保存会新增人工版本，AI 原结果保持不变。</p>:null}
<div className="actions">
<Button data-interaction-id="cloud:draft:manual-save" variant="primary" busy={busy} disabled={busy||dirty||!manualDirty||!centerText.trim()} disabledReason={dirty?'请先保存写作输入，再保存正文修改。':undefined} onClick={saveManual}>保存为新的人工结果</Button>
<Button data-interaction-id="cloud:draft:result-revert" disabled={busy||!manualDirty} onClick={()=>setCenterText(selected.finalPrompt)}>放弃正文修改</Button>
<Button data-interaction-id="cloud:draft:copy" disabled={!centerText.trim()} onClick={()=>void copyResult()}>复制正文</Button>
<Button data-interaction-id="cloud:draft:save-library" disabled={busy||dirty||manualDirty||!versionInput} disabledReason={manualDirty?'中央正文有未保存修改：请先保存为新的人工结果，再保存到提示词库，避免正文与版本来源不一致。':!versionInput?'正在读取该结果版本的不可变输入，暂不能用当前草稿代替。':undefined} onClick={openLibrary}>保存到提示词库</Button>
<Button data-interaction-id="cloud:draft:export-json" disabled={busy||manualDirty||!versionInput} disabledReason={manualDirty?'中央正文有未保存修改：请先保存为新的人工结果，再导出，避免正文与版本来源不一致。':!versionInput?'正在读取该结果版本的不可变输入，暂不能用当前草稿代替。':undefined} onClick={exportResult}>导出 JSON</Button>
<Button data-interaction-id="cloud:draft:restore-result" disabled={busy||dirty||manualDirty} onClick={()=>action(async()=>{const value=await client.restoreDraftResult(draft.id,draft.revision,selected.id);accept(value);selectNewest(value);setMessage('历史结果已恢复为新的人工版本');})}>恢复此历史结果</Button>
<Button data-interaction-id="cloud:draft:apply" disabled={busy||dirty||manualDirty} onClick={()=>openApply(selected,'text')}>插入文字</Button>
<Button data-interaction-id="cloud:draft:apply-video" disabled={busy||dirty||manualDirty} onClick={()=>openApply(selected,'video')}>应用到视频草稿</Button>
<Button data-interaction-id="cloud:draft:apply-flow" disabled={busy||dirty||manualDirty} onClick={()=>openApply(selected,'flow')}>创建视频流程</Button>
</div>
<h3>镜头草案</h3>
{selected.shotPlan.length?<ol data-interaction-id="cloud:draft:shot-plan">{selected.shotPlan.map(shot=><li key={shot.id}>{shot.durationSeconds} 秒 · {shot.prompt}{shot.startState?' · 起 '+shot.startState:''}{shot.endState?' · 止 '+shot.endState:''}</li>)}</ol>:<p>尚无镜头草案；规则整理或 AI 优化后显示。</p>}
<h3>改动说明</h3>
{selected.improvements.length?<ul data-interaction-id="cloud:draft:improvements">{selected.improvements.map((item,index)=><li key={index}>{item}</li>)}</ul>:<p>尚无改动说明。</p>}
{selected.warnings.length?<ul data-interaction-id="cloud:draft:warnings">{selected.warnings.map((item,index)=><li key={index}>{item}</li>)}</ul>:null}
{manualDirty?<p className="muted">应用、恢复与保存到库前请先保存正文修改，避免丢失本次编辑。</p>:null}
</>:<p>尚无结果版本；先保存写作草稿，再规则整理或 AI 优化。</p>}
</section>
<aside className={'cloud-prompt-pane pane-inspector'+(inspector?'':' pane-collapsed')} aria-label="写作检查">
<div className="actions"><Button data-interaction-id="cloud:draft:inspector-toggle" onClick={()=>setInspector(value=>!value)}>{inspector?'收起检查':'展开检查'}</Button><Button data-interaction-id="cloud:draft:input-snapshot" disabled={busy||!selected} onClick={()=>action(async()=>{if(!draft||!selected)return;const input=await client.draftRevision(draft.id,selected.sourceRevision);if(alive.current)setSnapshot(input);})}>查看输入快照</Button></div>
{selected?<><h3>源参数对照</h3><p>结果输入修订 {selected.sourceRevision} · 当前草稿修订 {draft.revision} · 规则 {versionInput?.ruleVersion??(inputFailed?'读取失败':'读取中')}</p>{versionInput?<CloudPromptInputSnapshot input={versionInput}/>:<p data-interaction-id="cloud:draft:input-state">{inputFailed?'无法读取该结果版本对应的输入快照；不使用当前草稿替代。':'正在读取该结果版本对应的输入快照…'}</p>}<p>结果建议规格：{selected.suggestedSpec.durationSeconds===undefined?'未指定':selected.suggestedSpec.durationSeconds+' 秒'} · {selected.suggestedSpec.ratio??'未指定'}</p></>:<p>尚无结果版本；先规则整理或 AI 优化。</p>}
   <p>规则整理根据当前输入编写候选文字；结果不会自动应用到画布或执行视频。</p><h2>结果历史</h2>{draft.resultVersions.length?[...draft.resultVersions].reverse().map(version=><article key={version.id} className="card">
<label className="cloud-result-version"><input type="radio" name={'result-version-'+draft.id} value={version.id} data-interaction-id="cloud:draft:version" checked={selected?.id===version.id} onChange={()=>{setSelectedId(version.id);setCenterText(version.finalPrompt);}} disabled={manualDirty}/>选择此结果版本{manualDirty?'（先保存或放弃正文修改后可切换）':''}</label><h3>{version.origin==='local'?'规则整理':version.origin==='ai'?'AI 优化':'人工修订'} · 输入修订 {version.sourceRevision}</h3><p>{version.validationState==='valid'?'规则检查通过':'结果待检查'}</p><pre aria-label="历史版本正文">{version.finalPrompt}</pre>{version.warnings.map((warning,index)=><p key={index}>{warning}</p>)}</article>):<p>尚无结果版本</p>}
  </aside></div></>:<p>新建草稿后开始写作。</p>}
  <Dialog open={!!library} title="保存到提示词库" dismissible={!busy} onClose={()=>{setLibrary(undefined);setLibraryKey('');}} footer={<>
<Button data-interaction-id="cloud:draft:library-cancel" disabled={busy} onClick={()=>{setLibrary(undefined);setLibraryKey('');}}>取消</Button>
<Button data-interaction-id="cloud:draft:library-save" variant="primary" busy={busy} disabled={!library?.title.trim()||!centerText.trim()} onClick={saveLibrary}>保存到提示词库</Button>
</>}>
<p>保存当前正文与该结果版本的来源；保留写作草稿与结果版本编号，便于回查。</p>
<label>提示词名称<input data-interaction-id="cloud:draft:library-title" disabled={busy} value={library?.title??''} onChange={event=>setLibrary(current=>current?{...current,title:event.target.value}:current)}/></label>
<label>提示词来源<input data-interaction-id="cloud:draft:library-source" disabled={busy} value={library?.source??''} onChange={event=>setLibrary(current=>current?{...current,source:event.target.value}:current)}/></label>
<p>草稿 {draft?.id} · 结果版本 {selected?.id}</p>
{error?<p role="alert">{error}</p>:null}
</Dialog>
  <Dialog open={!!snapshot} title="历史输入快照" onClose={()=>setSnapshot(undefined)}><p>输入修订 {snapshot?.revision} · 规则 {snapshot?.ruleVersion}</p>{snapshot?<CloudPromptInputSnapshot input={snapshot}/>:null}</Dialog>
  
  
  {draft&&applying?<CloudApplyPromptDialog client={client} draft={draft} version={applying} initialMode={applyingMode} onClose={()=>setApplying(undefined)} onApplied={revision=>{setApplying(undefined);setMessage('写作结果已应用到云端画布 · 修订 '+revision);}}/>:null}
  <Dialog open={!!preview} title="确认 AI 文字优化" dismissible={!busy} onClose={()=>setPreview(undefined)} footer={<><Button data-interaction-id="cloud:draft:ai-cancel" disabled={busy} onClick={()=>setPreview(undefined)}>取消</Button><Button data-interaction-id="cloud:draft:ai-confirm" variant="primary" busy={busy} disabled={!fee||!!preview?.priorUnknownRunIds.length&&!unknown} onClick={confirmAI}>确认调用文字模型</Button></>}>
   <p>模型：{preview?.model}</p><p>地址：{preview?.apiBase} · 输入修订 {preview?.draftRevision} · 配置修订 {preview?.configRevision}</p><p>仅发送写作文字和已选择素材的描述，图片和视频原件不会上传。</p><p>参考别名：{preview?.referenceAliases.join('、')||'无'}</p><label><input data-interaction-id="cloud:draft:ai-fee" type="checkbox" disabled={busy} checked={fee} onChange={event=>setFee(event.target.checked)}/>我确认此文字调用可能收费</label>{preview?.priorUnknownRunIds.length?<><p>此前有 {preview.priorUnknownRunIds.length} 次调用结果未知，可能已经执行或扣费。</p><label><input data-interaction-id="cloud:draft:ai-unknown" type="checkbox" disabled={busy} checked={unknown} onChange={event=>setUnknown(event.target.checked)}/>我已核对未知调用，并确认再次调用的风险</label></>:null}{error?<p role="alert">{error}</p>:null}
  </Dialog>
  <Dialog open={discard} title="放弃未保存写作输入" onClose={()=>setDiscard(false)} footer={<><Button data-interaction-id="cloud:draft:keep" onClick={()=>setDiscard(false)}>保留输入</Button><Button data-interaction-id="cloud:draft:discard" variant="danger" onClick={()=>{setDiscard(false);void action(reload);}}>放弃输入并重新加载</Button></>}><p>当前输入或中央正文修改尚未保存，重新加载会读取云端版本，未保存内容不再保留。</p></Dialog>
 </section>;
}
