import {useEffect,useRef,useState} from 'react';
import type {CloudRun} from '../../domain/cloud-video-run';
import type {Asset} from '../../domain/asset';
import type {PromptDraft} from '../../domain/prompt';
import {workspaceMessage,type WorkspaceClient} from '../../infrastructure/api/workspace-client';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
import {LocalLink,navigate} from '../../app/routes';
import {CloudAssetMedia} from './CloudAssetsPage';
import {CloudPromptInputSnapshot} from './CloudPromptInputSnapshot';
import {CloudVideoTaskDetail,cloudVideoStatus} from './CloudVideoTaskDetail';
export const cloudTaskStatus=(task:CloudRun)=>task.kind==='video'?cloudVideoStatus(task):({persisted:'任务已保存，等待调用',sending:'模型调用中',response_received:'回复已保存，正在写入结果',succeeded:'已完成',failed_confirmed:'未发出调用',response_unknown:'调用结果未知'}[task.executionState]);
export function CloudTasksPage({client}:{client:WorkspaceClient}){
 const [tasks,setTasks]=useState<CloudRun[]>([]),[assets,setAssets]=useState<Asset[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[paused,setPaused]=useState(false),[query,setQuery]=useState(''),[details,setDetails]=useState<{task:CloudRun;input?:PromptDraft}>();
 const alive=useRef(true),reading=useRef(false);
 async function reload(){if(reading.current)return;reading.current=true;try{const rows=await client.listTasks();if(alive.current){setTasks(rows);setDetails(current=>current?{...current,task:rows.find(row=>row.id===current.task.id)??current.task}:current);setError('');}void client.listAssets().then(media=>{if(alive.current)setAssets(media);}).catch(()=>{/* Missing thumbnails stay empty; the stored result is not changed. */});}catch(e){if(alive.current)setError(workspaceMessage(e));}finally{reading.current=false;}}
 useEffect(()=>{alive.current=true;void reload();return()=>{alive.current=false;};},[client]);
 useEffect(()=>{if(paused)return;const timer=setInterval(()=>{void reload();},2000);return()=>clearInterval(timer);},[client,paused]);
 async function open(task:CloudRun){if(busy)return;setBusy(true);setError('');try{const current=await client.readTask(task.id),input=current.kind==='prompt-optimize'?await client.draftRevision(current.draftId,current.sourceRevision):undefined;if(alive.current)setDetails({task:current,input});}catch(e){if(alive.current)setError(workspaceMessage(e));}finally{if(alive.current)setBusy(false);}}
 const assetFor=(task:CloudRun)=>task.kind==='video'&&task.resultAssetId?assets.find(asset=>asset.id===task.resultAssetId):undefined;
 const videoTasks=tasks.filter((task):task is Extract<CloudRun,{kind:'video'}>=>(task.kind==='video'));
 const visible=videoTasks.filter(task=>(task.inputSnapshot.spec.modelId+' '+task.id+' '+cloudTaskStatus(task)).toLowerCase().includes(query.toLowerCase()));
 return <section className="card"><div className="actions"><h1>任务中心</h1><Button data-interaction-id="cloud:tasks:reload" disabled={busy} onClick={reload}>重新读取任务</Button><Button data-interaction-id="cloud:tasks:pause-read" onClick={()=>setPaused(value=>!value)}>{paused?'恢复状态查询':'暂停状态查询'}</Button></div><p>任务由服务器保存和执行。暂停此页面的状态查询或关闭页面后，已确认的模型调用仍可能继续。</p><p data-interaction-id="cloud:tasks:scope">任务中心只呈现视频生成任务；Agent 记录从项目会话查看，文字写作任务从提示词库的写作记录查看。原任务数据与账务记录保留。</p><label>搜索任务<input data-interaction-id="cloud:tasks:search" value={query} onChange={event=>setQuery(event.target.value)}/></label>{error?<p role="alert">{error}</p>:null}
  {visible.length?visible.map(task=><article key={task.id} className="card"><h2>视频生成 · {cloudTaskStatus(task)}</h2><p>{task.inputSnapshot.spec.modelId} · {new Date(task.createdAt).toLocaleString()}</p>{assetFor(task)?<div className="cloud-task-result" data-interaction-id="cloud:tasks:result-media"><CloudAssetMedia client={client} asset={assetFor(task)!}/></div>:task.executionState==='succeeded'?<p className="muted">结果素材尚未进入当前账号的素材库；请重新读取任务或到素材库核对。</p>:null}<p>{'historical' in task&&task.historical?'导入的只读任务历史 · 不会自动恢复调用':task.billingState==='pending_reconciliation'?'积分仍在核对，尚未确认最终扣费。':'最终账务以供应商记录为准。'}</p><Button data-interaction-id="cloud:tasks:details" disabled={busy} onClick={()=>navigate('/projects/'+encodeURIComponent(task.projectId)+'/canvas?node='+encodeURIComponent(task.nodeId)+'&runId='+encodeURIComponent(task.id))}>查看任务详情</Button><LocalLink data-interaction-id="cloud:tasks:open-results" href={'/projects/'+encodeURIComponent(task.projectId)+'/results?runId='+encodeURIComponent(task.id)}>打开视频结果</LocalLink></article>):<p>暂无匹配任务</p>}
  <Dialog open={!!details} title="云端任务详情" onClose={()=>setDetails(undefined)}>{details?<>{details.task.kind==='video'?<CloudVideoTaskDetail client={client} task={details.task} onChanged={task=>{setDetails(current=>current?{...current,task}:current);void reload();}}/>:<><p>{cloudTaskStatus(details.task)}</p><p>模型：{details.task.model} · API：{details.task.apiBase}</p><p>输入修订 {details.task.kind==='agent-advice'?details.task.inputSnapshot.revision:details.task.sourceRevision} · 配置修订 {details.task.configRevision}</p>{details.task.kind==='agent-advice'?<><h3>已确认的描述与范围</h3><pre>{details.task.inputSnapshot.description}</pre><p>节点：{details.task.inputSnapshot.nodes.map(node=>node.title).join('、')}</p>{details.task.message?<pre>{details.task.message}</pre>:null}<p>建议不会自动应用到画布，需回到原项目审阅提案。</p></>:details.input?<CloudPromptInputSnapshot input={details.input}/>:null}{details.task.executionState==='response_unknown'?<p>请求可能已经执行。请先核对供应商记录，再决定是否明确发起新的调用。</p>:null}</>}<Button data-interaction-id="cloud:tasks:details-reload" disabled={busy} onClick={()=>open(details.task)}>重新读取此任务</Button></>:null}</Dialog>
 </section>;
}
