import {randomUUID} from 'node:crypto';
import {createReadStream} from 'node:fs';
import {z} from 'zod';
import type {Pool} from 'pg';
import type {AuthContext} from '../auth/context.js';
import {transaction} from '../db/transaction.js';
import {HttpError} from '../errors.js';
import {ownedImport,importView,commitImportSchema} from './repository.js';
import {workspaceMigrationSchema,migrationFileSchema} from '../../../src/domain/workspace-migration.js';
import {graphSchema,type Graph} from '../../../src/domain/graph.js';
import {assetSchema} from '../../../src/domain/asset.js';
import {remapResources} from '../../../src/domain/resource-remap.js';
import {cloudVideoArchiveSchema} from '../../../src/domain/cloud-video-run.js';
import {projectViewSchema} from '../projects/contracts.js';
import {graphAssetIds,validateResources} from '../projects/commands.js';
import {getOrderedInputs} from '../../../src/domain/graph-validation.js';
import {parseContent,promptDraftSchema,type ContentKind} from '../prompts/contracts.js';
import {writeContent} from '../prompts/repository.js';
import {preferencesSchema} from '../users/contracts.js';
import {verifyAssetFile,writeAssetFile,removePendingFiles,type AssetStorageOptions} from '../assets/storage.js';
export async function commitImport(pool:Pool,context:AuthContext,id:string,input:z.infer<typeof commitImportSchema>,storage:AssetStorageOptions,now:Date){
 const createdFiles:string[]=[],stagedFiles:string[]=[];
 try{
  const result=await transaction(pool,async db=>{
   await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[context.userId+':asset-quota']);const batch=await ownedImport(db,context,id,true);if(batch.state==='committed')return importView(db,context,batch);
   const data=workspaceMigrationSchema.parse(batch.document),files=await db.query<{id:string;manifest:unknown;uploaded:boolean}>('SELECT id,manifest,uploaded FROM workspace_import_files WHERE user_id=$1 AND batch_id=$2 ORDER BY id FOR UPDATE',[context.userId,id]),sources=new Map<string,{id:string;path:string}>();
   for(const row of files.rows){const manifest=migrationFileSchema.parse(row.manifest);if(!row.uploaded)throw new HttpError(409,'UPLOAD_INCOMPLETE');const path=await verifyAssetFile(storage,context.userId,row.id,'original',manifest);sources.set(manifest.path,{id:row.id,path});stagedFiles.push(row.id);}
   const preference=await db.query<{revision:number;preferences:unknown}>('SELECT revision,preferences FROM user_documents WHERE user_id=$1 FOR UPDATE',[context.userId]);if(input.importPreferences&&(!data.preferences||preference.rows[0].revision!==input.expectedDocumentRevision))throw new HttpError(409,'REVISION_CONFLICT');
   const documents=data.records.map(record=>({record,value:record.document as Record<string,unknown>})),commands=documents.filter(row=>row.record.kind==='receipt-history'&&row.value.beforeGraph&&row.value.afterGraph);
   const oldGraphs=[...data.projects.map(row=>row.graph),...commands.flatMap(row=>[graphSchema.parse(row.value.beforeGraph),graphSchema.parse(row.value.afterGraph)])];
   const draftRecords=documents.filter(row=>row.record.kind==='draft'),versions=draftRecords.flatMap(row=>promptDraftSchema.parse(row.value).resultVersions);
   const maps={project:new Map(data.projects.map(row=>[row.project.id,randomUUID()])),node:new Map(oldGraphs.flatMap(graph=>graph.nodes.map(node=>[node.id,randomUUID()] as const))),asset:new Map<string,string>(),run:new Map(documents.filter(row=>row.record.kind==='video-history'||row.record.kind==='text-history').map(row=>[row.record.id,randomUUID()])),entry:new Map(documents.filter(row=>row.record.kind==='prompt').map(row=>[row.record.id,randomUUID()])),draft:new Map(draftRecords.map(row=>[row.record.id,randomUUID()])),version:new Map(versions.map(version=>[version.id,randomUUID()]))};
   const oldVersions=documents.filter(row=>row.value.kind==='prompt-draft-version').map(row=>promptDraftSchema.parse(row.value.draft));for(const version of oldVersions)for(const result of version.resultVersions)if(!maps.version.has(result.id))maps.version.set(result.id,randomUUID());
   const edges=new Map(oldGraphs.flatMap(graph=>graph.edges.map(edge=>[edge.id,randomUUID()] as const))),receipts=new Map(commands.map(row=>[row.record.id,randomUUID()]));
   const mapGraph=(input:Graph)=>{const graph=remapResources(input,maps) as Graph;const mapped=graphSchema.parse({...graph,nodes:graph.nodes.map((node,index)=>({...node,id:maps.node.get(input.nodes[index].id)!})),edges:graph.edges.map((edge,index)=>({...edge,id:edges.get(input.edges[index].id)!}))});for(const node of mapped.nodes)if(node.type==='video-generation')node.data.inputBindings=getOrderedInputs(mapped,node.id);return mapped;};
   const existing=await db.query<{id:string;document:unknown;thumbnail:unknown}>("SELECT id,document,thumbnail FROM workspace_assets WHERE user_id=$1 AND state='complete' AND trashed_at IS NULL AND document->>'sourceRunId' IS NULL FOR UPDATE",[context.userId]),byHash=new Map(existing.rows.map(row=>[assetSchema.parse(row.document).sha256,row]));
   const newAssets:typeof data.assets=[];for(const row of data.assets){const duplicate=row.asset.sourceRunId?undefined:byHash.get(row.asset.sha256);if(duplicate){const prior=assetSchema.parse(duplicate.document);if(prior.bytes!==row.asset.bytes||prior.mimeType!==row.asset.mimeType||row.thumbnail&&(!duplicate.thumbnail||migrationFileSchema.parse({...duplicate.thumbnail as object,path:'media/'+row.thumbnail.sha256+'.thumbnail'}).sha256!==row.thumbnail.sha256))throw new HttpError(409,'MIGRATION_ASSET_CONFLICT');maps.asset.set(row.asset.id,duplicate.id);}else {const newId=randomUUID();maps.asset.set(row.asset.id,newId);newAssets.push(row);if(!row.asset.sourceRunId)byHash.set(row.asset.sha256,{id:newId,document:row.asset,thumbnail:row.thumbnail});}}
   const used=await db.query<{bytes:string}>('SELECT ((SELECT COALESCE(SUM(reserved_bytes),0) FROM workspace_assets WHERE user_id=$1)+(SELECT COALESCE(SUM(reserved_bytes),0) FROM workspace_imports WHERE user_id=$1 AND id<>$2))::text AS bytes',[context.userId,id]);if(Number(used.rows[0].bytes)+newAssets.reduce((total,row)=>total+row.asset.bytes+(row.thumbnail?.bytes??0),0)>storage.userQuotaBytes)throw new HttpError(413,'USER_QUOTA_EXCEEDED');
   for(const row of data.projects){const project=projectViewSchema.parse({...row.project,id:maps.project.get(row.project.id)!,starred:row.project.starred??false,trashedAt:null}),graph=mapGraph(row.graph);await db.query('INSERT INTO workspace_projects(user_id,id,revision,document,created_at,updated_at) VALUES($1,$2,$3,$4::jsonb,$5,$6)',[context.userId,project.id,project.revision,JSON.stringify(project),new Date(project.createdAt),new Date(project.updatedAt)]);await db.query('INSERT INTO workspace_graphs(user_id,project_id,revision,graph) VALUES($1,$2,$3,$4::jsonb)',[context.userId,project.id,graph.revision,JSON.stringify(graph)]);}
   for(const row of newAssets){const id=maps.asset.get(row.asset.id)!,asset=assetSchema.parse({...remapResources(row.asset,maps) as object,id,blobKey:'asset:'+id,metadataRevision:0,trashedAt:null});createdFiles.push(id);await writeAssetFile(storage,context.userId,id,'original',row.original,createReadStream(sources.get(row.original.path)!.path));if(row.thumbnail)await writeAssetFile(storage,context.userId,id,'thumbnail',row.thumbnail,createReadStream(sources.get(row.thumbnail.path)!.path));await db.query("INSERT INTO workspace_assets(user_id,id,state,document,thumbnail,sha256,bytes,reserved_bytes,created_at) VALUES($1,$2,'complete',$3::jsonb,$4::jsonb,$5,$6,$7,$8)",[context.userId,id,JSON.stringify(asset),row.thumbnail?JSON.stringify({bytes:row.thumbnail.bytes,sha256:row.thumbnail.sha256,mimeType:row.thumbnail.mimeType}):null,asset.sha256,asset.bytes,asset.bytes+(row.thumbnail?.bytes??0),new Date(asset.createdAt)]);}
   for(const row of documents.filter(row=>row.record.kind==='video-history')){const newId=maps.run.get(row.record.id)!,mapped=remapResources(row.value,maps) as Record<string,unknown>;let task;try{task=cloudVideoArchiveSchema.parse({...mapped,id:newId,kind:'video',historical:true,recordRevision:0});}catch{throw new HttpError(409,'MIGRATION_HISTORY_INVALID');}if(!maps.project.has(String(row.value.projectId)))throw new HttpError(409,'MIGRATION_REFERENCE_INVALID');await db.query('INSERT INTO workspace_task_archives(user_id,id,project_id,source_task_id,document) VALUES($1,$2,$3,$4,$5::jsonb)',[context.userId,newId,task.projectId,newId,JSON.stringify(task)]);for(const assetId of new Set([...(task.resultAssetId?[task.resultAssetId]:[]),...task.inputSnapshot.references.map(ref=>ref.assetId)]))await db.query('INSERT INTO workspace_asset_references(user_id,project_id,asset_id,source_id) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[context.userId,task.projectId,assetId,'run:'+newId]);}
   for(const row of commands){const before=mapGraph(graphSchema.parse(row.value.beforeGraph)),after=mapGraph(graphSchema.parse(row.value.afterGraph));if(before.projectId!==after.projectId||!maps.project.has(String(row.value.projectId)))throw new HttpError(409,'MIGRATION_REFERENCE_INVALID');await db.query('INSERT INTO workspace_command_receipts(user_id,id,project_id,revision,fingerprint,before_graph,after_graph,command_type,created_at) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,\'operations\',$8)',[context.userId,receipts.get(row.record.id)!,after.projectId,after.revision,'migration-history:'+receipts.get(row.record.id),JSON.stringify(before),JSON.stringify(after),new Date(Number(row.value.createdAt))]);for(const assetId of new Set([...graphAssetIds(before),...graphAssetIds(after)]))await db.query('INSERT INTO workspace_asset_references(user_id,project_id,asset_id,source_id) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[context.userId,after.projectId,assetId,'command:'+receipts.get(row.record.id)]);}
   for(const row of documents.filter(row=>row.record.kind==='prompt'||row.record.kind==='draft')){
    const kind:ContentKind=row.record.kind==='prompt'?'prompt':'draft',newId=(kind==='prompt'?maps.entry:maps.draft).get(row.record.id)!,history=kind==='draft'?oldVersions.filter(version=>version.id===row.record.id):[],current=parseContent(kind,row.value),rawVersions=[...history.filter(version=>version.revision!==current.revision),current].sort((a,b)=>a.revision-b.revision);
    const mapped=(input:typeof current)=>{const content=remapResources(input,maps) as Record<string,unknown>;if(kind==='draft'){const draft=promptDraftSchema.parse({...content,id:newId});return promptDraftSchema.parse({...draft,resultVersions:draft.resultVersions.map(version=>{const {promptRunId:sourceRun,...value}=version;void sourceRun;return {...value,id:maps.version.get(version.id)!};})});}return parseContent(kind,{...content,id:newId});};
    const next=mapped(current);await db.query('INSERT INTO workspace_content(user_id,id,kind,revision,document,created_at,updated_at) VALUES($1,$2,$3,$4,$5::jsonb,$6,$6)',[context.userId,newId,kind,next.revision,JSON.stringify(next),now]);for(const version of rawVersions)await writeContent(db,context,kind,mapped(version),now,kind==='prompt'&&'trashed'in current&&current.trashed===true);
   }
   for(const row of data.projects){const graph=mapGraph(row.graph);await validateResources(db,context,graph);for(const assetId of graphAssetIds(graph))await db.query("INSERT INTO workspace_asset_references(user_id,project_id,asset_id,source_id) VALUES($1,$2,$3,'graph') ON CONFLICT DO NOTHING",[context.userId,graph.projectId,assetId]);const stack=documents.find(value=>value.value.id==='history:'+row.project.id)?.value,translate=(input:unknown)=>{if(!Array.isArray(input))return [];return input.map(old=>{const id=receipts.get(String(old));if(!id)throw new HttpError(409,'MIGRATION_HISTORY_INVALID');return id;});};await db.query('INSERT INTO workspace_command_history(user_id,project_id,undo_stack,redo_stack) VALUES($1,$2,$3,$4)',[context.userId,graph.projectId,translate(stack?.undoStack),translate(stack?.redoStack)]);if(row.project.trashedAt!==null){const project={...row.project,id:graph.projectId,starred:row.project.starred??false};await db.query('UPDATE workspace_projects SET document=$3::jsonb,trashed_at=$4 WHERE user_id=$1 AND id=$2',[context.userId,graph.projectId,JSON.stringify(project),new Date(row.project.trashedAt)]);}}
   for(const row of commands){await validateResources(db,context,mapGraph(graphSchema.parse(row.value.beforeGraph)));await validateResources(db,context,mapGraph(graphSchema.parse(row.value.afterGraph)));}
   if(input.importPreferences){const preferences=preferencesSchema.parse({...preference.rows[0].preferences as object,...data.preferences});await db.query('UPDATE user_documents SET revision=revision+1,preferences=$2::jsonb WHERE user_id=$1',[context.userId,JSON.stringify(preferences)]);}
   const mapping={projects:Object.fromEntries(maps.project),assets:Object.fromEntries(maps.asset),entries:Object.fromEntries(maps.entry),drafts:Object.fromEntries(maps.draft)};await db.query("UPDATE workspace_imports SET state='committed',mapping=$3::jsonb,reserved_bytes=0,committed_at=$4 WHERE user_id=$1 AND id=$2",[context.userId,id,JSON.stringify(mapping),now]);return importView(db,context,await ownedImport(db,context,id));
  });
  for(const file of stagedFiles)await removePendingFiles(storage,context.userId,file).catch(()=>{});return result;
 }catch(error){for(const file of createdFiles)await removePendingFiles(storage,context.userId,file).catch(()=>{});throw error;}
}
