import {withDatabase,transact,requestResult,type StudioDb} from '../storage/database';
import {loadResourceSnapshot} from '../../features/assets/reference-index';
import {hashBlob} from '../../features/assets/hash-worker';
import {manifestSchema,packageDataSchema,packageAssetIds,portableContent,type PackageData} from './package-model';
import {createPackageZip,encodeJson,packageLimits} from './package-limits';
export type ExportOptions={mode:'full'|'structure';db?:StudioDb};
export type ExportResult={blob:Blob;filename:string;mode:ExportOptions['mode'];missing:string[];assetCount:number;bytes:number};
export async function exportProject(id:string,options:ExportOptions):Promise<ExportResult>{
 const snapshot=await withDatabase(options.db,db=>transact(db,['projects','graphs','assets','runs','promptDrafts','references','receipts','blobs'],'readonly',async tx=>{const resources=await loadResourceSnapshot(tx),project=resources.projects.find(p=>p.id===id),graph=resources.graphs.find(g=>g.projectId===id);if(!project||!graph||project.revision!==graph.revision)throw Error('project_revision_conflict');const runs=resources.runs.filter(r=>r.projectId===id),drafts=resources.drafts.filter(d=>d.sourceProjectId===id),imported=await requestResult<{data?:{runs:unknown[];drafts:unknown[]};unknownNodes?:{payload:Record<string,unknown>}[];isolatedEdges?:Record<string,unknown>[]}|undefined>(tx.objectStore('receipts').get('import-history:'+id));const historicalRuns=imported?.data?.runs??[],data=packageDataSchema.parse({manifest:{format:'aiwork-studio-project',schemaVersion:1,mode:options.mode,createdAt:Date.now(),assets:[]},project:portableContent(project),graph:portableContent(graph),runs:portableContent([...runs,...historicalRuns]),drafts:portableContent(drafts)}),ids=packageAssetIds(data);for(const ref of resources.links)if(ref.projectId===id&&ref.kind==='project-import')ids.add(ref.assetId);const assets=resources.assets.filter(a=>ids.has(a.id));if(assets.length!==ids.size)throw Error('package_missing_asset_metadata');const blobs=new Map<string,Blob>();for(const asset of assets){const row=await requestResult<{blob:Blob}|undefined>(tx.objectStore('blobs').get(asset.blobKey));if(row)blobs.set(asset.id,row.blob);}return {data,assets,blobs,unknown:imported?.unknownNodes??[],isolatedEdges:imported?.isolatedEdges??[]};}));
 const entries:Record<string,Uint8Array>={},missing:string[]=[],assets:PackageData['manifest']['assets']=[];let budget=0;
 for(const raw of snapshot.assets){const asset=portableContent(raw) as typeof raw,blob=snapshot.blobs.get(asset.id);if(!blob)missing.push(asset.id);if(options.mode==='full'){if(!blob)throw Error('package_missing_files');if(blob.size!==asset.bytes||await hashBlob(blob)!==asset.sha256)throw Error('package_asset_integrity_failed');budget+=blob.size;if(blob.size>packageLimits.entryBytes||budget>packageLimits.expandedBytes)throw Error('package_too_large');const path='media/'+asset.sha256+'.bin';if(!entries[path])entries[path]=new Uint8Array(await blob.arrayBuffer());assets.push({...asset,path});}else assets.push(asset);}
 const manifest=manifestSchema.parse({...snapshot.data.manifest,assets});Object.assign(entries,{'manifest.json':encodeJson(manifest),'project.json':encodeJson(snapshot.data.project),'graph.json':encodeJson({...snapshot.data.graph,nodes:[...snapshot.data.graph.nodes,...snapshot.unknown.map(n=>n.payload)],edges:[...snapshot.data.graph.edges,...snapshot.isolatedEdges]}),'runs.json':encodeJson(snapshot.data.runs),'drafts.json':encodeJson(snapshot.data.drafts)});const structure={manifest,project:snapshot.data.project,graph:JSON.parse(new TextDecoder().decode(entries['graph.json'])),runs:snapshot.data.runs,drafts:snapshot.data.drafts},json=options.mode==='structure'?encodeJson(structure):undefined;if(json&&json.byteLength>packageLimits.jsonBytes)throw Error('package_too_large');const blob=json?new Blob([new Uint8Array(json).buffer],{type:'application/json'}):createPackageZip(entries);return {blob,filename:snapshot.data.project.title.replace(/[<>:"/\\|?*\x00-\x1f]/g,'_')+'-'+options.mode+(options.mode==='structure'?'.json':'.zip'),mode:options.mode,missing,assetCount:assets.length,bytes:blob.size};
}
