import {z} from 'zod';
import {projectSchema,type Project} from '../../domain/project';
import {graphSchema,nodeSchema,type Graph} from '../../domain/graph';
import {assetSchema} from '../../domain/asset';
import {promptDraftSchema} from '../../domain/prompt';
import {transact,requestResult,withDatabase,type StudioDb} from '../storage/database';
import {putCreativeGraph} from '../../application/commands/apply-command';
import {hashBlob} from '../../features/assets/hash-worker';
import {detectMediaMime} from '../../features/assets/media-probe';
import {readPackageZip,decodeJson,encodeJson} from './package-limits';
import {packageDataSchema,manifestSchema,portableContent,packageAssetIds,countExcludedFields,type PackageData} from './package-model';
import {migrateLegacyPackage} from './legacy-migration';
import {validateConnection} from '../../domain/graph-validation';
import {unverifiedCapabilities} from '../../domain/connection';
export type ImportPlan={token:string};
export type ImportInspection={ok:boolean;errorCode?:string;plan?:ImportPlan;readonly?:boolean;unknownNodes?:IsolatedNode[];missing?:string[];title?:string;nodeCount?:number;assetCount?:number;mode?:'structure'|'full';original?:Blob;excludedFields?:number;history?:{id:string;taskId?:string;connectionId:string;authBindingId:string;executionState:string;queryState:string;deliveryState:string;billingState:string}[]};
type IsolatedNode={id:string;type:string;title:string;payload:Record<string,unknown>};
type ValidatedPlan={data:PackageData;blobs:Map<string,Blob>;unknown:IsolatedNode[];isolatedEdges:Record<string,unknown>[];missing:string[];createdAt:number;projectId:string};
const plans=new Map<string,ValidatedPlan>(),knownTypes=new Set(['text','asset','video-generation','result','group']);
export async function inspectImport(file:Blob,options:{legacy?:boolean}={}):Promise<ImportInspection>{
 try{
  const prefix=new Uint8Array(await file.slice(0,2).arrayBuffer());let entries:Record<string,Uint8Array>;if(prefix[0]===80&&prefix[1]===75)entries=await readPackageZip(file);else{if(file.size>16*1024*1024)throw Error('import_unsafe');const json=z.strictObject({manifest:z.unknown(),project:z.unknown(),graph:z.unknown(),runs:z.unknown(),drafts:z.unknown()}).parse(decodeJson(new Uint8Array(await file.arrayBuffer())));entries=Object.fromEntries(Object.entries(json).map(([name,value])=>[name+'.json',encodeJson(value)]));}const excludedFields=['manifest.json','project.json','graph.json','runs.json','drafts.json','projects.json'].filter(name=>entries[name]).reduce((count,name)=>count+countExcludedFields(decodeJson(entries[name])),0);if(entries['projects.json']){if(!options.legacy)return {ok:false,errorCode:'legacy_explicit_import_required',original:file};entries=await migrateLegacyPackage(entries);}
  const manifest=manifestSchema.parse(decodeJson(entries['manifest.json']));if(manifest.schemaVersion>1)return {ok:false,errorCode:'schema_too_new',readonly:true,original:file};
  const allowed=new Set(['manifest.json','project.json','graph.json','runs.json','drafts.json',...manifest.assets.flatMap(a=>a.path?[a.path]:[])]);if(Object.keys(entries).some(path=>!allowed.has(path)))throw Error('import_unsafe');
  if(new Set(manifest.assets.map(a=>a.id)).size!==manifest.assets.length)throw Error('import_unsafe');for(const asset of manifest.assets)if(asset.path&&asset.path!=='media/'+asset.sha256+'.bin')throw Error('import_unsafe');
  const rawGraph=z.object({projectId:z.string(),revision:z.number(),nodes:z.array(z.object({id:z.string(),type:z.string(),title:z.string()}).passthrough()),edges:z.array(z.unknown()),viewport:z.unknown()}).parse(decodeJson(entries['graph.json']));if(new Set(rawGraph.nodes.map(n=>n.id)).size!==rawGraph.nodes.length)throw Error('import_unsafe');const unknown=rawGraph.nodes.filter(n=>!knownTypes.has(n.type)).map(node=>({id:node.id,type:node.type,title:portableContent(node.title) as string,payload:portableContent(node) as Record<string,unknown>})),known=rawGraph.nodes.filter(n=>knownTypes.has(n.type)).map(n=>nodeSchema.parse(portableContent(n))),retained=new Set(known.map(n=>n.id));for(const node of known)if(node.type==='group')node.data.childIds=node.data.childIds.filter(id=>retained.has(id));
  const edges=z.array(z.object({id:z.string(),sourceId:z.string(),targetId:z.string()}).passthrough()).parse(rawGraph.edges);if(new Set(edges.map(e=>e.id)).size!==edges.length)throw Error('import_unsafe');const allIds=new Set(rawGraph.nodes.map(n=>n.id));if(edges.some(e=>!allIds.has(e.sourceId)||!allIds.has(e.targetId)))throw Error('import_unsafe');
  const data=packageDataSchema.parse({manifest,project:portableContent(decodeJson(entries['project.json'])),graph:{...rawGraph,nodes:known,edges:edges.filter(e=>retained.has(e.sourceId)&&retained.has(e.targetId))},runs:portableContent(decodeJson(entries['runs.json'])),drafts:portableContent(decodeJson(entries['drafts.json']))});if(data.project.id!==data.graph.projectId||data.project.revision!==data.graph.revision||data.runs.some(r=>r.projectId!==data.project.id))throw Error('import_unsafe');if(new Set(data.runs.map(r=>r.id)).size!==data.runs.length||new Set(data.drafts.map(d=>d.id)).size!==data.drafts.length)throw Error('import_unsafe');
  const assets=new Set(manifest.assets.map(a=>a.id)),runs=new Map(data.runs.map(r=>[r.id,r]));for(const assetId of packageAssetIds(data))if(!assets.has(assetId))throw Error('import_unsafe');for(const node of data.graph.nodes)if(node.type==='result'){const run=runs.get(node.data.runId),asset=manifest.assets.find(a=>a.id===node.data.assetId);if(!run||!asset||run.resultAssetId!==asset.id||asset.sourceRunId!==run.id)throw Error('import_unsafe');}
  for(const edge of data.graph.edges.filter(e=>e.relation))if(!validateConnection(data.graph,edge,unverifiedCapabilities(),{assets:manifest.assets,runs:data.runs}).ok)throw Error('import_unsafe');
  const blobs=new Map<string,Blob>(),missing:string[]=[];for(const asset of manifest.assets){if(asset.mediaType==='text'?asset.mimeType!=='text/plain':!['image/png','image/jpeg','image/gif','image/webp','video/mp4','video/webm','audio/wav','audio/ogg','audio/mpeg'].includes(asset.mimeType)||!asset.mimeType.startsWith(asset.mediaType+'/'))throw Error('import_unsafe');if(!asset.path||!entries[asset.path]){missing.push(asset.id);if(manifest.mode==='full')throw Error('import_unsafe');continue;}const bytes=entries[asset.path],blob=new Blob([new Uint8Array(bytes).buffer],{type:asset.mimeType});if(bytes.length!==asset.bytes||asset.mediaType!=='text'&&detectMediaMime(bytes.slice(0,128))!==asset.mimeType||await hashBlob(blob)!==asset.sha256)throw Error('import_unsafe');blobs.set(asset.id,blob);}
  const token=crypto.randomUUID();plans.set(token,{data,blobs,unknown,isolatedEdges:edges.filter(e=>!retained.has(e.sourceId)||!retained.has(e.targetId)).map(e=>portableContent(e) as Record<string,unknown>),missing,createdAt:Date.now(),projectId:crypto.randomUUID()});return {ok:true,plan:{token},readonly:unknown.length>0,unknownNodes:unknown,missing,title:data.project.title,nodeCount:known.length,assetCount:manifest.assets.length,mode:manifest.mode,original:file,excludedFields,history:data.runs.map(({id,taskId,connectionId,authBindingId,executionState,queryState,deliveryState,billingState})=>({id,taskId,connectionId,authBindingId,executionState,queryState,deliveryState,billingState}))};
 }catch{return {ok:false,errorCode:'import_unsafe',original:file};}
}
function remapCreative(value:unknown,maps:{project:Map<string,string>;node:Map<string,string>;asset:Map<string,string>;run:Map<string,string>;draft:Map<string,string>},key=''):unknown{
 if(typeof value==='string'){const map=['projectId','sourceProjectId'].includes(key)?maps.project:['nodeId','sourceNodeId','sourceId','targetId','childIds','missingInputNodeIds'].includes(key)?maps.node:['assetId','sourceAssetId','resultAssetId','assetIds'].includes(key)?maps.asset:['runId','sourceRunId'].includes(key)?maps.run:key==='draftId'?maps.draft:undefined;return map?map.get(value)??value:value;}
 if(Array.isArray(value))return value.map(v=>remapCreative(v,maps,key));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,remapCreative(v,maps,k)]));return value;
}
export async function commitImport(plan:ImportPlan,options:{db?:StudioDb}={}):Promise<Project>{
 const validated=plans.get(plan.token);if(!validated||Date.now()-validated.createdAt>15*60*1000)throw Error('import_plan_expired');const previous=await withDatabase(options.db,db=>transact(db,['receipts','projects'],'readonly',async tx=>{const receipt=await requestResult<{projectId:string}|undefined>(tx.objectStore('receipts').get('import:'+plan.token));return receipt?projectSchema.parse(await requestResult(tx.objectStore('projects').get(receipt.projectId))):undefined;}));if(previous)return previous;
 if(typeof navigator!=='undefined'&&navigator.storage?.estimate){const estimate=await navigator.storage.estimate().catch(()=>({usage:undefined,quota:undefined}));if(estimate.quota!==undefined&&estimate.usage!==undefined){const required=Array.from(validated.blobs.values()).reduce((total,blob)=>total+blob.size,0)+encodeJson(validated.data).byteLength;if(required>estimate.quota-estimate.usage)throw Error('import_storage_budget_exceeded');}}
 const {data,unknown,blobs,projectId}=validated,now=Date.now(),maps={project:new Map([[data.project.id,projectId]]),node:new Map([...data.graph.nodes,...unknown].map(n=>[n.id,crypto.randomUUID()])),asset:new Map(data.manifest.assets.map(a=>[a.id,crypto.randomUUID()])),run:new Map(data.runs.map(r=>[r.id,crypto.randomUUID()])),draft:new Map(data.drafts.map(d=>[d.id,crypto.randomUUID()]))};
 const project=projectSchema.parse({...data.project,id:projectId,revision:1,createdAt:now,updatedAt:now,archived:unknown.length>0,trashedAt:null}),graph=graphSchema.parse({...remapCreative(data.graph,maps) as Graph,projectId,revision:1,nodes:data.graph.nodes.map(n=>{const mapped=remapCreative(n,maps) as typeof n;return {...mapped,id:maps.node.get(n.id)!,locked:unknown.length>0||n.locked,...(mapped.type==='video-generation'?{data:{...mapped.data,stale:true}}:{})};})}),assets=data.manifest.assets.map(({path,...asset})=>{void path;return assetSchema.parse({...remapCreative(asset,maps) as typeof asset,id:maps.asset.get(asset.id)!,blobKey:'sha256:'+asset.sha256,trashedAt:null});}),drafts=data.drafts.map(d=>promptDraftSchema.parse({...remapCreative(d,maps) as typeof d,id:maps.draft.get(d.id)!,revision:1,resultVersions:d.resultVersions.map(v=>({...v,id:crypto.randomUUID(),shotPlan:v.shotPlan.map(s=>({...s,id:crypto.randomUUID()}))}))}));
 const runs=data.runs.map(r=>({...r,id:maps.run.get(r.id)!,originalRunId:r.id,originalProjectId:r.projectId,projectId,nodeId:maps.node.get(r.nodeId)??r.nodeId,resultAssetId:r.resultAssetId?maps.asset.get(r.resultAssetId):undefined,readonly:true}));
 return withDatabase(options.db,db=>transact(db,['projects','graphs','assets','blobs','promptDrafts','references','receipts','diagnostics'],'readwrite',async tx=>{const prior=await requestResult<{projectId:string}|undefined>(tx.objectStore('receipts').get('import:'+plan.token));if(prior)return projectSchema.parse(await requestResult(tx.objectStore('projects').get(prior.projectId)));if(await requestResult(tx.objectStore('projects').get(projectId)))throw Error('import_project_collision');tx.objectStore('projects').put(project);await putCreativeGraph(tx,graph);for(const [i,asset]of assets.entries()){tx.objectStore('assets').put(asset);const blob=blobs.get(data.manifest.assets[i].id);if(blob)tx.objectStore('blobs').put({id:asset.blobKey,blob});tx.objectStore('references').put({id:projectId+':import:'+asset.id,kind:'project-import',projectId,assetId:asset.id,revision:1});}for(const draft of drafts)tx.objectStore('promptDrafts').put(draft);tx.objectStore('receipts').put({id:'import-history:'+projectId,kind:'readonly-import-history',projectId,data:{runs},unknownNodes:unknown.map(n=>({...n,id:maps.node.get(n.id)!,payload:{...remapCreative(n.payload,maps) as Record<string,unknown>,id:maps.node.get(n.id)!}})),isolatedEdges:validated.isolatedEdges.map(e=>({...remapCreative(e,maps) as Record<string,unknown>,id:crypto.randomUUID()})),missing:validated.missing.map(id=>maps.asset.get(id)),createdAt:now});tx.objectStore('receipts').put({id:'import:'+plan.token,projectId,createdAt:now});tx.objectStore('diagnostics').put({id:crypto.randomUUID(),kind:'project_imported',projectId,count:graph.nodes.length,at:now});return project;}));
}
export function releaseImportPlan(plan:ImportPlan){plans.delete(plan.token);}
export function exportMemoryDraft(project:Project,graph:Graph){if(project.id!==graph.projectId)throw Error('draft_project_mismatch');return new Blob([new Uint8Array(encodeJson({format:'aiwork-studio-memory-draft',schemaVersion:1,project:portableContent(project),graph:portableContent(graph),saved:false,createdAt:Date.now()})).buffer],{type:'application/json'});}
