import {z} from 'zod';
import {decodeJson,encodeJson} from './package-limits';
import {portableContent} from './package-model';
import {hashBlob} from '../../features/assets/hash-worker';
import {probeMedia} from '../../features/assets/media-probe';
// Isolated explicit offline migration only. Fixed source export-format v3,
// dab19adc0847e32e39b7fc8ff90cb392561fb826. Never reads legacy browser storage.
const legacySchema=z.object({app:z.literal('infinite-canvas'),version:z.literal(3),projects:z.array(z.object({project:z.object({id:z.string(),title:z.string(),nodes:z.array(z.object({id:z.string(),type:z.string(),title:z.string(),position:z.object({x:z.number(),y:z.number()}),metadata:z.record(z.string(),z.unknown()).optional()}).passthrough()),connections:z.array(z.object({id:z.string(),fromNodeId:z.string(),toNodeId:z.string()})),viewport:z.object({x:z.number(),y:z.number(),k:z.number()})}),files:z.array(z.object({storageKey:z.string(),path:z.string(),mimeType:z.string(),bytes:z.number()}))})).length(1)});
export async function migrateLegacyPackage(entries:Record<string,Uint8Array>):Promise<Record<string,Uint8Array>>{
 const parsed=legacySchema.parse(decodeJson(entries['projects.json'])),{project,files}=parsed.projects[0],nodes:Record<string,unknown>[]=[],assets:Record<string,unknown>[]=[],media:Record<string,Uint8Array>={},now=Date.now();
 const allowed=new Set(['projects.json',...files.map(f=>f.path)]);if(Object.keys(entries).some(path=>!allowed.has(path)))throw Error('import_unsafe');if(new Set(project.nodes.map(n=>n.id)).size!==project.nodes.length)throw Error('import_unsafe');
 for(const node of project.nodes){const base={id:node.id,title:node.title,x:node.position.x,y:node.position.y,locked:false},meta=node.metadata??{};if(node.type==='text'){nodes.push({...base,type:'text',data:{kind:'text',text:typeof meta.content==='string'?meta.content:typeof meta.prompt==='string'?meta.prompt:'',referenceTokens:[]}});}else if(['image','video','audio'].includes(node.type)){const file=files.find(f=>f.storageKey===meta.storageKey),bytes=file?entries[file.path]:undefined;if(!file||!bytes||bytes.length!==file.bytes){nodes.push({...base,type:'legacy-missing-media',data:{}});continue;}const blob=new Blob([new Uint8Array(bytes).buffer]),actual=await probeMedia(blob),sha256=await hashBlob(blob),assetId=crypto.randomUUID(),path='media/'+sha256+'.bin';if(!actual.mimeType.startsWith(node.type+'/'))throw Error('import_unsafe');assets.push({id:assetId,sha256,mediaType:node.type,mimeType:actual.mimeType,bytes:bytes.length,blobKey:'sha256:'+sha256,title:node.title,createdAt:now,path,...(actual.width?{width:actual.width,height:actual.height}:{}),...(actual.durationSeconds===undefined?{}:{durationSeconds:actual.durationSeconds})});media[path]=bytes;nodes.push({...base,type:'asset',data:{kind:'asset',assetId}});}else if(node.type==='group')nodes.push({...base,type:'group',data:{kind:'group',collapsed:false,childIds:project.nodes.filter(n=>n.metadata?.groupId===node.id).map(n=>n.id)}});else nodes.push({...base,type:'legacy-unsupported-'+node.type,data:{}});}
 // Original open-string connections have no typed ports; preserve as a report,
 // not executable input wires. Model/channel/config/chat sessions are excluded.
 return {'manifest.json':encodeJson({format:'aiwork-studio-project',schemaVersion:1,mode:'full',createdAt:now,assets}),'project.json':encodeJson({id:project.id,schemaVersion:1,title:portableContent(project.title),description:'显式离线迁移；旧配置、会话和无类型连线未导入。',revision:1,createdAt:now,updatedAt:now,archived:false,trashedAt:null,tags:[]}),'graph.json':encodeJson({projectId:project.id,revision:1,nodes:portableContent(nodes),edges:[],viewport:{x:project.viewport.x,y:project.viewport.y,scale:project.viewport.k}}),'runs.json':encodeJson([]),'drafts.json':encodeJson([]),...media};
}
