import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {createLocalServer} from '../../scripts/serve-local.mjs';
const listen=async s=>{await new Promise(r=>s.listen(0,'127.0.0.1',r));return 'http://127.0.0.1:'+s.address().port;};
const close=async s=>{s.closeAllConnections();await new Promise(r=>s.close(r));};
async function register(origin,body){const s=await fetch(origin+'/studio-session.json',{headers:{'X-Studio-Settings':'1'}});assert.equal(s.status,200,'settings session must be available');const {nonce}=await s.json();return fetch(origin+'/studio-api/connections',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','X-Studio-Session':nonce},body:JSON.stringify(body)});}
test('settings register a fixed Core target without calling it, then only health/models can be read',async()=>{const calls=[];const upstream=createServer((req,res)=>{calls.push(req.url);res.setHeader('Content-Type','application/json');res.end(JSON.stringify(req.url==='/v1/models'?{data:[{id:'seedance'}]}:{ok:true}));});const target=await listen(upstream),server=createLocalServer(),origin=await listen(server);try{const response=await register(origin,{kind:'core',name:'Mock Core',origin:target});assert.equal(response.status,201);const {profile}=await response.json();assert.deepEqual(calls,[]);assert.equal((await fetch(origin+profile.proxyBase+'/healthz')).status,200);assert.equal((await fetch(origin+profile.proxyBase+'/v1/models')).status,200);assert.equal((await fetch(origin+profile.proxyBase+'/admin/v1/api-keys')).status,403);assert.equal((await fetch(origin+profile.proxyBase+'/v1/videos',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':'fake-1'},body:'{}'})).status,403);assert.deepEqual(calls,['/healthz','/v1/models']);const config=await (await fetch(origin+'/studio-deployment.json')).json();assert.equal(config.connections[0].contract.verification,'unknown');}finally{await close(server);await close(upstream);}});
test('text registration allows one confirmed chat request and blocks video/admin/redirects',async()=>{const calls=[];const upstream=createServer((req,res)=>{calls.push({url:req.url,cookie:req.headers.cookie});if(req.url==='/v1/models'){res.writeHead(302,{Location:'https://example.invalid'});res.end();}else{res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:'mock response'}}]}));}});const target=await listen(upstream),server=createLocalServer(),origin=await listen(server);try{const response=await register(origin,{kind:'text',name:'Mock text',origin:target+'/v1'});assert.equal(response.status,201);const {profile}=await response.json();assert.equal((await fetch(origin+profile.proxyBase+'/v1/models')).status,502);assert.equal((await fetch(origin+profile.proxyBase+'/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':'fake-text-1',Authorization:'Bearer fake-key',Cookie:'must-not-forward'},body:'{"model":"mock-text","messages":[]}'})).status,200);assert.equal((await fetch(origin+profile.proxyBase+'/v1/videos',{method:'POST',body:'{}'})).status,403);assert.equal((await fetch(origin+profile.proxyBase+'/admin/v1/api-keys')).status,403);assert.equal(calls.length,2);assert.equal(calls[1].cookie,undefined);}finally{await close(server);await close(upstream);}});
test('settings mutation rejects cross-origin/no nonce/credential metadata and malformed target',async()=>{const server=createLocalServer(),origin=await listen(server);try{assert.equal((await fetch(origin+'/studio-api/connections',{method:'POST',headers:{Origin:'https://evil.invalid','Content-Type':'application/json'},body:'{}'})).status,403);assert.equal((await fetch(origin+'/studio-api/connections',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:'{}'})).status,403);for(const body of [{kind:'core',name:'bad',origin:'https://u:pass@example.invalid'},{kind:'text',name:'bad',origin:'https://example.invalid/v1?key=fake'},{kind:'text',name:'bad',origin:'http://192.168.1.2'},{kind:'text',name:'bad',origin:'https://example.invalid',apiKey:'fake'}])assert.equal((await register(origin,body)).status,400);}finally{await close(server);}});
