import {z} from 'zod';
import {id,revision,timestamp,localText,bindingSchema,tags,jsonSnapshotText} from './common';
import {referenceTokenSchema} from './graph';
import {billingStateSchema} from './run';
export const requestedSpecSchema=z.strictObject({durationSeconds:z.number().positive().optional(),ratio:id.optional()});
export const lockedConstraintSchema=z.strictObject({id,field:id,originalValue:z.string(),acceptedValue:z.string().optional(),locked:z.boolean()});
export type LockedConstraint=z.infer<typeof lockedConstraintSchema>;
export const promptCompileInputSchema=z.strictObject({userRequest:localText,sceneId:id,requestedSpec:requestedSpecSchema,audioPlan:z.string(),lockedConstraints:z.array(lockedConstraintSchema),references:z.array(referenceTokenSchema)});
export type PromptCompileInput=z.infer<typeof promptCompileInputSchema>;
export const shotSchema=z.strictObject({id,durationSeconds:z.number().positive(),prompt:localText,startState:z.string(),endState:z.string()});
export type Shot=z.infer<typeof shotSchema>;
export const promptCompileResultSchema=z.strictObject({finalPrompt:localText,shotPlan:z.array(shotSchema),improvements:z.array(z.string()),warnings:z.array(z.string()),suggestedSpec:requestedSpecSchema});
export type PromptCompileResult=z.infer<typeof promptCompileResultSchema>;
export const promptResultVersionSchema=promptCompileResultSchema.extend({id,sourceRevision:revision,origin:z.enum(['local','ai','manual']),validationState:z.enum(['unchecked','needs_review','valid']),promptRunId:id.optional(),createdAt:timestamp});
export type PromptResultVersion=z.infer<typeof promptResultVersionSchema>;
export const promptDraftSchema=promptCompileInputSchema.extend({id,revision,type:z.enum(['video','image']),sourceProjectId:id.optional(),sourceNodeId:id.optional(),sourceRevision:revision.optional(),ruleVersion:id,resultVersions:z.array(promptResultVersionSchema)});
export type PromptDraft=z.infer<typeof promptDraftSchema>;
export const promptRunSchema=bindingSchema.extend({id,draftId:id,draftRevision:revision,mode:z.literal('ai'),textModelId:id,idempotencyKey:id,requestSnapshot:jsonSnapshotText,coreRequestId:id.optional(),executionState:z.enum(['persisted','sending','succeeded','failed_confirmed','response_unknown','waiting_stopped']),billingState:billingStateSchema,startedAt:timestamp,finishedAt:timestamp.optional()});
export type PromptRun=z.infer<typeof promptRunSchema>;
export const promptLibrarySchema=z.strictObject({id,title:z.string().min(1),body:localText,tags,variables:z.array(z.string()),source:z.string(),license:z.string(),revision,starred:z.boolean(),trashed:z.boolean()});
export type PromptLibraryEntry=z.infer<typeof promptLibrarySchema>;
