import {test,expect} from '../helpers/network-guard';
import {seedStudio} from '../helpers/seed-studio';
import {writeFileSync} from 'node:fs';
test.use({video:'on'});
async function setup(page:import('@playwright/test').Page){await seedStudio(page,'unverified-capability');await page.evaluate(async()=>{const p='/tests/fixtures/generation.ts';await(await import(p)).seedGeneration();});await page.goto('/projects/p1/canvas');await expect(page.getByTestId('node-text-1').getByLabel('节点文本')).toBeEditable();}
async function body(page:import('@playwright/test').Page):Promise<string>{return page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['graphs'],'readonly',async(tx:IDBTransaction)=>(await m.requestResult(tx.objectStore('graphs').get('p1'))).nodes.find((n:{id:string})=>n.id==='text-1').data.text);}finally{db.close();}});}
test('T46-C04 actual native Chromium IME composition defers commit, blocks shortcuts and persists Chinese/emoji exactly at the UTF8 boundary',async({page,context,networkCounter})=>{
 await setup(page);const input=page.getByTestId('node-text-1').getByLabel('节点文本',{exact:true}),original=await body(page);await input.focus();await input.evaluate(element=>{const events:{type:string;trusted:boolean}[]=[];Reflect.set(window,'actualIMEEvents',events);for(const type of ['compositionstart','compositionend'])element.addEventListener(type,event=>events.push({type:event.type,trusted:event.isTrusted}));});await page.keyboard.press('Control+a');const cdp=await context.newCDPSession(page);await cdp.send('Input.imeSetComposition',{text:'中文😀',selectionStart:0,selectionEnd:4,replacementStart:0,replacementEnd:original.length});await page.waitForTimeout(400);expect(await body(page)).toBe(original);await page.keyboard.press('Control+k');await expect(page.getByRole('dialog',{name:'命令面板',exact:true})).toHaveCount(0);await cdp.send('Input.insertText',{text:'中文😀'});await expect.poll(()=>body(page)).toBe('中文😀');const events=await page.evaluate(()=>Reflect.get(window,'actualIMEEvents'));// Chromium CDP starts trusted composition, but Input.insertText ends it with an untrusted event. Record the observed native API behavior; OS IME acceptance remains pending.
 expect(events).toEqual([{type:'compositionstart',trusted:true},{type:'compositionend',trusted:false}]);writeFileSync('docs/review/logs/T46-ime-events.json',JSON.stringify({method:'Chromium CDP Input.imeSetComposition + Input.insertText',events,osImeAcceptance:'pending',intermediateCommit:false,committedText:'中文😀'},null,2));
 const boundary='😀'.repeat(16384);await input.focus();await page.keyboard.press('Control+a');await cdp.send('Input.insertText',{text:boundary});await expect.poll(async()=>new TextEncoder().encode(await body(page)).byteLength).toBe(65536);await expect(input).toHaveValue(boundary);await cdp.send('Input.insertText',{text:'中'});await expect(page.getByTestId('node-text-1').getByRole('alert')).toHaveText('本地文本超过64KiB，已保存版本保持原样。');expect(new TextEncoder().encode(await input.inputValue()).byteLength).toBe(65539);expect(await body(page)).toBe(boundary);expect(networkCounter.paidRequests).toHaveLength(0);await page.screenshot({path:'docs/review/screenshots/T46-native-ime-byte-boundary.png'});
});
test('T46 keyboard focus traverses a native dialog, stays visible, wraps at both ends and returns to the exact opener on Escape',async({page,networkCounter})=>{
 await page.goto('/projects');const trigger=page.getByRole('button',{name:'命令面板',exact:true});await trigger.focus();await page.keyboard.press('Enter');const dialog=page.getByRole('dialog',{name:'命令面板',exact:true});await expect(dialog).toBeVisible();const controls=dialog.locator('button:not(:disabled),a[href],input:not(:disabled),textarea:not(:disabled),select:not(:disabled)');await controls.last().focus();await page.keyboard.press('Tab');await expect(controls.first()).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(controls.last()).toBeFocused();const box=await page.locator(':focus').boundingBox();expect(box?.height).toBeGreaterThanOrEqual(32);expect(box?.width).toBeGreaterThanOrEqual(32);await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(trigger).toBeFocused();expect(networkCounter.paidRequests).toHaveLength(0);await page.screenshot({path:'docs/review/screenshots/T46-keyboard-focus.png'});const recording=page.video();await page.close();if(!recording)throw Error('actual_keyboard_video_missing');await recording.saveAs('docs/review/screenshots/T46-keyboard-focus.webm');
});
