import {test,expect} from '../helpers/network-guard';
import type {Page} from '@playwright/test';
import {createServer} from 'node:http';
import {listenLocal,closeLocal} from '../helpers/distribution-runtime';
const model='deepseek-v4.1-flash';
async function connectText(page:Page,address:string,navigate=true){
 if(navigate)await page.goto('/settings/connections');await page.getByLabel('文字 API 地址',{exact:true}).fill(address);await page.getByLabel('文字 API Key',{exact:true}).fill('fake-deepseek-acceptance-key');await page.getByRole('button',{name:'测试文字 API（只读）',exact:true}).click();
 await page.getByLabel('独立文字模型',{exact:true}).selectOption(model);await page.locator('[data-interaction-id="text-api:ack"]').check();await page.getByRole('button',{name:'启用独立文字连接',exact:true}).click();await expect(page.getByText('独立文字连接已启用，仅用于提示词和 Agent 文字提案。每次文字调用仍需预览和费用确认；视频网关保持原绑定。',{exact:true})).toBeVisible();
}
async function preview(page:Page){await page.getByRole('button',{name:'AI优化',exact:true}).click();const dialog=page.getByRole('dialog',{name:'AI文字优化确认',exact:true});await dialog.getByLabel('文字模型',{exact:true}).selectOption(model);await dialog.getByRole('button',{name:'预览文字请求',exact:true}).click();return dialog;}
async function confirm(page:Page){const dialog=await preview(page);await expect(dialog.getByRole('button',{name:'确认文字请求',exact:true})).toBeDisabled();await dialog.locator('[data-interaction-id="ui:AIOptimizeDialog:input:adecea15e1a1"]').check();await dialog.getByRole('button',{name:'确认文字请求',exact:true}).click();}
async function promptRuns(page:Page){return page.evaluate(async()=>{const databases=await indexedDB.databases(),name=databases.find(info=>info.name)?.name;if(!name)throw Error('fixture_database_missing');return new Promise<unknown[]>((resolve,reject)=>{const open=indexedDB.open(name);open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,tx=db.transaction('promptRuns','readonly'),request=tx.objectStore('promptRuns').getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close();};});});}
test('DeepSeek full endpoint, stable same-draft session through refresh and separate confirmations preserve exact Chat body',async({page})=>{
 const calls:{method:string;path:string;body:string;session?:string|string[];userAgent?:string;idempotency?:string|string[]}[]=[],mock=createServer(async(req,res)=>{let body='';for await(const part of req)body+=part;calls.push({method:req.method??'',path:req.url??'',body,session:req.headers['x-opencode-session'],userAgent:req.headers['user-agent'],idempotency:req.headers['idempotency-key']});res.setHeader('Content-Type','application/json');if(req.url==='/zen/go/v1/models')res.end(JSON.stringify({data:[{id:model}]}));else if(req.url==='/zen/go/v1/chat/completions')res.end(JSON.stringify({id:'mock-deepseek-response',choices:[{message:{content:JSON.stringify({finalPrompt:'原创候选正文',shotPlan:[],improvements:[],warnings:[],suggestedSpec:{}})}}]}));else{res.statusCode=404;res.end('{}');}}),origin=await listenLocal(mock);
 try{
  await connectText(page,origin+'/zen/go/v1/chat/completions');expect(calls.map(call=>call.path)).toEqual(['/zen/go/v1/models']);await expect(page.getByLabel('文字 API 状态',{exact:true})).toContainText('只读连接成功');await page.getByLabel('文字 API 地址',{exact:true}).fill(origin+'/zen/go/v1');await expect(page.getByLabel('文字 API 状态',{exact:true})).toContainText('只读连接成功');await expect(page.getByRole('button',{name:'测试文字 API（只读）',exact:true})).toBeEnabled();await page.getByRole('link',{name:'提示词生成',exact:true}).click();await page.getByLabel('原始创意',{exact:true}).fill('原创验收人物走过庭院，无对白');await page.getByRole('button',{name:'保存草稿',exact:true}).click();
  const draftUrl=page.url();const cancelled=await preview(page);await cancelled.getByRole('button',{name:'取消',exact:true}).click();expect(calls.filter(call=>call.method==='POST')).toHaveLength(0);
  await confirm(page);await expect(page.getByText('AI候选已保存',{exact:false}).first()).toBeVisible();const first=calls.find(call=>call.method==='POST')!;expect(first.session).toMatch(/^studio-prompt-[a-f0-9]{64}$/);expect(first.userAgent).toBe('AIWorkStudio/0.0.1');expect(JSON.parse(first.body).model).toBe(model);expect(first.body).not.toContain('fake-deepseek-acceptance-key');expect(first.body).not.toContain(String(first.session));
  await page.reload();expect(calls.filter(call=>call.method==='POST')).toHaveLength(1);await page.getByRole('link',{name:'设置',exact:true}).click();await expect(page.getByLabel('文字 API Key',{exact:true})).toHaveValue('');await connectText(page,origin+'/zen/go/v1',false);await page.goBack();await expect(page).toHaveURL(draftUrl);await confirm(page);await expect(page.getByText('AI候选已保存',{exact:false}).first()).toBeVisible();
  const chats=calls.filter(call=>call.method==='POST');expect(chats).toHaveLength(2);expect(chats[1].session).toBe(first.session);expect(chats[1].body).toBe(first.body);expect(chats[1].idempotency).not.toBe(first.idempotency);expect(calls.some(call=>call.path.includes('videos'))).toBe(false);
  const runs=await promptRuns(page);expect(runs).toHaveLength(2);expect(runs).toEqual(expect.arrayContaining([expect.objectContaining({textModelId:model,executionState:'succeeded',billingState:'not_provided'})]));expect(JSON.stringify(runs)).not.toContain('fake-deepseek-acceptance-key');await page.screenshot({path:'docs/review/screenshots/acceptance-deepseek-prompt.png'});
 }finally{await closeLocal(mock);}
});
test('DeepSeek rejection shows safe specific reason, retains unknown request and blocks fresh send until separate prior-charge consent',async({page})=>{
 const calls:{method:string;path:string}[]=[],mock=createServer(async(req,res)=>{for await(const _ of req){void _;}calls.push({method:req.method??'',path:req.url??''});res.setHeader('Content-Type','application/json');if(req.method==='GET')res.end(JSON.stringify({data:[{id:model}]}));else{res.statusCode=400;res.end(JSON.stringify({type:'MissingSessionID',message:'private-raw-message fake-deepseek-acceptance-key'}));}}),origin=await listenLocal(mock);
 try{
  await connectText(page,origin+'/v1');await page.getByRole('link',{name:'提示词生成',exact:true}).click();await page.getByLabel('原始创意',{exact:true}).fill('保留原创输入，无对白');await page.getByRole('button',{name:'保存草稿',exact:true}).click();await confirm(page);await expect(page.getByText('文字服务失败（HTTP 400）：服务需要稳定会话标识，请更新本地客户端后重试。',{exact:false})).toBeVisible();
  await expect(page.getByLabel('原始创意',{exact:true})).toHaveValue('保留原创输入，无对白');expect(await page.locator('body').innerText()).not.toContain('private-raw-message');expect(await page.locator('body').innerText()).not.toContain('fake-deepseek-acceptance-key');const runs=await promptRuns(page);expect(runs).toHaveLength(1);expect(runs[0]).toMatchObject({executionState:'response_unknown',billingState:'not_provided'});
  const next=await preview(page);await next.locator('[data-interaction-id="ui:AIOptimizeDialog:input:adecea15e1a1"]').check();await expect(next.getByRole('button',{name:'确认文字请求',exact:true})).toBeDisabled();await expect(next.getByText('旧文字请求结果或账务尚未核对。新请求使用新的身份，可能再次产生费用，不会替换或取消旧请求。',{exact:true})).toBeVisible();await next.getByRole('button',{name:'取消',exact:true}).click();expect(calls.filter(call=>call.method==='POST')).toHaveLength(1);await page.screenshot({path:'docs/review/screenshots/acceptance-deepseek-error.png'});
 }finally{await closeLocal(mock);}
});

test('a Chat response that cannot become a prompt candidate does not claim generation verification',async({page})=>{
 const mock=createServer(async(req,res)=>{for await(const _ of req){void _;}res.setHeader('Content-Type','application/json');if(req.method==='GET')res.end(JSON.stringify({data:[{id:model}]}));else res.end(JSON.stringify({id:'mock-invalid-prompt',choices:[{message:{content:'plain text without a valid prompt candidate'}}]}));}),origin=await listenLocal(mock);
 try{
  await connectText(page,origin+'/v1');await page.getByRole('link',{name:'提示词生成',exact:true}).click();await page.getByLabel('原始创意',{exact:true}).fill('简短原创测试创意');await page.getByRole('button',{name:'保存草稿',exact:true}).click();await confirm(page);
  await expect(page.getByRole('region',{name:'AI结果差异',exact:true})).toContainText('响应解析失败');await page.getByRole('link',{name:'设置',exact:true}).click();await expect(page.getByLabel('文字 API 状态',{exact:true})).not.toContainText('真实生成已验证');
 }finally{await closeLocal(mock);}
});

test('Agent stale graph preview gives a specific local rejection before any Chat POST and preserves creative text',async({page})=>{
 const paths:string[]=[],mock=createServer(async(req,res)=>{for await(const part of req){void part;}paths.push(req.url??'');res.setHeader('Content-Type','application/json');res.end(JSON.stringify({data:[{id:model}]}));}),origin=await listenLocal(mock);
 try{
  await connectText(page,origin+'/v1');await page.getByRole('link',{name:'项目',exact:true}).click();await page.getByRole('button',{name:'新建项目',exact:true}).click();let dialog=page.getByRole('dialog',{name:'新建项目',exact:true});await dialog.getByLabel('项目名称',{exact:true}).fill('Agent 预览修订安全对照');await dialog.getByRole('button',{name:'创建',exact:true}).click();await page.getByRole('button',{name:'添加节点',exact:true}).click();await page.getByRole('button',{name:'文本节点',exact:true}).click();await page.getByLabel('节点文本',{exact:true}).fill('独立原创测试文字');await expect(page.locator('.canvas-heading > [role="status"]')).toHaveText('已保存');
  await page.getByRole('button',{name:'Agent 协作',exact:true}).click();await page.getByRole('button',{name:'连接线上文字模型',exact:true}).click();await page.getByLabel('上下文范围',{exact:true}).selectOption('nodes');await page.getByLabel(/^上下文节点 /).check();await page.getByRole('button',{name:'预览并管理授权',exact:true}).click();dialog=page.getByRole('dialog',{name:'Agent 项目授权',exact:true});await dialog.getByLabel('创作权限',{exact:true}).selectOption('propose');await dialog.getByRole('button',{name:'授予所列权限',exact:true}).click();await page.getByLabel('任务描述',{exact:true}).fill('建议一个标题');await page.getByRole('button',{name:'发送任务描述',exact:true}).click();dialog=page.getByRole('dialog',{name:'线上 Agent 文字请求确认',exact:true});
  // Only this fresh fixture database is changed: simulate a committed graph
  // revision after the UI has frozen its request preview.
  await page.evaluate(()=>new Promise<void>((resolve,reject)=>{const open=indexedDB.open('aiwork-studio:v1');open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,tx=db.transaction('graphs','readwrite'),request=tx.objectStore('graphs').getAll();request.onsuccess=()=>{if(request.result.length!==1){tx.abort();return;}const graph=request.result[0];tx.objectStore('graphs').put({...graph,revision:graph.revision+1});};tx.oncomplete=()=>{db.close();resolve();};tx.onabort=()=>{db.close();reject(tx.error??Error('fixture_graph_revision_failed'));};};}));
  await dialog.getByLabel('我确认文字请求及可能产生的费用',{exact:true}).check();await dialog.getByRole('button',{name:'确认发送文字请求',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('文字请求预览已过期：画布、授权或文字连接已变化。请重新预览并确认；本轮未发送文字请求。');expect(paths).toEqual(['/v1/models']);await expect(page.getByLabel('节点文本',{exact:true})).toHaveValue('独立原创测试文字');await page.screenshot({path:'docs/review/screenshots/acceptance-agent-stale-preview.png'});
 }finally{await closeLocal(mock);}
});
