import {test,expect} from '../helpers/account-api-ui-fixture';
const card=(page:import('@playwright/test').Page,channel:'video'|'text')=>page.getByRole('region',{name:channel==='video'?'视频 API':'文字 API',exact:true});
test('shared cards have three fields / two actions, video first, with address-key-model order for text',async({page})=>{
 await page.goto('/welcome');const video=card(page,'video'),text=card(page,'text');await expect(video).toBeVisible();await expect(text).toBeVisible();
 for(const panel of [video,text]){await expect(panel.locator('input')).toHaveCount(3);await expect(panel.getByRole('button')).toHaveCount(2);await expect(panel.getByRole('button',{name:'测试连接',exact:true})).toBeVisible();await expect(panel.getByRole('button',{name:'保存',exact:true})).toBeVisible();}
 expect(await video.locator('input').evaluateAll(inputs=>inputs.map(input=>input.getAttribute('data-field')))).toEqual(['apiBase','model','apiKey']);expect(await text.locator('input').evaluateAll(inputs=>inputs.map(input=>input.getAttribute('data-field')))).toEqual(['apiBase','apiKey','model']);await expect(page.getByRole('button',{name:'进入工作台',exact:true})).toBeVisible();await expect(page.getByText('进入本地模式',{exact:true})).toHaveCount(0);
});
test('text tests without model; unavailable catalog permits manual save; saved key remains an empty input',async({page,apiModel})=>{
 apiModel.catalogStatus='unavailable';apiModel.connection='unknown';apiModel.models=[];await page.goto('/welcome');const text=card(page,'text');await text.getByLabel('地址',{exact:true}).fill('https://fake.example/api');await text.getByLabel('密钥',{exact:true}).fill('FAKE_UI_KEY');await text.getByRole('button',{name:'测试连接',exact:true}).click();await expect(text.getByRole('status')).toContainText('可手动填写');expect(apiModel.probes[0].input).not.toHaveProperty('model');expect(apiModel.configWrites).toHaveLength(0);
 await text.getByLabel('模型名称',{exact:true}).fill('Vendor/Unlisted');await text.getByRole('button',{name:'保存',exact:true}).click();await expect(text.getByRole('status')).toContainText('已保存');await expect(text.getByLabel('密钥',{exact:true})).toHaveValue('');await expect(text.getByLabel('密钥',{exact:true})).toHaveAttribute('placeholder','已保存；留空继续使用');expect(apiModel.configs[0].model).toBe('Vendor/Unlisted');await expect(text).not.toContainText('生成成功');
});
test('settings and welcome reload the same saved values, retain typed model on retest and keep text controls visible',async({page,apiModel})=>{
 apiModel.configs=[{channel:'text',apiBase:'https://fake.example/api',model:'Vendor/Manual',revision:1,hasKey:true}];await page.goto('/welcome');const text=card(page,'text');await expect(text.getByLabel('模型名称',{exact:true})).toHaveValue('Vendor/Manual');await text.getByRole('button',{name:'测试连接',exact:true}).click();await expect(text.locator('option')).toHaveCount(1);await expect(text.getByLabel('模型名称',{exact:true})).toHaveValue('Vendor/Manual');
 await page.getByRole('link',{name:'API 设置',exact:true}).click();await expect(page).toHaveURL(/\/settings\/connections$/);await expect(card(page,'text').getByLabel('模型名称',{exact:true})).toHaveValue('Vendor/Manual');await card(page,'text').getByLabel('模型名称',{exact:true}).fill('Vendor/FromSettings');await card(page,'text').getByRole('button',{name:'保存',exact:true}).click();await expect(card(page,'text').getByRole('status')).toContainText('已保存');await page.getByRole('link',{name:'使用引导',exact:true}).click();await expect(card(page,'text').getByLabel('模型名称',{exact:true})).toHaveValue('Vendor/FromSettings');
});
test('Chinese composition Enter does not submit; only the save button makes a request',async({page,apiModel})=>{
 await page.goto('/settings/connections');const text=card(page,'text');await text.getByLabel('地址',{exact:true}).fill('https://fake.example');await text.getByLabel('密钥',{exact:true}).fill('FAKE_UI_KEY');const model=text.getByLabel('模型名称',{exact:true});await model.fill('供应商/模型');await model.dispatchEvent('compositionstart');await model.dispatchEvent('keydown',{key:'Enter',code:'Enter',isComposing:true});await model.dispatchEvent('compositionend');await model.press('Enter');expect(apiModel.configWrites).toHaveLength(0);expect(apiModel.probes).toHaveLength(0);await text.getByRole('button',{name:'保存',exact:true}).click();await expect(text.getByRole('status')).toContainText('已保存');expect(apiModel.configWrites).toHaveLength(1);
});
test('save conflict and failure retain entered credentials until explicit reload',async({page,apiModel})=>{
 apiModel.configs=[{channel:'text',apiBase:'https://fake.example',model:'Vendor/Saved',revision:1,hasKey:true}];await page.goto('/settings/connections');const text=card(page,'text');await text.getByLabel('模型名称',{exact:true}).fill('Vendor/Unsaved');await text.getByLabel('密钥',{exact:true}).fill('FAKE_UI_UNSAVED');apiModel.conflictNextSave=true;await text.getByRole('button',{name:'保存',exact:true}).click();await expect(text.getByRole('alert')).toContainText('输入已保留');await expect(text.getByLabel('模型名称',{exact:true})).toHaveValue('Vendor/Unsaved');await expect(text.getByLabel('密钥',{exact:true})).toHaveValue('FAKE_UI_UNSAVED');await page.getByRole('button',{name:'重新加载两项配置',exact:true}).click();await expect(text.getByLabel('模型名称',{exact:true})).toHaveValue('Vendor/Saved');await expect(text.getByLabel('密钥',{exact:true})).toHaveValue('');apiModel.failNextSave=true;await text.getByLabel('模型名称',{exact:true}).fill('Vendor/Keep');await text.getByRole('button',{name:'保存',exact:true}).click();await expect(text.getByRole('alert')).toBeVisible();await expect(text.getByLabel('模型名称',{exact:true})).toHaveValue('Vendor/Keep');
});
test('a changed address clears catalog and requires a replacement key; late probe cannot restore catalog',async({page,apiModel})=>{
 apiModel.configs=[{channel:'text',apiBase:'https://fake.example',model:'Vendor/Saved',revision:1,hasKey:true}];let release!:()=>void;apiModel.probeGate=new Promise<void>(resolve=>{release=resolve;});try{
  await page.goto('/settings/connections');const text=card(page,'text');await text.getByRole('button',{name:'测试连接',exact:true}).click();await expect.poll(()=>apiModel.probes.length).toBe(1);await text.getByLabel('地址',{exact:true}).fill('https://other.fake.example');release();await text.getByRole('button',{name:'保存',exact:true}).click();await expect(text.getByRole('alert')).toContainText('密钥');await expect(text.locator('option')).toHaveCount(0);expect(apiModel.configWrites).toHaveLength(0);
 }finally{release();}
});
test('account switch discards A draft and late results before showing B configurations',async({page,apiModel})=>{
 apiModel.configs=[{channel:'text',apiBase:'https://fake.example',model:'A/Model',revision:1,hasKey:true}];let release!:()=>void;apiModel.probeGate=new Promise<void>(resolve=>{release=resolve;});try{
  await page.goto('/welcome');const text=card(page,'text');await text.getByLabel('密钥',{exact:true}).fill('FAKE_A_DRAFT_KEY');await text.getByRole('button',{name:'测试连接',exact:true}).click();await expect.poll(()=>apiModel.probes.length).toBe(1);apiModel.session={...apiModel.session,user:{id:'22222222-2222-4222-8222-222222222222',username:'Fake_Task3_B'},contextId:'c'.repeat(43),csrfToken:'d'.repeat(43)};apiModel.configs=[{channel:'text',apiBase:'https://fake-b.example',model:'B/Model',revision:1,hasKey:true}];await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByText('当前账号：Fake_Task3_B',{exact:true})).toBeVisible();await expect(card(page,'text').getByLabel('模型名称',{exact:true})).toHaveValue('B/Model');release();await expect(card(page,'text').getByLabel('密钥',{exact:true})).toHaveValue('');await expect(card(page,'text').locator('option')).toHaveCount(0);
 }finally{release();}
});
test('entering workspace records server onboarding and keeps incomplete legacy workspace gated',async({page,apiModel})=>{
 await page.goto('/welcome');await page.getByRole('button',{name:'进入工作台',exact:true}).click();await expect(page).toHaveURL(/\/projects$/);expect(apiModel.onboardingWrites).toEqual([{expectedRevision:0,completed:true}]);expect(apiModel.probes).toHaveLength(0);expect(apiModel.configWrites).toHaveLength(0);await expect(page.getByRole('heading',{name:'账号工作区',exact:true})).toBeVisible();await expect(page.locator('.canvas-shell')).toHaveCount(0);
});
test('both themes at 1440/1280/1024/720 keep fields visible, targets 44px and cards follow the width boundary',async({page,apiModel},testInfo)=>{
 for(const theme of ['dark','light'] as const){apiModel.document.preferences.theme=theme;for(const width of [1440,1280,1024,720]){
  await page.setViewportSize({width,height:1100});await page.goto('/welcome');const video=card(page,'video'),text=card(page,'text');await expect(text).toBeVisible();const v=await video.boundingBox(),t=await text.boundingBox();if(!v||!t)throw new Error('Missing cards');if(width>=1024)expect(Math.abs(v.y-t.y)).toBeLessThan(2);else expect(t.y).toBeGreaterThan(v.y+v.height-2);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const sizes=await page.locator('.api-settings-panel input,.api-settings-panel button').evaluateAll(controls=>controls.map(control=>control.getBoundingClientRect().height));expect(sizes.every(height=>height>=44)).toBe(true);await page.screenshot({path:testInfo.outputPath(`task3-${theme}-${width}.png`),fullPage:true});
 }}
});
test('onboarding conflict reloads account revision, keeps API draft on failed/successful reload and then enters workspace',async({page,apiModel})=>{
 await page.goto('/welcome');const text=card(page,'text');await text.getByLabel('地址',{exact:true}).fill('https://fake.example');await text.getByLabel('密钥',{exact:true}).fill('FAKE_KEEP_ONBOARDING');await text.getByLabel('模型名称',{exact:true}).fill('Vendor/Unsaved');apiModel.conflictNextOnboarding=true;await page.getByRole('button',{name:'进入工作台',exact:true}).click();await expect(page.getByRole('alert')).toContainText('重新加载账号状态');await expect(page).toHaveURL(/\/welcome$/);
 apiModel.failNextDocumentRead=true;await page.getByRole('button',{name:'重新加载账号状态',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();await expect(text.getByLabel('密钥',{exact:true})).toHaveValue('FAKE_KEEP_ONBOARDING');await page.getByRole('button',{name:'重新加载账号状态',exact:true}).click();await expect(page.getByRole('status')).toContainText('账号状态已重新加载');await expect(text.getByLabel('模型名称',{exact:true})).toHaveValue('Vendor/Unsaved');await expect(text.getByLabel('密钥',{exact:true})).toHaveValue('FAKE_KEEP_ONBOARDING');await page.getByRole('button',{name:'进入工作台',exact:true}).click();await expect(page).toHaveURL(/\/projects$/);expect(apiModel.onboardingWrites).toEqual([{expectedRevision:0,completed:true},{expectedRevision:1,completed:true}]);expect(apiModel.configWrites).toHaveLength(0);expect(apiModel.probes).toHaveLength(0);
});
