import type {Page} from '@playwright/test';
import {assertAuthenticatedWelcome} from '../helpers/account-welcome-assertions';
import {test,expect,accountOrigin} from '../helpers/account-fixture';
const password='Fake browser password 2026';
async function auth(page:Page,username:string,operation='register'){await page.goto('/'+operation);await page.getByLabel('用户名',{exact:true}).fill(username);await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:operation==='register'?'注册':'登录',exact:true}).click();await expect(page.getByText('当前账号：'+username,{exact:true})).toBeVisible();}
async function appearance(page:Page,theme:string,sort:string){await page.getByRole('link',{name:'账号偏好',exact:true}).click();await page.getByLabel('主题',{exact:true}).selectOption(theme);await page.getByLabel('项目排序',{exact:true}).selectOption(sort);await page.getByRole('button',{name:'保存偏好',exact:true}).click();await expect(page.getByRole('status')).toContainText('偏好已保存');}
test('anonymous boundary does not initialize legacy storage or private requests; register uses two fields and secure Cookie',async({page,context,backend})=>{
 const api:string[]=[];page.on('request',r=>{if(r.url().includes('/studio-api/'))api.push(new URL(r.url()).pathname);});
 await page.addInitScript(()=>{localStorage.setItem('aiwork-studio:preferences','{"theme":"light","FAKE_PRIVATE":"OLD_USER"}');localStorage.setItem('aiwork-studio:onboarding','1');const raw=indexedDB.open.bind(indexedDB);(window as Window&{legacyOpens?:string[]}).legacyOpens=[];indexedDB.open=((name:string,version?:number)=>{(window as Window&{legacyOpens?:string[]}).legacyOpens!.push(name);return raw(name,version);}) as typeof indexedDB.open;});
 await page.goto('/projects');await expect(page).toHaveURL(/\/register$/);await expect(page.getByRole('heading',{name:'注册',exact:true})).toBeVisible();expect(api).not.toContain('/studio-api/me/document');
 await auth(page,'Fake_Browser_A');await expect(page).toHaveURL(/\/welcome$/);await assertAuthenticatedWelcome(page);
 const identity=await (await page.request.get('/studio-api/session')).json();const configs=await page.request.get('/studio-api/me/model-configs',{headers:{'X-Workspace-Context':identity.contextId}});expect(configs.status()).toBe(200);expect(await configs.json()).toEqual({configs:[]});
 await page.getByRole('button',{name:'\u8fdb\u5165\u5de5\u4f5c\u53f0',exact:true}).click();await expect(page).toHaveURL(/\/projects$/);await expect(page.getByText('\u521b\u4f5c\u5de5\u4f5c\u533a\u6682\u672a\u5f00\u653e\u3002',{exact:true})).toBeVisible();

 const opens=await page.evaluate(()=>(window as Window&{legacyOpens?:string[]}).legacyOpens);expect(opens).toEqual([]);expect(await page.evaluate(()=>localStorage.getItem('aiwork-studio:preferences'))).toContain('OLD_USER');
 const cookies=await context.cookies();const session=cookies.find(c=>c.name==='__Host-aiwork-session');expect(session).toMatchObject({secure:true,httpOnly:true,sameSite:'Lax',path:'/'});expect(cookies.some(c=>c.name==='__Host-aiwork-preauth')).toBe(false);expect(await page.evaluate(()=>document.cookie)).not.toContain('__Host-aiwork-session');expect((await backend.pool.query('SELECT count(*) AS n FROM users')).rows[0].n).toBe('1');
});
test('A and B preferences stay separate; logout clears A; new browser recovers server document; original data stays untouched',async({page,context,newAccountContext,backend})=>{
 await page.goto('/login');await page.evaluate(async()=>{localStorage.setItem('aiwork-studio:preferences','FAKE_ORIGINAL_PREFS');const modulePath='/src/infrastructure/storage/database.ts';const storage=await import(modulePath);const db=await storage.openStudioDb();try{await storage.transact(db,['blobs','projects'],'readwrite',(tx:IDBTransaction)=>{tx.objectStore('blobs').put({id:'FAKE_ORIGINAL_BLOB',blob:new Blob(['FAKE_ORIGINAL_BLOB'])});tx.objectStore('projects').put({id:'FAKE_ORIGINAL_PROJECT',title:'FAKE_PRIVATE_OLD'});});}finally{db.close();}});
 await auth(page,'Fake_Pref_A');await appearance(page,'light','title');await page.getByRole('button',{name:'退出登录',exact:true}).click();await expect(page).toHaveURL(/\/register$/);await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 await auth(page,'Fake_Pref_B');await page.getByRole('link',{name:'账号偏好',exact:true}).click();await expect(page.getByLabel('主题',{exact:true})).toHaveValue('dark');await expect(page.getByLabel('项目排序',{exact:true})).toHaveValue('updated');await appearance(page,'dark','updated');
 expect(await page.evaluate(()=>localStorage.getItem('aiwork-studio:preferences'))).toBe('FAKE_ORIGINAL_PREFS');const old=await page.evaluate(async()=>{const modulePath='/src/infrastructure/storage/database.ts';const storage=await import(modulePath);const db=await storage.openStudioDb();try{return await storage.transact(db,['blobs','projects'],'readonly',async(tx:IDBTransaction)=>{const blob=await storage.requestResult(tx.objectStore('blobs').get('FAKE_ORIGINAL_BLOB'));const project=await storage.requestResult(tx.objectStore('projects').get('FAKE_ORIGINAL_PROJECT'));return {text:await blob.blob.text(),project};});}finally{db.close();}});expect(old).toEqual({text:'FAKE_ORIGINAL_BLOB',project:{id:'FAKE_ORIGINAL_PROJECT',title:'FAKE_PRIVATE_OLD'}});
 const fresh=await newAccountContext();try{const p=await fresh.newPage();await auth(p,'Fake_Pref_A','login');await p.getByRole('link',{name:'账号偏好',exact:true}).click();await expect(p.getByLabel('主题',{exact:true})).toHaveValue('light');await expect(p.getByLabel('项目排序',{exact:true})).toHaveValue('title');await p.screenshot({path:'work/account-api-cloud/account-preferences-desktop.png'});}finally{await fresh.close();}
 const rows=await backend.pool.query('SELECT preferences FROM user_documents');expect(rows.rows).toHaveLength(2);expect(await context.cookies()).toHaveLength(1);
});
test('expiry clears private state and password; obsolete context plus B cookie is refused by real backend',async({page,backend})=>{
 await auth(page,'Fake_Expiry_A');const a=(await page.request.get('/studio-api/session')).json();const aView=await a;await appearance(page,'light','title');backend.advance(24*3600000+1);await page.reload();await expect(page).toHaveURL(/\/register$/);await expect(page.getByLabel('密码',{exact:true})).toHaveValue('');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 await auth(page,'Fake_Expiry_B');const bad=await page.request.patch('/studio-api/me/document',{headers:{Origin:accountOrigin,'X-Workspace-Context':aView.contextId,'X-CSRF-Token':aView.csrfToken},data:{expectedRevision:0,lastVisitedPage:'/projects'}});expect(bad.status()).toBe(409);expect(await bad.json()).toEqual({code:'SESSION_CHANGED'});const b=await page.request.get('/studio-api/me/document',{headers:{'X-Workspace-Context':(await (await page.request.get('/studio-api/session')).json()).contextId}});expect((await b.json()).revision).toBe(0);
});
test('identity broadcast clears an old tab and ignores its delayed real A preference response after B login',async({page,context})=>{
 await auth(page,'Fake_Tabs_A');await page.getByRole('link',{name:'账号偏好',exact:true}).click();await page.getByLabel('主题',{exact:true}).selectOption('light');
 let release:()=>void=()=>{};let gotResponse:()=>void=()=>{};const held=new Promise<void>(resolve=>{release=resolve;}),arrived=new Promise<void>(resolve=>{gotResponse=resolve;});
 await page.route('**/studio-api/me/document',async route=>{if(route.request().method()!=='PATCH')return route.continue();const real=await route.fetch();gotResponse();await held;try{await route.fulfill({response:real});}catch{/* The old page correctly aborted its request. */}});
 await page.getByRole('button',{name:'保存偏好',exact:true}).click();await arrived;const other=await context.newPage();await other.goto('/welcome');await expect(other.getByText('当前账号：Fake_Tabs_A',{exact:true})).toBeVisible();await other.getByRole('button',{name:'退出登录',exact:true}).click();await expect(page).toHaveURL(/\/register$/);await auth(other,'Fake_Tabs_B');release();await expect(page.getByText('当前账号：Fake_Tabs_B',{exact:true})).toBeVisible();await page.getByRole('link',{name:'账号偏好',exact:true}).click();await expect(page.getByLabel('主题',{exact:true})).toHaveValue('dark');await expect(page.getByText('当前账号：Fake_Tabs_A',{exact:true})).toHaveCount(0);
});
test('conflicting document revision preserves draft and supports explicit reload; unknown workspace routes do not read old resources',async({page,backend})=>{
 await auth(page,'Fake_Revision_A');await page.getByRole('link',{name:'账号偏好',exact:true}).click();await page.getByLabel('主题',{exact:true}).selectOption('light');await backend.pool.query('UPDATE user_documents SET revision=revision+1');await page.getByRole('button',{name:'保存偏好',exact:true}).click();await expect(page.getByRole('alert')).toContainText('偏好已在其他页面更新');await expect(page.getByLabel('主题',{exact:true})).toHaveValue('light');await page.getByRole('button',{name:'重新加载偏好',exact:true}).click();await expect(page.getByLabel('主题',{exact:true})).toHaveValue('dark');
 const urls:string[]=[];page.on('request',r=>{urls.push(r.url());});await page.goto('/projects/FAKE_PRIVATE_OLD/canvas');await expect(page.getByText('创作工作区暂未开放',{exact:false})).toBeVisible();expect(urls.some(u=>/registrations|core-proxy|text-proxy/.test(u))).toBe(false);await page.setViewportSize({width:390,height:844});await page.screenshot({path:'work/account-api-cloud/account-mobile.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('welcome decisions use current document onboarding and remembered page across fresh session reads',async({page,backend})=>{
 await auth(page,'Fake_Route_A');await backend.pool.query("UPDATE user_documents SET onboarding_completed_at=NOW(),last_visited_page='/settings/appearance',revision=revision+1");await page.goto('/');await expect(page).toHaveURL(/\/settings\/appearance$/);await expect(page.getByRole('heading',{name:'账号偏好',exact:true})).toBeVisible();await backend.pool.query('UPDATE user_documents SET onboarding_completed_at=NULL,revision=revision+1');await page.goto('/');await expect(page).toHaveURL(/\/welcome$/);
});

test('failed login and expired bootstrap show fixed feedback, clear password and allow a fresh verified submission',async({page,backend})=>{
 await auth(page,'Fake_Feedback_A');await page.getByRole('button',{name:'退出登录',exact:true}).click();await page.goto('/login');await page.getByLabel('用户名',{exact:true}).fill('Fake_Feedback_A');await page.getByLabel('密码',{exact:true}).fill('Fake incorrect password 2026');await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('alert')).toContainText('用户名或密码不正确');await expect(page.getByLabel('密码',{exact:true})).toHaveValue('');
 await page.goto('/register');await page.getByLabel('用户名',{exact:true}).fill('Fake_Feedback_B');await page.getByLabel('密码',{exact:true}).fill(password);await expect(page.getByRole('button',{name:'注册',exact:true})).toBeEnabled();backend.advance(600001);await page.getByRole('button',{name:'注册',exact:true}).click();await expect(page.getByRole('alert')).toContainText('登录验证已失效');await expect(page.getByLabel('密码',{exact:true})).toHaveValue('');await page.getByLabel('用户名',{exact:true}).fill('Fake_Feedback_B');await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'注册',exact:true}).click();await expect(page.getByText('当前账号：Fake_Feedback_B',{exact:true})).toBeVisible();
});
