import {test,expect} from '../helpers/network-guard';
import {holdNextNativeCommit,releaseNativeCommit,nativeCommitProbe} from '../helpers/native-commit-hold';
import type {Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const state=(page:Page)=>page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['diagnostics','runs','promptRuns','projects','graphs','receipts'],'readonly',async(tx:IDBTransaction)=>Object.fromEntries(await Promise.all(['diagnostics','runs','promptRuns','projects','graphs','receipts'].map(async table=>[table,await m.requestResult(tx.objectStore(table).getAll())]))));}finally{db.close();}});
test.beforeEach(async({page})=>{await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/task-history.ts';await (await import(p)).seedTaskHistory();const d='/src/infrastructure/storage/database.ts',m=await import(d);await m.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>m.transact(db,['diagnostics'],'readwrite',(tx:IDBTransaction)=>tx.objectStore('diagnostics').put({id:'display-only-test',kind:'project_saved',projectId:'p1',at:Date.now()})));});await page.goto('/activity');await expect(page.locator('article').filter({hasText:'display-only-test'})).toBeVisible();});

test('T44 H03 native diagnostic export read failure and delayed real completion preserve unknown requests and expose busy confirmation',async({page,networkCounter})=>{
 const before=await state(page);await page.getByRole('button',{name:'导出诊断包',exact:true}).click();const dialog=page.getByRole('dialog',{name:'导出脱敏诊断',exact:true});await page.evaluate(()=>{const original=IDBObjectStore.prototype.getAll;let armed=true;IDBObjectStore.prototype.getAll=function(...args:Parameters<typeof original>){if(armed&&this.name==='diagnostics'){armed=false;throw new DOMException('native-diagnostic-export-read','UnknownError');}return original.apply(this,args);};});await dialog.getByRole('button',{name:'确认导出诊断',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'诊断导出失败，未发送报告；原记录保留。'})).toBeVisible();expect(await state(page)).toEqual(before);
 await holdNextNativeCommit(page,'diagnostics','readonly');const pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'确认导出诊断',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});try{await expect(dialog.getByRole('button',{name:'确认导出诊断',exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'取消',exact:true})).toBeDisabled();expect(await state(page)).toEqual(before);}finally{await releaseNativeCommit(page);}const download=await pending,document=JSON.parse((await readFile((await download.path())!)).toString());expect(document.records.some((row:{id:string;executionState:string})=>row.id==='video-run-unknown'&&row.executionState==='submit_unknown')).toBe(true);expect(JSON.stringify(document)).not.toContain('fake-task-key');expect(JSON.stringify(document)).not.toMatch(/requestSnapshot|finalBody|idempotencyKey/);expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 H04 native diagnostic deletion failure rolls back its display transaction and busy retry retains all functional history',async({page,networkCounter})=>{
 const before=await state(page);await page.getByRole('button',{name:'清理活动显示',exact:true}).click();const dialog=page.getByRole('dialog',{name:'清理本地活动显示',exact:true});await page.evaluate(()=>{const original=IDBObjectStore.prototype.delete;let armed=true;IDBObjectStore.prototype.delete=function(...args:Parameters<typeof original>){if(armed&&this.name==='diagnostics'){armed=false;throw new DOMException('native-diagnostic-delete-failed','UnknownError');}return original.apply(this,args);};});await dialog.getByRole('button',{name:'确认清理显示',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'清理失败，原记录保留。'})).toBeVisible();expect(await state(page)).toEqual(before);
 await holdNextNativeCommit(page,'diagnostics');await dialog.getByRole('button',{name:'确认清理显示',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});try{await expect(dialog.getByRole('button',{name:'确认清理显示',exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'取消',exact:true})).toBeDisabled();const actual=await state(page);expect(actual.runs).toEqual(before.runs);expect(actual.promptRuns).toEqual(before.promptRuns);expect(actual.projects).toEqual(before.projects);expect(actual.graphs).toEqual(before.graphs);expect(actual.receipts).toEqual(before.receipts);expect(actual.diagnostics.some((row:{id:string})=>row.id==='display-only-test')).toBe(false);}finally{await releaseNativeCommit(page);}await expect(dialog).toHaveCount(0);await expect(page.getByRole('status').filter({hasText:'未知提交、追踪身份和恢复日志保留'})).toBeVisible();expect(networkCounter.paidRequests).toHaveLength(0);
});
