import {test,expect} from '../helpers/network-guard';
import {seedStudio} from '../helpers/seed-studio';
import type {Page} from '@playwright/test';
import {startCompanion} from '../../companion/src/server';
const state=(page:Page)=>page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['projects','graphs','runs','diagnostics','proposals','receipts'],'readonly',async(tx:IDBTransaction)=>Object.fromEntries(await Promise.all(['projects','graphs','runs','diagnostics','proposals','receipts'].map(async table=>[table,await m.requestResult(tx.objectStore(table).getAll())]))));}finally{db.close();}});
async function boot(page:Page){await seedStudio(page,'unverified-capability');await page.goto('/projects/p1/agent');await expect(page.getByRole('heading',{name:'Agent 协作',exact:true})).toBeVisible();}
async function pair(page:Page){const relay=await startCompanion({allowedOrigins:['http://127.0.0.1:4179']});await page.route(new RegExp('^http://127[.]0[.]0[.]1:4179/canvas/(connect|authorize|heartbeat|disconnect|poll|reply)$'),async route=>{const req=route.request(),headers={...req.headers(),origin:'http://127.0.0.1:4179'};delete(headers as Record<string,string>).host;const response=await fetch(relay.url+new URL(req.url()).pathname,{method:req.method(),headers,body:req.postData(),redirect:'error'});await route.fulfill({status:response.status,contentType:'application/json',body:await response.text()});});await page.getByRole('button',{name:'连接本地 Agent',exact:true}).click();const dialog=page.getByRole('dialog',{name:'连接本地 Agent',exact:true});await dialog.getByLabel('本机连接地址',{exact:true}).fill(locationOrigin);await dialog.getByLabel('独立临时配对令牌',{exact:true}).fill(relay.token);await dialog.getByRole('button',{name:'连接并默认只读',exact:true}).click();await expect(page.getByText('已连接 · 只读',{exact:true})).toBeVisible();return relay;}
const locationOrigin='http://127.0.0.1:4179';

test('T44 A01 actual rejected local pairing never creates a session or changes the original creative and execution records',async({page,networkCounter})=>{
 await boot(page);await expect(page.locator('[data-interaction-id="A-11"]')).toBeDisabled();await expect(page.locator('[data-interaction-id="A-12"]')).toBeDisabled();const before=await state(page);await page.route('**/canvas/connect',route=>route.fulfill({status:503,contentType:'application/json',body:'{"ok":false,"errorCode":"local_unavailable"}'}));await page.getByRole('button',{name:'连接本地 Agent',exact:true}).click();const dialog=page.getByRole('dialog',{name:'连接本地 Agent',exact:true});await dialog.getByLabel('本机连接地址',{exact:true}).fill(locationOrigin);await dialog.getByLabel('独立临时配对令牌',{exact:true}).fill('studio-agent-'+'a'.repeat(43));await dialog.getByRole('button',{name:'连接并默认只读',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('连接失败');expect(await state(page)).toEqual(before);expect(await page.evaluate(async()=>{const p='/src/features/agent/agent-client.ts';return (await import(p)).getProjectAgentSession('p1');})).toBeUndefined();expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 A02/A12 failed authorization retains the old scope; successful local grant stays memory-only and failed revocation honestly removes local permission',async({page,networkCounter})=>{
 await boot(page);const relay=await pair(page);try{const before=await state(page),original=await page.evaluate(async()=>{const p='/src/features/agent/agent-client.ts';return (await import(p)).getProjectAgentSession('p1');});await page.getByLabel('上下文范围',{exact:true}).selectOption('project');await page.getByRole('button',{name:'预览并管理授权',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Agent 项目授权',exact:true});await dialog.getByLabel('我明确允许读取整个项目的已保存节点',{exact:true}).check();const reject=async(route:import('@playwright/test').Route)=>route.fulfill({status:503,contentType:'application/json',body:'{"ok":false,"errorCode":"local_unavailable"}'});await page.route('**/canvas/authorize',reject);await dialog.getByRole('button',{name:'授予所列权限',exact:true}).click();await expect(dialog.getByRole('alert')).toHaveText('授权未更新，请检查本机连接、当前标签写权或有效期。');expect(await page.evaluate(async()=>{const p='/src/features/agent/agent-client.ts';return (await import(p)).getProjectAgentSession('p1');})).toEqual(original);expect(await state(page)).toEqual(before);await page.unroute('**/canvas/authorize',reject);await dialog.getByRole('button',{name:'授予所列权限',exact:true}).click();await expect(page.getByText('已授权 · 整个项目 · 只读',{exact:true})).toBeVisible();expect(await page.evaluate(async()=>{const p='/src/features/agent/agent-client.ts';return (await import(p)).getProjectAgentSession('p1').grant;})).toMatchObject({projectId:'p1',scope:'project',access:'read',nodeIds:[]});expect(await state(page)).toEqual(before);
 await page.route('**/canvas/disconnect',reject);await page.locator('[data-interaction-id="A-12"]').click();await expect(page.getByRole('status').filter({hasText:'本地已断开；服务撤权回执未知'})).toBeVisible();await expect(page.locator('[data-interaction-id="A-12"]')).toBeDisabled();await expect(page.locator('[data-interaction-id="A-11"]')).toBeDisabled();expect(await page.evaluate(async()=>{const p='/src/features/agent/agent-client.ts';return (await import(p)).getProjectAgentSession('p1');})).toBeUndefined();expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);}finally{await relay.close();}
});

test('T44 A13/A14 native local conversation create and delete faults retain existing descriptions and all original task records',async({page,networkCounter})=>{
 await boot(page);const before=await state(page);await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;let armed=true;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(armed&&this.name==='receipts'){armed=false;throw new DOMException('native-agent-conversation-create','QuotaExceededError');}return original.apply(this,args);};});await page.getByRole('button',{name:'新本地会话',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'本地会话或关联索引未保存'})).toBeVisible();expect(await state(page)).toEqual(before);await page.getByRole('button',{name:'新本地会话',exact:true}).click();await expect(page.getByText('已创建空本地会话；画布和旧提案保留。',{exact:true})).toBeVisible();await expect(page.getByLabel('本地会话',{exact:true})).not.toHaveValue('');const created=await state(page);expect(created.runs).toEqual(before.runs);await page.getByRole('button',{name:'删除本地会话',exact:true}).click();const dialog=page.getByRole('dialog',{name:'删除本地 Agent 会话',exact:true});await dialog.getByLabel('我确认删除这些本地对话记录',{exact:true}).check();await page.evaluate(()=>{const original=IDBObjectStore.prototype.delete;let armed=true;IDBObjectStore.prototype.delete=function(...args:Parameters<typeof original>){if(armed&&this.name==='receipts'){armed=false;throw new DOMException('native-agent-conversation-delete','QuotaExceededError');}return original.apply(this,args);};});await dialog.getByRole('button',{name:'确认删除本地会话',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'本地会话未确认删除'})).toBeVisible();await expect(dialog).toBeVisible();expect(await state(page)).toEqual(created);expect(networkCounter.paidRequests).toHaveLength(0);
});
