import {test,expect} from '../helpers/network-guard';
import {localDeployment} from '../helpers/deployment-fixture';
import {f} from '../helpers/fixtures';
test('API status separates text/video, permits memory-Key recheck and invalidates on clear/reload without paid requests',async({page,networkCounter},testInfo)=>{
 await page.route('**/studio-deployment.json',route=>route.fulfill({contentType:'application/json',body:JSON.stringify(localDeployment)}));
 await page.route('**/core-api/healthz',route=>route.fulfill({contentType:'application/json',body:'{"status":"ok"}'}));
 await page.route('**/core-api/v1/models',route=>route.fulfill({contentType:'application/json',body:'{"data":[{"id":"fake-text-only"},{"id":"fake-video-only"}]}'}));
 await page.goto('/settings/connections');const global=page.locator('[data-interaction-id="G-05"]');await expect(global).toContainText('文字：');await expect(global).toContainText('视频：');
 await page.getByLabel('连接名称',{exact:true}).fill('API状态隔离测试');await page.getByLabel('Core 服务地址',{exact:true}).fill('https://core.invalid');await page.getByRole('button',{name:'保存连接地址',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'连接地址已保存'})).toBeVisible();await page.getByLabel('普通用户 Key',{exact:true}).fill('fake-api-status-key');await page.getByRole('button',{name:'测试连接',exact:true}).click();
 await expect(page.getByRole('status').filter({hasText:'健康与模型目录只读核验成功'})).toBeVisible();await expect(page.getByLabel('普通用户 Key',{exact:true})).toHaveValue('');await expect(page.getByRole('button',{name:'测试连接',exact:true})).toBeEnabled();await expect(page.getByLabel('视频 API 状态',{exact:true})).toContainText('上次连接测试');
 await expect(global).toContainText('文字（Core回退）：');await expect(page.getByLabel('文字 API 状态',{exact:true})).toContainText('独立文字：配置缺失');await expect(page.getByLabel('文字 API 状态',{exact:true})).toContainText('独立文字 Key 未启用');
 await page.getByRole('button',{name:'测试连接',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'健康与模型目录只读核验成功'})).toBeVisible();await page.screenshot({path:testInfo.outputPath('api-status-readonly.png'),fullPage:true});
 await page.getByRole('button',{name:'清除当前 Key',exact:true}).click();await expect(page.getByLabel('视频 API 状态',{exact:true})).toContainText('本标签页未授权');await expect(global).not.toContainText('真实生成已验证');await page.reload();await expect(page.getByLabel('视频 API 状态',{exact:true})).toContainText('本标签页未授权');await expect(page.getByLabel('视频 API 状态',{exact:true})).toContainText('上次');expect(networkCounter.paidRequests).toHaveLength(0);
});
test('leaving a pending readonly check cancels it and never commits a late catalog or active binding',async({page,networkCounter})=>{
 let release!:()=>void,seen!:()=>void;const gate=new Promise<void>(r=>release=r),requested=new Promise<void>(r=>seen=r);
 await page.route('**/studio-deployment.json',route=>route.fulfill({contentType:'application/json',body:JSON.stringify(localDeployment)}));await page.route('**/core-api/healthz',route=>route.fulfill({contentType:'application/json',body:'{"status":"ok"}'}));await page.route('**/core-api/v1/models',async route=>{seen();await gate;await route.fulfill({contentType:'application/json',body:'{"data":[{"id":"fake-text-only"}]}'}).catch(()=>{});});
 await page.goto('/settings/connections');await page.getByLabel('连接名称',{exact:true}).fill('隔离取消检查');await page.getByLabel('Core 服务地址',{exact:true}).fill('https://core.invalid');await page.getByRole('button',{name:'保存连接地址',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'连接地址已保存'})).toBeVisible();await page.getByLabel('普通用户 Key',{exact:true}).fill('fake-canceled-status-key');await page.getByRole('button',{name:'测试连接',exact:true}).click();await requested;await expect(page.getByLabel('视频 API 状态',{exact:true})).toContainText('检测中');await page.getByRole('link',{name:'项目',exact:true}).click();await expect(page.getByRole('heading',{name:'项目',exact:true})).toBeVisible();release();
 const actual=await page.evaluate(async()=>{const c='/src/adapters/core/current-connection.ts',d='/src/infrastructure/storage/database.ts',s='/src/features/settings/connection-status.ts',core=await import(c),db=await import(d),status=await import(s);return {active:!!core.getActiveCore(),checking:status.isConnectionChecking('video'),receipts:await db.withDatabase(undefined,(connection:import('../../src/infrastructure/storage/database').StudioDb)=>db.transact(connection,['receipts'],'readonly',(tx:IDBTransaction)=>db.requestResult(tx.objectStore('receipts').getAll()) as Promise<{kind?:string}[]>))};});expect(actual.active).toBe(false);expect(actual.checking).toBe(false);expect(actual.receipts.filter((r:{kind?:string})=>['readonly-model-catalog','connection-session'].includes(r.kind??''))).toEqual([]);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('independent text catalog requires model/enable, memory authorization survives recheck and remains unverified for real generation',async({page,networkCounter},testInfo)=>{
 const profile=f.connection({id:'text-status',name:'隔离文字连接',originSnapshot:'https://text.example.invalid/v1',proxyBase:'/text-api/registered/text-status',contractVersion:'openai-compatible-text-v1'});
 const entry={profile,contract:{...localDeployment.connections[0].contract,version:profile.contractVersion,textModels:['fake-text-only'],videoModels:[],videoSpecs:[]}};
 await page.route('**/studio-deployment.json',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({...localDeployment,connections:[...localDeployment.connections,entry]})}));
 await page.route('**/studio-session.json',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({nonce:'a'.repeat(64)})}));
 await page.route('**/studio-api/connections',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({profile})}));
 await page.route('**/text-api/registered/text-status/v1/models',route=>route.fulfill({contentType:'application/json',body:'{"data":[{"id":"fake-text-only"},{"id":"fake-video-only"}]}'}));
 await page.goto('/settings/connections');await page.getByLabel('文字 API 地址',{exact:true}).fill(profile.originSnapshot);await page.getByLabel('文字 API Key',{exact:true}).fill('fake-text-status-key');await page.getByRole('button',{name:'测试文字 API（只读）',exact:true}).click();const status=page.getByLabel('文字 API 状态',{exact:true});await expect(status).toContainText('待选模型');await expect(page.getByLabel('文字 API Key',{exact:true})).toHaveValue('');await expect(page.getByRole('button',{name:'测试文字 API（只读）',exact:true})).toBeEnabled();await page.getByLabel('独立文字模型',{exact:true}).selectOption('fake-text-only');await expect(status).toContainText('待启用文字');await expect(page.getByRole('button',{name:'启用独立文字连接',exact:true})).toBeDisabled();await page.locator('[data-interaction-id="text-api:ack"]').check();await page.getByRole('button',{name:'启用独立文字连接',exact:true}).click();await expect(status).toContainText('已连接');await expect(status).toContainText('连接检查通过，生成待验证');await expect(page.locator('[data-interaction-id="G-05"]')).toContainText('文字：已连接');await page.getByRole('link',{name:'前往提示词AI优化',exact:true}).click();await expect(page.getByRole('heading',{name:'提示词生成',exact:true})).toBeVisible();await page.getByRole('link',{name:'设置',exact:true}).click();await expect(page.getByLabel('文字 API 地址',{exact:true})).toHaveValue(profile.originSnapshot);await expect(page.getByLabel('独立文字模型',{exact:true})).toHaveValue('fake-text-only');await expect(page.getByLabel('文字 API 状态',{exact:true})).toContainText('已连接');await page.getByRole('button',{name:'测试文字 API（只读）',exact:true}).click();await expect(page.getByLabel('文字 API 状态',{exact:true})).toContainText('已连接');await page.screenshot({path:testInfo.outputPath('api-status-text-enabled.png'),fullPage:true});await page.getByRole('button',{name:'清除文字 Key',exact:true}).click();await expect(page.getByLabel('文字 API 状态',{exact:true})).toContainText('本标签页未授权');await expect(page.locator('[data-interaction-id="G-05"]')).not.toContainText('真实生成已验证');expect(networkCounter.paidRequests).toHaveLength(0);
});
