import {test,expect} from '../helpers/network-guard';
import {holdNextNativeCommit,releaseNativeCommit,nativeCommitProbe} from '../helpers/native-commit-hold';
import type {Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(async()=>{const p='/tests/fixtures/asset-library.ts';return(await import(p)).storedAssets();});
async function deny(page:Page,table:string,method:'put'|'get'|'getAll'='put'){await page.evaluate(({target,operation})=>{const original=IDBObjectStore.prototype[operation];let armed=true;Reflect.set(IDBObjectStore.prototype,operation,function(this:IDBObjectStore,...args:unknown[]){if(armed&&this.name===target){armed=false;throw new DOMException('native-asset-operation-quota','QuotaExceededError');}return Reflect.apply(original,this,args);});},{target:table,operation:method});}
test.beforeEach(async({page})=>{await page.goto('/assets');await page.evaluate(async()=>{const p='/tests/fixtures/asset-library.ts';await(await import(p)).seedAssetLibrary();});await page.reload();});

test('T44 M08/M09 native insert and draft replacement failures preserve the original media identities, graph and historical attempts',async({page,networkCounter})=>{
 const before=await state(page);await page.getByRole('button',{name:'详情 声音440.wav',exact:true}).click();await page.getByRole('button',{name:'添加到画布',exact:true}).click();let dialog=page.getByRole('dialog',{name:'选择目标项目',exact:true});await deny(page,'graphs');await dialog.getByRole('button',{name:'插入 素材项目',exact:true}).click();await expect(dialog.getByRole('alert')).toHaveText('操作失败，修改尚未保存，请检查名称、标签限制或本地空间。');expect(await state(page)).toEqual(before);await dialog.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('button',{name:'替换草稿输入',exact:true}).click();await dialog.getByRole('button',{name:'替换 素材项目 / 图片引用',exact:true}).click();dialog=page.getByRole('dialog').filter({has:page.getByRole('button',{name:'确认替换草稿输入',exact:true})});await deny(page,'graphs');await dialog.getByRole('button',{name:'确认替换草稿输入',exact:true}).click();await expect(dialog.getByRole('alert')).toHaveText('操作失败，修改尚未保存，请检查名称、标签限制或本地空间。');expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 M12 native deletion-impact read and deletion write failures keep all original media; pending inspection prevents duplicate deletion entry',async({page,networkCounter})=>{
 const before=await state(page);await page.getByRole('button',{name:'详情 参考.png',exact:true}).click();await deny(page,'graphs','getAll');await page.getByRole('button',{name:'移到回收站',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('操作失败，修改尚未保存，请检查名称、标签限制或本地空间。');expect(await state(page)).toEqual(before);await holdNextNativeCommit(page,'graphs','readonly');await page.getByRole('button',{name:'移到回收站',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});try{await expect(page.getByRole('button',{name:'移到回收站',exact:true})).toBeDisabled();expect(await state(page)).toEqual(before);}finally{await releaseNativeCommit(page);}const dialog=page.getByRole('dialog',{name:'移入素材回收站',exact:true});await expect(dialog).toBeVisible();await deny(page,'assets');await dialog.getByRole('button',{name:'确认移入素材回收站',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('未保存');expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 M15 actual reference navigation with a failed native graph read reports the unreadable target and keeps the original media and tasks',async({page,networkCounter})=>{
 const before=await state(page);await page.getByRole('button',{name:'详情 参考.png',exact:true}).click();await deny(page,'graphs','get');await page.getByRole('link',{name:'定位 素材项目 / 图片引用',exact:true}).click();await expect(page).toHaveURL(/\/projects\/p1\/canvas\?node=asset-node$/);await expect(page.getByRole('alert')).toBeVisible();expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
