import {test,expect} from '../helpers/network-guard';
import {holdNextNativeCommit,releaseNativeCommit,nativeCommitProbe} from '../helpers/native-commit-hold';
import type {Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(async()=>{const p='/tests/fixtures/asset-library.ts';return (await import(p)).storedAssets();});
test.beforeEach(async({page})=>{await page.goto('/assets');await page.evaluate(async()=>{const p='/tests/fixtures/asset-library.ts';await (await import(p)).seedAssetLibrary();});await page.reload();});

test('T44 M01/M02 actual native import completion blocks duplicate file selection and confirmation until acknowledgement',async({page,networkCounter})=>{
 const before=await state(page),bytes=await page.evaluate(async()=>{const p='/tests/fixtures/asset-library.ts';return Array.from(new Uint8Array(await (await import(p)).wave(880).arrayBuffer()));});await page.getByLabel('导入素材',{exact:true}).setInputFiles({name:'声音880.wav',mimeType:'audio/wav',buffer:Buffer.from(bytes)});const dialog=page.getByRole('dialog',{name:'文件导入检查',exact:true});await expect(dialog).toContainText('有效 1 个');await holdNextNativeCommit(page,'blobs');await dialog.getByRole('button',{name:'确认导入 1 个有效文件',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});
 try{await expect(page.getByLabel('导入素材',{exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'确认导入 1 个有效文件',exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'取消导入',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(dialog).toBeVisible();const actual=await state(page);expect(actual.assets).toHaveLength(before.assets.length+1);expect(actual.assets.some((row:{title:string})=>row.title==='声音880.wav')).toBe(true);expect(actual.graph).toEqual(before.graph);expect(actual.runs).toEqual(before.runs);}finally{await releaseNativeCommit(page);}
 await expect(dialog).toHaveCount(0);await expect(page.getByLabel('导入素材',{exact:true})).toBeEnabled();await page.reload();await expect(page.getByRole('button',{name:'详情 声音880.wav',exact:true})).toBeVisible();expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 M07 actual native metadata save pending disables its submit while original hash and all Runs remain intact',async({page,networkCounter})=>{
 const before=await state(page);await page.getByRole('button',{name:'详情 参考.png',exact:true}).click();await page.getByLabel('素材名称',{exact:true}).fill('等待提交确认的参考');await holdNextNativeCommit(page,'assets');await page.getByRole('button',{name:'保存素材信息',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});try{await expect(page.getByRole('button',{name:'保存素材信息',exact:true})).toBeDisabled();const actual=await state(page);expect(actual.assets.find((row:{title:string})=>row.title==='等待提交确认的参考').sha256).toBe(before.assets.find((row:{title:string})=>row.title==='参考.png').sha256);expect(actual.runs).toEqual(before.runs);expect(actual.blobs).toEqual(before.blobs);}finally{await releaseNativeCommit(page);}await expect(page.getByRole('button',{name:'保存素材信息',exact:true})).toBeEnabled();await expect(page.getByRole('status').filter({hasText:'素材信息已保存'})).toBeVisible();expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 M11 actual native original read acknowledgement disables only its local download until the same bytes are available',async({page,networkCounter})=>{
 const before=await state(page);await page.getByRole('button',{name:'详情 参考.png',exact:true}).click();await expect(page.getByRole('complementary',{name:'素材详情',exact:true}).getByRole('img',{name:'参考.png',exact:true})).toBeVisible();await holdNextNativeCommit(page,'blobs','readonly');const pending=page.waitForEvent('download');await page.getByRole('button',{name:'下载原素材',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});try{await expect(page.getByRole('button',{name:'下载原素材',exact:true})).toBeDisabled();expect(await state(page)).toEqual(before);}finally{await releaseNativeCommit(page);}const download=await pending;expect(download.suggestedFilename()).toBe('参考.png');await expect(page.getByRole('button',{name:'下载原素材',exact:true})).toBeEnabled();expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
