import {test,expect} from '../helpers/network-guard';import {seedStudio} from '../helpers/seed-studio';
const graph=(page:import('@playwright/test').Page)=>page.evaluate(async()=>{const p='/src/infrastructure/storage/project-repository.ts';return(await import(p)).readGraph('p1');});
const actions=[
 {id:'C-10',name:'adding a text node',select:[],trigger:'添加节点',confirm:'文本节点'},
 {id:'N-02',name:'renaming a node',select:['镜头文字'],trigger:'title',confirm:'保存'},
 {id:'N-04',name:'pasting copied structure',select:['镜头文字'],copy:true,trigger:'粘贴节点'},
 {id:'N-05',name:'creating a local branch',select:['视频草稿'],trigger:'复制为分支'},
 {id:'N-06',name:'removing placement',select:['镜头文字'],trigger:'删除选中节点',confirm:'确认删除节点'},
 {id:'N-07',name:'locking a node',select:['镜头文字'],trigger:'锁定选中'},
 {id:'N-08',name:'grouping selected nodes',select:['镜头文字','参考一'],trigger:'组合选中',confirm:'创建分组'},
 {id:'N-09',name:'ungrouping nodes',select:['镜头组'],group:true,trigger:'取消组合'},
 {id:'N-10',name:'collapsing a group',select:['镜头组'],group:true,trigger:'收起分组'},
 {id:'N-11',name:'aligning nodes',select:['镜头文字','参考一'],trigger:'对齐顶部',confirm:'应用布局'},
 {id:'N-12',name:'arranging the graph',select:[],trigger:'整理布局',confirm:'应用布局'},
 {id:'N-18',name:'editing shot group metadata',select:['镜头组'],group:true,trigger:'镜头分组命名',confirm:'保存镜头分组'},
 {id:'N-19',name:'selecting a fixed result',select:['固定结果'],trigger:'选用此结果',confirm:'确认选用'},
] as const;
for(const action of actions)test('T44 '+action.id+' native write failure while '+action.name+' rolls back creative changes and cannot submit',async({page,networkCounter})=>{
 await seedStudio(page,'unverified-capability');if('group'in action)await page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{await m.transact(db,['graphs'],'readwrite',async(tx:IDBTransaction)=>{const g=await m.requestResult(tx.objectStore('graphs').get('p1')),group=g.nodes.find((n:{id:string})=>n.id==='group-1'),text=g.nodes.find((n:{id:string})=>n.id==='text-1');group.data.childIds=['text-1'];text.x-=group.x;text.y-=group.y;tx.objectStore('graphs').put(g);});}finally{db.close();}});await page.goto('/projects/p1/canvas');for(const name of action.select)await page.getByLabel('选择 '+name,{exact:true}).check();if('copy'in action)await page.getByRole('button',{name:'复制节点',exact:true}).click();const before=await graph(page);await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof put>){if(this.name==='graphs'){IDBObjectStore.prototype.put=put;throw new DOMException('test-canvas-command-abort','QuotaExceededError');}return put.apply(this,args);};});if(action.trigger==='title')await page.getByRole('button',{name:'编辑标题 镜头文字',exact:true}).press('Enter');else await page.getByRole('button',{name:action.trigger,exact:true}).click();if(action.id==='N-02')await page.getByLabel('节点标题',{exact:true}).fill('未成功落盘的新标题');if('confirm'in action)await page.getByRole('button',{name:action.confirm,exact:true}).click();await expect(page.locator('.canvas-heading [role="status"]')).toContainText('尚未保存');expect(await graph(page)).toEqual(before);const recovery=await page.evaluate(async()=>{const p='/src/features/recovery/memory-recovery.ts';return(await import(p)).readMemoryRecoveries();});expect(recovery.some((r:{project:{id:string}})=>r.project.id==='p1')).toBe(true);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 canvas readonly writer gate disables every visible creative mutation and title keyboard entry preserves the graph',async({page,networkCounter})=>{
 await seedStudio(page,'unverified-capability');await page.evaluate(async()=>{const p='/src/infrastructure/storage/project-lease.ts';await(await import(p)).acquireProjectLease('p1','another-actual-writer',Date.now());const d='/src/infrastructure/storage/database.ts',m=await import(d),db=await m.openStudioDb();try{await m.transact(db,['graphs'],'readwrite',async(tx:IDBTransaction)=>{const g=await m.requestResult(tx.objectStore('graphs').get('p1'));g.edges=[{id:'readonly-text',sourceId:'text-1',targetId:'video-1',port:'text',order:0},{id:'readonly-image-1',sourceId:'asset-1',targetId:'video-1',port:'image',order:1},{id:'readonly-image-2',sourceId:'asset-2',targetId:'video-1',port:'image',order:2}];tx.objectStore('graphs').put(g);});}finally{db.close();}});await page.goto('/projects/p1/canvas');await expect(page.getByText('只读 · 另一标签持有写权',{exact:true})).toBeVisible();await page.getByLabel('选择 镜头文字',{exact:true}).check();await page.getByLabel('选择 参考一',{exact:true}).check();for(const id of ['C-10','N-04','N-05','N-06','N-07','N-08','N-09','N-11','N-12','N-13','N-14','N-15','N-16','T-03','T-08','V-01','V-02','V-03','V-04','V-07']){const controls=page.locator('[data-interaction-id="'+id+'"]');await expect(controls).not.toHaveCount(0);for(let i=0;i<await controls.count();i++)await expect(controls.nth(i)).toBeDisabled();}const before=await graph(page),title=page.getByRole('button',{name:'编辑标题 镜头文字',exact:true});await expect(title).toHaveAttribute('aria-disabled','true');await title.press('Enter');await expect(page.getByRole('dialog',{name:'编辑节点标题',exact:true})).not.toBeVisible();expect(await graph(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
