import {test,expect} from '../helpers/network-guard';
import {seedStudio} from '../helpers/seed-studio';
test.use({actionTimeout:2500});test.setTimeout(15000);
async function stored(page:import('@playwright/test').Page){return page.evaluate(async()=>{const path='/src/infrastructure/storage/database.ts';const {openStudioDb,transact,requestResult}=await import(path) as typeof import('../../src/infrastructure/storage/database');const db=await openStudioDb();try{return await transact(db,['graphs','runs','assets'],'readonly',async tx=>({graph:await requestResult(tx.objectStore('graphs').get('p1')),runs:await requestResult(tx.objectStore('runs').getAll()),assets:await requestResult(tx.objectStore('assets').getAll())}));}finally{db.close();}});}
test.beforeEach(async({page})=>{await seedStudio(page,'unverified-capability');await page.goto('/projects/p1/canvas');});
test('T15-C01: duplicate uses new ID and 24px offset, without creating an execution',async({page,networkCounter})=>{await page.getByLabel('选择 镜头文字',{exact:true}).check();await page.getByTestId('canvas-stage').focus();await page.keyboard.press('Control+d');await expect(page.locator('[data-node-type="text"]')).toHaveCount(2);const state=await stored(page),copy=state.graph.nodes.find((n:{id:string;type:string})=>n.type==='text'&&n.id!=='text-1');expect(copy).toMatchObject({x:44,y:44});expect(state.runs).toHaveLength(1);expect(networkCounter.paidRequests).toHaveLength(0);});
test('T15-C02/C03: grouping/ungrouping preserves world positions; collapse preserves dependencies',async({page})=>{await page.getByLabel('选择 镜头文字',{exact:true}).check();await page.getByLabel('选择 视频草稿',{exact:true}).check();const before=await stored(page);await page.getByRole('button',{name:'组合选中',exact:true}).click();const dialog=page.getByRole('dialog',{name:'新建分组'});await dialog.getByLabel('镜头分组名称',{exact:true}).fill('镜头甲');await dialog.getByRole('button',{name:'创建分组',exact:true}).click();await expect(page.getByLabel('选择 镜头甲',{exact:true})).toBeChecked();let state=await stored(page);const group=state.graph.nodes.find((n:{title:string})=>n.title==='镜头甲'),child=state.graph.nodes.find((n:{id:string})=>n.id==='text-1');expect(child.x+group.x).toBe(20);expect(child.y+group.y).toBe(20);await page.getByRole('button',{name:'收起分组',exact:true}).click();await expect(page.getByTestId('node-text-1')).toHaveCount(0);expect((await stored(page)).graph.edges).toEqual(before.graph.edges);await page.getByRole('button',{name:'展开分组',exact:true}).click();await page.getByRole('button',{name:'取消组合',exact:true}).click();state=await stored(page);expect(state.graph.nodes.find((n:{id:string})=>n.id==='text-1')).toMatchObject({x:20,y:20});});
test('T15-C04: layout is previewed, Cancel preserves revision, Apply commits once without topology changes',async({page})=>{await page.getByLabel('选择 镜头文字',{exact:true}).check();await page.getByLabel('选择 参考一',{exact:true}).check();await page.getByRole('button',{name:'对齐顶部',exact:true}).click();const dialog=page.getByRole('dialog',{name:'预览布局'});await expect(dialog).toBeVisible();expect((await stored(page)).graph.revision).toBe(1);await page.screenshot({path:'docs/review/screenshots/T15-layout-preview.png'});await dialog.getByRole('button',{name:'取消',exact:true}).click();expect((await stored(page)).graph.revision).toBe(1);await page.getByRole('button',{name:'对齐顶部',exact:true}).click();await dialog.getByRole('button',{name:'应用布局',exact:true}).click();await expect.poll(async()=>(await stored(page)).graph.revision).toBe(2);expect((await stored(page)).graph.nodes.find((n:{id:string})=>n.id==='asset-1').y).toBe(20);expect((await stored(page)).graph.edges).toEqual([]);});
test('T15-C05: deleting a node preserves shared media and original Run, undo restores placement',async({page})=>{await page.getByLabel('选择 视频草稿',{exact:true}).check();const before=await stored(page);await page.getByRole('button',{name:'删除选中节点',exact:true}).click();const dialog=page.getByRole('dialog',{name:'删除节点'});await expect(dialog.getByText('任务与素材记录会保留，不取消生成或退款。',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'确认删除节点',exact:true}).click();await expect(page.getByTestId('node-video-1')).toHaveCount(0);expect((await stored(page)).runs).toEqual(before.runs);expect((await stored(page)).assets).toEqual(before.assets);await page.getByRole('button',{name:'撤销',exact:true}).click();await expect(page.getByTestId('node-video-1')).toBeVisible();});
test('T15-C06: marking a fixed result changes only selection revision and downstream drafts',async({page,networkCounter})=>{await page.getByLabel('选择 固定结果',{exact:true}).check();const before=await stored(page);await page.getByRole('button',{name:'选用此结果',exact:true}).click();const dialog=page.getByRole('dialog',{name:'选用固定结果'});await dialog.getByRole('button',{name:'确认选用',exact:true}).click();await expect.poll(async()=>(await stored(page)).graph.revision).toBe(2);expect((await stored(page)).runs).toEqual(before.runs);expect((await stored(page)).graph.nodes.find((n:{id:string})=>n.id==='result-1').data).toMatchObject({assetId:'a3',runId:'r1',selectionRevision:1});expect(networkCounter.paidRequests).toHaveLength(0);});
test('T15 menu: lock rejects movement; branch duplicates draft inputs with no approval',async({page,networkCounter})=>{await page.getByTestId('node-video-1').getByTestId('node-handle').click({button:'right'});const menu=page.getByRole('dialog',{name:'节点操作'});await menu.getByRole('button',{name:'复制为分支',exact:true}).click();await expect(page.locator('[data-node-type="video-generation"]')).toHaveCount(2);expect((await stored(page)).runs).toHaveLength(1);await page.getByLabel('选择 镜头文字',{exact:true}).check();await page.getByRole('button',{name:'锁定选中',exact:true}).click();await expect(page.getByTestId('node-text-1').getByTestId('node-handle')).toContainText('已锁定');expect(networkCounter.paidRequests).toHaveLength(0);});
test('QA08 N-05: text node can create a local branch when video execution capability is unknown',async({page,networkCounter})=>{
 await page.getByLabel('选择 镜头文字',{exact:true}).check();
 const branch=page.getByRole('button',{name:'复制为分支',exact:true});
 await expect(branch).toBeEnabled();
 await branch.click();
 await expect(page.locator('[data-node-type="video-generation"]')).toHaveCount(2);
 const generationEntries=page.getByRole('button',{name:'生成视频',exact:true});await expect(generationEntries).toHaveCount(2);for(const entry of await generationEntries.all())await expect(entry).toBeDisabled();
 const state=await stored(page);
 expect(state.graph.edges.some((edge:{sourceId:string;targetId:string})=>edge.sourceId==='text-1'&&state.graph.nodes.some((node:{id:string;type:string})=>node.id===edge.targetId&&node.type==='video-generation'&&node.id!=='video-1'))).toBe(true);
 expect(state.runs).toHaveLength(1);
 expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T15 clipboard: omitted external inputs remain a persisted warning after refresh',async({page})=>{const video=page.getByTestId('node-video-1');await video.getByRole('button',{name:'选择输入',exact:true}).click();await page.getByRole('dialog',{name:'选择输入'}).getByRole('button',{name:'连接 镜头文字',exact:true}).click();await page.getByLabel('选择 视频草稿',{exact:true}).check();await page.getByTestId('canvas-stage').focus();await page.keyboard.press('Control+d');await expect(page.locator('[data-node-type="video-generation"]')).toHaveCount(2);await page.reload();await expect(page.getByText('缺少复制前的外部输入，请明确重新连接。',{exact:true})).toBeVisible();});
test('T15 outline filters and sort preserve graph/references and indicate empty results',async({page})=>{const before=await stored(page);await page.getByRole('combobox',{name:'节点类型',exact:true}).selectOption('result');await expect(page.getByLabel('选择 固定结果',{exact:true})).toBeVisible();await expect(page.getByLabel('选择 镜头文字',{exact:true})).toHaveCount(0);await page.getByRole('combobox',{name:'大纲排序',exact:true}).selectOption('title');await page.getByLabel('查找节点',{exact:true}).fill('不存在的镜头');await expect(page.getByText('没有匹配节点',{exact:true})).toBeVisible();expect((await stored(page)).graph).toEqual(before.graph);});
test('T15 save acknowledgement: a display read error after commit never reports an unsaved transaction',async({page})=>{await page.getByLabel('选择 镜头文字',{exact:true}).check();await page.evaluate(()=>{const original=IDBObjectStore.prototype.getAll;let calls=0;IDBObjectStore.prototype.getAll=function(...args:Parameters<IDBObjectStore['getAll']>){if(this.name==='assets'&&++calls===2)throw new DOMException('display read fault','UnknownError');return original.apply(this,args);};});await page.getByTestId('canvas-stage').focus();await page.keyboard.press('Control+d');await expect(page.getByText('已保存 · 展示刷新失败',{exact:true})).toBeVisible();expect((await stored(page)).graph.revision).toBe(2);await page.reload();await expect(page.locator('[data-node-type="text"]')).toHaveCount(2);});
test('T15 edit protection: invalid local text is an unsaved draft and cannot silently leave',async({page})=>{await page.getByTestId('node-text-1').getByLabel('节点文本').fill('中'.repeat(21846));await expect(page.getByTestId('node-text-1').getByRole('alert')).toContainText('64KiB');await page.getByRole('link',{name:'项目',exact:true}).click();await expect(page.getByRole('dialog',{name:'离开前保存'})).toBeVisible();expect((await stored(page)).graph.nodes.find((n:{id:string})=>n.id==='text-1').data.text).toBe('原创镜头');});
test('T15 clipboard routing: an empty internal clipboard leaves external paste available without reading OS clipboard',async({page})=>{const allowed=await page.getByTestId('canvas-stage').evaluate(element=>element.dispatchEvent(new KeyboardEvent('keydown',{key:'v',ctrlKey:true,bubbles:true,cancelable:true})));expect(allowed).toBe(true);});


