import {test,expect} from '../helpers/network-guard';import {seedStudio} from '../helpers/seed-studio';
const graph=(page:import('@playwright/test').Page)=>page.evaluate(async()=>{const p='/src/infrastructure/storage/project-repository.ts';return(await import(p)).readGraph('p1');});
test.beforeEach(async({page})=>{await seedStudio(page,'canvas-project');await page.goto('/projects/p1/canvas');});
test('T44 C01/C02 actual tool buttons select and pan independently; only the viewport persists and creative revision remains fixed',async({page,networkCounter})=>{
 const before=await graph(page),select=page.getByRole('button',{name:'选择 V',exact:true}),pan=page.getByRole('button',{name:'平移 H',exact:true});await expect(select).toHaveAttribute('aria-pressed','true');await pan.click();await expect(pan).toHaveAttribute('aria-pressed','true');await expect(select).toHaveAttribute('aria-pressed','false');const box=await page.getByTestId('canvas-stage').boundingBox();if(!box)throw Error('canvas_missing');await page.mouse.move(box.x+10,box.y+10);await page.mouse.down();await page.mouse.move(box.x+50,box.y+40);await page.mouse.up();const view=await page.evaluate(()=>JSON.parse(localStorage.getItem('aiwork-studio:viewport:p1')!).view);expect(view).toMatchObject({x:40,y:30,scale:1});await select.click();await page.getByLabel('选择 镜头一',{exact:true}).check();await expect(page.getByTestId('node-text-1')).toHaveAttribute('aria-selected','true');await page.reload();expect(await graph(page)).toEqual(before);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('aiwork-studio:viewport:p1')!).view)).toEqual(view);await expect(select).toHaveAttribute('aria-pressed','true');expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 C02 native and optional viewport storage denial reports an error while allowing pan without writing creative data',async({page,networkCounter})=>{
 const before=await graph(page);await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof put>){if(this.name==='diagnostics')throw new DOMException('test-viewport-quota','QuotaExceededError');return put.apply(this,args);};const set=Storage.prototype.setItem;Storage.prototype.setItem=function(key:string,value:string){if(key.startsWith('aiwork-studio:viewport:'))throw new DOMException('test-viewport-denied','SecurityError');return set.call(this,key,value);};});await page.getByRole('button',{name:'平移 H',exact:true}).click();const box=await page.getByTestId('canvas-stage').boundingBox();if(!box)throw Error('canvas_missing');await page.mouse.move(box.x+10,box.y+10);await page.mouse.down();await page.mouse.move(box.x+50,box.y+40);await page.mouse.up();await expect(page.getByRole('alert')).toContainText('视口偏好未保存');expect(await graph(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 N10/N18/N19 existing group and result controls refuse a native foreign writer',async({page,networkCounter})=>{
 await seedStudio(page,'unverified-capability');await page.evaluate(async()=>{const p='/src/infrastructure/storage/project-lease.ts';await(await import(p)).acquireProjectLease('p1','actual-other-writer',Date.now());});await page.reload();await expect(page.getByText('只读 · 另一标签持有写权',{exact:true})).toBeVisible();const before=await graph(page);await page.getByLabel('选择 镜头组',{exact:true}).check();for(const id of ['N-10','N-18'])await expect(page.locator('[data-interaction-id="'+id+'"]')).toBeDisabled();await page.getByLabel('选择 镜头组',{exact:true}).uncheck();await page.getByLabel('选择 固定结果',{exact:true}).check();await expect(page.locator('[data-interaction-id="N-19"]')).toBeDisabled();expect(await graph(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
