import {test,expect} from '../helpers/network-guard';
import {seedStudio} from '../helpers/seed-studio';
test.use({actionTimeout:2500});test.setTimeout(15000);
async function graphState(page:import('@playwright/test').Page){return page.evaluate(async()=>{const path='/src/infrastructure/storage/database.ts';const {openStudioDb,transact,requestResult}=await import(path) as typeof import('../../src/infrastructure/storage/database');const db=await openStudioDb();try{return await transact(db,['graphs','receipts'],'readonly',async tx=>({graph:await requestResult(tx.objectStore('graphs').get('p1')),receipts:await requestResult(tx.objectStore('receipts').getAll())}));}finally{db.close();}});}
test.beforeEach(async({page})=>{await seedStudio(page,'canvas-project');});
test('T13-C01: invalid zoom restores value; bounds disable buttons and persist without creative revision',async({page})=>{
 await page.goto('/projects/p1/canvas');const zoom=page.getByLabel('缩放百分比');await zoom.fill('201');await zoom.press('Enter');await expect(page.getByText('缩放范围为25%–200%')).toBeVisible();await expect(zoom).toHaveValue('100');
 await zoom.fill('25');await zoom.press('Enter');await expect(page.getByRole('button',{name:'缩小',exact:true})).toBeDisabled();await zoom.fill('200');await zoom.press('Enter');await expect(page.getByRole('button',{name:'放大',exact:true})).toBeDisabled();await page.reload();await expect(zoom).toHaveValue('200');expect((await graphState(page)).graph.revision).toBe(1);
});
test('T13-C02: fit leaves 48px and keyboard outline is equivalent to box selection',async({page})=>{
 await page.goto('/projects/p1/canvas');await page.getByRole('button',{name:'适配全部'}).click();const stage=await page.getByTestId('canvas-stage').boundingBox(),node=await page.getByTestId('node-text-1').boundingBox();expect(stage).not.toBeNull();expect(node!.x-stage!.x).toBeGreaterThanOrEqual(47);expect(stage!.x+stage!.width-node!.x-node!.width).toBeGreaterThanOrEqual(47);
 await page.mouse.move(node!.x-10,node!.y-10);await page.mouse.down();await page.mouse.move(node!.x+node!.width+10,node!.y+node!.height+10);await page.mouse.up();await expect(page.getByTestId('node-text-1')).toHaveAttribute('aria-selected','true');await page.getByLabel('选择 镜头一').uncheck();await expect(page.getByTestId('node-text-1')).toHaveAttribute('aria-selected','false');await page.getByLabel('选择 镜头一').check();await expect(page.getByTestId('node-text-1')).toHaveAttribute('aria-selected','true');
});
test('T13-C04: space in input is retained and canvas pan is separate from graph edits',async({page})=>{
 await page.goto('/projects/p1/canvas');const field=page.getByLabel('查找节点');await field.fill('镜头');await field.press('Space');await expect(field).toHaveValue('镜头 ');await page.getByTestId('canvas-stage').focus();await page.keyboard.press('h');const stage=await page.getByTestId('canvas-stage').boundingBox();await page.mouse.move(stage!.x+15,stage!.y+15);await page.mouse.down();await page.mouse.move(stage!.x+60,stage!.y+60);await page.mouse.up();expect((await graphState(page)).graph.revision).toBe(1);
});
test('T13-C05: dragging previews in memory, mouseup commits once; undo/redo does not submit',async({page,networkCounter})=>{
 await page.goto('/projects/p1/canvas');const handle=page.getByTestId('node-text-1').getByTestId('node-handle'),box=await handle.boundingBox();await page.mouse.move(box!.x+30,box!.y+15);await page.mouse.down();await page.mouse.move(box!.x+130,box!.y+70,{steps:5});expect((await graphState(page)).graph.revision).toBe(1);await page.mouse.up();await expect.poll(async()=>(await graphState(page)).graph.revision).toBe(2);expect((await graphState(page)).receipts.filter((r:{status?:string})=>r.status==='applied')).toHaveLength(1);await page.getByRole('button',{name:'撤销',exact:true}).click();await expect.poll(async()=>(await graphState(page)).graph.nodes[0].x).toBe(80);await page.getByRole('button',{name:'重做',exact:true}).click();await expect.poll(async()=>(await graphState(page)).graph.nodes[0].x).toBe(180);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T13-C06: another writer makes canvas readonly; takeover requires explicit dialog',async({page})=>{
 await page.evaluate(async()=>{const path='/src/infrastructure/storage/project-lease.ts';const {acquireProjectLease}=await import(path) as typeof import('../../src/infrastructure/storage/project-lease');await acquireProjectLease('p1','other-tab',Date.now());});await page.goto('/projects/p1/canvas');await expect(page.getByText('只读 · 另一标签持有写权')).toBeVisible();const box=await page.getByTestId('node-text-1').getByTestId('node-handle').boundingBox();await page.mouse.move(box!.x+20,box!.y+15);await page.mouse.down();await page.mouse.move(box!.x+80,box!.y+30);await page.mouse.up();expect((await graphState(page)).graph.nodes[0].x).toBe(80);await page.getByRole('button',{name:'接管编辑'}).click();await expect(page.getByRole('dialog',{name:'接管编辑'})).toBeVisible();await page.getByRole('button',{name:'取消',exact:true}).click();expect((await graphState(page)).graph.revision).toBe(1);
});
test('T13 controls: text paste treats URL as text, minimap/background persist and no fetch occurs',async({page,networkCounter})=>{
 await page.goto('/projects/p1/canvas');await page.getByRole('button',{name:'添加节点'}).click();await page.getByRole('button',{name:'文本节点',exact:true}).click();await expect(page.locator('[data-node-type="text"]')).toHaveCount(2);await page.getByTestId('canvas-stage').evaluate(element=>{const data=new DataTransfer();data.setData('text/plain','https://example.invalid/创作');element.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));});await expect(page.locator('[data-node-type="text"]')).toHaveCount(3);await expect(page.getByText('https://example.invalid/创作',{exact:true})).toBeVisible();
 await page.getByLabel('画布背景').selectOption('grid');await page.getByRole('button',{name:'显示小地图'}).click();await expect(page.getByTestId('canvas-minimap')).toBeVisible();await page.screenshot({path:'docs/review/screenshots/T13-canvas.png'});await page.reload();await expect(page.getByLabel('画布背景')).toHaveValue('grid');await expect(page.getByTestId('canvas-minimap')).toBeVisible();expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T13 navigation: quota failure retains draft and blocks browser Back until explicit discard',async({page})=>{
 await page.goto('/projects');await page.getByRole('link',{name:'测试项目',exact:true}).click();await expect(page.getByTestId('node-text-1')).toBeVisible();await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;let once=true;IDBObjectStore.prototype.put=function(...args:Parameters<IDBObjectStore['put']>){if(this.name==='graphs'&&once){once=false;throw new DOMException('test quota','QuotaExceededError');}return original.apply(this,args);};});const box=await page.getByTestId('node-text-1').getByTestId('node-handle').boundingBox();await page.mouse.move(box!.x+15,box!.y+15);await page.mouse.down();await page.mouse.move(box!.x+70,box!.y+30);await page.mouse.up();await expect(page.getByText('尚未保存 · 内存草稿保留')).toBeVisible();expect((await graphState(page)).graph.revision).toBe(1);await page.goBack();await expect(page.getByRole('dialog',{name:'离开前保存'})).toBeVisible();await page.getByRole('button',{name:'继续编辑',exact:true}).click();await expect(page).toHaveURL(/\/canvas$/);await page.getByRole('link',{name:'项目',exact:true}).click();await expect(page.getByRole('dialog',{name:'离开前保存'})).toBeVisible();await page.getByRole('button',{name:'保存并离开',exact:true}).click();await expect(page).toHaveURL(/\/projects$/);expect((await graphState(page)).graph.revision).toBe(2);
});

