import {test,expect} from '../helpers/network-guard';
import type {Page} from '@playwright/test';
async function state(page:Page){return page.evaluate(async()=>{const d='/src/infrastructure/storage/database.ts',m=await import(d);return m.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>m.transact(db,['graphs','assets','blobs','runs'],'readonly',async(tx:IDBTransaction)=>({graph:await m.requestResult(tx.objectStore('graphs').get('p1')),assets:await m.requestResult(tx.objectStore('assets').getAll()),blobs:(await m.requestResult(tx.objectStore('blobs').getAll())).map((b:{id:string;blob:Blob})=>({id:b.id,bytes:b.blob.size})),runs:await m.requestResult(tx.objectStore('runs').getAll())})));});}
async function clipboardImage(page:Page){await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=8;canvas.height=8;const context=canvas.getContext('2d')!;context.fillStyle='#34d399';context.fillRect(0,0,8,8);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(Error('owned_png_fixture_failed')),'image/png'));await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);});}
async function pasteIntoCanvas(page:Page){const stage=page.getByTestId('canvas-stage'),bounds=await stage.boundingBox();if(!bounds)throw Error('canvas_not_rendered');await stage.click({position:{x:bounds.width-8,y:bounds.height-8}});await expect(stage).toBeFocused();await page.keyboard.press('Control+V');}
test.beforeEach(async({page})=>{await page.context().grantPermissions(['clipboard-read','clipboard-write']);await page.goto('/projects');await page.evaluate(async()=>{const g='/tests/fixtures/generation.ts';await(await import(g)).seedGeneration();});});
test('T44 C11 actual browser clipboard PNG and keyboard paste save the native original blob, media identity and canvas node together without any upload',async({page,networkCounter})=>{await page.goto('/projects/p1/canvas');const text=page.getByRole('textbox',{name:'节点文本',exact:true});await expect(text).toBeEditable();await clipboardImage(page);await text.click();await page.keyboard.press('Control+V');await expect(page.locator('[data-node-type="asset"]')).toHaveCount(0);expect((await state(page)).assets).toHaveLength(0);await pasteIntoCanvas(page);await expect(page.locator('[data-node-type="asset"]')).toHaveCount(1);const saved=await state(page);expect(saved.assets).toHaveLength(1);expect(saved.assets[0]).toMatchObject({mimeType:'image/png',width:8,height:8});expect(saved.blobs.find((b:{id:string})=>b.id===saved.assets[0].blobKey).bytes).toBe(saved.assets[0].bytes);expect(saved.graph.nodes.find((n:{type:string})=>n.type==='asset').data.assetId).toBe(saved.assets[0].id);expect(saved.graph.nodes.find((n:{id:string})=>n.id==='text-1').data.text).toBe('原创确认正文');expect(saved.graph.nodes.find((n:{id:string})=>n.id==='video-1').data.inputBindings).toEqual([{nodeId:'text-1',order:0,role:'text'}]);expect(saved.runs).toHaveLength(0);await page.reload();await expect(page.locator('[data-node-type="asset"]')).toHaveCount(1);expect(await state(page)).toEqual(saved);await page.screenshot({path:'docs/review/screenshots/T44-native-paste.png',fullPage:true});expect(networkCounter.paidRequests).toHaveLength(0);expect(networkCounter.requests.filter(r=>r.url.includes('/core-api/'))).toHaveLength(0);});
test('T44 C11 actual browser image paste quota abort preserves the graph, blobs, media and original Run together',async({page,networkCounter})=>{await page.goto('/projects/p1/canvas');await expect(page.getByRole('textbox',{name:'节点文本',exact:true})).toBeEditable();const before=await state(page);await clipboardImage(page);await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof put>){if(this.name==='blobs')throw new DOMException('native-clipboard-quota','QuotaExceededError');return put.apply(this,args);};});await pasteIntoCanvas(page);await expect(page.getByRole('alert')).toContainText('空间');expect(await state(page)).toEqual(before);await expect(page.locator('[data-node-type="asset"]')).toHaveCount(0);expect(networkCounter.paidRequests).toHaveLength(0);});
test('T44 C11 another native writer disables image paste without modifying any creative or execution data',async({page,networkCounter})=>{await page.evaluate(async()=>{const p='/src/infrastructure/storage/project-lease.ts';await(await import(p)).acquireProjectLease('p1','foreign-clipboard-writer',Date.now());});await page.goto('/projects/p1/canvas');await expect(page.getByRole('textbox',{name:'节点文本',exact:true})).toHaveJSProperty('readOnly',true);const before=await state(page);await clipboardImage(page);await pasteIntoCanvas(page);await expect(page.locator('[data-node-type="asset"]')).toHaveCount(0);expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);});
