import {test,expect} from '../helpers/network-guard';
import {seedStudio} from '../helpers/seed-studio';
import {holdNextNativeCommit,releaseNativeCommit,nativeCommitProbe} from '../helpers/native-commit-hold';
import type {Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['projects','graphs','runs','assets','receipts','blobs'],'readonly',async(tx:IDBTransaction)=>Object.fromEntries(await Promise.all(['projects','graphs','runs','assets','receipts','blobs'].map(async table=>[table,table==='blobs'?(await m.requestResult(tx.objectStore(table).getAll()) as {id:string;blob:Blob}[]).map(r=>({id:r.id,bytes:r.blob.size})):await m.requestResult(tx.objectStore(table).getAll())]))));}finally{db.close();}});

test('T44 D07/D08 pending real reference scan disables cleanup; actual clear-project abort preserves every project, original media and history',async({page,networkCounter})=>{
 await page.goto('/assets');await page.evaluate(async()=>{const p='/tests/fixtures/asset-library.ts';await(await import(p)).seedAssetLibrary();});await page.goto('/settings/storage');const before=await state(page);await holdNextNativeCommit(page,'graphs','readonly');await page.getByRole('button',{name:'清理未引用素材',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});try{await expect(page.getByRole('button',{name:'清理未引用素材',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'清空本地项目数据',exact:true})).toBeDisabled();expect(await state(page)).toEqual(before);}finally{await releaseNativeCommit(page);}await page.getByRole('dialog',{name:'清理未引用素材',exact:true}).getByRole('button',{name:'返回保留数据',exact:true}).click();await page.getByRole('button',{name:'清空本地项目数据',exact:true}).click();const dialog=page.getByRole('dialog',{name:'清空本地项目数据',exact:true});await dialog.getByLabel('输入确认词 清空本地项目',{exact:true}).fill('清空本地项目');await page.evaluate(()=>{const original=IDBObjectStore.prototype.delete;let armed=true;IDBObjectStore.prototype.delete=function(...args:Parameters<typeof original>){if(armed&&this.name==='projects'){armed=false;throw new DOMException('native-project-clear-abort','QuotaExceededError');}return original.apply(this,args);};});await dialog.getByRole('button',{name:'确认清空本地项目',exact:true}).click();await expect(dialog.getByRole('alert')).toHaveText('内容、追踪或写权已变化，或事务未完成；没有提交本次清理。请重新扫描后核对。');expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

async function trashBoth(page:Page){await seedStudio(page,'project-library');await page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{await m.transact(db,['projects'],'readwrite',async(tx:IDBTransaction)=>{for(const id of ['p1','p2']){const project=await m.requestResult(tx.objectStore('projects').get(id));tx.objectStore('projects').put({...project,trashedAt:1000});}});}finally{db.close();}});await page.goto('/trash');}
test('T44 Z01 actual restore quota retains trashed original and unknown tracking; a native retry disables restore until its real acknowledgement',async({page,networkCounter})=>{
 await trashBoth(page);const before=await state(page),row=page.getByTestId('trash-p1');await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;let armed=true;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(armed&&this.name==='projects'){armed=false;throw new DOMException('native-trash-restore-quota','QuotaExceededError');}return original.apply(this,args);};});await row.getByRole('button',{name:'恢复项目',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();expect(await state(page)).toEqual(before);await holdNextNativeCommit(page,'projects');await row.getByRole('button',{name:'恢复项目',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});try{await expect(row.getByRole('button',{name:'恢复项目',exact:true})).toBeDisabled();expect((await state(page)).runs).toEqual(before.runs);}finally{await releaseNativeCommit(page);}await expect(row).toHaveCount(0);const after=await state(page);expect(after.projects.find((p:{id:string})=>p.id==='p1').trashedAt).toBeNull();expect(after.runs).toEqual(before.runs);expect(after.assets).toEqual(before.assets);expect(after.blobs).toEqual(before.blobs);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 Z03 actual native batch deletion failure reports both failed and protected items and preserves original unknown task and shared files',async({page,networkCounter})=>{
 await trashBoth(page);const before=await state(page);await page.getByTestId('trash-p1').getByRole('checkbox',{name:'选择项目甲',exact:true}).check();await page.getByTestId('trash-p2').getByRole('checkbox',{name:'选择项目乙',exact:true}).check();await page.getByRole('button',{name:'批量永久删除',exact:true}).click();const dialog=page.getByRole('dialog',{name:'批量永久删除本地副本',exact:true});await expect(dialog).toContainText('可删除 1，阻止 1');await dialog.getByLabel('确认项目乙名称',{exact:true}).fill('项目乙');await page.evaluate(()=>{const original=IDBObjectStore.prototype.delete;let armed=true;IDBObjectStore.prototype.delete=function(...args:Parameters<typeof original>){if(armed&&this.name==='projects'){armed=false;throw new DOMException('native-trash-batch-quota','QuotaExceededError');}return original.apply(this,args);};});await dialog.getByRole('button',{name:'永久删除 1 项',exact:true}).click();await expect(page.getByRole('status')).toContainText('成功 0，失败 2');await expect(page.getByRole('status')).toContainText('项目乙：本地删除失败');await expect(page.getByTestId('trash-p1')).toBeVisible();await expect(page.getByTestId('trash-p2')).toBeVisible();expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
