import {randomUUID} from 'node:crypto';
import {test,expect} from '../helpers/cloud-workspace-ui-fixture';
test('connects text to video through visible ports with typed errors and keeps side-panel flow',async({page,workspace})=>{
 const project=(await workspace.call('POST','/studio-api/projects',{...workspace.headers(workspace.account),payload:{title:'端口连线'}})).json();
 await page.goto('/projects/'+project.id+'/canvas');
 await page.getByRole('button',{name:'添加文字节点',exact:true}).click();
 await page.locator('[data-interaction-id="cloud:canvas:node-text"]').first().fill('端口正文');
 await page.getByRole('button',{name:'添加节点',exact:true}).click();
 await page.locator('[data-interaction-id="cloud:canvas:dialog-model"]').fill('seedance');
 await page.getByRole('button',{name:'添加视频草稿',exact:true}).click();
 await page.getByRole('button',{name:'保存到云端',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('已保存');
 // 键盘等价连接：输出端口回车开始，目标输入端口点按完成
 await page.getByRole('button',{name:'输出文本',exact:true}).press('Enter');
 await page.getByRole('button',{name:'接收文本',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('已保存');
 await expect(page.locator('.canvas-wire')).toHaveCount(1);
 await expect(page.locator('.canvas-wire path.wire-visible')).toHaveCount(1);
 // 错误端口：文字输出到图片输入被拒绝且不建线
 await page.getByRole('button',{name:'输出文本',exact:true}).press('Enter');
 await page.getByRole('button',{name:'接收图片',exact:true}).click();
 await expect(page.getByRole('alert')).toContainText('输出与输入类型不匹配');
 await expect(page.locator('.canvas-wire')).toHaveCount(1);
 await expect(page.locator('.canvas-node')).toHaveCount(2);
 expect(workspace.providerCalls.filter(c=>c.method==='POST')).toHaveLength(0);
});
test('picks cloud thumbnails and uploads into the library before adding nodes',async({page,workspace})=>{
 const project=(await workspace.call('POST','/studio-api/projects',{...workspace.headers(workspace.account),payload:{title:'素材选择'}})).json();
 await page.goto('/projects/'+project.id+'/canvas');
 await page.getByRole('button',{name:'添加节点',exact:true}).click();
 await expect(page.getByText('云端素材库暂无内容',{exact:false})).toBeVisible();
 const png=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=8;return canvas.toDataURL('image/png').split(',')[1];});
 await page.locator('[data-interaction-id="cloud:asset:picker-files"]').setInputFiles({name:'选择器.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});
 await page.getByRole('button',{name:'上传到云端素材库',exact:true}).click();
 await expect(page.getByText('已进入云端素材库',{exact:false})).toBeVisible();
 await expect(page.locator('.cloud-asset-picker img')).toHaveCount(1);
 await page.getByRole('button',{name:'选择此素材',exact:true}).click();
 await expect(page.locator('.node-asset img')).toHaveCount(1);
 await page.getByRole('button',{name:'保存到云端',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('已保存');
 await page.reload();await expect(page.locator('.node-asset img')).toHaveCount(1);
 expect(workspace.providerCalls.filter(c=>c.method==='POST')).toHaveLength(0);
});
test('locks ports, undoes work and retains input on save conflicts',async({page,workspace})=>{
 const h=workspace.headers(workspace.account);
 const project=(await workspace.call('POST','/studio-api/projects',{...h,payload:{title:'锁定撤销冲突'}})).json();
 await page.goto('/projects/'+project.id+'/canvas');
 await page.getByRole('button',{name:'添加文字节点',exact:true}).click();
 await expect(page.getByRole('status').first()).toContainText('已保存');
 await page.getByRole('button',{name:'撤销',exact:true}).click();
 await expect(page.locator('.canvas-node')).toHaveCount(0);
 await page.getByRole('button',{name:'重做',exact:true}).click();
 await expect(page.locator('.canvas-node')).toHaveCount(1);
 await page.getByRole('button',{name:'锁定',exact:true}).first().click();
 await expect(page.getByRole('status').first()).toContainText('已保存');
 await expect(page.getByRole('button',{name:'输出文本',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'解锁',exact:true}).click();await expect(page.getByRole('status').first()).toContainText('已保存');
 await expect(page.getByRole('button',{name:'输出文本',exact:true})).toBeEnabled();
 expect((await workspace.call('POST','/studio-api/projects/'+project.id+'/commands',{...h,payload:{expectedRevision:5,idempotencyKey:randomUUID(),command:{type:'operations',operations:[{id:randomUUID(),type:'add_node',payload:{node:{id:randomUUID(),type:'text',title:'外部',x:40,y:400,locked:false,data:{kind:'text',text:'外部',referenceTokens:[]}}}}]}}})).statusCode).toBe(200);
 await page.locator('[data-interaction-id="cloud:canvas:node-text"]').first().fill('冲突保留');
 await page.getByRole('button',{name:'保存到云端',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('保存未完成');
 await expect(page.locator('[data-interaction-id="cloud:canvas:node-text"]').first()).toHaveValue('冲突保留');
 expect(workspace.providerCalls.filter(c=>c.method==='POST')).toHaveLength(0);
});test('box-selects nodes and applies alignment through the action bar',async({page,workspace})=>{
 const project=(await workspace.call('POST','/studio-api/projects',{...workspace.headers(workspace.account),payload:{title:'框选对齐'}})).json();
 await page.goto('/projects/'+project.id+'/canvas');
 await page.getByRole('button',{name:'添加文字节点',exact:true}).click();
 await page.getByRole('button',{name:'添加文字节点',exact:true}).click();
 await expect(page.getByRole('status').first()).toContainText('已保存');
 const box=await page.locator('.canvas-stage').boundingBox();if(!box)throw new Error('Missing stage');
 await page.mouse.move(box.x+10,box.y+10);await page.mouse.down();await page.mouse.move(box.x+900,box.y+500,{steps:8});await page.mouse.up();
 await expect(page.getByRole('button',{name:'对齐',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'对齐',exact:true}).click();
 await expect(page.getByRole('status').first()).toContainText('已保存');
 await page.getByRole('button',{name:'布局预览',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'预览布局',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'应用布局',exact:true}).click();
 await expect(page.getByRole('status').first()).toContainText('已保存');
 await page.reload();await expect(page.locator('.canvas-node')).toHaveCount(2);
 expect(workspace.providerCalls.filter(c=>c.method==='POST')).toHaveLength(0);
});
test('branches from text, resizes with the keyboard and restores everything on refresh',async({page,workspace})=>{
 const h=workspace.headers(workspace.account);
 expect((await workspace.call('PATCH','/studio-api/me/model-configs/video',{...h,payload:{apiBase:'https://video.example.test',model:'seedance',apiKey:'FAKE_VIDEO_UI_KEY',expectedRevision:null}})).statusCode).toBe(200);
 const project=(await workspace.call('POST','/studio-api/projects',{...h,payload:{title:'分支尺寸'}})).json();
 await page.goto('/projects/'+project.id+'/canvas');
 await page.getByRole('button',{name:'添加文字节点',exact:true}).click();
 await page.locator('[data-interaction-id="cloud:canvas:node-text"]').first().fill('分支来源');
 await expect(page.getByRole('status').first()).toContainText('已保存');
 await page.locator('[data-interaction-id="cloud:canvas:outline-select"]').check();
 await page.getByRole('button',{name:'复制为分支',exact:true}).click();
 await expect(page.locator('.node-video-generation')).toHaveCount(1);
 await page.locator('[data-interaction-id="canvas:resize"]').first().focus();
 await page.keyboard.press('ArrowRight');
 await expect(page.getByRole('status').first()).toContainText('已保存');
 const before=(await workspace.pool.query('SELECT graph FROM workspace_graphs WHERE project_id=$1',[project.id])).rows[0].graph;
 const text=before.nodes.find((n:{type:string})=>n.type==='text');
 expect(text.size?.width??320).toBeGreaterThan(320);
 await page.reload();
 const after=(await workspace.pool.query('SELECT graph FROM workspace_graphs WHERE project_id=$1',[project.id])).rows[0].graph;
 expect(after.nodes).toHaveLength(2);expect(after.edges).toHaveLength(1);
 expect(after.nodes.find((n:{type:string})=>n.type==='text').size.width).toBe(text.size.width);
 expect(workspace.providerCalls.filter(c=>c.method==='POST')).toHaveLength(0);
});
