import {test,expect} from '../helpers/cloud-workspace-ui-fixture';
test('copies and pastes canvas nodes through the actual controls and persists the resulting graph',async({page,workspace})=>{
 const project=(await workspace.call('POST','/studio-api/projects',{...workspace.headers(workspace.account),payload:{title:'画布操作验收'}})).json();
 await page.goto('/projects/'+project.id+'/canvas');await page.getByRole('button',{name:'添加文字节点',exact:true}).click();await page.getByLabel('节点文本',{exact:true}).fill('复制后仍需保留的正文');await expect(page.getByRole('status').first()).toContainText('已保存');
 await page.getByRole('button',{name:'复制节点',exact:true}).click();await expect(page.getByRole('button',{name:'粘贴节点',exact:true})).toBeEnabled();await page.getByRole('button',{name:'粘贴节点',exact:true}).click();await expect(page.locator('.canvas-node')).toHaveCount(2);await expect(page.getByRole('status').first()).toContainText('已保存');await page.reload();await expect(page.locator('.canvas-node')).toHaveCount(2);await expect(page.getByLabel('节点文本',{exact:true}).first()).toHaveValue('复制后仍需保留的正文');expect(workspace.providerCalls).toHaveLength(0);
});
test('uses grouping, layout, locking, view tools, undo and reload controls on the persisted cloud canvas',async({page,workspace})=>{
 test.setTimeout(90000);
 const project=(await workspace.call('POST','/studio-api/projects',{...workspace.headers(workspace.account),payload:{title:'完整画布工具'}})).json(),saved=async()=>expect(page.getByRole('status').first()).toContainText('已保存');
 await page.goto('/projects/'+project.id+'/canvas');await page.getByRole('button',{name:'添加文字节点',exact:true}).click();await saved();await page.getByRole('button',{name:'添加文字节点',exact:true}).click();await saved();
 const selection=page.locator('[data-interaction-id="cloud:canvas:outline-select"]');await selection.nth(0).check();await selection.nth(1).check();await page.getByRole('button',{name:'整理选中',exact:true}).click();await saved();await page.getByRole('button',{name:'创建分组',exact:true}).click();await saved();await expect(page.locator('.node-group')).toHaveCount(1);
 await page.getByRole('button',{name:'折叠分组',exact:true}).click();await saved();await expect(page.locator('.canvas-node')).toHaveCount(1);await page.getByRole('button',{name:'展开分组',exact:true}).click();await saved();await expect(page.locator('.canvas-node')).toHaveCount(3);await page.getByRole('button',{name:'解除分组',exact:true}).click();await saved();await expect(page.locator('.canvas-node')).toHaveCount(2);
 await page.getByRole('button',{name:'锁定',exact:true}).first().click();await saved();await expect(page.getByLabel('节点文本',{exact:true}).first()).toBeDisabled();await page.getByRole('button',{name:'解锁',exact:true}).click();await saved();await expect(page.getByLabel('节点文本',{exact:true}).first()).toBeEnabled();
 await page.getByRole('button',{name:'平移 H',exact:true}).click();await expect(page.getByRole('button',{name:'平移 H',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'选择 V',exact:true}).click();await page.getByRole('button',{name:'缩小',exact:true}).click();await saved();await page.getByRole('button',{name:'放大',exact:true}).click();await saved();await page.getByLabel('缩放百分比',{exact:true}).fill('80');await page.getByLabel('缩放百分比',{exact:true}).press('Enter');await saved();await page.getByRole('button',{name:'适配全部',exact:true}).click();await saved();await page.getByRole('button',{name:'定位选中',exact:true}).click();await saved();await page.getByRole('button',{name:'显示小地图',exact:true}).click();await expect(page.getByLabel('画布小地图',{exact:true})).toBeVisible();await page.getByRole('button',{name:'隐藏小地图',exact:true}).click();await page.getByRole('combobox',{name:'画布背景',exact:true}).selectOption('grid');await expect(page.getByRole('region',{name:'云端画布',exact:true})).toHaveClass(/background-grid/);
 await page.getByLabel('节点文本',{exact:true}).first().fill('待放弃的正文');await page.getByRole('button',{name:'重新加载画布',exact:true}).click();await page.getByRole('button',{name:'保留输入',exact:true}).click();await saved();await page.getByRole('button',{name:'撤销',exact:true}).click();await saved();await page.getByRole('button',{name:'重做',exact:true}).click();await saved();
 await page.getByLabel('节点文本',{exact:true}).first().fill('应明确放弃的正文');await page.getByRole('button',{name:'重新加载画布',exact:true}).click();await page.getByRole('button',{name:'放弃未保存输入并重新加载',exact:true}).click();await saved();await expect(page.getByLabel('节点文本',{exact:true}).first()).toHaveValue('待放弃的正文');
 await selection.nth(0).check();await selection.nth(1).check();await page.getByRole('button',{name:'删除选中节点',exact:true}).click();await saved();await expect(page.locator('.canvas-node')).toHaveCount(0);await page.getByRole('button',{name:'撤销',exact:true}).click();await saved();await expect(page.locator('.canvas-node')).toHaveCount(2);await page.reload();await expect(page.locator('.canvas-node')).toHaveCount(2);expect(workspace.providerCalls).toHaveLength(0);
});
test('edits project and asset metadata, searches and archives, and restores owned trash through the actual buttons',async({page,workspace})=>{
 test.setTimeout(60000);
 await workspace.call('POST','/studio-api/projects',{...workspace.headers(workspace.account),payload:{title:'初始项目'}});await page.goto('/projects');await page.getByRole('button',{name:'修改项目信息',exact:true}).click();await page.getByLabel('项目名称',{exact:true}).fill('修改后的项目');await page.getByLabel('项目说明',{exact:true}).fill('项目说明');await page.getByLabel('项目标签（逗号分隔）',{exact:true}).fill('验收,云端');await page.getByRole('button',{name:'保存项目信息',exact:true}).click();await expect(page.getByRole('link',{name:'修改后的项目',exact:true})).toBeVisible();await page.getByRole('button',{name:'星标',exact:true}).click();await expect(page.getByRole('button',{name:'取消星标',exact:true})).toBeVisible();await page.getByRole('button',{name:'取消星标',exact:true}).click();await page.getByRole('button',{name:'归档',exact:true}).click();await page.getByRole('combobox',{name:'项目筛选',exact:true}).selectOption('archived');await expect(page.getByRole('link',{name:'修改后的项目',exact:true})).toBeVisible();await page.getByRole('button',{name:'取消归档',exact:true}).click();await page.getByRole('combobox',{name:'项目筛选',exact:true}).selectOption('all');await page.getByLabel('搜索项目',{exact:true}).fill('云端');await page.getByRole('combobox',{name:'排序',exact:true}).selectOption('title');await page.getByRole('button',{name:'重新加载项目',exact:true}).click();await expect(page.getByRole('link',{name:'修改后的项目',exact:true})).toBeVisible();await page.getByRole('button',{name:'移入回收站',exact:true}).click();await page.getByRole('link',{name:'回收站',exact:true}).click();await page.getByRole('button',{name:'恢复项目',exact:true}).click();await expect(page.getByRole('button',{name:'恢复项目',exact:true})).toHaveCount(0);
 await page.getByRole('link',{name:'素材库',exact:true}).click();const png=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=2;return canvas.toDataURL('image/png').split(',')[1];});await page.getByLabel('选择素材文件',{exact:true}).setInputFiles({name:'初始素材.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.getByRole('button',{name:'上传到云端',exact:true}).click();await expect(page.getByText('初始素材.png',{exact:true})).toBeVisible();await page.getByRole('button',{name:'修改素材信息',exact:true}).click();await page.getByLabel('素材名称',{exact:true}).fill('修改后的素材');await page.getByLabel('素材说明',{exact:true}).fill('恢复时应保留的说明');await page.getByLabel('素材标签（逗号分隔）',{exact:true}).fill('验收');await page.getByRole('button',{name:'保存素材信息',exact:true}).click();await expect(page.getByText('修改后的素材',{exact:true})).toBeVisible();await page.getByLabel('搜索素材',{exact:true}).fill('验收');await page.getByRole('combobox',{name:'素材类型',exact:true}).selectOption('image');await page.getByRole('button',{name:'重新加载素材',exact:true}).click();await page.getByRole('button',{name:'移入回收站',exact:true}).click();await page.getByRole('link',{name:'回收站',exact:true}).click();await page.getByRole('button',{name:'恢复素材',exact:true}).click();await page.getByRole('link',{name:'素材库',exact:true}).click();await expect(page.getByText('恢复时应保留的说明',{exact:true})).toBeVisible();expect(workspace.providerCalls).toHaveLength(0);
});
