import {test,expect} from '../helpers/cloud-workspace-ui-fixture';
// 阶段8：从空项目开始，全程真实点击（本地假上游，零付费调用）——API 配置、
// 提示词、建流程、素材、生成确认、结果、修改、续写与跨页面恢复。
test('completes an empty-project journey purely through clicks without paid calls',async({page,workspace})=>{
 const video=page.getByRole('region',{name:'视频 API',exact:true});
 await page.goto('/projects');
 await page.getByRole('button',{name:'新建项目',exact:true}).click();
 await page.getByLabel('项目名称',{exact:true}).fill('全程旅程');
 await page.getByRole('button',{name:'创建项目',exact:true}).click();
 await expect(page.getByRole('link',{name:'全程旅程',exact:true})).toBeVisible();
 await page.goto('/settings/connections');
 await video.getByLabel('地址',{exact:true}).fill('https://video.example.test');
 await video.getByLabel('模型名称',{exact:true}).fill('seedance');
 await video.getByLabel('密钥',{exact:true}).fill('FAKE_VIDEO_UI_KEY');
 await video.getByRole('button',{name:'测试连接',exact:true}).click();
 await expect(video.getByRole('status')).toContainText('连接成功');
 await video.getByRole('button',{name:'保存',exact:true}).click();
 await expect(video.getByText('已保存到当前账号',{exact:false})).toBeVisible();
 await page.goto('/prompts');
 await page.getByRole('button',{name:'新建提示词',exact:true}).click();
 await page.getByLabel('提示词名称',{exact:true}).fill('旅程提示词');
 await page.getByLabel('提示词正文',{exact:true}).fill('旅程用的镜头文字');
 await page.getByLabel('提示词来源',{exact:true}).fill('全程旅程');
 await page.getByRole('button',{name:'保存提示词',exact:true}).click();
 await expect(page.getByRole('heading',{name:'旅程提示词',exact:true})).toBeVisible();
 await page.goto('/projects');await page.getByRole('link',{name:'全程旅程',exact:true}).click();
 await page.getByRole('button',{name:'添加文字节点',exact:true}).click();
 await page.locator('[data-interaction-id="cloud:canvas:node-text"]').first().fill('雨后街道，一镜到底');
 await page.getByRole('button',{name:'添加节点',exact:true}).click();
 await page.locator('[data-interaction-id="cloud:canvas:dialog-model"]').fill('seedance');
 await page.getByRole('button',{name:'添加视频草稿',exact:true}).click();
 await page.getByRole('button',{name:'输出文本',exact:true}).press('Enter');
 await page.getByRole('button',{name:'接收文本',exact:true}).click();
 await page.getByRole('button',{name:'保存到云端',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('已保存');
 await page.goto('/assets');
 const png=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=8;return canvas.toDataURL('image/png').split(',')[1];});
 await page.getByLabel('选择素材文件',{exact:true}).setInputFiles({name:'旅程素材.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});
 await page.getByRole('button',{name:'上传到云端',exact:true}).click();
 await expect(page.getByText('旅程素材.png',{exact:true})).toBeVisible();
 await page.goto('/projects');await page.getByRole('link',{name:'全程旅程',exact:true}).click();
 await page.locator('[data-interaction-id="V-08"]').click();

 await page.getByRole('button',{name:'确认',exact:true}).click();
 await expect.poll(async()=>(await workspace.pool.query("SELECT document->>'executionState' state FROM workspace_video_runs")).rows[0]?.state,{timeout:15000}).toBe('succeeded');
 await page.getByRole('button',{name:'查看视频任务',exact:true}).click();
 const detail=page.getByRole('dialog',{name:'云端视频任务',exact:true});
 await detail.getByRole('link',{name:'打开视频结果页',exact:true}).click();const resultUrl=page.url();
 const item=page.locator('[data-interaction-id="cloud:results:item"]');
 await expect(item.locator('video')).toHaveCount(1);
 await item.getByRole('button',{name:'修改后重新生成',exact:true}).click();
 const revision=page.getByRole('dialog',{name:'修改后重新生成',exact:true});
 await revision.locator('[data-interaction-id="cloud:results:revision-prompt"]').fill('旅程修改后的夜晚版本');
 await revision.getByRole('button',{name:'保存为新的视频草稿',exact:true}).click();
 await expect(page).toHaveURL(/\/canvas\?node=/);await page.goto(resultUrl);
 await item.getByRole('button',{name:'尾帧续写',exact:true}).click();
 const tail=page.getByRole('dialog',{name:'尾帧续写',exact:true});
 await tail.locator('[data-interaction-id="cloud:results:tail-frame-time"]').fill('0.2');
 await tail.getByRole('button',{name:'抽取并预览尾帧',exact:true}).click();
 await expect(tail.locator('[data-interaction-id="cloud:results:tail-frame-preview"]')).toBeVisible();
 await tail.locator('[data-interaction-id="cloud:results:tail-frame-prompt"]').fill('旅程续写向前推进');
 await tail.getByRole('button',{name:'上传尾帧并保存续写流程',exact:true}).click();
 await expect(page).toHaveURL(/\/canvas\?node=/);await page.goto(resultUrl);
 await page.reload();
 await expect(page.locator('[data-interaction-id="cloud:results:item"] video')).toHaveCount(1);
 await page.getByRole('link',{name:'返回画布',exact:true}).click();
 await expect(page.getByLabel('节点文本',{exact:true}).first()).toHaveValue('雨后街道，一镜到底');
 expect(workspace.providerCalls.filter(call=>call.method==='POST')).toHaveLength(1);
});
