import {randomUUID} from 'node:crypto';
import {test,expect} from '../helpers/cloud-workspace-ui-fixture';
import type {fixture,Account} from '../../server/tests/account-fixture';
async function savedProject(workspace:Awaited<ReturnType<typeof fixture>>&{account:Account}){
 const h=workspace.headers(workspace.account);expect((await workspace.call('PATCH','/studio-api/me/model-configs/video',{...h,payload:{apiBase:'https://video.example.test',model:'seedance',apiKey:'FAKE_VIDEO_UI_KEY',expectedRevision:null}})).statusCode).toBe(200);
 const project=(await workspace.call('POST','/studio-api/projects',{...h,payload:{title:'失败与取消检查'}})).json(),textId=randomUUID(),nodeId=randomUUID();expect((await workspace.call('POST','/studio-api/projects/'+project.id+'/commands',{...h,payload:{expectedRevision:0,idempotencyKey:randomUUID(),command:{type:'operations',operations:[{id:randomUUID(),type:'add_node',payload:{node:{id:textId,type:'text',title:'创意',x:40,y:40,locked:false,data:{kind:'text',text:'安全转换的输入',referenceTokens:[]}}}},{id:randomUUID(),type:'add_node',payload:{node:{id:nodeId,type:'video-generation',title:'视频草稿',x:440,y:40,locked:false,data:{kind:'video-generation',draft:{modelId:'seedance',durationSeconds:5,ratio:'16:9',resolution:'480p'},inputBindings:[],stale:true}}}},{id:randomUUID(),type:'add_edge',payload:{edge:{id:randomUUID(),sourceId:textId,targetId:nodeId,port:'text',order:0}}}]}}})).statusCode).toBe(200);return project;
}
test('previews exact owned cloud video inputs, confirms once, saves the private result and inserts durable lineage',async({page,workspace})=>{
 const h=workspace.headers(workspace.account);await workspace.call('PATCH','/studio-api/me/model-configs/video',{...h,payload:{apiBase:'https://video.example.test',model:'seedance',apiKey:'FAKE_VIDEO_UI_KEY',expectedRevision:null}});
 const project=(await workspace.call('POST','/studio-api/projects',{...h,payload:{title:'云端视频流程'}})).json(),textId=randomUUID(),nodeId=randomUUID();await workspace.call('POST','/studio-api/projects/'+project.id+'/commands',{...h,payload:{expectedRevision:0,idempotencyKey:randomUUID(),command:{type:'operations',operations:[{id:randomUUID(),type:'add_node',payload:{node:{id:textId,type:'text',title:'创意',x:40,y:40,locked:false,data:{kind:'text',text:'雨后街道',referenceTokens:[]}}}},{id:randomUUID(),type:'add_node',payload:{node:{id:nodeId,type:'video-generation',title:'视频草稿',x:440,y:40,locked:false,data:{kind:'video-generation',draft:{modelId:'seedance',durationSeconds:5,ratio:'16:9',resolution:'480p'},inputBindings:[],stale:true}}}},{id:randomUUID(),type:'add_edge',payload:{edge:{id:randomUUID(),sourceId:textId,targetId:nodeId,port:'text',order:0}}}]}}});
 await page.goto('/projects/'+project.id+'/canvas');await page.getByRole('button',{name:'预览视频生成',exact:true}).click();const preview=page.getByRole('dialog',{name:'确认云端视频生成',exact:true});await expect(preview).toContainText('雨后街道');await expect(preview).toContainText('5 秒');expect(workspace.providerCalls).toHaveLength(0);await expect(page.getByRole('button',{name:'确认提交视频生成',exact:true})).toBeDisabled();await page.getByLabel('我确认所列视频生成可能收费',{exact:true}).check();await page.getByRole('button',{name:'确认提交视频生成',exact:true}).click();await expect(page.getByRole('button',{name:'查看视频任务',exact:true})).toBeVisible();
 await page.reload();await expect.poll(async()=>(await workspace.pool.query("SELECT document->>'deliveryState' state FROM workspace_video_runs")).rows[0]?.state,{timeout:15000}).toBe('available_for_preview');await page.getByRole('button',{name:'查看视频任务',exact:true}).click();const detail=page.getByRole('dialog',{name:'云端视频任务',exact:true});await expect(detail).toContainText('生成已完成');await page.getByRole('button',{name:'添加结果到原画布',exact:true}).click();await expect(detail).toContainText('视频结果已添加到原画布');await detail.getByRole('button',{name:'关闭云端视频任务',exact:true}).click();await page.reload();await expect(page.locator('.node-result')).toHaveCount(1);expect(workspace.providerCalls.filter(call=>call.method==='POST')).toHaveLength(1);expect(workspace.providerCalls.every(call=>call.apiKey==='FAKE_VIDEO_UI_KEY')).toBe(true);await page.screenshot({path:'work/account-api-cloud/cloud-video-result.png',fullPage:true});
 await page.getByRole('link',{name:'任务中心',exact:true}).click();await page.getByRole('button',{name:'查看任务详情',exact:true}).click();await expect(page.getByRole('dialog',{name:'云端任务详情',exact:true})).toContainText('雨后街道');
});
test('keeps the safe 3003 reason and pending billing in both cloud task views after refresh',async({page,workspace})=>{
 workspace.setVideoOutcome('failed');const project=await savedProject(workspace);await page.goto('/projects/'+project.id+'/canvas');await page.getByRole('button',{name:'预览视频生成',exact:true}).click();await page.getByLabel('我确认所列视频生成可能收费',{exact:true}).check();await page.getByRole('button',{name:'确认提交视频生成',exact:true}).click();await expect.poll(async()=>(await workspace.pool.query("SELECT document->>'executionState' state FROM workspace_video_runs")).rows[0]?.state).toBe('failed_confirmed');await page.reload();await page.getByRole('button',{name:'查看视频任务',exact:true}).click();const detail=page.getByRole('dialog',{name:'云端视频任务',exact:true});for(const text of ['生成失败：上游判定参考图片可能包含真人，拒绝生成。','错误码：3003。','积分仍在核对，尚未确认最终扣费。'])await expect(detail).toContainText(text);await expect(detail).not.toContainText('FAKE_PRIVATE');await expect(detail).not.toContainText('input image');await page.getByRole('button',{name:'暂停原任务查询',exact:true}).click();await expect(detail).toContainText('原任务查询已暂停');await detail.getByRole('button',{name:'关闭云端视频任务',exact:true}).click();await page.getByRole('link',{name:'任务中心',exact:true}).click();await page.getByRole('button',{name:'查看任务详情',exact:true}).click();await expect(page.getByRole('dialog',{name:'云端任务详情',exact:true})).toContainText('生成失败：上游判定参考图片可能包含真人，拒绝生成。');expect(workspace.providerCalls.filter(call=>call.method==='POST')).toHaveLength(1);
});
test('canceling a video preview sends no provider request and does not create a run',async({page,workspace})=>{
 const project=await savedProject(workspace);await page.goto('/projects/'+project.id+'/canvas');await page.getByRole('button',{name:'预览视频生成',exact:true}).click();await page.getByRole('dialog',{name:'确认云端视频生成',exact:true}).getByRole('button',{name:'取消',exact:true}).click();expect(workspace.providerCalls).toHaveLength(0);expect((await workspace.pool.query('SELECT count(*)::int n FROM workspace_video_runs')).rows[0].n).toBe(0);
});
