import {test,expect} from '../helpers/network-guard';
import {localDeployment} from '../helpers/deployment-fixture';
import type {Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const state=(page:Page)=>page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['connections','receipts','projects','graphs','runs','promptRuns'],'readonly',async(tx:IDBTransaction)=>Object.fromEntries(await Promise.all(['connections','receipts','projects','graphs','runs','promptRuns'].map(async table=>[table,await m.requestResult(tx.objectStore(table).getAll())]))));}finally{db.close();}});
test.beforeEach(async({page})=>{await page.route('**/studio-deployment.json',route=>route.fulfill({contentType:'application/json',body:JSON.stringify(localDeployment)}));await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/task-history.ts',f='/tests/helpers/fixtures.ts',d='/src/infrastructure/storage/database.ts',m=await import(d),fixtures=await import(f);await (await import(p)).seedTaskHistory();await m.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>m.transact(db,['connections'],'readwrite',(tx:IDBTransaction)=>tx.objectStore('connections').put(fixtures.f.connection())));localStorage.setItem('aiwork-studio:default-connection','c1');});});

test('T44 K01/K02 invalid address and native address save quota keep original profiles and task ownership without a request',async({page,networkCounter})=>{
 await page.goto('/settings/connections');await expect(page.getByLabel('已保存连接',{exact:true})).toHaveValue('c1');const before=await state(page);await page.getByLabel('Core 服务地址',{exact:true}).fill('javascript:alert(1)');await page.getByRole('button',{name:'保存连接地址',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'连接操作失败'})).toBeVisible();expect(await state(page)).toEqual(before);await page.getByLabel('Core 服务地址',{exact:true}).fill('https://core.invalid');await page.getByLabel('连接名称',{exact:true}).fill('尚未保存的新名称');await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;Reflect.set(window,'connectionWriteDenied',0);IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(this.name==='connections'){Reflect.set(window,'connectionWriteDenied',Reflect.get(window,'connectionWriteDenied')+1);throw new DOMException('native-address-quota','QuotaExceededError');}return original.apply(this,args);};});await page.getByRole('button',{name:'保存连接地址',exact:true}).click();await expect.poll(()=>page.evaluate(()=>Reflect.get(window,'connectionWriteDenied'))).toBe(1);await expect(page.getByRole('status').filter({hasText:'连接操作失败'})).toBeVisible();expect(await state(page)).toEqual(before);expect(networkCounter.evidence.coreWrites).toBe(0);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 W05/K04/K07 real readonly HTTP rejection clears the ordinary Key and creates no verified binding or generation',async({page,networkCounter})=>{
 await page.route('**/core-api/healthz',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":{"code":"service_unavailable"}}'}));await page.route('**/core-api/v1/models',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":{"code":"service_unavailable"}}'}));await page.goto('/welcome');await expect(page.getByLabel('已保存连接',{exact:true})).toHaveValue('c1');const before=await state(page);await page.getByLabel('普通用户 Key',{exact:true}).fill('fake-native-readonly-rejected-key');await page.getByRole('button',{name:'测试连接',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'只读核验失败：HTTP 503'})).toBeVisible();await expect(page.getByLabel('普通用户 Key',{exact:true})).toHaveValue('');expect(await state(page)).toEqual(before);expect(await page.evaluate(async()=>{const p='/src/adapters/core/current-connection.ts';return (await import(p)).getActiveCore();})).toBeUndefined();expect(networkCounter.requests.filter(row=>row.url.includes('/core-api/')).length).toBeGreaterThan(0);expect(networkCounter.requests.filter(row=>row.url.includes('/core-api/')).every(row=>row.method==='GET')).toBe(true);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 K08 actual readonly model refresh failure marks the old catalog stale without rewriting original authorization or task identities',async({page,networkCounter})=>{
 await page.route('**/core-api/healthz',route=>route.fulfill({contentType:'application/json',body:'{"status":"ok"}'}));await page.route('**/core-api/v1/models',route=>route.fulfill({contentType:'application/json',body:'{"data":[{"id":"fake-text-only"},{"id":"fake-video-only"}]}'}));await page.goto('/settings/connections');await expect(page.getByLabel('已保存连接',{exact:true})).toHaveValue('c1');await page.getByLabel('普通用户 Key',{exact:true}).fill('fake-stale-model-key');await page.getByRole('button',{name:'测试连接',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'健康与模型目录只读核验成功'})).toBeVisible();const before=await state(page),binding=await page.evaluate(async()=>{const p='/src/adapters/core/current-connection.ts';return (await import(p)).getActiveCore().client.binding.id;});await page.route('**/core-api/v1/models',route=>route.fulfill({status:502,contentType:'application/json',body:'{"error":{"code":"model_directory_unavailable"}}'}));await page.getByRole('button',{name:'刷新模型列表',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'连接操作失败'})).toBeVisible();const after=await state(page);for(const table of ['connections','projects','graphs','runs','promptRuns'])expect(after[table]).toEqual(before[table]);expect(after.receipts.find((row:{id:string})=>row.id==='connection-catalog:c1').stale).toBe(true);expect(await page.evaluate(async()=>{const p='/src/adapters/core/current-connection.ts';return (await import(p)).getActiveCore().client.binding.id;})).toBe(binding);expect(JSON.stringify(after)).not.toContain('fake-stale-model-key');expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 K10 public configuration download failure preserves sources and permits only an explicit local export retry',async({page,networkCounter})=>{
 await page.goto('/settings/connections');await expect(page.getByLabel('已保存连接',{exact:true})).toHaveValue('c1');const before=await state(page);await page.evaluate(()=>{const original=HTMLAnchorElement.prototype.click;let armed=true;HTMLAnchorElement.prototype.click=function(){if(armed&&this.download){armed=false;throw new DOMException('native-public-export-denied','NotAllowedError');}return original.call(this);};});await page.getByRole('button',{name:'导出连接配置',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'连接操作失败'})).toBeVisible();expect(await state(page)).toEqual(before);const pending=page.waitForEvent('download');await page.getByRole('button',{name:'导出连接配置',exact:true}).click();const download=await pending,document=JSON.parse((await readFile((await download.path())!)).toString());expect(document.connections[0].originSnapshot).toBe(new URL(before.connections[0].originSnapshot).href);expect(JSON.stringify(document)).not.toMatch(/authBindingId|apiKey|token|authorization/);expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
