import {test,expect} from '../helpers/network-guard';
import {holdNextNativeCommit,releaseNativeCommit,nativeCommitProbe} from '../helpers/native-commit-hold';
import type {Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['projects','graphs','runs','promptDrafts','promptRuns','receipts'],'readonly',async(tx:IDBTransaction)=>Object.fromEntries(await Promise.all(['projects','graphs','runs','promptDrafts','promptRuns','receipts'].map(async table=>[table,await m.requestResult(tx.objectStore(table).getAll())]))));}finally{db.close();}});
async function deny(page:Page,table:string){await page.evaluate(target=>{const original=IDBObjectStore.prototype.put;let armed=true;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(armed&&this.name===target){armed=false;throw new DOMException('native-creative-operation-quota','QuotaExceededError');}return original.apply(this,args);};},table);}
test.beforeEach(async({page})=>{await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/generation.ts';await(await import(p)).seedGeneration();});});

test('T44 T08 native text-to-flow write failure is visible within its confirmation and preserves the original source and all task records',async({page,networkCounter})=>{
 await page.goto('/projects/p1/canvas');const before=await state(page);await page.getByTestId('node-text-1').getByRole('button',{name:'从文本创建视频流程',exact:true}).click();const dialog=page.getByRole('dialog',{name:'从文本创建视频流程',exact:true});await deny(page,'graphs');await dialog.getByRole('button',{name:'确认仅创建草稿',exact:true}).click();await expect(dialog.getByRole('alert')).toHaveText('存储空间不足，本次修改尚未保存。');await page.screenshot({path:'docs/review/screenshots/T44-flow-native-quota.png'});expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 PG15 actual unsaved manual output native quota blocks AI preview before any approval or billable request',async({page,networkCounter})=>{
 await page.goto('/prompt-generator?type=video');await page.evaluate(async()=>{const p='/tests/fixtures/generation.ts';(await import(p)).connectGeneration();});await page.getByLabel('原始创意',{exact:true}).fill('原创中文创作场景');await page.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(page.getByRole('button',{name:'AI优化',exact:true})).toBeEnabled();const before=await state(page);await page.getByLabel('最终提示词正文',{exact:true}).fill('尚未保存的人工中文正文，品牌康济健葆。');await deny(page,'promptDrafts');await page.getByRole('button',{name:'AI优化',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('保存失败，当前草稿保留；请重试保存，不会自动调用模型。');await expect(page.getByRole('dialog',{name:'AI文字优化确认',exact:true})).toHaveCount(0);expect(await state(page)).toEqual(before);await expect(page.getByLabel('最终提示词正文',{exact:true})).toHaveValue('尚未保存的人工中文正文，品牌康济健葆。');expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 PG30 actual native flow commit quota preserves the complete writing draft and leaves zero partial nodes, groups or execution records',async({page,networkCounter})=>{
 await page.evaluate(async()=>{const p='/tests/fixtures/prompt-workspace.ts';await (await import(p)).seedPromptWorkspace();});await page.goto('/prompt-generator?type=video&draftId=d1');await page.evaluate(async()=>{const p='/tests/fixtures/generation.ts';(await import(p)).connectGeneration();});await page.getByRole('button',{name:'本地整理',exact:true}).click();await expect(page.getByRole('button',{name:'仅建流程',exact:true})).toBeEnabled();await page.getByRole('button',{name:'仅建流程',exact:true}).click();const dialog=page.getByRole('dialog',{name:'选择插入目标',exact:true});await dialog.getByLabel('目标项目',{exact:true}).selectOption('p1');await dialog.getByLabel('流程视频规格',{exact:true}).selectOption('0');await expect(dialog.getByRole('button',{name:'确认仅建流程',exact:true})).toBeEnabled();const before=await state(page);await deny(page,'graphs');await dialog.getByRole('button',{name:'确认仅建流程',exact:true}).click();await expect(dialog.getByRole('alert')).toHaveText('存储写入失败，本次没有留下节点或连线；草稿保留，可重试。');expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 V05 real explicit reference with missing native file stays listed and blocks preflight without replacing its identity or sending',async({page,networkCounter})=>{
 await page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',f='/tests/helpers/fixtures.ts',m=await import(p),fixture=(await import(f)).f,db=await m.openStudioDb();try{await m.transact(db,['graphs','assets'],'readwrite',async(tx:IDBTransaction)=>{const graph=await m.requestResult(tx.objectStore('graphs').get('p1')),video=graph.nodes.find((n:{id:string})=>n.id==='video-1');graph.nodes.push({id:'missing-reference',title:'缺文件的原参考',type:'asset',x:40,y:360,locked:false,data:{kind:'asset',assetId:'a1'}});graph.edges.push({id:'missing-edge',sourceId:'missing-reference',targetId:'video-1',port:'image',order:1});video.data.inputBindings.push({nodeId:'missing-reference',assetId:'a1',order:1,role:'image'});tx.objectStore('graphs').put(graph);tx.objectStore('assets').put(fixture.asset());});}finally{db.close();}});await page.goto('/projects/p1/canvas');await page.evaluate(async()=>{const p='/tests/fixtures/generation.ts';(await import(p)).connectGeneration();});const before=await state(page),video=page.getByTestId('node-video-1');await expect(video.getByRole('list',{name:'显式参考素材列表',exact:true})).toContainText('缺文件的原参考');await video.locator('[data-interaction-id="V-08"]').click();await expect(page.getByRole('dialog',{name:'输入无效清单',exact:true})).toContainText('参考素材缺失或本地文件不可读');await expect(page.getByRole('dialog',{name:'生成确认单',exact:true})).toHaveCount(0);expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 V10 real pending durable approval disables local cancellation before dispatch and releases only the original confirmed request',async({page,networkCounter})=>{
 await page.goto('/projects/p1/canvas');await page.evaluate(async()=>{const p='/tests/fixtures/generation.ts';(await import(p)).connectGeneration();});await page.route('**/core-api/v1/videos/generations',route=>route.fulfill({status:202,contentType:'application/json',body:'{"task":{"id":"mock-t44-durable-approved","status":"queued"}}'}));await page.getByTestId('node-video-1').locator('[data-interaction-id="V-08"]').click();const dialog=page.getByRole('dialog',{name:'生成确认单',exact:true});await dialog.getByLabel('我确认以上输入，并知悉可能消耗积分且金额未知').check();await holdNextNativeCommit(page,'runs');await dialog.getByRole('button',{name:'确认提交 1 项',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});try{await expect(dialog.getByRole('button',{name:'返回编辑',exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'确认提交 1 项',exact:true})).toBeDisabled();expect(networkCounter.paidRequests).toHaveLength(0);const actual=await state(page);expect(actual.runs).toHaveLength(1);expect(actual.runs[0].executionState).toBe('persisted');}finally{await releaseNativeCommit(page);}await expect(page.getByText('已提交 1 项 · 追踪中',{exact:true})).toBeVisible();expect(networkCounter.paidRequests).toHaveLength(1);
});
