import {test,expect} from '../helpers/network-guard';import {seedStudio} from '../helpers/seed-studio';
const stored=(page:import('@playwright/test').Page)=>page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['graphs','runs','assets'],'readonly',async(tx:IDBTransaction)=>({graph:await m.requestResult(tx.objectStore('graphs').get('p1')),runs:await m.requestResult(tx.objectStore('runs').getAll()),assets:await m.requestResult(tx.objectStore('assets').getAll())}));}finally{db.close();}});
test.beforeEach(async({page})=>{await seedStudio(page,'unverified-capability');await page.goto('/projects/p1/canvas');});
test('T44 N03/N04 actual copy and paste buttons produce a new structure identity and preserve original media and Run after reload',async({page,networkCounter})=>{
 await expect(page.getByRole('button',{name:'复制节点',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'粘贴节点',exact:true})).toBeDisabled();await page.getByLabel('选择 镜头文字',{exact:true}).check();const before=await stored(page);await page.getByRole('button',{name:'复制节点',exact:true}).click();expect((await stored(page)).graph).toEqual(before.graph);await page.getByRole('button',{name:'粘贴节点',exact:true}).click();await expect(page.locator('[data-node-type="text"]')).toHaveCount(2);await page.reload();await expect(page.locator('[data-node-type="text"]')).toHaveCount(2);const after=await stored(page),added=after.graph.nodes.find((node:{id:string;type:string})=>node.type==='text'&&node.id!=='text-1');expect(added).toMatchObject({x:44,y:44,data:{text:'原创镜头'}});expect(after.runs).toEqual(before.runs);expect(after.assets).toEqual(before.assets);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 N12 arranging is previewed before a single native commit and survives reload without changing topology or execution',async({page,networkCounter})=>{
 const before=await stored(page);await page.getByRole('button',{name:'整理布局',exact:true}).click();const dialog=page.getByRole('dialog',{name:'预览布局',exact:true});await expect(dialog).toBeVisible();expect((await stored(page)).graph).toEqual(before.graph);await dialog.getByRole('button',{name:'应用布局',exact:true}).click();await expect(page.locator('.canvas-heading [role="status"]')).toContainText('已保存');const changed=await stored(page);expect(changed.graph.revision).toBe(before.graph.revision+1);expect(changed.graph.edges).toEqual(before.graph.edges);expect(changed.runs).toEqual(before.runs);await page.reload();expect((await stored(page)).graph).toEqual(changed.graph);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 N18 shot group name and order reject invalid input, save a native revision and survive reload without changing Run',async({page,networkCounter})=>{
 await page.getByLabel('选择 镜头组',{exact:true}).check();const before=await stored(page);await page.getByRole('button',{name:'镜头分组命名',exact:true}).click();const dialog=page.getByRole('dialog',{name:'编辑镜头分组',exact:true});await dialog.getByLabel('镜头分组名称',{exact:true}).fill('中'.repeat(61));await dialog.getByRole('button',{name:'保存镜头分组',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('1–60');expect((await stored(page)).graph).toEqual(before.graph);await dialog.getByLabel('镜头分组名称',{exact:true}).fill('原创镜头甲');await dialog.getByLabel('镜头序号',{exact:true}).fill('2');await dialog.getByRole('button',{name:'保存镜头分组',exact:true}).click();await page.reload();await expect(page.getByRole('button',{name:'编辑标题 原创镜头甲',exact:true})).toBeVisible();const after=await stored(page);expect(after.graph.nodes.find((n:{id:string})=>n.id==='group-1')).toMatchObject({title:'原创镜头甲',data:{shotOrder:2}});expect(after.runs).toEqual(before.runs);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 T02/T04 font preferences persist without editing text; clipboard rejection preserves source and gives a manual-copy path',async({page,networkCounter})=>{
 const before=await stored(page),node=page.getByTestId('node-text-1');await node.getByLabel('文本字号',{exact:true}).selectOption('20');await page.reload();await expect(node.getByLabel('文本字号',{exact:true})).toHaveValue('20');await expect(node.getByLabel('节点文本',{exact:true})).toHaveCSS('font-size','20px');await page.evaluate(()=>{Object.defineProperty(navigator.clipboard,'writeText',{value:async()=>{throw new DOMException('test-clipboard-denied','NotAllowedError');},configurable:true});});await node.getByRole('button',{name:'复制文本',exact:true}).click();await expect(node.getByRole('status')).toContainText('手动复制');expect((await stored(page)).graph).toEqual(before.graph);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 T03 inserting a selected but missing original records an unavailable reference rather than pretending the file is readable',async({page,networkCounter})=>{
 await page.getByLabel('选择 参考一',{exact:true}).check();const node=page.getByTestId('node-text-1');await node.getByRole('button',{name:'插入参考 @',exact:true}).click();await node.getByRole('button',{name:'参考一',exact:true}).click();await expect(node.getByRole('alert')).toContainText('参考素材不可用');await expect.poll(async()=>(await stored(page)).graph.nodes.find((n:{id:string})=>n.id==='text-1').data.referenceTokens[0]?.available).toBe(false);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 T03/T04 readable selected reference and successful clipboard copy preserve the original media and Run through reload',async({page,networkCounter})=>{
 await page.evaluate(async()=>{const url='/src/infrastructure/storage/database.ts',m=await import(url),db=await m.openStudioDb();try{await m.transact(db,['blobs'],'readwrite',(tx:IDBTransaction)=>{const bytes=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jf8kAAAAASUVORK5CYII='),c=>c.charCodeAt(0));tx.objectStore('blobs').put({id:'blob-a1',blob:new Blob([bytes],{type:'image/png'})});});}finally{db.close();}Object.defineProperty(navigator.clipboard,'writeText',{value:async(text:string)=>{document.documentElement.dataset.testCopiedText=text;},configurable:true});});await page.reload();await page.evaluate(()=>Object.defineProperty(navigator.clipboard,'writeText',{value:async(text:string)=>{document.documentElement.dataset.testCopiedText=text;},configurable:true}));const before=await stored(page);await page.getByLabel('选择 参考一',{exact:true}).check();const node=page.getByTestId('node-text-1');await node.getByRole('button',{name:'插入参考 @',exact:true}).click();await node.getByRole('button',{name:'参考一',exact:true}).click();await expect.poll(async()=>(await stored(page)).graph.nodes.find((n:{id:string})=>n.id==='text-1').data.referenceTokens[0]?.available).toBe(true);await node.getByRole('button',{name:'复制文本',exact:true}).click();await expect(node.getByRole('status')).toContainText('已复制');expect(await page.evaluate(()=>document.documentElement.dataset.testCopiedText)).toBe('原创镜头 @参考一');await page.reload();await expect(node.getByLabel('节点文本',{exact:true})).toHaveValue('原创镜头 @参考一');await expect(node.getByRole('alert')).toHaveCount(0);const after=await stored(page);expect(after.assets).toEqual(before.assets);expect(after.runs).toEqual(before.runs);expect(networkCounter.paidRequests).toHaveLength(0);
});
