import {localDeployment} from '../helpers/deployment-fixture';
import {test,expect} from '../helpers/network-guard';
import {seedStudio} from '../helpers/seed-studio';
async function countAssets(page:import('@playwright/test').Page){return page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['assets'],'readonly',(tx:IDBTransaction)=>m.requestResult(tx.objectStore('assets').count()));}finally{db.close();}});}
test('T44 D04/M01/M02 import inspection rejects active content, waits for explicit commit, cancellation writes nothing',async({page,networkCounter})=>{
 await page.goto('/assets');const bytes=await page.evaluate(async()=>{const p='/tests/fixtures/asset-library.ts';return Array.from(new Uint8Array(await(await(await import(p)).imageFile()).arrayBuffer()));});const before=await countAssets(page);await page.getByLabel('导入素材',{exact:true}).setInputFiles([{name:'有效.png',mimeType:'image/png',buffer:Buffer.from(bytes)},{name:'恶意.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg onload="globalThis.pwned=true"/>')}]);const dialog=page.getByRole('dialog',{name:'文件导入检查',exact:true});await expect(dialog).toHaveAttribute('data-dialog-id','D04');await expect(dialog).toContainText('恶意.svg');await expect(dialog).toContainText('未写入');expect(await countAssets(page)).toBe(before);await page.keyboard.press('Escape');expect(await countAssets(page)).toBe(before);await page.getByLabel('导入素材',{exact:true}).setInputFiles({name:'有效.png',mimeType:'image/png',buffer:Buffer.from(bytes)});await page.getByRole('dialog',{name:'文件导入检查',exact:true}).getByRole('button',{name:'确认导入 1 个有效文件',exact:true}).click();await expect.poll(()=>countAssets(page)).toBe(before+1);await page.reload();expect(await countAssets(page)).toBe(before+1);expect(await page.evaluate(()=>(globalThis as unknown as {pwned?:boolean}).pwned)).toBeUndefined();expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 D01/D02/D03/D19 actual dialogs preserve identity and enforce destructive impact gates',async({page,networkCounter})=>{
 await seedStudio(page,'project-library');await page.goto('/projects');await page.getByRole('button',{name:'新建项目',exact:true}).click();await expect(page.getByRole('dialog',{name:'新建项目',exact:true})).toHaveAttribute('data-dialog-id','D01');await page.keyboard.press('Escape');await page.getByTestId('project-p1').getByRole('button',{name:'复制项目',exact:true}).click();await expect(page.getByRole('dialog',{name:'复制项目',exact:true})).toHaveAttribute('data-dialog-id','D02');await page.keyboard.press('Escape');await page.getByTestId('project-p1').getByRole('button',{name:'移入回收站',exact:true}).click();await expect(page.getByRole('dialog',{name:'移入项目回收站',exact:true})).toHaveAttribute('data-dialog-id','D03');await page.getByRole('dialog',{name:'移入项目回收站',exact:true}).getByRole('button',{name:'移入回收站',exact:true}).click();await page.goto('/trash');await page.getByTestId('trash-p1').getByRole('button',{name:'永久删除本地副本',exact:true}).click();await expect(page.getByRole('dialog',{name:'永久删除本地副本',exact:true})).toHaveAttribute('data-dialog-id','D19');await expect(page.getByRole('dialog').getByRole('button',{name:'永久删除',exact:true})).toBeDisabled();expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 D12/J11 original authorization rejects a wrong Key without changing historical binding or allowing POST, then accepts explicit original-resource read',async({page,networkCounter})=>{
 await page.route('**/studio-deployment.json',route=>route.fulfill({contentType:'application/json',body:JSON.stringify(localDeployment)}));await page.route('**/core-api/v1/videos/mock-core-1',route=>route.fulfill({status:route.request().headers().authorization==='Bearer fake-correct-t44-key'?200:401,contentType:'application/json',body:JSON.stringify({task:{id:'mock-core-1',status:'processing'}})}));await page.route('**/core-api/healthz',route=>route.fulfill({contentType:'application/json',body:'{"status":"ok"}'}));await page.route('**/core-api/v1/models',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({data:[{id:'fake-text-only'},{id:'fake-video-only'}]})})); await page.goto('/tasks');await page.evaluate(async()=>{const p='/tests/fixtures/task-history.ts';await(await import(p)).seedTaskHistory();});await page.reload();await page.getByTestId('video-run-1').getByRole('button',{name:'详情',exact:true}).click();await page.getByRole('button',{name:'补充原授权',exact:true}).click();const dialog=page.getByRole('dialog',{name:'重新授权原任务',exact:true});await expect(dialog).toHaveAttribute('data-dialog-id','D12');await expect(dialog.getByRole('button',{name:'只读验证原任务',exact:true})).toBeDisabled();await dialog.getByLabel('原任务普通 Key',{exact:true}).fill('fake-wrong-t44-key');await dialog.getByLabel('我确认此授权用于所列原任务，不改变其服务或归属',{exact:true}).check();await dialog.getByRole('button',{name:'只读验证原任务',exact:true}).click();await expect(dialog.getByRole('alert')).toBeVisible();expect(networkCounter.paidRequests).toHaveLength(0);await dialog.getByLabel('原任务普通 Key',{exact:true}).fill('fake-correct-t44-key');await dialog.getByRole('button',{name:'只读验证原任务',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole('dialog',{name:'任务详情',exact:true})).toContainText('已使用当前输入授权只读验证原任务');await page.keyboard.press('Escape');await page.reload();const stored=await page.evaluate(async()=>{const p='/tests/fixtures/task-history.ts';return(await import(p)).taskHistoryState();});expect(stored.runs.find((r:{id:string})=>r.id==='video-run-1').authBindingId).toBe('task-original-binding');expect(JSON.stringify(stored)).not.toContain('fake-wrong-t44-key');expect(JSON.stringify(stored)).not.toContain('fake-correct-t44-key');expect(networkCounter.paidRequests).toHaveLength(0);
});
