import {test,expect} from '../helpers/network-guard';
import {resolve} from 'node:path';
import {createServer} from 'node:http';
import {randomUUID,createHash} from 'node:crypto';
import {mkdirSync,writeFileSync,readFileSync,cpSync} from 'node:fs';
import {unzipSync} from 'fflate';
import {listenLocal,closeLocal,rawLocalRequest,startOwnedNode,startupLine,stopOwnedNode} from '../helpers/distribution-runtime';
const runtimeModule=resolve('scripts/serve-local.mjs');
test('T47 nonsecret runtime registration rejects credential aliases inside otherwise accepted contract metadata',async({networkCounter})=>{
 const m=await import(runtimeModule);for(const name of ['coreKey','privateToken','CoreAuthorization']){const runtime={...m.offlineRuntime,connections:[{profile:{id:'local-config-test',name:'配置测试',originSnapshot:'https://core.example.invalid',proxyBase:'/core-api',contractVersion:'test'},contract:{version:'test',evidence:[{kind:'deployment_review',reference:'local-only',details:{[name]:'STUDIO_T47_CREDENTIAL_DO_NOT_EXPORT'}}]}}]};expect(()=>m.validateRuntime(runtime),name).toThrow('runtime_credentials_denied');}expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T47 production CSP permits validated local creation and native persistence across full-page reload without generation',async({page,networkCounter})=>{
 await page.goto('/projects');await page.getByRole('button',{name:'新建项目',exact:true}).click();const dialog=page.getByRole('dialog',{name:'新建项目',exact:true});await dialog.getByLabel('项目名称',{exact:true}).fill('中'.repeat(61));await dialog.getByRole('button',{name:'创建',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('1–60');await dialog.getByLabel('项目名称',{exact:true}).fill('发行构建真实保存');await dialog.getByRole('button',{name:'创建',exact:true}).click();await expect(page).toHaveURL(/\/projects\/[^/]+\/canvas$/);await expect(page.getByRole('button',{name:'立即保存',exact:true})).toBeEnabled();await page.reload();await expect(page.getByRole('heading',{name:'发行构建真实保存',exact:true})).toBeVisible();await page.goto('/projects');await page.reload();await expect(page.getByRole('heading',{name:'发行构建真实保存',exact:true})).toBeVisible();expect(networkCounter.paidRequests).toHaveLength(0);await page.screenshot({path:'docs/review/screenshots/T47-production-persisted-project.png'});
});
test('T47 fixed target selection honors the longest registered service prefix alongside the default service',async({networkCounter})=>{
 const m=await import(runtimeModule),seen:string[]=[],a=createServer((req,res)=>{seen.push('a:'+req.url);res.setHeader('Content-Type','application/json');res.end('{"service":"a"}');}),b=createServer((req,res)=>{seen.push('b:'+req.url);res.setHeader('Content-Type','application/json');res.end('{"service":"b"}');}),oa=await listenLocal(a),ob=await listenLocal(b),entries=[{base:'/core-api',origin:oa,id:'a'},{base:'/core-api/registered/b',origin:ob,id:'b'}],runtime={...m.offlineRuntime,connections:entries.map(e=>({profile:{id:e.id,name:e.id,originSnapshot:e.origin,proxyBase:e.base,contractVersion:'mock'},contract:{version:'mock'}})),coreTargets:entries.map(e=>({proxyBase:e.base,origin:e.origin,allowWrites:false}))},server=m.createLocalServer({runtime}),origin=await listenLocal(server);
 try{const registered=await rawLocalRequest(origin,'/core-api/registered/b/v1/models');expect(registered.status).toBe(200);expect(JSON.parse(registered.body)).toEqual({service:'b'});const original=await rawLocalRequest(origin,'/core-api/v1/models');expect(original.status).toBe(200);expect(JSON.parse(original.body)).toEqual({service:'a'});expect(seen).toEqual(['b:/v1/models','a:/v1/models']);expect(networkCounter.paidRequests).toHaveLength(0);}finally{await closeLocal(server);await closeLocal(a);await closeLocal(b);}
});
test('T47-C04 actual production build opens and refreshes its own nested routes without Core traffic',async({page,networkCounter})=>{
 for(const path of ['/projects','/settings/storage','/help']){await page.goto(path);await page.reload();await expect(page.getByRole('link',{name:'AI WORK Studio',exact:true})).toBeVisible();await expect(page.getByText('由 Core 执行').first()).toHaveCount(0);expect(await page.locator('iframe').count()).toBe(0);}expect(networkCounter.paidRequests).toHaveLength(0);await page.screenshot({path:'docs/review/screenshots/T47-production-help.png'});
});
test('T47 Q02 production copyright dialog opens explicitly, retains original rights and returns focus without a default external channel',async({page,networkCounter})=>{
 await page.goto('/help');const opener=page.locator('[data-interaction-id="Q-02"]');await opener.click();const dialog=page.getByRole('dialog',{name:'第三方许可与来源',exact:true});await expect(dialog).toBeVisible();await dialog.getByText('画布逻辑许可',{exact:true}).click();await expect(dialog.locator('pre').filter({hasText:'MIT License'}).first()).toBeVisible();expect(await dialog.locator('a[href^="http"]').count()).toBe(0);await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(opener).toBeFocused();expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T47-C01/C02/C07 artifact scanners reject promotion, counterfeit legal chunks, source maps, sentinel credentials and modified license copies',async({networkCounter})=>{
 const b=await import(resolve('scripts/check-brand.mjs')),l=await import(resolve('scripts/check-license.mjs')),base=resolve('work/t47-scan-'+randomUUID());mkdirSync(base,{recursive:true});
 for(const [name,text]of [['page.js',"window.location='https://infinite-canvas.example.invalid';"],['legal-notices-counterfeit.js',"export const ad='infinite-canvas promotional shortcut';"],['page.map','{}'],['credential.js',"const value='STUDIO_T47_CREDENTIAL_DO_NOT_EXPORT';"]]){const root=base+'/'+name;mkdirSync(root);writeFileSync(root+'/'+name,text);expect(b.scanBrand(root).passed,name).toBe(false);}
 expect(b.scanBrand().passed).toBe(true);const copies=base+'/licenses';cpSync('third-party',copies,{recursive:true});const retained=l.scanLicenses(copies);expect(retained.preservedAll).toBe(true);expect(retained.releaseAllowed).toBe(false);expect(retained.frontendMarkAuthorization).toBe('unresolved');writeFileSync(copies+'/licenses/infinite-canvas.LICENSE','tampered');expect(l.scanLicenses(copies).modified).toContain('licenses/infinite-canvas.LICENSE');expect(l.scanLicenses().preservedAll).toBe(true);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T47-C03/C05 actual fixed loopback proxy refuses raw traversal/admin, follows no redirect, strips Cookie and never retries a lost POST',async({networkCounter})=>{
 const m=await import(runtimeModule),seen:{path:string;method:string;cookie?:string;authorization?:string;body:string}[]=[],sinkHits:string[]=[];
 const sink=createServer((req,res)=>{sinkHits.push(req.url??'');res.end('sink');}),sinkOrigin=await listenLocal(sink),mock=createServer(async(req,res)=>{const chunks:Buffer[]=[];for await(const chunk of req)chunks.push(chunk);seen.push({path:req.url??'',method:req.method??'',cookie:req.headers.cookie,authorization:req.headers.authorization,body:Buffer.concat(chunks).toString()});if(req.url==='/v1/models'){res.writeHead(302,{Location:sinkOrigin+'/leak'}).end();}else req.socket.destroy();}),mockOrigin=await listenLocal(mock);
 const runtime={...m.offlineRuntime,port:0,connections:[{profile:{id:'mock-core',name:'本地Mock',originSnapshot:mockOrigin,proxyBase:'/core-api/registered/mock',contractVersion:'local-mock-v1'},contract:{version:'local-mock-v1'}}],coreTargets:[{proxyBase:'/core-api/registered/mock',origin:mockOrigin,allowWrites:true}]},server=m.createLocalServer({runtime}),origin=await listenLocal(server);
 try{expect(server.address().address).toBe('127.0.0.1');for(const path of ['/core-api/registered/mock/admin/v1','/core-api/registered/mock/%2e%2e/admin','/%2e%2e/package.json'])expect((await rawLocalRequest(origin,path)).status).toBe(403);expect(seen).toHaveLength(0);expect((await rawLocalRequest(origin,'/core-api/registered/mock/v1/models')).status).toBe(502);expect(sinkHits).toHaveLength(0);expect(seen).toHaveLength(1);
  const body='{"model":"fake-video-only","prompt":"冻结正文"}',path='/core-api/registered/mock/v1/videos/generations';expect((await rawLocalRequest(origin,path,{method:'POST',headers:{'Content-Type':'application/json'},body})).status).toBe(400);expect(seen).toHaveLength(1);const result=await rawLocalRequest(origin,path,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':'same-frozen-test-identity',Authorization:'Bearer fake-local-test-only',Cookie:'must-not-forward=1'},body});expect(result.status).toBe(502);expect(JSON.parse(result.body)).toEqual({error:{code:'core_transport_unknown'}});expect(seen).toHaveLength(2);expect(seen[1]).toMatchObject({path:'/v1/videos/generations',method:'POST',authorization:'Bearer fake-local-test-only',body});expect(seen[1].cookie).toBeUndefined();expect(sinkHits).toHaveLength(0);
  const blocked=m.createLocalServer({runtime:{...runtime,coreTargets:[{...runtime.coreTargets[0],allowWrites:false}]}}),blockedOrigin=await listenLocal(blocked);try{expect((await rawLocalRequest(blockedOrigin,path,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':'same-frozen-test-identity'},body})).status).toBe(403);expect(seen).toHaveLength(2);}finally{await closeLocal(blocked);}expect(networkCounter.paidRequests).toHaveLength(0);
 }finally{await closeLocal(server);await closeLocal(mock);await closeLocal(sink);}
});
test('T47 offline ZIP has actual per-file and archive SHA256, complete licenses and starts from its extracted files without development dependencies',async({networkCounter})=>{
 const p=await import(resolve('scripts/package-release.mjs')),root=resolve('work/t47-unpacked-'+randomUUID());mkdirSync(root,{recursive:true});expect(()=>p.packageRelease({outputDir:root,offlineReview:false})).toThrow('frontend_mark_release_gate_unresolved');const built=p.packageRelease({outputDir:root,offlineReview:true}),zip=readFileSync(built.output),entries=unzipSync(new Uint8Array(zip)),hash=(bytes:Uint8Array|string)=>createHash('sha256').update(bytes).digest('hex');expect(hash(zip)).toBe(built.sha256);const manifest=JSON.parse(new TextDecoder().decode(entries['distribution-manifest.json']));expect(manifest).toMatchObject({kind:'offline-review',formalReleaseApproved:false,liveVerified:false,coreConfigured:false});
 for(const row of manifest.files as {file:string;sha256:string;bytes:number}[]){expect(entries[row.file].length).toBe(row.bytes);expect(hash(entries[row.file]),row.file).toBe(row.sha256);}expect(Object.keys(entries).filter(name=>/(?:^|\/)(?:node_modules|tests|work)\/|\.map$|\.db$/.test(name))).toEqual([]);expect(entries['third-party/licenses/infinite-canvas.docs_content_docs_business_license.zh-CN.mdx']).toBeTruthy();expect(entries['companion/dist/main.mjs']).toBeTruthy();
 for(const [name,bytes]of Object.entries(entries)){if(name.startsWith('/')||name.split('/').includes('..'))throw Error('unsafe_owned_archive_path');const target=resolve(root,name);mkdirSync(resolve(target,'..'),{recursive:true});writeFileSync(target,bytes);if(/\.(mjs|js|json)$/.test(name))expect(new TextDecoder().decode(bytes)).not.toContain('STUDIO_T47_CREDENTIAL_DO_NOT_EXPORT');}
 for(const [name,bytes]of Object.entries(entries))if(name.startsWith('companion/dist/')&&/\.(mjs|js)$/.test(name)){const imports=[...new TextDecoder().decode(bytes).matchAll(/from\s+["']([^"']+)["']/g)].map(m=>m[1]);expect(imports.filter(value=>!value.startsWith('node:')&&!value.startsWith('.')),name+' cannot require undeployed node_modules').toEqual([]);}
 const child=startOwnedNode(resolve(root,'scripts/serve-local.mjs'),['--root',resolve(root,'dist'),'--port','0'],root);try{const origin=await startupLine(child,/http:\/\/127\.0\.0\.1:\d+/);expect((await rawLocalRequest(origin,'/projects/p1/canvas')).status).toBe(200);expect((await rawLocalRequest(origin,'/core-api/admin/v1/api-keys')).status).toBe(403);expect(JSON.parse((await rawLocalRequest(origin,'/studio-deployment.json')).body)).toEqual({schemaVersion:1,connections:[]});}finally{await stopOwnedNode(child);}
 const reservation=createServer(),reserved=await listenLocal(reservation),port=new URL(reserved).port;await closeLocal(reservation);const companion=startOwnedNode(resolve(root,'companion/dist/main.mjs'),[],root,{STUDIO_ORIGIN:'http://127.0.0.1:4188',STUDIO_AGENT_PORT:port});try{const origin=await startupLine(companion,/http:\/\/127\.0\.0\.1:\d+/);const denied=await rawLocalRequest(origin,'/canvas/connect',{method:'POST',headers:{Origin:'http://attacker.invalid','Content-Type':'application/json'},body:'{}'});expect(denied.status).toBe(403);expect(JSON.parse(denied.body)).toMatchObject({errorCode:'origin_denied'});
  const mcp=startOwnedNode(resolve(root,'companion/dist/mcp.mjs'),[],root,{STUDIO_AGENT_ENDPOINT:origin,STUDIO_AGENT_TOKEN:'studio-agent-'+'A'.repeat(43),STUDIO_AGENT_SESSION:'unpaired-initialization-only'});try{const initialized=startupLine(mcp,/"protocolVersion":"2025-03-26"/);mcp.stdin!.write(JSON.stringify({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'local-distribution-test',version:'1'}}})+'\n');expect(await initialized).toBe('"protocolVersion":"2025-03-26"');}finally{await stopOwnedNode(mcp);}
 }finally{await stopOwnedNode(companion);}expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T47-C05 unknown Core, admin, absolute and encoded paths are denied by the actual local startup server',async({page,networkCounter})=>{
 for(const path of ['/core-api/admin/v1/api-keys','/core-api/v1/finance','/core-api/https://business.invalid/','/core-api/%2Fadmin']){const reply=await page.request.get(path);expect([403,404],path).toContain(reply.status());}expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T47-C03 only loopback may be configured and foreign Host requests never render the application',async({page,networkCounter})=>{
 const m=await import(runtimeModule);expect(()=>m.validateRuntime({schemaVersion:1,host:'0.0.0.0',port:4179,connections:[],coreTargets:[]})).toThrow('localhost_only');const reply=await page.request.get('/projects',{headers:{Host:'attacker.invalid:4179'}});expect(reply.status()).toBe(403);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T47-C06 runtime rejects credentials at every depth and browser runtime never exports a Key',async({page,networkCounter})=>{
 const m=await import(runtimeModule);for(const extra of [{apiKey:'fake-for-test'},{nested:{Authorization:'fake-for-test'}},{cookie:'fake-for-test'}])expect(()=>m.validateRuntime({schemaVersion:1,host:'127.0.0.1',port:4179,connections:[],coreTargets:[],...extra})).toThrow();const response=await page.request.get('/studio-deployment.json');expect(response.headers()['content-type']).toContain('application/json');expect(await response.json()).toEqual({schemaVersion:1,connections:[]});expect(networkCounter.paidRequests).toHaveLength(0);
});
