import {test,expect} from '../helpers/network-guard';
import {seedStudio} from '../helpers/seed-studio';
import type {Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['projects','graphs','runs','promptRuns','prompts','promptDrafts'],'readonly',async(tx:IDBTransaction)=>Promise.all(['projects','graphs','runs','promptRuns','prompts','promptDrafts'].map(table=>m.requestResult(tx.objectStore(table).getAll()))));}finally{db.close();}});

test('T44 T04/T05/PG01 actual empty text and multi-selection disable their inapplicable actions without an execution',async({page,networkCounter})=>{
 await seedStudio(page,'unverified-capability');await page.goto('/projects/p1/canvas');const text=page.getByTestId('node-text-1');await text.getByRole('textbox',{name:'节点文本',exact:true}).fill('');await expect(text.getByRole('button',{name:'复制文本',exact:true})).toBeDisabled();await expect(text.getByRole('button',{name:'保存为提示词',exact:true})).toBeDisabled();await expect(text.getByRole('button',{name:'从文本创建视频流程',exact:true})).toBeDisabled();await page.getByRole('checkbox',{name:'选择 镜头文字',exact:true}).check();await page.getByRole('checkbox',{name:'选择 视频草稿',exact:true}).check();await expect(page.locator('[data-interaction-id="PG01"]')).toBeDisabled();await expect.poll(async()=>(await state(page))[1][0].nodes.find((node:{id:string})=>node.id==='text-1').data.text).toBe('');expect((await state(page))[2]).toHaveLength(1);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 L01 actual new prompt has no save action until both name and body exist; project package export needs a local project',async({page,networkCounter})=>{
 await page.goto('/projects');await page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{await m.transact(db,db.tables.slice(),'readwrite',(tx:IDBTransaction)=>{for(const table of db.tables)tx.objectStore(table).clear();});}finally{db.close();}});await page.goto('/prompts');await page.getByRole('button',{name:'新建提示词',exact:true}).click();const dialog=page.getByRole('dialog',{name:'编辑提示词',exact:true});await expect(dialog.getByRole('button',{name:'保存提示词',exact:true})).toBeDisabled();await dialog.getByLabel('提示词名称',{exact:true}).fill('仅填写名称');await expect(dialog.getByRole('button',{name:'保存提示词',exact:true})).toBeDisabled();await dialog.getByLabel('提示词正文',{exact:true}).fill('中文创作正文');await expect(dialog.getByRole('button',{name:'保存提示词',exact:true})).toBeEnabled();await dialog.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('dialog',{name:'放弃未保存提示词修改',exact:true}).getByRole('button',{name:'确认放弃修改',exact:true}).click();const before=await state(page);await page.goto('/projects/packages');await expect(page.getByRole('button',{name:'导出项目包',exact:true})).toBeDisabled();expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 J01/J08/J09 actual unknown task cannot archive and empty filtering cannot export; failed native filtering keeps original states',async({page,networkCounter})=>{
 await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/task-history.ts';await (await import(p)).seedTaskHistory();});await page.goto('/tasks');await expect(page.getByTestId('video-run-unknown').getByRole('button',{name:'归档记录',exact:true})).toBeDisabled();const before=await state(page);await page.getByLabel('执行状态筛选',{exact:true}).selectOption('failed_confirmed');await expect(page.getByRole('button',{name:'导出脱敏CSV',exact:true})).toBeDisabled();await page.evaluate(()=>{const original=IDBObjectStore.prototype.getAll;let armed=true;IDBObjectStore.prototype.getAll=function(...args:Parameters<typeof original>){if(armed&&this.name==='runs'){armed=false;throw new DOMException('native-task-filter-read-failed','UnknownError');}return original.apply(this,args);};});await page.getByLabel('执行状态筛选',{exact:true}).selectOption('running');await expect(page.getByRole('alert')).toHaveText('本地任务读取失败，原记录保留，请重试。');expect(await state(page)).toEqual(before);await page.getByRole('button',{name:'清除筛选',exact:true}).click();await expect(page.getByTestId('video-run-unknown')).toBeVisible();expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 PG29/PG32 a real empty independent draft cannot clear or apply to a nonexistent source',async({page,networkCounter})=>{
 await page.goto('/projects');await page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{await m.transact(db,db.tables.slice(),'readwrite',(tx:IDBTransaction)=>{for(const table of db.tables)tx.objectStore(table).clear();});}finally{db.close();}});await page.goto('/prompt-generator?type=video');await expect(page.getByLabel('原始创意',{exact:true})).toHaveValue('');await page.getByLabel('原始创意',{exact:true}).fill('本地临时输入');await page.getByLabel('原始创意',{exact:true}).fill('');await expect(page.getByRole('button',{name:'清空输入',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'应用到源节点',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'AI优化',exact:true})).toBeDisabled();const saved=await state(page);expect(saved[2]).toHaveLength(0);expect(saved[3]).toHaveLength(0);expect(saved[5]).toHaveLength(1);expect(saved[5][0].sourceProjectId).toBeUndefined();expect(networkCounter.paidRequests).toHaveLength(0);
});
