import {test,expect} from '../helpers/network-guard';
import {seedStudio} from '../helpers/seed-studio';
import type {Page} from '@playwright/test';
test.use({actionTimeout:2000});test.setTimeout(20000);
async function boot(page:Page){await seedStudio(page,'unverified-capability');await page.evaluate(async()=>{
 const seedUrl='/tests/fixtures/generation.ts';await (await import(seedUrl)).seedGeneration();
});await page.goto('/projects/p1/canvas');await expect(page.getByTestId('node-text-1').getByLabel('节点文本')).toBeEditable();await page.evaluate(async()=>{const path='/tests/fixtures/generation.ts';await (await import(path)).connectGeneration();});}
async function open(page:Page){await page.getByTestId('node-video-1').locator('[data-interaction-id="V-08"]').click();return page.getByRole('dialog',{name:'生成确认单',exact:true});}
test.beforeEach(async({page})=>{await boot(page);await page.route('**/core-api/v1/videos/generations',route=>route.fulfill({status:202,contentType:'application/json',body:JSON.stringify({task:{id:'mock-confirm-video-1',status:'queued'},request_id:'mock-confirm-request-1'})}));});
test('T26-C01/C06: actual preflight lists visible inputs and unknown fee with zero uploads or paid requests',async({page,networkCounter})=>{const dialog=await open(page);await expect(dialog).toBeVisible();await expect(dialog).toContainText('金额未知');await expect(dialog).toContainText('原创确认正文');await expect(dialog).toContainText('1 项');await expect(dialog).toContainText('本地Mock');expect(networkCounter.requests.filter(r=>r.method==='POST')).toEqual([]);await page.screenshot({path:'docs/review/screenshots/T26-generation-confirm.png'});});
test('T26-C02/C05: deliberate double click preserves one approval and sends exactly one confirmed frozen request',async({page,networkCounter})=>{const dialog=await open(page);expect(networkCounter.paidRequests).toHaveLength(0);await dialog.getByLabel('我确认以上输入，并知悉可能消耗积分且金额未知').check();await dialog.getByRole('button',{name:'确认提交 1 项',exact:true}).evaluate(button=>{(button as HTMLButtonElement).click();(button as HTMLButtonElement).click();});await expect(page.getByText('已提交 1 项 · 追踪中',{exact:true})).toBeVisible();const saved=await page.evaluate(async()=>{const path='/src/infrastructure/storage/database.ts',m=await import(path);return m.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>m.transact(db,['runs','receipts'],'readonly',async(tx:IDBTransaction)=>({runs:await m.requestResult(tx.objectStore('runs').getAll()),approvals:(await m.requestResult(tx.objectStore('receipts').getAll())).filter((r:{id:string})=>r.id.startsWith('approval:'))})));});expect(saved.runs).toHaveLength(1);expect(saved.approvals).toHaveLength(1);expect(saved.approvals[0].planHash).toMatch(/^[a-f0-9]{64}$/);expect(saved.approvals[0].revision).toBe(1);expect(saved.approvals[0].nodeCount).toBe(1);expect(saved.runs[0].inputSnapshot.prompt).toBe('原创确认正文');expect(JSON.parse(saved.runs[0].finalBody)).toEqual({model:'fake-video-only',prompt:'原创确认正文',duration:5,ratio:'9:16'});expect(saved.runs[0].executionState).toBe('accepted');expect(networkCounter.paidRequests).toHaveLength(1);});
test('T26-C03: unsupported duration produces an explicit blocker without clamping the draft',async({page})=>{await page.evaluate(async()=>{const path='/src/infrastructure/storage/database.ts',m=await import(path);await m.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>m.transact(db,['graphs'],'readwrite',async(tx:IDBTransaction)=>{const graph=await m.requestResult(tx.objectStore('graphs').get('p1'));graph.nodes.find((n:{id:string})=>n.id==='video-1').data.draft.durationSeconds=15;tx.objectStore('graphs').put(graph);}));});await page.reload();await page.evaluate(async()=>{const path='/tests/fixtures/generation.ts';await (await import(path)).connectGeneration();});await page.getByTestId('node-video-1').locator('[data-interaction-id="V-08"]').click();const dialog=page.getByRole('dialog',{name:'输入无效清单'});await expect(dialog).toContainText('时长或比例');expect(await page.getByTestId('node-video-1').getByLabel('时长（秒）').inputValue()).toBe('15');await expect(page.getByRole('dialog',{name:'生成确认单'})).not.toBeVisible();});
test('T26-C04: persisted graph changes after preview invalidate the approval and create no Run',async({page})=>{const dialog=await open(page);await page.evaluate(async()=>{const path='/src/infrastructure/storage/database.ts',m=await import(path);await m.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>m.transact(db,['projects','graphs'],'readwrite',async(tx:IDBTransaction)=>{for(const name of ['projects','graphs']){const row=await m.requestResult(tx.objectStore(name).get('p1'));row.revision++;tx.objectStore(name).put(row);}}));});await dialog.getByLabel('我确认以上输入，并知悉可能消耗积分且金额未知').check();await dialog.getByRole('button',{name:'确认提交 1 项',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('已变化');});
test('T26 V-10: Escape cancels without approval or Run and restores the preflight button focus',async({page,networkCounter})=>{const dialog=await open(page);await expect(dialog).toBeVisible();await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();await expect(page.getByTestId('node-video-1').locator('[data-interaction-id="V-08"]')).toBeFocused();expect(networkCounter.requests.filter(r=>r.method==='POST')).toEqual([]);});
test('T26: confirmation remains disabled until the exact fee/input acknowledgment is selected',async({page})=>{const dialog=await open(page);await expect(dialog.getByRole('button',{name:'确认提交 1 项',exact:true})).toBeDisabled();});
test('T26: readable checkbox stays beside its acknowledgment rather than spanning the dialog',async({page})=>{const dialog=await open(page),box=dialog.getByLabel('我确认以上输入，并知悉可能消耗积分且金额未知');await expect(box).toBeVisible();const geometry=await box.boundingBox();expect(geometry!.width).toBeLessThan(32);await expect(box.locator('..')).toHaveCSS('display','flex');});
test('T26: quota failure atomically preserves draft and refuses approval/Run creation',async({page,networkCounter})=>{const dialog=await open(page);await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(this.name==='runs')throw new DOMException('injected confirmation quota','QuotaExceededError');return original.apply(this,args);};});await dialog.getByLabel('我确认以上输入，并知悉可能消耗积分且金额未知').check();await dialog.getByRole('button',{name:'确认提交 1 项',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('保存失败');const counts=await page.evaluate(async()=>{const path='/src/infrastructure/storage/database.ts',m=await import(path);return m.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>m.transact(db,['runs','receipts'],'readonly',async(tx:IDBTransaction)=>({runs:await m.requestResult(tx.objectStore('runs').count()),approvals:(await m.requestResult(tx.objectStore('receipts').getAll())).filter((r:{id:string})=>r.id.startsWith('approval:')).length})));});expect(counts).toEqual({runs:0,approvals:0});expect(networkCounter.paidRequests).toHaveLength(0);});
test('T26: changing text even without revision bump invalidates the reviewed input snapshot',async({page})=>{const dialog=await open(page);await page.evaluate(async()=>{const path='/src/infrastructure/storage/database.ts',m=await import(path);await m.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>m.transact(db,['graphs'],'readwrite',async(tx:IDBTransaction)=>{const graph=await m.requestResult(tx.objectStore('graphs').get('p1'));graph.nodes.find((n:{id:string})=>n.id==='text-1').data.text='确认后改变';tx.objectStore('graphs').put(graph);}));});await dialog.getByLabel('我确认以上输入，并知悉可能消耗积分且金额未知').check();await dialog.getByRole('button',{name:'确认提交 1 项',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('已变化');});
