import {test,expect} from '../helpers/network-guard';
import {seedStudio} from '../helpers/seed-studio';
import {readFile} from 'node:fs/promises';
import {unzipSync,strFromU8} from 'fflate';
test('T44 G06/D03 immediate save reads actual commit status and flushes current text without charging',async({page,networkCounter})=>{
 await seedStudio(page,'canvas-project');await page.goto('/projects/p1/canvas');await page.getByRole('button',{name:'立即保存',exact:true}).click();await page.getByRole('button',{name:'保存详情',exact:true}).click();await expect(page.getByRole('dialog',{name:'保存详情',exact:true})).toContainText('上次成功保存');await page.keyboard.press('Escape');await page.getByLabel('节点文本',{exact:true}).fill('立即保存的最新中文稿');await page.getByRole('button',{name:'立即保存',exact:true}).click();await page.reload();await expect(page.getByLabel('节点文本',{exact:true})).toHaveValue('立即保存的最新中文稿');expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 G10 restore layout preserves all node coordinates, creative revision and task identities',async({page,networkCounter})=>{
 await seedStudio(page,'canvas-project');await page.goto('/projects/p1/canvas');await page.getByRole('button',{name:'显示小地图',exact:true}).click();const before=await page.getByTestId('node-text-1').getAttribute('style');await page.getByRole('button',{name:'Agent 协作',exact:true}).click();await page.getByRole('button',{name:'恢复布局',exact:true}).click();await expect(page.getByRole('complementary',{name:'Agent 协作面板',exact:true})).toHaveCount(0);await expect(page.getByTestId('canvas-minimap')).toHaveCount(0);await expect(page.getByTestId('node-text-1')).toHaveAttribute('style',before!);await page.reload();await expect(page.getByTestId('canvas-minimap')).toHaveCount(0);await expect(page.getByRole('complementary',{name:'Agent 协作面板',exact:true})).toHaveCount(0);await expect(page.getByTestId('node-text-1')).toHaveAttribute('style',before!);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 P11 batch export has an exact manifest and independently recoverable packages, no source mutation or paid request',async({page,networkCounter})=>{
 await seedStudio(page,'project-library');await page.goto('/projects');await page.getByTestId('project-p1').getByRole('checkbox',{name:'选择项目甲'}).check();await page.getByTestId('project-p2').getByRole('checkbox',{name:'选择项目乙'}).check();await page.getByRole('button',{name:'批量导出所选项目',exact:true}).click();const dialog=page.getByRole('dialog',{name:'批量导出项目包',exact:true});await expect(dialog).toContainText('2 个');await dialog.getByLabel('备份范围').selectOption('structure');const pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'确认导出 2 个项目',exact:true}).click();const download=await pending,entries=unzipSync(new Uint8Array(await readFile((await download.path())!))),manifest=JSON.parse(strFromU8(entries['manifest.json']));expect(manifest.format).toBe('aiwork-studio-project-batch');expect(manifest.projects.map((p:{id:string})=>p.id)).toEqual(['p1','p2']);expect(Object.keys(entries)).toHaveLength(3);await expect(page.getByRole('status').filter({hasText:'已触发浏览器下载'})).toBeVisible();const backups=await page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['receipts'],'readonly',(tx:IDBTransaction)=>m.requestResult(tx.objectStore('receipts').getAll()));}finally{db.close();}});expect(backups.filter((r:{kind:string})=>r.kind==='project-backup-download-triggered').map((r:{projectId:string})=>r.projectId).sort()).toEqual(['p1','p2']);for(const project of manifest.projects){const data=JSON.parse(strFromU8(entries[project.path]));expect(data.project.id).toBe(project.id);expect(data.manifest.mode).toBe('structure');}expect(JSON.stringify(manifest)).not.toMatch(/apiKey|token|authorization/i);expect(networkCounter.paidRequests).toHaveLength(0);
});
