import {test,expect} from '../helpers/network-guard';
import {seedStudio} from '../helpers/seed-studio';
test('T44 global controls: semantic navigation, search, help and notifications have their own interaction identities and no paid side effect',async({page,networkCounter})=>{
 await page.goto('/projects');await expect(page.locator('[data-interaction-id="G-01"]')).toHaveAttribute('href','/projects');await page.locator('[data-interaction-id="G-04"]').fill('不存在的本地项目');await expect(page.locator('.search-results')).toContainText('没有匹配内容');await page.getByRole('button',{name:'清除搜索',exact:true}).click();
 await page.locator('[data-interaction-id="G-07"]').click();await expect(page.getByRole('dialog',{name:'当前区域帮助',exact:true})).toContainText('项目保存在当前浏览器');await page.keyboard.press('Escape');await expect(page.locator('[data-interaction-id="G-07"]')).toBeFocused();await page.locator('[data-interaction-id="G-09"]').click();await expect(page.getByRole('dialog',{name:'通知消息',exact:true})).toContainText('提交未知');expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 viewport control identities: disabled history, zoom errors, saved background and actual undo/redo cannot submit',async({page,networkCounter})=>{
 await seedStudio(page,'canvas-project');await page.goto('/projects/p1/canvas');await expect(page.locator('[data-interaction-id="C-13"]')).toBeDisabled();await expect(page.locator('[data-interaction-id="C-14"]')).toBeDisabled();await expect(page.locator('[data-interaction-id="C-07"]')).toBeDisabled();await page.locator('[data-interaction-id="C-05"]').fill('999');await page.locator('[data-interaction-id="C-05"]').press('Enter');await expect(page.getByRole('alert')).toContainText('25%–200%');await page.locator('[data-interaction-id="C-09"]').selectOption('grid');await page.locator('[data-interaction-id="C-08"]').click();await page.locator('[data-interaction-id="C-10"]').click();await page.getByRole('dialog',{name:'添加节点',exact:true}).getByRole('button',{name:'文本节点',exact:true}).click();await expect(page.locator('[data-interaction-id="C-13"]')).toBeEnabled();await page.locator('[data-interaction-id="C-13"]').click();await expect(page.locator('[data-interaction-id="C-14"]')).toBeEnabled();await page.locator('[data-interaction-id="C-14"]').click();await page.reload();await expect(page.locator('[data-interaction-id="C-09"]')).toHaveValue('grid');expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 project controls: selection and view changes preserve scope, details are readonly and failed rename cannot persist',async({page,networkCounter})=>{
 await seedStudio(page,'project-library');await page.goto('/projects');await page.getByTestId('project-p1').locator('[data-interaction-id="P-09"]').check();await page.locator('[data-interaction-id="P-13"]').click();await expect(page.getByTestId('project-p1').locator('[data-interaction-id="P-09"]')).toBeChecked();await page.getByTestId('project-p1').locator('[data-interaction-id="P-14"]').click();await expect(page.getByRole('dialog')).toContainText('项目甲');await page.keyboard.press('Escape');await page.getByTestId('project-p1').locator('[data-interaction-id="P-04"]').click();await page.getByRole('dialog').getByLabel('项目名称').fill('');await page.getByRole('dialog').getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible();await page.keyboard.press('Escape');await page.reload();await expect(page.getByRole('heading',{name:'项目甲',exact:true})).toBeVisible();expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 preference identities: theme, density, autoplay and reduced motion persist and do not create runs',async({page,networkCounter})=>{
 await page.goto('/settings/appearance');await page.locator('[data-interaction-id="S-01"]').selectOption('light');await page.locator('[data-interaction-id="S-02"]').selectOption('compact');await page.locator('[data-interaction-id="S-03"]').check();await page.locator('[data-interaction-id="S-04"]').selectOption('reduced');await page.reload();await expect(page.locator('[data-interaction-id="S-01"]')).toHaveValue('light');await expect(page.locator('[data-interaction-id="S-02"]')).toHaveValue('compact');await expect(page.locator('[data-interaction-id="S-03"]')).toBeChecked();await expect(page.locator('[data-interaction-id="S-04"]')).toHaveValue('reduced');expect(networkCounter.paidRequests).toHaveLength(0);
});
