import {readFile} from 'node:fs/promises';
import {unzipSync,strFromU8} from 'fflate';
import {test,expect} from '../helpers/cloud-workspace-ui-fixture';
test('recovers unexported legacy browser content only after an explicit read and downloads a complete package without uploading',async({page,workspace},testInfo)=>{
 await page.goto('/projects');await expect(page.getByText('还没有项目',{exact:true})).toBeVisible();
 await page.evaluate(async()=>{
  const storagePath='/src/infrastructure/storage/database.ts';const {openStudioDb,transact}=await import(storagePath),db=await openStudioDb();
  const canvas=document.createElement('canvas');canvas.width=canvas.height=2;canvas.getContext('2d')!.fillRect(0,0,2,2);const blob=await new Promise<Blob>(resolve=>canvas.toBlob(value=>resolve(value!),'image/png')),sha256=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))].map(n=>n.toString(16).padStart(2,'0')).join('');
  await transact(db,['projects','graphs','assets','blobs','prompts','receipts','connections'],'readwrite',(tx:IDBTransaction)=>{
   tx.objectStore('projects').put({id:'legacy-project',schemaVersion:1,title:'升级前尚未导出的项目',description:'原始资料',revision:0,createdAt:1,updatedAt:1,archived:false,trashedAt:10,tags:[]});tx.objectStore('graphs').put({projectId:'legacy-project',revision:0,nodes:[{id:'legacy-node',type:'asset',title:'旧原件',x:1,y:2,locked:false,data:{kind:'asset',assetId:'legacy-asset'}}],edges:[],viewport:{x:0,y:0,scale:1}});
   tx.objectStore('assets').put({id:'legacy-asset',sha256,bytes:blob.size,mimeType:'image/png',mediaType:'image',blobKey:'old-original',title:'旧参考图片',createdAt:1});tx.objectStore('blobs').put({id:'old-original',blob});tx.objectStore('blobs').put({id:'thumbnail:'+sha256,blob});tx.objectStore('prompts').put({id:'legacy-prompt',title:'旧独立提示词',body:'必须保留的旧正文',tags:[],variables:[],source:'自有',license:'自有',revision:0,starred:false,trashed:false});tx.objectStore('receipts').put({id:'agent-note:old',kind:'agent-local-note',projectId:'legacy-project',conversationId:'old-conversation',body:'必须保留的旧 Agent 描述',context:{scope:'project',nodeIds:[],revision:0},createdAt:1});tx.objectStore('connections').put({id:'old-connection',apiKey:'NEVER_EXPORT_PRIVATE_KEY'});
  });db.close();localStorage.setItem('aiwork-studio:preferences','{"theme":"light"}');
 });
 const uploads:string[]=[];page.on('request',request=>{if(request.method()==='POST'&&/\/studio-api\/(projects|assets|me\/imports)/.test(request.url()))uploads.push(request.url());});
 await page.getByRole('link',{name:'旧版数据迁移',exact:true}).click();await expect(page.getByText('升级前尚未导出的项目',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'从此浏览器读取旧版内容',exact:true}).click();await page.getByLabel('升级前尚未导出的项目 · 回收站',{exact:true}).check();await page.getByLabel('包含独立提示词、草稿、素材及其历史',{exact:true}).check();await page.getByLabel('包含旧版偏好',{exact:true}).check();
 const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'下载所选旧版迁移包',exact:true}).click();const download=await downloading,path=testInfo.outputPath('legacy-workspace.zip');await download.saveAs(path);const entries=unzipSync(await readFile(path)),data=JSON.parse(strFromU8(entries['workspace.json']));expect(data.format).toBe('aiwork-workspace-migration');expect(data.projects).toHaveLength(1);expect(data.assets[0].thumbnail).toBeDefined();expect(Object.keys(entries)).toHaveLength(3);expect(JSON.stringify(data)).toContain('必须保留的旧 Agent 描述');expect(JSON.stringify(data)).not.toContain('NEVER_EXPORT_PRIVATE_KEY');expect(uploads).toEqual([]);expect(workspace.providerCalls).toHaveLength(0);expect((await workspace.pool.query('SELECT id FROM workspace_projects')).rows).toHaveLength(0);
 await page.getByLabel('选择工作区迁移包',{exact:true}).setInputFiles(path);await page.getByRole('button',{name:'校验迁移包并预览',exact:true}).click();await expect(page.getByText('1 个项目 · 1 个素材 · 2 条内容或历史 · 2 个文件',{exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'确认导入当前账号',exact:true})).toBeDisabled();await page.getByLabel('我确认这些内容属于当前账号，可以导入',{exact:true}).check();await page.getByRole('button',{name:'确认导入当前账号',exact:true}).click();await expect(page.getByRole('button',{name:'已导入当前账号',exact:true})).toBeDisabled();await expect(page.getByRole('status')).toContainText('迁移已保存到当前账号');
 await page.reload();await page.getByRole('button',{name:'查看原始只读历史',exact:true}).click();await expect(page.getByText('必须保留的旧 Agent 描述',{exact:true})).toBeVisible();expect((await workspace.pool.query('SELECT id FROM workspace_projects')).rows).toHaveLength(1);expect(workspace.providerCalls).toHaveLength(0);
});
