import {test,expect} from '../helpers/network-guard';
import type {Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const records=(page:Page)=>page.evaluate(async()=>{const url='/src/infrastructure/storage/database.ts',m=await import(url),db=await m.openStudioDb();try{return await m.transact(db,['projects','graphs','runs','promptRuns','prompts','promptDrafts'],'readonly',async(tx:IDBTransaction)=>Promise.all(['projects','graphs','runs','promptRuns','prompts','promptDrafts'].map(table=>m.requestResult(tx.objectStore(table).getAll()))));}finally{db.close();}});
async function denyNextDownload(page:Page){await page.evaluate(()=>{const original=HTMLAnchorElement.prototype.click;let armed=true;HTMLAnchorElement.prototype.click=function(){if(armed&&this.download){armed=false;throw new DOMException('native-download-denied','NotAllowedError');}return original.call(this);};});}

test('T44 L11 actual browser download failure reports an honest error and keeps every source entry before explicit retry',async({page,networkCounter})=>{
 await page.goto('/prompts');await page.evaluate(async()=>{const p='/tests/fixtures/prompt-library.ts';await (await import(p)).seedPromptLibrary();});await page.reload();await expect(page.getByRole('button',{name:'导出所选提示词',exact:true})).toBeDisabled();await page.getByLabel('选择 品牌模板',{exact:true}).check();const before=await records(page);await denyNextDownload(page);await page.getByRole('button',{name:'导出所选提示词',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('提示词导出未完成；原条目保留，请检查浏览器下载权限后重试。');expect(await records(page)).toEqual(before);
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'导出所选提示词',exact:true}).click();const download=await pending,data=JSON.parse((await readFile((await download.path())!)).toString());expect(data.entries[0].body).toBe(before[4].find((entry:{id:string})=>entry.id==='template').body);expect(data.entries[0].source).toBe('用户提供的测试来源');expect(await records(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 J09 actual browser CSV download refusal does not claim success or alter original execution and billing records',async({page,networkCounter})=>{
 await page.goto('/tasks');await page.evaluate(async()=>{const p='/tests/fixtures/task-history.ts';await (await import(p)).seedTaskHistory();});await page.reload();await expect(page.getByTestId('video-run-1')).toBeVisible();const before=await records(page);await denyNextDownload(page);await page.getByRole('button',{name:'导出脱敏CSV',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'CSV导出未完成；原任务记录保留，请检查浏览器下载权限后重试。'})).toBeVisible();expect(await records(page)).toEqual(before);
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'导出脱敏CSV',exact:true}).click();const download=await pending,csv=(await readFile((await download.path())!)).toString();expect(csv).toContain('video-run-unknown');expect(csv).not.toContain('fake-task-key');expect(await records(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 PG27 current unchecked memory draft export survives browser refusal without saving, credentials or media',async({page,networkCounter})=>{
 await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/prompt-workspace.ts';await (await import(p)).seedPromptWorkspace();});await page.goto('/prompt-generator?type=video&draftId=d1');await expect(page.getByLabel('原始创意',{exact:true})).toHaveValue(/康济健葆/);const before=await records(page);await denyNextDownload(page);await page.getByRole('button',{name:'导出草稿JSON',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('导出失败：浏览器限制或草稿超过16MiB；内容仍保留。');expect(await records(page)).toEqual(before);
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'导出草稿JSON',exact:true}).click();const download=await pending,text=(await readFile((await download.path())!)).toString();const document=JSON.parse(text);expect(document.draft.userRequest).toBe(before[5][0].userRequest);expect(document.validationState).toBe('unvalidated');expect(document.draft.currentBody).toBe('');expect(text).not.toMatch(/apiKey|authorization|idempotencyKey/);await expect(page.getByRole('status').filter({hasText:'此写作草稿未校验'})).toBeVisible();expect(await records(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
