import {test,expect} from '../helpers/network-guard';
import {resolve} from 'node:path';
test.use({launchOptions:{downloadsPath:resolve('E:/trae-studio/tools/temp/playwright-downloads/media')}});
test('T33 actual native video: authenticated blob preview, local cache offline, original-byte download and cleanup; zero paid POST',async({page,networkCounter})=>{
 await page.addInitScript(()=>{const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL),live=new Set<string>();Object.assign(window,{mediaLiveUrls:live});URL.createObjectURL=blob=>{const url=create(blob);live.add(url);return url;};URL.revokeObjectURL=url=>{live.delete(url);revoke(url);};});
 await page.clock.install();
 await page.goto('/tests/fixtures/media-delivery.html');const bytes=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=64;canvas.height=32;const context=canvas.getContext('2d')!;context.fillStyle='#34d399';context.fillRect(0,0,64,32);const stream=canvas.captureStream(10),recorder=new MediaRecorder(stream,{mimeType:'video/webm'}),chunks:Blob[]=[];return await new Promise<number[]>(resolve=>{recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{for(const track of stream.getTracks())track.stop();void new Blob(chunks,{type:'video/webm'}).arrayBuffer().then(buffer=>resolve(Array.from(new Uint8Array(buffer))));};recorder.start();setTimeout(()=>recorder.stop(),350);});});
 await page.route('**/core-api/v1/videos/mock-core-1/content',async route=>{expect(route.request().headers().authorization).toBe('Bearer fake-generation-key');await route.fulfill({status:200,contentType:'video/webm',body:Buffer.from(bytes)});});
 await page.getByRole('button',{name:'获取并缓存结果',exact:true}).click();await expect(page.getByRole('status')).toContainText('已缓存到当前浏览器');const video=page.locator('video');await expect.poll(()=>video.evaluate(e=>(e as HTMLVideoElement).readyState)).toBeGreaterThanOrEqual(2);expect(await video.getAttribute('src')).toMatch(/^blob:/);expect(await video.getAttribute('src')).not.toContain('fake-generation-key');
 await page.getByRole('button',{name:/^播放 视频-/}).click();await expect.poll(()=>video.evaluate(e=>(e as HTMLVideoElement).paused)).toBe(false);await page.screenshot({path:'docs/review/screenshots/T33-local-video.png'});
 await page.evaluate(async()=>{const path='/src/adapters/core/current-connection.ts';(await import(path)).clearActiveCore();});const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'下载结果',exact:true}).click();const download=await downloading,stream=await download.createReadStream();if(!stream)throw Error('download stream unavailable');const chunks:Buffer[]=[];for await(const chunk of stream)chunks.push(Buffer.from(chunk));expect(Array.from(Buffer.concat(chunks))).toEqual(bytes);await expect(page.getByRole('status')).toContainText('已触发浏览器下载');await expect(page.getByText('已保存到下载目录',{exact:true})).toHaveCount(0);expect(networkCounter.requests.filter(r=>r.url.endsWith('/content'))).toHaveLength(1);expect(networkCounter.requests.filter(r=>r.method==='POST')).toHaveLength(0);
 await page.clock.fastForward(60001);await page.evaluate(async()=>{const path='/tests/fixtures/media-delivery.tsx';(await import(path)).unmountMediaFixture();});await expect.poll(()=>page.evaluate(()=>Reflect.get(window,'mediaLiveUrls').size)).toBe(0);
});
test('T33 actual transport: redirected media is blocked without any generation change or remote redirect request',async({page,networkCounter})=>{await page.goto('/tests/fixtures/media-delivery.html');await page.route('**/core-api/v1/videos/mock-core-1/content',route=>route.fulfill({status:302,headers:{Location:'https://untrusted.invalid/video'}}));await page.getByRole('button',{name:'获取并缓存结果',exact:true}).click();await expect(page.getByRole('status')).toContainText('未核验的下载跳转已阻止');const stored=await page.evaluate(async()=>{const path='/src/infrastructure/storage/run-repository.ts';return(await import(path)).readRun('media-original-run');});expect(stored).toMatchObject({executionState:'succeeded',billingState:'not_provided',deliveryState:'download_failed'});expect(networkCounter.requests.filter(r=>r.method==='POST')).toHaveLength(0);});
