import {test,expect} from '../helpers/network-guard';
test('T49 old client cannot overwrite future project and unknown Run and PromptRun evidence remains identical',async({page,networkCounter})=>{await page.goto('/projects');const result=await page.evaluate(async()=>{const p='/tests/fixtures/release-rehearsal.ts';return(await import(p)).staleOverwrite();});expect(result.result).toEqual({status:'failed',code:'stored_project_not_writable'});expect(result.after).toEqual(result.before);expect(result.after.runs[0]).toMatchObject({taskId:'future-task',billingState:'reconcile_required'});expect(networkCounter.requests.filter(r=>r.method==='POST')).toHaveLength(0);});
test('T49 newer native database rejects old client without upgrading down or losing unknown histories',async({page,networkCounter})=>{await page.goto('/projects');const result=await page.evaluate(async()=>{const p='/tests/fixtures/release-rehearsal.ts';return(await import(p)).upgradeAndRejectOldDatabase();});expect(result).toMatchObject({error:'db_schema_too_new',version:3,run:{executionState:'future_pending',billingState:'reconcile_required'},prompt:{executionState:'future_response_unknown'}});expect(networkCounter.requests.filter(r=>r.method==='POST')).toHaveLength(0);});
test('T49 pre-upgrade backup recovers into new project while newer charging evidence remains in original database and no task replays',async({page,networkCounter})=>{
 await page.goto('/projects');const result=await page.evaluate(async()=>{
  const fixture='/tests/fixtures/result-review.ts';await(await import(fixture)).seedResultReview();
  const database='/src/infrastructure/storage/database.ts',exports='/src/infrastructure/packages/export-project.ts',imports='/src/infrastructure/packages/import-project.ts';const m=await import(database),e=await import(exports),i=await import(imports);
  const backup=await e.exportProject('p1',{mode:'full'}),db=await m.openStudioDb();try{await m.transact(db,['runs','promptRuns'],'readwrite',(tx:IDBTransaction)=>{tx.objectStore('runs').put({id:'new-fee-after-backup',projectId:'p1',taskId:'new-task-after-backup',executionState:'future_unknown',billingState:'reconcile_required'});tx.objectStore('promptRuns').put({id:'new-text-after-backup',draftId:'original-draft',executionState:'future_unknown',billingState:'reconcile_required'});});const before=await m.transact(db,['runs','promptRuns'],'readonly',async(tx:IDBTransaction)=>({runs:await m.requestResult(tx.objectStore('runs').getAll()),prompts:await m.requestResult(tx.objectStore('promptRuns').getAll())}));const inspection=await i.inspectImport(backup.blob);if(!inspection.ok)throw Error(inspection.errorCode);const restored=await i.commitImport(inspection.plan,{db});const after=await m.transact(db,['runs','promptRuns','blobs','projects','receipts'],'readonly',async(tx:IDBTransaction)=>({runs:await m.requestResult(tx.objectStore('runs').getAll()),prompts:await m.requestResult(tx.objectStore('promptRuns').getAll()),projects:await m.requestResult(tx.objectStore('projects').count()),blobs:await m.requestResult(tx.objectStore('blobs').count()),receipts:await m.requestResult(tx.objectStore('receipts').getAll())}));return {before,after,restoredId:restored.id};}finally{db.close();}
 });expect(result.restoredId).not.toBe('p1');expect(result.after.runs).toEqual(result.before.runs);expect(result.after.prompts).toEqual(result.before.prompts);expect(result.after.projects).toBe(2);expect(result.after.blobs).toBeGreaterThanOrEqual(2);expect(result.after.receipts).toEqual(expect.arrayContaining([expect.objectContaining({kind:'readonly-import-history'})]));expect(networkCounter.requests.filter(r=>r.method==='POST')).toHaveLength(0);
});
test('T49 corrupt and future packages retain original byte-for-byte and never change native data',async({page,networkCounter})=>{
 await page.goto('/projects');const result=await page.evaluate(async()=>{const fp='/tests/fixtures/release-rehearsal.ts',ip='/src/infrastructure/packages/import-project.ts';const f=await import(fp),i=await import(ip);await f.prepareFutureProject();const before=await f.snapshot();const bad=new Blob(['{"bad":']);const future=new Blob([JSON.stringify({manifest:{format:'aiwork-studio-project',schemaVersion:2,mode:'structure',createdAt:1,assets:[]},project:{},graph:{},runs:[],drafts:[]})]);const a=await i.inspectImport(bad),b=await i.inspectImport(future);return {a:{ok:a.ok,error:a.errorCode,original:a.original===bad,text:await a.original.text()},b:{ok:b.ok,error:b.errorCode,readonly:b.readonly,original:b.original===future,text:await b.original.text()},before,after:await f.snapshot(),future:await future.text()};});expect(result.a).toEqual({ok:false,error:'import_unsafe',original:true,text:'{"bad":'});expect(result.b).toEqual({ok:false,error:'schema_too_new',readonly:true,original:true,text:result.future});expect(result.after).toEqual(result.before);expect(networkCounter.requests.filter(r=>r.method==='POST')).toHaveLength(0);
});
