import {test,expect} from '../helpers/network-guard';
import type {Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(async()=>{const p='/tests/fixtures/asset-library.ts';return (await import(p)).storedAssets();});
test.beforeEach(async({page})=>{await page.goto('/assets');await page.evaluate(async()=>{const p='/tests/fixtures/asset-library.ts';await (await import(p)).seedAssetLibrary();const url='/src/infrastructure/storage/database.ts',m=await import(url),db=await m.openStudioDb();try{await m.transact(db,['blobs'],'readwrite',(tx:IDBTransaction)=>tx.objectStore('blobs').put({id:'thumbnail:state-contract',blob:new Blob(['cache-only'])}));}finally{db.close();}});await page.goto('/settings/storage');await expect(page.getByRole('button',{name:'清理可重建缩略图',exact:true})).toBeEnabled();});

test('T44 D01/D02/D06 actual native persistence outcome is held for busy controls and remains truthful after reload',async({page,networkCounter})=>{
 const before=await state(page);await page.evaluate(()=>{const original=navigator.storage.persist.bind(navigator.storage),probe={settled:false,result:undefined as boolean|undefined,release:undefined as undefined|(()=>void)};Reflect.set(window,'nativeStoragePersistenceProbe',probe);Object.defineProperty(navigator.storage,'persist',{configurable:true,value:async()=>{const result=await original();probe.settled=true;probe.result=result;await new Promise<void>(resolve=>{probe.release=resolve;});return result;}});});
 await page.getByRole('button',{name:'请求持久存储',exact:true}).click();await expect.poll(()=>page.evaluate(()=>Reflect.get(window,'nativeStoragePersistenceProbe').settled)).toBe(true);
 for(const name of ['刷新存储统计','请求持久存储','清理可重建缩略图'])await expect(page.getByRole('button',{name,exact:true})).toBeDisabled();
 const nativeResult=await page.evaluate(()=>{const probe=Reflect.get(window,'nativeStoragePersistenceProbe');if(!probe.release)throw Error('native result not settled');probe.release();return probe.result as boolean;});
 await expect(page.getByRole('status').filter({hasText:nativeResult?'浏览器当前批准持久存储；仍需备份。':'浏览器未批准持久存储；可以继续创作，请及时备份。'})).toBeVisible();await expect(page.getByRole('button',{name:'请求持久存储',exact:true})).toBeEnabled();expect(await navigatorState(page)).toBe(nativeResult);expect(await state(page)).toEqual(before);
 await page.reload();await expect(page.getByText('持久存储：'+(nativeResult?'浏览器当前已批准':'当前未批准')+'。统计来源：浏览器估计与本地实际Blob统计。',{exact:true})).toBeVisible();expect(await navigatorState(page)).toBe(nativeResult);expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
const navigatorState=(page:Page)=>page.evaluate(()=>navigator.storage.persisted());

test('T44 D01 actual native summary read failure can explicitly retry without deleting originals or tasks',async({page,networkCounter})=>{
 const before=await state(page);await page.evaluate(()=>{const original=IDBObjectStore.prototype.getAll;let armed=true;IDBObjectStore.prototype.getAll=function(...args:Parameters<typeof original>){if(armed&&this.name==='assets'){armed=false;throw new DOMException('native-summary-read-denied','UnknownError');}return original.apply(this,args);};});
 await page.getByRole('button',{name:'刷新存储统计',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('本地统计读取失败，未清理任何文件。');expect(await state(page)).toEqual(before);await page.getByRole('button',{name:'刷新存储统计',exact:true}).click();await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.getByText(/本地实际原文件 .*缺失原文件 0 项/)).toBeVisible();expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 D06 native cleanup commit failure rolls back removed thumbnail and preserves every source and Run before explicit retry',async({page,networkCounter})=>{
 const before=await state(page),originalKeys=new Set(before.assets.map((row:{blobKey:string})=>row.blobKey)),removable=before.blobs.filter((row:{id:string})=>row.id.startsWith('thumbnail:')&&!originalKeys.has(row.id));await page.getByRole('button',{name:'清理可重建缩略图',exact:true}).click();await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;let armed=true;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(armed&&this.name==='diagnostics'){armed=false;throw new DOMException('native-cleanup-quota','QuotaExceededError');}return original.apply(this,args);};});
 const dialog=page.getByRole('dialog',{name:'清理缩略图缓存',exact:true});await dialog.getByRole('button',{name:'确认清理缩略图',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('清理事务未完成，原文件与任务保留。');await expect(dialog).toBeVisible();expect(await state(page)).toEqual(before);
 await dialog.getByRole('button',{name:'确认清理缩略图',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.getByRole('status').filter({hasText:'已清理 '+removable.length+' 项'})).toBeVisible();const after=await state(page);expect(after.assets).toEqual(before.assets);expect(after.graph).toEqual(before.graph);expect(after.runs).toEqual(before.runs);expect(after.blobs).toEqual(before.blobs.filter((row:{id:string})=>!removable.some((item:{id:string})=>item.id===row.id)));await page.reload();await expect(page.getByRole('button',{name:'清理可重建缩略图',exact:true})).toBeDisabled();expect(await state(page)).toEqual(after);expect(networkCounter.paidRequests).toHaveLength(0);
});
