import {test,expect} from '../helpers/network-guard';
import {holdNextNativeCommit,releaseNativeCommit,nativeCommitProbe} from '../helpers/native-commit-hold';
import type {Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const state=(page:Page)=>page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['projects','graphs','runs','receipts','assets'],'readonly',async(tx:IDBTransaction)=>Object.fromEntries(await Promise.all(['projects','graphs','runs','receipts','assets'].map(async table=>[table,await m.requestResult(tx.objectStore(table).getAll())]))));}finally{db.close();}});
test.beforeEach(async({page})=>{await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/result-review.ts';await (await import(p)).seedResultReview();});});

test('T44 D04/D05/I01/I02 native snapshot failure keeps all creative data and real export stays disabled until actual read acknowledgement',async({page,networkCounter})=>{
 await page.goto('/projects/packages?projectId=p1');await page.getByRole('button',{name:'导出项目包',exact:true}).click();const dialog=page.getByRole('dialog',{name:'导出项目包',exact:true});await dialog.getByLabel('备份范围',{exact:true}).selectOption('structure');const before=await state(page);await page.evaluate(()=>{const original=IDBObjectStore.prototype.getAll;let armed=true;IDBObjectStore.prototype.getAll=function(...args:Parameters<typeof original>){if(armed&&this.name==='graphs'){armed=false;throw new DOMException('native-package-read-denied','UnknownError');}return original.apply(this,args);};});await dialog.getByRole('button',{name:'确认导出',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('操作未完成，原项目保留；请检查文件完整性和本地存储。');expect(await state(page)).toEqual(before);
 await holdNextNativeCommit(page,'graphs','readonly');const pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'确认导出',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});try{await expect(dialog.getByRole('button',{name:'确认导出',exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'取消',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'导出项目包',exact:true})).toBeDisabled();await expect(page.getByLabel('选择项目包',{exact:true})).toBeDisabled();expect(await state(page)).toEqual(before);}finally{await releaseNativeCommit(page);}const download=await pending,document=JSON.parse((await readFile((await download.path())!)).toString());expect(document.manifest.mode).toBe('structure');expect(document.project.id).toBe('p1');await expect(page.getByRole('status').filter({hasText:'已触发浏览器下载'})).toBeVisible();const after=await state(page);for(const table of ['projects','graphs','runs','assets'])expect(after[table]).toEqual(before[table]);expect(after.receipts.filter((r:{kind:string})=>r.kind==='project-backup-download-triggered')).toHaveLength(1);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 I06/I07 native import quota rolls back every partial project and the real retry freezes cancel until acknowledgement',async({page,networkCounter})=>{
 const bytes=await page.evaluate(async()=>{const p='/src/infrastructure/packages/export-project.ts';return (await (await import(p)).exportProject('p1',{mode:'structure'})).blob.text();});await page.goto('/projects/packages');await page.getByLabel('选择项目包',{exact:true}).setInputFiles({name:'structure.json',mimeType:'application/json',buffer:Buffer.from(bytes)});const dialog=page.getByRole('dialog',{name:'检查项目包',exact:true});await expect(dialog).toContainText('仅结构包');const before=await state(page);await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;let armed=true;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(armed&&this.name==='projects'){armed=false;throw new DOMException('native-package-import-quota','QuotaExceededError');}return original.apply(this,args);};});await dialog.getByRole('button',{name:'导入新项目',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('操作未完成，原项目保留；请检查文件完整性和本地存储。');expect(await state(page)).toEqual(before);
 await holdNextNativeCommit(page,'projects');await dialog.getByRole('button',{name:'导入新项目',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});try{await expect(dialog.getByRole('button',{name:'导入新项目',exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'取消',exact:true})).toBeDisabled();await expect(page.getByLabel('选择项目包',{exact:true})).toBeDisabled();const during=await state(page);expect(during.projects).toHaveLength(before.projects.length+1);expect(during.projects.find((p:{id:string})=>p.id==='p1')).toEqual(before.projects[0]);expect(during.runs).toEqual(before.runs);}finally{await releaseNativeCommit(page);}await expect(page.getByRole('status').filter({hasText:'已导入新项目'})).toBeVisible();await expect(dialog).toHaveCount(0);const after=await state(page);expect(after.projects).toHaveLength(2);expect(after.runs).toEqual(before.runs);expect(after.receipts.filter((r:{kind:string})=>r.kind==='readonly-import-history')).toHaveLength(1);expect(networkCounter.paidRequests).toHaveLength(0);
});
