import {test,expect} from '../helpers/network-guard';
import type {Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['projects','graphs','runs','receipts'],'readonly',async(tx:IDBTransaction)=>Object.fromEntries(await Promise.all(['projects','graphs','runs','receipts'].map(async table=>[table,await m.requestResult(tx.objectStore(table).getAll())]))));}finally{db.close();}});
async function denyWrite(page:Page){await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;let armed=true;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(armed&&this.name==='projects'){armed=false;throw new DOMException('native-project-quota','QuotaExceededError');}return original.apply(this,args);};});}
test.beforeEach(async({page})=>{await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/result-review.ts';await (await import(p)).seedResultReview();});await page.reload();});

test('T44 P02/P05 native template and clone quota preserve original graph and history; explicit template retry persists a new draft only',async({page,networkCounter})=>{
 const before=await state(page);await page.getByRole('button',{name:'复制项目',exact:true}).click();const clone=page.getByRole('dialog',{name:'复制项目',exact:true});await denyWrite(page);await clone.getByRole('button',{name:'创建副本',exact:true}).click();await expect(clone.getByRole('alert')).toBeVisible();expect(await state(page)).toEqual(before);await clone.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('button',{name:'使用本地模板',exact:true}).click();const template=page.getByRole('dialog',{name:'使用本地模板',exact:true});await denyWrite(page);await template.getByRole('button',{name:'创建原创分镜草稿',exact:true}).click();await expect(template.getByRole('alert')).toBeVisible();expect(await state(page)).toEqual(before);await template.getByRole('button',{name:'创建原创分镜草稿',exact:true}).click();await expect(page).toHaveURL(/\/projects\/[^/]+\/canvas$/);await page.reload();await expect(page.getByRole('heading',{name:'原创分镜草稿',exact:true})).toBeVisible();const after=await state(page);expect(after.projects).toHaveLength(2);expect(after.graphs.find((g:{projectId:string})=>g.projectId==='p1')).toEqual(before.graphs[0]);expect(after.graphs.find((g:{projectId:string})=>g.projectId!=='p1').nodes.every((n:{type:string})=>n.type==='text')).toBe(true);expect(after.runs).toEqual(before.runs);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 P08 native soft-deletion quota retains original project and ongoing task identities without cancellation or refund',async({page,networkCounter})=>{
 const before=await state(page);await page.getByRole('button',{name:'移入回收站',exact:true}).click();const dialog=page.getByRole('dialog',{name:'移入项目回收站',exact:true});await expect(dialog).toBeVisible();await denyWrite(page);await dialog.getByRole('button',{name:'移入回收站',exact:true}).click();await expect(dialog.getByRole('alert')).toBeVisible();expect(await state(page)).toEqual(before);await dialog.getByRole('button',{name:'返回',exact:true}).click();await page.reload();expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);expect(networkCounter.requests.filter(r=>/cancel|refund/.test(r.url))).toHaveLength(0);
});

test('T44 P11 actual batch export snapshot failure generates no empty success package and keeps the original selected project and frozen tasks',async({page,networkCounter})=>{
 const before=await state(page);await page.getByRole('checkbox').first().check();await page.getByRole('button',{name:'批量导出所选项目',exact:true}).click();const dialog=page.getByRole('dialog',{name:'批量导出项目包',exact:true});await expect(dialog).toContainText('1 个项目');await dialog.getByLabel('备份范围',{exact:true}).selectOption('structure');const downloads:string[]=[];page.on('download',d=>downloads.push(d.suggestedFilename()));await page.evaluate(()=>{const original=IDBObjectStore.prototype.getAll;let armed=true;IDBObjectStore.prototype.getAll=function(...args:Parameters<typeof original>){if(armed&&this.name==='graphs'){armed=false;throw new DOMException('native-batch-backup-read','UnknownError');}return original.apply(this,args);};});await dialog.getByRole('button',{name:'确认导出 1 个项目',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('操作未完成，原项目保留；请检查文件完整性和本地存储。');await expect(dialog).toBeVisible();expect(downloads).toHaveLength(0);expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
