import {test,expect} from '../helpers/network-guard';
import {seedStudio} from '../helpers/seed-studio';
import type {Page} from '@playwright/test';
const records=(page:Page)=>page.evaluate(async()=>{const url='/src/infrastructure/storage/database.ts',m=await import(url),db=await m.openStudioDb();try{return await m.transact(db,['projects','graphs','runs'],'readonly',async(tx:IDBTransaction)=>({projects:await m.requestResult(tx.objectStore('projects').getAll()),graphs:await m.requestResult(tx.objectStore('graphs').getAll()),runs:await m.requestResult(tx.objectStore('runs').getAll())}));}finally{db.close();}});
test.beforeEach(async({page})=>{await seedStudio(page,'project-library');await page.goto('/projects');});
test('T44 P03 opening an existing project preserves its creative revision, shared media and original unknown Run',async({page,networkCounter})=>{
 const before=await records(page);await page.getByTestId('project-p1').getByRole('link',{name:'项目甲',exact:true}).click();await expect(page).toHaveURL(/projects\/p1\/canvas$/);await expect(page.getByTestId('node-asset-p1')).toBeVisible();const after=await records(page);expect(after.graphs).toEqual(before.graphs);expect(after.runs).toEqual(before.runs);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 P06/P07 favorite and archive toggle independently, survive reload and leave creative graphs and original tracking intact',async({page,networkCounter})=>{
 const before=await records(page),card=page.getByTestId('project-p1');await card.getByRole('button',{name:'收藏',exact:true}).click();await expect(card.getByRole('button',{name:'取消收藏',exact:true})).toHaveAttribute('aria-pressed','true');await card.getByRole('button',{name:'归档',exact:true}).click();await expect(card.getByRole('button',{name:'取消归档',exact:true})).toBeVisible();await page.reload();await expect(card.getByRole('button',{name:'取消收藏',exact:true})).toHaveAttribute('aria-pressed','true');await expect(card.getByRole('button',{name:'取消归档',exact:true})).toBeVisible();let saved=await records(page);expect(saved.projects.find((p:{id:string})=>p.id==='p1')).toMatchObject({starred:true,archived:true});for(const original of before.graphs){const current=saved.graphs.find((g:{projectId:string})=>g.projectId===original.projectId);expect(current).toEqual({...original,revision:original.revision+(original.projectId==='p1'?2:0)});}expect(saved.runs).toEqual(before.runs);await card.getByRole('button',{name:'取消收藏',exact:true}).click();await card.getByRole('button',{name:'取消归档',exact:true}).click();await page.reload();saved=await records(page);expect(saved.projects.find((p:{id:string})=>p.id==='p1')).toMatchObject({starred:false,archived:false});expect(networkCounter.paidRequests).toHaveLength(0);
});
for(const action of [{id:'P-06',name:'收藏'},{id:'P-07',name:'归档'}])test('T44 '+action.id+' native project write failure retains the prior state and reports an error without changing Run',async({page,networkCounter})=>{
 const before=await records(page);await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(this.name==='projects')throw new DOMException('test-project-actions-quota','QuotaExceededError');return original.apply(this,args);};});await page.getByTestId('project-p1').getByRole('button',{name:action.name,exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();expect(await records(page)).toEqual(before);await expect(page.getByTestId('project-p1').getByRole('button',{name:action.name,exact:true})).toBeEnabled();expect(networkCounter.paidRequests).toHaveLength(0);
});
