import {test,expect} from '../helpers/network-guard';import type {Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['promptDrafts','prompts','promptRuns','runs'],'readonly',async(tx:IDBTransaction)=>({drafts:await m.requestResult(tx.objectStore('promptDrafts').getAll()),prompts:await m.requestResult(tx.objectStore('prompts').getAll()),promptRuns:await m.requestResult(tx.objectStore('promptRuns').getAll()),runs:await m.requestResult(tx.objectStore('runs').getAll())}));}finally{db.close();}});
test.beforeEach(async({page})=>{await page.goto('/prompt-generator');await page.evaluate(async()=>{const p='/tests/fixtures/prompt-workspace.ts';await(await import(p)).seedPromptWorkspace();});await page.goto('/prompt-generator?type=video&draftId=d1');});
test('T44 PG23/PG24 result tabs are local views; PG25 copies only the final body and PG26 saves an independent library entry without execution',async({page,networkCounter})=>{
 await expect(page.getByRole('button',{name:'复制正文',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'保存到库',exact:true})).toBeDisabled();await page.getByRole('button',{name:'本地整理',exact:true}).click();const before=await state(page),body=await page.getByLabel('最终提示词正文',{exact:true}).inputValue();await page.getByRole('tab',{name:'镜头草案',exact:true}).click();await expect(page.getByRole('tab',{name:'镜头草案',exact:true})).toHaveAttribute('aria-selected','true');await page.getByRole('tab',{name:'改动说明',exact:true}).click();await expect(page.getByRole('tab',{name:'改动说明',exact:true})).toHaveAttribute('aria-selected','true');expect(await state(page)).toEqual(before);await page.getByRole('tab',{name:'最终提示词',exact:true}).click();await page.evaluate(()=>Object.defineProperty(navigator.clipboard,'writeText',{value:async(text:string)=>{document.documentElement.dataset.testPromptCopy=text;},configurable:true}));await page.getByRole('button',{name:'复制正文',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'已复制最终提示词正文'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.dataset.testPromptCopy)).toBe(body);await page.getByRole('button',{name:'保存到库',exact:true}).click();const dialog=page.getByRole('dialog',{name:'编辑提示词',exact:true});await expect(dialog.getByLabel('提示词正文',{exact:true})).toHaveValue(body);await dialog.getByLabel('提示词名称',{exact:true}).fill('原创正文副本');await dialog.getByRole('button',{name:'保存提示词',exact:true}).click();await expect(dialog).not.toBeVisible();const after=await state(page);expect(after.prompts).toHaveLength(1);expect(after.prompts[0]).toMatchObject({title:'原创正文副本',body});expect(after.drafts).toEqual(before.drafts);expect(after.runs).toEqual([]);expect(after.promptRuns).toEqual([]);await page.reload();expect((await state(page)).prompts[0].body).toBe(body);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 PG25 clipboard denial leaves the original final body and stored result untouched',async({page,networkCounter})=>{
 await page.getByRole('button',{name:'本地整理',exact:true}).click();const before=await state(page),body=await page.getByLabel('最终提示词正文',{exact:true}).inputValue();await page.evaluate(()=>Object.defineProperty(navigator.clipboard,'writeText',{value:async()=>{throw new DOMException('test-prompt-copy-denied','NotAllowedError');},configurable:true}));await page.getByRole('button',{name:'复制正文',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'剪贴板权限被拒绝'})).toBeVisible();await expect(page.getByLabel('最终提示词正文',{exact:true})).toHaveValue(body);expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 PG26 native library quota failure retains its editor and source result with no partial prompt or request',async({page,networkCounter})=>{
 await page.getByRole('button',{name:'本地整理',exact:true}).click();const before=await state(page);await page.getByRole('button',{name:'保存到库',exact:true}).click();const dialog=page.getByRole('dialog',{name:'编辑提示词',exact:true});await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof put>){if(this.name==='prompts')throw new DOMException('test-library-quota','QuotaExceededError');return put.apply(this,args);};});await dialog.getByRole('button',{name:'保存提示词',exact:true}).click();await expect(dialog.getByRole('alert')).toBeVisible();await expect(dialog).toBeVisible();expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 PG16 connection navigation saves current input first and never sends a test chat',async({page,networkCounter})=>{
 await page.getByLabel('原始创意',{exact:true}).fill('转到连接前必须保存的原创输入');await page.getByRole('button',{name:'连接与只读测试',exact:true}).click();await expect(page).toHaveURL(/settings\/connections$/);expect((await state(page)).drafts[0].userRequest).toBe('转到连接前必须保存的原创输入');expect(networkCounter.paidRequests).toHaveLength(0);expect(networkCounter.requests.filter(r=>r.method==='POST')).toHaveLength(0);
});
test('T44 PG16 native draft failure prevents connection navigation and keeps the unsaved input visible',async({page,networkCounter})=>{
 const before=await state(page);await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof put>){if(this.name==='promptDrafts')throw new DOMException('test-connection-navigation-quota','QuotaExceededError');return put.apply(this,args);};});await page.getByLabel('原始创意',{exact:true}).fill('不能遗失的当前输入');await page.getByRole('button',{name:'连接与只读测试',exact:true}).click();await expect(page.getByRole('alert')).toContainText('保存失败');await expect(page).toHaveURL(/prompt-generator/);await expect(page.getByLabel('原始创意',{exact:true})).toHaveValue('不能遗失的当前输入');expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
