import {test,expect} from '../helpers/network-guard';
import type {Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['projects','graphs','promptDrafts','promptRuns','runs'],'readonly',async(tx:IDBTransaction)=>Promise.all(['projects','graphs','promptDrafts','promptRuns','runs'].map(table=>m.requestResult(tx.objectStore(table).getAll()))));}finally{db.close();}});
async function denyNextRead(page:Page,table:string,method:'get'|'getAll'='getAll'){await page.evaluate(({table,method})=>{const original=IDBObjectStore.prototype[method];let armed=true;IDBObjectStore.prototype[method]=function(...args:Parameters<typeof original>){if(armed&&this.name===table){armed=false;throw new DOMException('native-prompt-read-denied','UnknownError');}return Reflect.apply(original,this,args);};},{table,method});}

test('T44 PG01/PG02/T06 actual native draft discovery failure preserves graph and rejects opening rather than creating a fee',async({page,networkCounter})=>{
 await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/generation.ts';await (await import(p)).seedGeneration();(await import(p)).connectGeneration();const r='/src/app/routes.tsx';(await import(r)).navigate('/projects/p1/canvas');});const node=page.getByTestId('node-text-1');await expect(node.getByRole('button',{name:'AI润色',exact:true})).toBeEnabled();const before=await state(page);
 for(const target of [page.locator('[data-interaction-id="PG01"]'),node.getByRole('button',{name:'提示词生成',exact:true}),node.getByRole('button',{name:'AI润色',exact:true})]){await denyNextRead(page,'promptDrafts');await target.click();await expect(page.getByRole('alert')).toHaveText('提示词草稿准备失败；请检查来源保存状态。');await expect(page.getByRole('complementary',{name:'提示词生成面板',exact:true})).toHaveCount(0);expect(await state(page)).toEqual(before);}
 expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 PG03 actual native existing draft read failure in type navigation retains both draft kinds and exposes no execution',async({page,networkCounter})=>{
 await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/prompt-workspace.ts';await (await import(p)).seedPromptWorkspace();});await page.goto('/prompt-generator?type=video&draftId=d1');await expect(page.getByLabel('原始创意',{exact:true})).toHaveValue(/康济健葆/);const before=await state(page);await denyNextRead(page,'promptDrafts','get');await page.getByRole('button',{name:'视频提示词',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('草稿读取或来源修订检查失败，请返回项目核对。');expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 PG06/PG07/PG09 native reference read and role or removal saves fail without changing original references or Runs',async({page,networkCounter})=>{
 await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/prompt-workspace.ts';await (await import(p)).seedPromptWorkspace();const a='/tests/fixtures/asset-library.ts',i='/src/features/assets/import-service.ts';const report=await (await import(i)).importAssets([await (await import(a)).imageFile()]);if(report.failures.length)throw Error('native-image-import-failed');});await page.goto('/prompt-generator?type=video&draftId=d1');await expect(page.getByLabel('原始创意',{exact:true})).toHaveValue(/康济健葆/);await page.getByText('本地参考素材与用途',{exact:true}).click();const before=await state(page);await denyNextRead(page,'assets');await page.getByRole('button',{name:'选择本地素材',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('素材库读取失败；已有引用保持不变。');expect(await state(page)).toEqual(before);
 await page.getByRole('button',{name:'选择本地素材',exact:true}).click();await page.getByRole('checkbox',{name:'参考.png',exact:true}).check();await page.getByRole('button',{name:'保存草稿',exact:true}).click();const saved=await state(page);expect(saved[2][0].references).toHaveLength(1);
 await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(this.name==='promptDrafts')throw new DOMException('native-reference-save-quota','QuotaExceededError');return original.apply(this,args);};});await page.locator('[data-interaction-id="PG07"]').fill('待保存的明确人物用途');await page.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(page.getByRole('alert')).toContainText('保存失败');expect(await state(page)).toEqual(saved);
 await page.getByRole('button',{name:/^移除引用 /}).click();await page.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(page.getByRole('alert')).toContainText('保存失败');expect(await state(page)).toEqual(saved);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 PG31 actual native history snapshot read and restoration commit failures preserve both saved versions and current input',async({page,networkCounter})=>{
 await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/prompt-workspace.ts';await (await import(p)).seedPromptWorkspace();});await page.goto('/prompt-generator?type=video&draftId=d1');await page.getByRole('button',{name:'本地整理',exact:true}).click();await expect(page.getByText('规则整理草稿',{exact:true})).toBeVisible();const before=await state(page);await page.getByRole('button',{name:'查看历史',exact:true}).click();const dialog=page.getByRole('dialog',{name:'提示词结果历史',exact:true});await denyNextRead(page,'receipts','get');await dialog.getByRole('button',{name:'查看输入快照',exact:true}).click();await expect(dialog.getByRole('alert')).toHaveText('历史输入快照读取失败；原记录保留。');expect(await state(page)).toEqual(before);
 await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(this.name==='promptDrafts')throw new DOMException('native-history-restore-quota','QuotaExceededError');return original.apply(this,args);};});await dialog.getByRole('button',{name:'恢复结果',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'恢复失败，原历史与当前输入保留。'})).toBeVisible();await expect(dialog).toBeVisible();expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 PG17/PG18 native pre-dispatch PromptRun quota produces zero HTTP calls and preserves original writing draft',async({page,networkCounter})=>{
 await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/prompt-workspace.ts';await (await import(p)).seedPromptWorkspace();});await page.goto('/prompt-generator?type=video&draftId=d1');await expect(page.getByLabel('原始创意',{exact:true})).toHaveValue(/康济健葆/);await page.evaluate(async()=>{const p='/tests/fixtures/generation.ts';(await import(p)).connectGeneration();});const before=await state(page);
 await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(this.name==='promptRuns')throw new DOMException('native-presend-prompt-quota','QuotaExceededError');return original.apply(this,args);};});await page.getByRole('button',{name:'AI优化',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('文字请求或结果保存尚未完成，原请求记录保留；请核对原记录，不自动重复调用。');await expect(page.locator('[data-interaction-id="PG18"]')).toContainText('原请求待核对');expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);expect(networkCounter.evidence.coreWrites).toBe(0);
});
