import {test,expect} from '../helpers/network-guard';
test.beforeEach(async({page})=>{await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/prompt-workspace.ts';await(await import(p)).seedPromptWorkspace();});await page.goto('/prompt-generator?type=video&draftId=d1');await expect(page.getByLabel('原始创意',{exact:true})).toHaveValue(/康济健葆/);await page.evaluate(async()=>{const p='/tests/fixtures/generation.ts';const g=await import(p),connection=g.connectGeneration(),t='/src/adapters/core/current-connection.ts';const caps={...g.generationCaps,videoModels:[],videoSpecs:[]};(await import(t)).setActiveCore(connection.client,caps);const d='/src/infrastructure/storage/database.ts',db=await import(d);await db.withDatabase(undefined,(connection:import('../../src/infrastructure/storage/database').StudioDb)=>db.transact(connection,['diagnostics'],'readwrite',(tx:IDBTransaction)=>tx.objectStore('diagnostics').put({id:'capability:current',capability:caps}))); });});
const optimized='康济健葆，1位人物，一镜到底，保持品牌原文的优化正文';
test('PG17 native retry-intent quota failure leaves the earlier unknown identity untouched and sends no extra request',async({page,networkCounter})=>{
 await page.route('**/core-api/v1/chat/completions',route=>route.fulfill({status:500,contentType:'application/json',body:'{"error":{"message":"isolated failure"}}'}));await page.getByRole('button',{name:'AI优化',exact:true}).click();await expect(page.locator('[data-interaction-id="PG18"]')).toContainText('响应未知');
 const before=await page.evaluate(async()=>{const p='/tests/fixtures/prompt-workspace.ts';return(await import(p)).promptWorkspaceState();});await page.getByRole('button',{name:'AI优化',exact:true}).click();const dialog=page.getByRole('dialog',{name:'核对旧文字请求',exact:true});await dialog.getByLabel('我已核对旧请求，仍确认创建新的文字请求',{exact:true}).check();await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof put>){if(this.name==='promptRuns')throw new DOMException('retry-intent-quota','QuotaExceededError');return put.apply(this,args);};});await dialog.getByRole('button',{name:'确认新的文字请求',exact:true}).click();await expect(page.getByRole('alert')).toContainText('文字请求或结果保存尚未完成');const after=await page.evaluate(async()=>{const p='/tests/fixtures/prompt-workspace.ts';return(await import(p)).promptWorkspaceState();});expect(after).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(1);await expect(page.getByLabel('原始创意',{exact:true})).toHaveValue(before.drafts[0].userRequest);
});
test('PG17/PGD02 only unresolved earlier requests require risk acknowledgement; an explicitly confirmed new request preserves both identities',async({page,networkCounter})=>{
 let calls=0;await page.route('**/core-api/v1/chat/completions',route=>{calls++;return route.fulfill({status:calls===1?500:200,contentType:'application/json',body:JSON.stringify(calls===1?{error:{message:'isolated unknown response'}}:{choices:[{message:{content:JSON.stringify({finalPrompt:optimized,shotPlan:[],improvements:[],warnings:[],suggestedSpec:{durationSeconds:5,ratio:'9:16'}})}}]})});});
 await page.getByRole('button',{name:'AI优化',exact:true}).click();await expect(page.locator('[data-interaction-id="PG18"]')).toContainText('响应未知');
 await page.getByRole('button',{name:'AI优化',exact:true}).click();const dialog=page.getByRole('dialog',{name:'核对旧文字请求',exact:true});await expect(dialog).toHaveAttribute('data-dialog-id','PGD02');await expect(dialog.getByRole('combobox')).toHaveCount(0);const send=dialog.getByRole('button',{name:'确认新的文字请求',exact:true});await expect(send).toBeDisabled();expect(networkCounter.paidRequests).toHaveLength(1);
 await dialog.getByLabel('我已核对旧请求，仍确认创建新的文字请求',{exact:true}).check();await expect(send).toBeEnabled();await send.click();await expect(dialog).toHaveCount(0);await expect(page.getByLabel('最终提示词正文',{exact:true})).toHaveValue(optimized);expect(networkCounter.paidRequests).toHaveLength(2);
 const state=await page.evaluate(async()=>{const p='/tests/fixtures/prompt-workspace.ts';return(await import(p)).promptWorkspaceState();});expect(state.promptRuns).toHaveLength(2);expect(state.promptRuns.map((run:{executionState:string})=>run.executionState).sort()).toEqual(['response_unknown','succeeded']);expect(new Set(state.promptRuns.map((run:{idempotencyKey:string})=>run.idempotencyKey)).size).toBe(2);expect(state.runs).toHaveLength(0);await page.reload();await expect(page.getByLabel('最终提示词正文',{exact:true})).toHaveValue(optimized);expect(networkCounter.paidRequests).toHaveLength(2);
});
test('one click uses the configured text model, fills and persists正文 without video capability or a confirmation modal',async({page,networkCounter})=>{await page.route('**/core-api/v1/chat/completions',route=>{expect(route.request().postDataJSON().model).toBe('fake-text-only');return route.fulfill({contentType:'application/json',body:JSON.stringify({id:'mock-one-click',choices:[{message:{content:JSON.stringify({finalPrompt:optimized,shotPlan:[],improvements:[],warnings:[],suggestedSpec:{durationSeconds:5,ratio:'9:16'}})}}]})});});await page.getByRole('button',{name:'AI优化',exact:true}).click();await expect(page.getByLabel('最终提示词正文',{exact:true})).toHaveValue(optimized);await expect(page.getByRole('dialog',{name:'AI文字优化确认',exact:true})).toHaveCount(0);expect(networkCounter.paidRequests).toHaveLength(1);expect(networkCounter.paidRequests[0].url).toContain('/chat/completions');await page.reload();await expect(page.getByLabel('最终提示词正文',{exact:true})).toHaveValue(optimized);expect(networkCounter.paidRequests).toHaveLength(1);});
test('late response never overwrites a newer manual正文 and double click sends only one request',async({page,networkCounter})=>{let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});await page.route('**/core-api/v1/chat/completions',async route=>{await gate;await route.fulfill({contentType:'application/json',body:JSON.stringify({choices:[{message:{content:JSON.stringify({finalPrompt:optimized,shotPlan:[],improvements:[],warnings:[],suggestedSpec:{durationSeconds:5,ratio:'9:16'}})}}]})});});await page.getByRole('button',{name:'AI优化',exact:true}).dblclick();await expect.poll(()=>networkCounter.paidRequests.length).toBe(1);await page.getByLabel('最终提示词正文',{exact:true}).fill('我正在写的新正文');release();await expect(page.getByRole('region',{name:'AI结果差异'})).toContainText(optimized);await expect(page.getByLabel('最终提示词正文',{exact:true})).toHaveValue('我正在写的新正文');expect(networkCounter.paidRequests).toHaveLength(1);});
