import {test,expect} from '../helpers/network-guard';
import type {Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(async()=>{const url='/tests/fixtures/prompt-workspace.ts';return(await import(url)).promptWorkspaceState();});
test.beforeEach(async({page})=>{await page.goto('/prompt-generator');await page.evaluate(async()=>{const url='/tests/fixtures/prompt-workspace.ts';await(await import(url)).seedPromptWorkspace();});await page.goto('/prompt-generator?type=video&draftId=d1');});
test('T44 PG04/PG05/PG10/PG11/PG12 explicit writing fields persist together without changing the original source or calling a model',async({page,networkCounter})=>{
 await page.getByLabel('原始创意',{exact:true}).fill('原创品牌，5秒，9:16');await page.getByLabel('创作方向',{exact:true}).selectOption({index:1});const scene=await page.getByLabel('创作方向',{exact:true}).inputValue();await page.getByLabel('时长目标（秒）',{exact:true}).fill('8');await page.getByLabel('画幅目标',{exact:true}).fill('16:9');await page.getByRole('textbox',{name:'声音策略',exact:true}).fill('只写环境声，不上传音频');await page.getByRole('textbox',{name:'品牌原文',exact:true}).fill('原创品牌');await page.getByRole('textbox',{name:'人物数量',exact:true}).fill('2');await page.getByRole('textbox',{name:'对白原文',exact:true}).fill('大家好');await page.getByRole('textbox',{name:'动作禁止项',exact:true}).fill('不切镜');await page.getByRole('button',{name:'保存草稿',exact:true}).click();const saved=(await state(page)).drafts[0];expect(saved).toMatchObject({userRequest:'原创品牌，5秒，9:16',sceneId:scene,requestedSpec:{durationSeconds:8,ratio:'16:9'},audioPlan:'只写环境声，不上传音频'});expect(saved.lockedConstraints).toEqual(expect.arrayContaining([expect.objectContaining({field:'brand',originalValue:'原创品牌',locked:true}),expect.objectContaining({field:'dialogue',originalValue:'大家好',locked:true})]));await page.reload();await expect(page.getByRole('textbox',{name:'声音策略',exact:true})).toHaveValue('只写环境声，不上传音频');await expect(page.getByRole('textbox',{name:'品牌原文',exact:true})).toHaveValue('原创品牌');await expect(page.getByLabel('创作方向',{exact:true})).toHaveValue(scene);const source=await page.evaluate(async()=>{const url='/src/infrastructure/storage/project-repository.ts';return(await import(url)).readGraph('p1');});expect(source.nodes[0].data.text).toContain('康济健葆');expect((await state(page)).runs).toEqual([]);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 PG06/PG07/PG08/PG09 reference selection, roles, reorder and removal preserve stable IDs and never delete media',async({page,networkCounter})=>{
 await page.evaluate(async()=>{const url='/src/infrastructure/storage/database.ts',m=await import(url),db=await m.openStudioDb();try{await m.transact(db,['assets','blobs'],'readwrite',(tx:IDBTransaction)=>{for(const id of ['one','two']){tx.objectStore('assets').put({id,sha256:(id==='one'?'a':'b').repeat(64),mediaType:'image',mimeType:'image/png',bytes:1,blobKey:'blob-'+id,title:'本地参考'+id,createdAt:1000});tx.objectStore('blobs').put({id:'blob-'+id,blob:new Blob(['x'],{type:'image/png'})});}});}finally{db.close();}});await page.reload();await page.getByText('本地参考素材与用途',{exact:true}).click();await expect(page.getByRole('button',{name:'新增未绑定参考说明',exact:true})).toBeDisabled();await page.getByRole('button',{name:'选择本地素材',exact:true}).click();await page.getByRole('checkbox',{name:'本地参考one',exact:true}).check();await page.getByRole('checkbox',{name:'本地参考two',exact:true}).check();await page.getByLabel('@图片1 用途',{exact:true}).fill('人物');await page.getByLabel('@图片2 用途',{exact:true}).fill('场景');await expect(page.getByRole('button',{name:'上移引用 @图片1',exact:true})).toBeDisabled();await page.getByRole('button',{name:'上移引用 @图片2',exact:true}).click();await page.getByRole('button',{name:'保存草稿',exact:true}).click();expect((await state(page)).drafts[0].references.map((r:{assetId:string;role:string;alias:string})=>[r.assetId,r.role,r.alias])).toEqual([['two','场景','@图片1'],['one','人物','@图片2']]);await page.getByRole('button',{name:'移除引用 @图片2',exact:true}).click();await page.getByLabel('外部参考说明',{exact:true}).fill('未提供人物照片');await page.getByRole('button',{name:'新增未绑定参考说明',exact:true}).click();await page.getByRole('button',{name:'保存草稿',exact:true}).click();await page.reload();const refs=(await state(page)).drafts[0].references;expect(refs[0]).toMatchObject({assetId:'two',role:'场景'});expect(refs[1]).toMatchObject({unbound:true,available:false,description:'未提供人物照片'});const count=await page.evaluate(async()=>{const url='/src/infrastructure/storage/database.ts',m=await import(url),db=await m.openStudioDb();try{return await m.transact(db,['assets'],'readonly',(tx:IDBTransaction)=>m.requestResult(tx.objectStore('assets').count()));}finally{db.close();}});expect(count).toBe(2);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 PG05/PG11/PG12 native draft storage failure preserves saved fields and exposes the current recoverable input',async({page,networkCounter})=>{
 const before=await state(page);await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(this.name==='promptDrafts')throw new DOMException('test-prompt-fields-quota','QuotaExceededError');return original.apply(this,args);};});await page.getByLabel('原始创意',{exact:true}).fill('存储失败时保留的新输入');await page.getByRole('textbox',{name:'声音策略',exact:true}).fill('尚未保存的环境声');await page.getByRole('textbox',{name:'品牌原文',exact:true}).fill('尚未保存品牌');await page.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(page.getByRole('alert')).toContainText('保存失败');expect(await state(page)).toEqual(before);await expect(page.getByLabel('原始创意',{exact:true})).toHaveValue('存储失败时保留的新输入');await page.getByRole('link',{name:'项目',exact:true}).click();await expect(page.getByRole('dialog',{name:'离开未保存提示词草稿',exact:true})).toBeVisible();expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 PG08 oversized external reference description is visibly rejected before insertion, preserves the raw note and becomes usable after correction',async({page,networkCounter})=>{
 await page.getByText('本地参考素材与用途',{exact:true}).click();const before=await state(page),note='中'.repeat(21846);await page.getByLabel('外部参考说明',{exact:true}).fill(note);await expect(page.getByRole('button',{name:'新增未绑定参考说明',exact:true})).toBeDisabled();await expect(page.getByRole('alert')).toContainText('64KiB');await expect(page.getByLabel('外部参考说明',{exact:true})).toHaveValue(note);expect(await state(page)).toEqual(before);await page.getByLabel('外部参考说明',{exact:true}).fill('修正后的原创参考说明');await page.getByRole('button',{name:'新增未绑定参考说明',exact:true}).click();await page.getByRole('button',{name:'保存草稿',exact:true}).click();expect((await state(page)).drafts[0].references[0]).toMatchObject({description:'修正后的原创参考说明',available:false,unbound:true});expect(networkCounter.paidRequests).toHaveLength(0);
});
