import {test,expect} from '../helpers/network-guard';
import {holdNextNativeCommit,releaseNativeCommit,nativeCommitProbe} from '../helpers/native-commit-hold';
import type {Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(async()=>{const p='/tests/fixtures/prompt-library.ts';return (await import(p)).promptState();});
async function deny(page:Page,table:string,operation:'put'|'getAll'='put'){await page.evaluate(({target,method})=>{const original=IDBObjectStore.prototype[method];let armed=true;Reflect.set(IDBObjectStore.prototype,method,function(this:IDBObjectStore,...args:unknown[]){if(armed&&this.name===target){armed=false;throw new DOMException('native-prompt-library-quota','QuotaExceededError');}return Reflect.apply(original,this,args);});},{target:table,method:operation});}
test.beforeEach(async({page})=>{await page.goto('/prompts');await page.evaluate(async()=>{const p='/tests/fixtures/prompt-library.ts';await (await import(p)).seedPromptLibrary();});await page.reload();});

test('T44 L02/L03/L04 actual editor, favorite and deletion read-write failures keep the original prompt versions and inserted text',async({page,networkCounter})=>{
 const before=await state(page);await deny(page,'prompts');await page.getByRole('button',{name:'收藏 本地示例',exact:true}).click();await expect(page.getByRole('alert')).toContainText('操作未完成');expect(await state(page)).toEqual(before);await page.getByRole('button',{name:'编辑 本地示例',exact:true}).click();const editor=page.getByRole('dialog',{name:'编辑提示词',exact:true});await editor.getByLabel('提示词正文',{exact:true}).fill('本地尚未保存的更改');await deny(page,'prompts');await editor.getByRole('button',{name:'保存提示词',exact:true}).click();await expect(editor.getByRole('alert')).toContainText('保存失败');expect(await state(page)).toEqual(before);await editor.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('dialog',{name:'放弃未保存提示词修改',exact:true}).getByRole('button',{name:'确认放弃修改',exact:true}).click();await deny(page,'graphs','getAll');await page.getByRole('button',{name:'删除 本地示例',exact:true}).click();await expect(page.getByRole('alert')).toContainText('操作未完成');await expect(page.getByRole('dialog',{name:'删除提示词',exact:true})).toHaveCount(0);expect(await state(page)).toEqual(before);await page.getByRole('button',{name:'删除 本地示例',exact:true}).click();const deletion=page.getByRole('dialog',{name:'删除提示词',exact:true});await deny(page,'prompts');await deletion.getByRole('button',{name:'确认软删除',exact:true}).click();await expect(deletion.getByRole('alert')).toContainText('操作未完成');expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 L08/L09 template target read and native replacement failures remain visible; pending replacement disables confirmation without changing source prompts or runs',async({page,networkCounter})=>{
 const before=await state(page);await page.getByRole('button',{name:'复制 品牌模板',exact:true}).click();const template=page.getByRole('dialog',{name:'填写模板变量',exact:true});await template.getByLabel('变量 人物',{exact:true}).fill('演员');await deny(page,'graphs','getAll');await template.getByRole('button',{name:'插入画布',exact:true}).click();await expect(template.getByRole('alert')).toContainText('操作未完成');expect(await state(page)).toEqual(before);await template.getByRole('button',{name:'应用到文本节点',exact:true}).click();await page.getByRole('dialog',{name:'选择提示词目标',exact:true}).getByRole('button',{name:'应用 提示词项目 / 旧文字',exact:true}).click();const diff=page.getByRole('dialog').filter({has:page.getByRole('button',{name:'确认替换文本',exact:true})});await deny(page,'graphs');await diff.getByRole('button',{name:'确认替换文本',exact:true}).click();await expect(diff.getByRole('alert')).toContainText('操作未完成');expect(await state(page)).toEqual(before);
 await holdNextNativeCommit(page,'graphs');await diff.getByRole('button',{name:'确认替换文本',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});try{await expect(diff.getByRole('button',{name:'确认替换文本',exact:true})).toBeDisabled();const actual=await state(page);expect(actual.prompts).toEqual(before.prompts);expect(actual.runs).toEqual(before.runs);expect(actual.graph.nodes[0].data.text).toBe('演员展示康济健葆，保持不切镜。');}finally{await releaseNativeCommit(page);}await expect(page.getByRole('status').filter({hasText:'提示词已写入文本节点'})).toBeVisible();expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 L12 actual native source-state read rejection preserves all source entries and imported prompt licenses',async({page,networkCounter})=>{
 const before=await state(page);await deny(page,'diagnostics','getAll');await page.getByRole('button',{name:'来源管理',exact:true}).click();await expect(page.getByRole('dialog',{name:'提示词来源',exact:true}).getByRole('alert')).toHaveText('来源状态读取失败，请重试。');expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);expect(networkCounter.requests.filter(r=>r.url.includes('source.invalid'))).toHaveLength(0);
});
