import {test,expect} from '../helpers/network-guard';
import {holdNextNativeCommit,releaseNativeCommit,nativeCommitProbe} from '../helpers/native-commit-hold';
import type {Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(async()=>{const p='/tests/fixtures/pending-queue.ts';return(await import(p)).pendingQueueState();});
async function denyReceipt(page:Page){await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;let armed=true;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(armed&&this.name==='receipts'){armed=false;throw new DOMException('native-queue-write-denied','QuotaExceededError');}return original.apply(this,args);};});}

test('T44 J06/J07 real native pause and withdrawal failures preserve original attempts; retries disable both controls until completion',async({page,networkCounter})=>{
 await page.goto('/projects');const ids=await page.evaluate(async()=>{const p='/tests/fixtures/pending-queue.ts';return(await import(p)).seedPendingQueue();});await page.goto('/tasks');await page.getByTestId(ids.runId).getByRole('button',{name:'详情',exact:true}).click();const region=page.getByRole('region',{name:'原任务本地队列',exact:true});await expect(region).toContainText('准备就绪');const original=await state(page);await denyReceipt(page);await region.getByRole('button',{name:'停止后续提交',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'队列或写权已变化'}).first()).toBeVisible();expect(await state(page)).toEqual(original);
 await holdNextNativeCommit(page,'receipts');await region.getByRole('button',{name:'停止后续提交',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});try{await expect(region.getByRole('button',{name:'停止后续提交',exact:true})).toBeDisabled();await expect(region.getByRole('button',{name:'移出本地待提交队列',exact:true})).toBeDisabled();expect((await state(page)).runs).toEqual(original.runs);}finally{await releaseNativeCommit(page);}await expect(region).toContainText('已暂停');await expect(region.getByRole('button',{name:'停止后续提交',exact:true})).toBeDisabled();const paused=await state(page);
 await region.getByRole('button',{name:'移出本地待提交队列',exact:true}).click();const dialog=page.getByRole('dialog',{name:'移出本地待提交队列',exact:true});await denyReceipt(page);await dialog.getByRole('button',{name:'确认撤回本地未提交项',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('操作未保存');expect(await state(page)).toEqual(paused);
 await holdNextNativeCommit(page,'receipts');await dialog.getByRole('button',{name:'确认撤回本地未提交项',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});try{await expect(dialog.getByRole('button',{name:'确认撤回本地未提交项',exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'返回保留待提交项',exact:true})).toBeDisabled();expect((await state(page)).runs).toEqual(original.runs);}finally{await releaseNativeCommit(page);}await expect(region).toContainText('本地已撤回');await expect(region.getByRole('button',{name:'移出本地待提交队列',exact:true})).toBeDisabled();expect((await state(page)).runs).toEqual(original.runs);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 C17/C18 restored queue cannot pause again and native resume preflight read failure preserves its frozen attempt without sending',async({page,networkCounter})=>{
 await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/pending-queue.ts';await(await import(p)).seedPendingQueue();});await page.goto('/projects/p1/canvas');await page.evaluate(async()=>{const p='/tests/fixtures/generation.ts';(await import(p)).connectGeneration();});const controls=page.getByRole('region',{name:'执行队列',exact:true});await expect(controls).toContainText('已暂停');await expect(controls.getByRole('button',{name:'暂停待提交项',exact:true})).toBeDisabled();const before=await state(page);await page.evaluate(()=>{const original=IDBObjectStore.prototype.get;let armed=true;IDBObjectStore.prototype.get=function(...args:Parameters<typeof original>){if(armed&&this.name==='graphs'){armed=false;throw new DOMException('native-queue-preflight-read','UnknownError');}return original.apply(this,args);};});await controls.getByRole('button',{name:'重新确认待提交项',exact:true}).click();await expect(page.getByRole('dialog').filter({hasText:'预检无法读取当前输入、能力或写权'})).toBeVisible();expect(await state(page)).toEqual(before);await expect(page.getByRole('dialog',{name:'生成确认单',exact:true})).toHaveCount(0);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 C17/C18 native pause failure keeps the pending original HTTP request and explicit retry stops later work without a new fee',async({page,networkCounter})=>{
 await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/generation.ts';await (await import(p)).seedGeneration();const d='/src/infrastructure/storage/database.ts',m=await import(d);await m.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>m.transact(db,['graphs'],'readwrite',async(tx:IDBTransaction)=>{const graph=await m.requestResult(tx.objectStore('graphs').get('p1')),video=structuredClone(graph.nodes.find((n:{id:string})=>n.id==='video-1'));video.id='video-2';video.title='第二镜头';graph.nodes.push(video);graph.edges.push({id:'second-text',sourceId:'text-1',targetId:'video-2',port:'text',order:0});tx.objectStore('graphs').put(graph);}));});await page.goto('/projects/p1/canvas');await page.evaluate(async()=>{const p='/tests/fixtures/generation.ts';(await import(p)).connectGeneration();});let release!:()=>void,received=0;const held=new Promise<void>(resolve=>{release=resolve;});await page.route('**/core-api/v1/videos/generations',async route=>{received++;await held;await route.fulfill({status:202,contentType:'application/json',body:'{"task":{"id":"mock-t44-queue-held","status":"queued"},"request_id":"mock-t44-queue-request"}'});});await page.getByRole('button',{name:'运行全部视频',exact:true}).click();const dialog=page.getByRole('dialog',{name:'生成确认单',exact:true});await dialog.getByLabel('我确认以上输入，并知悉可能消耗积分且金额未知').check();await dialog.getByRole('button',{name:'确认提交 2 项',exact:true}).click();await expect.poll(()=>received).toBe(1);const controls=page.getByRole('region',{name:'执行队列',exact:true}),before=await state(page);await expect(controls.getByRole('button',{name:'重新确认待提交项',exact:true})).toBeDisabled();await denyReceipt(page);await controls.getByRole('button',{name:'暂停待提交项',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'队列暂停未保存'})).toBeVisible();expect(await state(page)).toEqual(before);try{await controls.getByRole('button',{name:'暂停待提交项',exact:true}).click();await expect(controls).toContainText('已暂停');expect(networkCounter.paidRequests).toHaveLength(1);}finally{release();}await expect(controls).toContainText('video-1 · 已提交');await expect(controls).toContainText('video-2 · 待提交');expect(received).toBe(1);expect(networkCounter.paidRequests).toHaveLength(1);
});
