import {test,expect} from '../helpers/network-guard';
import {chromium} from '@playwright/test';
import {isAllowedTestUrl} from '../helpers/network-policy.mjs';
import {seedVisualRuntime,visualViews,openVisualView,viewportEvidence} from '../helpers/visual-runtime';
import {mkdirSync,writeFileSync} from 'node:fs';import {resolve,join} from 'node:path';import {randomUUID} from 'node:crypto';import {inflateSync} from 'node:zlib';
type ZoomTab={id?:number;url?:string};type NativeChrome={tabs:{query:(options:object)=>Promise<ZoomTab[]>;setZoom:(id:number,factor:number)=>Promise<void>;getZoom:(id:number)=>Promise<number>}};
test.setTimeout(120000);
for(const factor of [1.25,1.5])test(`T46-C03 actual Chrome tabs zoom ${factor*100}% changes CSS viewport and DPR while preserving readable Studio interaction`,async({networkCounter})=>{
 const root=resolve('work/t46-test-zoom-extension');mkdirSync(root,{recursive:true});writeFileSync(join(root,'manifest.json'),JSON.stringify({manifest_version:3,name:'Local Studio Zoom Test',version:'1.0.0',permissions:['tabs'],background:{service_worker:'worker.js'}}));writeFileSync(join(root,'worker.js'),'chrome.runtime.onInstalled.addListener(()=>{});');
 const context=await chromium.launchPersistentContext(resolve('work/t46-zoom-'+randomUUID()),{channel:'chromium',headless:true,viewport:null,args:['--window-size=1440,1000','--disable-extensions-except='+root,'--load-extension='+root]});
 try{const worker=context.serviceWorkers()[0]??await context.waitForEvent('serviceworker');context.on('request',r=>networkCounter.record(r.url(),r.method(),!isAllowedTestUrl(r.url(),'http://127.0.0.1:4179')));await context.route('**/*',async route=>{if(isAllowedTestUrl(route.request().url(),'http://127.0.0.1:4179'))await route.continue();else await route.abort('blockedbyclient');});await context.routeWebSocket('**/*',ws=>{const allowed=isAllowedTestUrl(ws.url(),'http://127.0.0.1:4179');networkCounter.record(ws.url(),'WS',!allowed);if(allowed)ws.connectToServer();else ws.close();});
  const page=context.pages()[0];await seedVisualRuntime(page);const before=await viewportEvidence(page),tabs=await worker.evaluate(()=> (Reflect.get(globalThis,'chrome') as NativeChrome).tabs.query({}));const id=tabs.find(t=>t.url?.startsWith('http://127.0.0.1:4179/'))?.id;if(!id)throw Error('native_zoom_tab_missing');await worker.evaluate(async({id,factor})=>{await(Reflect.get(globalThis,'chrome') as NativeChrome).tabs.setZoom(id,factor);},{id,factor});const confirmed=await worker.evaluate(id=>(Reflect.get(globalThis,'chrome') as NativeChrome).tabs.getZoom(id),id);expect(confirmed).toBe(factor);await page.waitForFunction(expected=>Math.abs(devicePixelRatio-expected)<.01,before.dpr*factor);const records=[];
  for(const pageId of ['P03','P13','P21','P22']){const view=visualViews.find(v=>v.id===pageId)!;await openVisualView(page,view);const evidence=await viewportEvidence(page);expect(evidence.bodyFont).toBe('16px');expect(Math.abs(evidence.innerWidth-before.innerWidth/factor)).toBeLessThanOrEqual(2);expect(evidence.documentWidth).toBeLessThanOrEqual(evidence.innerWidth);expect(evidence.dpr).toBeCloseTo(before.dpr*factor,2);await page.keyboard.press('Tab');await expect(page.locator(':focus')).toBeVisible();if(pageId==='P22'){const panel=page.getByRole('complementary',{name:'提示词生成面板',exact:true}),box=await panel.boundingBox();expect(box).toBeTruthy();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(evidence.innerWidth+1);expect(box!.y+box!.height).toBeLessThanOrEqual(evidence.innerHeight+1);await panel.getByRole('button',{name:'关闭面板',exact:true}).click({trial:true});}const screenshot='docs/review/screenshots/T46-zoom-'+factor*100+'-'+pageId+'.png';const cdp=await context.newCDPSession(page),capture=await cdp.send('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:false}),pixels=Buffer.from(capture.data,'base64');writeFileSync(screenshot,pixels);expect(pixels.readUInt32BE(16)).toBeGreaterThanOrEqual(Math.floor(evidence.innerWidth*evidence.dpr)-2);const parts:Buffer[]=[];for(let at=8;at<pixels.length;){const size=pixels.readUInt32BE(at);if(pixels.toString('ascii',at+4,at+8)==='IDAT')parts.push(pixels.subarray(at+8,at+8+size));at+=size+12;}expect(new Set(inflateSync(Buffer.concat(parts))).size,'actual rendered screenshot must contain varied pixels, never a blank headless window').toBeGreaterThan(16);await cdp.detach();records.push({id:pageId,evidence,screenshot,capture:'native Chromium viewport screenshot, physical pixels, fromSurface=true'});if(pageId==='P22'){await page.getByRole('complementary',{name:'提示词生成面板',exact:true}).getByRole('button',{name:'关闭面板',exact:true}).click();await expect(page.getByRole('complementary',{name:'提示词生成面板',exact:true})).toHaveCount(0);}}
  expect(networkCounter.paidRequests).toHaveLength(0);expect(networkCounter.requests.filter(r=>r.blocked)).toEqual([]);writeFileSync('docs/review/logs/T46-real-zoom-'+factor*100+'.json',JSON.stringify({method:'Native chrome.tabs.setZoom/getZoom in disposable local test profile',before,confirmed,records,network:networkCounter.evidence,userAcceptance:'pending'},null,2)+'\n');
 }finally{await context.close();}
});
