import {test,expect} from '../helpers/network-guard';import {seedStudio} from '../helpers/seed-studio';import type {Page} from '@playwright/test';
const records=(page:Page)=>page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['projects','graphs','runs'],'readonly',async(tx:IDBTransaction)=>({projects:await m.requestResult(tx.objectStore('projects').getAll()),graphs:await m.requestResult(tx.objectStore('graphs').getAll()),runs:await m.requestResult(tx.objectStore('runs').getAll())}));}finally{db.close();}});
async function failedDraft(page:Page){await seedStudio(page,'canvas-project');await page.goto('/projects/p1/canvas');await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof put>){if(this.name==='graphs'){IDBObjectStore.prototype.put=put;throw new DOMException('test-recovery-quota','QuotaExceededError');}return put.apply(this,args);};});await page.getByLabel('节点文本',{exact:true}).fill('真实保存失败后仍需保留的中文稿');await expect(page.locator('.canvas-heading [role="status"]')).toContainText('尚未保存');await page.getByRole('button',{name:'处理保存问题',exact:true}).click();await expect(page.getByRole('dialog',{name:'存储失败恢复',exact:true})).toBeVisible();}
test('T44 F03/D20 conflict copy after an actual native save failure preserves source project and saves the recoverable creative text under a new ID',async({page,networkCounter})=>{
 await failedDraft(page);const before=await records(page),dialog=page.getByRole('dialog',{name:'存储失败恢复',exact:true});await dialog.getByRole('button',{name:'保存为冲突副本',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('已另存冲突副本');const after=await records(page);expect(after.projects).toHaveLength(before.projects.length+1);expect(after.graphs.find((g:{projectId:string})=>g.projectId==='p1')).toEqual(before.graphs[0]);expect(after.graphs.find((g:{projectId:string})=>g.projectId!=='p1').nodes[0].data.text).toBe('真实保存失败后仍需保留的中文稿');expect(after.runs).toEqual(before.runs);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 F04 discard requires an explicit second choice, keeps the draft on return and restores the saved source without creating an execution',async({page,networkCounter})=>{
 await failedDraft(page);const before=await records(page),dialog=page.getByRole('dialog',{name:'存储失败恢复',exact:true});await dialog.getByRole('button',{name:'丢弃本地草稿并重载',exact:true}).click();await expect(dialog).toContainText('确认丢弃这份未保存');await dialog.getByRole('button',{name:'返回保留草稿',exact:true}).click();await expect(page.getByLabel('节点文本',{exact:true})).toHaveValue('真实保存失败后仍需保留的中文稿');await dialog.getByRole('button',{name:'丢弃本地草稿并重载',exact:true}).click();await dialog.getByRole('button',{name:'确认丢弃并重载',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByLabel('节点文本',{exact:true})).toHaveValue('原创镜头');expect(await records(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 F03 conflict copy native quota failure retains the current memory draft and writes no partial copy',async({page,networkCounter})=>{
 await failedDraft(page);const before=await records(page);await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof put>){if(this.name==='projects')throw new DOMException('test-conflict-copy-quota','QuotaExceededError');return put.apply(this,args);};});const dialog=page.getByRole('dialog',{name:'存储失败恢复',exact:true});await dialog.getByRole('button',{name:'保存为冲突副本',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('冲突副本未保存');expect(await records(page)).toEqual(before);await expect(page.getByLabel('节点文本',{exact:true})).toHaveValue('真实保存失败后仍需保留的中文稿');expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 H01/H02/D22 local activity filter and detail show original unknown state without querying or changing the task',async({page,networkCounter})=>{
 await seedStudio(page,'project-library');await page.goto('/activity');const before=await records(page);await page.getByLabel('按项目ID筛选',{exact:true}).fill('not-existing');await expect(page.getByText('没有符合筛选的活动；可以清除筛选查看其他记录。',{exact:true})).toBeVisible();await page.getByRole('button',{name:'清除活动筛选',exact:true}).click();await page.getByRole('button',{name:'查看活动详情',exact:true}).first().click();const dialog=page.getByRole('dialog',{name:'本地活动详情',exact:true});await expect(dialog).toContainText('submit_unknown');await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();expect(await records(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 F04 native reload failure retains the emergency draft and original saved project rather than claiming restoration',async({page,networkCounter})=>{
 await failedDraft(page);const before=await records(page),dialog=page.getByRole('dialog',{name:'存储失败恢复',exact:true});await dialog.getByRole('button',{name:'丢弃本地草稿并重载',exact:true}).click();await page.evaluate(()=>{const get=IDBObjectStore.prototype.get;IDBObjectStore.prototype.get=function(...args:Parameters<typeof get>){if(this.name==='graphs'){IDBObjectStore.prototype.get=get;throw new DOMException('test-reload-read-denied','UnknownError');}return get.apply(this,args);};});await dialog.getByRole('button',{name:'确认丢弃并重载',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('重载失败');await expect(page.getByLabel('节点文本',{exact:true})).toHaveValue('真实保存失败后仍需保留的中文稿');const recoveries=await page.evaluate(async()=>{const p='/src/features/recovery/memory-recovery.ts';return(await import(p)).readMemoryRecoveries();});expect(recoveries).toHaveLength(1);expect(await records(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 H01 native activity filter read failure reports the unread state and retains every original Run',async({page,networkCounter})=>{
 await seedStudio(page,'project-library');await page.goto('/activity');await expect(page.getByRole('button',{name:'查看活动详情',exact:true}).first()).toBeVisible();const before=await records(page);await page.evaluate(()=>{const get=IDBObjectStore.prototype.getAll;IDBObjectStore.prototype.getAll=function(...args:Parameters<typeof get>){if(this.name==='runs'){IDBObjectStore.prototype.getAll=get;throw new DOMException('test-activity-read-denied','UnknownError');}return get.apply(this,args);};});await page.getByLabel('按项目ID筛选',{exact:true}).fill('p1');await expect(page.getByRole('status')).toContainText('本地活动读取失败');expect(await records(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
