import {test,expect} from '../helpers/network-guard';
import {seedStudio} from '../helpers/seed-studio';
import {holdNextNativeCommit,nativeCommitProbe} from '../helpers/native-commit-hold';
import {zipSync,strToU8} from 'fflate';
import type {Page} from '@playwright/test';
import type {Run} from '../../src/domain/run';

async function nativeRuns(page:Page):Promise<Run[]>{return page.evaluate(async()=>{const path='/src/infrastructure/storage/database.ts',m=await import(path),db=await m.openStudioDb();try{return await m.transact(db,['runs'],'readonly',(tx:IDBTransaction)=>m.requestResult(tx.objectStore('runs').getAll()));}finally{db.close();}});}
async function setup(page:Page){await seedStudio(page,'unverified-capability');await page.evaluate(async()=>{const path='/tests/fixtures/generation.ts';await(await import(path)).seedGeneration();});await page.goto('/projects/p1/canvas');await page.evaluate(async()=>{const path='/tests/fixtures/generation.ts';await(await import(path)).connectGeneration();});await expect(page.getByTestId('node-text-1').getByLabel('节点文本')).toBeEditable();}
async function confirm(page:Page){await page.getByTestId('node-video-1').locator('[data-interaction-id="V-08"]').click();const dialog=page.getByRole('dialog',{name:'生成确认单',exact:true});await dialog.getByLabel('我确认以上输入，并知悉可能消耗积分且金额未知').check();return dialog;}

test('T45-C01 native approval commit then tab closure before dispatch preserves the original and produces zero POST on reopening',async({page,context,networkCounter})=>{
 await setup(page);const dialog=await confirm(page);await holdNextNativeCommit(page,'runs');await dialog.getByRole('button',{name:'确认提交 1 项',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});const before=await nativeRuns(page);expect(before).toHaveLength(1);expect(before[0].executionState).toBe('persisted');expect(networkCounter.paidRequests).toHaveLength(0);await page.close();const reopened=await context.newPage();await reopened.goto('/tasks');await expect(reopened.getByRole('region',{name:'本地任务中心',exact:true})).toBeVisible();expect(await nativeRuns(reopened)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);await reopened.screenshot({path:'docs/review/screenshots/T45-before-send-reopened.png'});
});
test('T45-C02 native lost response and actual tab reopening retain one frozen unknown request and never replace its body or key',async({page,context,networkCounter})=>{
 await setup(page);await page.route('**/core-api/v1/videos/generations',route=>route.abort('connectionclosed'));const dialog=await confirm(page);await dialog.getByRole('button',{name:'确认提交 1 项',exact:true}).click();await expect(page.getByRole('dialog',{name:'任务未知结果',exact:true})).toBeVisible();const before=await nativeRuns(page);expect(before).toHaveLength(1);expect(before[0]).toMatchObject({executionState:'submit_unknown',billingState:'not_provided'});expect(before[0].finalBody).toBeTruthy();expect(networkCounter.paidRequests).toHaveLength(1);await page.close();const reopened=await context.newPage();await reopened.goto('/tasks');await expect(reopened.getByRole('region',{name:'本地任务中心',exact:true})).toBeVisible();expect(await nativeRuns(reopened)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(1);await reopened.screenshot({path:'docs/review/screenshots/T45-unknown-reopened.png'});
});
test('T45-C03 actual native dispatch quota rejects a new generation before HTTP and retains the original approved attempt',async({page,networkCounter})=>{
 await setup(page);await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(this.name==='runs'&&(args[0] as {executionState?:string}).executionState==='submitting')throw new DOMException('actual-dispatch-storage-full','QuotaExceededError');return original.apply(this,args);};});const dialog=await confirm(page);await dialog.getByRole('button',{name:'确认提交 1 项',exact:true}).click();await expect(page.getByRole('region',{name:'执行队列',exact:true})).toContainText('已暂停');await expect(page.getByRole('dialog',{name:'任务未知结果',exact:true})).toHaveCount(0);const runs=await nativeRuns(page);expect(runs[0].executionState).toBe('persisted');expect(runs[0].finalBody).toBeTruthy();expect(runs[0].billingState).toBe('not_provided');expect(networkCounter.paidRequests).toHaveLength(0);
 await page.goto('/tests/fixtures/media-delivery.html');const cachedRunBefore=await nativeRuns(page);const exhausted=await page.evaluate(async()=>{const path='/src/infrastructure/storage/database.ts',delivery='/src/features/review/media-delivery.ts',m=await import(path),db=await m.openStudioDb();try{await m.transact(db,['blobs'],'readwrite',(tx:IDBTransaction)=>tx.objectStore('blobs').put({id:'existing-cache-budget',blob:new Blob([new Uint8Array(256)])}));let error='unexpected_success';try{await(await import(delivery)).fetchRunMedia('media-original-run','cache',{db,cacheBudgetBytes:128});}catch(failure){error=(failure as Error).message;}const remaining=await m.transact(db,['blobs','assets'],'readonly',async(tx:IDBTransaction)=>({blob:(await m.requestResult(tx.objectStore('blobs').get('existing-cache-budget'))).blob.size,assets:await m.requestResult(tx.objectStore('assets').count())}));return {error,...remaining};}finally{db.close();}});expect(exhausted).toEqual({error:'media_cache_budget_exceeded',blob:256,assets:0});expect(await nativeRuns(page)).toEqual(cachedRunBefore);expect(networkCounter.requests.filter(r=>r.url.endsWith('/content'))).toHaveLength(0);expect(networkCounter.paidRequests).toHaveLength(0);

});
test('T45-C04 actual replacement Key cannot query or download another binding and leaves the original task identity untouched',async({page,networkCounter})=>{
 await setup(page);await page.route('**/core-api/v1/videos/generations',route=>route.fulfill({status:202,contentType:'application/json',body:JSON.stringify({task:{id:'security-original',status:'queued'}})}));await page.route('**/core-api/v1/videos/security-original',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({task:{id:'security-original',status:'completed',content_url:'/v1/videos/security-original/content'}})}));const dialog=await confirm(page);await dialog.getByRole('button',{name:'确认提交 1 项',exact:true}).click();await expect.poll(async()=>{const rows=await nativeRuns(page);return rows[0]?.executionState;}).toBe('succeeded');const before=await nativeRuns(page),networkBefore=networkCounter.requests.filter(r=>r.url.includes('/core-api/')).length;
 const outcome=await page.evaluate(async()=>{const active='/src/adapters/core/current-connection.ts',auth='/src/domain/authorization.ts',credentials='/src/security/credential-session.ts',clientPath='/src/adapters/core/http-client.ts',delivery='/src/features/review/media-delivery.ts',poll='/src/application/runs/poll-video.ts',database='/src/infrastructure/storage/database.ts';const a=await import(active),c=await import(credentials),old=a.getActiveCore(),profile=old.client.profile,binding=(await import(auth)).createAuthBinding(profile);c.setSessionCredential(binding.id,'fake-replacement-security-key');const client=(await import(clientPath)).createCoreClient(profile,{binding,withCredential:c.withCredential},{registry:[profile]});a.setActiveCore(client,old.capability);const d=await import(database),run=await d.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>d.transact(db,['runs'],'readonly',async(tx:IDBTransaction)=>(await d.requestResult(tx.objectStore('runs').getAll()))[0]));let mediaError='unexpected_success';try{await(await import(delivery)).fetchRunMedia(run.id,'cache',{client});}catch(error){mediaError=(error as Error).message;}const queried=await(await import(poll)).pollVideoOnce(run.id,{client,capability:old.capability});return {mediaError,queryState:queried.queryState};});expect(outcome).toEqual({mediaError:'original_authorization_required',queryState:'auth_required'});const after=await nativeRuns(page);expect(after[0]).toEqual({...before[0],queryState:'auth_required',updatedAt:after[0].updatedAt});expect(networkCounter.requests.filter(r=>r.url.includes('/core-api/'))).toHaveLength(networkBefore);expect(networkCounter.paidRequests).toHaveLength(1);
});
test('T45-C05 native SVG and HTML imports stay inert even when disguised as PNG, with no asset or execution write',async({page,networkCounter})=>{
 await page.goto('/assets');await page.evaluate(async()=>{const path='/tests/fixtures/generation.ts';await(await import(path)).seedGeneration();});await page.reload();const before=await nativeRuns(page),attempts=await page.evaluate(async()=>{Object.assign(window,{securityExecuted:0});const p='/src/features/assets/import-service.ts',m=await import(p);const payloads=['<svg xmlns="http://www.w3.org/2000/svg"><script>window.securityExecuted++</script></svg>','<html><script>window.securityExecuted++</script></html>'];const reports=[];for(const [i,payload]of payloads.entries())reports.push(await m.importAssets([new File([payload],'attack-'+i+'.png',{type:'image/png'})]));return {reports,executed:Reflect.get(window,'securityExecuted')};});expect(attempts.executed).toBe(0);expect(attempts.reports).toHaveLength(2);const mediaCounts=await page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['assets','blobs'],'readonly',async(tx:IDBTransaction)=>({assets:await m.requestResult(tx.objectStore('assets').count()),blobs:await m.requestResult(tx.objectStore('blobs').count())}));}finally{db.close();}});expect(mediaCounts).toEqual({assets:0,blobs:0});for(const r of attempts.reports){expect(r.successes).toEqual([]);expect(r.failures).toHaveLength(1);expect(r.failures[0].errorCode).toBe('media_invalid_signature');}expect(await nativeRuns(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T45-C06 compressed native ZIP bomb forged expansion is rejected with an observable reason and zero creative writes',async({page,networkCounter})=>{
 await setup(page);const before=await nativeRuns(page),bytes=zipSync({'payload.bin':strToU8('x'.repeat(1024))}),view=new DataView(bytes.buffer);for(let i=0;i<bytes.length-46;i++)if(view.getUint32(i,true)===0x02014b50){view.setUint32(i+24,600*1024*1024,true);break;}await page.goto('/projects/packages');await page.getByLabel('选择项目包',{exact:true}).setInputFiles({name:'expansion-bomb.zip',mimeType:'application/zip',buffer:Buffer.from(bytes)});await expect(page.getByRole('alert').filter({hasText:'项目包未通过安全检查'})).toBeVisible();expect(await nativeRuns(page)).toEqual(before);const count=await page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['projects'],'readonly',(tx:IDBTransaction)=>m.requestResult(tx.objectStore('projects').count()));}finally{db.close();}});expect(count).toBe(1);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T45-C07 actual download redirect never contacts its target or leaks a Key and never regenerates the completed task',async({page,networkCounter})=>{
 await page.goto('/tests/fixtures/media-delivery.html');const before=await nativeRuns(page);await page.route('**/core-api/v1/videos/mock-core-1/content',async route=>{expect(route.request().headers().authorization).toBe('Bearer fake-generation-key');await route.fulfill({status:302,headers:{location:'http://127.0.0.1:4180/forbidden-key-sink'},body:''});});const message=await page.evaluate(async()=>{const path='/src/features/review/media-delivery.ts';try{await(await import(path)).fetchRunMedia('media-original-run','download');return 'unexpected_success';}catch(error){return (error as Error).message;}});expect(message).toBe('redirect_blocked');const after=await nativeRuns(page);expect(after[0]).toEqual({...before[0],deliveryState:'download_failed',updatedAt:after[0].updatedAt});expect(after[0].updatedAt).toBeGreaterThan(before[0].updatedAt);expect(networkCounter.requests.filter(r=>r.url.includes('forbidden-key-sink'))).toHaveLength(0);expect(networkCounter.requests.filter(r=>r.url.endsWith('/content'))).toHaveLength(1);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T45-C08 closing a real native approved pending queue reopens paused and never resumes unsubmitted work automatically',async({page,context,networkCounter})=>{
 await setup(page);await page.evaluate(async()=>{const s='/src/features/projects/project-service.ts',d='/src/infrastructure/storage/database.ts',a='/src/application/runs/approval.ts',p='/src/application/runs/preflight.ts',q='/src/application/runs/queue.ts',c='/src/adapters/core/current-connection.ts';const service=await import(s),database=await import(d),approval=await import(a),preflight=await import(p),queue=await import(q),core=(await import(c)).getActiveCore(),lease=await service.getProjectWriter('p1');const draft=await database.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>database.transact(db,['graphs','assets','blobs','diagnostics','runs'],'readonly',(tx:IDBTransaction)=>approval.storedRunDraft(tx,'p1',['video-1'],core,true)));const checked=preflight.preflightRun(draft);if(checked.status!=='ready')throw Error('test_preflight_not_ready');const plan=await preflight.sealRunPlan(checked.plan),approved=await approval.approveRun(plan,{confirmed:true,kind:'video',planHash:plan.planHash,nodeCount:1,acknowledgeUnknownFee:true},{...core,lease});await queue.createRunQueue({projectId:'p1',revision:1,nodeIds:['video-1'],approved},{...core,lease,tabId:service.studioTabId});});const before=await nativeRuns(page);expect(before).toHaveLength(1);expect(before[0].executionState).toBe('persisted');await page.close();const reopened=await context.newPage();await reopened.goto('/projects/p1/canvas');await reopened.getByRole('button',{name:'接管编辑',exact:true}).click();await reopened.getByRole('dialog',{name:'接管编辑',exact:true}).getByRole('button',{name:'确认接管',exact:true}).click();await expect(reopened.getByRole('region',{name:'执行队列',exact:true})).toContainText('已暂停');expect(await nativeRuns(reopened)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);await reopened.screenshot({path:'docs/review/screenshots/T45-pending-queue-reopened.png'});
});
