import {test,expect} from '../helpers/network-guard';
import {seedStudio} from '../helpers/seed-studio';
import type {Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';

test.use({actionTimeout:2500});test.setTimeout(20000);
const saved=(page:Page)=>page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p);return m.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>m.transact(db,['projects','graphs','runs','assets'],'readonly',async(tx:IDBTransaction)=>({projects:await m.requestResult(tx.objectStore('projects').getAll()),graphs:await m.requestResult(tx.objectStore('graphs').getAll()),runs:await m.requestResult(tx.objectStore('runs').getAll()),assets:await m.requestResult(tx.objectStore('assets').getAll())})));});
async function failedDraft(page:Page){await seedStudio(page,'canvas-project');await page.goto('/projects/p1/canvas');await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof put>){if(this.name==='graphs'){IDBObjectStore.prototype.put=put;throw new DOMException('qa35-native-quota','QuotaExceededError');}return put.apply(this,args);};});await page.getByLabel('节点文本',{exact:true}).fill('失败后保留的中文内存稿');await expect(page.locator('.canvas-heading [role="status"]')).toContainText('尚未保存');}
test('QA35 remaining: emergency download retains unsaved native-failed content and Retry saves exactly that draft',async({page,networkCounter})=>{
 await failedDraft(page);const before=await saved(page),pending=page.waitForEvent('download');await page.getByRole('button',{name:'导出紧急内存草稿',exact:true}).click();const download=await pending,content=JSON.parse(await readFile((await download.path())!,'utf8'));expect(content.saved).toBe(false);expect(content.graph.nodes[0].data.text).toBe('失败后保留的中文内存稿');expect(await saved(page)).toEqual(before);await page.getByRole('button',{name:'重试保存',exact:true}).click();await expect(page.locator('.canvas-heading [role="status"]')).toHaveText('已保存');const after=await saved(page);expect(after.graphs[0].nodes[0].data.text).toBe('失败后保留的中文内存稿');expect(after.runs).toEqual(before.runs);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('QA35 remaining: display reread acknowledges prior native commit without duplicate creative writes',async({page,networkCounter})=>{
 await seedStudio(page,'unverified-capability');await page.goto('/projects/p1/canvas');const before=await saved(page);await page.getByLabel('选择 镜头文字',{exact:true}).check();await page.evaluate(()=>{const getAll=IDBObjectStore.prototype.getAll;let calls=0;IDBObjectStore.prototype.getAll=function(...args:Parameters<typeof getAll>){if(this.name==='assets'&&++calls===2)throw new DOMException('qa35-display-read','UnknownError');return getAll.apply(this,args);};});await page.getByTestId('canvas-stage').focus();await page.keyboard.press('Control+d');await expect(page.getByText('已保存 · 展示刷新失败',{exact:true})).toBeVisible();const committed=await saved(page);expect(committed.graphs[0].revision).toBe(2);await page.getByRole('button',{name:'重新读取显示',exact:true}).click();await expect(page.locator('[data-node-type="text"]')).toHaveCount(2);await expect(page.getByRole('button',{name:'重新读取显示',exact:true})).toHaveCount(0);expect(await saved(page)).toEqual(committed);expect(committed.runs).toEqual(before.runs);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('QA35 remaining: invalid local draft Continue and explicit Discard leave persisted graph intact',async({page,networkCounter})=>{
 await seedStudio(page,'canvas-project');await page.goto('/projects/p1/canvas');const before=await saved(page),invalid='中'.repeat(21846);await page.getByLabel('节点文本',{exact:true}).fill(invalid);await expect(page.getByTestId('node-text-1').getByRole('alert')).toContainText('64KiB');await page.getByRole('link',{name:'项目',exact:true}).click();const dialog=page.getByRole('dialog',{name:'离开前保存'});await dialog.getByRole('button',{name:'继续编辑',exact:true}).click();await expect(page.getByLabel('节点文本',{exact:true})).toHaveValue(invalid);await page.getByRole('link',{name:'项目',exact:true}).click();await dialog.getByRole('button',{name:'放弃本次未保存修改并离开',exact:true}).click();await expect(page).toHaveURL(/\/projects$/);expect(await saved(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('QA35 remaining: recovery center exports retained native-failed draft and exposes readable fallback on download denial',async({page,networkCounter})=>{
 await failedDraft(page);const before=await saved(page);await page.getByRole('button',{name:'处理保存问题',exact:true}).click();await page.getByRole('dialog',{name:'存储失败恢复'}).getByRole('button',{name:'继续编辑',exact:true}).click();await page.getByRole('link',{name:'活动',exact:true}).click();await page.getByRole('dialog',{name:'离开前保存'}).getByRole('button',{name:'放弃本次未保存修改并离开',exact:true}).click();await page.getByRole('link',{name:'打开恢复中心',exact:true}).click();await expect(page.getByRole('button',{name:'处理当前内存草稿',exact:true})).toBeVisible();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'导出紧急内存草稿',exact:true}).click();const download=await pending;expect(JSON.parse(await readFile((await download.path())!,'utf8')).graph.nodes[0].data.text).toBe('失败后保留的中文内存稿');await page.getByRole('button',{name:'处理当前内存草稿',exact:true}).click();const dialog=page.getByRole('dialog',{name:'存储失败恢复'});await page.evaluate(()=>{const click=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){HTMLAnchorElement.prototype.click=click;throw new DOMException('qa35-native-download-denied','NotAllowedError');};});await dialog.getByRole('button',{name:'导出紧急内存草稿',exact:true}).click();const fallback=dialog.locator('[data-interaction-id="ui:RecoveryCenter:textarea:35c87868acf4"]');await expect(fallback).toHaveValue(/失败后保留的中文内存稿/);await fallback.click();await fallback.press('Control+a');await expect(fallback).toHaveAttribute('readonly','');await dialog.getByRole('button',{name:'继续编辑',exact:true}).click();await expect(dialog).toHaveCount(0);expect(await saved(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('QA35 remaining: restoring a hidden historical address never restores credentials or rewrites historical runs',async({page,networkCounter})=>{
 await page.goto('/projects');await page.evaluate(async()=>{const d='/src/infrastructure/storage/database.ts',f='/tests/helpers/fixtures.ts',p='/tests/fixtures/task-history.ts',m=await import(d),fixtures=await import(f);await(await import(p)).seedTaskHistory();await m.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>m.transact(db,['connections'],'readwrite',(tx:IDBTransaction)=>tx.objectStore('connections').put(fixtures.f.connection())));localStorage.setItem('aiwork-studio:default-connection','c1');});await page.goto('/settings/connections');const before=await saved(page);await page.getByRole('button',{name:'删除连接档案',exact:true}).click();await page.getByRole('dialog',{name:'删除连接档案'}).getByRole('button',{name:'确认删除档案',exact:true}).click();await page.getByRole('button',{name:'恢复只读地址档案 本地Mock',exact:true}).click();await expect(page.getByLabel('已保存连接',{exact:true}).locator('option[value="c1"]')).toHaveCount(1);await expect(page.getByRole('button',{name:'清除当前 Key',exact:true})).toBeDisabled();expect((await saved(page)).runs).toEqual(before.runs);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('QA35 remaining: Close batch results clears presentation and preserves partial archive plus locked project',async({page,networkCounter})=>{
 await seedStudio(page,'project-library');await page.evaluate(async()=>{const p='/src/infrastructure/storage/project-lease.ts';const result=await(await import(p)).acquireProjectLease('p2','qa35-other-tab',Date.now());if(!result.ok)throw Error('fixture_lock_failed');});await page.goto('/projects');const before=await saved(page);for(const [id,title] of [['p1','项目甲'],['p2','项目乙']])await page.getByTestId('project-'+id).getByRole('checkbox',{name:'选择'+title,exact:true}).check();await page.getByRole('button',{name:'批量归档',exact:true}).click();await page.getByRole('dialog',{name:'批量归档'}).getByRole('button',{name:'归档 2 项',exact:true}).click();await expect(page.getByRole('status')).toContainText('成功 1，失败 1');await expect(page.getByTestId('batch-failures')).toContainText('项目乙');const partial=await saved(page);expect(partial.projects.find((p:{id:string})=>p.id==='p2')).toEqual(before.projects.find((p:{id:string})=>p.id==='p2'));for(const graph of before.graphs)expect(partial.graphs.find((g:{projectId:string})=>g.projectId===graph.projectId)).toEqual({...graph,revision:graph.revision+(graph.projectId==='p1'?1:0)});expect(partial.projects.find((p:{id:string})=>p.id==='p1')).toMatchObject({archived:true,revision:2});expect(partial.runs).toEqual(before.runs);await page.getByRole('button',{name:'关闭批量结果',exact:true}).click();await expect(page.getByTestId('batch-failures')).toHaveCount(0);expect(await saved(page)).toEqual(partial);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('QA35 remaining: higher schema original package copy is byte-for-byte preserved without importing',async({page,networkCounter})=>{
 await seedStudio(page,'canvas-project');await page.goto('/projects/packages');const before=await saved(page),bytes=Buffer.from(JSON.stringify({manifest:{format:'aiwork-studio-project',schemaVersion:2,mode:'structure',createdAt:1,assets:[]},project:{},graph:{},runs:[],drafts:[]}));await page.getByLabel('选择项目包',{exact:true}).setInputFiles({name:'future.json',mimeType:'application/json',buffer:bytes});await expect(page.getByRole('alert')).toContainText('项目版本高于');const pending=page.waitForEvent('download');await page.getByRole('button',{name:'保留原始包副本',exact:true}).click();const download=await pending;expect(await readFile((await download.path())!)).toEqual(bytes);expect(await saved(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('QA35 remaining: asset library native read failure offers an actual reread without changing assets',async({page,networkCounter})=>{
 await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/asset-library.ts';await(await import(p)).seedAssetLibrary();const getAll=IDBObjectStore.prototype.getAll;IDBObjectStore.prototype.getAll=function(...args:Parameters<typeof getAll>){if(this.name==='assets'){IDBObjectStore.prototype.getAll=getAll;throw new DOMException('qa35-assets-read','UnknownError');}return getAll.apply(this,args);};});await page.getByRole('link',{name:'素材',exact:true}).click();await expect(page.getByRole('button',{name:'重新读取素材',exact:true})).toBeVisible();const before=await saved(page);await page.getByRole('button',{name:'重新读取素材',exact:true}).click();await expect(page.getByTestId('asset-card')).toHaveCount(3);await expect(page.getByRole('button',{name:'重新读取素材',exact:true})).toHaveCount(0);expect(await saved(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('QA35 remaining: task queue Return keeps pending identity and native keyboard changes only local preparation concurrency',async({page,networkCounter})=>{
 await page.goto('/projects');const ids=await page.evaluate(async()=>{const p='/tests/fixtures/pending-queue.ts';return(await import(p)).seedPendingQueue();});await page.goto('/tasks');await page.getByTestId(ids.runId).getByRole('button',{name:'详情',exact:true}).click();await page.getByRole('button',{name:'停止后续提交',exact:true}).click();const before=await saved(page);await page.getByRole('button',{name:'移出本地待提交队列',exact:true}).click();await page.getByRole('dialog',{name:'移出本地待提交队列'}).getByRole('button',{name:'返回保留待提交项',exact:true}).click();await expect(page.getByRole('dialog',{name:'移出本地待提交队列'})).toHaveCount(0);expect(await saved(page)).toEqual(before);await page.goto('/projects/p1/canvas');const select=page.getByRole('combobox',{name:'本地准备并行',exact:true});await expect(select).toBeEnabled();await select.press('ArrowDown');await select.press('Tab');await expect(select).toHaveValue('2');const queues=await page.evaluate(async()=>{const p='/src/application/runs/queue.ts';return(await import(p)).listProjectQueues('p1');});expect(queues[0].preparationConcurrency).toBe(2);expect((await saved(page)).runs).toEqual(before.runs);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('QA35 remaining: connection status configuration link closes the popup and opens settings',async({page,networkCounter})=>{
 await page.goto('/projects');await page.locator('[data-interaction-id="G-05"]').click();const dialog=page.getByRole('dialog',{name:'连接详情'});await dialog.getByRole('link',{name:'配置 Core 连接',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page).toHaveURL(/\/settings\/connections$/);await expect(page.getByLabel('Core 服务地址',{exact:true})).toBeVisible();expect(networkCounter.paidRequests).toHaveLength(0);
});
test('QA35 remaining: prompt with no project offers the actual create-target route without a video request',async({page,networkCounter})=>{
 await page.goto('/prompts');await page.getByRole('button',{name:'新建提示词',exact:true}).click();const editor=page.getByRole('dialog',{name:'编辑提示词'});await editor.getByLabel('提示词名称',{exact:true}).fill('没有目标的本地模板');await editor.getByLabel('提示词正文',{exact:true}).fill('原始提示词，不调用模型');await editor.getByRole('button',{name:'保存提示词',exact:true}).click();await page.getByRole('button',{name:'复制 没有目标的本地模板',exact:true}).click();await page.getByRole('dialog',{name:'填写模板变量'}).getByRole('button',{name:'插入画布',exact:true}).click();await page.getByRole('dialog',{name:'选择提示词目标'}).getByRole('link',{name:'先创建目标项目',exact:true}).click();await expect(page.getByRole('dialog',{name:'新建项目',exact:true})).toBeVisible();expect((await saved(page)).graphs).toEqual([]);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('QA35 remaining: activity detail next-step link closes details and opens the recorded recovery destination',async({page,networkCounter})=>{
 await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/task-history.ts';await(await import(p)).seedTaskHistory();});await page.goto('/activity');const before=await saved(page);await page.getByRole('button',{name:'查看活动详情',exact:true}).first().click();const dialog=page.getByRole('dialog',{name:'本地活动详情'}),link=dialog.locator('[data-interaction-id="ui:ActivityPage:LocalLink:057f9f2773c7"]'),href=await link.getAttribute('href');expect(href).toMatch(/^\//);await link.click();await expect(dialog).toHaveCount(0);expect(new URL(page.url()).pathname).toBe(href);expect(await saved(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('QA35 remaining: pointer attempt on unverified work-version button stays disabled with zero Core requests',async({page,networkCounter})=>{
 await seedStudio(page,'unverified-capability');await page.goto('/projects/p1/canvas');const before=await saved(page);await page.getByRole('button',{name:'作业版本与续写',exact:true}).click();const dialog=page.getByRole('dialog',{name:'作业版本与续写'}),button=dialog.getByRole('button',{name:'读取作业版本',exact:true});await expect(button).toBeDisabled();await expect(dialog).toContainText('需要原授权、已核验作业能力和原任务作业身份');const box=await button.boundingBox();expect(box).not.toBeNull();await page.mouse.click(box!.x+box!.width/2,box!.y+box!.height/2);await expect(button).toBeDisabled();await expect(dialog.getByRole('status')).toHaveText('');expect(await saved(page)).toEqual(before);expect(networkCounter.requests.filter(r=>r.url.includes('/core-api/'))).toEqual([]);await page.screenshot({path:'docs/review/qa-20261003/qa35-work-read-disabled.png'});
});
test('QA35 remaining: pointer attempt on unverified idempotency replay never emits a repeated video request',async({page,networkCounter})=>{
 await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/task-history.ts';await(await import(p)).seedTaskHistory();});await page.goto('/tasks');const before=await saved(page);await page.getByTestId('video-run-unknown').getByRole('button',{name:'详情',exact:true}).click();await page.getByRole('button',{name:'核对未知提交',exact:true}).click();const dialog=page.getByRole('dialog',{name:'任务未知结果'}),button=dialog.getByRole('button',{name:'重放原请求',exact:true});await expect(button).toBeDisabled();const box=await button.boundingBox();expect(box).not.toBeNull();await page.mouse.click(box!.x+box!.width/2,box!.y+box!.height/2);await expect(button).toBeDisabled();expect(await saved(page)).toEqual(before);expect(networkCounter.requests.filter(r=>r.method==='POST')).toEqual([]);await page.screenshot({path:'docs/review/qa-20261003/qa35-replay-disabled.png'});
});
