import {test,expect} from '../helpers/network-guard';
import {holdNextNativeCommit,releaseNativeCommit,nativeCommitProbe} from '../helpers/native-commit-hold';
import type {Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const state=(page:Page)=>page.evaluate(async()=>{const p='/tests/fixtures/result-review.ts';return(await import(p)).reviewStoredState();});
test.beforeEach(async({page})=>{await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/result-review.ts';await(await import(p)).seedResultReview();});});

test('T44 R02/R03/R05/R09/R11/R12/R13/V17 real missing media and archived project disable inapplicable actions without changing original results',async({page,networkCounter})=>{
 await page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{await m.transact(db,['projects','runs'],'readwrite',async(tx:IDBTransaction)=>{const project=await m.requestResult(tx.objectStore('projects').get('p1')),run=await m.requestResult(tx.objectStore('runs').get('r1'));project.archived=true;delete run.resultAssetId;delete run.taskId;tx.objectStore('projects').put(project);tx.objectStore('runs').put(run);});}finally{db.close();}});const before=await state(page);await page.goto('/projects/p1/results?runId=r1');await page.getByText('任务详情与版本比较',{exact:true}).click();for(const name of ['全屏预览','下载','复制任务编号','加入素材库','尾帧续写','选为后续输入'])await expect(page.getByRole('button',{name,exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:/^移除结果摆放/})).toBeDisabled();await page.getByLabel('r1',{exact:true}).check();await page.getByLabel('r2',{exact:true}).check();await page.getByRole('button',{name:'比较所选版本',exact:true}).click();await page.getByRole('dialog',{name:'对照版本选择',exact:true}).getByRole('button',{name:'开始本地对照',exact:true}).click();await expect(page.locator('[data-interaction-id="R-09"]')).toBeDisabled();expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 R02 native fullscreen rejection retains normal playable preview and all original execution and media identities',async({page,networkCounter})=>{
 await page.goto('/projects/p1/results?runId=r1');await page.getByText('任务详情与版本比较',{exact:true}).click();await expect.poll(()=>page.locator('video').evaluate((v:HTMLVideoElement)=>v.readyState)).toBeGreaterThanOrEqual(2);const before=await state(page);await page.evaluate(()=>{const original=Element.prototype.requestFullscreen;let armed=true;Element.prototype.requestFullscreen=function(...args:Parameters<typeof original>){if(armed&&this instanceof HTMLVideoElement){armed=false;return Promise.reject(new DOMException('native-fullscreen-denied','NotAllowedError'));}return original.apply(this,args);};});await page.getByRole('button',{name:'全屏预览',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'浏览器未允许全屏，可以继续普通预览。'})).toBeVisible();expect(await page.evaluate(()=>document.fullscreenElement)).toBeNull();await page.getByRole('region',{name:'视频审片预览',exact:true}).focus();await page.keyboard.press('Space');await expect.poll(()=>page.locator('video').evaluate((v:HTMLVideoElement)=>v.paused)).toBe(false);expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 R08 actual compare navigation read failure keeps both original selected versions and displays a recoverable local failure',async({page,networkCounter})=>{
 await page.goto('/projects/p1/results?runId=r1');await page.getByText('任务详情与版本比较',{exact:true}).click();const before=await state(page);await page.getByLabel('r1',{exact:true}).check();await page.getByLabel('r2',{exact:true}).check();await page.getByRole('button',{name:'比较所选版本',exact:true}).click();const dialog=page.getByRole('dialog',{name:'对照版本选择',exact:true});await page.evaluate(()=>{const original=IDBObjectStore.prototype.get;let armed=true;IDBObjectStore.prototype.get=function(...args:Parameters<typeof original>){if(armed&&this.name==='graphs'){armed=false;throw new DOMException('native-compare-source-read','UnknownError');}return original.apply(this,args);};});await dialog.getByRole('button',{name:'开始本地对照',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('项目或结果记录不可用，请查看本地任务历史。');expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 R11/V17 native selected result quota remains visible inside confirmation and preserves downstream drafts and immutable original histories',async({page,networkCounter})=>{
 await page.goto('/projects/p1/results?runId=r2');await page.getByText('任务详情与版本比较',{exact:true}).click();const before=await state(page);await page.getByRole('button',{name:'选为后续输入',exact:true}).click();const dialog=page.getByRole('dialog',{name:'确认选用结果',exact:true});await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;let armed=true;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(armed&&this.name==='graphs'){armed=false;throw new DOMException('native-result-selection-quota','QuotaExceededError');}return original.apply(this,args);};});await dialog.getByRole('button',{name:'确认选用',exact:true}).click();await expect(dialog.getByRole('status')).toHaveText('结果引用未保存；原结果与任务保留，请检查画布版本、写权和本地空间后重试。');await page.screenshot({path:'docs/review/screenshots/T44-result-native-quota.png'});expect(await state(page)).toEqual(before);await expect(dialog).toBeVisible();expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 R03/R04/R12 native download read rejection preserves original cached bytes; actual retry disables download and cache until read completion',async({page,networkCounter})=>{
 await page.goto('/projects/p1/results?runId=r1');await page.getByText('任务详情与版本比较',{exact:true}).click();await expect.poll(()=>page.locator('video').evaluate((v:HTMLVideoElement)=>v.readyState)).toBeGreaterThanOrEqual(2);const before=await state(page),bytes=await page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['blobs','assets'],'readonly',async(tx:IDBTransaction)=>{const asset=await m.requestResult(tx.objectStore('assets').get('result-asset-1')),row=await m.requestResult(tx.objectStore('blobs').get(asset.blobKey));return Array.from(new Uint8Array(await row.blob.arrayBuffer()));});}finally{db.close();}});await page.evaluate(()=>{const original=IDBObjectStore.prototype.get;let armed=true;IDBObjectStore.prototype.get=function(...args:Parameters<typeof original>){if(armed&&this.name==='blobs'){armed=false;throw new DOMException('native-result-download-read','UnknownError');}return original.apply(this,args);};});await page.getByRole('button',{name:'下载',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'视频加载或保存失败'})).toBeVisible();expect(await state(page)).toEqual(before);
 await holdNextNativeCommit(page,'blobs','readonly');const pending=page.waitForEvent('download');await page.getByRole('button',{name:'重新下载',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});try{await expect(page.getByRole('button',{name:'重新下载',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'加入素材库',exact:true})).toBeDisabled();expect(await state(page)).toEqual(before);}finally{await releaseNativeCommit(page);}const download=await pending;expect(Array.from(await readFile((await download.path())!))).toEqual(bytes);const after=await state(page),changed=after.runs.find((r:{id:string})=>r.id==='r1');expect(changed.updatedAt).toBeGreaterThan(before.runs.find((r:{id:string})=>r.id==='r1').updatedAt);expect(after).toEqual({...before,runs:before.runs.map((r:{id:string})=>r.id==='r1'?{...r,deliveryState:'browser_download_triggered',updatedAt:changed.updatedAt}:r)});expect(networkCounter.paidRequests).toHaveLength(0);
});
