import {test,expect} from '../helpers/network-guard';import type {Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(async()=>{const p='/tests/fixtures/result-review.ts';return(await import(p)).reviewStoredState();});
test.beforeEach(async({page})=>{await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/result-review.ts';await(await import(p)).seedResultReview();});await page.goto('/projects/p1/results?runId=r1');await page.getByText('任务详情与版本比较',{exact:true}).click();});
test('T44 R01/R05/R06/R07 canvas review navigation, original identity copy and history selection never change source or downstream input',async({page,networkCounter})=>{
 const before=await state(page);await page.goto('/projects/p1/canvas');await page.getByRole('button',{name:'查看结果与审片',exact:true}).click();await page.getByText('任务详情与版本比较',{exact:true}).click();await expect(page.getByRole('combobox',{name:'历史版本',exact:true})).toHaveValue('r1');await page.evaluate(()=>Object.defineProperty(navigator.clipboard,'writeText',{value:async(text:string)=>{document.documentElement.dataset.testReviewCopy=text;},configurable:true}));await page.getByRole('button',{name:'复制任务编号',exact:true}).click();const original=before.runs.find((r:{id:string})=>r.id==='r1');expect(await page.evaluate(()=>document.documentElement.dataset.testReviewCopy)).toBe(original.connectionId+' / '+original.taskId);await page.getByRole('button',{name:'复制参数快照',exact:true}).click();expect(JSON.parse((await page.evaluate(()=>document.documentElement.dataset.testReviewCopy))!)).toEqual(original.inputSnapshot);await page.getByRole('combobox',{name:'历史版本',exact:true}).selectOption('r2');await expect(page).toHaveURL(/runId=r2/);await page.reload();await expect(page.getByRole('combobox',{name:'历史版本',exact:true})).toHaveValue('r2');const after=await state(page);expect(after.graph).toEqual(before.graph);expect(after.runs).toEqual(before.runs);expect(after.assets).toEqual(before.assets);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 R05/R06 clipboard rejection reports the failure and preserves the native result and original parameter snapshot',async({page,networkCounter})=>{
 const before=await state(page);await page.evaluate(()=>Object.defineProperty(navigator.clipboard,'writeText',{value:async()=>{throw new DOMException('test-result-copy-denied','NotAllowedError');},configurable:true}));for(const name of ['复制任务编号','复制参数快照']){await page.getByRole('button',{name,exact:true}).click();await expect(page.getByRole('status').filter({hasText:'复制失败，可手动选择原文。'})).toBeVisible();}const after=await state(page);expect(after.graph).toEqual(before.graph);expect(after.runs).toEqual(before.runs);expect(after.assets).toEqual(before.assets);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 R13 remove placement is separately confirmed, preserves immutable task and original files, and is undoable through the canvas',async({page,networkCounter})=>{
 const before=await state(page);await page.getByRole('button',{name:'移除结果摆放 选用的结果',exact:true}).click();let dialog=page.getByRole('dialog',{name:'移除结果摆放',exact:true});await dialog.getByRole('button',{name:'取消',exact:true}).click();expect((await state(page)).graph).toEqual(before.graph);await page.getByRole('button',{name:'移除结果摆放 选用的结果',exact:true}).click();dialog=page.getByRole('dialog',{name:'移除结果摆放',exact:true});await dialog.getByRole('button',{name:'确认移除',exact:true}).click();await expect(dialog).not.toBeVisible();const removed=await state(page);expect(removed.graph.nodes.some((n:{id:string})=>n.id==='result-ref')).toBe(false);expect(removed.runs).toEqual(before.runs);expect(removed.assets).toEqual(before.assets);await page.goto('/projects/p1/canvas');await page.getByRole('button',{name:'撤销',exact:true}).click();await expect(page.getByTestId('node-result-ref')).toBeVisible();expect((await state(page)).graph.nodes).toEqual(before.graph.nodes);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 R13 native removal quota failure leaves the placement, result history and media intact with an explicit retry message',async({page,networkCounter})=>{
 const before=await state(page);await page.getByRole('button',{name:'移除结果摆放 选用的结果',exact:true}).click();await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof put>){if(this.name==='graphs')throw new DOMException('test-result-removal-quota','QuotaExceededError');return put.apply(this,args);};});await page.getByRole('dialog',{name:'移除结果摆放',exact:true}).getByRole('button',{name:'确认移除',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'移除未保存'})).toBeVisible();const after=await state(page);expect(after.graph).toEqual(before.graph);expect(after.runs).toEqual(before.runs);expect(after.assets).toEqual(before.assets);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 M04/M05/M06 native playback, mute, volume and seeking affect only the readable local clip',async({page,networkCounter})=>{
 const before=await state(page),video=page.locator('video');await expect.poll(()=>video.evaluate((el:HTMLVideoElement)=>el.readyState)).toBeGreaterThanOrEqual(2);await page.getByRole('button',{name:'取消静音 原创版本1.webm',exact:true}).click();await expect(video).toHaveJSProperty('muted',false);await page.getByRole('slider',{name:'原创版本1.webm 音量',exact:true}).press('End');await expect(video).toHaveJSProperty('volume',1);await page.getByRole('button',{name:'播放 原创版本1.webm',exact:true}).click();await expect(video).toHaveJSProperty('paused',false);await page.getByRole('button',{name:'暂停 原创版本1.webm',exact:true}).click();await expect(video).toHaveJSProperty('paused',true);await page.getByRole('slider',{name:'原创版本1.webm 播放进度',exact:true}).press('ArrowLeft');await expect(video).toHaveJSProperty('currentTime',0);const after=await state(page);expect(after.graph).toEqual(before.graph);expect(after.runs).toEqual(before.runs);expect(after.assets).toEqual(before.assets);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T44 R09 one-sided native playback rejection pauses both clips and preserves their fixed original results',async({page,networkCounter})=>{
 const before=await state(page);await page.goto('/projects/p1/compare?runs=r1,r2');const play=page.getByRole('button',{name:'同步播放',exact:true});await expect(play).toBeEnabled();await page.evaluate(()=>{const play=HTMLMediaElement.prototype.play;let first=true;HTMLMediaElement.prototype.play=function(){if(first){first=false;return Promise.reject(new DOMException('test-comparison-play-denied','NotAllowedError'));}return play.call(this);};});await play.click();await expect(page.getByRole('status').filter({hasText:'一侧播放失败，双方已暂停'})).toBeVisible();for(const video of await page.locator('video').all())await expect(video).toHaveJSProperty('paused',true);const after=await state(page);expect(after.graph).toEqual(before.graph);expect(after.runs).toEqual(before.runs);expect(after.assets).toEqual(before.assets);expect(networkCounter.paidRequests).toHaveLength(0);
});
