import {test,expect} from '../helpers/network-guard';
import {seedStudio} from '../helpers/seed-studio';
test.setTimeout(20000);
test('T29: refreshed pending queue is visible and paused; resume opens fresh confirmation with zero POST',async({page,networkCounter})=>{
 await seedStudio(page,'unverified-capability');await page.evaluate(async()=>{const fixture='/tests/fixtures/generation.ts';await(await import(fixture)).seedGeneration();await(await import(fixture)).connectGeneration();
  const service='/src/features/projects/project-service.ts',database='/src/infrastructure/storage/database.ts',approval='/src/application/runs/approval.ts',preflight='/src/application/runs/preflight.ts',queue='/src/application/runs/queue.ts',active='/src/adapters/core/current-connection.ts';
  const s=await import(service),d=await import(database),a=await import(approval),p=await import(preflight),q=await import(queue),core=(await import(active)).getActiveCore(),lease=await s.getProjectWriter('p1');
  const draft=await d.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>d.transact(db,['graphs','assets','blobs','diagnostics','runs'],'readonly',(tx:IDBTransaction)=>a.storedRunDraft(tx,'p1',['video-1'],core,true)));const checked=p.preflightRun(draft);if(checked.status!=='ready')throw Error('fixture blocked');const plan=await p.sealRunPlan(checked.plan),approved=await a.approveRun(plan,{confirmed:true,kind:'video',planHash:plan.planHash,nodeCount:1,acknowledgeUnknownFee:true},{...core,lease});await q.createRunQueue({projectId:'p1',revision:1,nodeIds:['video-1'],approved},{...core,lease,tabId:s.studioTabId});
 });
 await page.goto('/projects/p1/canvas');await page.evaluate(async()=>{const fixture='/tests/fixtures/generation.ts';await(await import(fixture)).connectGeneration();});const controls=page.getByRole('region',{name:'执行队列'});await expect(controls).toContainText('已暂停');expect(networkCounter.paidRequests).toHaveLength(0);await controls.getByRole('button',{name:'重新确认待提交项'}).click();await expect(page.getByRole('dialog',{name:'生成确认单',exact:true})).toBeVisible();expect(networkCounter.paidRequests).toHaveLength(0);await page.keyboard.press('Escape');await expect(controls.getByRole('button',{name:'重新确认待提交项'})).toBeFocused();await page.screenshot({path:'docs/review/screenshots/T29-queue-paused.png'});
});
test('T29: actual pause while the first request waits keeps its response and stops the second submission',async({page,networkCounter})=>{
 await seedStudio(page,'unverified-capability');await page.evaluate(async()=>{const fixture='/tests/fixtures/generation.ts';await(await import(fixture)).seedGeneration();const database='/src/infrastructure/storage/database.ts',d=await import(database);await d.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>d.transact(db,['graphs'],'readwrite',async(tx:IDBTransaction)=>{const graph=await d.requestResult(tx.objectStore('graphs').get('p1')),video=structuredClone(graph.nodes.find((n:{id:string})=>n.id==='video-1'));video.id='video-2';video.title='第二镜头';video.y=350;graph.nodes.push(video);graph.edges.push({id:'second-text',sourceId:'text-1',targetId:'video-2',port:'text',order:0});tx.objectStore('graphs').put(graph);}));});
 await page.goto('/projects/p1/canvas');await page.evaluate(async()=>{const fixture='/tests/fixtures/generation.ts';await(await import(fixture)).connectGeneration();});let release!:()=>void;const held=new Promise<void>(resolve=>{release=resolve;});let received=0;await page.route('**/core-api/v1/videos/generations',async route=>{received++;await held;await route.fulfill({status:202,contentType:'application/json',body:JSON.stringify({task:{id:'mock-queue-first',status:'queued'},request_id:'mock-queue-request'})});});await page.getByRole('button',{name:'运行全部视频',exact:true}).click();const dialog=page.getByRole('dialog',{name:'生成确认单',exact:true});await dialog.getByLabel('我确认以上输入，并知悉可能消耗积分且金额未知').check();await dialog.getByRole('button',{name:'确认提交 2 项',exact:true}).click();await expect.poll(()=>received).toBe(1);const controls=page.getByRole('region',{name:'执行队列'});await controls.getByRole('button',{name:'暂停待提交项'}).click();release();await expect(controls).toContainText('已暂停');await expect(controls).toContainText('video-1 · 已提交');await expect(controls).toContainText('video-2 · 待提交');expect(networkCounter.paidRequests).toHaveLength(1);await expect(page.getByRole('dialog',{name:'提交结果不明'})).not.toBeVisible();
});
