import {test,expect} from '../helpers/network-guard';
import {holdNextNativeCommit,releaseNativeCommit,nativeCommitProbe} from '../helpers/native-commit-hold';
import type {Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const state=(page:Page)=>page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',m=await import(p),db=await m.openStudioDb();try{return await m.transact(db,['connections','projects','graphs','runs','promptRuns','receipts'],'readonly',async(tx:IDBTransaction)=>Object.fromEntries(await Promise.all(['connections','projects','graphs','runs','promptRuns','receipts'].map(async table=>[table,await m.requestResult(tx.objectStore(table).getAll())]))));}finally{db.close();}});
test.beforeEach(async({page})=>{await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/task-history.ts';await (await import(p)).seedTaskHistory();});await page.goto('/settings/storage');await expect(page.getByRole('button',{name:'导出脱敏设置',exact:true})).toBeVisible();});

test('T44 D09/D10 native configuration read failure and pending export preserve old tasks and disable both transfer controls',async({page,networkCounter})=>{
 const before=await state(page);await page.evaluate(()=>{const original=IDBObjectStore.prototype.getAll;let armed=true;IDBObjectStore.prototype.getAll=function(...args:Parameters<typeof original>){if(armed&&this.name==='connections'){armed=false;throw new DOMException('native-settings-export-read','UnknownError');}return original.apply(this,args);};});await page.getByRole('button',{name:'导出脱敏设置',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('设置文件未通过白名单检查，或本地保存未完成；没有自动测试、安装或生成。');expect(await state(page)).toEqual(before);
 await holdNextNativeCommit(page,'connections','readonly');const pending=page.waitForEvent('download');await page.getByRole('button',{name:'导出脱敏设置',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});try{await expect(page.getByRole('button',{name:'导出脱敏设置',exact:true})).toBeDisabled();await expect(page.getByLabel('选择设置文件',{exact:true})).toBeDisabled();expect(await state(page)).toEqual(before);}finally{await releaseNativeCommit(page);}const download=await pending,document=JSON.parse((await readFile((await download.path())!)).toString());expect(document.format).toBe('aiwork-studio-settings');expect(JSON.stringify(document)).not.toMatch(/authBindingId|apiKey|authorization|token/);expect(await state(page)).toEqual(before);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('T44 D10 native imported connection quota leaves old ownership intact and a real retry stays busy until acknowledgement',async({page,networkCounter})=>{
 const before=await state(page),bytes=await page.evaluate(async()=>{const p='/src/features/settings/settings-transfer.ts';return (await (await import(p)).exportSettings()).text();}),document=JSON.parse(bytes);document.connections=[{id:'untrusted-import-id',name:'本地迁移目标',originSnapshot:'https://core.invalid',proxyBase:'/core-api',contractVersion:'unverified'}];await page.getByLabel('选择设置文件',{exact:true}).setInputFiles({name:'settings.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(document))});const dialog=page.getByRole('dialog',{name:'选择性导入设置',exact:true});await expect(dialog).toContainText('地址需要重新授权');await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;let armed=true;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(armed&&this.name==='connections'){armed=false;throw new DOMException('native-settings-import-quota','QuotaExceededError');}return original.apply(this,args);};});await dialog.getByRole('button',{name:'确认导入所选设置',exact:true}).click();await expect(page.getByRole('alert')).toHaveText('设置文件未通过白名单检查，或本地保存未完成；没有自动测试、安装或生成。');await expect(dialog).toBeVisible();expect(await state(page)).toEqual(before);
 await holdNextNativeCommit(page,'connections');await dialog.getByRole('button',{name:'确认导入所选设置',exact:true}).click();await expect.poll(()=>nativeCommitProbe(page)).toMatchObject({nativeCommitted:true,awaitingDelivery:true});try{await expect(dialog.getByRole('button',{name:'确认导入所选设置',exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'取消',exact:true})).toBeDisabled();await expect(page.getByLabel('选择设置文件',{exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'导出脱敏设置',exact:true})).toBeDisabled();const actual=await state(page);expect(actual.connections).toHaveLength(before.connections.length+1);expect(actual.connections[0].id).not.toBe('untrusted-import-id');expect(actual.runs).toEqual(before.runs);expect(actual.promptRuns).toEqual(before.promptRuns);expect(actual.graphs).toEqual(before.graphs);expect(actual.projects).toEqual(before.projects);}finally{await releaseNativeCommit(page);}await expect(dialog).toHaveCount(0);await expect(page.getByRole('status').filter({hasText:'没有自动测试'})).toBeVisible();expect(networkCounter.paidRequests).toHaveLength(0);expect(networkCounter.requests.filter(row=>row.url.includes('/core-api/'))).toHaveLength(0);
});
