import {test,expect} from '../helpers/network-guard';
import type {Page} from '@playwright/test';
const original='松鼠把苹果递给猴子，随后一起走入树林。';
const polished='松鼠双爪捧起苹果递给猴子，猴子接过苹果，二者沿林间小路缓缓前行，镜头稳定跟随。';
const stored=(page:Page)=>page.evaluate(async()=>{const p='/tests/fixtures/result-review.ts';return(await import(p)).reviewStoredState();});
async function open(page:Page){await page.getByRole('button',{name:'尾帧续写',exact:true}).click();const dialog=page.getByRole('dialog',{name:'尾帧续写',exact:true});await expect(dialog.getByRole('img',{name:'提取的尾帧',exact:true})).toBeVisible();return dialog;}
test.beforeEach(async({page})=>{
 await page.goto('/projects');await page.evaluate(async()=>{const p='/tests/fixtures/result-review.ts';await(await import(p)).seedResultReview();});await page.goto('/projects/p1/results?runId=r1');
});
async function connect(page:Page){await page.evaluate(async()=>{const p='/tests/fixtures/generation.ts',g=await import(p);g.connectGeneration();const d='/src/infrastructure/storage/database.ts',db=await import(d);await db.withDatabase(undefined,(c:import('../../src/infrastructure/storage/database').StudioDb)=>db.transact(c,['diagnostics'],'readwrite',(tx:IDBTransaction)=>tx.objectStore('diagnostics').put({id:'capability:current',capability:g.generationCaps})));});}
const response=()=>({choices:[{message:{content:JSON.stringify({finalPrompt:polished,shotPlan:[],improvements:['明确动作顺序'],warnings:['未看到尾帧，不推断上段姿态'],suggestedSpec:{durationSeconds:5,ratio:'9:16'}})}}]});

test('tail dialog polishes inline using configured model and confirms edited result before creating connected canvas draft',async({page,networkCounter})=>{
 await connect(page);const before=await stored(page);await page.route('**/core-api/v1/chat/completions',route=>{const body=route.request().postDataJSON(),input=JSON.parse(body.messages[1].content);expect(body.model).toBe('fake-text-only');expect(input.userRequest).toBe(original);expect(input.scene.title).toBe('视频延长');expect(input.references).toEqual([]);return route.fulfill({contentType:'application/json',body:JSON.stringify(response())});});
 const dialog=await open(page);await dialog.getByLabel('下一段内容',{exact:true}).fill(original);await dialog.getByRole('button',{name:'AI润色',exact:true}).click();await expect(dialog.getByLabel('润色结果',{exact:true})).toHaveValue(polished);await expect(dialog.getByLabel('下一段内容',{exact:true})).toHaveValue(original);
 const preview=await stored(page);expect(preview.runs).toEqual(before.runs);expect(preview.graph).toEqual(before.graph);expect(preview.assets).toEqual(before.assets);expect(networkCounter.paidRequests).toHaveLength(1);
 await dialog.getByLabel('润色结果',{exact:true}).fill(polished+' 保持自然光。');await dialog.getByRole('button',{name:'确认并进入画布',exact:true}).click();await expect(page).toHaveURL(/\/projects\/p1\/canvas\?node=/);
 const after=await stored(page),text=after.graph.nodes.find((n:{title:string})=>n.title==='续写提示词'),video=after.graph.nodes.find((n:{title:string})=>n.title==='尾帧续写视频');expect(text.data.text).toBe(polished+' 保持自然光。');expect(after.graph.edges.filter((e:{targetId:string})=>e.targetId===video.id).map((e:{port:string})=>e.port).sort()).toEqual(['image','text']);expect(after.runs).toEqual(before.runs);expect(networkCounter.paidRequests).toHaveLength(1);
});

test('tail dialog without current text authorization explains connection and keeps manual continuation available',async({page,networkCounter})=>{
 const dialog=await open(page);await dialog.getByLabel('下一段内容',{exact:true}).fill(original);await expect(dialog.getByRole('button',{name:'AI润色',exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'创建续写草稿',exact:true})).toBeEnabled();await dialog.getByRole('button',{name:'连接文字 API',exact:true}).click();await expect(page).toHaveURL(/settings\/connections/);expect(networkCounter.paidRequests).toHaveLength(0);
});

test('tail text failure preserves input and source clip and never submits video or automatically retries',async({page,networkCounter})=>{
 await connect(page);const before=await stored(page);await page.route('**/core-api/v1/chat/completions',route=>route.fulfill({status:401,contentType:'application/json',body:'{"error":{"code":"invalid_api_key","message":"fake-key-never-display"}}'}));const dialog=await open(page);await dialog.getByLabel('下一段内容',{exact:true}).fill(original);await dialog.getByRole('button',{name:'AI润色',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('401');await expect(dialog.getByRole('alert')).not.toContainText('fake-key-never-display');await expect(dialog.getByLabel('下一段内容',{exact:true})).toHaveValue(original);await expect(dialog.getByLabel('润色结果',{exact:true})).not.toBeVisible();const after=await stored(page);expect(after.runs).toEqual(before.runs);expect(after.graph).toEqual(before.graph);expect(after.assets).toEqual(before.assets);expect(networkCounter.paidRequests).toHaveLength(1);
});

test('invalid AI output is kept for review and does not become a usable tail prompt',async({page,networkCounter})=>{
 await connect(page);await page.route('**/core-api/v1/chat/completions',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({choices:[{message:{content:'unstructured-output'}}]})}));const dialog=await open(page);await dialog.getByLabel('下一段内容',{exact:true}).fill(original);await dialog.getByRole('button',{name:'AI润色',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('解析');await expect(dialog.getByLabel('润色结果',{exact:true})).not.toBeVisible();await expect(dialog.getByLabel('下一段内容',{exact:true})).toHaveValue(original);expect(networkCounter.paidRequests).toHaveLength(1);
});

test('changing the idea invalidates its polished result; cancelling creates no canvas nodes',async({page,networkCounter})=>{
 await connect(page);const before=await stored(page);await page.route('**/core-api/v1/chat/completions',route=>route.fulfill({contentType:'application/json',body:JSON.stringify(response())}));const dialog=await open(page);await dialog.getByLabel('下一段内容',{exact:true}).fill(original);await dialog.getByRole('button',{name:'AI润色',exact:true}).click();await expect(dialog.getByLabel('润色结果',{exact:true})).toHaveValue(polished);await dialog.getByLabel('下一段内容',{exact:true}).fill('猴子继续爬树。');await expect(dialog.getByRole('button',{name:'确认并进入画布',exact:true})).not.toBeVisible();await expect(dialog.getByLabel('润色结果',{exact:true})).not.toBeVisible();await dialog.getByRole('button',{name:'取消',exact:true}).click();const after=await stored(page);expect(after.runs).toEqual(before.runs);expect(after.graph).toEqual(before.graph);expect(after.assets).toEqual(before.assets);expect(networkCounter.paidRequests).toHaveLength(1);
});

test('closing while AI is pending ignores late output and reopening requires review before any new charged request',async({page,networkCounter})=>{
 await connect(page);const before=await stored(page);let release!:()=>void,seen!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),requested=new Promise<void>(resolve=>seen=resolve);
 await page.route('**/core-api/v1/chat/completions',async route=>{seen();await gate;await route.fulfill({contentType:'application/json',body:JSON.stringify(response())}).catch(()=>{});});
 const dialog=await open(page);await dialog.getByLabel('下一段内容',{exact:true}).fill(original);await dialog.getByRole('button',{name:'AI润色',exact:true}).dblclick();await requested;await expect(dialog.getByRole('button',{name:'AI润色',exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'创建续写草稿',exact:true})).toBeDisabled();await dialog.getByRole('button',{name:'取消',exact:true}).click();release();await expect(dialog).not.toBeVisible();
 await expect.poll(()=>page.evaluate(async()=>{const p='/src/infrastructure/storage/database.ts',d=await import(p);return d.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>d.transact(db,['promptRuns'],'readonly',async(tx:IDBTransaction)=>(await d.requestResult(tx.objectStore('promptRuns').getAll()) as {executionState:string}[]).map(run=>run.executionState)));})).toEqual(['waiting_stopped']);
 const reopened=await open(page);await reopened.getByLabel('下一段内容',{exact:true}).fill(original);await expect(reopened.getByLabel('润色结果',{exact:true})).not.toBeVisible();await reopened.getByRole('button',{name:'AI润色',exact:true}).click();const review=page.getByRole('dialog',{name:'核对旧文字请求',exact:true});await expect(review).toBeVisible();await expect(review.getByRole('button',{name:'确认新的文字请求',exact:true})).toBeDisabled();await review.getByRole('button',{name:'取消',exact:true}).click();await reopened.getByRole('button',{name:'取消',exact:true}).click();const after=await stored(page);expect(after.runs).toEqual(before.runs);expect(after.graph).toEqual(before.graph);expect(after.assets).toEqual(before.assets);expect(networkCounter.paidRequests).toHaveLength(1);
});
