import {test,expect} from '../helpers/network-guard';
import type {Page} from '@playwright/test';
const state=(page:Page)=>page.evaluate(async()=>{const p='/tests/fixtures/task-history.ts';return(await import(p)).taskHistoryState();});
const details=async(page:Page)=>{await page.getByTestId('video-run-1').getByRole('button',{name:'详情',exact:true}).click();return page.getByRole('dialog',{name:'任务详情',exact:true});};
test.beforeEach(async({page})=>{await page.goto('/tasks');await page.evaluate(async()=>{const p='/tests/fixtures/task-history.ts';await(await import(p)).seedTaskHistory();});await page.reload();await expect(page.getByTestId('video-run-1')).toBeVisible();});
test('T44 V12/V13 explicit original query and local pause preserve the frozen request and billing; pause persists and a second pause is disabled',async({page,networkCounter})=>{await page.evaluate(async()=>{const p='/tests/fixtures/task-history.ts';(await import(p)).connectTaskHistory();});await page.route('**/core-api/v1/videos/mock-core-1',route=>route.fulfill({contentType:'application/json',body:'{"id":"mock-core-1","status":"running"}'}));const before=await state(page),dialog=await details(page);await dialog.getByRole('button',{name:'重新查询原任务',exact:true}).click();await expect(dialog.getByRole('status').filter({hasText:'已查询原任务，没有创建新任务。'})).toBeVisible();await dialog.getByRole('button',{name:'停止本地查询',exact:true}).click();await expect(dialog.getByRole('status').filter({hasText:'已停止本地查询，不代表取消或退款。'})).toBeVisible();await expect(dialog.getByRole('button',{name:'停止本地查询',exact:true})).toBeDisabled();const after=await state(page),original=before.runs.find((r:{id:string})=>r.id==='video-run-1'),changed=after.runs.find((r:{id:string})=>r.id==='video-run-1');expect(changed).toMatchObject({queryState:'paused_by_user',executionState:'running',billingState:original.billingState,connectionId:original.connectionId,authBindingId:original.authBindingId,originSnapshot:original.originSnapshot,inputSnapshot:original.inputSnapshot,idempotencyKey:original.idempotencyKey});expect(after.runs.filter((r:{id:string})=>r.id!=='video-run-1')).toEqual(before.runs.filter((r:{id:string})=>r.id!=='video-run-1'));await page.reload();const restored=await details(page);await expect(restored).toContainText('已停止本地查询');expect(networkCounter.requests.filter(r=>r.url.endsWith('/v1/videos/mock-core-1'))).toHaveLength(1);expect(networkCounter.paidRequests).toHaveLength(0);});
test('T44 V12/J03 missing original authorization disables queries but locating an existing original node navigates without rewriting records',async({page,networkCounter})=>{const before=await state(page),dialog=await details(page);await expect(dialog.getByRole('button',{name:'重新查询原任务',exact:true})).toBeDisabled();await dialog.getByRole('button',{name:'定位原节点',exact:true}).click();await expect(page).toHaveURL(/\/projects\/p1\/canvas\?node=text-1$/);await expect(page.getByTestId('node-text-1')).toBeVisible();expect((await state(page)).runs).toEqual(before.runs);expect(networkCounter.paidRequests).toHaveLength(0);expect(networkCounter.requests.filter(r=>r.url.includes('/core-api/'))).toHaveLength(0);});
test('T44 V12 native query save failure is reported and preserves original identity, frozen request and all task records',async({page,networkCounter})=>{await page.evaluate(async()=>{const p='/tests/fixtures/task-history.ts';(await import(p)).connectTaskHistory();});const before=await state(page),dialog=await details(page);await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof put>){if(this.name==='runs')throw new DOMException('test-single-query-quota','QuotaExceededError');return put.apply(this,args);};});await dialog.getByRole('button',{name:'重新查询原任务',exact:true}).click();await expect(dialog.getByRole('status').filter({hasText:'查询尚未完成，请核对原服务与授权；未重新提交。'})).toBeVisible();expect((await state(page)).runs).toEqual(before.runs);expect(networkCounter.paidRequests).toHaveLength(0);});
test('T44 V13 native pause save failure keeps the previous query state and never calls cancellation or refunds',async({page,networkCounter})=>{const before=await state(page),dialog=await details(page);await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof put>){if(this.name==='runs')throw new DOMException('test-local-pause-quota','QuotaExceededError');return put.apply(this,args);};});await dialog.getByRole('button',{name:'停止本地查询',exact:true}).click();await expect(dialog.getByRole('status').filter({hasText:'停止查询尚未保存，请保留原记录。'})).toBeVisible();expect((await state(page)).runs).toEqual(before.runs);expect(networkCounter.requests.filter(r=>r.url.includes('/core-api/'))).toHaveLength(0);expect(networkCounter.paidRequests).toHaveLength(0);});
