import {test,expect} from '../helpers/network-guard';
import {seedStudio} from '../helpers/seed-studio';
test.use({actionTimeout:2500});test.setTimeout(20000);
test.beforeEach(async({page})=>{await seedStudio(page,'unverified-capability');await page.goto('/projects/p1/canvas');});
test('T14-C04: unknown capabilities keep video drafts editable without an execution button',async({page,networkCounter})=>{
 await page.getByTestId('node-video-1').click();await expect(page.getByText('尚未验证此功能是否可用',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'确认生成',exact:true})).toHaveCount(0);await expect(page.getByLabel('视频模型')).toBeDisabled();await expect(page.getByTestId('node-video-1')).toHaveCSS('width','360px');await expect(page.getByTestId('node-text-1')).toHaveCSS('width','320px');expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T14-C05: debounced local text saves; UTF-8 overflow keeps persisted text intact',async({page,networkCounter})=>{
 const node=page.getByTestId('node-text-1'),field=node.getByLabel('节点文本');await field.fill('新的原创镜头');await expect(page.getByText('已保存',{exact:true})).toBeVisible();await page.reload();await expect(field).toHaveValue('新的原创镜头');await field.fill('中'.repeat(21846));await expect(node.getByRole('alert')).toContainText('64KiB');await page.reload();await expect(field).toHaveValue('新的原创镜头');expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T14-C01/C02: explicit ordered inputs persist through layout; disconnect never rewrites Run',async({page,networkCounter})=>{
 const node=page.getByTestId('node-video-1');await node.getByRole('button',{name:'选择输入',exact:true}).click();const dialog=page.getByRole('dialog',{name:'选择输入'});await dialog.getByRole('button',{name:'连接 参考一',exact:true}).click();await node.getByRole('button',{name:'选择输入',exact:true}).click();await dialog.getByRole('button',{name:'连接 参考二',exact:true}).click();await node.getByRole('button',{name:'查看输入快照',exact:true}).click();const snapshot=page.getByRole('dialog',{name:'输入快照'});await expect(snapshot.getByTestId('input-order')).toHaveText(/1.*参考一.*2.*参考二/s);await snapshot.getByRole('button',{name:'关闭',exact:true}).click();await node.getByRole('button',{name:'上移 参考二'}).click();await expect(node.getByTestId('input-list').locator('li').first()).toContainText('参考二');await node.getByRole('button',{name:'断开 参考一'}).click();await expect(node.getByTestId('input-list').locator('li')).toHaveCount(1);expect(networkCounter.paidRequests).toHaveLength(0);
});
test('T14-C03: result node displays fixed asset and run; preview does not replace history',async({page})=>{
 await page.getByRole('button',{name:'定位 固定结果',exact:true}).click();const result=page.getByTestId('node-result-1');await expect(result.getByText('素材 a3',{exact:true})).toBeVisible();await expect(result.getByText('视频-19700101-080001-R1',{exact:true})).toBeVisible();await expect(result.getByText('视频-19700101-080001-R1',{exact:true})).toHaveAttribute('title','任务ID：r1');await expect(result.getByRole('button',{name:'生成'})).toHaveCount(0);await page.screenshot({path:'docs/review/screenshots/T14-typed-nodes.png'});
});
test('T14 N02/T02: title validates Unicode length and display font does not edit content',async({page})=>{
 const node=page.getByTestId('node-text-1');await node.getByTestId('node-handle').dblclick();const dialog=page.getByRole('dialog',{name:'编辑节点标题'});await dialog.getByLabel('节点标题',{exact:true}).fill('中'.repeat(61));await dialog.getByRole('button',{name:'保存',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('1–60');await dialog.getByLabel('节点标题',{exact:true}).fill('镜头正文');await dialog.getByRole('button',{name:'保存',exact:true}).click();await expect(node.getByTestId('node-handle')).toContainText('镜头正文');await node.getByLabel('文本字号').selectOption('20');await expect(node.getByLabel('节点文本')).toHaveCSS('font-size','20px');await expect(node.getByLabel('节点文本')).toHaveValue('原创镜头');
});
test('T14 N13: ports support keyboard and pointer equivalents; invalid type stays unconnected',async({page})=>{await page.getByTestId('node-text-1').getByRole('button',{name:'输出文本',exact:true}).click();const video=page.getByTestId('node-video-1');await video.getByRole('button',{name:'接收图片',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'类型不匹配'})).toBeVisible();await expect(video.getByTestId('input-list').locator('li')).toHaveCount(0);await page.getByTestId('node-text-1').getByRole('button',{name:'输出文本',exact:true}).click();await video.getByRole('button',{name:'接收文本',exact:true}).click();await expect(video.getByTestId('input-list').locator('li')).toHaveCount(1);});
test('T14 node creation: local asset and fixed result references use existing identities',async({page,networkCounter})=>{await page.getByRole('button',{name:'添加节点',exact:true}).click();await page.getByRole('button',{name:'素材节点',exact:true}).click();await page.getByRole('dialog',{name:'选择素材节点'}).getByRole('button',{name:'插入 参考一',exact:true}).click();await expect(page.locator('[data-node-type="asset"]')).toHaveCount(3);await page.getByRole('button',{name:'添加节点',exact:true}).click();await page.getByRole('button',{name:'结果引用节点',exact:true}).click();await page.getByRole('dialog',{name:'选择结果引用'}).getByRole('button',{name:'引用 固定结果素材',exact:true}).click();await expect(page.locator('[data-node-type="result"]')).toHaveCount(2);expect(networkCounter.paidRequests).toHaveLength(0);});
test('T14 tab identity: a duplicated session identity is fenced, while reload keeps the original writer',async({page,context})=>{await expect(page.getByTestId('node-text-1').getByLabel('节点文本')).toBeEditable();const firstId=await page.evaluate(()=>sessionStorage.getItem('aiwork-studio:tab-id'));const other=await context.newPage();await other.addInitScript(id=>sessionStorage.setItem('aiwork-studio:tab-id',id!),firstId);await other.goto('/projects/p1/canvas');await expect(other.getByText('只读 · 另一标签持有写权')).toBeVisible();expect(await other.evaluate(()=>sessionStorage.getItem('aiwork-studio:tab-id'))).not.toBe(firstId);await page.reload();await expect(page.getByTestId('node-text-1').getByLabel('节点文本')).toBeEditable();expect(await page.evaluate(()=>sessionStorage.getItem('aiwork-studio:tab-id'))).toBe(firstId);await other.close();});
test('T14 N13: real pointer drag from text output to text input creates one dependency',async({page})=>{const from=await page.getByTestId('node-text-1').getByRole('button',{name:'输出文本',exact:true}).boundingBox(),to=await page.getByTestId('node-video-1').getByRole('button',{name:'接收文本',exact:true}).boundingBox();await page.mouse.move(from!.x+from!.width/2,from!.y+from!.height/2);await page.mouse.down();await page.mouse.move(to!.x+to!.width/2,to!.y+to!.height/2,{steps:6});await page.mouse.up();await expect(page.getByTestId('node-video-1').getByTestId('input-list').locator('li')).toHaveCount(1);});
test('T14 identity fallback: without Web Locks a copied session cannot reuse another writer identity',async({page,context})=>{await expect(page.getByTestId('node-text-1').getByLabel('节点文本')).toBeEditable();const firstId=await page.evaluate(()=>sessionStorage.getItem('aiwork-studio:tab-id'));const other=await context.newPage();await other.addInitScript(id=>{sessionStorage.setItem('aiwork-studio:tab-id',id!);Object.defineProperty(navigator,'locks',{value:undefined,configurable:true});},firstId);await other.goto('/projects/p1/canvas');await expect(other.getByText('只读 · 另一标签持有写权')).toBeVisible();expect(await other.evaluate(()=>sessionStorage.getItem('aiwork-studio:tab-id'))).not.toBe(firstId);await other.close();});
