import {test,expect} from '../helpers/network-guard';
import {seedStudio} from '../helpers/seed-studio';
test.use({actionTimeout:2500});test.setTimeout(20000);
test.beforeEach(async({page})=>{await seedStudio(page,'unverified-capability');await page.evaluate(async()=>{const path='/tests/fixtures/generation.ts';await (await import(path)).seedGeneration();});await page.goto('/projects/p1/canvas');await expect(page.getByTestId('node-text-1').getByLabel('节点文本')).toBeEditable();await page.evaluate(async()=>{const path='/tests/fixtures/generation.ts';await (await import(path)).connectGeneration();});});
test('T27 actual UI: confirming frozen inputs sends exactly one same-origin fake video request after intent is durable',async({page,networkCounter})=>{
 let dispatchState:string|undefined,body:string|undefined;
 await page.route('**/core-api/v1/videos/generations',async route=>{body=route.request().postData()??undefined;dispatchState=await page.evaluate(async()=>{const path='/src/infrastructure/storage/database.ts',m=await import(path);return m.withDatabase(undefined,(db:import('../../src/infrastructure/storage/database').StudioDb)=>m.transact(db,['runs'],'readonly',async(tx:IDBTransaction)=>(await m.requestResult(tx.objectStore('runs').getAll()))[0].executionState));});await route.fulfill({status:202,contentType:'application/json',body:JSON.stringify({task:{id:'mock-ui-video-1',status:'queued'},request_id:'mock-ui-request-1'})});});
 await page.getByTestId('node-video-1').locator('[data-interaction-id="V-08"]').click();const dialog=page.getByRole('dialog',{name:'生成确认单'});expect(networkCounter.paidRequests).toHaveLength(0);await dialog.getByLabel('我确认以上输入，并知悉可能消耗积分且金额未知').check();await dialog.getByRole('button',{name:'确认提交 1 项',exact:true}).click();await expect(page.getByText('已提交 1 项 · 追踪中',{exact:true})).toBeVisible();expect(dispatchState).toBe('submitting');expect(JSON.parse(body!)).toEqual({model:'fake-video-only',prompt:'原创确认正文',duration:5,ratio:'9:16'});expect(networkCounter.paidRequests).toHaveLength(1);
});
test('T27 D21: lost actual browser response preserves unknown state, original identity and disabled unverified replay',async({page,networkCounter})=>{await page.route('**/core-api/v1/videos/generations',route=>route.abort('connectionclosed'));await page.getByTestId('node-video-1').locator('[data-interaction-id="V-08"]').click();const dialog=page.getByRole('dialog',{name:'生成确认单'});await dialog.getByLabel('我确认以上输入，并知悉可能消耗积分且金额未知').check();await dialog.getByRole('button',{name:'确认提交 1 项',exact:true}).click();const unknown=page.getByRole('dialog',{name:'任务未知结果'});await expect(unknown).toBeVisible();await expect(unknown).toContainText('原请求');await expect(unknown.getByRole('button',{name:'重放原请求',exact:true})).toBeDisabled();expect(networkCounter.paidRequests).toHaveLength(1);await page.screenshot({path:'docs/review/screenshots/T27-submit-unknown.png'});await unknown.getByRole('button',{name:'暂存待核对',exact:true}).click();expect(networkCounter.paidRequests).toHaveLength(1);});
test('T27 V-14: a deliberate new attempt warns about the unknown prior charge and requires separate risk acknowledgment',async({page,networkCounter})=>{await page.route('**/core-api/v1/videos/generations',route=>route.abort('connectionclosed'));const open=()=>page.getByTestId('node-video-1').locator('[data-interaction-id="V-08"]').click();await open();let dialog=page.getByRole('dialog',{name:'生成确认单'});await dialog.getByLabel('我确认以上输入，并知悉可能消耗积分且金额未知').check();await dialog.getByRole('button',{name:'确认提交 1 项',exact:true}).click();await page.getByRole('dialog',{name:'任务未知结果'}).getByRole('button',{name:'暂存待核对',exact:true}).click();await open();dialog=page.getByRole('dialog',{name:'生成确认单'});await expect(dialog).toContainText('原任务结果仍不明');await dialog.getByLabel('我确认以上输入，并知悉可能消耗积分且金额未知').check();await expect(dialog.getByRole('button',{name:'确认提交 1 项',exact:true})).toBeDisabled();await dialog.getByLabel('我明确要创建新尝试，已知原任务可能仍在执行且可能再次计费').check();await expect(dialog.getByRole('button',{name:'确认提交 1 项',exact:true})).toBeEnabled();await dialog.getByRole('button',{name:'返回编辑',exact:true}).click();expect(networkCounter.paidRequests).toHaveLength(1);});
test('T27 D21: after a response save fault the durable journal enables querying the known original task without resubmission',async({page,networkCounter})=>{await page.route('**/core-api/v1/videos/generations',route=>route.fulfill({status:202,contentType:'application/json',body:JSON.stringify({task:{id:'mock-journal-video-1',status:'queued'}})}));await page.route('**/core-api/v1/videos/mock-journal-video-1',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({task:{id:'mock-journal-video-1',status:'completed',content_url:'/core-api/v1/videos/mock-journal-video-1/content'}})}));await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<typeof original>){if(this.name==='runs'&&(args[0] as {executionState?:string}).executionState==='accepted'){IDBObjectStore.prototype.put=original;throw new DOMException('injected response save','QuotaExceededError');}return original.apply(this,args);};});await page.getByTestId('node-video-1').locator('[data-interaction-id="V-08"]').click();const confirm=page.getByRole('dialog',{name:'生成确认单'});await confirm.getByLabel('我确认以上输入，并知悉可能消耗积分且金额未知').check();await confirm.getByRole('button',{name:'确认提交 1 项',exact:true}).click();const unknown=page.getByRole('dialog',{name:'任务未知结果'});await expect(unknown).toBeVisible();await expect(unknown.getByRole('button',{name:'查询原任务',exact:true})).toBeEnabled();await unknown.getByRole('button',{name:'查询原任务',exact:true}).click();await expect(unknown).not.toBeVisible();await expect(page.getByText('原任务已恢复 · 继续追踪',{exact:true})).toBeVisible();expect(networkCounter.paidRequests).toHaveLength(1);expect(networkCounter.requests.filter(r=>r.method==='GET'&&r.url.endsWith('/v1/videos/mock-journal-video-1'))).toHaveLength(1);});
