import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {unzipSync,strFromU8} from 'fflate';
const index=()=>JSON.parse(fs.readFileSync('docs/review/task-evidence-index.json','utf8'));
test('T50 fifty task records point to actual evidence, commits and executed command logs',()=>{
 const x=index();assert.equal(x.tasks.length,50);assert.equal(new Set(x.tasks.map(t=>t.id)).size,50);
 for(const task of x.tasks){assert.ok(fs.existsSync(task.evidence));const e=JSON.parse(fs.readFileSync(task.evidence,'utf8'));assert.equal(e.taskId,task.id);assert.ok(Array.isArray(e.commands)&&e.commands.length>0);assert.equal(task.commandEvidence.length,e.commands.length);assert.ok(task.commandEvidence.some(c=>c.verifiedLog));for(const [position,command]of e.commands.entries()){assert.equal(typeof command.command,'string');const audit=task.commandEvidence[position];assert.equal(audit.command,command.command);assert.equal(audit.exitCode,command.exitCode);if(audit.verifiedLog){assert.equal(Number.isInteger(command.exitCode),true);assert.ok(audit.logs.length>0);for(const log of audit.logs)assert.ok(fs.existsSync(log));}else{assert.ok(audit.reason);assert.notEqual(audit.status,'PASS');}if(audit.status==='PASS'){assert.equal(command.exitCode,0);assert.equal(command.failed??0,0);assert.notEqual(command.passed,0);assert.equal(audit.verifiedLog,true);}}if(task.commit)assert.match(execFileSync('git',['rev-parse','--verify',task.commit+'^{commit}'],{encoding:'utf8'}).trim(),/^[0-9a-f]{40}$/);assert.notEqual(task.status,'独立审查通过');}
});
test('T50 live, collaboration, release and review limitations cannot be misrepresented as accepted',()=>{
 const x=index();assert.equal(x.liveVerified,false);assert.equal(x.actualBusinessCalls,0);assert.notEqual(x.releaseStatus,'正式发布通过');assert.equal(x.independentReviewPerformed,false);assert.equal(x.userAccepted,false);assert.equal(x.blockingDefectsVerifiedZero,false);assert.equal(x.scopes.live.status,'待额外授权与真实验证');assert.equal(x.scopes.collaboration.modelHostVerified,false);assert.equal(x.scopes.release.frontendMarkPermission,'unresolved');assert.ok(x.unresolvedGates.includes('T02 全视觉用户认可'));assert.ok(x.unresolvedGates.includes('T48 真实 Core/收费联调'));assert.ok(fs.existsSync(x.auditChecklist));
});
test('T50 archive byte hashes and committed source correspond and contain no unapproved release claim',()=>{
 const x=index();assert.ok(x.artifact?.report);const report=JSON.parse(fs.readFileSync(x.artifact.report,'utf8')),bytes=fs.readFileSync(report.output),sha=createHash('sha256').update(bytes).digest('hex');assert.equal(sha,report.sha256);assert.equal(sha,x.artifact.sha256);const files=unzipSync(bytes),manifest=JSON.parse(strFromU8(files['distribution-manifest.json']));assert.equal(manifest.sourceCommit,x.sourceCommit);assert.equal(manifest.dirtySources,false);assert.equal(manifest.kind,'offline-review');assert.equal(manifest.formalReleaseApproved,false);assert.equal(manifest.liveVerified,false);for(const file of manifest.files){assert.equal(files[file.file].byteLength,file.bytes);assert.equal(createHash('sha256').update(files[file.file]).digest('hex'),file.sha256);}for(const file of ['scripts/serve-local.mjs','scripts/start-canvas.ps1','scripts/start-companion.ps1','src/adapters/core/route-policy.ts','deploy/nginx-canvas.conf']){const committed=execFileSync('git',['show',x.sourceCommit+':'+file],{encoding:'utf8'});assert.equal(strFromU8(files[file]).replaceAll('\r\n','\n'),committed.replaceAll('\r\n','\n'));}assert.match(execFileSync('git',['rev-parse','--verify',x.sourceCommit+'^{commit}'],{encoding:'utf8'}).trim(),/^[0-9a-f]{40}$/);
});
test('T50 interaction proof is actual assertion and action coverage, not screenshots alone',()=>{
 const x=index();assert.ok(x.coverage?.report);const report=JSON.parse(fs.readFileSync(x.coverage.report,'utf8'));assert.equal(report.complete,true);assert.deepEqual(report.errors,[]);assert.equal(x.coverage.interactions,260);assert.equal(x.coverage.pages,23);assert.equal(x.coverage.dialogs,30);assert.ok(x.coverage.executedBrowserReport);const run=JSON.parse(fs.readFileSync(x.coverage.executedBrowserReport,'utf8'));assert.equal(run.status,'passed');assert.ok(run.tests.length>=412);assert.equal(run.tests.filter(t=>t.status!=='passed').length,0);assert.ok(run.tests.some(t=>t.actions>0&&t.assertions>0&&t.network));
});
