import {useEffect,useRef,useState} from 'react';
import type {Graph} from '../../domain/graph';
import type {Proposal} from '../../domain/proposal';
import type {AgentSession} from '../../domain/agent-session';
import {localText} from '../../domain/common';
import {readGraph} from '../../infrastructure/storage/project-repository';
import {connectAgent,connectOnlineAgent,isOnlineAgent,disconnectAgent,getProjectAgentSession,getOpenedCanvasIdentity,getOpenedCanvasSelection} from './agent-client';
import {subscribeAgentChanges} from './agent-events';
import {ContextPicker,resolvedContext,type AgentContext} from './ContextPicker';
import {AgentPermissionDialog} from './AgentPermissionDialog';
import {AgentHistory} from './AgentHistory';
import {ProposalReview} from './ProposalReview';
import {createLocalAgentConversation,bindLocalAgentConversation,saveLocalAgentNote,deleteLocalAgentConversation,type AgentConversation} from './agent-history';
import {getIndependentText,subscribeTextConnection} from '../../adapters/text/current-text';
import {prepareOnlineAgent,sendOnlineAgent,type OnlineAgentPreview} from './online-agent';
import {LocalLink} from '../../app/routes';
import {Dialog} from '../../ui/Dialog';
import {Button} from '../../ui/Button';
export function AgentPanel({projectId,onClose,onApplied,canApply=true}:{projectId:string;onClose?:()=>void;onApplied?:()=>Promise<void>;canApply?:boolean}){
 const [graph,setGraph]=useState<Graph>(),[selection,setSelection]=useState<string[]>([]),[session,setSession]=useState<AgentSession>(),[writer,setWriter]=useState(false),[pairOpen,setPairOpen]=useState(false),[permissionOpen,setPermissionOpen]=useState(false),[endpoint,setEndpoint]=useState('http://127.0.0.1:4181'),[context,setContext]=useState<AgentContext>({scope:'selection',nodeIds:[]}),[tab,setTab]=useState<'会话'|'建议'|'记录'>('会话'),[review,setReview]=useState<Proposal>(),[description,setDescription]=useState(''),[conversationId,setConversationId]=useState(''),[deleteConversation,setDeleteConversation]=useState<AgentConversation>(),[abandon,setAbandon]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[connecting,setConnecting]=useState(false);
 const tokenField=useRef<HTMLInputElement>(null),sending=useRef(false),controller=useRef<AbortController|undefined>(undefined);
 const [modelVersion,setModelVersion]=useState(0),[onlinePreview,setOnlinePreview]=useState<OnlineAgentPreview>(),[textFee,setTextFee]=useState(false),[unknownAck,setUnknownAck]=useState(false),[onlineBusy,setOnlineBusy]=useState(false);void modelVersion;useEffect(()=>subscribeTextConnection(()=>setModelVersion(v=>v+1)),[]);useEffect(()=>()=>controller.current?.abort(),[]);const online=!!session&&isOnlineAgent(session.id),textConnection=getIndependentText();
 useEffect(()=>{let alive=true;async function sync(){if(!alive)return;const active=getProjectAgentSession(projectId);setSession(current=>JSON.stringify(current)===JSON.stringify(active)?current:active);try{await getOpenedCanvasIdentity(projectId);if(alive)setWriter(true);}catch{if(alive)setWriter(false);}try{const ids=await getOpenedCanvasSelection(projectId);if(alive)setSelection(current=>JSON.stringify(current)===JSON.stringify(ids)?current:ids);}catch{if(alive)setSelection([]);}}void sync();const timer=setInterval(()=>void sync(),1000),unsubscribe=subscribeAgentChanges(()=>void sync());void readGraph(projectId).then(g=>{if(alive)setGraph(g);}).catch(()=>{if(alive)setError('上下文读取失败，请刷新上下文。');});return()=>{alive=false;clearInterval(timer);unsubscribe();};},[projectId]);
 const selectedIds=resolvedContext(context,graph,selection),authorized=!!session?.connected&&session.grant.expiresAt>Date.now(),scopeLabel=session?.grant.scope==='project'?'整个项目':session?.grant.scope==='nodes'?'指定节点':'当前选区',accessLabel=session?.grant.access==='propose'?'允许提案':'只读';
 async function fresh(){setGraph(await readGraph(projectId));try{setSelection(await getOpenedCanvasSelection(projectId));}catch{setSelection([]);}}
 async function newConversation(){try{const row=await createLocalAgentConversation(projectId);setConversationId(row.id);setDescription('');if(session)await bindLocalAgentConversation(row.id,session.id);setMessage('已创建空本地会话；画布和旧提案保留。');}catch{setError('本地会话或关联索引未保存，请重新读取，画布保持原样。');}}
 async function disconnect(stopped=false){controller.current?.abort();setOnlinePreview(undefined);let acknowledged=true;if(session)try{await disconnectAgent(session.id);}catch{acknowledged=false;}if(tokenField.current)tokenField.current.value='';setSession(undefined);setMessage(stopped?'已停止本地上下文传输。宿主未提供停止协议，宿主回合状态未知；原 Core 视频继续追踪，不代表取消或退款。':acknowledged?'已断开':'本地已断开；服务撤权回执未知，旧连接按失联规则失效。');}
 return <aside className="agent-panel" aria-label="Agent 协作面板"><header className="agent-panel-heading"><h2>Agent 协作</h2>{onClose?<Button data-interaction-id="ui:AgentPanel:Button:c7fdbecd0a78" aria-label="关闭 Agent 面板" onClick={onClose}>×</Button>:null}</header><p role="status">{connecting?'连接中…':authorized?(session?.grant.scope==='selection'&&!session.grant.nodeIds.length?'已连接 · 只读':'已授权 · '+scopeLabel+' · '+accessLabel):'当前标签没有 Agent 授权'}</p>{session?<p className="break-word">会话 ID：{session.id}<br/>授权到期：{new Date(session.grant.expiresAt).toLocaleString('zh-CN')}</p>:null}<div className="actions"><Button data-interaction-id="A-01" disabled={!writer||connecting||authorized} disabledReason={!writer?'当前标签没有有效写者租约，请在画布明确接管。':authorized?'已连接，请先断开再更换连接。':undefined} onClick={()=>{setPairOpen(true);setError('');}}>连接本地 Agent</Button><Button data-interaction-id="A-12" disabled={!session} onClick={()=>disconnect()}>断开并撤销授权</Button></div><p>Agent 提案是模型建议的画布修改，先审阅再应用；接受提案不会授权视频生成。</p><Button data-interaction-id="agent:connect-online" disabled={!writer||connecting||authorized||!textConnection} disabledReason="请先在设置中启用独立文字 API，并取得当前画布写权。" onClick={async()=>{setConnecting(true);try{const connected=await connectOnlineAgent(projectId);setSession(connected);setMessage('已连接线上文字模型 · 默认只读；请预览并管理授权，再发送任务。');}catch{setError('线上文字连接不可用，请核对文字 Key 与画布写权。');}finally{setConnecting(false);}}}>连接线上文字模型</Button><LocalLink data-interaction-id="agent:text-settings" href="/settings/connections">配置独立文字 API</LocalLink><p>线上模型协助文字和位置提案；其他工具协作通过下方本机通道。连接与授权本身不调用模型。</p><p>外部模型宿主尚未验收</p><p>请明确启动本机 companion，再用其独立临时令牌配对；不能填 Core Key，不自动安装插件或启动模型。</p><ContextPicker graph={graph} selection={selection} value={context} onChange={setContext}/><div className="actions"><Button data-interaction-id="ui:AgentPanel:Button:1320224afce8" onClick={async()=>{try{await fresh();setMessage('上下文已刷新；既有授权范围保持原样。');}catch{setError('上下文读取失败，请保留原提案。');}}}>刷新上下文</Button><Button data-interaction-id="ui:AgentPanel:Button:c6fc490c55a4" disabled={!authorized} onClick={async()=>{try{await fresh();setPermissionOpen(true);}catch{setError('无法读取当前上下文，未打开授权。');}}}>预览并管理授权</Button></div><div role="tablist" aria-label="Agent 内容">{(['会话','建议','记录'] as const).map(t=><Button data-interaction-id="ui:AgentPanel:Button:a1f780f0dbc8" role="tab" key={t} aria-selected={tab===t} onClick={()=>setTab(t)}>{t}</Button>)}</div><AgentHistory projectId={projectId} tab={tab} conversationId={conversationId} onConversation={setConversationId} onReview={setReview} onNew={newConversation} onDelete={c=>{setDeleteConversation(c);setAbandon(false);}}/>
 <label>任务描述<textarea data-interaction-id="ui:AgentPanel:textarea:fd01057c9fce" aria-label="任务描述" value={description} onChange={e=>setDescription(e.target.value)} placeholder="先查看上下文，再在已验收宿主中明确发送任务描述"/></label><p>模型由外部宿主选择；成本未知，发送描述可能产生文字模型费用。</p><div className="actions"><Button data-interaction-id="ui:AgentPanel:Button:54c4baa5d90e" disabled={!description.trim()||!localText.safeParse(description).success} onClick={async()=>{try{let id=conversationId;if(!id){const row=await createLocalAgentConversation(projectId);id=row.id;setConversationId(id);if(session)await bindLocalAgentConversation(id,session.id);}await fresh();const saved=await readGraph(projectId);if(!saved)throw Error('graph_missing');await saveLocalAgentNote(id,description,{scope:context.scope,nodeIds:resolvedContext(context,saved,await getOpenedCanvasSelection(projectId).catch(()=>[])),revision:saved.revision});setDescription('');setMessage('任务描述已保存到本地，尚未发送至模型宿主。');}catch{setError('本地描述未保存，请保留输入并重试。');}}}>保存本地描述</Button><Button data-interaction-id="A-04" disabled={!online||!authorized||session?.grant.access!=='propose'||!description.trim()||onlineBusy} disabledReason="线上模型需要允许提案、已授权节点和文字费用确认；本机宿主仍由宿主侧发送。" onClick={async()=>{if(!session||onlineBusy)return;try{await fresh();setTextFee(false);setUnknownAck(false);setOnlinePreview(await prepareOnlineAgent(session.id,description));}catch{setError('文字预览受阻，请先保存画布、授权所选节点并检查文字连接。');}}}>发送任务描述</Button><Button data-interaction-id="A-11" disabled={!session} onClick={()=>disconnect(true)}>请求停止 Agent 回合</Button></div>{message?<p role={message.includes('宿主回合状态未知')?'alert':'status'}>{message}</p>:null}{error?<p role="alert">{error}</p>:null}
 <Dialog open={!!onlinePreview} title="线上 Agent 文字请求确认" onClose={()=>setOnlinePreview(undefined)} dismissible={!onlineBusy} footer={<Button data-interaction-id="agent:confirm-text" disabled={!onlinePreview||!textFee||onlineBusy||!!onlinePreview.priorUnknownIds.length&&!unknownAck} onClick={async()=>{if(!onlinePreview||!textFee||sending.current)return;sending.current=true;setOnlineBusy(true);const requestController=new AbortController();controller.current=requestController;const timer=setTimeout(()=>requestController.abort(),60000);try{const result=await sendOnlineAgent(onlinePreview,{confirmed:true,acknowledgePriorUnknown:unknownAck},requestController.signal);setOnlinePreview(undefined);setMessage(result.status==='proposed'?'线上模型提案已保存，尚未改动画布。':result.status==='advice'?'线上文字建议：'+result.message:result.status==='invalid_result'?'原响应已保存，但格式、范围或授权校验未通过，未改动画布。':(result.message?result.message+' ':'')+'文字响应未知；原请求已保留，不会自动重发，不代表退款。');}catch(error){setError(error instanceof Error&&error.message==='agent_preview_expired'?'文字请求预览已过期：画布、授权或文字连接已变化。请重新预览并确认；本轮未发送文字请求。':'文字请求或保存未确认完成；请保留原请求记录，不自动重试。');setOnlinePreview(undefined);}finally{clearTimeout(timer);controller.current=undefined;sending.current=false;setOnlineBusy(false);}}}>确认发送文字请求</Button>}><p>服务：{textConnection?.client.profile.name} · 模型：{textConnection?.capability.textModels.join('、')}。可能产生文字费用，金额未知。仅发送下列文字，不上传素材文件。</p><pre className="request-preview">{onlinePreview?.body}</pre><label className="generation-ack"><input data-interaction-id="agent:text-fee" type="checkbox" checked={textFee} disabled={onlineBusy} onChange={e=>setTextFee(e.target.checked)}/>我确认文字请求及可能产生的费用</label>{onlinePreview?.priorUnknownIds.length?<label className="generation-ack"><input data-interaction-id="agent:unknown-ack" type="checkbox" checked={unknownAck} onChange={e=>setUnknownAck(e.target.checked)}/>旧文字请求结果未知；我已核对并确认新请求可能再次产生费用</label>:null}</Dialog>
 <Dialog open={pairOpen} title="连接本地 Agent" onClose={()=>{setPairOpen(false);setError('');if(tokenField.current)tokenField.current.value='';}} dismissible={!connecting} footer={<Button data-interaction-id="ui:AgentPanel:Button:6f3763e1bf8a" busy={connecting} variant="primary" onClick={async()=>{setConnecting(true);try{const identity=await getOpenedCanvasIdentity(projectId),connected=await connectAgent({...identity,endpoint,token:tokenField.current?.value??'',origin:location.origin});if(tokenField.current)tokenField.current.value='';setSession(connected);setPairOpen(false);setMessage('');if(conversationId)await bindLocalAgentConversation(conversationId,connected.id).catch(()=>setError('连接已建立，本地会话关联索引未保存，请重试本地记录。'));}catch{setError('连接失败，请检查本机地址、独立令牌、当前网页与写权；没有申请额外系统权限。');}finally{setConnecting(false);}}}>连接并默认只读</Button>}><label>本机连接地址<input data-interaction-id="ui:AgentPanel:input:2aa75e14d573" aria-label="本机连接地址" value={endpoint} onChange={e=>setEndpoint(e.target.value)} autoComplete="off"/></label><label>独立临时配对令牌<input data-interaction-id="ui:AgentPanel:input:2c6d0dee68a9" ref={tokenField} aria-label="独立临时配对令牌" type="password" autoComplete="off" spellCheck={false}/></label><p>仅当前标签内存；配对后输入立即清空。首连默认只读且没有全项目访问；费用与模型选择不由此授权。</p>{error?<p role="alert">{error}</p>:null}</Dialog>
 {permissionOpen&&session?<AgentPermissionDialog session={session} context={context} nodeIds={selectedIds} graph={graph} onClose={()=>setPermissionOpen(false)}/>:null}{review?<ProposalReview proposal={review} canApply={canApply&&writer} onClose={()=>setReview(undefined)} onChanged={async()=>{await fresh();await onApplied?.();setMessage('提案决定已保存；请在建议或记录中查看当前状态。');}}/>:null}
 <Dialog open={!!deleteConversation} title="删除本地 Agent 会话" onClose={()=>setDeleteConversation(undefined)} footer={<><Button data-interaction-id="ui:AgentPanel:Button:a3e873fe4a20" onClick={()=>setDeleteConversation(undefined)}>保留会话</Button><Button data-interaction-id="ui:AgentPanel:Button:66a2418c1de2" variant="danger" disabled={!abandon} onClick={async()=>{if(!deleteConversation)return;try{await disconnect();await deleteLocalAgentConversation(deleteConversation.id,true);if(conversationId===deleteConversation.id)setConversationId('');setDeleteConversation(undefined);setMessage('本地会话与描述已删除；提案、批准记录和原任务保留。');}catch{setError('本地会话未确认删除，请重新读取。');}}}>确认删除本地会话</Button></>}><p>删除本地描述与会话索引，并断开当前授权。未处理提案和批准记录保留；不声明删除远端模型记录，也不取消视频。</p><label className="generation-ack"><input data-interaction-id="ui:AgentPanel:input:bea4223ae450" type="checkbox" checked={abandon} onChange={e=>setAbandon(e.target.checked)}/>我确认删除这些本地对话记录</label></Dialog>
 </aside>;
}
