import {useEffect,useState} from 'react';
import type {Proposal} from '../../domain/proposal';
import {listProjectProposals} from '../../application/proposals/apply-proposal';
import {listLocalAgentHistory,type AgentConversation} from './agent-history';
import {subscribeAgentChanges} from './agent-events';
import {Button} from '../../ui/Button';
import {sanitizeKnownSecrets} from '../../security/credential-session';
const labels:Record<string,string>={proposed:'待审阅',applied:'已应用',rejected:'已拒绝',conflict:'版本冲突'};
export function AgentHistory({projectId,tab,conversationId,onConversation,onReview,onNew,onDelete}:{projectId:string;tab:'会话'|'建议'|'记录';conversationId:string;onConversation:(id:string)=>void;onReview:(proposal:Proposal)=>void;onNew:()=>Promise<void>;onDelete:(conversation:AgentConversation)=>void}){const [history,setHistory]=useState<Awaited<ReturnType<typeof listLocalAgentHistory>>>({conversations:[],notes:[],decisions:[]}),[proposals,setProposals]=useState<Proposal[]>([]),[showText,setShowText]=useState(false),[error,setError]=useState('');async function refresh(){try{const [h,p]=await Promise.all([listLocalAgentHistory(projectId),listProjectProposals(projectId)]);setHistory(h);setProposals(p);setError('');}catch{setError('Agent 本地记录读取失败，请重新读取。');}}useEffect(()=>{let alive=true;const load=async()=>{try{const [h,p]=await Promise.all([listLocalAgentHistory(projectId),listProjectProposals(projectId)]);if(alive){setHistory(h);setProposals(p);}}catch{if(alive)setError('Agent 本地记录读取失败，请重新读取。');}};void load();const unsubscribe=subscribeAgentChanges(()=>void load());return()=>{alive=false;unsubscribe();};},[projectId]);return <section><Button onClick={refresh}>{tab==='建议'?'刷新建议':'刷新本地记录'}</Button>{error?<p role="alert">{error}</p>:null}{tab==='建议'?<>{!proposals.length?<p>正在等待结构化提案；不会自动应用。</p>:proposals.map(p=><div className="agent-history-item" key={p.id}><p>{labels[p.status]+' · '+sanitizeKnownSecrets(p.id)}</p><p>基于修订 {p.baseRevision} · {p.operations.length} 项操作</p><Button aria-label={'审阅提案 '+p.id} onClick={()=>onReview(p)}>审阅提案</Button>{p.status==='conflict'?<p>请基于当前修订重新提出新 ID 的提案；旧提案不覆盖。</p>:null}</div>)}</>:<><label>本地会话<select aria-label="本地会话" value={conversationId} onChange={e=>onConversation(e.target.value)}><option value="">选择本地会话</option>{history.conversations.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><div className="actions"><Button data-interaction-id="A-13" onClick={onNew}>新本地会话</Button><Button data-interaction-id="A-14" disabled={!conversationId} onClick={()=>{const c=history.conversations.find(c=>c.id===conversationId);if(c)onDelete(c);}}>删除本地会话</Button></div><label className="agent-checkbox"><input type="checkbox" checked={showText} onChange={e=>setShowText(e.target.checked)}/>显示任务描述</label>{history.notes.filter(n=>n.conversationId===conversationId).map(n=><div key={n.id} className="agent-history-item"><p>本地描述 · 修订 {n.context.revision} · {n.context.nodeIds.length} 个节点 · {new Date(n.createdAt).toLocaleString('zh-CN')}</p>{showText?<pre>{sanitizeKnownSecrets(n.body)}</pre>:<p>正文已隐藏</p>}<p>尚未发送至模型宿主。</p></div>)}{tab==='记录'?<div data-interaction-id="A-15"><h3>提案决策</h3>{history.decisions.map((d,i)=><p key={d.proposalId+':'+i}>{sanitizeKnownSecrets(d.proposalId)} · {d.decision==='applied'?'已应用':'已拒绝'}{d.count?' · '+d.count+' 项':''} · {new Date(d.createdAt).toLocaleString('zh-CN')}</p>)}<p>这是本地创作记录，Core 财务与远端模型记录由原服务管理。</p></div>:null}</> }</section>;}
