import {handleCanvasTool,type CanvasToolBridge} from '../../../companion/src/mcp';
import {toolEnvelopeSchema} from '../../../companion/src/tool-inbox';
import {agentSessionSchema,agentGrantSchema,type AgentSession,type AgentGrant,type AgentConnectInput,type CanvasIdentity} from '../../domain/agent-session';
import {validateAgentEndpoint} from '../../../companion/src/origin-policy';
import {registerDiagnosticSecret} from '../../security/credential-session';
export type OpenedCanvas={identity:()=>Promise<CanvasIdentity|undefined>;toolBridge?:CanvasToolBridge};
let opened:OpenedCanvas|undefined;
type Connection={identity:CanvasIdentity;endpoint:string;token:string;browserNonce:string;origin:string;session:AgentSession;stopTools?:()=>void};
const connections=new Map<string,Connection>();
export function registerOpenedCanvas(canvas:OpenedCanvas){const previous=opened;opened=canvas;return()=>{if(opened===canvas){opened=previous;for(const [id,record]of connections)if(record.session.connected)void disconnectAgent(id).catch(()=>{});}};}
async function identity(projectId:string){const current=await opened?.identity();if(!current||current.projectId!==projectId)throw Error('canvas_not_connected');return current;}
export const getOpenedCanvasIdentity=identity;
async function request(endpoint:string,token:string,origin:string,path:string,body:unknown,nonce?:string){const response=await fetch(endpoint+path,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',Origin:origin,...(nonce?{'X-Studio-Browser':nonce}:{})},body:JSON.stringify(body),credentials:'omit',redirect:'error',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(5000)});if(Number(response.headers.get('content-length'))>262144)throw Error('agent_response_too_large');const reader=response.body?.getReader();if(!reader)throw Error('agent_response_invalid');let text='',size=0;const decoder=new TextDecoder('utf-8',{fatal:true});try{while(true){const part=await reader.read();if(part.done)break;size+=part.value.byteLength;if(size>262144){await reader.cancel();throw Error('agent_response_too_large');}text+=decoder.decode(part.value,{stream:true});}text+=decoder.decode();}finally{reader.releaseLock();}const reply=JSON.parse(text) as {ok?:boolean;errorCode?:string;session?:unknown;browserNonce?:string;jobs?:unknown[]};if(!response.ok||reply.ok!==true)throw Error(reply.errorCode&&/^[a-z_]+$/.test(reply.errorCode)?reply.errorCode:'agent_connection_failed');return reply;}
export async function connectAgent(input:AgentConnectInput):Promise<AgentSession>{const endpoint=validateAgentEndpoint(input.endpoint);if(!/^studio-agent-[A-Za-z0-9_-]{43}$/.test(input.token))throw Error('agent_token_format_invalid');if(typeof location!=='undefined'&&input.origin!==location.origin)throw Error('origin_denied');const current=await identity(input.projectId);if(current.tabId!==input.tabId||current.epoch!==input.epoch)throw Error('agent_epoch_mismatch');registerDiagnosticSecret(input.token);const reply=await request(endpoint,input.token,input.origin,'/canvas/connect',current),session=agentSessionSchema.parse(reply.session);if(session.projectId!==current.projectId||session.grant.epoch!==current.epoch||session.allowedOrigin!==input.origin||!reply.browserNonce||!/^[A-Za-z0-9_-]{43}$/.test(reply.browserNonce))throw Error('agent_handshake_invalid');registerDiagnosticSecret(reply.browserNonce);try{const live=await identity(current.projectId);if(live.tabId!==current.tabId||live.epoch!==current.epoch)throw Error('agent_epoch_mismatch');}catch(error){await request(endpoint,input.token,input.origin,'/canvas/disconnect',{sessionId:session.id},reply.browserNonce).catch(()=>{});throw error;}connections.set(session.id,{identity:{...current},endpoint,token:input.token,browserNonce:reply.browserNonce,origin:input.origin,session});if(opened?.toolBridge)startAgentToolPolling(session.id,opened.toolBridge);return structuredClone(session);}
export function getAgentSession(id:string){const record=connections.get(id);return record?structuredClone(record.session):undefined;}
export async function authorizeAgent(id:string,raw:AgentGrant,options:{fullProjectConfirmed?:boolean}={}):Promise<void>{const record=connections.get(id);if(!record?.session.connected)throw Error('agent_disconnected');const current=await identity(record.session.projectId),grant=agentGrantSchema.parse(raw);if(current.epoch!==grant.epoch||current.tabId!==record.identity.tabId||grant.projectId!==current.projectId)throw Error('agent_scope_mismatch');const reply=await request(record.endpoint,record.token,record.origin,'/canvas/authorize',{sessionId:id,grant,fullProjectConfirmed:options.fullProjectConfirmed??false},record.browserNonce);record.session=agentSessionSchema.parse(reply.session);}
export async function heartbeatAgent(id:string){const record=connections.get(id);if(!record?.session.connected)throw Error('agent_disconnected');try{const current=await identity(record.session.projectId);if(current.epoch!==record.session.grant.epoch||current.tabId!==record.identity.tabId)throw Error('agent_epoch_mismatch');const reply=await request(record.endpoint,record.token,record.origin,'/canvas/heartbeat',{sessionId:id,identity:current},record.browserNonce);record.session=agentSessionSchema.parse(reply.session);return structuredClone(record.session);}catch(error){record.stopTools?.();record.session.connected=false;record.session.grant.access='read';record.session.grant.nodeIds=[];connections.delete(id);await request(record.endpoint,record.token,record.origin,'/canvas/disconnect',{sessionId:id},record.browserNonce).catch(()=>{});throw error;}}
export async function disconnectAgent(id:string){const record=connections.get(id);if(!record)return;record.stopTools?.();connections.delete(id);record.session.connected=false;record.session.grant.access='read';record.session.grant.nodeIds=[];await request(record.endpoint,record.token,record.origin,'/canvas/disconnect',{sessionId:id},record.browserNonce);}

export function startAgentToolPolling(id:string,bridge:CanvasToolBridge){const record=connections.get(id);if(!record?.session.connected)throw Error('agent_disconnected');record.stopTools?.();let stopped=false,timer:ReturnType<typeof setTimeout>|undefined;const stop=()=>{stopped=true;if(timer)clearTimeout(timer);};record.stopTools=stop;async function tick(){if(stopped||connections.get(id)!==record)return;try{await heartbeatAgent(id);if(stopped)return;const reply=await request(record!.endpoint,record!.token,record!.origin,'/canvas/poll',{sessionId:id},record!.browserNonce);for(const raw of reply.jobs??[]){if(stopped)break;const data=raw as {session?:unknown},session=agentSessionSchema.parse(data.session),job=toolEnvelopeSchema.parse({requestId:(raw as Record<string,unknown>).requestId,sessionId:(raw as Record<string,unknown>).sessionId,name:(raw as Record<string,unknown>).name,input:(raw as Record<string,unknown>).input});const result=await handleCanvasTool(job.name,job.input,session,bridge);if(!stopped&&connections.get(id)===record)await request(record!.endpoint,record!.token,record!.origin,'/canvas/reply',{sessionId:id,requestId:job.requestId,result},record!.browserNonce);}}catch{stop();await disconnectAgent(id).catch(()=>{});}finally{if(!stopped)timer=setTimeout(()=>void tick(),1000);}}timer=setTimeout(()=>void tick(),100);return stop;}
