import {useState} from 'react';
import type {AgentGrant,AgentSession} from '../../domain/agent-session';
import type {Graph} from '../../domain/graph';
import {authorizeAgent} from './agent-client';
import type {AgentContext} from './ContextPicker';
import {Dialog} from '../../ui/Dialog';
import {Button} from '../../ui/Button';
import {sanitizeKnownSecrets} from '../../security/credential-session';
export function AgentPermissionDialog({session,context,nodeIds,graph,onClose}:{session:AgentSession;context:AgentContext;nodeIds:string[];graph:Graph|undefined;onClose:()=>void}){const [access,setAccess]=useState<AgentGrant['access']>(session.grant.access),[minutes,setMinutes]=useState(30),[whole,setWhole]=useState(false),[error,setError]=useState('');return <Dialog open title="Agent 项目授权" onClose={onClose} footer={<><Button onClick={onClose}>拒绝并返回</Button><Button data-interaction-id="A-02" variant="primary" disabled={context.scope==='project'&&!whole||nodeIds.length>1000} disabledReason="整个项目需要单独勾选明确许可；最多1000个节点。" onClick={async()=>{try{await authorizeAgent(session.id,{projectId:session.projectId,scope:context.scope,nodeIds:context.scope==='project'?[]:nodeIds,access,expiresAt:Date.now()+minutes*60000,epoch:session.grant.epoch},{fullProjectConfirmed:whole});onClose();}catch{setError('授权未更新，请检查本机连接、当前标签写权或有效期。');}}}>授予所列权限</Button></>}><p>项目 {sanitizeKnownSecrets(session.projectId)} · 当前修订 {graph?.revision??'未知'} · {nodeIds.length} 个节点</p><p>本次范围：{context.scope==='project'?'整个项目':context.scope==='nodes'?'指定节点':'当前选区'}。授权是当前列表快照，之后的选区变化不会自动扩权。</p><ul>{graph?.nodes.filter(n=>nodeIds.includes(n.id)).map(n=><li key={n.id}>{sanitizeKnownSecrets(n.title)}</li>)}</ul><label>创作权限<select data-interaction-id="A-03" aria-label="创作权限" value={access} onChange={e=>setAccess(e.target.value as AgentGrant['access'])}><option value="read">只读</option><option value="propose">允许提案</option></select></label><label>授权期限<select value={minutes} onChange={e=>setMinutes(Number(e.target.value))}><option value={5}>5 分钟</option><option value={15}>15 分钟</option><option value={30}>30 分钟</option></select></label>{context.scope==='project'?<label className="generation-ack"><input type="checkbox" checked={whole} onChange={e=>setWhole(e.target.checked)}/>我明确允许读取整个项目的已保存节点</label>:null}<p>允许提案不授权收费、网络脚本或系统命令。执行仍须单独确认。到期或失联后旧授权失效，不自动续授。</p>{error?<p role="alert">{error}</p>:null}</Dialog>;}
