import {z} from 'zod';
import {boundedText,id,localText,revision,timestamp} from '../../domain/common';
import {withDatabase,transact,requestResult,type StudioDb} from '../../infrastructure/storage/database';
import {sanitizeKnownSecrets} from '../../security/credential-session';
import {emitAgentChanges} from './agent-events';
const conversationSchema=z.strictObject({id,kind:z.literal('agent-local-conversation'),projectId:id,title:boundedText(1,60),sessionIds:z.array(id).max(100),createdAt:timestamp,updatedAt:timestamp});
const contextSchema=z.strictObject({scope:z.enum(['selection','nodes','project']),nodeIds:z.array(id).max(1000),revision});
const noteSchema=z.strictObject({id,kind:z.literal('agent-local-note'),projectId:id,conversationId:id,body:localText,context:contextSchema,createdAt:timestamp});
export type AgentConversation=z.infer<typeof conversationSchema>;
export type AgentLocalNote=z.infer<typeof noteSchema>;
export async function createLocalAgentConversation(projectId:string,db?:StudioDb):Promise<AgentConversation>{const now=Date.now(),row:AgentConversation={id:'agent-conversation:'+crypto.randomUUID(),projectId,kind:'agent-local-conversation',title:'本地会话 '+new Date(now).toLocaleTimeString('zh-CN',{hour12:false}),sessionIds:[],createdAt:now,updatedAt:now};await withDatabase(db,c=>transact(c,['receipts'],'readwrite',tx=>tx.objectStore('receipts').put(conversationSchema.parse(row))));emitAgentChanges();return row;}
export async function listLocalAgentHistory(projectId:string,db?:StudioDb){return withDatabase(db,c=>transact(c,['receipts'],'readonly',async tx=>{const rows=await requestResult<unknown[]>(tx.objectStore('receipts').getAll());return {conversations:rows.flatMap(raw=>{const r=conversationSchema.safeParse(raw);return r.success&&r.data.projectId===projectId?[r.data]:[];}).sort((a,b)=>b.createdAt-a.createdAt),notes:rows.flatMap(raw=>{const r=noteSchema.safeParse(raw);return r.success&&r.data.projectId===projectId?[r.data]:[];}).sort((a,b)=>a.createdAt-b.createdAt),decisions:rows.filter(raw=>raw&&typeof raw==='object'&&'kind'in raw&&raw.kind==='agent-proposal-decision'&&'projectId'in raw&&raw.projectId===projectId) as {proposalId:string;decision:string;count?:number;createdAt:number}[]};}));}
export async function bindLocalAgentConversation(conversationId:string,sessionId:string,db?:StudioDb){await withDatabase(db,c=>transact(c,['receipts'],'readwrite',async tx=>{const row=conversationSchema.parse(await requestResult(tx.objectStore('receipts').get(conversationId)));tx.objectStore('receipts').put(conversationSchema.parse({...row,sessionIds:[...new Set([...row.sessionIds,sessionId])],updatedAt:Date.now()}));}));emitAgentChanges();}
export async function saveLocalAgentNote(conversationId:string,body:string,context:z.infer<typeof contextSchema>,db?:StudioDb){const clean=sanitizeKnownSecrets(body);if(!clean.trim()||!localText.safeParse(clean).success)throw Error('agent_description_invalid');await withDatabase(db,c=>transact(c,['receipts'],'readwrite',async tx=>{const conversation=conversationSchema.parse(await requestResult(tx.objectStore('receipts').get(conversationId))),now=Date.now();tx.objectStore('receipts').put(noteSchema.parse({id:'agent-note:'+crypto.randomUUID(),kind:'agent-local-note',projectId:conversation.projectId,conversationId,body:clean,context,createdAt:now}));tx.objectStore('receipts').put({...conversation,updatedAt:now});}));emitAgentChanges();}
export async function deleteLocalAgentConversation(conversationId:string,confirmedAbandon=false,db?:StudioDb){await withDatabase(db,c=>transact(c,['receipts','proposals'],'readwrite',async tx=>{const row=conversationSchema.parse(await requestResult(tx.objectStore('receipts').get(conversationId))),proposals=await requestResult<{sessionId:string;status:string}[]>(tx.objectStore('proposals').getAll());if(proposals.some(p=>p.status==='proposed'&&row.sessionIds.includes(p.sessionId))&&!confirmedAbandon)throw Error('pending_agent_proposals_confirmation_required');const notes=await requestResult<unknown[]>(tx.objectStore('receipts').getAll());for(const raw of notes){const n=noteSchema.safeParse(raw);if(n.success&&n.data.conversationId===conversationId)tx.objectStore('receipts').delete(n.data.id);}tx.objectStore('receipts').delete(conversationId);}));emitAgentChanges();}
