import type {CanvasToolBridge} from '../../../companion/src/mcp';
import type {StudioDb} from '../../infrastructure/storage/database';
import type {AgentSession} from '../../domain/agent-session';
import {readGraph} from '../../infrastructure/storage/project-repository';
import {getAgentSession,getOpenedCanvasIdentity,heartbeatAgent} from './agent-client';
import {sanitizeKnownSecrets} from '../../security/credential-session';
import {receiveProposal,readProposal} from '../../application/proposals/apply-proposal';
import {proposalSchema} from '../../domain/proposal';
import {selectProposalOperations} from '../../application/proposals/validate-proposal';
export function createBrowserCanvasTools(options:{db?:StudioDb;selection:()=>string[];review:(id:string)=>Promise<void>;requestRun:(requestId:string,nodeIds:string[],session?:AgentSession)=>Promise<void>}):CanvasToolBridge{
 const runRequests=new Map<string,{nodeIds:string[];promise:Promise<{requestId:string;nodeIds:string[]}>}>();
 function live(session:AgentSession){const actual=getAgentSession(session.id);if(!actual?.connected||actual.grant.expiresAt<=Date.now()||JSON.stringify(actual)!==JSON.stringify(session))throw Error('agent_permission_changed');return actual;}
 async function guard(session:AgentSession){live(session);const identity=await getOpenedCanvasIdentity(session.projectId);if(identity.epoch!==session.grant.epoch)throw Error('agent_epoch_mismatch');await heartbeatAgent(session.id);live(session);}
 async function scoped(session:AgentSession){await guard(session);const graph=await readGraph(session.projectId,options.db);if(!graph)throw Error('canvas_not_connected');live(session);const ids=new Set(session.grant.scope==='project'?graph.nodes.map(n=>n.id):session.grant.nodeIds),nodes=graph.nodes.filter(n=>ids.has(n.id)).map(n=>({...n,...(n.type==='group'?{data:{...n.data,childIds:n.data.childIds.filter(id=>ids.has(id))}}:{})}));return {projectId:graph.projectId,revision:graph.revision,nodes,edges:graph.edges.filter(e=>ids.has(e.sourceId)&&ids.has(e.targetId))};}
 return {readState:async session=>JSON.parse(sanitizeKnownSecrets(JSON.stringify(await scoped(session)))) as unknown,readSelection:async session=>{const graph=await scoped(session),allowed=new Set(graph.nodes.map(n=>n.id));return {nodeIds:options.selection().filter(id=>allowed.has(id))};},propose:async(raw,session)=>{await guard(session);const proposal=proposalSchema.parse((raw as {proposal:unknown}).proposal);if(proposal.sessionId!==session.id||proposal.projectId!==session.projectId)throw Error('agent_proposal_binding_mismatch');const result=await receiveProposal(proposal,options.db);return {proposalId:result.id,status:result.status};},review:async(raw,session)=>{await guard(session);const input=raw as {proposalId:string;selectedOperationIds?:string[]},proposal=await readProposal(input.proposalId,options.db);if(proposal.sessionId!==session.id||proposal.projectId!==session.projectId||proposal.status!=='proposed')throw Error('agent_proposal_binding_mismatch');if(input.selectedOperationIds?.length)selectProposalOperations(proposal,input.selectedOperationIds);live(session);await options.review(proposal.id);return {proposalId:proposal.id};},requestRun:async(raw,session)=>{await guard(session);const input=raw as {requestId:string;nodeIds:string[]},key=session.id+':'+input.requestId,prior=runRequests.get(key);if(prior){if(JSON.stringify(prior.nodeIds)!==JSON.stringify(input.nodeIds))throw Error('agent_run_request_id_reused');return prior.promise;}if(runRequests.size>=100)throw Error('agent_run_request_limit');const promise=(async()=>{const graph=await scoped(session);if(input.nodeIds.some(id=>!graph.nodes.some(n=>n.id===id)))throw Error('agent_node_scope');const result={requestId:input.requestId,nodeIds:[...input.nodeIds]};live(session);await options.requestRun(input.requestId,input.nodeIds,session);return result;})();runRequests.set(key,{nodeIds:[...input.nodeIds],promise});return promise;}};
}
