import {useEffect,useState} from 'react';
import type {Graph} from '../../domain/graph';
import type {Proposal} from '../../domain/proposal';
import {applyProposal,listProjectProposals,rejectProposal} from '../../application/proposals/apply-proposal';
import {getAgentSession} from './agent-client';
import {readGraph} from '../../infrastructure/storage/project-repository';
import {sanitizeKnownSecrets} from '../../security/credential-session';
import {Dialog} from '../../ui/Dialog';
import {Button} from '../../ui/Button';
const labels:Record<string,string>={add_node:'新增节点',remove_node:'删除节点',update_node:'修改节点',move_node:'移动节点',add_edge:'新增连线',remove_edge:'删除连线',group:'组合节点',ungroup:'解除组合',select_result:'选择结果'};
const statuses:Record<string,string>={proposed:'待审阅',applied:'已应用',rejected:'已拒绝',conflict:'版本冲突'};
export function ProposalReview({proposal,canApply,onClose,onChanged}:{proposal:Proposal;canApply:boolean;onClose:()=>void;onChanged:()=>Promise<void>}){
 const [selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState(''),[working,setWorking]=useState(false),[expired,setExpired]=useState(false),[confirmAll,setConfirmAll]=useState(false),[decided,setDecided]=useState(false),[before,setBefore]=useState<Graph>();
 useEffect(()=>{let live=true;void readGraph(proposal.projectId).then(graph=>{if(live)setBefore(graph);});return()=>{live=false;};},[proposal.projectId]);
 useEffect(()=>{const check=()=>{const s=getAgentSession(proposal.sessionId);setExpired(!s?.connected||s.grant.access!=='propose'||s.grant.expiresAt<=Date.now());};check();const timer=setInterval(check,500);return()=>clearInterval(timer);},[proposal.sessionId]);
 const deleted=proposal.operations.filter(op=>op.type==='remove_node').length,chosenDeleted=proposal.operations.filter(op=>selected.includes(op.id)&&op.type==='remove_node').length,blocked=!canApply||expired||proposal.status!=='proposed'||working||decided;
 async function apply(ids:string[]){setWorking(true);setConfirmAll(false);try{const result=await applyProposal(proposal.id,ids);if(result.status==='applied'||result.status==='replayed'){await onChanged();onClose();}else if(result.status==='conflict'){setDecided(true);const graph=await readGraph(proposal.projectId);setMessage('版本冲突：当前修订 '+(graph?.revision??'未知')+'。旧提案未覆盖画布，请要求 Agent 基于当前版本生成新提案，重新审阅。');await onChanged();}else setMessage('修改未应用：'+(result.errorCode??'proposal_rejected')+'。请检查权限、操作依赖和保存状态。');}catch{setMessage('提案处理失败，画布未确认写入，请重新读取记录。');}finally{setWorking(false);}}
 return <><Dialog open title="Agent 提案审阅" onClose={onClose} dismissible={!working} footer={<><Button data-interaction-id="A-09" disabled={working||proposal.status!=='proposed'} onClick={async()=>{setWorking(true);try{await rejectProposal(proposal.id);await onChanged();onClose();}catch{setMessage('拒绝结果未保存，请重试。');}finally{setWorking(false);}}}>拒绝提案</Button><Button data-interaction-id="A-08" disabled={blocked} onClick={()=>setConfirmAll(true)}>接受全部修改</Button><Button data-interaction-id="A-07" variant="primary" disabled={blocked||!selected.length} disabledReason={expired?'连接或提案权限已失效，请重新授权。':!canApply?'请先保存画布修改并取得编辑权。':proposal.status!=='proposed'?'该提案已决定或发生冲突。':'请勾选要接受的操作；有关联的操作须一起选择。'} onClick={()=>apply(selected)}>应用选中修改</Button></>}>
 <p>提案 {sanitizeKnownSecrets(proposal.id)} · 基于修订 {proposal.baseRevision} · {statuses[proposal.status]}</p><p className={deleted?'banner error':'banner'}>删除节点 {deleted} · 选中删除 {chosenDeleted} · 总操作 {proposal.operations.length}</p><p>接受创作修改不授权生成。收费执行仍需要单独确认。</p>
 {proposal.operations.map(op=><section key={op.id}><label style={{display:"flex",flexDirection:"row",alignItems:"center",gap:12}}><input style={{width:"auto"}} type="checkbox" aria-label={'选择操作 '+op.id} disabled={blocked} checked={selected.includes(op.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,op.id]:ids.filter(id=>id!==op.id))}/>{labels[op.type]??'结构化修改'} · {sanitizeKnownSecrets(op.id)}</label><OperationDiff op={op} graph={before}/></section>)}{message?<p role="alert">{message}</p>:null}
 </Dialog><Dialog open={confirmAll} title="确认接受全部修改" onClose={()=>setConfirmAll(false)} footer={<><Button onClick={()=>setConfirmAll(false)}>继续审阅</Button><Button variant={deleted?'danger':'primary'} disabled={blocked} onClick={()=>apply(proposal.operations.map(op=>op.id))}>确认全部 {proposal.operations.length} 项修改</Button></>}><p>将接受全部 {proposal.operations.length} 项操作，其中删除节点 {deleted} 个。操作会作为一次可撤销的画布事务保存。</p></Dialog></>;
}
export function ProposalInbox({projectId,canApply,onClose,onChanged}:{projectId:string;canApply:boolean;onClose:()=>void;onChanged:()=>Promise<void>}){
 const [proposals,setProposals]=useState<Proposal[]>([]),[review,setReview]=useState<Proposal>(),[error,setError]=useState('');
 async function load(){try{setProposals(await listProjectProposals(projectId));setError('');}catch{setError('提案记录读取失败，请重新读取。');}}
 useEffect(()=>{let alive=true;void listProjectProposals(projectId).then(rows=>{if(alive)setProposals(rows);}).catch(()=>{if(alive)setError('提案记录读取失败，请重新读取。');});return()=>{alive=false;};},[projectId]);
 return <><Dialog open={!review} title="Agent 提案" onClose={onClose} footer={<Button onClick={load}>重新读取提案</Button>}><p>只审阅当前项目的提案。连接后默认只读，允许提案需单独授权。</p>{error?<p role="alert">{error}</p>:null}{!proposals.length?<p>当前没有提案。</p>:proposals.map(p=><div key={p.id}><span>{statuses[p.status]} · 修订 {p.baseRevision} · {p.operations.length} 项</span><Button aria-label={'审阅提案 '+p.id} onClick={()=>setReview(p)}>审阅提案 {sanitizeKnownSecrets(p.id)}</Button></div>)}</Dialog>{review?<ProposalReview proposal={review} canApply={canApply} onClose={()=>{setReview(undefined);void load();}} onChanged={async()=>{await onChanged();await load();}}/>:null}</>;
}

function OperationDiff({op,graph}:{op:Proposal['operations'][number];graph:Graph|undefined}){const node=graph?.nodes.find(n=>n.id===op.payload.nodeId),patch=op.payload.patch as Record<string,unknown>|undefined;return <div><p>{node?('节点：'+sanitizeKnownSecrets(node.title)):''}</p>{op.type==='update_node'&&patch&&Object.entries(patch).map(([key,value])=><p key={key}>{({title:'标题',locked:'锁定状态',data:'内容'} as Record<string,string>)[key]??'属性'}：{sanitizeKnownSecrets(JSON.stringify(node?.[key as keyof typeof node]??null))} → {sanitizeKnownSecrets(JSON.stringify(value))}</p>)}{op.type==='move_node'?<p>位置：({node?.x??'未知'}, {node?.y??'未知'}) → ({String(op.payload.x)}, {String(op.payload.y)})</p>:null}{op.type==='remove_node'?<p className='banner error'>此节点将被删除；相关连线会同时移除。</p>:null}<details><summary>查看结构化操作</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{sanitizeKnownSecrets(JSON.stringify(op.payload,null,2))}</pre></details></div>;}
