import {Button} from '../../ui/Button';
import type {CanvasNode} from '../../domain/graph';
import type {Run} from '../../domain/run';
import {videoNumber} from './video-number';
import type {RunQueue} from '../../application/runs/queue';
const states={draft:'待确认',ready:'准备就绪',active:'正在准备与提交',paused:'已暂停',waiting_confirmation:'等待输入确认',blocked:'依赖受阻',completed:'队列已结束'};
const items={waiting_confirmation:'待确认输入',ready:'待提交',preparing:'正在准备',accepted:'已提交',blocked:'受阻',submit_unknown:'提交结果不明',withdrawn:'本地已撤回'};
export function QueueControls({queue,nodes,runs,canWrite,canResume=canWrite,onPause,onResume,onConcurrency}:{queue:RunQueue;nodes:CanvasNode[];runs:Run[];canWrite:boolean;canResume?:boolean;onPause:()=>Promise<void>;onResume:()=>void;onConcurrency:(value:number)=>Promise<void>}){
 const pending=queue.items.filter(i=>!['accepted','submit_unknown','withdrawn'].includes(i.status));
 return <section aria-label="执行队列" className="queue-controls"><strong>执行队列 · {states[queue.state]}</strong><label>本地准备并行<select data-interaction-id="ui:QueueControls:select:310167e217d8" aria-label="本地准备并行" value={queue.preparationConcurrency} disabled={!canWrite||!['paused','ready','draft'].includes(queue.state)} onChange={event=>void onConcurrency(Number(event.target.value))}>{[1,2,3].map(n=><option key={n} value={n}>{n}</option>)}</select></label><p>此数量只控制本地准备；服务准入由 Core 决定。暂停不会取消已发出的任务，也不表示退款。</p><ul>{queue.items.map(item=><li key={item.nodeId}><span title={'节点ID：'+item.nodeId}>{nodes.find(node=>node.id===item.nodeId)?.title??'历史视频节点'} · {items[item.status]}</span>{item.runId&&runs.find(run=>run.id===item.runId&&run.nodeId===item.nodeId)?<small title={'任务ID：'+item.runId}> · {videoNumber(runs.find(run=>run.id===item.runId&&run.nodeId===item.nodeId)!)}</small>:null}{item.errorCode==='upstream_failed'?' · 原上游任务失败':item.requiresVisibleOutputs.length?' · 先查看并明确引用上游结果':''}</li>)}</ul><Button data-interaction-id="C-17" disabled={!canWrite||!['ready','active'].includes(queue.state)} onClick={onPause}>暂停待提交项</Button><Button data-interaction-id="C-18" disabled={!canWrite||!canResume||queue.state!=='paused'||!pending.length||queue.items.some(i=>i.status==='submit_unknown')} disabledReason="待提交项需要重新确认；结果不明的请求请先核对原记录。" onClick={onResume}>重新确认待提交项</Button></section>;
}
