import {useEffect,useState} from 'react';import type {Run} from '../../domain/run';
import {listProjectQueues,pauseQueue,withdrawQueueItem,type RunQueue} from '../../application/runs/queue';import {getProjectWriter} from '../projects/project-service';import {Button} from '../../ui/Button';import {Dialog} from '../../ui/Dialog';
export function TaskQueueActions({run,onChange}:{run:Run;onChange:()=>Promise<void>}){
 const [queue,setQueue]=useState<RunQueue>(),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function reload(){const rows=await listProjectQueues(run.projectId);setQueue(rows.find(q=>q.items.some(i=>i.runId===run.id)));}
 useEffect(()=>{let active=true;void listProjectQueues(run.projectId).then(rows=>{if(active)setQueue(rows.find(q=>q.items.some(i=>i.runId===run.id)));}).catch(()=>{if(active)setError('本地队列读取失败，原记录保留。');});return()=>{active=false;};},[run.projectId,run.id]);
 const item=queue?.items.find(i=>i.runId===run.id),removable=!!queue&&!!item&&['draft','ready','paused','blocked','waiting_confirmation'].includes(queue.state)&&['ready','waiting_confirmation','blocked'].includes(item.status)&&run.executionState==='persisted'&&!run.taskId;
 async function change(action:(queue:RunQueue)=>Promise<void>){if(!queue||busy)return;setBusy(true);setError('');try{await action(queue);await reload();await onChange();}catch{setError('队列或写权已变化；操作未保存，请重新读取并核对。原执行与账务记录保留。');}finally{setBusy(false);}}
 return <section aria-label="原任务本地队列"><p>{queue?'原任务本地队列 · '+(queue.state==='paused'?'已暂停':queue.state==='active'?'正在提交':queue.state==='ready'?'准备就绪':'待核对'):'未找到可操作的本地队列。'}</p><p>{item?.status==='withdrawn'?'本地已撤回；原尝试不能重新提交，不代表取消生成或退款。':item?.status==='accepted'?'此项已发出，不能移出未提交队列。':'仅操作本地尚未发出的项，已发出任务仍保留追踪。'}</p><div className="actions"><Button data-interaction-id="J-07" disabled={busy||!queue||!['ready','active'].includes(queue.state)} onClick={()=>change(async q=>{const lease=await getProjectWriter(q.projectId);setQueue(await pauseQueue(q.queueId,{lease}));})}>停止后续提交</Button><Button data-interaction-id="J-06" disabled={!removable||busy} disabledReason="需本地未提交项和有效写权；准备中或已发出的任务不能移除。" onClick={()=>setOpen(true)}>移出本地待提交队列</Button><Button data-interaction-id="ui:TaskQueueActions:Button:671b289946d4" disabled={busy} onClick={reload}>重新读取队列</Button></div>{error?<p role="alert">{error}</p>:null}<Dialog open={open} title="移出本地待提交队列" width={560} dismissible={!busy} onClose={()=>setOpen(false)} footer={<><Button data-interaction-id="ui:TaskQueueActions:Button:8554bc9c87a2" disabled={busy} onClick={()=>setOpen(false)}>返回保留待提交项</Button><Button data-interaction-id="J-06" disabled={!removable} busy={busy} onClick={()=>change(async q=>{const lease=await getProjectWriter(q.projectId);await withdrawQueueItem(q.queueId,run.nodeId,{confirmed:true,epoch:q.epoch},{lease});setOpen(false);})}>确认撤回本地未提交项</Button></>}><p>本地执行 {run.id} · 节点 {run.nodeId}。保留原 Run、冻结请求、授权和账务证据；此尝试将不再提交。不会取消远端任务，不表示退款，也不自动创建新尝试。</p>{error?<p role="alert">{error}</p>:null}</Dialog></section>;
}
