import {withDatabase,transact,requestResult,type StudioDb} from '../../infrastructure/storage/database';
import {runSchema,type Run} from '../../domain/run';
import {promptRunSchema,promptDraftSchema,type PromptRun} from '../../domain/prompt';
import {projectSchema} from '../../domain/project';
import {graphSchema} from '../../domain/graph';
import {getActiveCore} from '../../adapters/core/current-connection';
import {pollVideoOnce,resumePolling,type PollOptions} from '../../application/runs/poll-video';
import {sanitizeKnownSecrets} from '../../security/credential-session';
import {redact} from '../../security/redaction';
import {acquireMediaUrl} from '../review/object-url-pool';
export type TaskFilter={kind?:'all'|'video'|'prompt';projectId?:string;connectionId?:string;executionState?:string;queryState?:string;deliveryState?:string;billingState?:string;query?:string;includeArchived?:boolean};
type CommonTask={locallyWithdrawn?:boolean;id:string;title:string;projectId?:string;projectTitle:string;projectArchived:boolean;nodeExists:boolean;draftExists:boolean;archived:boolean;connectionId:string;authBindingId:string;originSnapshot:string;executionState:string;queryState:string;deliveryState:string;billingState:string;taskId?:string;coreRequestId?:string;createdAt:number};
export type TaskListItem=CommonTask&({kind:'video';record:Run}|{kind:'prompt';record:PromptRun});
export const executionLabels:Record<string,string>={draft:'草稿',preflight_blocked:'输入待修复',awaiting_confirmation:'待确认',persisted:'本地待提交',uploading:'准备参考素材',submitting:'提交结果待确认',submit_unknown:'提交结果待确认',accepted:'已提交',running:'生成中',succeeded:'已完成',failed_confirmed:'明确失败',sending:'等待文字响应',response_unknown:'文字响应待核对',waiting_stopped:'已停止等待，原请求待核对'};
export const queryLabels:Record<string,string>={idle:'查询空闲',polling:'查询中',paused_by_user:'已停止本地查询',interrupted:'查询中断',auth_required:'需要原授权',not_applicable:'文字无异步查询通道'};
export const deliveryLabels:Record<string,string>={not_ready:'内容待获取',fetching:'获取内容中',available_for_preview:'可预览',cached_local:'本地已缓存',browser_download_triggered:'已触发浏览器下载',download_failed:'下载失败',not_applicable:'文字结果见草稿历史'};
export const billingLabels:Record<string,string>={not_provided:'账务未提供',reserved:'Core记录预留',pending_reconciliation:'账务待核对',settled:'Core记录结算',released:'Core记录释放'};
export function taskExecutionLabel(item:TaskListItem){return item.locallyWithdrawn?'本地待提交已撤回（原执行记录保留）':item.executionState==='succeeded'?(item.kind==='video'?'视频已完成':'文字请求已完成'):executionLabels[item.executionState]??'状态未知';}
function archiveId(kind:TaskListItem['kind'],id:string){return 'task-archive:'+kind+':'+id;}
export function taskCanArchive(item:Pick<TaskListItem,'executionState'|'queryState'|'deliveryState'|'billingState'>){return ['succeeded','failed_confirmed'].includes(item.executionState)&&['idle','not_applicable'].includes(item.queryState)&&!['fetching','download_failed'].includes(item.deliveryState)&&item.billingState!=='pending_reconciliation';}
export async function listLocalTasks(filter:TaskFilter={},db?:StudioDb):Promise<TaskListItem[]>{
 return withDatabase(db,c=>transact(c,['runs','promptRuns','projects','graphs','promptDrafts','receipts'],'readonly',async tx=>{
  const all=await Promise.all([requestResult<unknown[]>(tx.objectStore('runs').getAll()),requestResult<unknown[]>(tx.objectStore('promptRuns').getAll()),requestResult<unknown[]>(tx.objectStore('projects').getAll()),requestResult<unknown[]>(tx.objectStore('graphs').getAll()),requestResult<unknown[]>(tx.objectStore('promptDrafts').getAll()),requestResult<{id:string;kind?:string;archived?:boolean;draft?:unknown}[]>(tx.objectStore('receipts').getAll())]);
  const projects=all[2].map(p=>projectSchema.safeParse(p)).flatMap(p=>p.success?[p.data]:[]),graphs=all[3].map(g=>graphSchema.safeParse(g)).flatMap(g=>g.success?[g.data]:[]),drafts=all[4].map(d=>promptDraftSchema.safeParse(d)).flatMap(d=>d.success?[d.data]:[]),receipts=all[5],items:TaskListItem[]=[];
  for(const raw of all[0]){const run=runSchema.parse(raw),project=projects.find(p=>p.id===run.projectId),node=graphs.find(g=>g.projectId===run.projectId)?.nodes.find(n=>n.id===run.nodeId);items.push({locallyWithdrawn:receipts.some(r=>r.id==='run-withdrawal:'+run.id&&r.kind==='local-unsent-withdrawal'),id:run.id,kind:'video',record:run,title:node?.title??'历史节点 '+run.nodeId,projectId:run.projectId,projectTitle:project?.title??'原项目已不可用',projectArchived:project?.archived??false,nodeExists:!!node&&!!project&&project.trashedAt===null,draftExists:false,archived:receipts.find(r=>r.id===archiveId('video',run.id))?.archived===true,connectionId:run.connectionId,authBindingId:run.authBindingId,originSnapshot:run.originSnapshot,executionState:run.executionState,queryState:run.queryState,deliveryState:run.deliveryState,billingState:run.billingState,taskId:run.taskId,coreRequestId:run.coreRequestId,createdAt:run.createdAt});}
  for(const raw of all[1]){const run=promptRunSchema.parse(raw),current=drafts.find(d=>d.id===run.draftId),saved=receipts.find(r=>r.id===`prompt-draft:${run.draftId}:${run.draftRevision}`&&r.kind==='prompt-draft-version'),historical=promptDraftSchema.safeParse(saved?.draft),source=historical.success?historical.data:current?.revision===run.draftRevision?current:undefined,project=projects.find(p=>p.id===source?.sourceProjectId);items.push({id:run.id,kind:'prompt',record:run,title:'文字优化 · '+run.textModelId,projectId:source?.sourceProjectId,projectTitle:project?.title??(source?.sourceProjectId?'原项目已不可用':'独立提示词或来源待恢复'),projectArchived:project?.archived??false,nodeExists:false,draftExists:!!current,archived:receipts.find(r=>r.id===archiveId('prompt',run.id))?.archived===true,connectionId:run.connectionId,authBindingId:run.authBindingId,originSnapshot:run.originSnapshot,executionState:run.executionState,queryState:'not_applicable',deliveryState:'not_applicable',billingState:run.billingState,coreRequestId:run.coreRequestId,createdAt:run.startedAt});}
  const query=filter.query?.trim().toLocaleLowerCase();return items.filter(i=>(!filter.kind||filter.kind==='all'||i.kind===filter.kind)&&(!filter.projectId||i.projectId===filter.projectId)&&(!filter.connectionId||i.connectionId===filter.connectionId)&&(!filter.executionState||filter.executionState==='all'||i.executionState===filter.executionState)&&(!filter.queryState||filter.queryState==='all'||i.queryState===filter.queryState)&&(!filter.deliveryState||filter.deliveryState==='all'||i.deliveryState===filter.deliveryState)&&(!filter.billingState||filter.billingState==='all'||i.billingState===filter.billingState)&&(filter.includeArchived||!i.archived)&&(!query||[i.id,i.title,i.projectTitle,i.taskId??'',i.coreRequestId??''].some(v=>v.toLocaleLowerCase().includes(query)))).sort((a,b)=>b.createdAt-a.createdAt||a.id.localeCompare(b.id));
 }));
}
export async function archiveLocalTask(item:TaskListItem,archived:boolean,db?:StudioDb){return withDatabase(db,c=>transact(c,['runs','promptRuns','receipts'],'readwrite',async tx=>{
 const raw=await requestResult(tx.objectStore(item.kind==='video'?'runs':'promptRuns').get(item.id)),current=item.kind==='video'?runSchema.parse(raw):promptRunSchema.parse(raw),status={executionState:current.executionState,billingState:current.billingState,queryState:'queryState'in current?current.queryState:'not_applicable',deliveryState:'deliveryState'in current?current.deliveryState:'not_applicable'};if(archived&&!taskCanArchive(status))throw Error('task_archive_requires_known_terminal');tx.objectStore('receipts').put({id:archiveId(item.kind,item.id),kind:'task-archive',taskKind:item.kind,taskId:item.id,archived,at:Date.now()});
 }));}
export async function refreshKnownTasks(items:TaskListItem[],queryFailuresOnly=false,options:Pick<PollOptions,'db'|'tabId'>={}){let completed=0,skipped=0,failed=0;const active=getActiveCore();
 for(const item of items){const matches=!!active&&item.authBindingId===active.client.binding.id&&item.connectionId===active.client.profile.id&&item.originSnapshot===active.client.profile.originSnapshot;
  if(completed+failed>=50||item.kind!=='video'||!matches||!item.taskId||['submitting','submit_unknown','draft','persisted','uploading','failed_confirmed'].includes(item.executionState)||queryFailuresOnly&&!['interrupted','auth_required'].includes(item.queryState)||item.queryState==='paused_by_user'){skipped++;continue;}
  try{const run=await pollVideoOnce(item.id,{...active,...options});if(['interrupted','auth_required'].includes(run.queryState))failed++;else completed++;}catch{failed++;}
  if(items.length>1)await new Promise(resolve=>setTimeout(resolve,100));
 }return {completed,skipped,failed};
}
export async function querySingleTask(item:TaskListItem){if(item.kind!=='video')throw Error('text_query_unsupported');const active=getActiveCore();if(!active||active.client.binding.id!==item.authBindingId||active.client.profile.id!==item.connectionId||active.client.profile.originSnapshot!==item.originSnapshot)throw Error('original_authorization_required');if(item.queryState==='paused_by_user')await resumePolling(item.id,active);return pollVideoOnce(item.id,active);}
function csvCell(value:string){const redacted=redact({message:sanitizeKnownSecrets(value)}) as {message:string};let clean=redacted.message;if(/^[\s\uFEFF]*[=+@-]/.test(clean)||/^[\t\r\n]/.test(clean))clean="'"+clean;return '"'+clean.replace(/"/g,'""')+'"';}
export function tasksCsv(items:TaskListItem[]){const columns=['类型','本地ID','标题','项目','原连接','原授权绑定','Core任务ID','Core请求ID','执行状态','查询状态','交付状态','账务状态'];return '\uFEFF'+[columns,...items.map(i=>[i.kind,i.id,i.title,i.projectTitle,i.connectionId,i.authBindingId,i.taskId??'',i.coreRequestId??'',i.executionState,i.queryState,i.deliveryState,i.billingState])].map(row=>row.map(csvCell).join(',')).join('\r\n');}
export function downloadTasksCsv(items:TaskListItem[]){const url=acquireMediaUrl(new Blob([tasksCsv(items)],{type:'text/csv;charset=utf-8'})),anchor=document.createElement('a');anchor.href=url.objectUrl;anchor.download='AIWORK-任务记录.csv';document.body.append(anchor);try{anchor.click();}finally{anchor.remove();setTimeout(url.release,60000);}}
