import {useCallback,useEffect,useRef,useState} from 'react';
import {Button} from '../../ui/Button';
import {listLocalTasks,archiveLocalTask,downloadTasksCsv,refreshKnownTasks,taskCanArchive,taskExecutionLabel,executionLabels,queryLabels,deliveryLabels,billingLabels,type TaskFilter,type TaskListItem} from './task-filters';
import {TaskDetail} from './TaskDetail';
import {subscribeActiveCore} from '../../adapters/core/current-connection';
import {TaskTracking} from './TaskTracking';
export function TaskRecords({projectId}:{projectId?:string}){
 const [filter,setFilter]=useState<TaskFilter>({kind:'all',includeArchived:false}),[items,setItems]=useState<TaskListItem[]>([]),[selected,setSelected]=useState<string[]>([]),[detailId,setDetailId]=useState<string>(),[message,setMessage]=useState(''),[failed,setFailed]=useState(false),request=useRef(0),alive=useRef(true),[,connectionChanged]=useState(0);
 useEffect(()=>subscribeActiveCore(()=>connectionChanged(v=>v+1)),[]);const filterKey=JSON.stringify({...filter,projectId});
 const load=useCallback(async()=>{const token=++request.current;try{const result=await listLocalTasks(JSON.parse(filterKey) as TaskFilter);if(alive.current&&request.current===token){setItems(result);setFailed(false);}}catch{if(alive.current&&request.current===token)setFailed(true);}},[filterKey]);
 useEffect(()=>{alive.current=true;void load();const timer=setInterval(()=>void load(),1500);return()=>{alive.current=false;request.current++;clearInterval(timer);};},[load]);
 async function batch(failuresOnly:boolean){const picked=items.filter(i=>selected.includes(i.kind+':'+i.id));const result=await refreshKnownTasks(picked,failuresOnly);setMessage(`查询完成 ${result.completed}，跳过 ${result.skipped}，失败 ${result.failed}；没有提交新生成。`);await load();}
 const detail=items.find(i=>i.kind+':'+i.id===detailId),groups=new Map<string,TaskListItem[]>();for(const item of items){const key=item.connectionId+' / '+item.authBindingId;groups.set(key,[...(groups.get(key)??[]),item]);}
 function selector(label:string,key:'executionState'|'queryState'|'deliveryState'|'billingState',labels:Record<string,string>){return <label>{label}<select data-interaction-id="J-01" aria-label={label} value={filter[key]??'all'} onChange={event=>setFilter(v=>({...v,[key]:event.target.value}))}><option value="all">全部</option>{Object.entries(labels).map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>;}
 return <><p>仅此浏览器创建或导入的任务记录，范围不包含全部 Core 历史。</p><div className="actions"><Button data-interaction-id="ui:TasksPage:Button:d74b52a30263" aria-pressed={filter.kind==='all'} onClick={()=>setFilter(v=>({...v,kind:'all'}))}>全部记录</Button><Button data-interaction-id="ui:TasksPage:Button:625e1cf5fa9b" aria-pressed={filter.kind==='video'} onClick={()=>setFilter(v=>({...v,kind:'video'}))}>视频任务</Button><Button data-interaction-id="ui:TasksPage:Button:82a5a4ec3912" aria-pressed={filter.kind==='prompt'} onClick={()=>setFilter(v=>({...v,kind:'prompt'}))}>文字优化</Button></div>
 <div className="task-filters"><label>搜索本地任务<input data-interaction-id="ui:TasksPage:input:6ae4ff0b3019" type="search" value={filter.query??''} onChange={event=>setFilter(v=>({...v,query:event.target.value}))}/></label>{selector('执行状态筛选','executionState',executionLabels)}{selector('查询状态筛选','queryState',queryLabels)}{selector('交付状态筛选','deliveryState',deliveryLabels)}{selector('账务状态筛选','billingState',billingLabels)}<label><input data-interaction-id="ui:TasksPage:input:470b5101b017" type="checkbox" checked={filter.includeArchived??false} onChange={event=>setFilter(v=>({...v,includeArchived:event.target.checked}))}/>显示归档记录</label></div>
 <div className="actions"><Button data-interaction-id="J-04" disabled={!selected.length} onClick={()=>batch(false)}>刷新所选已知任务</Button><Button data-interaction-id="J-05" disabled={!selected.length} onClick={()=>batch(true)}>仅重试查询中断项</Button><Button data-interaction-id="J-09" disabled={!items.length} onClick={()=>{downloadTasksCsv(items);setMessage('已触发浏览器下载；CSV只包含脱敏记录摘要。');}}>导出脱敏CSV</Button><Button data-interaction-id="ui:TasksPage:Button:237eb27fe82a" onClick={()=>setFilter({kind:'all',includeArchived:false})}>清除筛选</Button></div><p role="status">{message}</p>{failed?<p role="alert">本地任务读取失败，原记录保留，请重试。</p>:!items.length?<p>没有符合当前筛选的本地任务记录。</p>:null}
 {[...groups].map(([key,rows])=><section className="task-origin" key={key} aria-label={'原连接分组 '+key}><h3>原连接 / 授权绑定：{key}</h3>{rows.map(item=><article className="card task-row" key={item.kind+':'+item.id} data-testid={item.id}><label><input data-interaction-id="ui:TasksPage:input:b985f4a202b6" type="checkbox" aria-label={'选择记录 '+item.id} checked={selected.includes(item.kind+':'+item.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,item.kind+':'+item.id]:v.filter(id=>id!==item.kind+':'+item.id))}/>{item.kind==='video'?'视频任务':'文字优化'} · {item.title}</label><p>{taskExecutionLabel(item)} · {queryLabels[item.queryState]} · {deliveryLabels[item.deliveryState]} · {billingLabels[item.billingState]}</p><small>{item.projectTitle}{item.projectArchived?' · 项目归档，追踪保留':''}{item.archived?' · 记录已归档':''}</small><div className="actions"><Button data-interaction-id="J-02" onClick={()=>setDetailId(item.kind+':'+item.id)}>详情</Button><Button data-interaction-id="J-08" disabled={!item.archived&&!taskCanArchive(item)} disabledReason={!taskCanArchive(item)?'尚有未明状态，保留在任务记录中':undefined} onClick={async()=>{try{await archiveLocalTask(item,!item.archived);await load();}catch{setMessage('归档未保存；原任务仍保留。');}}}>{item.archived?'取消归档':'归档记录'}</Button></div></article>)}</section>)}
 {detail?<TaskDetail key={detail.kind+':'+detail.id} item={detail} onClose={()=>setDetailId(undefined)} onChange={load}/>:null}</>;
}
export function TasksPage(){return <section aria-label="本地任务中心"><TaskTracking/><TaskRecords/></section>;}
