import {z} from 'zod';
import {agentSessionSchema,type AgentSession} from '../../src/domain/agent-session';
import {proposalSchema} from '../../src/domain/proposal';
import {byteLength,snapshotSchema} from '../../src/domain/common';
import {readCanvasTool} from './tools/canvas-read';
import {proposeCanvasTool} from './tools/canvas-propose';
import {requestCanvasRun} from './tools/canvas-run';
export type ToolResult={status:'ok'|'proposed'|'awaiting_browser_confirmation'|'awaiting_browser_proposal_confirmation'|'rejected';data?:unknown;errorCode?:string};
export type CanvasToolBridge={readState:(session:AgentSession)=>Promise<unknown>;readSelection:(session:AgentSession)=>Promise<unknown>;propose:(input:unknown,session:AgentSession)=>Promise<unknown>;review:(input:unknown,session:AgentSession)=>Promise<unknown>;requestRun:(input:unknown,session:AgentSession)=>Promise<unknown>};
const boundedId=z.string().min(1).max(256),nodeIds=z.array(boundedId).min(1).max(1000).refine(ids=>new Set(ids).size===ids.length);
export const canvasToolSchemas={canvas_get_state:z.strictObject({}),canvas_get_selection:z.strictObject({}),canvas_propose_ops:z.strictObject({proposal:proposalSchema}),canvas_apply_proposal:z.strictObject({proposalId:boundedId,selectedOperationIds:z.array(boundedId).max(100).optional()}),canvas_request_run:z.strictObject({requestId:boundedId,nodeIds})};
export type CanvasToolName=keyof typeof canvasToolSchemas;
export function validateCanvasToolInput(name:string,input:unknown,session:AgentSession){const s=agentSessionSchema.parse(session);if(!s.connected||s.grant.expiresAt<=Date.now())throw Error('agent_session_expired');if(!(name in canvasToolSchemas)||!Object.hasOwn(canvasToolSchemas,name))throw Error('canvas_tool_unknown');if(!snapshotSchema.safeParse(input).success||byteLength(JSON.stringify(input))>262144)throw Error('agent_input_too_large');const tool=name as CanvasToolName,value=canvasToolSchemas[tool].parse(input);if((tool==='canvas_propose_ops'||tool==='canvas_apply_proposal')&&s.grant.access!=='propose')throw Error('agent_propose_permission_required');if(tool==='canvas_request_run'&&s.grant.scope!=='project'&&(value as {nodeIds:string[]}).nodeIds.some(id=>!s.grant.nodeIds.includes(id)))throw Error('agent_node_scope');return {tool,value};}
export const canvasToolDefinitions=Object.entries(canvasToolSchemas).map(([name,schema])=>({name,description:({canvas_get_state:'读取浏览器当前授权范围的已保存画布，不含授权或执行请求',canvas_get_selection:'读取当前授权范围内的选区',canvas_propose_ops:'保存结构化创作提案；不自动应用',canvas_apply_proposal:'请求浏览器审阅提案；应用须由用户明确确认',canvas_request_run:'请求浏览器预检和独立收费确认；不会直接提交生成'} as Record<string,string>)[name],inputSchema:z.toJSONSchema(schema),annotations:{readOnlyHint:name==='canvas_get_state'||name==='canvas_get_selection',destructiveHint:false,openWorldHint:false}}));
export async function handleCanvasTool(name:string,input:unknown,session:AgentSession,bridge?:CanvasToolBridge):Promise<ToolResult>{try{const {tool,value}=validateCanvasToolInput(name,input,session);if(!bridge)throw Error('canvas_not_connected');let result:ToolResult;if(tool==='canvas_get_state'||tool==='canvas_get_selection')result=await readCanvasTool(tool,session,bridge);else if(tool==='canvas_request_run')result=await requestCanvasRun(value,session,bridge);else result=await proposeCanvasTool(tool,value,session,bridge);if(!snapshotSchema.safeParse(result).success||byteLength(JSON.stringify(result))>262144)throw Error('agent_response_too_large');return result;}catch(error){return {status:'rejected',errorCode:error instanceof Error&&/^[a-z_]+$/.test(error.message)?error.message:'canvas_tool_input_invalid'};}}
