import {createServer,type IncomingMessage,type ServerResponse} from 'node:http';
import {randomBytes,timingSafeEqual} from 'node:crypto';
import {z} from 'zod';
import {canvasIdentitySchema,agentGrantSchema} from '../../src/domain/agent-session';
import {AgentSessionStore} from './session';
import {permittedOrigin} from './origin-policy';
const sessionRequest=z.strictObject({sessionId:z.string().min(1).max(256)}),grantRequest=sessionRequest.extend({grant:agentGrantSchema,fullProjectConfirmed:z.boolean().optional()}),heartbeatRequest=sessionRequest.extend({identity:canvasIdentitySchema});
async function readJson(req:IncomingMessage){if(!req.headers['content-type']?.startsWith('application/json'))throw Error('content_type_required');let size=0;const parts:Buffer[]=[];for await(const chunk of req){const part=Buffer.from(chunk);size+=part.length;if(size>262144)throw Error('agent_input_too_large');parts.push(part);}return JSON.parse(Buffer.concat(parts).toString('utf8'));}
function send(res:ServerResponse,status:number,value:unknown){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(value));}
export async function startCompanion(options:{allowedOrigins:string[];port?:number;now?:()=>number}){const allowedOrigins=[...options.allowedOrigins];if(!allowedOrigins.length||allowedOrigins.some(origin=>!permittedOrigin(origin,allowedOrigins)))throw Error('origin_configuration_invalid');const token='studio-agent-'+randomBytes(32).toString('base64url'),store=new AgentSessionStore(options.now),server=createServer((req,res)=>{void handle(req,res).catch(error=>{if(!res.headersSent)send(res,400,{ok:false,errorCode:error instanceof Error&&/^[a-z_]+$/.test(error.message)?error.message:'agent_request_invalid'});});});let host='';
 async function handle(req:IncomingMessage,res:ServerResponse){if(req.socket.remoteAddress!=='127.0.0.1'||req.headers.host!==host)return send(res,403,{ok:false,errorCode:'host_denied'});const path=new URL(req.url??'/', 'http://'+host);if(path.searchParams.has('token')||path.searchParams.has('key'))return send(res,400,{ok:false,errorCode:'url_credential_denied'});const origin=req.headers.origin,browserPath=path.pathname.startsWith('/canvas/');if(origin!==undefined&&!permittedOrigin(origin,allowedOrigins)||browserPath&&!permittedOrigin(origin,allowedOrigins))return send(res,403,{ok:false,errorCode:'origin_denied'});if(origin){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');}if(req.method==='OPTIONS'){if(!origin)return send(res,403,{ok:false,errorCode:'origin_denied'});res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Authorization, Content-Type, X-Studio-Browser');if(req.headers['access-control-request-private-network']==='true')res.setHeader('Access-Control-Allow-Private-Network','true');res.writeHead(204);res.end();return;}const credential=req.headers.authorization?.replace(/^Bearer /,'')??'',left=Buffer.from(credential),right=Buffer.from(token);if(left.length!==right.length||!timingSafeEqual(left,right))return send(res,401,{ok:false,errorCode:'agent_token_required'});
 try{if(req.method==='GET'&&path.pathname==='/health')return send(res,200,{ok:true,protocol:'aiwork-studio-agent-v1',generationBackend:false,hostAdapter:'not-configured'});if(req.method==='GET'&&path.pathname==='/agent/state')return send(res,200,{ok:true,session:store.read(path.searchParams.get('sessionId')??undefined)});if(req.method!=='POST')return send(res,405,{ok:false,errorCode:'method_denied'});const body=await readJson(req),nonce=typeof req.headers['x-studio-browser']==='string'?req.headers['x-studio-browser']:undefined;
 if(path.pathname==='/canvas/connect'){const identity=canvasIdentitySchema.parse(body);return send(res,200,{ok:true,...store.connect(identity,origin!)});}if(path.pathname==='/canvas/authorize'){const input=grantRequest.parse(body);return send(res,200,{ok:true,session:store.authorize(input.sessionId,nonce,origin!,input.grant,input.fullProjectConfirmed)});}if(path.pathname==='/canvas/heartbeat'){const input=heartbeatRequest.parse(body);return send(res,200,{ok:true,session:store.heartbeat(input.sessionId,nonce,origin!,input.identity)});}if(path.pathname==='/canvas/disconnect'){const input=sessionRequest.parse(body);return send(res,200,{ok:true,session:store.disconnect(input.sessionId,nonce,origin!)});}return send(res,404,{ok:false,errorCode:'route_denied'});
 }catch(error){const code=error instanceof Error&&/^[a-z_]+$/.test(error.message)?error.message:'agent_request_invalid';send(res,['canvas_not_connected','agent_session_expired'].includes(code)?409:403,{ok:false,errorCode:code});}}
 server.requestTimeout=10000;server.headersTimeout=10000;await new Promise<void>((resolve,reject)=>{server.once('error',reject);server.listen(options.port??0,'127.0.0.1',resolve);});const address=server.address();if(!address||typeof address==='string')throw Error('listen_failed');host='127.0.0.1:'+address.port;return {server,token,store,url:'http://'+host,close:()=>{store.clear();server.closeIdleConnections();return new Promise<void>(resolve=>server.close(()=>resolve()));}};}
