import {useEffect,useRef,useState} from 'react';
import type {Project} from '../../domain/project';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
import {Toast} from '../../ui/Toast';
import {LocalLink,navigate} from '../../app/routes';
import {displayUtcTime} from '../../ui/copy.zh-CN';
import {createProject,cloneProject,listProjects,updateProjectMetadata,getProjectWriter,projectError} from './project-service';
import {getDeletionImpact,deleteLocalResource,type DeletionImpact} from './delete-policy';
import {getPreferences,savePreferences} from '../settings/preferences-store';
import {ProjectDetails} from './ProjectDetails';
export function ProjectsPage(){
 const [projects,setProjects]=useState<Project[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [batchFailures,setBatchFailures]=useState<{id:string;title:string;message:string}[]>([]);
 const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[sort,setSort]=useState(()=>getPreferences().projectSort),[list,setList]=useState(()=>getPreferences().projectList),[selection,setSelection]=useState<Set<string>>(new Set());
 const [mode,setMode]=useState<'create'|'clone'|'rename'|'delete'|'batch-archive'|'template'|null>(()=>new URLSearchParams(location.search).get('create')==='1'?'create':null);
 const [target,setTarget]=useState<Project|null>(null),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[includeHistory,setIncludeHistory]=useState(true),[detailsId,setDetailsId]=useState<string|null>(null),[impact,setImpact]=useState<DeletionImpact|null>(null),[busy,setBusy]=useState(false),inFlight=useRef(false);
 const refresh=async()=>{const rows=await listProjects();setProjects(rows.filter(p=>p.trashedAt===null));setLoading(false);};
 useEffect(()=>{refresh().catch(error=>{setLoading(false);setError(projectError(error));});},[]);
 const perform=async(action:()=>Promise<void>)=>{if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{await action();}catch(error){setError(projectError(error));}finally{inFlight.current=false;setBusy(false);}};
 const open=(next:typeof mode,project?:Project)=>{setError('');setTarget(project??null);setTitle(next==='clone'&&project?([...project.title].length<=57?project.title+' 副本':project.title):project?.title??'');setDescription(project?.description??'');setIncludeHistory(true);setMode(next);};
 const visible=projects.filter(p=>(filter==='all'||filter==='archived'&&p.archived||filter==='starred'&&p.starred||filter==='active'&&!p.archived)&&p.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):b.updatedAt-a.updatedAt||a.id.localeCompare(b.id));
 const toggle=(id:string)=>setSelection(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;});
 const deletePrompt=(project:Project)=>perform(async()=>{const value=await getDeletionImpact({kind:'project',id:project.id,mode:'soft'});setImpact(value);open('delete',project);});
 async function saveForm(){
  await perform(async()=>{
   if(mode==='create'){const project=await createProject({title,description});setMode(null);navigate('/projects/'+encodeURIComponent(project.id)+'/canvas');}
   else if(mode==='clone'&&target){await cloneProject(target.id,{title,description,includeReadonlyHistory:includeHistory});setMode(null);setMessage('已创建本地副本；无运行队列与授权。');await refresh();}
   else if(mode==='rename'&&target){await updateProjectMetadata(target.id,target.revision,{title,description});setMode(null);await refresh();setMessage('项目已保存');}
  });
 }
 return <section><div className="page-header"><div className="actions"><Button variant="primary" data-interaction-id="P-01" onClick={()=>open('create')}>新建项目</Button><Button data-interaction-id="P-02" onClick={()=>open('template')}>使用本地模板</Button><LocalLink data-interaction-id="ui:ProjectsPage:LocalLink:83c7c6da1f3c" href="/trash">回收站</LocalLink></div></div>{error&&mode===null?<Toast kind="error">{error}</Toast>:null}{message?<Toast kind={batchFailures.length?'warning':'success'} onClose={()=>setMessage('')}>{message}</Toast>:null}{batchFailures.length?<section className="banner warning" data-testid="batch-failures"><h3>未完成的项目</h3><ul>{batchFailures.map(item=><li key={item.id}>{item.title}：{item.message}</li>)}</ul><Button data-interaction-id="ui:ProjectsPage:Button:d11d2e484ff2" onClick={()=>{setBatchFailures([]);setMessage('');}}>关闭批量结果</Button></section>:null}
 <div className="actions project-filters"><label>搜索项目<input data-interaction-id="P-12" type="search" value={query} onChange={event=>setQuery(event.target.value)}/></label><label>分类<select data-interaction-id="ui:ProjectsPage:select:a2cbd433bafd" value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">全部项目</option><option value="active">未归档</option><option value="starred">收藏</option><option value="archived">归档</option></select></label><label>排序<select value={sort} data-interaction-id="P-12" onChange={event=>{const value=event.target.value==='title'?'title':'updated';setSort(value);if(!savePreferences({projectSort:value}).persisted)setError('排序偏好未保存，当前视图仍可使用。');}}><option value="updated">最近修改</option><option value="title">名称</option></select></label><Button data-interaction-id="P-13" aria-pressed={list} onClick={()=>{const next=!list;setList(next);if(!savePreferences({projectList:next}).persisted)setError('视图偏好未保存，当前视图仍可使用。');}}>{list?'网格视图':'列表视图'}</Button></div>
 {selection.size?<div className="banner actions"><strong>已选择 {selection.size} 项</strong><small>包含筛选范围外已选项目</small><Button data-interaction-id="P-10" disabled={busy} onClick={()=>setMode('batch-archive')}>批量归档</Button><Button data-interaction-id="P-11" disabled={busy} onClick={()=>navigate('/projects/packages?projectIds='+encodeURIComponent(Array.from(selection).join(',')))}>批量导出所选项目</Button><Button data-interaction-id="ui:ProjectsPage:Button:7a221c20f930" onClick={()=>setSelection(new Set())}>清除选择</Button></div>:null}
 {loading?<p role="status">正在读取本地项目…</p>:!visible.length?<div className="card empty-state"><h2>{query?'没有匹配项目':'从一个项目开始'}</h2><p>本地整理不会创建生成任务。</p><Button data-interaction-id="ui:ProjectsPage:Button:4b18a70737b2" onClick={()=>open('create')}>创建第一个项目</Button></div>:<div className={list?'project-list':'project-grid'}>{visible.map(project=><article key={project.id} className="card project-card" data-testid={'project-'+project.id}><label className="project-select"><input data-interaction-id="P-09" type="checkbox" aria-label={'选择'+project.title} checked={selection.has(project.id)} onChange={()=>toggle(project.id)}/><small>{project.archived?'已归档':'本地项目'}</small></label><h2><LocalLink data-interaction-id="P-03" href={'/projects/'+encodeURIComponent(project.id)+'/canvas'}>{project.title}</LocalLink></h2><p className="muted">{project.description||'暂无项目说明'}</p><small>{displayUtcTime(project.updatedAt)} · 修订 {project.revision}</small><div className="actions"><Button data-interaction-id="P-06" aria-pressed={!!project.starred} disabled={busy} onClick={()=>perform(async()=>{await updateProjectMetadata(project.id,project.revision,{starred:!project.starred});await refresh();})}>{project.starred?'取消收藏':'收藏'}</Button><Button data-interaction-id="P-07" disabled={busy} onClick={()=>perform(async()=>{await updateProjectMetadata(project.id,project.revision,{archived:!project.archived});await refresh();})}>{project.archived?'取消归档':'归档'}</Button><Button data-interaction-id="P-04" onClick={()=>open('rename',project)}>重命名</Button><Button data-interaction-id="P-05" onClick={()=>open('clone',project)}>复制项目</Button><Button data-interaction-id="P-08" variant="danger" disabled={busy} onClick={()=>deletePrompt(project)}>移入回收站</Button><Button data-interaction-id="P-14" onClick={()=>setDetailsId(project.id)}>详情</Button></div></article>)}</div>}
 <Dialog open={mode==='create'||mode==='clone'||mode==='rename'} title={mode==='clone'?'复制项目':mode==='rename'?'重命名项目':'新建项目'} onClose={()=>setMode(null)} dismissible={!busy} width={480}><form className="form-stack" onSubmit={event=>{event.preventDefault();void saveForm();}}><label>{mode==='clone'?'副本名称':'项目名称'}<input data-interaction-id="ui:ProjectsPage:input:dd0a8dfd62f9" value={title} onChange={event=>setTitle(event.target.value)} autoComplete="off"/></label><label>项目说明<textarea data-interaction-id="ui:ProjectsPage:textarea:589f6131dce4" value={description} onChange={event=>setDescription(event.target.value)}/></label>{mode==='clone'?<><label className="checkbox-label"><input data-interaction-id="ui:ProjectsPage:input:441176a43036" type="checkbox" checked={includeHistory} onChange={event=>setIncludeHistory(event.target.checked)}/>保留历史结果引用（只读）</label><small>共享素材，复制结构；不复制任务、Key、队列或执行授权。</small></>:null}{error?<p role="alert" className="banner error">{error}</p>:null}<div className="actions"><Button data-interaction-id="ui:ProjectsPage:Button:e9c342f92b84" type="button" disabled={busy} onClick={()=>setMode(null)}>取消</Button><Button data-interaction-id="ui:ProjectsPage:Button:247e893e2acd" type="submit" variant="primary" busy={busy}>{mode==='clone'?'创建副本':mode==='rename'?'保存':'创建'}</Button></div></form></Dialog>
 <Dialog open={mode==='delete'} title="移入项目回收站" onClose={()=>setMode(null)} dismissible={!busy} width={560} footer={<><Button data-interaction-id="ui:ProjectsPage:Button:7d0e6aa3d9ba" disabled={busy} onClick={()=>setMode(null)}>返回</Button><Button data-interaction-id="ui:ProjectsPage:Button:3a3f92b220e2" variant="danger" busy={busy} onClick={()=>perform(async()=>{if(!target||!impact)return;const lease=await getProjectWriter(target.id);const result=await deleteLocalResource(impact.target,{impactHash:impact.impactHash,displayedCounts:impact.displayedCounts},{lease,expectedRevision:target.revision});if(!result.success)throw new Error(result.errorCode);setMode(null);await refresh();setSelection(current=>{const next=new Set(current);next.delete(target.id);return next;});setMessage('已移入本地回收站，任务追踪保留。');})}>移入回收站</Button></>}><p>远端任务仍可能继续。移入本地回收站不会取消任务或退款。</p><p>活动或未知任务 {impact?.activeRuns.length??0} 项；素材 {impact?.referencedAssets.length??0} 项，其中共享或历史引用 {impact?.sharedAssets.length??0} 项。</p>{error?<p role="alert" className="banner error">{error}</p>:null}</Dialog>
 <Dialog open={mode==='batch-archive'} title="批量归档" onClose={()=>setMode(null)} dismissible={!busy} footer={<><Button data-interaction-id="ui:ProjectsPage:Button:1f72d6dcdd10" onClick={()=>setMode(null)}>返回</Button><Button data-interaction-id="ui:ProjectsPage:Button:15f30fe5b0b4" busy={busy} onClick={()=>perform(async()=>{let succeeded=0,failed=0;const failures:{id:string;title:string;message:string}[]=[];for(const id of selection){const project=projects.find(p=>p.id===id);if(!project){failed++;failures.push({id,title:id,message:'项目已不在当前列表，请刷新核对。'});continue;}try{await updateProjectMetadata(project.id,project.revision,{archived:true});succeeded++;}catch(error){failed++;failures.push({id:project.id,title:project.title,message:projectError(error)});}}setMode(null);await refresh();setBatchFailures(failures);setMessage('成功 '+succeeded+'，失败 '+failed);})}>{'归档 '+selection.size+' 项'}</Button></>}><p>已选择 {selection.size} 个本地项目，包含当前筛选范围外的已选项。归档不停止远端任务。</p></Dialog>
 <Dialog open={mode==='template'} title="使用本地模板" onClose={()=>setMode(null)} dismissible={!busy}>{error?<p role="alert">{error}</p>:null}<p>原创静态结构：创作需求与分镜约束两个文本节点，无模型执行授权。</p><Button data-interaction-id="ui:ProjectsPage:Button:354edfed1cb8" busy={busy} onClick={()=>perform(async()=>{const project=await createProject({title:'原创分镜草稿',template:'original-shot-draft'});setMode(null);navigate('/projects/'+encodeURIComponent(project.id)+'/canvas');})}>创建原创分镜草稿</Button></Dialog>
 <LocalLink data-interaction-id="ui:ProjectsPage:LocalLink:6e4444130ef9" href="/projects/packages">项目导入导出与备份</LocalLink><ProjectDetails projectId={detailsId} onClose={()=>setDetailsId(null)}/>
 </section>;
}

