import {useEffect,useRef,useState} from 'react';
import type {Project} from '../../domain/project';
import {listTrashedProjects,restoreProject} from './trash-service';
import {getProjectWriter,projectError} from './project-service';
import {getDeletionImpact,deleteLocalResource,type DeletionImpact} from './delete-policy';
import {Dialog} from '../../ui/Dialog';
import {Button} from '../../ui/Button';
import {LocalLink} from '../../app/routes';
import {Toast} from '../../ui/Toast';
export function TrashPage(){
 const [projects,setProjects]=useState<Project[]>([]),[target,setTarget]=useState<Project|null>(null),[impact,setImpact]=useState<DeletionImpact|null>(null),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),inFlight=useRef(false);
 const [selection,setSelection]=useState<Set<string>>(new Set()),[batch,setBatch]=useState<{project:Project;impact:DeletionImpact}[]|null>(null),[names,setNames]=useState<Record<string,string>>({}),[batchMessage,setBatchMessage]=useState('');
 const safe=batch?.filter(item=>item.impact.deletable)??[];
 const toggle=(id:string)=>setSelection(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;});
 const refresh=async()=>setProjects(await listTrashedProjects());
 useEffect(()=>{refresh().catch(error=>setError(projectError(error)));},[]);
 const perform=async(action:()=>Promise<void>)=>{if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{await action();}catch(error){setError(projectError(error));}finally{inFlight.current=false;setBusy(false);}};
 return <section><p>不会自动清空回收站。恢复与删除仅作用于本地数据。</p><LocalLink data-interaction-id="ui:TrashPage:LocalLink:7e9d2c5477b0" href="/projects">返回项目</LocalLink>{error?<Toast kind="error">{error}</Toast>:null}{batchMessage?<Toast kind="warning">{batchMessage}</Toast>:null}{selection.size?<div className="banner actions"><strong>已选择 {selection.size} 项</strong><Button data-interaction-id="Z-03" disabled={busy} onClick={()=>perform(async()=>{const items=[];for(const project of projects.filter(p=>selection.has(p.id)))items.push({project,impact:await getDeletionImpact({kind:'project',id:project.id,mode:'permanent'})});setNames({});setBatch(items);})}>批量永久删除</Button></div>:null}{!projects.length?<section className="card empty-state"><h2>回收站为空</h2></section>:<div className="project-grid">{projects.map(project=><article className="card" key={project.id} data-testid={'trash-'+project.id}><label className="checkbox-label"><input data-interaction-id="ui:TrashPage:input:8a96883cd61d" type="checkbox" aria-label={'选择'+project.title} checked={selection.has(project.id)} onChange={()=>toggle(project.id)}/>{project.title}</label><h2>{project.title}</h2><div className="actions"><Button data-interaction-id="Z-01" disabled={busy} onClick={()=>perform(async()=>{const lease=await getProjectWriter(project.id),result=await restoreProject(project.id,{lease,expectedRevision:project.revision});if(!result.success)throw new Error(result.errorCode);await refresh();})}>恢复项目</Button><Button data-interaction-id="Z-02" variant="danger" disabled={busy} onClick={()=>perform(async()=>{const impact=await getDeletionImpact({kind:'project',id:project.id,mode:'permanent'});setTarget(project);setImpact(impact);setName('');})}>永久删除本地副本</Button></div></article>)}</div>}
 <Dialog open={!!target} title="永久删除本地副本" onClose={()=>setTarget(null)} dismissible={!busy} width={560} footer={<><Button data-interaction-id="ui:TrashPage:Button:1b58c58ed91e" disabled={busy} onClick={()=>setTarget(null)}>返回</Button><Button data-interaction-id="ui:TrashPage:Button:19ea2eaf6e16" variant="danger" disabled={!impact?.deletable||name!==target?.title} disabledReason={!impact?.deletable?'存在活动或未知任务，唯一追踪记录不能删除。':name!==target?.title?'输入完整项目名称后才能确认。':undefined} busy={busy} onClick={()=>perform(async()=>{if(!target||!impact)return;const lease=await getProjectWriter(target.id),result=await deleteLocalResource(impact.target,{impactHash:impact.impactHash,displayedCounts:impact.displayedCounts,projectTitle:name},{lease,expectedRevision:target.revision});if(!result.success)throw new Error(result.errorCode);setTarget(null);await refresh();})}>永久删除</Button></>}><p>此操作不可撤销；保留共享素材及历史任务证据，不会请求远端取消。</p>{impact?.activeRuns.length?<p role="alert">此项目有 {impact.activeRuns.length} 项活动或未知任务，不能删除唯一追踪。</p>:null}<label>完整项目名称<input data-interaction-id="ui:TrashPage:input:7bfb40f16fb4" value={name} onChange={event=>setName(event.target.value)} autoComplete="off"/></label></Dialog>
 <Dialog open={!!batch} title="批量永久删除本地副本" onClose={()=>setBatch(null)} dismissible={!busy} width={720} footer={<><Button data-interaction-id="ui:TrashPage:Button:79b26aee3b42" disabled={busy} onClick={()=>setBatch(null)}>返回</Button><Button data-interaction-id="ui:TrashPage:Button:3e6b910be184" variant="danger" disabled={!safe.length||safe.some(item=>names[item.project.id]!==item.project.title)} disabledReason="逐项输入安全项目名称后确认数量；被阻止项不会删除。" busy={busy} onClick={()=>perform(async()=>{let succeeded=0,failed=0;const failures:string[]=[];for(const item of batch??[]){if(!item.impact.deletable){failed++;failures.push(item.project.title+'：活动或未知任务等条件阻止删除');continue;}try{const lease=await getProjectWriter(item.project.id),result=await deleteLocalResource(item.impact.target,{impactHash:item.impact.impactHash,displayedCounts:item.impact.displayedCounts,projectTitle:names[item.project.id]},{lease,expectedRevision:item.project.revision});if(!result.success)throw new Error(result.errorCode);succeeded++;}catch{failed++;failures.push(item.project.title+'：本地删除失败，请重新检查影响');}}setBatch(null);setSelection(new Set());await refresh();setBatchMessage('成功 '+succeeded+'，失败 '+failed+(failures.length?'。'+failures.join('；'):''));})}>{'永久删除 '+safe.length+' 项'}</Button></>}><p>可删除 {safe.length}，阻止 {(batch?.length??0)-safe.length}。不会取消远端任务，历史任务与共享素材保留。</p><div className="form-stack">{batch?.map(item=>item.impact.deletable?<label key={item.project.id}>{'确认'+item.project.title+'名称'}<input data-interaction-id="ui:TrashPage:input:93bc2d02b83e" value={names[item.project.id]??''} onChange={event=>setNames(current=>({...current,[item.project.id]:event.target.value}))} autoComplete="off"/></label>:<p key={item.project.id} role="alert">{item.project.title}：活动或未知任务等条件阻止删除。</p>)}</div></Dialog>
 </section>;
}
