import {useEffect,useState} from 'react';
import type {PromptDraft} from '../../domain/prompt';
import {getActiveCore} from '../../adapters/core/current-connection';
import {isTextOnlyModel} from '../../application/prompts/text-model-policy';
import {preparePromptOptimization,type ApprovedPromptInput,type PromptOptimizationPreview} from '../../application/prompts/optimize-text';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
export function AIOptimizeDialog({draft,onClose,onConfirm}:{draft:PromptDraft;onClose:()=>void;onConfirm:(input:ApprovedPromptInput)=>Promise<void>}){
 const active=getActiveCore(),models=active?.capability.textModels.filter(id=>isTextOnlyModel(id,active.capability))??[],[model,setModel]=useState(''),[aliases,setAliases]=useState<string[]>([]),[preview,setPreview]=useState<PromptOptimizationPreview>(),[ack,setAck]=useState(false),[priorAck,setPriorAck]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{setPreview(undefined);setAck(false);setPriorAck(false);},[model,aliases]);
 return <Dialog open title="AI文字优化确认" width={720} onClose={onClose} dismissible={!busy} footer={<><Button disabled={busy} onClick={onClose}>取消</Button><Button disabled={busy||!preview||!ack||!!preview.priorUnknownRunIds.length&&!priorAck} onClick={async()=>{if(!preview||!ack||preview.priorUnknownRunIds.length&&!priorAck)return;setBusy(true);try{await onConfirm({preview,decision:{confirmed:true,acknowledgeTextFee:true,...(priorAck?{acknowledgePriorUnknown:true as const}:{})}});}catch{setError('草稿、授权、确认或存储已变化；请保留原文并重新预览。');}finally{setBusy(false);}}}>确认文字请求</Button></>}>
 <p>这是单独的文字调用，可能产生费用且金额未知。媒体二进制不会发送；返回内容只是候选结果，视频生成另行确认。</p><label>文字模型<select aria-label="文字模型" value={model} disabled={busy} onChange={event=>setModel(event.target.value)}><option value="">请选择已核验的文字模型</option>{models.map(id=><option value={id} key={id}>{id}</option>)}</select></label><p>服务：{active?.client.profile.name??'未连接'} · 输入修订 {draft.revision}</p>
 <fieldset><legend>本次发送的参考说明（默认不勾选）</legend>{draft.references.map(ref=><label className="generation-ack" key={ref.alias}><input type="checkbox" disabled={busy} checked={aliases.includes(ref.alias)} onChange={event=>setAliases(current=>event.target.checked?[...current,ref.alias]:current.filter(alias=>alias!==ref.alias))}/>{ref.alias} · {ref.description}</label>)}{!draft.references.length?<p>本次没有参考说明。</p>:null}</fieldset><Button disabled={busy||!model||!active} onClick={async()=>{const current=getActiveCore();if(!current)return;setBusy(true);setError('');try{setPreview(await preparePromptOptimization(draft.id,{textModelId:model,referenceAliases:aliases},current));setAck(false);setPriorAck(false);}catch{setError('预览受阻：请检查文字模型、输入冲突、存储和文本限制。');}finally{setBusy(false);}}}>预览文字请求</Button>
 {preview?<><h3>将发送的确切文字请求</h3><pre>{preview.requestSnapshot}</pre><label className="generation-ack"><input type="checkbox" checked={ack} disabled={busy} onChange={event=>setAck(event.target.checked)}/>我确认文字请求，并知悉可能产生费用且金额未知</label>{preview.priorUnknownRunIds.length?<><p className="banner warning">旧文字请求结果或账务尚未核对。新请求使用新的身份，可能再次产生费用，不会替换或取消旧请求。</p><label className="generation-ack"><input type="checkbox" checked={priorAck} disabled={busy} onChange={event=>setPriorAck(event.target.checked)}/>我已核对旧请求，仍确认创建新的文字请求</label></>:null}</>:null}{error?<p role="alert">{error}</p>:null}
 </Dialog>;
}
