import {useEffect,useState} from 'react';
import type {PromptDraft,PromptResultVersion} from '../../domain/prompt';
import type {CapabilityProfile} from '../../domain/connection';
import type {VideoSpec} from '../../domain/common';
import {readGraph} from '../../infrastructure/storage/project-repository';
import {Dialog} from '../../ui/Dialog';
import {Button} from '../../ui/Button';
import {applyPromptToCanvas,type ApplyPromptInput} from '../../application/commands/prompt-to-canvas';
import {promptCanvasError,type CanvasPromptCommit} from './InsertTargetDialog';
import {navigate} from '../../app/routes';
export function ApplyPromptDialog({draft,result,capability,onClose,onInsert,onCommit}:{draft:PromptDraft;result:PromptResultVersion;capability:CapabilityProfile;onClose:()=>void;onInsert:()=>void;onCommit?:CanvasPromptCommit}){
 const [old,setOld]=useState(''),[revision,setRevision]=useState<number>(),[video,setVideo]=useState<VideoSpec>(),[acceptSpec,setAcceptSpec]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[id,setId]=useState(()=>crypto.randomUUID());
 const candidate=video?{modelId:video.modelId,...result.suggestedSpec,...(video.resolution?{resolution:video.resolution}:{})}:undefined;
 const describeSpec=(spec:VideoSpec|undefined)=>spec?`${spec.modelId} · ${spec.durationSeconds??'未指定'} 秒 · ${spec.ratio??'未指定画幅'}${spec.resolution?' · '+spec.resolution:''}`:'未指定';
 const canAccept=!!candidate&&capability.verification!=='unknown'&&capability.videoSpecs.some(s=>JSON.stringify(s)===JSON.stringify(candidate));
 async function compare(){try{const graph=await readGraph(draft.sourceProjectId!);const node=graph?.nodes.find(n=>n.id===draft.sourceNodeId);if(!graph||!node||!['text','video-generation'].includes(node.type)||node.locked){setError('源节点无法编辑，请另存为新节点。');setRevision(undefined);return;}setVideo(node.type==='video-generation'?node.data.draft:undefined);setAcceptSpec(false);setOld(node.type==='text'?node.data.text:graph.edges.filter(e=>e.targetId===node.id&&e.port==='text').map(e=>graph.nodes.find(n=>n.id===e.sourceId)).map(n=>n?.type==='text'?n.data.text:'').join('\n\n'));setRevision(graph.revision);setId(crypto.randomUUID());setError(graph.revision===draft.sourceRevision?'':'来源版本已变化，已显示最新原文；接受后按此版本保存。');}catch{setError('源节点读取失败，草稿保留。');}}
 useEffect(()=>{void compare();},[draft.id,draft.sourceNodeId,result.id]);
 async function apply(){if(revision===undefined)return;setBusy(true);try{const input:ApplyPromptInput={draftId:draft.id,resultVersionId:result.id,targetProjectId:draft.sourceProjectId!,targetNodeId:draft.sourceNodeId,baseRevision:revision,sourceRevision:revision,mode:'apply',commandId:id,...(acceptSpec&&candidate?{acceptedVideoSpec:candidate}:{})};const receipt=await(onCommit??applyPromptToCanvas)(input);if(receipt.status==='applied'||receipt.status==='replayed'){onClose();navigate('/projects/'+encodeURIComponent(draft.sourceProjectId!)+'/canvas?node='+encodeURIComponent(draft.sourceNodeId!));}else setError(promptCanvasError(receipt.errorCode));}catch{setError('应用未保存；正文保留，请重试。');}finally{setBusy(false);}}
 return <Dialog open title="应用提示词到节点" dismissible={!busy} onClose={onClose} width={960} footer={<><Button data-interaction-id="ui:ApplyPromptDialog:Button:59bcccc6200b" disabled={busy} onClick={onClose}>返回编辑</Button><Button data-interaction-id="ui:ApplyPromptDialog:Button:593e93bf5c43" disabled={busy} onClick={onInsert}>另存新节点</Button><Button data-interaction-id="ui:ApplyPromptDialog:Button:cb4c39473eb8" disabled={busy} onClick={()=>void compare()}>重新比较</Button><Button data-interaction-id="ui:ApplyPromptDialog:Button:13cab6ea0c26" variant="primary" busy={busy} disabled={revision===undefined} onClick={()=>void apply()}>接受并应用</Button></>}><p>替换所示提示词并标记下游待更新，不触发视频执行。来源输入修订 {result.sourceRevision}，目标画布修订 {revision??'未读取'}。</p>{video?<><p>将新建提示词节点并替换此视频配置的文本连线，原文本节点保留；其他素材连线保留。</p><p>当前视频参数：{describeSpec(video)}；建议参数：{describeSpec(candidate)}</p><label className="prompt-reference-choice"><input data-interaction-id="ui:ApplyPromptDialog:input:fb464b59ee06" type="checkbox" aria-label="接受视频参数变更" disabled={!canAccept} checked={acceptSpec} onChange={e=>setAcceptSpec(e.target.checked)}/>接受视频参数变更</label><small>{canAccept?'勾选后按所示完整规格保存。':'建议规格尚未核验，视频参数保持原值。'}未勾选时视频参数保持原值，执行仍须另行检查。</small></>:null}<div className="form-row"><label>原节点文字<textarea data-interaction-id="ui:ApplyPromptDialog:textarea:5eb7a3a19f67" aria-label="原节点文字" value={old} readOnly/></label><label>将应用的文字<textarea data-interaction-id="ui:ApplyPromptDialog:textarea:ab568fd9070a" aria-label="将应用的文字" value={result.finalPrompt} readOnly/></label></div>{error?<p className="banner warning" role="alert">{error}</p>:null}</Dialog>;
}
