import {useEffect,useState} from 'react';
import type {Project} from '../../domain/project';
import type {CapabilityProfile} from '../../domain/connection';
import {listProjects} from '../projects/project-service';
import {readGraph} from '../../infrastructure/storage/project-repository';
import {Dialog} from '../../ui/Dialog';
import {Button} from '../../ui/Button';
import {applyPromptToCanvas,previewPromptCanvas,type ApplyPromptInput} from '../../application/commands/prompt-to-canvas';
import type {CommandReceipt,GraphOperation} from '../../application/commands/registry';
import {navigate} from '../../app/routes';
export type CanvasPromptCommit=(input:ApplyPromptInput)=>Promise<CommandReceipt>;
export const promptCanvasError=(code?:string)=>/revision|preview_changed/.test(code??'')?'项目或来源版本已变化；请重新比较或刷新目标后确认。':/lease|writer/.test(code??'')?'此项目正在其他标签页编辑，请先在画布接管编辑。':/quota|abort/.test(code??'')?'存储写入失败，本次没有留下节点或连线；草稿保留，可重试。':/capability|spec|reference|asset|constraint|locked/.test(code??'')?'规格、锁定要求或素材尚不能用于此流程，请返回写作检查。':'本次未保存，草稿保留。请重新选择目标或检查本地存储。';
export function InsertTargetDialog({draftId,resultVersionId,flow,capability,onClose,onCommit}:{draftId:string;resultVersionId:string;flow:boolean;capability:CapabilityProfile;onClose:()=>void;onCommit?:CanvasPromptCommit}){
 const [projects,setProjects]=useState<Project[]>([]),[project,setProject]=useState(''),[revision,setRevision]=useState<number>(),[x,setX]=useState(64),[y,setY]=useState(64),[specIndex,setSpecIndex]=useState(''),[preview,setPreview]=useState<GraphOperation[]>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[id]=useState(()=>crypto.randomUUID());
 useEffect(()=>{let active=true;void listProjects().then(p=>{if(active)setProjects(p.filter(p=>p.trashedAt===null&&!p.archived));}).catch(()=>{if(active)setError('项目读取失败，请保留草稿后重试。');});return()=>{active=false;};},[]);
 const specs=capability.videoSpecs.filter(s=>capability.videoModels.includes(s.modelId));
 const input:ApplyPromptInput={draftId,resultVersionId,targetProjectId:project,baseRevision:revision??0,mode:'insert',commandId:id,position:{x,y},...(flow&&specIndex!==''?{flow:{spec:specs[Number(specIndex)],capabilityVersion:capability.contractVersion}}:{})};
 useEffect(()=>{let active=true;setPreview(undefined);if(!project||revision===undefined||flow&&specIndex==='')return;void previewPromptCanvas(input).then(p=>{if(active){setPreview(p);setError('');}}).catch(e=>{if(active)setError(promptCanvasError(e instanceof Error?e.message:undefined));});return()=>{active=false;};},[draftId,resultVersionId,project,revision,x,y,specIndex,flow,capability,id]); // Same immutable result and explicit target snapshot.
 async function selectProject(value:string){setProject(value);setRevision(undefined);setPreview(undefined);try{const graph=await readGraph(value);if(graph)setRevision(graph.revision);else setError('目标画布无法读取。');}catch{setError('目标读取失败，草稿保留。');}}
 async function submit(){if(!preview||busy)return;setBusy(true);try{const result=await(onCommit??applyPromptToCanvas)(input);if(result.status==='applied'||result.status==='replayed'){onClose();navigate('/projects/'+encodeURIComponent(project)+'/canvas?node='+encodeURIComponent(id+(flow?':group':':text')));}else setError(promptCanvasError(result.errorCode));}catch{setError('存储提交失败，本次未保存；草稿保留。');}finally{setBusy(false);}}
 return <Dialog open title="选择插入目标" onClose={onClose} dismissible={!busy} footer={<><Button data-interaction-id="ui:InsertTargetDialog:Button:59bcccc6200b" disabled={busy} onClick={onClose}>返回编辑</Button><Button data-interaction-id="ui:InsertTargetDialog:Button:f81c09e9f3cb" disabled={busy||!project} onClick={()=>void selectProject(project)}>刷新目标版本</Button><Button data-interaction-id="ui:InsertTargetDialog:Button:2ab3535fbce3" variant="primary" busy={busy} disabled={!preview} onClick={()=>void submit()}>{flow?'确认仅建流程':'确认插入文本'}</Button></>}><p>{flow?'预览文本、素材连线、视频配置和分组后，一次保存。':'默认新建提示词文本节点。'}此操作不授权生成或收费。</p><label>目标项目<select data-interaction-id="ui:InsertTargetDialog:select:c25d4eed011c" aria-label="目标项目" value={project} onChange={e=>void selectProject(e.target.value)}><option value="">请选择项目</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>{!projects.length?<p>暂无可写项目，请先到项目主页新建；当前草稿保留。</p>:null}<div className="form-row"><label>画布横坐标<input data-interaction-id="ui:InsertTargetDialog:input:306ee1bbe2e3" type="number" value={x} onChange={e=>setX(Number(e.target.value))}/></label><label>画布纵坐标<input data-interaction-id="ui:InsertTargetDialog:input:8a67912ef2d1" type="number" value={y} onChange={e=>setY(Number(e.target.value))}/></label></div>{flow?<label>流程视频规格<select data-interaction-id="ui:InsertTargetDialog:select:beb96cae7cf7" aria-label="流程视频规格" value={specIndex} onChange={e=>setSpecIndex(e.target.value)}><option value="">明确选择已审阅规格</option>{specs.map((s,index)=><option key={index} value={index}>{s.modelId} · {s.durationSeconds??'未指定'}秒 · {s.ratio??'未指定'}{s.resolution?' · '+s.resolution:''}</option>)}</select></label>:null}{preview?<section className="banner"><h3>{flow?'流程预览':'文本插入预览'}</h3><p>{projects.find(p=>p.id===project)?.title} · 修订 {revision} · 位置 ({x}, {y})</p><p>{preview.filter(o=>o.type==='add_node').length} 个新节点{flow?'、显式连线和一个分组；不会创建执行记录。':'；原节点保留。'}</p></section>:null}{error?<p role="alert" className="banner error">{error}</p>:null}</Dialog>;
}
