import {useState} from 'react';
import type {PromptResultVersion,PromptDraft} from '../../domain/prompt';
import {readDraftRevision} from './draft-repository';
import {readPromptRun} from './prompt-run-repository';
import {Dialog} from '../../ui/Dialog';
import {Button} from '../../ui/Button';
export function PromptResultHistory({draftId,open,versions,onClose,onSelect,onRestore}:{draftId:string;open:boolean;versions:PromptResultVersion[];onClose:()=>void;onSelect:(version:PromptResultVersion)=>void;onRestore:(version:PromptResultVersion)=>Promise<void>}){
 const [snapshot,setSnapshot]=useState<{draft:PromptDraft;model?:string}>(),[error,setError]=useState('');
 return <><Dialog open={open} title="提示词结果历史" width={960} onClose={onClose}>{error?<p role="alert">{error}</p>:null}<p>历史结果保留其原始输入修订；恢复新增人工修订，当前输入保持不变。</p>{versions.length?[...versions].reverse().map(version=><article className="card" key={version.id}><h3>{version.origin==='local'?'本地整理':version.origin==='ai'?'AI优化':'人工修订'} · 输入修订 {version.sourceRevision}</h3><small>结果 {version.id} · {version.validationState==='unchecked'?'待检查':version.validationState==='valid'?'规则检查通过':'需人工检查'}</small><pre>{version.finalPrompt}</pre><div className="actions"><Button data-interaction-id="ui:PromptResultHistory:Button:79803ac1c321" onClick={async()=>{try{const draft=await readDraftRevision(draftId,version.sourceRevision);if(!draft)throw new Error("missing");const run=version.promptRunId?await readPromptRun(version.promptRunId):undefined;setSnapshot({draft,model:run?.textModelId});}catch{setError("历史输入快照读取失败；原记录保留。");}}}>查看输入快照</Button><Button data-interaction-id="ui:PromptResultHistory:Button:0affaacbcaff" onClick={()=>onSelect(version)}>查看结果</Button><Button data-interaction-id="ui:PromptResultHistory:Button:c3612f4b5bc6" onClick={()=>onRestore(version)}>恢复结果</Button></div></article>):<p>暂无结果历史。</p>}</Dialog><Dialog open={!!snapshot} title="历史输入快照" onClose={()=>setSnapshot(undefined)}><p>输入修订 {snapshot?.draft.revision} · 规则 {snapshot?.draft.ruleVersion}</p><p>文字模型：{snapshot?.model??"本地或人工修订，无文字模型调用"}</p><h3>原始创意</h3><pre>{snapshot?.draft.userRequest}</pre><h3>当时的目标规格、约束与引用</h3><pre>{snapshot?JSON.stringify({requestedSpec:snapshot.draft.requestedSpec,lockedConstraints:snapshot.draft.lockedConstraints,references:snapshot.draft.references},null,2):""}</pre></Dialog></>;
}
