import {useEffect,useRef,useState} from 'react';
import type {Project} from '../../domain/project';
import {listProjects} from '../projects/project-service';
import {exportProject} from '../../infrastructure/packages/export-project';
import {exportProjectBatch} from '../../infrastructure/packages/export-batch';
import {inspectImport,commitImport,releaseImportPlan,type ImportInspection} from '../../infrastructure/packages/import-project';
import {withDatabase,transact} from '../../infrastructure/storage/database';
import {triggerLocalDownload} from '../../ui/local-download';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
import {LocalLink} from '../../app/routes';
export function PackagePage(){
 const requestedIds=new URLSearchParams(location.search).get('projectIds')?.split(',').filter(Boolean),batchMode=!!requestedIds?.length;
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(()=>new URLSearchParams(location.search).get('projectId')??''),[mode,setMode]=useState<'full'|'structure'>('full'),[exportOpen,setExportOpen]=useState(batchMode),[inspection,setInspection]=useState<ImportInspection>(),[legacy,setLegacy]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');const planRef=useRef<ImportInspection['plan']>(undefined),inFlight=useRef(false);
 const reload=()=>listProjects().then(rows=>{const selected=new URLSearchParams(location.search).get('projectIds')?.split(','),available=rows.filter(p=>p.trashedAt===null&&(!selected||selected.includes(p.id)));setProjects(available);setProjectId(id=>id||available[0]?.id||'');});useEffect(()=>{void reload().catch(()=>setError('项目列表读取失败，原项目保留。'));return()=>{if(planRef.current)releaseImportPlan(planRef.current);};},[]);
 function closeImport(){if(inFlight.current)return;if(planRef.current)releaseImportPlan(planRef.current);planRef.current=undefined;setInspection(undefined);}
 async function run(action:()=>Promise<void>){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{await action();}catch(error){const code=error instanceof Error?error.message:'';setError(code==='package_missing_files'?'本地文件缺失，完整备份未生成；可选择仅结构包。':code==='package_too_large'?'项目超过当前项目包安全初限，请分批导出；没有生成空成功包。':code==='import_storage_budget_exceeded'?'已知本地剩余空间不足，导入未写入；请备份后清理可重建缓存。':'操作未完成，原项目保留；请检查文件完整性和本地存储。');}finally{inFlight.current=false;setBusy(false);}}
 return <section className="card" aria-label="项目导入导出"><p>项目保存在当前浏览器。完整包包含可读本地媒体；仅结构包不含媒体，不能代替完整备份。导出不上传到 Core。</p><div className="actions"><LocalLink data-interaction-id="ui:PackagePage:LocalLink:7e9d2c5477b0" href="/projects">返回项目</LocalLink><LocalLink data-interaction-id="ui:PackagePage:LocalLink:3dbf02f83037" href="/settings/storage">本地数据与备份</LocalLink></div>
 <label>导出项目<select data-interaction-id="ui:PackagePage:select:6eed72ff7fb9" aria-label="导出项目" value={projectId} disabled={busy} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><Button data-interaction-id="D-04" disabled={!projectId||busy} onClick={()=>setExportOpen(true)}>{batchMode?'批量导出项目包':'导出项目包'}</Button>
 <hr/><label className="review-choice"><input data-interaction-id="ui:PackagePage:input:9a5dd6df4777" type="checkbox" checked={legacy} disabled={busy} onChange={e=>setLegacy(e.target.checked)}/>显式启用旧离线格式迁移</label><p>只读取你选择的离线文件，不扫描旧浏览器存储；旧配置、会话、无类型连线不恢复为可执行内容。</p><label>选择项目包<input data-interaction-id="I-01" type="file" accept=".zip,.json,application/zip,application/json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;void run(async()=>{if(planRef.current)releaseImportPlan(planRef.current);planRef.current=undefined;setInspection(undefined);const report=await inspectImport(file,{legacy});if(!report.ok){setError(report.errorCode==='schema_too_new'?'项目版本高于当前客户端，原包保留，不能降版本导入。':report.errorCode==='legacy_explicit_import_required'?'此文件需要你显式启用旧离线格式迁移。':'项目包未通过安全检查；没有导入或执行内容。');setInspection(report);return;}planRef.current=report.plan;setInspection(report);});}}/></label>
 {error?<p role="alert">{error}</p>:null}<p role="status">{message}</p>{inspection&&!inspection.ok&&inspection.original?<Button data-interaction-id="ui:PackagePage:Button:5916ff7fdf7d" disabled={busy} onClick={()=>triggerLocalDownload(inspection.original!,'original-package-preserved.zip')}>保留原始包副本</Button>:null}
 <Dialog title={batchMode?'批量导出项目包':'导出项目包'} open={exportOpen} onClose={()=>{if(!busy)setExportOpen(false);}} footer={<><Button data-interaction-id="ui:PackagePage:Button:1380d32c2cb3" disabled={busy} onClick={()=>setExportOpen(false)}>取消</Button><Button data-interaction-id="D-05" disabled={busy} onClick={()=>void run(async()=>{if(batchMode&&requestedIds!.some(id=>!projects.some(p=>p.id===id)))throw Error('batch_export_selection_invalid');const result=batchMode?await exportProjectBatch(requestedIds!,{mode}):await exportProject(projectId,{mode});triggerLocalDownload(result.blob,result.filename);let recorded=true;await withDatabase(undefined,db=>transact(db,['receipts'],'readwrite',tx=>{const batchId=batchMode?crypto.randomUUID():undefined,createdAt=Date.now();for(const id of batchMode?requestedIds!:[projectId])tx.objectStore('receipts').put({id:crypto.randomUUID(),kind:'project-backup-download-triggered',projectId:id,...batchId?{batchId}:{},mode,bytes:result.bytes,createdAt});})).catch(()=>{recorded=false;});setExportOpen(false);setMessage('已触发浏览器下载；请确认保存位置。'+(mode==='structure'?'仅结构JSON，不含媒体。':'完整本地文件包。')+(recorded?'':'备份记录未保存，请保留本次文件。'));})}>{batchMode?'确认导出 '+requestedIds!.length+' 个项目':'确认导出'}</Button></>}>{batchMode?<p>本次明确导出 {requestedIds!.length} 个项目；包含清单和各自可恢复的项目包。任何一项失败，不生成空成功包。</p>:null}<label>备份范围<select data-interaction-id="ui:PackagePage:select:beec76bc6997" aria-label="备份范围" value={mode} disabled={busy} onChange={e=>setMode(e.target.value as 'full'|'structure')}><option value="full">完整包（结构和本地媒体）</option><option value="structure">仅结构（不含媒体）</option></select></label><p>排除 Key、Token、临时链接、执行授权和自动任务；原服务/任务编号保留为只读来源。256MiB压缩、512MiB展开、单条目200MiB、10000条目为当前防御初限。</p></Dialog>
 <Dialog title="检查项目包" open={!!inspection?.ok} onClose={closeImport} footer={<><Button data-interaction-id="I-07" disabled={busy} onClick={closeImport}>取消</Button><Button data-interaction-id="I-06" disabled={busy||!inspection?.plan} onClick={()=>void run(async()=>{const imported=await commitImport(inspection!.plan!);const report={title:inspection!.title,nodeCount:inspection!.nodeCount,assetCount:inspection!.assetCount,missing:inspection!.missing?.length??0,unknownNodes:inspection!.unknownNodes?.map(n=>({id:n.id,type:n.type,title:n.title}))??[],readonly:inspection!.readonly??false,projectId:imported.id,secretsExcluded:true,automaticExecution:false,excludedFields:inspection!.excludedFields??0,history:inspection!.history??[]};triggerLocalDownload(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),'project-import-report.json');releaseImportPlan(inspection!.plan!);planRef.current=undefined;setInspection(undefined);setMessage('已导入新项目；旧项目保留，历史任务只读，没有恢复执行授权。');await reload();})}>导入新项目</Button></>}><p data-interaction-id="I-03">{inspection?.title} · {inspection?.nodeCount} 个已识别节点 · {inspection?.assetCount} 个素材</p><p data-interaction-id="I-04">默认另存新项目；历史任务只读，不查询、不生成、不安装插件。</p><p>本次检查剔除敏感或执行字段 {inspection?.excludedFields??0} 项；原服务和授权绑定保留为只读来源。</p><ul>{inspection?.history?.map(r=><li key={r.id}>{r.id} · 原任务 {r.taskId??'未提供'} · 原服务 {r.connectionId} · 原授权绑定 {r.authBindingId} · {r.executionState} / {r.queryState} / {r.deliveryState} / {r.billingState}</li>)}</ul><p>{inspection?.mode==='structure'?'仅结构包，媒体需要重新关联。':'已核对包内媒体哈希。'} 缺失媒体 {inspection?.missing?.length??0} 项。</p>{inspection?.readonly?<p data-interaction-id="I-05" role="alert">未知节点 {inspection.unknownNodes?.length} 项已隔离；此项目只读，不能执行未知内容。</p>:null}<ul>{inspection?.unknownNodes?.map(n=><li key={n.id}>{n.title} · {n.type}</li>)}</ul></Dialog>
 </section>;
}
