import {connectionSchema,type ConnectionProfile} from '../../domain/connection';
import {normalizeCoreBase} from '../../adapters/core/url';
import {withDatabase,transact,requestResult,type StudioDb} from '../../infrastructure/storage/database';
import {loadRegisteredConnections} from '../../infrastructure/deployment/registration';
import {matchRegisteredConnection} from '../../infrastructure/deployment/registration';
import {getActiveCore,setActiveCore} from '../../adapters/core/current-connection';
import {resolveCapabilities} from '../../adapters/core/capabilities';
import {parseCoreModels} from '../../adapters/core/contracts';
import {guardCheckTransaction,runConnectionCheck,rememberReadonlyStatus,readonlyStatusMetadata} from './connection-status';
import {sanitizeKnownSecrets} from '../../security/credential-session';
export async function refreshActiveModels(){const active=getActiveCore();if(!active)throw Error('session_credential_required');return runConnectionCheck('video',active.client,async ctx=>{
 const reply=await active.client.requestJson('GET','/v1/models',undefined,{signal:ctx.signal});ctx.assertCurrent();if(!reply.ok){await withDatabase(undefined,db=>transact(db,['receipts'],'readwrite',async tx=>{guardCheckTransaction(ctx,tx);const id='connection-catalog:'+active.client.profile.id,previous=await requestResult<Record<string,unknown>|undefined>(tx.objectStore('receipts').get(id));ctx.assertCurrent();if(previous)tx.objectStore('receipts').put({...previous,stale:true});}));throw reply.error;}
 const models=parseCoreModels(reply.value);if(models.some(m=>sanitizeKnownSecrets(m.id)!==m.id))throw Error('model_catalog_unsafe');const registration=matchRegisteredConnection(active.client.profile,await loadRegisteredConnections());ctx.assertCurrent();if(!registration)throw Error('connection_unregistered');const capability=resolveCapabilities(registration.contract,models),verifiedAt=Date.now(),mock=registration.contract.evidence.some(e=>e.kind==='mock');
 await withDatabase(undefined,db=>transact(db,['receipts','diagnostics'],'readwrite',tx=>{guardCheckTransaction(ctx,tx);tx.objectStore('receipts').put({id:'connection-catalog:'+active.client.profile.id,kind:'readonly-model-catalog',connectionId:active.client.profile.id,models,capability,verifiedAt,stale:false,evidence:registration.contract.evidence});tx.objectStore('diagnostics').put(readonlyStatusMetadata('video',active.client,verifiedAt,models.map(m=>m.id),mock,'模型目录'));tx.objectStore('diagnostics').put(readonlyStatusMetadata('text',active.client,verifiedAt,models.map(m=>m.id),mock));}));ctx.assertCurrent();rememberReadonlyStatus('video',active.client,models.map(m=>m.id),{verifiedAt,mock,scope:'模型目录'});if(getActiveCore()?.client.binding.id===active.client.binding.id)setActiveCore(active.client,capability);return {models,capability};});}
export async function listHiddenConnections(){return withDatabase(undefined,db=>transact(db,['receipts'],'readonly',async tx=>(await requestResult<{kind?:string;profile?:unknown}[]>(tx.objectStore('receipts').getAll())).filter(r=>r.kind==='readonly-connection-configuration').flatMap(r=>{const parsed=connectionSchema.safeParse(r.profile);return parsed.success?[parsed.data]:[];})));}
export async function restoreConnection(profile:ConnectionProfile){const parsed=connectionSchema.parse(profile);await withDatabase(undefined,db=>transact(db,['connections','receipts'],'readwrite',async tx=>{const existing=await requestResult(tx.objectStore('connections').get(parsed.id));if(!existing)tx.objectStore('connections').put(parsed);tx.objectStore('receipts').delete('hidden-connection:'+parsed.id);}));}
export async function listConnections(db?:StudioDb){return withDatabase(db,c=>transact(c,['connections'],'readonly',async tx=>(await requestResult<unknown[]>(tx.objectStore('connections').getAll())).map(p=>connectionSchema.parse(p))));}
export async function saveConnectionAddress(input:{id?:string;name:string;address:string},db?:StudioDb):Promise<ConnectionProfile>{const base=normalizeCoreBase(input.address);if(!base.ok||base.value.startsWith('/'))throw Error('connection_address_invalid');if(!input.name.trim()||[...input.name].length>60)throw Error('connection_name_invalid');const registry=await loadRegisteredConnections(),registered=registry.find(entry=>entry.profile.originSnapshot===base.value);return withDatabase(db,c=>transact(c,['connections'],'readwrite',async tx=>{const previous=input.id?connectionSchema.parse(await requestResult(tx.objectStore('connections').get(input.id))):undefined,same=previous?.originSnapshot===base.value,profile=connectionSchema.parse({id:same?previous.id:crypto.randomUUID(),name:input.name,originSnapshot:base.value,proxyBase:registered?.profile.proxyBase??'/core-api',contractVersion:registered?.profile.contractVersion??'unverified'});tx.objectStore('connections').put(profile);return profile;}));}
export async function renameConnection(profile:ConnectionProfile,name:string,db?:StudioDb){return saveConnectionAddress({id:profile.id,address:profile.originSnapshot,name},db);}
export async function connectionHistory(profile:ConnectionProfile,db?:StudioDb){return withDatabase(db,c=>transact(c,['runs','promptRuns','receipts'],'readonly',async tx=>{const runs=await requestResult<{connectionId:string;authBindingId:string;originSnapshot:string;executionState:string}[]>(tx.objectStore('runs').getAll()),prompts=await requestResult<typeof runs>(tx.objectStore('promptRuns').getAll()),receipts=await requestResult<{kind?:string;connectionId?:string;authBindingId?:string;originSnapshot?:string}[]>(tx.objectStore('receipts').getAll()),bound=[...runs,...prompts].filter(r=>r.connectionId===profile.id&&r.originSnapshot===profile.originSnapshot),bindings=Array.from(new Set([...bound.map(r=>r.authBindingId),...receipts.filter(r=>r.kind==='connection-session'&&r.connectionId===profile.id&&r.originSnapshot===profile.originSnapshot).map(r=>r.authBindingId).filter((id):id is string=>!!id)]));return {bindings,hasHistory:bound.length>0,hasActive:bound.some(r=>['persisted','uploading','submitting','submit_unknown','accepted','running','sending','response_unknown','waiting_stopped'].includes(r.executionState))};}));}
export async function hideConnection(profile:ConnectionProfile,confirmedReadonly:boolean,db?:StudioDb){return withDatabase(db,c=>transact(c,['connections','receipts','runs','promptRuns'],'readwrite',async tx=>{const runs=await requestResult<{connectionId:string;originSnapshot:string}[]>(tx.objectStore('runs').getAll()),prompts=await requestResult<typeof runs>(tx.objectStore('promptRuns').getAll()),hasHistory=[...runs,...prompts].some(r=>r.connectionId===profile.id&&r.originSnapshot===profile.originSnapshot);if(hasHistory&&!confirmedReadonly)throw Error('connection_history_confirmation_required');if(hasHistory)tx.objectStore('receipts').put({id:'hidden-connection:'+profile.id,kind:'readonly-connection-configuration',profile,createdAt:Date.now()});tx.objectStore('connections').delete(profile.id);}));}
