import {useEffect,useRef,useState} from 'react';
import type {ConnectionProfile} from '../../domain/connection';
import {createAuthBinding} from '../../domain/authorization';
import {createCoreClient} from '../../adapters/core/http-client';
import {resolveCapabilities} from '../../adapters/core/capabilities';
import {getActiveCore,setActiveCore,clearActiveCore,subscribeActiveCore} from '../../adapters/core/current-connection';
import {loadRegisteredConnections,matchRegisteredConnection,type RegisteredConnection} from '../../infrastructure/deployment/registration';
import {withDatabase,transact} from '../../infrastructure/storage/database';
import {setSessionCredential,forgetSessionCredential,withCredential,sanitizeKnownSecrets,hasSessionCredential} from '../../security/credential-session';
import {listConnections,saveConnectionAddress,connectionHistory,hideConnection,refreshActiveModels,listHiddenConnections,restoreConnection} from './connection-service';
import {registerConnectionTarget} from '../../infrastructure/deployment/register-target';
import {normalizeCoreBase} from '../../adapters/core/url';
import {Button} from '../../ui/Button';
import {LocalLink} from '../../app/routes';
import {Dialog} from '../../ui/Dialog';
import {exportSettings} from './settings-transfer';
import {usePreferences,getPreferences,savePreferences} from './preferences-store';
import {suggestDefaultVideoModel} from './default-models';
import {ConnectionStatus} from './ConnectionStatus';
import {guardCheckTransaction,runConnectionCheck,setConnectionStatusCandidate,cancelConnectionCheck,configureConnectionStatus,rememberReadonlyStatus,readonlyStatusMetadata,safeConnectionFailure,subscribeConnectionStatus,isConnectionChecking,videoStatusSpec} from './connection-status';
import {triggerLocalDownload} from '../../ui/local-download';
export function ConnectionSettings({onboarding=false}:{onboarding?:boolean}={}){const [addressError,setAddressError]=useState(''),[hidden,setHidden]=useState<ConnectionProfile[]>([]),[profiles,setProfiles]=useState<ConnectionProfile[]>([]),[registry,setRegistry]=useState<RegisteredConnection[]>([]),[selected,setSelected]=useState<ConnectionProfile>(),[name,setName]=useState(''),[address,setAddress]=useState(''),[bindings,setBindings]=useState<string[]>([]),[bindingId,setBindingId]=useState('new'),[visible,setVisible]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[deleteOpen,setDeleteOpen]=useState(false),[hasHistory,setHasHistory]=useState(false),[,refreshActive]=useState(0),key=useRef<HTMLInputElement>(null),inFlight=useRef(false),mounted=useRef(true),version=useRef(0);
 useEffect(()=>{mounted.current=true;const stop=subscribeConnectionStatus(()=>refreshActive(v=>v+1));return()=>{mounted.current=false;version.current++;cancelConnectionCheck('video');stop();};},[]);
 useEffect(()=>subscribeActiveCore(()=>refreshActive(v=>v+1)),[]);const preferences=usePreferences(),active=getActiveCore(),registered=selected&&address===selected.originSnapshot?matchRegisteredConnection(selected,registry):undefined;
 async function reload(){const rows=await listConnections();setProfiles(rows);if(!selected){let preferred:string|undefined;try{preferred=localStorage.getItem('aiwork-studio:default-connection')??undefined;}catch{/* Optional preference. */}const stored=rows.find(p=>p.id===preferred);if(stored)await choose(stored);}setHidden(await listHiddenConnections());setRegistry(await loadRegisteredConnections());}useEffect(()=>{void reload().catch(()=>setMessage('本地连接或部署登记读取失败，未发起业务请求。'));},[]);
 async function choose(profile:ConnectionProfile){version.current++;cancelConnectionCheck('video');const history=await connectionHistory(profile),currentActive=getActiveCore();if(currentActive&&currentActive.client.profile.id!==profile.id)clearActiveCore();if(key.current)key.current.value='';setVisible(false);setSelected(profile);configureConnectionStatus('video',profile);try{localStorage.setItem('aiwork-studio:default-connection',profile.id);}catch{/* Current selection remains usable. */}setName(profile.name);setAddress(profile.originSnapshot);setBindingId('new');setBindings(history.bindings);setHasHistory(history.hasHistory);setMessage('已选择地址档案；输入授权后只读核验。切换不会改写旧任务。');}
 function startNew(){version.current++;cancelConnectionCheck('video');setConnectionStatusCandidate('video');if(key.current)key.current.value='';setVisible(false);setSelected(undefined);setName('');setAddress('');setBindingId('new');setBindings([]);setHasHistory(false);setMessage('正在新增地址档案；现有连接及旧任务保留。');}
 async function execute(action:()=>Promise<void>){if(inFlight.current)return;inFlight.current=true;setBusy(true);setMessage('');try{await action();}catch(error){if(!mounted.current||error instanceof Error&&error.message==='connection_check_obsolete')return;setMessage(previous=>previous.startsWith('只读核验失败：')?previous:error instanceof Error&&error.message==='credential_binding_rebind_required'?'此绑定在当前标签页已属于另一Key；请使用原Key，或新建授权绑定。':'连接操作失败，请检查名称、合法地址、部署登记和原授权；项目与旧任务保留。');}finally{inFlight.current=false;if(mounted.current)setBusy(false);}}
 async function authorize(){
  if(!selected||address!==selected.originSnapshot)return;const started=version.current,assertMounted=()=>{if(!mounted.current||version.current!==started)throw Error('connection_check_obsolete');};
  const entered=key.current?.value,existing=getActiveCore();if(!entered&&existing?.client.profile.id===selected.id&&hasSessionCredential(existing.client.binding.id)){await check(existing.client,registered);return;}
  if(!entered)return;let entry=registered,profile=selected;
  if(!entry){await registerConnectionTarget('core',name,address);assertMounted();const nextRegistry=await loadRegisteredConnections(true);assertMounted();setRegistry(nextRegistry);profile=await saveConnectionAddress({id:selected.id,name,address});assertMounted();setSelected(profile);entry=matchRegisteredConnection(profile,nextRegistry);if(!entry)throw Error('registration_missing');}
  const binding=bindingId==='new'?createAuthBinding(profile):{id:bindingId,connectionId:profile.id,originSnapshot:profile.originSnapshot,kind:'core-user' as const,createdAt:Date.now()},owned=!hasSessionCredential(binding.id);
  setSessionCredential(binding.id,entered);key.current!.value='';setVisible(false);const client=createCoreClient(profile,{binding,withCredential},{registry:[{...entry.profile,id:profile.id,name:profile.name}]});
  try{await check(client,entry);}catch(error){if(owned)forgetSessionCredential(binding.id);throw error;}
  async function check(client:ReturnType<typeof createCoreClient>,entry:RegisteredConnection|undefined){
   setConnectionStatusCandidate('video',client);await runConnectionCheck('video',client,async ctx=>{assertMounted();const reply=await client.testConnection({signal:ctx.signal});ctx.assertCurrent();assertMounted();if(!reply.ok){setMessage('只读核验失败：'+safeConnectionFailure(reply.error)+'；没有发起生成。');throw reply.error;}if(reply.value.some(m=>sanitizeKnownSecrets(m.id)!==m.id))throw Error('model_catalog_unsafe');const matched=entry??matchRegisteredConnection(client.profile,await loadRegisteredConnections());ctx.assertCurrent();assertMounted();if(!matched)throw Error('registration_missing');const capability=resolveCapabilities(matched.contract,reply.value),verifiedAt=Date.now(),mock=matched.contract.evidence.some(e=>e.kind==='mock');
    await withDatabase(undefined,db=>transact(db,['receipts','diagnostics'],'readwrite',tx=>{guardCheckTransaction(ctx,tx);assertMounted();tx.objectStore('diagnostics').put({id:'capability:current',capability});tx.objectStore('diagnostics').put(readonlyStatusMetadata('video',client,verifiedAt,reply.value.map(m=>m.id),mock));tx.objectStore('diagnostics').put(readonlyStatusMetadata('text',client,verifiedAt,reply.value.map(m=>m.id),mock));tx.objectStore('receipts').put({id:'connection-session:'+client.binding.id,kind:'connection-session',connectionId:client.profile.id,authBindingId:client.binding.id,originSnapshot:client.profile.originSnapshot,createdAt:verifiedAt});tx.objectStore('receipts').put({id:'connection-catalog:'+client.profile.id,kind:'readonly-model-catalog',connectionId:client.profile.id,models:reply.value,capability,verifiedAt,stale:false,evidence:matched.contract.evidence});}));
    ctx.assertCurrent();assertMounted();rememberReadonlyStatus('video',client,reply.value.map(m=>m.id),{verifiedAt,mock});setActiveCore(client,capability);const suggested=suggestDefaultVideoModel(client.profile.originSnapshot,reply.value.map(m=>m.id),getPreferences().defaultVideoModel);if(suggested)savePreferences({defaultVideoModel:suggested});setConnectionStatusCandidate('video');const history=await connectionHistory(client.profile);ctx.assertCurrent();assertMounted();setBindings(history.bindings);setMessage('健康与模型目录只读核验成功；模型可见不代表全部scope或收费授权。');
   });
  }
 }
 return <section className="card"><h2>视频执行网关（Trae-core）</h2><ConnectionStatus channel="video" model={preferences.defaultVideoModel} spec={videoStatusSpec(preferences.defaultVideoModel,preferences.defaultDuration,preferences.defaultRatio)} profile={selected} configured={!!address.trim()} draftChanged={(!!address.trim()&&(!selected||address!==selected.originSnapshot))||!!key.current?.value}/><p>地址档案可保存；普通Key只在当前标签页内存，不记住、不导出。测试只请求健康与模型目录。</p><label>已保存连接<select data-interaction-id="K-03" aria-label="已保存连接" value={selected?.id??''} disabled={busy} onChange={e=>{const profile=profiles.find(p=>p.id===e.target.value);if(profile)void execute(()=>choose(profile));else startNew();}}><option value="">新增地址档案</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name} · {p.originSnapshot}</option>)}</select></label><label>连接名称<input data-interaction-id="ui:ConnectionSettings:input:2b9da3b03141" value={name} disabled={busy} onChange={e=>setName(e.target.value)}/></label><label>Core 服务地址<input data-interaction-id={onboarding?'W-02':'K-02'} value={address} disabled={busy} autoComplete="off" onBlur={()=>{if(!onboarding||!address.trim())return;const normalized=normalizeCoreBase(address);if(!normalized.ok||normalized.value.startsWith('/'))setAddressError('请输入允许的 HTTPS 或本机服务地址，不含用户名、密码或查询凭据。');else{setAddress(normalized.value);setAddressError('');}}} onChange={e=>{version.current++;cancelConnectionCheck('video');setAddress(e.target.value);setAddressError('');}}/></label><Button data-interaction-id="K-01" disabled={busy||!name.trim()||!address.trim()} onClick={()=>void execute(async()=>{const profile=await saveConnectionAddress({id:selected?.id,name,address});await reload();await choose(profile);setMessage('连接地址已保存；地址变化创建新身份，旧任务绑定保留。');})}>保存连接地址</Button>{addressError?<p role="alert">{addressError}</p>:null}
 <label>普通用户 Key<input data-interaction-id={onboarding?'W-03':'K-04'} ref={key} type={visible?'text':'password'} autoComplete="off" spellCheck={false} disabled={busy} onBlur={()=>setVisible(false)} onChange={()=>{version.current++;cancelConnectionCheck('video');refreshActive(v=>v+1);}}/></label><Button data-interaction-id={onboarding?'W-04':'K-04'} aria-pressed={visible} onMouseDown={e=>e.preventDefault()} onClick={()=>{setVisible(v=>!v);key.current?.focus();}}>{onboarding?visible?'隐藏 Key':'显示 Key':'显示或隐藏 Key'}</Button><label>授权用途<select data-interaction-id="ui:ConnectionSettings:select:3f95c8d431f4" aria-label="授权用途" value={bindingId} disabled={busy} onChange={e=>setBindingId(e.target.value)}><option value="new">新授权绑定</option>{bindings.map(id=><option key={id} value={id}>{'恢复原授权 '+id}</option>)}</select></label>{selected&&!registered?<p>此地址尚未登记。点击测试连接会登记固定目标，并只读核验健康与模型目录。视频生成仍需核验部署契约。</p>:null}
 <div className="actions"><Button data-interaction-id={onboarding?'W-05':'K-07'} disabled={busy||isConnectionChecking('video')||!selected||address!==selected.originSnapshot||(!key.current?.value&&!(active?.client.profile.id===selected.id&&hasSessionCredential(active.client.binding.id)))} disabledReason="请先保存连接地址，再输入当前 Key；测试只读，不产生生成请求。" onClick={()=>void execute(authorize)}>测试连接</Button><Button data-interaction-id="K-08" disabled={busy||isConnectionChecking('video')||!active||!selected||active.client.profile.id!==selected.id} onClick={()=>void execute(async()=>{await refreshActiveModels();setMessage('只读模型目录已刷新；失效默认值保留，需手动选择。');})}>刷新模型列表</Button><Button data-interaction-id="K-05" disabled={!active} onClick={()=>{version.current++;cancelConnectionCheck('video');forgetSessionCredential(active!.client.binding.id);clearActiveCore();if(key.current)key.current.value='';setMessage('当前Key已清除，停止当前授权的新提交与本页轮询；远端任务可能继续。');}}>清除当前 Key</Button><Button data-interaction-id="K-09" disabled={!selected||busy} onClick={()=>void navigator.clipboard.writeText(selected!.originSnapshot).then(()=>setMessage('已复制公开连接地址。')).catch(()=>setMessage('复制失败，可手动选择地址。'))}>复制连接地址</Button><Button data-interaction-id="K-10" disabled={busy||!profiles.length} onClick={()=>void execute(async()=>{triggerLocalDownload(await exportSettings(),'aiwork-studio-connections.json');setMessage('已触发公开配置下载；不包含当前Key或执行授权，请确认文件保存。');})}>导出连接配置</Button><Button data-interaction-id="K-06" disabled={!selected||busy} onClick={()=>setDeleteOpen(true)}>删除连接档案</Button></div><div className="actions">{hidden.map(profile=><Button data-interaction-id="ui:ConnectionSettings:Button:957d3c5e6b55" key={profile.id} disabled={busy} onClick={()=>void execute(async()=>{await restoreConnection(profile);await reload();setMessage('地址档案已恢复；仍需原Key只读核验，不自动查询或生成。');})}>{'恢复只读地址档案 '+profile.name}</Button>)}</div><div className="actions"><LocalLink data-interaction-id="video-api:verify-generation" href="/projects">前往项目验证视频生成（需预览确认）</LocalLink></div><p>当前活动连接：{active?.client.profile.name??'未连接'} · 授权绑定 {active?.client.binding.id??'无'} · 只读目录不等于生成许可</p><p role="status">{message}</p>
 <Dialog title="删除连接档案" open={deleteOpen} onClose={()=>{if(!busy)setDeleteOpen(false);}} footer={<><Button data-interaction-id="ui:ConnectionSettings:Button:327de420a987" disabled={busy} onClick={()=>setDeleteOpen(false)}>取消</Button><Button data-interaction-id="ui:ConnectionSettings:Button:33e13e27ed7e" disabled={busy} onClick={()=>void execute(async()=>{if(!selected)return;await hideConnection(selected,true);if(active?.client.profile.id===selected.id){forgetSessionCredential(active.client.binding.id);clearActiveCore();}setSelected(undefined);setName('');setAddress('');setBindings([]);setDeleteOpen(false);await reload();setMessage('已移除新建入口；有历史绑定的脱敏档案保留为只读，任务没有删除。');})}>确认删除档案</Button></>}><p>{hasHistory?'此地址有任务历史，保留脱敏只读配置及原追踪身份。':'只移除本地地址档案。'}不删除项目、原任务或远端账务；不迁移到另一Key。</p></Dialog></section>;
}
