import {useEffect,useRef,useState} from 'react';
import type {ConnectionProfile} from '../../domain/connection';
import {createAuthBinding} from '../../domain/authorization';
import {createCoreClient} from '../../adapters/core/http-client';
import {resolveCapabilities} from '../../adapters/core/capabilities';
import {getActiveCore,setActiveCore,clearActiveCore,subscribeActiveCore} from '../../adapters/core/current-connection';
import {loadRegisteredConnections,matchRegisteredConnection,type RegisteredConnection} from '../../infrastructure/deployment/registration';
import {withDatabase,transact} from '../../infrastructure/storage/database';
import {setSessionCredential,forgetSessionCredential,withCredential,sanitizeKnownSecrets} from '../../security/credential-session';
import {listConnections,saveConnectionAddress,connectionHistory,hideConnection,refreshActiveModels,listHiddenConnections,restoreConnection} from './connection-service';
import {normalizeCoreBase} from '../../adapters/core/url';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
import {exportSettings} from './settings-transfer';
import {triggerLocalDownload} from '../../ui/local-download';
export function ConnectionSettings({onboarding=false}:{onboarding?:boolean}={}){const [addressError,setAddressError]=useState(''),[hidden,setHidden]=useState<ConnectionProfile[]>([]),[profiles,setProfiles]=useState<ConnectionProfile[]>([]),[registry,setRegistry]=useState<RegisteredConnection[]>([]),[selected,setSelected]=useState<ConnectionProfile>(),[name,setName]=useState(''),[address,setAddress]=useState(''),[bindings,setBindings]=useState<string[]>([]),[bindingId,setBindingId]=useState('new'),[visible,setVisible]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[deleteOpen,setDeleteOpen]=useState(false),[hasHistory,setHasHistory]=useState(false),[,refreshActive]=useState(0),key=useRef<HTMLInputElement>(null),inFlight=useRef(false);
 useEffect(()=>subscribeActiveCore(()=>refreshActive(v=>v+1)),[]);const active=getActiveCore(),registered=selected&&address===selected.originSnapshot?matchRegisteredConnection(selected,registry):undefined;
 async function reload(){const rows=await listConnections();setProfiles(rows);if(!selected){let preferred:string|undefined;try{preferred=localStorage.getItem('aiwork-studio:default-connection')??undefined;}catch{/* Optional preference. */}const stored=rows.find(p=>p.id===preferred);if(stored)await choose(stored);}setHidden(await listHiddenConnections());setRegistry(await loadRegisteredConnections());}useEffect(()=>{void reload().catch(()=>setMessage('本地连接或部署登记读取失败，未发起业务请求。'));},[]);
 async function choose(profile:ConnectionProfile){const history=await connectionHistory(profile),currentActive=getActiveCore();if(currentActive&&currentActive.client.profile.id!==profile.id)clearActiveCore();if(key.current)key.current.value='';setVisible(false);setSelected(profile);try{localStorage.setItem('aiwork-studio:default-connection',profile.id);}catch{/* Current selection remains usable. */}setName(profile.name);setAddress(profile.originSnapshot);setBindingId('new');setBindings(history.bindings);setHasHistory(history.hasHistory);setMessage('已选择地址档案；输入授权后只读核验。切换不会改写旧任务。');}
 async function execute(action:()=>Promise<void>){if(inFlight.current)return;inFlight.current=true;setBusy(true);try{await action();}catch(error){setMessage(error instanceof Error&&error.message==='credential_binding_rebind_required'?'此绑定在当前标签页已属于另一Key；请使用原Key，或新建授权绑定。':'连接操作失败，请检查名称、合法地址、部署登记和原授权；项目与旧任务保留。');}finally{inFlight.current=false;setBusy(false);}}
 async function authorize(){if(!selected||!registered||!key.current?.value)return;const secret=key.current.value,binding=bindingId==='new'?createAuthBinding(selected):{id:bindingId,connectionId:selected.id,originSnapshot:selected.originSnapshot,kind:'core-user' as const,createdAt:Date.now()};setSessionCredential(binding.id,secret);key.current.value='';setVisible(false);const client=createCoreClient(selected,{binding,withCredential},{registry:[{...registered.profile,id:selected.id,name:selected.name}]}),reply=await client.testConnection();if(!reply.ok){forgetSessionCredential(binding.id);if(active?.client.binding.id===binding.id)clearActiveCore();setMessage('只读核验失败：HTTP '+reply.error.httpStatus+' / '+reply.error.errorCode+'；没有发起生成。');return;}if(reply.value.some(m=>sanitizeKnownSecrets(m.id)!==m.id)){forgetSessionCredential(binding.id);throw Error('model_catalog_unsafe');}const capability=resolveCapabilities(registered.contract,reply.value);await withDatabase(undefined,db=>transact(db,['receipts'],'readwrite',tx=>{tx.objectStore('receipts').put({id:'connection-session:'+binding.id,kind:'connection-session',connectionId:selected.id,authBindingId:binding.id,originSnapshot:selected.originSnapshot,createdAt:Date.now()});tx.objectStore('receipts').put({id:'connection-catalog:'+selected.id,kind:'readonly-model-catalog',connectionId:selected.id,models:reply.value,capability,verifiedAt:Date.now(),evidence:registered.contract.evidence});}));setActiveCore(client,capability);const history=await connectionHistory(selected);setBindings(history.bindings);setMessage('健康与模型目录只读核验成功；模型可见不代表全部scope或收费授权。');}
 return <section className="card"><h2>连接与普通用户授权</h2><p>地址档案可保存；普通Key只在当前标签页内存，不记住、不导出。测试只请求健康与模型目录。</p><label>已保存连接<select data-interaction-id="K-03" aria-label="已保存连接" value={selected?.id??''} disabled={busy} onChange={e=>{const profile=profiles.find(p=>p.id===e.target.value);if(profile)void execute(()=>choose(profile));}}><option value="">新增地址档案</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name} · {p.originSnapshot}</option>)}</select></label><label>连接名称<input data-interaction-id="ui:ConnectionSettings:input:2b9da3b03141" value={name} disabled={busy} onChange={e=>setName(e.target.value)}/></label><label>Core 服务地址<input data-interaction-id={onboarding?'W-02':'K-02'} value={address} disabled={busy} autoComplete="off" onBlur={()=>{if(!onboarding||!address.trim())return;const normalized=normalizeCoreBase(address);if(!normalized.ok||normalized.value.startsWith('/'))setAddressError('请输入允许的 HTTPS 或本机服务地址，不含用户名、密码或查询凭据。');else{setAddress(normalized.value);setAddressError('');}}} onChange={e=>{setAddress(e.target.value);setAddressError('');}}/></label><Button data-interaction-id="K-01" disabled={busy||!name.trim()||!address.trim()} onClick={()=>void execute(async()=>{const profile=await saveConnectionAddress({id:selected?.id,name,address});await reload();await choose(profile);setMessage('连接地址已保存；地址变化创建新身份，旧任务绑定保留。');})}>保存连接地址</Button>{addressError?<p role="alert">{addressError}</p>:null}
 <label>普通用户 Key<input data-interaction-id={onboarding?'W-03':'K-04'} ref={key} type={visible?'text':'password'} autoComplete="off" spellCheck={false} disabled={busy} onBlur={()=>setVisible(false)} onChange={()=>refreshActive(v=>v+1)}/></label><Button data-interaction-id={onboarding?'W-04':'K-04'} aria-pressed={visible} onMouseDown={e=>e.preventDefault()} onClick={()=>{setVisible(v=>!v);key.current?.focus();}}>{onboarding?visible?'隐藏 Key':'显示 Key':'显示或隐藏 Key'}</Button><label>授权用途<select data-interaction-id="ui:ConnectionSettings:select:3f95c8d431f4" aria-label="授权用途" value={bindingId} disabled={busy} onChange={e=>setBindingId(e.target.value)}><option value="new">新授权绑定</option>{bindings.map(id=><option key={id} value={id}>{'恢复原授权 '+id}</option>)}</select></label>{selected&&!registered?<p>地址尚未在当前部署登记，不能测试或生成。</p>:null}
 <div className="actions"><Button data-interaction-id={onboarding?'W-05':'K-07'} disabled={busy||!registered||!key.current?.value} disabledReason="需要部署登记的固定目标和当前输入Key" onClick={()=>void execute(authorize)}>测试连接</Button><Button data-interaction-id="K-08" disabled={busy||!active||!selected||active.client.profile.id!==selected.id} onClick={()=>void execute(async()=>{await refreshActiveModels();setMessage('只读模型目录已刷新；失效默认值保留，需手动选择。');})}>刷新模型列表</Button><Button data-interaction-id="K-05" disabled={!active} onClick={()=>{forgetSessionCredential(active!.client.binding.id);clearActiveCore();if(key.current)key.current.value='';setMessage('当前Key已清除，停止当前授权的新提交与本页轮询；远端任务可能继续。');}}>清除当前 Key</Button><Button data-interaction-id="K-09" disabled={!selected||busy} onClick={()=>void navigator.clipboard.writeText(selected!.originSnapshot).then(()=>setMessage('已复制公开连接地址。')).catch(()=>setMessage('复制失败，可手动选择地址。'))}>复制连接地址</Button><Button data-interaction-id="K-10" disabled={busy||!profiles.length} onClick={()=>void execute(async()=>{triggerLocalDownload(await exportSettings(),'aiwork-studio-connections.json');setMessage('已触发公开配置下载；不包含当前Key或执行授权，请确认文件保存。');})}>导出连接配置</Button><Button data-interaction-id="K-06" disabled={!selected||busy} onClick={()=>setDeleteOpen(true)}>删除连接档案</Button></div><div className="actions">{hidden.map(profile=><Button data-interaction-id="ui:ConnectionSettings:Button:957d3c5e6b55" key={profile.id} disabled={busy} onClick={()=>void execute(async()=>{await restoreConnection(profile);await reload();setMessage('地址档案已恢复；仍需原Key只读核验，不自动查询或生成。');})}>{'恢复只读地址档案 '+profile.name}</Button>)}</div><p>当前活动连接：{active?.client.profile.name??'未连接'} · 授权绑定 {active?.client.binding.id??'无'} · 只读目录不等于生成许可</p><p role="status">{message}</p>
 <Dialog title="删除连接档案" open={deleteOpen} onClose={()=>{if(!busy)setDeleteOpen(false);}} footer={<><Button data-interaction-id="ui:ConnectionSettings:Button:327de420a987" disabled={busy} onClick={()=>setDeleteOpen(false)}>取消</Button><Button data-interaction-id="ui:ConnectionSettings:Button:33e13e27ed7e" disabled={busy} onClick={()=>void execute(async()=>{if(!selected)return;await hideConnection(selected,true);if(active?.client.profile.id===selected.id){forgetSessionCredential(active.client.binding.id);clearActiveCore();}setSelected(undefined);setName('');setAddress('');setBindings([]);setDeleteOpen(false);await reload();setMessage('已移除新建入口；有历史绑定的脱敏档案保留为只读，任务没有删除。');})}>确认删除档案</Button></>}><p>{hasHistory?'此地址有任务历史，保留脱敏只读配置及原追踪身份。':'只移除本地地址档案。'}不删除项目、原任务或远端账务；不迁移到另一Key。</p></Dialog></section>;
}
