import {z} from 'zod';
import {connectionSchema,type ConnectionProfile} from '../../domain/connection';
import {preferencesSchema,getPreferences,savePreferences,type Preferences} from './preferences-store';
import {listConnections} from './connection-service';
import {loadRegisteredConnections} from '../../infrastructure/deployment/registration';
import {withDatabase,transact,requestResult} from '../../infrastructure/storage/database';
import {normalizeCoreBase} from '../../adapters/core/url';
import {portableContent} from '../../infrastructure/packages/package-model';
import {getActiveCore,clearActiveCore} from '../../adapters/core/current-connection';
import {forgetSessionCredential} from '../../security/credential-session';
export const settingsSchema=z.strictObject({format:z.literal('aiwork-studio-settings'),schemaVersion:z.literal(1),preferences:preferencesSchema,connections:z.array(connectionSchema).max(50)});
export type SettingsDocument=z.infer<typeof settingsSchema>;
export type SettingsImportReceipt={id:string;connectionIds:string[];beforePreferences:Preferences;preferencesChanged:boolean;preferencesSaved:boolean};
export async function exportSettings():Promise<Blob>{const document=settingsSchema.parse(portableContent({format:'aiwork-studio-settings',schemaVersion:1,preferences:getPreferences(),connections:await listConnections()}));return new Blob([JSON.stringify(document,null,2)],{type:'application/json'});}
export async function inspectSettings(file:Blob):Promise<SettingsDocument>{if(file.size>65536)throw Error('settings_unsafe');const document=settingsSchema.parse(JSON.parse(await file.text()));if(new Set(document.connections.map(p=>p.id)).size!==document.connections.length)throw Error('settings_unsafe');for(const connection of document.connections){const origin=normalizeCoreBase(connection.originSnapshot),proxy=normalizeCoreBase(connection.proxyBase);if(!origin.ok||origin.value.startsWith('/')||!proxy.ok||!proxy.value.startsWith('/'))throw Error('settings_unsafe');}return document;}
export async function importSettings(document:SettingsDocument,options:{preferences:boolean;connections:boolean}):Promise<SettingsImportReceipt>{const safe=settingsSchema.parse(document),beforePreferences={...getPreferences()},registry=await loadRegisteredConnections(),profiles:ConnectionProfile[]=options.connections?safe.connections.map(p=>{const target=registry.find(e=>e.profile.originSnapshot===p.originSnapshot);return connectionSchema.parse({id:crypto.randomUUID(),name:p.name,originSnapshot:p.originSnapshot,proxyBase:target?.profile.proxyBase??'/core-api',contractVersion:target?.profile.contractVersion??'unverified'});}):[],id=crypto.randomUUID();await withDatabase(undefined,db=>transact(db,['connections','receipts'],'readwrite',tx=>{for(const profile of profiles)tx.objectStore('connections').put(profile);tx.objectStore('receipts').put({id:'settings-import:'+id,kind:'settings-import',connectionIds:profiles.map(p=>p.id),createdAt:Date.now()});}));const saved=options.preferences?savePreferences(safe.preferences):{persisted:true};return {id,connectionIds:profiles.map(p=>p.id),beforePreferences,preferencesChanged:options.preferences,preferencesSaved:saved.persisted};}
export async function undoSettingsImport(receipt:SettingsImportReceipt){await withDatabase(undefined,db=>transact(db,['connections','receipts','runs','promptRuns'],'readwrite',async tx=>{const runs=await requestResult<{connectionId:string}[]>(tx.objectStore('runs').getAll()),prompts=await requestResult<typeof runs>(tx.objectStore('promptRuns').getAll());for(const id of receipt.connectionIds){const profile=await requestResult<ConnectionProfile|undefined>(tx.objectStore('connections').get(id));if(!profile)continue;if([...runs,...prompts].some(r=>r.connectionId===id))tx.objectStore('receipts').put({id:'hidden-connection:'+id,kind:'readonly-connection-configuration',profile,createdAt:Date.now()});tx.objectStore('connections').delete(id);}tx.objectStore('receipts').put({id:'settings-import-undo:'+receipt.id,kind:'settings-import-undo',createdAt:Date.now()});}));const active=getActiveCore();if(active&&receipt.connectionIds.includes(active.client.profile.id)){forgetSessionCredential(active.client.binding.id);clearActiveCore();}if(receipt.preferencesChanged)savePreferences(receipt.beforePreferences);}
