import {UnavailableCapability} from './UnavailableCapability';
import {unverifiedCapabilities} from '../../domain/connection';
import {LocalLink} from '../../app/routes';
import {TextApiSettings} from './TextApiSettings';
import {ConnectionSettings} from './ConnectionSettings';
import {CapabilitySettings} from './CapabilitySettings';
import {StorageSettings} from './StorageSettings';
import {Preferences} from './Preferences';
export function SettingsPage({pathname}:{pathname:string}){return <><nav className="actions" aria-label="设置分类"><LocalLink data-interaction-id="ui:SettingsPage:LocalLink:61b40970ff46" href="/settings/connections">连接与授权</LocalLink><LocalLink data-interaction-id="ui:SettingsPage:LocalLink:0132b5d2b2c0" href="/settings/capabilities">模型与能力</LocalLink><LocalLink data-interaction-id="ui:SettingsPage:LocalLink:99d9b3342719" href="/settings/appearance">外观与播放</LocalLink><LocalLink data-interaction-id="ui:SettingsPage:LocalLink:3dbf02f83037" href="/settings/storage">本地数据与备份</LocalLink><LocalLink data-interaction-id="ui:SettingsPage:LocalLink:cdc2e45160fb" href="/settings/backup">可选备份说明</LocalLink></nav>{pathname==='/settings/connections'?<div className="connection-settings-stack"><ConnectionSettings/><TextApiSettings/></div>:pathname==='/settings/capabilities'||pathname==='/settings/models'?<CapabilitySettings/>:pathname==='/settings/appearance'||pathname==='/settings/preferences'?<Preferences/>:pathname==='/settings/storage'?<StorageSettings/>:pathname==='/settings/backup'?<section className="card"><h2>可选备份说明</h2><UnavailableCapability id="webdav-backup" caps={unverifiedCapabilities()}/><p>WebDAV备份当前未开放。没有自动上传、实时多人协作或覆盖已有数据；可以手动导出当前浏览器项目包。</p><LocalLink data-interaction-id="ui:SettingsPage:LocalLink:6e4444130ef9" href="/projects/packages">项目备份与恢复</LocalLink></section>:<p>请选择设置分类。</p>}</>;}
