import {useEffect,useState} from 'react';
import {getStorageSummary,requestPersistence,cleanRebuildableCache,type StorageSummary} from './storage-service';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
import {LocalLink} from '../../app/routes';
import {LocalCleanup} from './LocalCleanup';
import {SettingsTransfer} from './SettingsTransfer';
export {getStorageSummary,requestPersistence,cleanRebuildableCache} from './storage-service';
export function StorageSettings(){const [summary,setSummary]=useState<StorageSummary>(),[message,setMessage]=useState(''),[error,setError]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);async function refresh(){try{setSummary(await getStorageSummary());setError('');}catch{setError('本地统计读取失败，未清理任何文件。');}}useEffect(()=>{void refresh();},[]);return <section className="card" aria-label="本地数据与备份"><h2>本地数据与备份</h2><p>当前浏览器保存创作数据；Core保存任务与账务，浏览器持久存储也不能替代备份。</p><p>{summary?.remaining===undefined?'剩余容量未知':`浏览器估计使用 ${summary.usage} B，估计配额 ${summary.quota} B，估计剩余 ${summary.remaining} B`}</p><p>本地实际原文件 {summary?.originalBytes??'正在读取'} B · 可重建缩略图 {summary?.rebuildableCount??'正在读取'} 项 / {summary?.rebuildableBytes??'正在读取'} B · 缺失原文件 {summary?.missingOriginals??'正在读取'} 项</p><p>持久存储：{summary?.persisted===undefined?'未知':summary.persisted?'浏览器当前已批准':'当前未批准'}。统计来源：{summary?.source??'等待浏览器与数据库'}。</p><div className="actions"><Button data-interaction-id="D-01" disabled={busy} onClick={()=>void refresh()}>刷新存储统计</Button><Button data-interaction-id="D-02" disabled={busy} onClick={async()=>{setBusy(true);const granted=await requestPersistence();setMessage(granted?'浏览器当前批准持久存储；仍需备份。':'浏览器未批准持久存储；可以继续创作，请及时备份。');await refresh();setBusy(false);}}>请求持久存储</Button><LocalLink data-interaction-id="D-05" href="/projects/packages">导出项目备份</LocalLink><Button data-interaction-id="D-06" disabled={busy||!summary?.rebuildableCount} onClick={()=>setOpen(true)}>清理可重建缩略图</Button></div><p>结果内容自动缓存预算当前为200MiB，超限会停止获取，不自动重新生成。唯一原文件和任务记录不会作为缩略图清理。</p>{error?<p role="alert">{error}</p>:null}<p role="status">{message}</p><Dialog title="清理缩略图缓存" open={open} onClose={()=>{if(!busy)setOpen(false);}} footer={<><Button data-interaction-id="ui:StorageSettings:Button:8554bc9c87a2" disabled={busy} onClick={()=>setOpen(false)}>取消</Button><Button data-interaction-id="ui:StorageSettings:Button:c21d52742385" disabled={busy} onClick={async()=>{setBusy(true);try{const result=await cleanRebuildableCache();setMessage(`已清理 ${result.removed} 项可重建缩略图 / ${result.bytes} B；保留原文件与任务。`);setOpen(false);await refresh();}catch{setError('清理事务未完成，原文件与任务保留。');}finally{setBusy(false);}}}>确认清理缩略图</Button></>}><p>当前显示 {summary?.rebuildableCount} 项、{summary?.rebuildableBytes} B。提交时再次检查引用，保留原文件、历史任务及当前项目；不删除远端内容。</p></Dialog><LocalCleanup onChange={refresh}/><SettingsTransfer/></section>;}
