import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
import {connectionSchema} from '../../domain/connection';
import {unverifiedCapabilities} from '../../domain/connection';
import type {CoreClient} from '../../adapters/core/http-client';
import {createTextClient} from '../../adapters/core/http-client';
import {createAuthBinding} from '../../domain/authorization';
import {registerConnectionTarget} from '../../infrastructure/deployment/register-target';
import {getIndependentText,setActiveText,clearActiveText,canDeclareTextModel,subscribeTextConnection} from '../../adapters/text/current-text';
import {withDatabase,transact,requestResult} from '../../infrastructure/storage/database';
import {setSessionCredential,withCredential,forgetSessionCredential,sanitizeKnownSecrets} from '../../security/credential-session';
import {Button} from '../../ui/Button';
const savedTextSchema=z.strictObject({id:z.string().startsWith('text-profile:'),profile:connectionSchema,model:z.string().min(1).max(256)});
type SavedText=z.infer<typeof savedTextSchema>;
export function TextApiSettings(){
 const [name,setName]=useState('独立文字模型'),[address,setAddress]=useState(''),[model,setModel]=useState(''),[models,setModels]=useState<string[]>([]),[saved,setSaved]=useState<SavedText[]>([]),[picked,setPicked]=useState(''),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[,refresh]=useState(0);const key=useRef<HTMLInputElement>(null),candidate=useRef<CoreClient|undefined>(undefined),pending=useRef(false);
 useEffect(()=>subscribeTextConnection(()=>refresh(v=>v+1)),[]);
 useEffect(()=>{void withDatabase(undefined,db=>transact(db,['diagnostics'],'readonly',tx=>requestResult<unknown[]>(tx.objectStore('diagnostics').getAll()))).then(rows=>setSaved(rows.flatMap(row=>{const parsed=savedTextSchema.safeParse(row);return parsed.success?[parsed.data]:[]}))).catch(()=>setMessage('已保存文字连接读取失败，请保留现有项目数据。'));return()=>{if(candidate.current)forgetSessionCredential(candidate.current.binding.id);};},[]);
 const active=getIndependentText();
 async function verify(){if(pending.current||!key.current?.value)return;pending.current=true;setBusy(true);setMessage('');try{const profile=await registerConnectionTarget('text',name,address),binding=createAuthBinding(profile,'text-api');setSessionCredential(binding.id,key.current.value);key.current.value='';const client=createTextClient(profile,{binding,withCredential},{registry:[profile]});const reply=await client.testConnection();if(!reply.ok){forgetSessionCredential(binding.id);throw Error('catalog_failed');}const ids=reply.value.map(m=>m.id).filter(id=>sanitizeKnownSecrets(id)===id);if(candidate.current)forgetSessionCredential(candidate.current.binding.id);candidate.current=client;setModels(ids);setModel(current=>ids.includes(current)?current:'');setAck(false);setMessage('模型目录已读取。请选择文字模型并确认用途，之后才能进行文字请求。没有发起收费调用。');}catch{setMessage('只读连接失败：请检查 HTTPS 地址、Key、兼容的 /v1/models 接口和本地服务版本。未发起文字请求。');}finally{pending.current=false;setBusy(false);}}
 async function enable(){const client=candidate.current;if(pending.current||!client||!models.includes(model)||!canDeclareTextModel(model)||!ack)return;pending.current=true;setBusy(true);try{const capability={...unverifiedCapabilities(),contractVersion:client.profile.contractVersion,verification:'reviewed' as const,textModels:[model]},row:SavedText={id:'text-profile:'+client.profile.id,profile:client.profile,model};await withDatabase(undefined,db=>transact(db,['diagnostics'],'readwrite',tx=>{tx.objectStore('diagnostics').put(row);tx.objectStore('diagnostics').put({id:'capability:text:'+client.profile.id,capability,evidence:'用户明确选择文字模型；只读目录匹配；尚未真实文字联调'});}));setActiveText(client,capability);candidate.current=undefined;setSaved(rows=>[...rows.filter(r=>r.id!==row.id),row]);setMessage('独立文字连接已启用，仅用于提示词和 Agent 文字提案。每次文字调用仍需预览和费用确认；视频网关保持原绑定。');}catch{setMessage('文字连接未启用，请检查本地保存空间并重试。');}finally{pending.current=false;setBusy(false);}}
 return <section className="card text-api-settings"><h2>独立文字 API（提示词 / Agent）</h2><p>支持 OpenAI 兼容接口。线上 HTTPS 和本机服务都可以；视频继续走上方 Trae-core 网关。地址和模型可保存，Key 仅在当前标签页内存，刷新后重新输入。</p><label>已保存文字连接<select data-interaction-id="text-api:saved" aria-label="已保存文字连接" value={picked} disabled={busy} onChange={e=>{setPicked(e.target.value);const row=saved.find(r=>r.id===e.target.value);if(row){setName(row.profile.name);setAddress(row.profile.originSnapshot);setModel(row.model);setModels([]);setAck(false);if(key.current)key.current.value='';if(candidate.current)forgetSessionCredential(candidate.current.binding.id);candidate.current=undefined;}}}><option value="">新建文字连接</option>{saved.map(row=><option key={row.id} value={row.id}>{row.profile.name+' · '+row.model}</option>)}</select></label><label>文字连接名称<input data-interaction-id="text-api:name" aria-label="文字连接名称" value={name} disabled={busy} onChange={e=>{setName(e.target.value);}}/></label><label>文字 API 地址<input data-interaction-id="text-api:address" aria-label="文字 API 地址" placeholder="https://你的文字服务地址/v1" value={address} disabled={busy} autoComplete="off" onChange={e=>{setAddress(e.target.value);if(candidate.current)forgetSessionCredential(candidate.current.binding.id);candidate.current=undefined;setModels([]);setAck(false);}}/></label><label>文字 API Key<input data-interaction-id="text-api:key" aria-label="文字 API Key" ref={key} type="password" autoComplete="off" spellCheck={false} disabled={busy} onChange={()=>refresh(v=>v+1)}/></label><Button data-interaction-id="text-api:test" disabled={busy||!name.trim()||!address.trim()||!key.current?.value} onClick={()=>void verify()}>测试文字 API（只读）</Button><label>独立文字模型<select data-interaction-id="text-api:model" aria-label="独立文字模型" value={model} disabled={busy||!models.length} onChange={e=>{setModel(e.target.value);setAck(false);}}><option value="">请选择目录中的文字模型</option>{model&&!models.includes(model)?<option value={model}>{model+'（尚未重新核验）'}</option>:null}{models.map(id=><option key={id} value={id} disabled={!canDeclareTextModel(id)}>{id+(!canDeclareTextModel(id)?'（媒体/非对话模型，不可用）':'')}</option>)}</select></label><label className="generation-ack"><input data-interaction-id="text-api:ack" type="checkbox" checked={ack} disabled={busy||!models.includes(model)||!canDeclareTextModel(model)} onChange={e=>setAck(e.target.checked)}/>我确认所选模型用于文字对话；目录匹配不代表免费或已完成真实业务联调</label><div className="actions"><Button data-interaction-id="text-api:enable" disabled={busy||!candidate.current||!ack||!models.includes(model)||!canDeclareTextModel(model)} onClick={()=>void enable()}>启用独立文字连接</Button><Button data-interaction-id="text-api:clear" disabled={!active||busy} onClick={()=>{clearActiveText();setMessage('独立文字 Key 已清除。已发送的请求可能仍在处理，不代表取消或退款。');}}>清除文字 Key</Button></div><p>当前独立文字连接：{active?active.client.profile.name+' · '+active.capability.textModels.join('、'):'未连接；提示词可继续本地整理'}</p><p role="status">{message}</p></section>;
}
