import {useEffect,useId,useState} from 'react';
import {sessionStore,type AuthState} from '../../infrastructure/api/session';
import {apiMessage} from '../../infrastructure/api/client';
import {userPreferencesSchema,type UserPreferences} from '../../infrastructure/api/user-document';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
const appearanceDefaults={theme:'dark',projectSort:'updated',projectList:false,density:'comfortable',animation:'system',autoPlay:false,muted:true,volume:1} as const;
export function AccountPreferences({state}:{state:Extract<AuthState,{status:'authenticated'}>}){
 const id=useId(),doc=state.document,[values,setValues]=useState(doc.preferences),[message,setMessage]=useState(''),[error,setError]=useState(''),[reload,setReload]=useState(0);
 const [resetOpen,setResetOpen]=useState(false),[before,setBefore]=useState<UserPreferences>();
 useEffect(()=>{setValues(doc.preferences);setMessage('');setError('');},[doc.revision,reload]);
 const patch=<K extends keyof UserPreferences>(key:K,value:UserPreferences[K])=>setValues(current=>({...current,[key]:value}));
 const valid=userPreferencesSchema.safeParse(values).success;
 async function save(){setMessage('');setError('');try{await sessionStore.saveDocument({expectedRevision:doc.revision,preferences:userPreferencesSchema.parse(values),lastVisitedPage:'/settings/appearance'});setMessage('偏好已保存');}catch(failure){setError(apiMessage(failure));}}
 async function resetAppearance(){setMessage('');setError('');try{const snapshot=userPreferencesSchema.parse(doc.preferences);await sessionStore.saveDocument({expectedRevision:doc.revision,preferences:{...snapshot,...appearanceDefaults},lastVisitedPage:'/settings/appearance'});setBefore(snapshot);setResetOpen(false);setMessage('外观与播放偏好已重置；生成规格、模型配置、项目与任务不受影响。');}catch(failure){setError(apiMessage(failure));}}
 async function restoreBefore(){if(!before)return;setMessage('');setError('');try{await sessionStore.saveDocument({expectedRevision:doc.revision,preferences:before,lastVisitedPage:'/settings/appearance'});setBefore(undefined);setMessage('已恢复重置前偏好。');}catch(failure){setError(apiMessage(failure));}}
 return <section className="card"><h1>账号偏好</h1><p className="muted">保存到当前账号，可在其他设备恢复。</p><fieldset className="form-stack account-fields" disabled={state.busy}><legend>外观与列表</legend>
 <label htmlFor={id+'theme'}>主题</label><select id={id+'theme'} data-interaction-id="account:preferences:theme" value={values.theme} onChange={event=>patch('theme',event.target.value as UserPreferences['theme'])}><option value="dark">深色</option><option value="light">浅色</option><option value="system">跟随系统</option></select>
 <label htmlFor={id+'sort'}>项目排序</label><select id={id+'sort'} data-interaction-id="account:preferences:sort" value={values.projectSort} onChange={event=>patch('projectSort',event.target.value as UserPreferences['projectSort'])}><option value="updated">最近更新</option><option value="title">名称</option></select>
 <label><input data-interaction-id="account:preferences:list" type="checkbox" checked={values.projectList} onChange={event=>patch('projectList',event.target.checked)}/>使用紧凑项目列表</label>
 <label htmlFor={id+'density'}>界面密度</label><select id={id+'density'} data-interaction-id="account:preferences:density" value={values.density} onChange={event=>patch('density',event.target.value as UserPreferences['density'])}><option value="comfortable">舒适</option><option value="compact">紧凑</option></select>
 <label htmlFor={id+'animation'}>动画</label><select id={id+'animation'} data-interaction-id="account:preferences:animation" value={values.animation} onChange={event=>patch('animation',event.target.value as UserPreferences['animation'])}><option value="system">跟随系统</option><option value="reduced">减少动画</option><option value="full">完整动画</option></select>
 </fieldset><fieldset className="form-stack account-fields" disabled={state.busy}><legend>媒体播放</legend><label><input data-interaction-id="account:preferences:autoplay" type="checkbox" checked={values.autoPlay} onChange={event=>patch('autoPlay',event.target.checked)}/>自动播放预览</label><label><input data-interaction-id="account:preferences:muted" type="checkbox" checked={values.muted} onChange={event=>patch('muted',event.target.checked)}/>默认静音</label><label htmlFor={id+'volume'}>播放音量（0–1）</label><input id={id+'volume'} data-interaction-id="account:preferences:volume" type="number" min="0" max="1" step="0.05" value={values.volume} onChange={event=>patch('volume',event.target.value===''?NaN:Number(event.target.value))}/></fieldset>
 <fieldset className="form-stack account-fields" disabled={state.busy}><legend>生成规格偏好</legend><label><input data-interaction-id="account:preferences:unavailable" type="checkbox" checked={values.showUnavailable} onChange={event=>patch('showUnavailable',event.target.checked)}/>显示暂不可用的生成能力</label><p>默认规格只在供应商支持时使用，生成前仍需核对并确认。</p><label htmlFor={id+'duration'}>默认时长（秒，可留空）</label><input id={id+'duration'} data-interaction-id="account:preferences:duration" type="number" min="0.1" step="0.1" value={values.defaultDuration??''} onChange={event=>patch('defaultDuration',event.target.value===''?null:Number(event.target.value))}/><label htmlFor={id+'ratio'}>默认画幅（可留空）</label><input id={id+'ratio'} data-interaction-id="account:preferences:ratio" maxLength={32} value={values.defaultRatio} onChange={event=>patch('defaultRatio',event.target.value)}/></fieldset>
 <button data-interaction-id="account:preferences:save" className="button primary" disabled={state.busy||!valid} onClick={()=>{void save();}}>保存偏好</button>{!valid?<p role="alert">请检查音量、时长和画幅设置。</p>:null}<button data-interaction-id="account:preferences:reset" className="button" disabled={state.busy} onClick={()=>setResetOpen(true)}>重置外观与播放偏好</button>{before?<button data-interaction-id="account:preferences:restore" className="button" disabled={state.busy} onClick={()=>{void restoreBefore();}}>恢复重置前偏好</button>:null}{message?<p className="banner" role="status">{message}</p>:null}{error?<p className="banner error" role="alert">{error}</p>:null}<button data-interaction-id="account:preferences:reload" className="button" disabled={state.busy} onClick={()=>{setError('');void sessionStore.reloadDocument().then(()=>setReload(value=>value+1)).catch(failure=>setError(apiMessage(failure)));}}>重新加载偏好</button>
 <Dialog open={resetOpen} title="重置操作偏好" onClose={()=>setResetOpen(false)} footer={<><Button data-interaction-id="account:preferences:reset-cancel" onClick={()=>setResetOpen(false)}>取消</Button><Button data-interaction-id="account:preferences:reset-confirm" variant="primary" onClick={()=>{void resetAppearance();}}>确认重置偏好</Button></>}><p>仅重置主题、排序、列表、密度、动画与播放偏好；生成规格、模型配置、项目与任务不受影响。重置后可恢复前值。</p></Dialog></section>;
}
