import {useEffect,useRef,useState,type FormEvent} from 'react';
import {sessionStore,type AuthBootstrapView} from '../../infrastructure/api/session';
import {apiMessage} from '../../infrastructure/api/client';
import {LocalLink} from '../../app/routes';
export function AuthForm({operation}:{operation:'register'|'login'}){
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[bootstrap,setBootstrap]=useState<AuthBootstrapView|null>(null),[message,setMessage]=useState(''),[pending,setPending]=useState(false),composing=useRef(false),active=useRef(true);
 const title=operation==='register'?'注册':'登录';
 useEffect(()=>{active.current=true;const controller=new AbortController();void sessionStore.bootstrap(controller.signal).then(value=>{if(active.current)setBootstrap(value);}).catch(()=>{if(active.current)setMessage('无法初始化登录，请重试。');});return()=>{active.current=false;controller.abort();};},[operation]);
 async function submit(event:FormEvent){event.preventDefault();if(pending||composing.current)return;if(!bootstrap){setMessage('登录验证尚未就绪，请重试。');return;}
  if(!/^[\p{Script=Han}A-Za-z0-9_-]+$/u.test(username.normalize('NFKC').trim())||Array.from(username.normalize('NFKC').trim()).length<3||Array.from(username.normalize('NFKC').trim()).length>32||Array.from(password).length<15||Array.from(password).length>128){setMessage('用户名需3–32个中英文、数字、下划线或短横线字符；密码需15–128个字符。');return;}
  const credentials={username,password};setPassword('');setPending(true);setMessage('');try{await sessionStore.authenticate(operation,credentials,bootstrap);}catch(error){if(active.current)setMessage(apiMessage(error));}finally{credentials.password='';if(active.current)setPending(false);}
 }
 return <main className="account-entry"><section className="card account-form"><p className="account-brand">AI WORK Studio</p><h1>{title}</h1><p className="muted">使用用户名和密码访问自己的账号。</p><form className="form-stack" onSubmit={event=>{void submit(event);}} onCompositionStart={()=>{composing.current=true;}} onCompositionEnd={()=>{composing.current=false;}} onKeyDown={event=>{if(event.key==='Enter'&&event.nativeEvent.isComposing)event.preventDefault();}}><label>用户名<input data-interaction-id={'account:'+operation+':'+'username'} name="username" autoComplete="username" required value={username} maxLength={64} onChange={event=>setUsername(event.target.value)} disabled={pending}/></label><label>密码<input data-interaction-id={'account:'+operation+':'+'password'} name="password" type="password" autoComplete={operation==='register'?'new-password':'current-password'} required value={password} maxLength={256} onChange={event=>setPassword(event.target.value)} disabled={pending}/></label><small>用户名3–32个字符，密码15–128个字符。</small>{message?<p className="banner error" role="alert">{message}</p>:null}<button data-interaction-id={'account:'+operation+':'+'submit'} className="button primary" type="submit" disabled={pending||!bootstrap}>{title}</button>{!bootstrap?<button data-interaction-id={'account:'+operation+':'+'bootstrap-retry'} className="button" type="button" onClick={()=>{setMessage('');void sessionStore.bootstrap().then(setBootstrap).catch(()=>setMessage('无法初始化登录，请重试。'));}}>重试连接</button>:null}</form><p className="account-switch">{operation==='register'?<>已有账号？<LocalLink data-interaction-id={'account:'+operation+':'+'login-link'} href="/login">登录</LocalLink></>:<>还没有账号？<LocalLink data-interaction-id={'account:'+operation+':'+'register-link'} href="/register">注册</LocalLink></>}</p></section></main>;
}
