import {useEffect,useRef,useState} from 'react';
import {readLegacyWorkspace,type LegacySnapshot} from './legacy-reader';
import {exportLegacyWorkspace,inspectWorkspaceMigration,type WorkspaceMigrationPlan} from './workspace-migration-package';
import {workspaceMessage,type WorkspaceClient} from '../../infrastructure/api/workspace-client';
import {sessionStore} from '../../infrastructure/api/session';
import type {MigrationBatch,WorkspaceMigration} from '../../domain/workspace-migration';
import {Button} from '../../ui/Button';
import {useCloudDraftGuard} from '../workspace/use-cloud-draft-guard';
export function migrationMessage(error:unknown){const code=error instanceof Error?error.message:'';return ({legacy_close_old_tabs:'请先关闭仍打开旧版的标签页，再重试读取。',legacy_record_invalid:'有旧版记录无法识别，请保留原浏览器资料。',legacy_read_failed:'旧版资料读取未完成，请重试。',legacy_preferences_invalid:'旧版偏好格式无法识别，请保留原始资料。',migration_project_incomplete:'选中项目缺少完整画布，导出未完成。',migration_file_integrity:'原件或缩略图缺失或不符合清单，迁移未完成；原资料已保留。',package_too_large:'所选资料超过迁移包大小限制，请分批选择项目。'} as Record<string,string>)[code]??'迁移包未通过完整性检查。原资料和文件已保留。';}
const historyLabels:Record<string,string>={prompt:'提示词',draft:'创作草稿','video-history':'视频历史','text-history':'文字历史','agent-proposal':'Agent 建议','receipt-history':'操作与对话历史','reference-history':'参考资料'};
function HistoryContent({value}:{value:unknown}){
 if(typeof value==='string')return <p style={{whiteSpace:'pre-wrap'}}>{value}</p>;
 if(Array.isArray(value))return <>{value.map((entry,index)=><HistoryContent key={index} value={entry}/>)}</>;
 if(value&&typeof value==='object')return <>{Object.entries(value).filter(([key])=>!['id','kind','schemaVersion','projectId','conversationId','nodeIds','revision','createdAt','updatedAt'].includes(key)).map(([key,entry])=><HistoryContent key={key} value={entry}/>)}</>;
 return null;
}
export function LegacyImportPage({client}:{client:WorkspaceClient}){
 const [snapshot,setSnapshot]=useState<LegacySnapshot>(),[selected,setSelected]=useState<string[]>([]),[standalone,setStandalone]=useState(false),[trash,setTrash]=useState(true),[preferences,setPreferences]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[file,setFile]=useState<File>(),[plan,setPlan]=useState<WorkspaceMigrationPlan>();
 const [owner,setOwner]=useState(false),[importPreferences,setImportPreferences]=useState(false),[batch,setBatch]=useState<MigrationBatch>(),[batches,setBatches]=useState<MigrationBatch[]>([]),[history,setHistory]=useState<WorkspaceMigration>();
 const alive=useRef(true),urls=useRef(new Set<string>());
 useEffect(()=>{alive.current=true;void client.listImports().then(rows=>{if(alive.current)setBatches(rows);}).catch(()=>{});return()=>{alive.current=false;for(const url of urls.current)URL.revokeObjectURL(url);urls.current.clear();};},[]);
 useCloudDraftGuard(busy,()=>setError('迁移包正在处理，请等待完成。'));
 async function action(work:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setMessage('');try{await work();}catch(e){if(alive.current)setError(workspaceMessage(e)+' '+migrationMessage(e));}finally{if(alive.current)setBusy(false);}}
 async function read(){await action(async()=>{let raw:string|null=null;try{raw=localStorage.getItem('aiwork-studio:preferences');}catch{/* Preference storage may be unavailable; content remains readable. */}const value=await readLegacyWorkspace({preferences:raw});if(alive.current){setSnapshot(value);setSelected([]);setMessage('只读清单已加载。请选择要导出的项目及独立内容。');}});}
 async function download(){if(!snapshot)return;await action(async()=>{const result=await exportLegacyWorkspace(snapshot,{projectIds:selected,includeStandalone:standalone,includeTrash:trash,includePreferences:preferences});if(!alive.current)return;const url=URL.createObjectURL(result.blob);urls.current.add(url);const link=document.createElement('a');link.href=url;link.download=result.filename;link.click();setTimeout(()=>{URL.revokeObjectURL(url);urls.current.delete(url);},1000);setMessage('已触发迁移包下载：'+result.data.projects.length+' 个项目、'+result.data.assets.length+' 个素材、'+result.data.records.length+' 条内容或历史。请妥善保存下载文件。');});}
 async function commit(){if(!plan||!owner)return;await action(async()=>{const identity=sessionStore.getState();if(identity.status!=='authenticated')throw new Error('AUTH_REQUIRED');const current=batch??await client.stageImport(plan.data);if(!alive.current)return;setBatch(current);for(const descriptor of current.files){if(current.state==='committed'||descriptor.uploaded)continue;await client.uploadImportFile(current.id,descriptor.id,plan.files.get(descriptor.path)!);}const result=await client.commitImport(current.id,importPreferences,identity.document.revision);if(!alive.current)return;setBatch(result);setBatches(await client.listImports());if(importPreferences)await sessionStore.reloadDocument();setMessage('迁移已保存到当前账号，请到项目、素材和回收站核对。原文件及本地资料保留。');});}
 return <section className="card"><h1>旧版数据迁移</h1><p>此浏览器的旧版资料可能属于其他使用者。请确认归属后主动导出，核对目标账号再导入。读取和下载不会修改旧库或上传资料。</p><Button data-interaction-id="migration:legacy:read" disabled={busy} onClick={read}>从此浏览器读取旧版内容</Button>{snapshot?<><p>{snapshot.projects.length} 个旧项目 · {snapshot.assets.length} 个素材 · {snapshot.records.length} 条内容或历史</p><fieldset disabled={busy}><legend>导出选择</legend>{snapshot.projects.filter(row=>trash||row.trashedAt===null).map(row=><label key={row.id}><input data-interaction-id="migration:legacy:project" type="checkbox" checked={selected.includes(row.id)} onChange={event=>setSelected(ids=>event.target.checked?[...ids,row.id]:ids.filter(id=>id!==row.id))}/>{row.title}{row.trashedAt!==null?' · 回收站':''}</label>)}<label><input data-interaction-id="migration:legacy:standalone" type="checkbox" checked={standalone} onChange={event=>setStandalone(event.target.checked)}/>包含独立提示词、草稿、素材及其历史</label><label><input data-interaction-id="migration:legacy:trash" type="checkbox" checked={trash} onChange={event=>{setTrash(event.target.checked);if(!event.target.checked)setSelected(ids=>ids.filter(id=>snapshot.projects.find(row=>row.id===id)?.trashedAt===null));}}/>包含所选内容的回收站记录</label><label><input data-interaction-id="migration:legacy:preferences" type="checkbox" checked={preferences} onChange={event=>setPreferences(event.target.checked)}/>包含旧版偏好</label></fieldset><Button data-interaction-id="migration:legacy:download" disabled={busy||!selected.length&&!standalone&&!preferences} onClick={download}>下载所选旧版迁移包</Button></>:null}
 <h2>核对完整迁移包</h2><label>选择工作区迁移包<input data-interaction-id="migration:package:file" type="file" accept=".zip" disabled={busy} onChange={event=>{setFile(event.target.files?.[0]);setPlan(undefined);setBatch(undefined);setOwner(false);setImportPreferences(false);setError('');}}/></label><Button data-interaction-id="migration:package:inspect" disabled={busy||!file} onClick={()=>action(async()=>{const value=await inspectWorkspaceMigration(file!);if(alive.current)setPlan(value);})}>校验迁移包并预览</Button>{plan?<><p>{plan.data.projects.length} 个项目 · {plan.data.assets.length} 个素材 · {plan.data.records.length} 条内容或历史 · {plan.files.size} 个文件</p><p>此包来自旧版浏览器资料，执行授权已移除。导入创建新项目，原包和本地资料保留。</p><label><input data-interaction-id="migration:package:owner" type="checkbox" checked={owner} disabled={busy||batch?.state==='committed'} onChange={event=>setOwner(event.target.checked)}/>我确认这些内容属于当前账号，可以导入</label>{plan.data.preferences?<label><input data-interaction-id="migration:package:preferences" type="checkbox" checked={importPreferences} disabled={busy||batch?.state==='committed'} onChange={event=>setImportPreferences(event.target.checked)}/>明确导入包内偏好</label>:null}<Button data-interaction-id="migration:package:commit" busy={busy} disabled={!owner||batch?.state==='committed'} onClick={commit}>{batch?.state==='committed'?'已导入当前账号':'确认导入当前账号'}</Button></>:null}<h2>导入批次与原始历史</h2>{batches.map(row=><article key={row.id}><p>{row.state==='committed'?'已导入':'文件暂存中'} · {row.counts.projects} 个项目 · {row.counts.records} 条历史</p><Button data-interaction-id="migration:batch:history" disabled={busy} onClick={()=>action(async()=>{const value=await client.importHistory(row.id);if(alive.current)setHistory(value);})}>查看原始只读历史</Button></article>)}{history?<><p>原始导出 {history.exportId}，以下记录不会恢复执行授权。</p>{history.records.map(record=><article key={record.kind+record.id}><h3>{historyLabels[record.kind]}</h3><HistoryContent value={record.document}/><details><summary data-interaction-id="migration:history:detail">查看完整记录</summary><pre>{JSON.stringify(record.document,null,2)}</pre></details></article>)}</>:null}{error?<p role="alert">{error}</p>:null}{message?<p role="status">{message}</p>:null}</section>;
}
