import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import type {Pool,PoolClient} from 'pg';
import type {AuthContext} from '../auth/context.js';
import {transaction} from '../db/transaction.js';
import {HttpError} from '../errors.js';
import {ownedProject,readProjectGraph} from '../projects/repository.js';
import {applyProjectCommandInTransaction} from '../projects/commands.js';
import {findConfig,type ConfigRow} from '../settings/repository.js';
import {userSecrets} from '../tasks/prompt-repository.js';
import type {ApiSettingsDependencies} from '../settings/service.js';
import {cloudAgentConversationSchema,cloudAgentProposalSchema,cloudAgentPreviewSchema,cloudAgentRunSchema,cloudAgentContextSchema,type CloudAgentConversation} from '../../../src/domain/cloud-agent.js';
import {agentGrantSchema,type AgentGrant} from '../../../src/domain/agent-session.js';
import {buildAgentAdviceRequest} from '../../../src/domain/agent-advice.js';
import {boundedText,localText,id as operationId} from '../../../src/domain/common.js';
import {projectCommandSchema} from '../projects/contracts.js';
export const createConversationSchema=z.strictObject({title:boundedText(1,60),idempotencyKey:z.uuid()});
export const noteSchema=z.strictObject({expectedRevision:z.number().int().nonnegative(),body:localText.refine(text=>!!text.trim()),context:cloudAgentContextSchema,idempotencyKey:z.uuid()});
export const grantSchema=z.strictObject({expectedRevision:z.number().int().nonnegative(),scope:z.enum(['selection','nodes','project']),nodeIds:z.array(z.uuid()).max(1000),access:z.enum(['read','propose'])});
export const previewSchema=z.strictObject({expectedRevision:z.number().int().nonnegative(),graphRevision:z.number().int().nonnegative(),configRevision:z.number().int().positive(),description:localText.refine(text=>!!text.trim())});
export const confirmationSchema=z.strictObject({approvalId:z.uuid(),decision:z.strictObject({confirmed:z.literal(true),acknowledgeTextFee:z.literal(true),acknowledgePriorUnknown:z.literal(true).optional()})});
export const decisionSchema=z.strictObject({expectedRevision:z.number().int().nonnegative(),decision:z.enum(['apply','reject']),operationIds:z.array(operationId).max(100)});
export async function ownedConversation(db:Pool|PoolClient,context:AuthContext,id:string,lock=false){const rows=await db.query<{document:unknown}>('SELECT document FROM workspace_agent_conversations WHERE user_id=$1 AND id::text=$2'+(lock?' FOR UPDATE':''),[context.userId,id]);if(!rows.rows[0])throw new HttpError(404,'NOT_FOUND');return cloudAgentConversationSchema.parse(rows.rows[0].document);}
export async function writeConversation(db:PoolClient,context:AuthContext,document:CloudAgentConversation){const value=cloudAgentConversationSchema.parse(document);if(Buffer.byteLength(JSON.stringify(value))>8*1024*1024)throw new HttpError(413,'BODY_TOO_LARGE');await db.query('UPDATE workspace_agent_conversations SET document=$3::jsonb WHERE user_id=$1 AND id=$2',[context.userId,value.id,JSON.stringify(value)]);await db.query('INSERT INTO workspace_agent_versions(user_id,id,revision,document) VALUES($1,$2,$3,$4::jsonb)',[context.userId,value.id,value.revision,JSON.stringify(value)]);return value;}
async function ownedWritableGraph(db:PoolClient,context:AuthContext,projectId:string){const project=await ownedProject(db,context,projectId,true);if(project.trashedAt!==null)throw new HttpError(409,'PROJECT_IN_TRASH');return readProjectGraph(db,context,projectId);}
function validScope(nodeIds:string[],scope:string,graph:Awaited<ReturnType<typeof readProjectGraph>>){if(new Set(nodeIds).size!==nodeIds.length||scope==='project'&&nodeIds.length||scope!=='project'&&!nodeIds.length||nodeIds.some(id=>!graph.nodes.some(node=>node.id===id)))throw new HttpError(422,'AGENT_SCOPE_INVALID');}
export function requireGrant(conversation:CloudAgentConversation,now:Date,frozen?:AgentGrant){const grant=conversation.grant;if(conversation.historical||!grant||grant.access!=='propose'||grant.expiresAt<=now.getTime()||frozen&&JSON.stringify(grant)!==JSON.stringify(agentGrantSchema.parse(frozen)))throw new HttpError(409,'GRANT_CHANGED');return grant;}
export async function listConversations(pool:Pool,context:AuthContext,projectId:string){await ownedProject(pool,context,projectId);const rows=await pool.query<{document:unknown}>('SELECT document FROM workspace_agent_conversations WHERE user_id=$1 AND project_id=$2 ORDER BY (document->>\'updatedAt\')::bigint DESC,id',[context.userId,projectId]);return rows.rows.map(row=>cloudAgentConversationSchema.parse(row.document));}
export async function createConversation(pool:Pool,context:AuthContext,projectId:string,input:z.infer<typeof createConversationSchema>,now:Date){return transaction(pool,async db=>{
 await ownedWritableGraph(db,context,projectId);const fingerprint=JSON.stringify({kind:'conversation',projectId,...input});await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[context.userId+':agent:'+input.idempotencyKey]);const prior=await db.query<{conversation_id:string;fingerprint:string}>('SELECT conversation_id,fingerprint FROM workspace_agent_receipts WHERE user_id=$1 AND id=$2',[context.userId,input.idempotencyKey]);if(prior.rows[0]){if(prior.rows[0].fingerprint!==fingerprint)throw new HttpError(409,'IDEMPOTENCY_CONFLICT');return ownedConversation(db,context,prior.rows[0].conversation_id);}
 const document=cloudAgentConversationSchema.parse({id:randomUUID(),projectId,title:input.title,revision:0,grant:null,notes:[],createdAt:now.getTime(),updatedAt:now.getTime()});await db.query('INSERT INTO workspace_agent_conversations(user_id,id,project_id,document) VALUES($1,$2,$3,$4::jsonb)',[context.userId,document.id,projectId,JSON.stringify(document)]);await writeConversation(db,context,document);await db.query('INSERT INTO workspace_agent_receipts(user_id,id,conversation_id,fingerprint) VALUES($1,$2,$3,$4)',[context.userId,input.idempotencyKey,document.id,fingerprint]);return document;
});}
export async function appendNote(pool:Pool,context:AuthContext,id:string,input:z.infer<typeof noteSchema>,now:Date){return transaction(pool,async db=>{
 const conversation=await ownedConversation(db,context,id,true);if(conversation.historical)throw new HttpError(409,'HISTORY_READONLY');const fingerprint=JSON.stringify({kind:'note',id,...input});await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[context.userId+':agent:'+input.idempotencyKey]);const prior=await db.query<{fingerprint:string}>('SELECT fingerprint FROM workspace_agent_receipts WHERE user_id=$1 AND id=$2',[context.userId,input.idempotencyKey]);if(prior.rows[0]){if(prior.rows[0].fingerprint!==fingerprint)throw new HttpError(409,'IDEMPOTENCY_CONFLICT');return conversation;}
 if(conversation.revision!==input.expectedRevision)throw new HttpError(409,'REVISION_CONFLICT');const graph=await ownedWritableGraph(db,context,conversation.projectId);if(graph.revision!==input.context.revision)throw new HttpError(409,'REVISION_CONFLICT');validScope(input.context.nodeIds,input.context.scope,graph);
 const value=await writeConversation(db,context,{...conversation,revision:conversation.revision+1,notes:[...conversation.notes,{id:randomUUID(),body:input.body,context:input.context,createdAt:now.getTime()}],updatedAt:now.getTime()});await db.query('INSERT INTO workspace_agent_receipts(user_id,id,conversation_id,fingerprint) VALUES($1,$2,$3,$4)',[context.userId,input.idempotencyKey,id,fingerprint]);return value;
});}
export async function changeGrant(pool:Pool,context:AuthContext,id:string,input:z.infer<typeof grantSchema>|{expectedRevision:number},now:Date){return transaction(pool,async db=>{
 const conversation=await ownedConversation(db,context,id,true);if(conversation.historical)throw new HttpError(409,'HISTORY_READONLY');if(conversation.revision!==input.expectedRevision)throw new HttpError(409,'REVISION_CONFLICT');const graph=await ownedWritableGraph(db,context,conversation.projectId);let grant:AgentGrant|null=null;if('scope' in input){validScope(input.nodeIds,input.scope,graph);grant=agentGrantSchema.parse({projectId:graph.projectId,scope:input.scope,nodeIds:input.nodeIds,access:input.access,epoch:conversation.revision+1,expiresAt:now.getTime()+10*60*1000});}return writeConversation(db,context,{...conversation,revision:conversation.revision+1,grant,updatedAt:now.getTime()});
});}
async function priorUnknown(db:Pool|PoolClient,context:AuthContext,conversationId:string){const rows=await db.query<{id:string}>("SELECT id FROM workspace_agent_runs WHERE user_id=$1 AND conversation_id=$2 AND document->>'executionState' IN ('sending','response_unknown') ORDER BY id",[context.userId,conversationId]);return rows.rows.map(row=>row.id);}
export async function prepareAgentPreview(pool:Pool,context:AuthContext,id:string,input:z.infer<typeof previewSchema>,dependencies:ApiSettingsDependencies,now:Date){return transaction(pool,async db=>{
 const conversation=await ownedConversation(db,context,id,true);if(conversation.revision!==input.expectedRevision)throw new HttpError(409,'REVISION_CONFLICT');const grant=requireGrant(conversation,now),graph=await ownedWritableGraph(db,context,conversation.projectId);if(graph.revision!==input.graphRevision)throw new HttpError(409,'REVISION_CONFLICT');validScope(grant.nodeIds,grant.scope,graph);
 await db.query("SELECT id FROM api_configs WHERE user_id=$1 AND channel='text' FOR SHARE",[context.userId]);const config=await findConfig(db,context,'text');if(!config)throw new HttpError(422,'MODEL_CONFIG_REQUIRED');if(config.revision!==input.configRevision)throw new HttpError(409,'CONFIG_CHANGED');let prepared:ReturnType<typeof buildAgentAdviceRequest>;try{prepared=buildAgentAdviceRequest(input.description,graph,grant,config.model);}catch{throw new HttpError(422,'AGENT_CONTEXT_INVALID');}if((await userSecrets(db,context.userId,dependencies)).some(key=>prepared.body.includes(key)||prepared.body.includes(JSON.stringify(key).slice(1,-1))))throw new HttpError(422,'INPUT_CONTAINS_CREDENTIAL');
 const preview=cloudAgentPreviewSchema.parse({id:randomUUID(),conversationId:id,projectId:graph.projectId,conversationRevision:conversation.revision,graphRevision:graph.revision,grantEpoch:grant.epoch,inputSnapshot:prepared.input,apiBase:config.api_base,model:config.model,configRevision:config.revision,priorUnknownRunIds:await priorUnknown(db,context,id),expiresAt:now.getTime()+120000});await db.query('INSERT INTO workspace_agent_previews(user_id,id,conversation_id,document,frozen_config,frozen_graph,frozen_grant,request_body) VALUES($1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb,$7::jsonb,$8)',[context.userId,preview.id,id,JSON.stringify(preview),JSON.stringify(config),JSON.stringify(graph),JSON.stringify(grant),prepared.body]);return preview;
});}
export async function confirmAgentPreview(pool:Pool,context:AuthContext,id:string,input:z.infer<typeof confirmationSchema>,now:Date){return transaction(pool,async db=>{
 const conversation=await ownedConversation(db,context,id,true),rows=await db.query<{document:unknown;frozen_config:ConfigRow;frozen_graph:unknown;frozen_grant:AgentGrant;request_body:string;task_id:string|null}>('SELECT document,frozen_config,frozen_graph,frozen_grant,request_body,task_id FROM workspace_agent_previews WHERE user_id=$1 AND id=$2 AND conversation_id=$3 FOR UPDATE',[context.userId,input.approvalId,id]);const row=rows.rows[0];if(!row)throw new HttpError(404,'NOT_FOUND');if(row.task_id){const task=await db.query<{document:unknown}>('SELECT document FROM workspace_agent_runs WHERE user_id=$1 AND id=$2',[context.userId,row.task_id]);return cloudAgentRunSchema.parse(task.rows[0]!.document);}
 const preview=cloudAgentPreviewSchema.parse(row.document);if(preview.expiresAt<=now.getTime()||preview.conversationRevision!==conversation.revision)throw new HttpError(409,'PREVIEW_EXPIRED');requireGrant(conversation,now,row.frozen_grant);const graph=await ownedWritableGraph(db,context,conversation.projectId);if(graph.revision!==preview.graphRevision)throw new HttpError(409,'PREVIEW_EXPIRED');await db.query("SELECT id FROM api_configs WHERE user_id=$1 AND channel='text' FOR SHARE",[context.userId]);const config=await findConfig(db,context,'text');if(!config||(['id','user_id','api_base','model','revision','active_secret_version'] as const).some(key=>config[key]!==row.frozen_config[key]))throw new HttpError(409,'CONFIG_CHANGED');const unknown=await priorUnknown(db,context,id);if(JSON.stringify(unknown)!==JSON.stringify(preview.priorUnknownRunIds))throw new HttpError(409,'PREVIEW_EXPIRED');if(unknown.length&&!input.decision.acknowledgePriorUnknown)throw new HttpError(422,'PRIOR_UNKNOWN_CONFIRMATION_REQUIRED');
 const run=cloudAgentRunSchema.parse({id:randomUUID(),kind:'agent-advice',projectId:graph.projectId,conversationId:id,inputSnapshot:preview.inputSnapshot,apiBase:config.api_base,model:config.model,configRevision:config.revision,secretVersion:config.active_secret_version,executionState:'persisted',billingState:'not_provided',createdAt:now.getTime(),updatedAt:now.getTime()});await db.query('INSERT INTO workspace_agent_runs(user_id,id,conversation_id,config_id,secret_version,frozen_config,frozen_graph,frozen_grant,document,request_body,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8::jsonb,$9::jsonb,$10,$11,$11)',[context.userId,run.id,id,config.id,config.active_secret_version,JSON.stringify(config),JSON.stringify(row.frozen_graph),JSON.stringify(row.frozen_grant),JSON.stringify(run),row.request_body,now]);await db.query('UPDATE workspace_agent_previews SET task_id=$3 WHERE user_id=$1 AND id=$2',[context.userId,preview.id,run.id]);return run;
});}
export async function ownedProposal(db:Pool|PoolClient,context:AuthContext,id:string,lock=false){const rows=await db.query<{document:unknown;frozen_grant:AgentGrant}>('SELECT document,frozen_grant FROM workspace_agent_proposals WHERE user_id=$1 AND id::text=$2'+(lock?' FOR UPDATE':''),[context.userId,id]);if(!rows.rows[0])throw new HttpError(404,'NOT_FOUND');const document=cloudAgentProposalSchema.parse(rows.rows[0].document);return {document,grant:document.historical?undefined:agentGrantSchema.parse(rows.rows[0].frozen_grant)};}
export async function listProposals(pool:Pool,context:AuthContext,conversationId:string){await ownedConversation(pool,context,conversationId);const rows=await pool.query<{document:unknown}>('SELECT document FROM workspace_agent_proposals WHERE user_id=$1 AND conversation_id=$2 ORDER BY id',[context.userId,conversationId]);return rows.rows.map(row=>cloudAgentProposalSchema.parse(row.document));}
export async function decideProposal(pool:Pool,context:AuthContext,id:string,input:z.infer<typeof decisionSchema>,now:Date){return transaction(pool,async db=>{
 const owned=await ownedProposal(db,context,id,true),proposal=owned.document;if(proposal.historical)throw new HttpError(409,'HISTORY_READONLY');const selected=proposal.operations.filter(op=>input.operationIds.includes(op.id));if(new Set(input.operationIds).size!==input.operationIds.length||selected.length!==input.operationIds.length||input.decision==='apply'&&!selected.length)throw new HttpError(400,'INVALID_REQUEST');const decision=proposal.decisions.at(-1);if(decision){if(decision.decision!==(input.decision==='apply'?'applied':'rejected')||JSON.stringify([...decision.operationIds].sort())!==JSON.stringify([...input.operationIds].sort()))throw new HttpError(409,'PROPOSAL_ALREADY_DECIDED');return proposal;}if(proposal.revision!==input.expectedRevision||proposal.status!=='proposed')throw new HttpError(409,'REVISION_CONFLICT');
 const conversation=await ownedConversation(db,context,proposal.conversationId,true);let graphRevision:number|undefined;if(input.decision==='apply'){requireGrant(conversation,now,owned.grant);const command=projectCommandSchema.parse({expectedRevision:proposal.baseRevision,idempotencyKey:proposal.id,command:{type:'operations',operations:selected}});const result=await applyProjectCommandInTransaction(db,context,proposal.projectId,command,now);graphRevision=result.graph.revision;}
 const document=cloudAgentProposalSchema.parse({...proposal,status:input.decision==='apply'?'applied':'rejected',revision:proposal.revision+1,decisions:[{decision:input.decision==='apply'?'applied':'rejected',operationIds:input.operationIds,createdAt:now.getTime(),...(graphRevision!==undefined?{graphRevision}:{})}]});await db.query('UPDATE workspace_agent_proposals SET document=$3::jsonb WHERE user_id=$1 AND id=$2',[context.userId,id,JSON.stringify(document)]);return document;
});}
