import {emitAgentChanges} from '../../features/agent/agent-events';
import {proposalSchema,type Proposal} from '../../domain/proposal';
import type {CommandReceipt} from '../commands/registry';
import {withDatabase,transact,requestResult,storageErrorCode,type StudioDb} from '../../infrastructure/storage/database';
import {validateProposal,selectProposalOperations,assertProposalGraphScope} from './validate-proposal';
import {getAgentSession,heartbeatAgent,getOpenedCanvasIdentity} from '../../features/agent/agent-client';
import {applyCommand} from '../commands/apply-command';
import {graphSchema} from '../../domain/graph';
import {getActiveCore} from '../../adapters/core/current-connection';
import type {AgentSession} from '../../domain/agent-session';
function requireSession(id:string,expected?:AgentSession){const session=getAgentSession(id);if(!session?.connected||session.grant.expiresAt<=Date.now()||session.grant.access!=='propose'||expected&&JSON.stringify(session.grant)!==JSON.stringify(expected.grant))throw Error('agent_propose_permission_required');return session;}
export async function listProjectProposals(projectId:string,db?:StudioDb){return withDatabase(db,c=>transact(c,['proposals'],'readonly',async tx=>(await requestResult<unknown[]>(tx.objectStore('proposals').getAll())).map(p=>proposalSchema.parse(p)).filter(p=>p.projectId===projectId)));}
export async function readProposal(id:string,db?:StudioDb){return withDatabase(db,c=>transact(c,['proposals'],'readonly',async tx=>proposalSchema.parse(await requestResult(tx.objectStore('proposals').get(id)))));}
export async function receiveProposal(raw:unknown,db?:StudioDb):Promise<Proposal>{const proposal=proposalSchema.parse(raw),session=requireSession(proposal.sessionId),checked=validateProposal(raw,session.grant);if(!checked.ok)throw Error(checked.issues[0].code);await withDatabase(db,c=>transact(c,['proposals'],'readwrite',async tx=>{requireSession(proposal.sessionId,session);const prior=await requestResult<Proposal|undefined>(tx.objectStore('proposals').get(proposal.id));if(prior){if(JSON.stringify({...prior,status:'proposed'})!==JSON.stringify(proposal))throw Error('proposal_id_reused');return;}tx.objectStore('proposals').put(proposal);}));emitAgentChanges();return proposal;}
export async function rejectProposal(id:string,db?:StudioDb){await withDatabase(db,c=>transact(c,['proposals','receipts'],'readwrite',async tx=>{const proposal=proposalSchema.parse(await requestResult(tx.objectStore('proposals').get(id)));if(proposal.status==='applied')throw Error('proposal_already_applied');tx.objectStore('proposals').put({...proposal,status:'rejected'});tx.objectStore('receipts').put({id:'agent-decision:'+id,kind:'agent-proposal-decision',projectId:proposal.projectId,sessionId:proposal.sessionId,proposalId:id,decision:'rejected',createdAt:Date.now()});}));emitAgentChanges();}
export async function applyProposal(id:string,selectedOperationIds:string[],options:{db?:StudioDb}={}):Promise<CommandReceipt>{try{const proposal=await readProposal(id,options.db);requireSession(proposal.sessionId);const session=await heartbeatAgent(proposal.sessionId),checked=validateProposal({...proposal,status:'proposed'},session.grant);if(!checked.ok)throw Error(checked.issues[0].code);const operations=selectProposalOperations(proposal,selectedOperationIds),lease=await getOpenedCanvasIdentity(proposal.projectId);if(lease.epoch!==session.grant.epoch)throw Error('agent_epoch_mismatch');const prior=await withDatabase(options.db,c=>transact(c,['receipts'],'readonly',tx=>requestResult<{selectedOperationIds:string[];revision:number}|undefined>(tx.objectStore('receipts').get('agent-decision:'+id))));if(prior){if(JSON.stringify(prior.selectedOperationIds)!==JSON.stringify(selectedOperationIds))throw Error('proposal_already_decided');return {id:'agent-command:'+id,status:'replayed',revision:prior.revision};}if(proposal.status!=='proposed')throw Error('proposal_not_pending');const result=await applyCommand({id:'agent-command:'+id,projectId:proposal.projectId,baseRevision:proposal.baseRevision,leaseEpoch:lease.epoch,origin:'mcp',operations},{db:options.db,lease,origin:'mcp',capability:getActiveCore()?.capability,authorize:()=>{requireSession(proposal.sessionId,session);},beforeCreativeCommit:async tx=>{requireSession(proposal.sessionId,session);const current=proposalSchema.parse(await requestResult(tx.objectStore('proposals').get(id)));if(current.status!=='proposed'||JSON.stringify(current)!==JSON.stringify(proposal))throw Error('proposal_changed');const graph=graphSchema.parse(await requestResult(tx.objectStore('graphs').get(proposal.projectId)));assertProposalGraphScope(graph,operations,session.grant);tx.objectStore('proposals').put({...proposal,status:'applied'});tx.objectStore('receipts').put({id:'agent-decision:'+id,kind:'agent-proposal-decision',projectId:proposal.projectId,sessionId:proposal.sessionId,proposalId:id,decision:'applied',selectedOperationIds:[...selectedOperationIds],count:operations.length,deleted:operations.filter(o=>o.type==='remove_node').length,revision:graph.revision+1,createdAt:Date.now()});}});if(result.status==='conflict')await withDatabase(options.db,c=>transact(c,['proposals'],'readwrite',async tx=>{const current=proposalSchema.parse(await requestResult(tx.objectStore('proposals').get(id)));if(current.status==='proposed'&&JSON.stringify(current)===JSON.stringify(proposal))tx.objectStore('proposals').put({...current,status:'conflict'});}));emitAgentChanges();return result;}catch(error){return {id:'agent-command:'+id,status:'rejected',errorCode:storageErrorCode(error)};}}
