import {proposalSchema,type Proposal} from '../../domain/proposal';
import {agentGrantSchema,type AgentGrant} from '../../domain/agent-session';
import {byteLength,snapshotSchema,type ValidationResult} from '../../domain/common';
import {commandEnvelopeSchema,executeGraphOperations,type GraphOperation} from '../commands/registry';
import type {Graph} from '../../domain/graph';
import {snapshotAssetIds} from '../../features/assets/reference-index';
const denied=(code:string):ValidationResult<Proposal>=>({ok:false,issues:[{code,path:'proposal',message:'提案超出当前权限、结构或依赖范围，未修改画布。'}]});
export function proposalNodeReferences(op:GraphOperation):string[]{const p=op.payload;if(op.type==='add_edge'){const edge=p.edge as {sourceId:string;targetId:string};return [edge.sourceId,edge.targetId];}if(op.type==='group'){const node=p.node as {data:{childIds:string[]}};return node.data.childIds;}return typeof p.nodeId==='string'?[p.nodeId]:[];}
export function createdProposalNodes(operations:GraphOperation[]){return new Map(operations.filter(op=>op.type==='add_node'||op.type==='group').map(op=>[(op.payload.node as {id:string}).id,op.id]));}
export function validateProposal(raw:unknown,grant:AgentGrant):ValidationResult<Proposal>{try{const g=agentGrantSchema.parse(grant);if(g.access!=='propose'||g.expiresAt<=Date.now())return denied('agent_propose_permission_required');if(!snapshotSchema.safeParse(raw).success||byteLength(JSON.stringify(raw))>262144)return denied('proposal_payload_limit');const p=proposalSchema.parse(raw);if(p.status!=='proposed'||p.projectId!==g.projectId||!p.operations.length||p.operations.length>100)return denied('proposal_scope_or_size');if(g.scope!=='project'&&!g.nodeIds.length)return denied('agent_empty_scope');const command=commandEnvelopeSchema.safeParse({id:'agent-command:'+p.id,projectId:p.projectId,baseRevision:p.baseRevision,leaseEpoch:g.epoch,origin:'mcp',operations:p.operations});if(!command.success)return denied('proposal_command_schema');const created=createdProposalNodes(p.operations),allowed=new Set([...g.nodeIds,...created.keys()]);if(g.scope!=='project'&&p.operations.some(op=>proposalNodeReferences(op).some(id=>!allowed.has(id))))return denied('proposal_node_scope');return {ok:true,value:p};}catch{return denied('proposal_invalid');}}
export function selectProposalOperations(proposal:Proposal,selectedIds:string[]):GraphOperation[]{if(!selectedIds.length||new Set(selectedIds).size!==selectedIds.length||selectedIds.some(id=>!proposal.operations.some(op=>op.id===id)))throw Error('proposal_selection_invalid');const selected=new Set(selectedIds),created=createdProposalNodes(proposal.operations),operations=proposal.operations.filter(op=>selected.has(op.id));for(const op of operations)for(const ref of proposalNodeReferences(op)){const prerequisite=created.get(ref);if(prerequisite&&!selected.has(prerequisite))throw Error('proposal_dependency_missing');}return operations;}
export function assertProposalGraphScope(graph:Graph,operations:GraphOperation[],grant:AgentGrant){if(graph.projectId!==grant.projectId)throw Error('proposal_project_scope');const next=executeGraphOperations(graph,operations);if(grant.scope==='project')return;const allowed=new Set(grant.nodeIds),created=createdProposalNodes(operations),assets=snapshotAssetIds(graph.nodes.filter(n=>allowed.has(n.id)));for(const node of graph.nodes){const changed=next.nodes.find(n=>n.id===node.id);if(!allowed.has(node.id)&&JSON.stringify(changed)!==JSON.stringify(node))throw Error('proposal_node_scope');}for(const op of operations){if(op.type==='remove_edge'){const edge=graph.edges.find(e=>e.id===op.payload.edgeId);if(edge&&(!allowed.has(edge.sourceId)||!allowed.has(edge.targetId)))throw Error('proposal_edge_scope');}if(['remove_node','update_node','select_result'].includes(op.type)&&typeof op.payload.nodeId==='string')for(const edge of graph.edges.filter(e=>e.sourceId===op.payload.nodeId))if(!allowed.has(edge.targetId)&&!created.has(edge.targetId))throw Error('proposal_downstream_scope');}for(const assetId of snapshotAssetIds(next.nodes.filter(n=>created.has(n.id)||allowed.has(n.id))))if(!assets.has(assetId))throw Error('proposal_asset_scope');}
