import {z} from 'zod';
import {isAbsolute} from 'node:path';
import {lstat,readFile} from 'node:fs/promises';
import {deploymentContractSchema} from '../../src/adapters/core/capabilities.js';
import {normalizeModelBase} from './security/outbound.js';
const absolute=z.string().refine(isAbsolute),name=z.string().regex(/^[a-z_][a-z0-9_]{0,62}$/),port=z.number().int().min(1024).max(65535);
export const runtimeConfigSchema=z.strictObject({origin:z.url().refine(value=>{const url=new URL(value);return url.protocol==='https:'&&url.origin===value&&!url.username&&!url.password;}),host:z.literal('127.0.0.1'),port,database:z.strictObject({host:z.literal('127.0.0.1'),port,name,user:name}),secretsFile:absolute,assets:z.strictObject({root:absolute,maxAssetBytes:z.number().int().positive().max(200*1024*1024),userQuotaBytes:z.number().int().positive(),maxThumbnailBytes:z.number().int().positive()}),videoContracts:z.array(z.strictObject({apiBase:z.string().transform(normalizeModelBase),contract:deploymentContractSchema.refine(value=>value.verification!=='unknown'&&value.evidence.length>0&&!value.evidence.some(entry=>entry.kind==='mock'),'Production requires reviewed non-mock contracts')})).max(20)}).superRefine((value,ctx)=>{if(value.assets.userQuotaBytes<value.assets.maxAssetBytes||value.assets.maxThumbnailBytes>value.assets.maxAssetBytes)ctx.addIssue({code:'custom',message:'Explicit storage capacity required'});if(new Set(value.videoContracts.map(row=>row.apiBase)).size!==value.videoContracts.length)ctx.addIssue({code:'custom',message:'Duplicate provider policy'});});
export type RuntimeConfig=z.infer<typeof runtimeConfigSchema>;
const secretSchema=z.strictObject({databasePassword:z.string().min(1).max(4096),activeVersion:z.string().regex(/^[A-Za-z0-9_.-]{1,64}$/),keys:z.record(z.string().regex(/^[A-Za-z0-9_.-]{1,64}$/),z.string().regex(/^[A-Za-z0-9+/]{43}=$/))});
export function parseRuntimeSecrets(input:unknown){const value=secretSchema.parse(input),keys=new Map(Object.entries(value.keys).map(([version,key])=>[version,Buffer.from(key,'base64')]));if(!keys.has(value.activeVersion)||[...keys.values()].some(key=>key.length!==32))throw new Error('INVALID_ENCRYPTION_ROOT');return {...value,keys};}
export async function readRuntimeConfig(path:string){if(!isAbsolute(path))throw new Error('ABSOLUTE_RUNTIME_PATH_REQUIRED');const raw=await readFile(path,'utf8');if(Buffer.byteLength(raw)>1024*1024)throw new Error('RUNTIME_CONFIG_TOO_LARGE');return runtimeConfigSchema.parse(JSON.parse(raw));}
export async function readRuntimeSecrets(path:string){const info=await lstat(path);if(!info.isFile()||info.size>1024*1024||process.platform!=='win32'&&((info.mode&0o077)!==0||info.uid!==process.getuid!()&&info.uid!==0))throw new Error('PRIVATE_SECRETS_FILE_REQUIRED');return parseRuntimeSecrets(JSON.parse(await readFile(path,'utf8')));}
