import {z} from 'zod';
import {promptLibrarySchema,type PromptLibraryEntry} from '../../domain/prompt';
import {localText,type ValidationResult,boundedText} from '../../domain/common';
import {withDatabase,transact,requestResult,type StudioDb} from '../../infrastructure/storage/database';
import {readGraph} from '../../infrastructure/storage/project-repository';
import {getProjectWriter} from '../projects/project-service';
import {releaseProjectLease} from '../../infrastructure/storage/project-lease';
import {applyUiCommand} from '../../application/commands/apply-command';
import type {GraphOperation} from '../../application/commands/registry';
export function templateNames(entry:PromptLibraryEntry){return [...new Set([...entry.variables,...Array.from(entry.body.matchAll(/\{\{\s*([^{}]+?)\s*\}\}/g),match=>match[1].trim())])];}
const validName=(name:string)=>!!name.trim()&&!['__proto__','constructor','prototype'].includes(name)&&!/[{}]/.test(name);
export function fillTemplate(entry:PromptLibraryEntry,values:Record<string,string>):ValidationResult<string>{if(!entry.body.trim())return {ok:false,issues:[{code:'prompt_body_required',path:'body',message:'正文不能为空'}]};if(new Set(entry.variables).size!==entry.variables.length)return {ok:false,issues:[{code:'template_variable_duplicate',path:'variables',message:'变量声明重复'}]};const names=templateNames(entry),issues=names.flatMap(name=>!validName(name)?[{code:'template_variable_invalid',path:name,message:'变量名称无效'}]:!Object.hasOwn(values,name)||typeof values[name]!=='string'||!values[name].trim()?[{code:'template_variable_missing',path:name,message:'请填写变量：'+name}]:[]);if(/\{\{\s*\}\}/.test(entry.body))issues.push({code:'template_variable_invalid',path:'body',message:'模板中有空变量'});if(issues.length)return {ok:false,issues};const value=entry.body.replace(/\{\{\s*([^{}]+?)\s*\}\}/g,(_,name:string)=>values[name.trim()]);if(!localText.safeParse(value).success)return {ok:false,issues:[{code:'prompt_text_too_large',path:'body',message:'填值后的正文超过64KiB'}]};return {ok:true,value};}
export async function listPrompts(db?:StudioDb){return withDatabase(db,c=>transact(c,['prompts'],'readonly',async tx=>(await requestResult<unknown[]>(tx.objectStore('prompts').getAll())).map(p=>promptLibrarySchema.parse(p))));}
function validateEntry(entry:PromptLibraryEntry){const parsed=promptLibrarySchema.parse(entry);if(!parsed.title.trim()||!parsed.body.trim())throw new Error('prompt_title_body_required');if(parsed.variables.some(n=>!validName(n))||new Set(parsed.variables).size!==parsed.variables.length)throw new Error('prompt_variable_invalid');return parsed;}
export async function savePrompt(entry:PromptLibraryEntry,expectedRevision?:number,options:{db?:StudioDb}={}):Promise<PromptLibraryEntry>{const input=validateEntry(entry);return withDatabase(options.db,c=>transact(c,['prompts','receipts'],'readwrite',async tx=>{const raw=await requestResult(tx.objectStore('prompts').get(input.id)),previous=raw?promptLibrarySchema.parse(raw):undefined;if((previous?.revision??0)!==(expectedRevision??input.revision))throw new Error('prompt_revision_conflict');const saved=promptLibrarySchema.parse({...input,revision:(previous?.revision??0)+1});tx.objectStore('prompts').put(saved);tx.objectStore('receipts').put({id:crypto.randomUUID(),kind:'prompt-version',entryId:saved.id,...previous?{before:previous}:{},after:saved,at:Date.now()});return saved;}));}
export const promptTransferSchema=z.strictObject({version:z.literal(1),entries:z.array(promptLibrarySchema.pick({title:true,body:true,tags:true,variables:true,source:true,license:true})).min(1)});
export function previewPromptImport(text:string){if(new TextEncoder().encode(text).byteLength>16*1024*1024)throw new Error('prompt_import_too_large');const parsed=promptTransferSchema.parse(JSON.parse(text));return parsed.entries.map(item=>validateEntry({...item,id:crypto.randomUUID(),revision:0,starred:false,trashed:false}));}
export async function importPromptEntries(entries:PromptLibraryEntry[],db?:StudioDb){const candidates=entries.map(entry=>validateEntry({...entry,id:crypto.randomUUID(),revision:1,starred:false,trashed:false}));return withDatabase(db,c=>transact(c,['prompts','receipts'],'readwrite',tx=>{for(const entry of candidates){tx.objectStore('prompts').put(entry);tx.objectStore('receipts').put({id:crypto.randomUUID(),kind:'prompt-import',entryId:entry.id,source:entry.source,license:entry.license,at:Date.now()});}return candidates;}));}
export const exportPrompts=(entries:PromptLibraryEntry[])=>JSON.stringify({version:1,entries:entries.map(entry=>({title:entry.title,body:entry.body,tags:entry.tags,variables:entry.variables,source:entry.source,license:entry.license}))},null,2);
export async function usePrompt(entry:PromptLibraryEntry,text:string,projectId:string,nodeId?:string,baseRevision?:number){localText.parse(text);const lease=await getProjectWriter(projectId);try{const graph=await readGraph(projectId);if(!graph)throw new Error('project_missing');if(baseRevision!==undefined&&graph.revision!==baseRevision)throw new Error('project_revision_conflict');const node=graph.nodes.find(n=>n.id===nodeId);if(nodeId&&(!node||node.type!=='text'||node.locked))throw new Error('prompt_target_not_editable');const data={kind:'text' as const,text,referenceTokens:node?.type==='text'?node.data.referenceTokens:[],promptLibrarySource:{entryId:entry.id,revision:entry.revision,source:entry.source,license:entry.license}};const operation:GraphOperation=node?{id:crypto.randomUUID(),type:'update_node',payload:{nodeId:node.id,patch:{data}}}:{id:crypto.randomUUID(),type:'add_node',payload:{node:{id:crypto.randomUUID(),title:boundedText(1,60).safeParse(entry.title).success?entry.title:'提示词文本',type:'text',x:64,y:64,locked:false,data}}};const receipt=await applyUiCommand({id:crypto.randomUUID(),projectId,baseRevision:graph.revision,operations:[operation]},{lease});if(receipt.status!=='applied')throw new Error(receipt.errorCode??'prompt_apply_failed');return receipt;}finally{await releaseProjectLease(lease);}}
export async function setPromptSource(source:string,enabled:boolean){return withDatabase(undefined,db=>transact(db,['diagnostics'],'readwrite',async tx=>{const prior=(await requestResult<{id:string;kind?:string;source?:string}[]>(tx.objectStore('diagnostics').getAll())).find(row=>row.kind==='prompt-source'&&row.source===source);tx.objectStore('diagnostics').put({id:prior?.id??crypto.randomUUID(),kind:'prompt-source',source,enabled});}));}
export async function removePromptSourceCache(source:string){return withDatabase(undefined,db=>transact(db,['diagnostics'],'readwrite',async tx=>{const rows=await requestResult<{id:string;kind?:string;source?:string}[]>(tx.objectStore('diagnostics').getAll());for(const row of rows)if(row.kind==='prompt-source'&&row.source===source)tx.objectStore('diagnostics').delete(row.id);}));}
