import {useEffect,useRef,useState} from 'react';
import type {PromptLibraryEntry} from '../../domain/prompt';
import {Dialog} from '../../ui/Dialog';
import {Button} from '../../ui/Button';
import {savePrompt} from './prompt-library';
import {navigate,addNavigationGuard} from '../../app/routes';
export function newPrompt(body='',title='',source='用户本地创作'):PromptLibraryEntry{return {id:crypto.randomUUID(),title,body,tags:[],variables:[],source,license:'用户填写的来源与许可尚未核验',revision:0,starred:false,trashed:false};}
export function PromptEditor({entry,onSaved,onClose}:{entry:PromptLibraryEntry;onSaved:(entry:PromptLibraryEntry)=>void;onClose:()=>void}){const [title,setTitle]=useState(entry.title),[body,setBody]=useState(entry.body),[tags,setTags]=useState(entry.tags.join(',')),[variables,setVariables]=useState(entry.variables.join(',')),[source,setSource]=useState(entry.source),[license,setLicense]=useState(entry.license),[error,setError]=useState(''),[discard,setDiscard]=useState(false);const dirty=useRef(false),leavePath=useRef(''),saved=useRef(false),restoreGuard=useRef<()=>void>(()=>{});
 const altered=title!==entry.title||body!==entry.body||tags!==entry.tags.join(',')||variables!==entry.variables.join(',')||source!==entry.source||license!==entry.license;dirty.current=altered&&!saved.current;
 function close(){if(dirty.current)setDiscard(true);else onClose();}
 useEffect(()=>{restoreGuard.current=addNavigationGuard(path=>{if(dirty.current){leavePath.current=path;setDiscard(true);return false;}return true;});const unload=(event:BeforeUnloadEvent)=>{if(dirty.current){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',unload);return()=>{restoreGuard.current();window.removeEventListener('beforeunload',unload);};},[]);
 return <><Dialog open title="编辑提示词" onClose={close} footer={<><Button data-interaction-id="ui:PromptEditor:Button:52a6d3f1f20f" onClick={close}>取消</Button><Button data-interaction-id="L-01" disabled={!title.trim()||!body.trim()} disabledReason={!title.trim()||!body.trim()?'名称和正文不能为空。':undefined} onClick={async()=>{setError('');try{const result=await savePrompt({...entry,title,body,tags:tags?tags.split(/[,，]/).map(value=>value.trim()):[],variables:variables?variables.split(/[,，]/).map(value=>value.trim()):[],source,license},entry.revision);saved.current=true;dirty.current=false;onSaved(result);}catch(e){setError(e instanceof Error&&e.message.includes('conflict')?'提示词版本已变化，未覆盖已保存版本。':'保存失败：检查正文64KiB、标签最多10个/每个1–24字符、变量名称和本地空间。');}}}>保存提示词</Button></>}>{error?<p role="alert">{error}</p>:null}<label>提示词名称<input data-interaction-id="ui:PromptEditor:input:69a71a04f5af" value={title} onChange={event=>setTitle(event.target.value)}/></label><label>提示词正文<textarea data-interaction-id="ui:PromptEditor:textarea:031ebf4819c6" aria-label="提示词正文" value={body} onChange={event=>setBody(event.target.value)}/></label><label>提示词标签<input data-interaction-id="ui:PromptEditor:input:6d705210c8f7" value={tags} onChange={event=>setTags(event.target.value)}/></label><label>模板变量<input data-interaction-id="ui:PromptEditor:input:d1b736cc3af8" value={variables} placeholder="逗号分隔；正文用 {{变量}}" onChange={event=>setVariables(event.target.value)}/></label><label>提示词来源<input data-interaction-id="ui:PromptEditor:input:d80e2f4122ff" value={source} onChange={event=>setSource(event.target.value)}/></label><label>提示词许可<input data-interaction-id="ui:PromptEditor:input:e1ba837e3171" value={license} onChange={event=>setLicense(event.target.value)}/></label><p>保存只写本地提示词库；没有收费调用。</p></Dialog><Dialog open={discard} title="放弃未保存提示词修改" onClose={()=>{setDiscard(false);leavePath.current='';}} footer={<><Button data-interaction-id="ui:PromptEditor:Button:fa1765aadc4f" onClick={()=>{setDiscard(false);leavePath.current='';}}>继续编辑</Button><Button data-interaction-id="ui:PromptEditor:Button:0b8e01a646ee" onClick={()=>{dirty.current=false;restoreGuard.current();onClose();if(leavePath.current)navigate(leavePath.current);}}>确认放弃修改</Button></>}><p>未保存内容会丢失，源条目保持已保存版本。</p></Dialog></>;
}

