import {useEffect,useState} from 'react';
import type {PromptLibraryEntry} from '../../domain/prompt';
import type {Project} from '../../domain/project';
import type {Graph} from '../../domain/graph';
import {projectSchema} from '../../domain/project';
import {graphSchema} from '../../domain/graph';
import {listPrompts,savePrompt,previewPromptImport,importPromptEntries,exportPrompts,usePrompt,setPromptSource,removePromptSourceCache} from './prompt-library';
import {searchPrompts} from './prompt-search';
import {TemplateVariables} from './TemplateVariables';
import {PromptEditor,newPrompt} from './PromptEditor';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
import {triggerLocalDownload} from '../../ui/local-download';
import {withDatabase,transact,requestResult} from '../../infrastructure/storage/database';
import {useRoute,LocalLink} from '../../app/routes';
export function PromptsPage(){
 const route=useRoute(),[entries,setEntries]=useState<PromptLibraryEntry[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[debounced,setDebounced]=useState(''),[tag,setTag]=useState(''),[scope,setScope]=useState<'active'|'starred'|'trash'>('active'),[selected,setSelected]=useState<string[]>([]),[editor,setEditor]=useState<PromptLibraryEntry>(),[detail,setDetail]=useState<PromptLibraryEntry>(),[deletion,setDeletion]=useState<PromptLibraryEntry>(),[deletionRefs,setDeletionRefs]=useState<string[]>([]),[template,setTemplate]=useState<PromptLibraryEntry>(),[importPreview,setImportPreview]=useState<PromptLibraryEntry[]>(),[sourcesOpen,setSourcesOpen]=useState(false),[sourceState,setSourceState]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[error,setError]=useState(''),[target,setTarget]=useState<{text:string;mode:'insert'|'apply'}>(),[targetData,setTargetData]=useState<{projects:Project[];graphs:Graph[]}>({projects:[],graphs:[]}),[diff,setDiff]=useState<{projectId:string;nodeId:string;baseRevision:number;old:string}>();
 useEffect(()=>{if(!sourcesOpen)return;let active=true;void withDatabase(undefined,db=>transact(db,['diagnostics'],'readonly',async tx=>{const rows=await requestResult<{kind?:string;source?:string;enabled?:boolean}[]>(tx.objectStore('diagnostics').getAll());return Object.fromEntries(rows.filter(row=>row.kind==='prompt-source'&&typeof row.source==='string'&&typeof row.enabled==='boolean').map(row=>[row.source!,row.enabled?'来源已启用（不自动抓取）':'来源已停用']));})).then(state=>{if(active)setSourceState(state);}).catch(()=>{if(active)setError('来源状态读取失败，请重试。');});return()=>{active=false;};},[sourcesOpen]);
 async function reload(){const rows=await listPrompts();setEntries(rows);setLoading(false);return rows;}
 useEffect(()=>{void reload().catch(()=>{setLoading(false);setError('提示词库读取失败，请重试。');});},[]);
 useEffect(()=>{const timer=setTimeout(()=>setDebounced(query),300);return()=>clearTimeout(timer);},[query]);
 useEffect(()=>{const id=new URLSearchParams(route.split('?')[1]??'').get('entry');if(id){const entry=entries.find(e=>e.id===id);if(entry)setDetail(entry);}},[route,entries]);
 function update(entry:PromptLibraryEntry){setEntries(rows=>[...rows.filter(row=>row.id!==entry.id),entry]);}
 async function perform(action:()=>Promise<void>){setError('');try{await action();}catch(e){setError(e instanceof Error&&/conflict|writer|lease/.test(e.message)?'版本或写权已变化，本次未覆盖草稿。':'操作未完成，请检查格式、标签限制和本地空间。');}}
 async function openDeletion(entry:PromptLibraryEntry){await perform(async()=>{const refs=await withDatabase(undefined,db=>transact(db,['graphs','projects'],'readonly',async tx=>{const graphs=(await requestResult<unknown[]>(tx.objectStore('graphs').getAll())).map(g=>graphSchema.parse(g)),projects=(await requestResult<unknown[]>(tx.objectStore('projects').getAll())).map(p=>projectSchema.parse(p));return graphs.flatMap(graph=>graph.nodes.filter(node=>node.type==='text'&&node.data.promptLibrarySource?.entryId===entry.id).map(node=>(projects.find(p=>p.id===graph.projectId)?.title??graph.projectId)+' / '+node.title));}));setDeletionRefs(refs);setDeletion(entry);});}
 async function openTarget(text:string,mode:'insert'|'apply'){await perform(async()=>{const data=await withDatabase(undefined,db=>transact(db,['projects','graphs'],'readonly',async tx=>({projects:(await requestResult<unknown[]>(tx.objectStore('projects').getAll())).map(p=>projectSchema.parse(p)).filter(p=>p.trashedAt===null),graphs:(await requestResult<unknown[]>(tx.objectStore('graphs').getAll())).map(g=>graphSchema.parse(g))})));setTargetData(data);setTarget({text,mode});});}
 async function apply(projectId:string,nodeId?:string,baseRevision?:number){if(!template||!target)return;await perform(async()=>{await usePrompt(template,target.text,projectId,nodeId,baseRevision);setTarget(undefined);setDiff(undefined);setTemplate(undefined);setMessage('提示词已写入文本节点；没有创建生成任务。');});}
 const filtered=searchPrompts(entries,debounced,{tag,scope}),sources=[...new Set(entries.map(entry=>entry.source||'用户导入，来源未核验'))];
 return <section><div className="card prompt-filters"><div className="actions"><Button data-interaction-id="L-01" onClick={()=>setEditor(newPrompt())}>新建提示词</Button><label>导入提示词JSON<input data-interaction-id="L-10" type="file" accept=".json,application/json" onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)void perform(async()=>setImportPreview(previewPromptImport(await file.text())));}}/></label><Button data-interaction-id="L-11" disabled={!selected.length} disabledReason={!selected.length?'先选择提示词。':undefined} onClick={()=>{setError('');try{const text=exportPrompts(entries.filter(entry=>selected.includes(entry.id)));triggerLocalDownload(new Blob([text],{type:'application/json'}),'AIWORK-prompts.json');setMessage('已触发浏览器下载：AIWORK-prompts.json');}catch{setError('提示词导出未完成；原条目保留，请检查浏览器下载权限后重试。');}}}>导出所选提示词</Button><Button data-interaction-id="L-12" onClick={()=>setSourcesOpen(true)}>来源管理</Button></div><div className="form-row"><label>搜索提示词<input data-interaction-id="L-05" type="search" value={query} onChange={event=>setQuery(event.target.value)}/></label><label>提示词标签筛选<select data-interaction-id="ui:PromptsPage:select:628e02c00687" value={tag} onChange={event=>setTag(event.target.value)}><option value="">全部标签</option>{[...new Set(entries.flatMap(entry=>entry.tags))].map(name=><option key={name}>{name}</option>)}</select></label><label>提示词范围<select data-interaction-id="ui:PromptsPage:select:4f38baf528f3" value={scope} onChange={event=>setScope(event.target.value as typeof scope)}><option value="active">全部条目</option><option value="starred">收藏</option><option value="trash">已删除</option></select></label><Button data-interaction-id="ui:PromptsPage:Button:8139f80960ce" onClick={()=>{setQuery('');setDebounced('');setTag('');setScope('active');}}>清除筛选</Button></div></div>
 {message?<p role="status" className="banner">{message}</p>:null}{error&&!target&&!diff&&!importPreview&&!sourcesOpen?<p role="alert">{error}</p>:null}{loading?<p role="status">正在读取本地提示词…</p>:<div className={"prompt-library-layout"+(detail?" with-detail":"")}><aside className="prompt-categories card" aria-label="提示词分类"><h2>分类</h2><Button data-interaction-id="ui:PromptsPage:Button:7e99d5010b57" onClick={()=>{setTag("");setScope("active");}}>全部</Button><Button data-interaction-id="ui:PromptsPage:Button:7408729ffa21" onClick={()=>setScope("starred")}>收藏</Button>{[...new Set(entries.flatMap(entry=>entry.tags))].map(name=><Button data-interaction-id="ui:PromptsPage:Button:64dce2caf743" key={name} aria-pressed={tag===name} onClick={()=>setTag(name)}>{name}</Button>)}</aside><div className="prompt-grid">{!filtered.length?<p className="card">没有匹配提示词，可新建或清除筛选。</p>:null}{filtered.map(entry=><article className="card prompt-entry" data-testid="prompt-entry" key={entry.id}><label><input data-interaction-id="ui:PromptsPage:input:84053c475441" type="checkbox" aria-label={'选择 '+entry.title} checked={selected.includes(entry.id)} onChange={event=>setSelected(ids=>event.target.checked?[...ids,entry.id]:ids.filter(id=>id!==entry.id))}/><strong>{entry.title}</strong></label><p className="prompt-body-preview">{entry.body}</p><small>{entry.tags.join(' · ')} · 修订 {entry.revision}</small><div className="actions"><Button data-interaction-id="L-06" aria-label={'详情 '+entry.title} onClick={()=>setDetail(entry)}>详情</Button>{entry.trashed?<Button data-interaction-id="ui:PromptsPage:Button:4059dc419856" aria-label={'恢复 '+entry.title} onClick={()=>perform(async()=>{const saved=await savePrompt({...entry,trashed:false},entry.revision);update(saved);})}>恢复</Button>:<><Button data-interaction-id="L-07" aria-label={'复制 '+entry.title} onClick={()=>setTemplate(entry)}>复制/使用</Button><Button data-interaction-id="L-02" aria-label={'编辑 '+entry.title} onClick={()=>setEditor(entry)}>编辑</Button><Button data-interaction-id="L-04" aria-label={(entry.starred?'取消收藏 ':'收藏 ')+entry.title} onClick={()=>perform(async()=>{update(await savePrompt({...entry,starred:!entry.starred},entry.revision));})}>{entry.starred?'已收藏':'收藏'}</Button><Button data-interaction-id="L-03" aria-label={'删除 '+entry.title} onClick={()=>openDeletion(entry)}>删除</Button></>}</div></article>)}</div>{detail?<aside className="prompt-inspector card" aria-label="提示词详情"><div className="actions"><h2>提示词详情</h2><Button data-interaction-id="ui:PromptsPage:Button:6bbee0761cf6" onClick={()=>setDetail(undefined)}>关闭提示词详情</Button></div><h3>{detail.title}</h3><p>修订 {detail.revision}</p><pre>{detail.body}</pre><p>变量：{detail.variables.join("、")||"无"}</p><p>来源：{detail.source||"用户导入，来源未核验"}</p><p>许可：{detail.license||"未知，待核验"}</p><Button data-interaction-id="ui:PromptsPage:Button:88047c0fadef" onClick={()=>setEditor(detail)}>编辑此提示词</Button></aside>:null}</div>}
 {editor?<PromptEditor entry={editor} onClose={()=>setEditor(undefined)} onSaved={entry=>{update(entry);setEditor(undefined);setMessage('提示词已保存。');}}/>:null}
 {template?<TemplateVariables key={template.id} entry={template} onClose={()=>setTemplate(undefined)} onTarget={(text,mode)=>void openTarget(text,mode)}/>:null}

 <Dialog open={!!deletion} title="删除提示词" onClose={()=>setDeletion(undefined)} footer={<><Button data-interaction-id="ui:PromptsPage:Button:8c3c414048ab" onClick={()=>setDeletion(undefined)}>取消</Button><Button data-interaction-id="ui:PromptsPage:Button:5d82239e6ace" onClick={()=>perform(async()=>{if(!deletion)return;update(await savePrompt({...deletion,trashed:true},deletion.revision));setDeletion(undefined);setMessage('提示词已软删除；已插入的文本保持原样。');})}>确认软删除</Button></>}><p>只软删除库条目，可以恢复。已插入节点保存各自副本与原修订，不会跟随删除。</p><p>{deletion?.title}</p><p>已插入副本：{deletionRefs.length}（本次检查）</p><ul>{deletionRefs.map((ref,index)=><li key={index}>{ref}</li>)}</ul>{error?<p role="alert">{error}</p>:null}</Dialog>
 <Dialog open={!!importPreview} title="确认导入提示词" onClose={()=>setImportPreview(undefined)} footer={<><Button data-interaction-id="ui:PromptsPage:Button:d9e17899de2e" onClick={()=>setImportPreview(undefined)}>取消</Button><Button data-interaction-id="ui:PromptsPage:Button:ec738e160e7b" onClick={()=>perform(async()=>{if(!importPreview)return;const rows=await importPromptEntries(importPreview);setEntries(current=>[...current,...rows]);setImportPreview(undefined);setMessage('已另存 '+rows.length+' 条提示词；同名条目未覆盖。');})}>另存导入条目</Button></>}>{error?<p role="alert">{error}</p>:null}<p>全部条目另存新 ID，来源与许可原样保留，不执行 HTML 或脚本。</p>{importPreview?.map(entry=><div className="card" key={entry.id}><strong>{entry.title}</strong><p>{entry.source||'来源未核验'}</p><p>{entry.license||'许可未知'}</p><pre>{entry.body}</pre></div>)}</Dialog>
 <Dialog open={sourcesOpen} title="提示词来源" onClose={()=>setSourcesOpen(false)}><p>没有自动加载远端来源；基础版不定时联网抓取。用户已另存的条目不会因停用或清理源缓存被删除。</p>{error?<p role="alert">{error}</p>:null}{sources.map(source=><div className="card" key={source}><p>{source}</p><small>{sourceState[source]??'仅本地条目，无自动抓取'}</small><div className="actions"><Button data-interaction-id="ui:PromptsPage:Button:74b7432b1e1b" onClick={()=>perform(async()=>{await setPromptSource(source,false);setSourceState(state=>({...state,[source]:'来源已停用'}));})}>停用来源</Button><Button data-interaction-id="ui:PromptsPage:Button:29a98c978f59" onClick={()=>perform(async()=>{await removePromptSourceCache(source);setSourceState(state=>({...state,[source]:'缓存已移除，另存条目保留'}));})}>移除来源缓存</Button></div></div>)}</Dialog>
 <Dialog open={!!target&&!diff} title="选择提示词目标" onClose={()=>setTarget(undefined)}><p>只写文本节点。只读目标拒绝写入；原任务与收费授权不变。</p>{!targetData.projects.length?<LocalLink data-interaction-id="ui:PromptsPage:LocalLink:4c28486c9e87" href="/projects?create=1">先创建目标项目</LocalLink>:null}{error?<p role="alert">{error}</p>:null}{targetData.projects.map(project=>target?.mode==='insert'?<Button data-interaction-id="ui:PromptsPage:Button:fd255a81b9ea" key={project.id} onClick={()=>apply(project.id)}>{'插入 '+project.title}</Button>:targetData.graphs.filter(g=>g.projectId===project.id).flatMap(graph=>graph.nodes.filter(n=>n.type==='text'&&!n.locked).map(node=><Button data-interaction-id="ui:PromptsPage:Button:cfb07035d689" key={node.id} onClick={()=>setDiff({projectId:project.id,nodeId:node.id,baseRevision:graph.revision,old:node.data.kind==='text'?node.data.text:''})}>{'应用 '+project.title+' / '+node.title}</Button>)))}</Dialog>
 <Dialog open={!!diff} title="确认替换文本" onClose={()=>setDiff(undefined)} footer={<><Button data-interaction-id="ui:PromptsPage:Button:caeb1f63a694" onClick={()=>setDiff(undefined)}>取消</Button><Button data-interaction-id="L-09" onClick={()=>{if(diff)return apply(diff.projectId,diff.nodeId,diff.baseRevision);}}>确认替换文本</Button></>}>{error?<p role="alert">{error}</p>:null}<h3>原文</h3><pre>{diff?.old}</pre><h3>新文</h3><pre>{target?.text}</pre><p>项目版本变更将拒绝覆盖；下游仅标待更新，不自动执行。</p></Dialog>
 </section>;
}
