import {useState} from 'react';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
import {LocalLink} from '../../app/routes';
import notices from '../../../third-party/THIRD_PARTY_NOTICES.txt?raw';
import canvasLicense from '../../../third-party/licenses/infinite-canvas.LICENSE?raw';
import promptLicense from '../../../third-party/licenses/prompt-for-seedance-gptimage2.5.LICENSE?raw';
import zipLicense from '../../../third-party/licenses/fflate-0.8.2.LICENSE?raw';
export function HelpPage(){const [licenses,setLicenses]=useState(false);return <section className="card"><h2>帮助与版本</h2><p data-interaction-id="Q-01">开发版本 0.0.1 · 项目Schema 1 · 适配器能力按连接契约</p><p>未发布开发版；用户统一验收和独立审查待进行。这里没有自动反馈、遥测或默认外部渠道。</p><div className="actions"><LocalLink data-interaction-id="Q-04" href="/welcome">查看入门引导</LocalLink><LocalLink href="/recovery">恢复与冲突中心</LocalLink><LocalLink data-interaction-id="Q-03" href="/activity">导出本地脱敏报告</LocalLink><Button onClick={()=>setLicenses(true)}>第三方许可与来源</Button></div><details open><summary>保存与备份</summary><p>创作内容保存在当前浏览器，Core不保存整张画布。显示“已保存”表示本地事务提交成功；清除站点数据前请手动导出项目包。浏览器持久存储不能替代备份。</p></details><details><summary>授权与费用</summary><p>普通Key只在当前标签页内存。刷新后需要重新输入原Key恢复原绑定；切换不会改写旧任务。创建流程、应用提示词或接受提案不等于收费授权，文字优化和视频生成分别确认。</p></details><details><summary>未知提交与重试</summary><p>提交结果暂未确认时保留原身份和冻结请求，不自动换键或新素材重发。只有已核验支持的原身份恢复动作可用。下载失败只重试获取文件。</p><p>executionState、queryState、deliveryState、billingState独立保存。停止本地查询不等于取消生成或退款；收到视频也不代表账务已结算。</p></details><details><summary>受控能力与本地数据</summary><p>未核验的图片/音频生成、远端取消和WebDAV没有执行入口。未知节点只读隔离，不能安装远程脚本。素材仅在明确选择后导入；参考描述不表示文字模型已经看过视频。</p></details><Dialog title="第三方许可与来源" open={licenses} onClose={()=>setLicenses(false)} width={960} footer={<Button onClick={()=>setLicenses(false)}>关闭</Button>}><p>算法与规则来源依法保留 MIT 等许可和原权利声明，产品UI独立重组。前端标识授权仍是发布门槛，未声称完全自研或已获许可。</p><details><summary>画布逻辑许可</summary><pre>{canvasLicense}</pre></details><details><summary>视频提示词规则许可</summary><pre>{promptLicense}</pre></details><details><summary>fflate ZIP许可</summary><pre>{zipLicense}</pre></details><details><summary>完整来源与声明台账</summary><pre>{notices}</pre></details></Dialog></section>;}
