import {useEffect,useId,useRef,useState} from 'react';
import {useRoute,LocalLink} from '../../app/routes';
import {Button} from '../../ui/Button';
import {useResultResources,reviewAsset,ReviewMedia,ResultSnapshot,ResultActions} from './review-components';
export function ComparePage({projectId}:{projectId:string}){
 const route=useRoute(),params=new URLSearchParams(route.split('?')[1]??''),ids=(params.get('runs')??'').split(','),{resources,error,reload}=useResultResources(projectId),group=useId(),[swapped,setSwapped]=useState(false),[ready,setReady]=useState({left:false,right:false}),[playing,setPlaying]=useState(false),[message,setMessage]=useState(''),media=useRef<{left:HTMLMediaElement|null;right:HTMLMediaElement|null}>({left:null,right:null});
 function pause(){media.current.left?.pause();media.current.right?.pause();setPlaying(false);}
 useEffect(()=>()=>{media.current.left?.pause();media.current.right?.pause();},[]);
 async function synchronize(){const {left,right}=media.current;if(!left||!right||left.readyState<2||right.readyState<2)return;if(playing){pause();return;}const time=Math.min(left.currentTime,right.currentTime);left.currentTime=time;right.currentTime=time;try{await Promise.all([left.play(),right.play()]);setPlaying(true);setMessage('正在按共同时间近似播放。');}catch{pause();setMessage('一侧播放失败，双方已暂停；原文件保留。');}}
 if(ids.length!==2||new Set(ids).size!==2||ids.some(id=>!id))return <p role="alert">请选择且仅选择两个不同的已完成视频版本。</p>;if(error)return <p role="alert">{error}</p>;if(!resources)return <p role="status">正在读取两个原版本…</p>;
 const ordered=swapped?[ids[1],ids[0]]:ids,runs=ordered.map(id=>resources.runs.find(r=>r.id===id&&r.executionState==='succeeded'));if(runs.some(r=>!r))return <p role="alert">所选版本不存在或尚未完成，原任务历史保留。</p>;
 return <section aria-label="两版本比较"><LocalLink href={'/projects/'+encodeURIComponent(projectId)+'/results?runId='+encodeURIComponent(ids[0])}>返回审片</LocalLink><p>按共同时间近似同步，不是帧级同步。</p><div className="actions"><Button data-interaction-id="R-09" disabled={!ready.left||!ready.right} onClick={synchronize}>{playing?'同步暂停':'同步播放'}</Button><Button data-interaction-id="R-10" onClick={()=>{pause();setReady({left:false,right:false});setSwapped(!swapped);}}>交换A/B</Button></div><p role="status">{message}</p>
 <div className="review-comparison">{runs.map((run,index)=>{const slot=index===0?'left':'right',asset=reviewAsset(resources,run!);return <article className="card" data-testid={'comparison-'+slot} data-run-id={run!.id} key={slot}><h3>{index===0?'A':'B'} · {run!.id}</h3><ReviewMedia key={'media:'+run!.id} label={'比较版本'+(index===0?'A':'B')} asset={asset} group={group} onMediaReady={element=>{media.current[slot]=element;}} onCanPlay={()=>setReady(v=>({...v,[slot]:true}))} onPause={pause} onEnded={()=>{pause();setMessage('短片已结束，两侧已暂停；比较不是帧级同步。');}}/><ResultSnapshot run={run!} asset={asset}/><ResultActions key={'actions:'+run!.id} run={run!} asset={asset} resources={resources} onChange={reload}/></article>;})}</div></section>;
}
