import {useState} from 'react';
import {useRoute,navigate,LocalLink} from '../../app/routes';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
import {useResultResources,reviewAsset,ReviewMedia,ResultSnapshot,ResultActions} from './review-components';
export function ResultPage({projectId}:{projectId:string}){
 const route=useRoute(),params=new URLSearchParams(route.split('?')[1]??''),{resources,error,reload}=useResultResources(projectId),[comparison,setComparison]=useState<string[]>([]),[message,setMessage]=useState(''),[compareOpen,setCompareOpen]=useState(false);
 if(error)return <p role="alert">{error}</p>;if(!resources)return <p role="status">正在读取原结果记录…</p>;const completed=resources.runs.filter(r=>r.executionState==='succeeded'),id=params.get('runId')??params.get('run')??completed[0]?.id,run=completed.find(r=>r.id===id);
 if(!run)return <section className="card"><p>暂无所选已完成结果；原任务历史保留。</p><LocalLink data-interaction-id="ui:ResultPage:LocalLink:222c33482532" href="/tasks">查看本地任务中心</LocalLink></section>;const asset=reviewAsset(resources,run);
 return <section aria-label="视频审片"><div className="actions"><LocalLink data-interaction-id="ui:ResultPage:LocalLink:5c80fbc5a1f4" href={'/projects/'+encodeURIComponent(projectId)+'/canvas'}>返回画布</LocalLink><LocalLink data-interaction-id="ui:ResultPage:LocalLink:222c33482532" href="/tasks">查看本地任务中心</LocalLink><label>历史版本<select data-interaction-id="R-07" aria-label="历史版本" value={run.id} onChange={e=>navigate('/projects/'+encodeURIComponent(projectId)+'/results?runId='+encodeURIComponent(e.target.value))}>{completed.map(r=><option key={r.id} value={r.id}>{r.id}</option>)}</select></label></div><p>历史版本只读，查看不会改默认下游输入。</p>
 <ReviewMedia asset={asset}/><ResultSnapshot run={run} asset={asset}/><ResultActions key={run.id} run={run} asset={asset} resources={resources} onChange={reload}/>
 <h3>比较两个版本</h3>{completed.map(r=><label className="review-choice" key={r.id}><input data-interaction-id="R-08" type="checkbox" checked={comparison.includes(r.id)} onChange={e=>{if(e.target.checked){if(comparison.length>=2){setMessage('只能选择两个不同版本进行比较。');return;}setComparison(v=>[...v,r.id]);}else setComparison(v=>v.filter(id=>id!==r.id));}}/>{r.id}</label>)}<Button data-interaction-id="R-08" disabled={comparison.length!==2} onClick={()=>setCompareOpen(true)}>比较所选版本</Button><p role="status">{message}</p>
 <Dialog open={compareOpen} title="对照版本选择" onClose={()=>setCompareOpen(false)} footer={<><Button data-interaction-id="ui:ResultPage:Button:1613ba3da49c" onClick={()=>setCompareOpen(false)}>取消</Button><Button data-interaction-id="R-08" disabled={comparison.length!==2||comparison.some(id=>!completed.some(r=>r.id===id))} onClick={()=>{setCompareOpen(false);navigate('/projects/'+encodeURIComponent(projectId)+'/compare?runs='+encodeURIComponent(comparison.join(',')));}}>开始本地对照</Button></>}><p>对照所选两个固定历史版本，只读取本地媒体，不重新生成，不改变后续输入。</p>{comparison.map(id=>{const chosen=completed.find(r=>r.id===id);return chosen?<section key={id}><h3>{id}</h3><ResultSnapshot run={chosen} asset={reviewAsset(resources,chosen)}/></section>:<p role="alert" key={id}>版本已不可用，请返回核对或恢复原内容；不会自动重新生成。</p>;})}</Dialog></section>;
}
