import {useEffect,useRef,useState,type ReactNode} from 'react';
import type {Run} from '../../domain/run';
import type {Asset} from '../../domain/asset';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
import {redact} from '../../security/redaction';
import {isEditableTarget} from '../../ui/copy.zh-CN';
import {AssetPreview} from '../assets/AssetPreview';
import {activateLocalMedia} from '../assets/playback-coordinator';
import {RunMediaActions} from './RunMediaActions';
import {affectedResultNodes,readResultResources,selectResult,undoResultSelection,removeResultPlacement,type ResultResources} from './result-selection';
export function useResultResources(projectId:string){const [resources,setResources]=useState<ResultResources>(),[error,setError]=useState(''),[version,setVersion]=useState(0);useEffect(()=>{let alive=true;void readResultResources(projectId).then(data=>{if(alive){setResources(data);setError('');}}).catch(()=>{if(alive)setError('项目或结果记录不可用，请查看本地任务历史。');});return()=>{alive=false;};},[projectId,version]);return {resources,error,reload:()=>setVersion(v=>v+1)};}
export function reviewAsset(resources:ResultResources,run:Run){return resources.assets.find(a=>a.id===run.resultAssetId&&a.sourceRunId===run.id&&a.mediaType==='video'&&a.trashedAt==null);}
export function ReviewMedia({asset,label='视频审片预览',group,onMediaReady,onEnded,onPause,onCanPlay,children}:{asset?:Asset;label?:string;group?:string;onMediaReady?:(e:HTMLMediaElement|null)=>void;onEnded?:()=>void;onPause?:()=>void;onCanPlay?:()=>void;children?:ReactNode}){
 const container=useRef<HTMLDivElement>(null),element=useRef<HTMLMediaElement|null>(null),[message,setMessage]=useState('');
 useEffect(()=>{const exiting=()=>{if(!document.fullscreenElement)element.current?.pause();};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'&&document.fullscreenElement===element.current){event.preventDefault();void document.exitFullscreen();}};document.addEventListener('fullscreenchange',exiting);document.addEventListener('keydown',escape,true);return()=>{document.removeEventListener('fullscreenchange',exiting);document.removeEventListener('keydown',escape,true);};},[]);
 async function fullscreen(){const video=element.current;if(!video)return;try{activateLocalMedia(video);await video.requestFullscreen();}catch{setMessage('浏览器未允许全屏，可以继续普通预览。');}}
 return <div className="review-media" role="region" aria-label={label} tabIndex={0} ref={container} onKeyDown={event=>{if(isEditableTarget(event.target)||event.nativeEvent.isComposing||document.querySelector('dialog[open]'))return;if(event.key==='Escape'&&document.fullscreenElement){event.preventDefault();void document.exitFullscreen();}else if(event.key===' '){event.preventDefault();event.stopPropagation();const video=element.current;if(video){if(video.paused){activateLocalMedia(video,group);void video.play().catch(()=>setMessage('播放失败，原文件与任务记录保留。'));}else video.pause();}}}}>
 {asset?<AssetPreview key={asset.id} assetId={asset.id} playbackGroup={group} onMediaReady={e=>{element.current=e;onMediaReady?.(e);}} onEnded={onEnded} onPlaybackPaused={onPause} onCanPlay={onCanPlay}/>:<p>当前没有可用的本地结果文件；原任务和快照保留，请用原授权获取内容。</p>}
 <Button data-interaction-id="R-02" disabled={!asset} onClick={fullscreen}>全屏预览</Button><small>空格播放或暂停，Esc退出全屏。</small>{message?<p role="status">{message}</p>:null}{children}</div>;
}
export function ResultSnapshot({run,asset}:{run:Run;asset?:Asset}){const safe=redact({message:JSON.stringify(run.inputSnapshot)}) as {message:string};return <><p>版本 {run.id} · 原任务 {run.taskId??'未提供'} · 原请求 {run.coreRequestId??'未提供'}</p><p>原服务 {run.connectionId} · 原授权绑定 {run.authBindingId}</p><p>素材记录：{asset?[asset.title,asset.width&&asset.height?`${asset.width}×${asset.height}`:'尺寸未知',asset.durationSeconds===undefined?'实际时长未知':asset.durationSeconds+'秒',asset.bytes+'字节'].join(' · '):'文件缺失或等待获取'}</p><p>原请求规格：{run.requestedSpec?JSON.stringify(run.requestedSpec):'未单独提供'}；执行规格：{run.executionSpec?JSON.stringify(run.executionSpec):'Core未提供，不以请求规格冒充实际规格'}</p><pre className="task-snapshot">{safe.message}</pre></>;}
export function ResultActions({run,asset,resources,onChange}:{run:Run;asset?:Asset;resources:ResultResources;onChange:()=>void}){
 const [selectOpen,setSelectOpen]=useState(false),[nodeId,setNodeId]=useState(''),[removeId,setRemoveId]=useState(''),[message,setMessage]=useState(''),[undoRevision,setUndoRevision]=useState<number>();
 const nodes=resources.graph.nodes.filter(n=>n.type==='result'&&!n.locked),affected=affectedResultNodes(resources.graph,nodeId);
 async function copy(value:string){try{const safe=redact({message:value}) as {message:string};await navigator.clipboard.writeText(safe.message);setMessage('已复制脱敏内容。');}catch{setMessage('复制失败，可手动选择原文。');}}
 async function select(){if(!asset||!nodeId)return;try{const result=await selectResult({projectId:resources.graph.projectId,baseRevision:resources.graph.revision,nodeId,runId:run.id,assetId:asset.id,confirmed:true,commandId:crypto.randomUUID()});if(result.status==='applied'||result.status==='replayed'){setUndoRevision(result.revision);setSelectOpen(false);setMessage('草稿结果引用已更新，下游待更新；未自动重跑。');onChange();}else setMessage('画布已变化或当前只读，请重新检查影响；未替换。');}catch{setMessage('结果来源、缓存或写权检查未通过，原结果保持不变。');}}
 return <><div className="actions"><Button data-interaction-id="R-05" disabled={!run.taskId} onClick={()=>copy(run.connectionId+' / '+run.taskId)}>复制任务编号</Button><Button data-interaction-id="R-06" onClick={()=>copy(JSON.stringify(run.inputSnapshot))}>复制参数快照</Button><Button data-interaction-id="R-11" disabled={!asset||resources.archived||!nodes.length} disabledReason="需要可读结果、可编辑项目和已有结果引用节点" onClick={()=>{setNodeId(nodes[0]?.id??'');setSelectOpen(true);}}>选为后续输入</Button>{undoRevision!==undefined?<Button onClick={async()=>{const receipt=await undoResultSelection(resources.graph.projectId,undoRevision);if(receipt.status==='applied'){setUndoRevision(undefined);setMessage('本次选用已撤销，历史结果保持不变。');onChange();}else setMessage('画布已变化，不能撤销另一条修改，请在画布核对历史。');}}>撤销本次选用</Button>:null}</div>
 <RunMediaActions key={run.id} run={run} showPreview={false} onCached={onChange}/><p role="status">{message}</p>
 {resources.graph.nodes.filter(n=>n.type==='result'&&n.data.runId===run.id).map(n=><Button key={n.id} data-interaction-id="R-13" disabled={n.locked||resources.archived} onClick={()=>setRemoveId(n.id)}>移除结果摆放 {n.title}</Button>)}
 <Dialog open={selectOpen} title="确认选用结果" onClose={()=>setSelectOpen(false)} footer={<><Button onClick={()=>setSelectOpen(false)}>取消</Button><Button disabled={!nodeId||!asset} onClick={select}>确认选用</Button></>}><p>只修改所选结果引用和下游草稿，原任务、素材与执行快照不可覆写；不会自动重跑。</p><label>结果引用节点<select aria-label="结果引用节点" value={nodeId} onChange={e=>setNodeId(e.target.value)}>{nodes.map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><p>受影响节点：</p><ul>{affected.map(n=><li key={n.id}>{n.title}</li>)}</ul>{!affected.length?<p>此引用当前没有下游。</p>:null}</Dialog>
 <Dialog open={!!removeId} title="移除结果摆放" onClose={()=>setRemoveId('')} footer={<><Button onClick={()=>setRemoveId('')}>取消</Button><Button onClick={async()=>{const receipt=await removeResultPlacement(resources.graph.projectId,removeId,resources.graph.revision);if(receipt.status==='applied'){setRemoveId('');onChange();setMessage('仅移除了画布摆放；历史任务和原文件保留。');}else setMessage('移除未保存，请重新检查画布。');}}>确认移除</Button></>}><p>只移除画布卡片及相关连线，不删除原任务或素材；可以在画布撤销。</p></Dialog>
 </>;
}
