import {withDatabase,transact,requestResult,type StudioDb} from '../infrastructure/storage/database';
import {redact} from './redaction';
import {sanitizeKnownSecrets} from './credential-session';
import {recoveryCode} from '../features/recovery/recovery-model';
export type DiagnosticFilter={projectId?:string;kind?:string;timeRange?:{from?:number;to?:number}};
export type DiagnosticEntry={id:string;kind:string;projectId?:string;nodeId?:string;runId?:string;draftId?:string;taskId?:string;coreRequestId?:string;connectionId?:string;authBindingId?:string;originSnapshot?:string;errorCode?:string;at:number;executionState?:string;queryState?:string;deliveryState?:string;billingState?:string;revision?:number};
const fields=['id','projectId','nodeId','runId','draftId','taskId','coreRequestId','connectionId','authBindingId','originSnapshot','errorCode','executionState','queryState','deliveryState','billingState'] as const;
export const visibleDiagnosticKinds=new Set(['project_saved','run_saved','command_applied','command_rejected','project_imported','rebuildable_cache_cleaned','video_poll','dispatch_intent_committed','original_replay_intent','storage_failed','unknown_exception']);
export function diagnosticEntry(raw:unknown,kind?:'video-run'|'prompt-run'):DiagnosticEntry|undefined{const clean=redact(raw) as Record<string,unknown>|undefined;if(!clean||typeof clean!=='object'||typeof clean.id!=='string')return undefined;const out:Record<string,unknown>={};for(const key of fields)if(typeof clean[key]==='string')out[key]=sanitizeKnownSecrets(clean[key]).slice(0,512);out.kind=kind??(typeof clean.kind==='string'&&visibleDiagnosticKinds.has(clean.kind)?clean.kind:'unknown-event');out.at=typeof clean.at==='number'?clean.at:typeof clean.updatedAt==='number'?clean.updatedAt:typeof clean.createdAt==='number'?clean.createdAt:typeof clean.startedAt==='number'?clean.startedAt:0;if(typeof clean.revision==='number')out.revision=clean.revision;if(out.errorCode)out.errorCode=recoveryCode(out.errorCode);return out as DiagnosticEntry;}
export async function listDiagnosticEntries(filter:DiagnosticFilter={},db?:StudioDb):Promise<DiagnosticEntry[]>{return withDatabase(db,c=>transact(c,['diagnostics','runs','promptRuns'],'readonly',async tx=>{const rows:DiagnosticEntry[]=[];for(const [table,kind]of [['diagnostics',undefined],['runs','video-run'],['promptRuns','prompt-run']] as const){const values=await requestResult<unknown[]>(tx.objectStore(table).getAll());for(const value of values){const entry=diagnosticEntry(value,kind);if(entry&&(table!=='diagnostics'||entry.kind!=='unknown-event'||entry.errorCode))rows.push(entry);}}return rows.filter(e=>(!filter.projectId||e.projectId===filter.projectId)&&(!filter.kind||e.kind===filter.kind)&&(filter.timeRange?.from===undefined||e.at>=filter.timeRange.from)&&(filter.timeRange?.to===undefined||e.at<=filter.timeRange.to)).sort((a,b)=>b.at-a.at).slice(0,5000);}));}
export async function exportDiagnostics(filter:DiagnosticFilter={},db?:StudioDb):Promise<Blob>{const rows=await listDiagnosticEntries(filter,db);return new Blob([JSON.stringify({format:'aiwork-studio-diagnostics',schemaVersion:1,source:'本地浏览器记录，非Core审计',createdAt:new Date().toISOString(),timeBasis:'存储UTC；界面采用浏览器本地时区',fields:['记录ID','原服务和授权绑定ID','错误分类','四维状态','修订及UTC时间'],records:rows},null,2)],{type:'application/json'});}
// Preserve functional metadata and all Run/receipt journals. Only explicit display events are removed.
export async function clearDiagnosticDisplay(db?:StudioDb){return withDatabase(db,c=>transact(c,['diagnostics','runs','promptRuns'],'readwrite',async tx=>{const runs=await requestResult<{id:string;executionState:string;billingState:string}[]>(tx.objectStore('runs').getAll()),prompts=await requestResult<typeof runs>(tx.objectStore('promptRuns').getAll()),activeIds=new Set([...runs,...prompts].filter(r=>!['succeeded','failed_confirmed','response_received','failed_before_dispatch'].includes(r.executionState)||r.billingState==='pending_reconciliation').map(r=>r.id)),rows=await requestResult<{id:string;kind?:string;runId?:string;promptRunId?:string}[]>(tx.objectStore('diagnostics').getAll());let count=0;for(const row of rows)if(row.kind&&visibleDiagnosticKinds.has(row.kind)&&!activeIds.has(row.runId??'')&&!activeIds.has(row.promptRunId??'')){tx.objectStore('diagnostics').delete(row.id);count++;}return count;}));}
