import {useEffect,useRef,useState} from 'react';
import {localText,byteLength} from '../../../domain/common';
import type {CanvasNode,ReferenceToken} from '../../../domain/graph';
import {Button} from '../../../ui/Button';
export type TextCanvasNode=Extract<CanvasNode,{type:'text'}>;
export function TextNode({node,readonly,onDraft,onChange,references,fontSize,onFontSize}:{node:TextCanvasNode;readonly:boolean;onDraft:()=>void;onChange:(data:TextCanvasNode['data'])=>void;references:ReferenceToken[];fontSize:number;onFontSize:(size:number)=>void}){
 const [text,setText]=useState(node.data.text),[error,setError]=useState(''),[referenceOpen,setReferenceOpen]=useState(false),[copyMessage,setCopyMessage]=useState('');const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),composing=useRef(false),tokens=useRef(node.data.referenceTokens);
 useEffect(()=>{setText(node.data.text);tokens.current=node.data.referenceTokens;},[node.data]);useEffect(()=>()=>clearTimeout(timer.current),[]);
 function save(value:string){clearTimeout(timer.current);if(!localText.safeParse(value).success){setError('本地文本超过64KiB，已保存版本保持原样。');return;}setError('');onDraft();if(!composing.current)timer.current=setTimeout(()=>onChange({...node.data,text:value,referenceTokens:tokens.current}),300);}
 return <div className="text-node-editor"><textarea aria-label="节点文本" value={text} readOnly={readonly} style={{fontSize}} onChange={e=>{setText(e.target.value);save(e.target.value);}} onCompositionStart={()=>{composing.current=true;clearTimeout(timer.current);}} onCompositionEnd={e=>{composing.current=false;save(e.currentTarget.value);}}/><small>{byteLength(text)} / 65536 字节</small>{error?<p role="alert">{error}</p>:null}<div className="node-actions"><label>文本字号<select value={fontSize} onChange={e=>onFontSize(Number(e.target.value))}>{[12,14,16,20].map(size=><option key={size} value={size}>{size}px</option>)}</select></label><Button disabled={readonly} onClick={()=>setReferenceOpen(!referenceOpen)}>插入参考 @</Button><Button disabled={!text} onClick={async()=>{try{await navigator.clipboard.writeText(text);setCopyMessage('已复制');}catch{setCopyMessage('剪贴板权限被拒绝，请选中文本手动复制。');}}}>复制文本</Button></div>{referenceOpen?<div className="reference-picker">{references.length?references.map(ref=><Button key={ref.alias} onClick={()=>{tokens.current=[...tokens.current.filter(t=>t.alias!==ref.alias),ref];const value=text+' @'+ref.alias;setText(value);save(value);setReferenceOpen(false);}}>{ref.alias}</Button>):<p>请先选择或连接可读素材。</p>}</div>:null}{node.data.referenceTokens.some(ref=>!ref.available||ref.unbound)?<p role="alert">参考素材不可用，请修复后再执行。</p>:null}{copyMessage?<p role="status">{copyMessage}</p>:null}</div>;
}
