import {useEffect,useRef,useState} from 'react';
import {localText,byteLength} from '../../../domain/common';
import type {CanvasNode,ReferenceToken} from '../../../domain/graph';
import {Button} from '../../../ui/Button';
import {navigate} from '../../../app/routes';
export type TextCanvasNode=Extract<CanvasNode,{type:'text'}>;
export function TextNode({node,readonly,onDraft,onChange,references,fontSize,onFontSize,onSavePrompt,onOptimize,onCreateFlow,onAIOptimize,canAI=false}:{node:TextCanvasNode;readonly:boolean;onDraft:(data:TextCanvasNode['data'])=>void;onChange:(data:TextCanvasNode['data'])=>void;references:ReferenceToken[];fontSize:number;onFontSize:(size:number)=>void;onSavePrompt?:(text:string)=>void;onOptimize?:(text:string)=>void;onCreateFlow?:()=>void;onAIOptimize?:(text:string)=>void;canAI?:boolean}){
 const [text,setText]=useState(node.data.text),[error,setError]=useState(''),[referenceOpen,setReferenceOpen]=useState(false),[copyMessage,setCopyMessage]=useState('');const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),composing=useRef(false),tokens=useRef(node.data.referenceTokens),latestText=useRef(text),draftDirty=useRef(false);
 useEffect(()=>{if(!draftDirty.current||node.data.text===latestText.current){setText(node.data.text);latestText.current=node.data.text;tokens.current=node.data.referenceTokens;draftDirty.current=false;}},[node.data]);useEffect(()=>()=>clearTimeout(timer.current),[]);
 function save(value:string){clearTimeout(timer.current);latestText.current=value;draftDirty.current=true;onDraft({...node.data,text:value,referenceTokens:tokens.current});if(!localText.safeParse(value).success){setError('本地文本超过64KiB，已保存版本保持原样。');return;}setError('');if(!composing.current)timer.current=setTimeout(()=>onChange({...node.data,text:value,referenceTokens:tokens.current}),300);}
 return <div className="text-node-editor"><textarea data-interaction-id="T-01" aria-label="节点文本" value={text} readOnly={readonly} style={{fontSize}} onChange={e=>{setText(e.target.value);save(e.target.value);}} onCompositionStart={()=>{composing.current=true;clearTimeout(timer.current);}} onCompositionEnd={e=>{composing.current=false;save(e.currentTarget.value);}}/><small>{byteLength(text)} / 65536 字节</small>{error?<p role="alert">{error}</p>:null}<div className="node-actions"><label>文本字号<select aria-label="文本字号" data-interaction-id="T-02" value={fontSize} onChange={e=>onFontSize(Number(e.target.value))}>{[12,14,16,20].map(size=><option key={size} value={size}>{size}px</option>)}</select></label><Button data-interaction-id="T-03" disabled={readonly} onClick={()=>setReferenceOpen(!referenceOpen)}>插入参考 @</Button><Button data-interaction-id="T-05" disabled={!text.trim()||!localText.safeParse(text).success} onClick={()=>onSavePrompt?.(text)}>保存为提示词</Button><Button data-interaction-id="T-08" disabled={readonly||!text.trim()||!localText.safeParse(text).success} onClick={onCreateFlow}>从文本创建视频流程</Button><Button data-interaction-id="PG02" onClick={()=>onOptimize?.(text)}>提示词生成</Button><Button data-interaction-id="T-06" disabled={readonly||!canAI||!text.trim()||!localText.safeParse(text).success} disabledReason={readonly?"当前节点只读或已锁定":!canAI?"请在设置中连接文字 API；已保存的连接会自动恢复。":"请先输入有效文字"} onClick={()=>onAIOptimize?.(text)}>AI润色</Button>{!canAI?<Button data-interaction-id="text-node:connect-api" onClick={()=>navigate("/settings/connections#text-api")}>连接文字 API</Button>:null}<Button data-interaction-id="T-04" disabled={!text} onClick={async()=>{try{await navigator.clipboard.writeText(text);setCopyMessage('已复制');}catch{setCopyMessage('剪贴板权限被拒绝，请选中文本手动复制。');}}}>复制文本</Button></div>{referenceOpen?<div className="reference-picker">{references.length?references.map(ref=><Button data-interaction-id="ui:TextNode:Button:72c9cd7ad633" key={ref.alias} onClick={()=>{tokens.current=[...tokens.current.filter(t=>t.alias!==ref.alias),ref];const value=text+' @'+ref.alias;setText(value);save(value);setReferenceOpen(false);}}>{ref.alias}</Button>):<p>请先选择或连接可读素材。</p>}</div>:null}{node.data.referenceTokens.some(ref=>!ref.available||ref.unbound)?<p role="alert">参考素材不可用，请修复后再执行。</p>:null}{copyMessage?<p role="status">{copyMessage}</p>:null}</div>;
}

