import {useState} from 'react';
import type {CanvasNode,Graph} from '../../../domain/graph';
import type {CapabilityProfile} from '../../../domain/connection';
import type {Asset} from '../../../domain/asset';
import type {GraphOperation} from '../../../application/commands/registry';
import {Button} from '../../../ui/Button';
import {InputInspector} from '../InputInspector';
import {Dialog} from '../../../ui/Dialog';
export type VideoCanvasNode=Extract<CanvasNode,{type:'video-generation'}>;
export function VideoNode({node,graph,assets,capability,readonly,onChange,onCommand,onOptimize}:{node:VideoCanvasNode;graph:Graph;assets:Asset[];capability:CapabilityProfile;readonly:boolean;onChange:(data:VideoCanvasNode['data'])=>void;onCommand:(ops:GraphOperation[])=>void;onOptimize?:()=>void}){
 const [resetOpen,setResetOpen]=useState(false),[resetIndex,setResetIndex]=useState(0);
 const known=capability.verification!=='unknown',specs=capability.videoSpecs.filter(s=>s.modelId===node.data.draft.modelId),durations=[...new Set(specs.flatMap(s=>s.durationSeconds===undefined?[]:[s.durationSeconds]))],ratios=[...new Set(specs.flatMap(s=>s.ratio?[s.ratio]:[]))],resolutions=[...new Set(specs.flatMap(s=>s.resolution?[s.resolution]:[]))];
 const patch=(value:Partial<VideoCanvasNode['data']['draft']>)=>onChange({...node.data,draft:{...node.data.draft,...value},stale:true});
 return <div className="video-node-editor">{node.data.missingInputNodeIds?.length?<p role="alert">缺少复制前的外部输入，请明确重新连接。</p>:null}{!known?<p className="banner warning">尚未验证此功能是否可用</p>:null}{node.data.stale?<small>输入或参数已变 · 待更新</small>:null}<label>视频模型<select disabled={readonly||!known||!capability.videoModels.length} value={node.data.draft.modelId} onChange={e=>patch({modelId:e.target.value})}>{!capability.videoModels.includes(node.data.draft.modelId)?<option value={node.data.draft.modelId}>原草稿模型 · 待核验</option>:null}{capability.videoModels.map(model=><option key={model} value={model}>{model}</option>)}</select></label><div className="video-spec-fields"><label>时长（秒）<select disabled={readonly||!known||!durations.length} value={node.data.draft.durationSeconds??''} onChange={e=>patch({durationSeconds:Number(e.target.value)})}>{!durations.includes(node.data.draft.durationSeconds??0)?<option value={node.data.draft.durationSeconds??''}>原值 {node.data.draft.durationSeconds??'未设置'} · 待核验</option>:null}{durations.map(duration=><option key={duration} value={duration}>{duration}</option>)}</select></label><label>画幅比例<select disabled={readonly||!known||!ratios.length} value={node.data.draft.ratio??''} onChange={e=>patch({ratio:e.target.value})}>{!ratios.includes(node.data.draft.ratio??'')?<option value={node.data.draft.ratio??''}>原值 {node.data.draft.ratio??'未设置'} · 待核验</option>:null}{ratios.map(ratio=><option key={ratio}>{ratio}</option>)}</select></label><label>清晰度<select disabled={readonly||!known||!resolutions.length} value={node.data.draft.resolution??''} onChange={e=>patch({resolution:e.target.value})}>{!resolutions.includes(node.data.draft.resolution??'')?<option value={node.data.draft.resolution??''}>原值 {node.data.draft.resolution??'未设置'} · 待核验</option>:null}{resolutions.map(resolution=><option key={resolution}>{resolution}</option>)}</select></label></div><Button disabled={readonly||!known||!specs.length} onClick={()=>{setResetIndex(0);setResetOpen(true);}}>重置为已核验规格</Button><InputInspector graph={graph} nodeId={node.id} assets={assets} capability={capability} readonly={readonly} onCommand={onCommand}/><Button data-interaction-id="PG02" onClick={onOptimize}>提示词生成</Button><small>本地草稿不代表执行授权。</small><Dialog open={resetOpen} title="确认重置参数" onClose={()=>setResetOpen(false)} footer={<><Button onClick={()=>setResetOpen(false)}>取消</Button><Button disabled={!specs[resetIndex]} onClick={()=>{const selected=specs[resetIndex];if(selected)onChange({...node.data,draft:{...selected},stale:true});setResetOpen(false);}}>应用所选规格</Button></>}><p>服务没有提供默认值时，请明确选择一项已核验规格。旧任务快照保持原样。</p><p>当前草稿：{JSON.stringify(node.data.draft)}</p>{specs.map((spec,index)=><label key={index}><input type="radio" name={"reset-"+node.id} checked={resetIndex===index} onChange={()=>setResetIndex(index)}/>{JSON.stringify(spec)}</label>)}</Dialog></div>;
}


