import {useState} from 'react';
import type {Asset} from '../../domain/asset';
import type {ResourceSnapshot} from './reference-index';
import {referencesFor} from './reference-index';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
import {LocalLink} from '../../app/routes';
import {AssetPreview} from './AssetPreview';
import {saveAssetMetadata,undoAssetMetadata,useAssetInProject} from './asset-service';
import {relinkAsset,confirmDifferentContent,type RelinkResult} from './relink-service';
import {getDeletionImpact,deleteLocalResource,type DeletionImpact} from '../projects/delete-policy';
import {withDatabase,transact,requestResult} from '../../infrastructure/storage/database';
export function AssetInspector({asset,snapshot,onChange,onClose}:{asset:Asset;snapshot:ResourceSnapshot;onChange:()=>Promise<void>;onClose:()=>void}){
 const [title,setTitle]=useState(asset.title),[tags,setTags]=useState((asset.tags??[]).join(',')),[description,setDescription]=useState(asset.description??''),[message,setMessage]=useState(''),[error,setError]=useState(''),[receiptId,setReceiptId]=useState(''),[refresh,setRefresh]=useState(0),[targetOpen,setTargetOpen]=useState(false),[replaceMode,setReplaceMode]=useState(false),[candidate,setCandidate]=useState<Extract<RelinkResult,{status:'new_asset_requires_confirmation'}>>(),[replace,setReplace]=useState<{projectId:string;nodeId:string;revision:number;count:number;names:string[]}>();
 const [deleteImpact,setDeleteImpact]=useState<DeletionImpact>(),[deleteBusy,setDeleteBusy]=useState(false);
 const refs=referencesFor(snapshot,asset.id),projects=snapshot.projects.filter(p=>p.trashedAt===null);
 function downstream(projectId:string,nodeId:string){const graph=snapshot.graphs.find(g=>g.projectId===projectId),seen=new Set<string>(),pending=[nodeId];while(pending.length){const source=pending.shift()!;for(const edge of graph?.edges.filter(e=>e.sourceId===source)??[])if(!seen.has(edge.targetId)){seen.add(edge.targetId);pending.push(edge.targetId);}}return [...seen].map(id=>graph?.nodes.find(n=>n.id===id)?.title??id);}
 async function perform(action:()=>Promise<void>,failureMessage?:string){setError('');try{await action();}catch(e){setError(failureMessage??(e instanceof Error&&/conflict|changed|lease|writer/.test(e.message)?'内容或写权已变化，请重新读取后操作。':'操作失败，修改尚未保存，请检查名称、标签限制或本地空间。'));}}
 async function download(){await perform(async()=>{const row=await withDatabase(undefined,db=>transact(db,['blobs'],'readonly',tx=>requestResult<{blob:Blob}|undefined>(tx.objectStore('blobs').get(asset.blobKey))));if(!row)throw new Error('blob_missing');const url=URL.createObjectURL(row.blob),link=document.createElement('a');link.href=url;link.download=asset.title;link.click();setTimeout(()=>URL.revokeObjectURL(url),20000);setMessage('已触发浏览器下载：'+asset.title);},'原素材下载失败，请重新读取或关联本地文件；素材与任务记录保留。');}
 return <aside data-dialog-id="D07" className="asset-inspector card" aria-label="素材详情"><div className="actions"><h2>素材详情</h2><Button data-interaction-id="ui:AssetInspector:Button:e8b0366eaa87" onClick={onClose}>关闭详情</Button></div>{error&&!targetOpen&&!replace&&!candidate?<p role="alert">{error}</p>:null}{message?<p role="status">{message}</p>:null}<AssetPreview allowAutoPlay assetId={asset.id} refresh={refresh+(asset.metadataRevision??0)}/><dl><dt>素材 ID</dt><dd>{asset.id}</dd><dt>内容 hash</dt><dd className="break-word">{asset.sha256}</dd><dt>来源</dt><dd>{asset.sourceRunId?'任务 '+asset.sourceRunId:'用户本地导入'}</dd><dt>规格 / 时长 / 大小</dt><dd>{asset.width&&asset.height?asset.width+' × '+asset.height:'未知'} / {asset.durationSeconds??'未知'} 秒 / {asset.bytes} 字节</dd><dt>本地位置</dt><dd>当前浏览器 · {asset.blobKey}</dd><dt>引用数量（含历史）</dt><dd>{refs.length}</dd></dl>
 <label>素材名称<input data-interaction-id="ui:AssetInspector:input:69a71a04f5af" value={title} onChange={event=>setTitle(event.target.value)}/></label><label>素材标签<input data-interaction-id="ui:AssetInspector:input:7d275eaa6ee2" value={tags} onChange={event=>setTags(event.target.value)} placeholder="逗号分隔，最多10个，每个1–24字符"/></label><label>素材说明<textarea data-interaction-id="ui:AssetInspector:textarea:589f6131dce4" value={description} onChange={event=>setDescription(event.target.value)}/></label><div className="actions"><Button data-interaction-id="M-07" onClick={()=>perform(async()=>{const result=await saveAssetMetadata(asset,{title,tags:tags?tags.split(/[,，]/).map(t=>t.trim()):[],description});setReceiptId(result.receiptId);await onChange();setMessage('素材信息已保存，内容 hash 不变。');})}>保存素材信息</Button><Button data-interaction-id="ui:AssetInspector:Button:6a86e042018a" disabled={!receiptId} onClick={()=>perform(async()=>{const restored=await undoAssetMetadata(receiptId);setReceiptId('');setTitle(restored.title);setTags((restored.tags??[]).join(','));setDescription(restored.description??'');await onChange();setMessage('素材信息已撤销。');})}>撤销素材信息修改</Button></div>
 <h3>引用位置</h3>{snapshot.graphs.flatMap(graph=>graph.nodes.filter(node=>(node.type==='asset'||node.type==='result')&&node.data.assetId===asset.id).map(node=><div key={graph.projectId+node.id}><LocalLink data-interaction-id="M-15" href={'/projects/'+encodeURIComponent(graph.projectId)+'/canvas?node='+encodeURIComponent(node.id)}>{'定位 '+(projects.find(p=>p.id===graph.projectId)?.title??'回收站项目')+' / '+node.title}</LocalLink></div>))}{refs.filter(ref=>ref.kind!=='graph').map((ref,index)=><small key={index}>{ref.kind} · {ref.id}<br/></small>)}
 <div className="actions"><Button data-interaction-id="M-08" onClick={()=>{setReplaceMode(false);setTargetOpen(true);}}>添加到画布</Button><Button data-interaction-id="M-09" onClick={()=>{setReplaceMode(true);setTargetOpen(true);}}>替换草稿输入</Button><Button data-interaction-id="M-11" onClick={download}>下载原素材</Button><Button data-interaction-id="M-12" variant="danger" onClick={()=>perform(async()=>{setDeleteImpact(await getDeletionImpact({kind:'asset',id:asset.id,mode:'soft'}));})}>移到回收站</Button></div>
 <Dialog open={!!deleteImpact} title="移入素材回收站" width={560} dismissible={!deleteBusy} onClose={()=>setDeleteImpact(undefined)} footer={<><Button data-interaction-id="ui:AssetInspector:Button:b25ec1b1303b" disabled={deleteBusy} onClick={()=>setDeleteImpact(undefined)}>返回保留素材</Button><Button data-interaction-id="M-12" variant="danger" disabled={!deleteImpact?.deletable} busy={deleteBusy} onClick={()=>perform(async()=>{if(!deleteImpact)return;setDeleteBusy(true);try{const result=await deleteLocalResource(deleteImpact.target,{impactHash:deleteImpact.impactHash,displayedCounts:deleteImpact.displayedCounts});if(!result.success)throw Error(result.errorCode);setDeleteImpact(undefined);await onChange();onClose();}finally{setDeleteBusy(false);}})}>确认移入素材回收站</Button></>}><p>素材 {asset.title} · 本地及历史引用 {deleteImpact?.displayedCounts.references??0} 项。只隐藏素材库入口，原文件、画布引用和任务追踪保留；不会取消生成或退款。</p>{error?<p role="alert">{error}</p>:null}</Dialog>
 <label>重新关联文件<input data-interaction-id="M-10" type="file" accept="image/*,video/*,audio/*" onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)void perform(async()=>{const result=await relinkAsset(asset.id,file);if(result.status==='same_hash_restored'){setRefresh(value=>value+1);setMessage('相同内容已恢复，原素材身份与来源保留。');await onChange();}else if(result.status==='new_asset_requires_confirmation')setCandidate(result);else throw new Error(result.errorCode);});}}/></label>
 <Dialog open={!!candidate} title="确认不同内容" onClose={()=>setCandidate(undefined)} footer={<><Button data-interaction-id="ui:AssetInspector:Button:8a42aab5254b" onClick={()=>setCandidate(undefined)}>取消</Button><Button data-interaction-id="ui:AssetInspector:Button:ae645462fc23" onClick={()=>perform(async()=>{if(!candidate)return;const created=await confirmDifferentContent(candidate.candidate);setCandidate(undefined);await onChange();setMessage('已另存为新素材：'+created.title+'；原素材与历史不变。需要替换草稿时，请选择新素材并确认影响。');})}>确认另存新素材</Button></>}><p>内容 hash 不同；即使文件名相同，也不能恢复为原素材。将另建素材，保留原来源与运行快照。</p><p>原素材本地引用：{refs.length}；不会自动替换引用。</p></Dialog>
 <Dialog open={targetOpen} title="选择目标项目" onClose={()=>setTargetOpen(false)} footer={<Button data-interaction-id="ui:AssetInspector:Button:b0475de47d44" onClick={()=>setTargetOpen(false)}>取消</Button>}>{error?<p role="alert">{error}</p>:null}<p>{replaceMode?'仅替换可编辑素材节点；运行快照与历史结果不变。':'只创建素材引用节点，不复制文件、不提交生成。'}</p>{projects.map(project=>replaceMode?snapshot.graphs.filter(g=>g.projectId===project.id).flatMap(g=>g.nodes.filter(n=>n.type==='asset'&&!n.locked).map(n=><Button data-interaction-id="ui:AssetInspector:Button:d1731561f35f" key={n.id} onClick={()=>{setTargetOpen(false);setReplace({projectId:project.id,nodeId:n.id,revision:g.revision,count:downstream(project.id,n.id).length,names:downstream(project.id,n.id)});}}>{'替换 '+project.title+' / '+n.title}</Button>)):<Button data-interaction-id="ui:AssetInspector:Button:e8295373a4b9" key={project.id} onClick={()=>perform(async()=>{await useAssetInProject(asset,project.id);setTargetOpen(false);await onChange();setMessage('已添加素材引用节点；没有创建生成任务。');})}>{'插入 '+project.title}</Button>)}</Dialog>
 <Dialog open={!!replace} title="确认替换输入" onClose={()=>setReplace(undefined)} footer={<><Button data-interaction-id="ui:AssetInspector:Button:d95f90018184" onClick={()=>setReplace(undefined)}>取消</Button><Button data-interaction-id="ui:AssetInspector:Button:f54ccdc6292a" onClick={()=>perform(async()=>{if(!replace)return;await useAssetInProject(asset,replace.projectId,replace.nodeId,replace.revision);setReplace(undefined);await onChange();setMessage('输入已替换，下游草稿标为待更新，原任务未改写。');})}>确认替换草稿输入</Button></>}>{error?<p role="alert">{error}</p>:null}<p>受影响下游节点：{replace?.count??0}。替换只改变草稿；历史任务、收费授权与冻结请求均保留。</p><ul>{replace?.names.map(name=><li key={name}>{name}</li>)}</ul></Dialog>
 </aside>;
}


