import {useEffect,useState} from 'react';
import type {ResourceSnapshot} from './reference-index';
import {referencesFor} from './reference-index';
import {listAssetResources} from './asset-service';
import {inspectAssetFiles,commitInspectedAssets,type ImportInspection,type ImportReport} from './import-service';
import {AssetInspector} from './AssetInspector';
import {AssetPreview} from './AssetPreview';
import {Dialog} from '../../ui/Dialog';
import {useRoute} from '../../app/routes';
import {Button} from '../../ui/Button';
const empty:ResourceSnapshot={projects:[],graphs:[],assets:[],runs:[],drafts:[],links:[],receipts:[]};
export function AssetsPage(){const [inspection,setInspection]=useState<ImportInspection>();const route=useRoute();const [snapshot,setSnapshot]=useState(empty),[loading,setLoading]=useState(true),[error,setError]=useState(''),[report,setReport]=useState<ImportReport>(),[importing,setImporting]=useState(false),[query,setQuery]=useState(''),[type,setType]=useState('all'),[tag,setTag]=useState(''),[referenced,setReferenced]=useState(false),[sort,setSort]=useState('recent'),[view,setView]=useState('grid'),[selected,setSelected]=useState<string[]>([]),[inspected,setInspected]=useState<string|undefined>(()=>new URLSearchParams(location.search).get('asset')??undefined),[preview,setPreview]=useState<string>();
 async function reload(){const next=await listAssetResources();setSnapshot(next);setLoading(false);}
 useEffect(()=>{void reload().catch(()=>{setLoading(false);setError('素材库读取失败，请重试。');});},[]);
 useEffect(()=>{const id=new URLSearchParams(route.split('?')[1]??'').get('asset');if(id)setInspected(id);},[route]);
 const assets=snapshot.assets.filter(a=>!a.trashedAt),filtered=assets.filter(a=>(type==='all'||a.mediaType===type)&&a.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())&&(!tag||a.tags?.includes(tag))&&(!referenced||referencesFor(snapshot,a.id).length>0)).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title,'zh-CN'):b.createdAt-a.createdAt||a.title.localeCompare(b.title,'zh-CN')),asset=snapshot.assets.find(a=>a.id===inspected);
 return <section><div className="asset-filters card"><label>导入素材<input data-interaction-id="M-01" type="file" accept="image/*,video/*,audio/*" multiple disabled={importing} onChange={async event=>{const files=Array.from(event.target.files??[]);event.target.value='';if(!files.length)return;setImporting(true);setError('');try{setInspection(await inspectAssetFiles(files));}catch{setError('导入未完成，请检查本地空间。');}finally{setImporting(false);}}}/></label>{importing?<p role="status">正在本地解析、计算 hash，尚未写入…</p>:null}{report?<p role="status">{'成功 '+report.successes.length+'，重复 '+report.successes.filter(s=>s.deduplicated).length+'，失败 '+report.failures.length}{report.errorCode?' · '+report.errorCode:''}{report.failures.map(f=><span key={f.fileName}><br/>{f.fileName}：{f.errorCode}</span>)}</p>:null}
 <div className="form-row"><label>搜索素材<input data-interaction-id="ui:AssetsPage:input:241a38c91652" type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>素材类型<select data-interaction-id="M-13" value={type} onChange={e=>setType(e.target.value)}><option value="all">全部</option><option value="image">图片</option><option value="video">视频</option><option value="audio">音频</option><option value="text">文本</option></select></label><label>标签筛选<select data-interaction-id="ui:AssetsPage:select:eda28edc5037" value={tag} onChange={e=>setTag(e.target.value)}><option value="">全部标签</option>{[...new Set(assets.flatMap(a=>a.tags??[]))].map(t=><option key={t}>{t}</option>)}</select></label><label>素材排序<select data-interaction-id="ui:AssetsPage:select:dc8454e7607a" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">最近添加</option><option value="title">名称</option></select></label></div><div className="actions"><label><input data-interaction-id="ui:AssetsPage:input:05f9551e82ad" type="checkbox" checked={referenced} onChange={e=>setReferenced(e.target.checked)}/>仅被引用素材</label><Button data-interaction-id="M-14" aria-pressed={view==='grid'} onClick={()=>setView('grid')}>网格</Button><Button data-interaction-id="M-14" aria-pressed={view==='list'} onClick={()=>setView('list')}>列表</Button><Button data-interaction-id="ui:AssetsPage:Button:1027387eebcf" onClick={()=>{setQuery('');setType('all');setTag('');setReferenced(false);}}>清除筛选</Button><span>已选择 {selected.length} 项</span></div></div>
 {error?<p role="alert">{error}<Button data-interaction-id="ui:AssetsPage:Button:c8c912747cde" onClick={async()=>{try{await reload();setError('');}catch{setError('素材库仍无法读取。');}}}>重新读取素材</Button></p>:null}{loading?<p role="status">正在读取素材库…</p>:<div className={'asset-library '+(asset?'with-inspector':'')}><div className={'asset-cards '+view}>{!filtered.length?<p className="card">没有匹配素材，请导入或清除筛选。</p>:null}{filtered.map(a=><article className="card asset-card" data-testid="asset-card" key={a.id}><label><input data-interaction-id="ui:AssetsPage:input:7dd94fb7d974" type="checkbox" aria-label={'选择 '+a.title} checked={selected.includes(a.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,a.id]:ids.filter(id=>id!==a.id))}/>{a.title}</label><AssetPreview assetId={a.id} refresh={a.metadataRevision??0} thumbnail={a.mediaType==='image'}/><small>{a.mediaType} · {a.bytes} 字节 · 引用 {referencesFor(snapshot,a.id).length}</small><div className="actions">{a.mediaType==='image'?<Button data-interaction-id="M-03" aria-label={'预览 '+a.title} onClick={()=>setPreview(a.id)}>查看大图</Button>:null}<Button data-interaction-id="M-15" aria-label={'详情 '+a.title} onClick={()=>setInspected(a.id)}>详情</Button></div></article>)}</div>{asset?<AssetInspector key={asset.id} asset={asset} snapshot={snapshot} onChange={reload} onClose={()=>setInspected(undefined)}/>:null}</div>}
<Dialog width={720} title="文件导入检查" open={!!inspection} dismissible={!importing} onClose={()=>setInspection(undefined)} footer={<><Button data-interaction-id="ui:AssetsPage:Button:b9f19eb3bdbb" disabled={importing} onClick={()=>setInspection(undefined)}>取消导入</Button><Button data-interaction-id="M-02" disabled={importing||!inspection?.valid.length} onClick={async()=>{if(!inspection)return;setImporting(true);try{setReport(await commitInspectedAssets(inspection));setInspection(undefined);await reload();}catch{setError('导入保存失败，请保留原文件重新选择。');}finally{setImporting(false);}}}>{'确认导入 '+(inspection?.valid.length??0)+' 个有效文件'}</Button></>}><p>当前只在内存解析，未写入素材库、画布或 Core。有效 {inspection?.valid.length??0} 个，失败 {inspection?.failures.length??0} 个。</p><ul>{inspection?.valid.map((item,index)=><li key={index}>{item.file.name} · {item.metadata.mimeType} · {item.file.size} 字节</li>)}{inspection?.failures.map((item,index)=><li role="alert" key={index}>{item.fileName}：{item.errorCode}；不会导入。</li>)}</ul></Dialog>
 <Dialog open={!!preview} title="素材预览" width={960} onClose={()=>setPreview(undefined)}>{preview?<AssetPreview assetId={preview}/>:null}</Dialog>
 </section>;
}

