import {useEffect,useRef,useState,type ReactElement} from 'react';
import {assetSchema,type Asset} from '../../domain/asset';
import {withDatabase,transact,requestResult} from '../../infrastructure/storage/database';
import {Button} from '../../ui/Button';
import {activateLocalMedia,releaseLocalMedia} from './playback-coordinator';
let sessionVolume=1,sessionMuted=true;
export function useLocalAsset(assetId:string,refresh=0,thumbnail=false){const [state,setState]=useState<{asset?:Asset;url?:string;missing?:boolean;error?:string}>({});useEffect(()=>{let alive=true,url:string|undefined;void withDatabase(undefined,db=>transact(db,['assets','blobs'],'readonly',async tx=>{const raw=await requestResult(tx.objectStore('assets').get(assetId));if(!raw)return {missing:true};const asset=assetSchema.parse(raw),record=await requestResult<{blob:Blob}|undefined>(tx.objectStore('blobs').get(thumbnail?'thumbnail:'+asset.sha256:asset.blobKey));return {asset,record};})).then(result=>{if(!alive)return;if(result.record)url=URL.createObjectURL(result.record.blob);setState({asset:result.asset,url,missing:!url});}).catch(()=>{if(alive)setState({error:'本地媒体读取失败，请重试。'});});return()=>{alive=false;if(url)URL.revokeObjectURL(url);};},[assetId,refresh,thumbnail]);return state;}
export function AssetPreview({assetId,refresh=0,thumbnail=false,playbackGroup,onMediaReady,onEnded,onPlaybackPaused,onCanPlay}:{assetId:string;refresh?:number;thumbnail?:boolean;playbackGroup?:string;onMediaReady?:(element:HTMLMediaElement|null)=>void;onEnded?:()=>void;onPlaybackPaused?:()=>void;onCanPlay?:()=>void}):ReactElement{
 const {asset,url,missing,error}=useLocalAsset(assetId,refresh,thumbnail),media=useRef<HTMLMediaElement|null>(null),[playing,setPlaying]=useState(false),[failed,setFailed]=useState(false),[muted,setMuted]=useState(sessionMuted),[volume,setVolume]=useState(sessionVolume),[position,setPosition]=useState(0),[original,setOriginal]=useState(false);
 useEffect(()=>{const element=media.current;return()=>{if(element){element.pause();element.removeAttribute('src');element.load();releaseLocalMedia(element);}};},[url]);
 useEffect(()=>{if(media.current){media.current.muted=muted;media.current.volume=volume;}},[muted,volume,url]);
 function start(element:HTMLMediaElement){activateLocalMedia(element,playbackGroup);setPlaying(true);}
 async function toggle(){const element=media.current;if(!element)return;if(!element.paused){element.pause();return;}activateLocalMedia(element,playbackGroup);try{await element.play();}catch{setFailed(true);}}
 if(error)return <p role="alert">{error}</p>;if(missing)return <p className="muted">本地文件缺失，请重新关联；不会扫描磁盘或自动请求远端。</p>;if(!asset||!url)return <p>正在读取本地媒体…</p>;
 if(asset.mediaType==='image')return <div className={'asset-image '+(original?'original':'fit')}><img src={url} alt={asset.title}/>{!thumbnail?<div className="actions"><Button aria-pressed={!original} onClick={()=>setOriginal(false)}>适配</Button><Button aria-pressed={original} onClick={()=>setOriginal(true)}>原尺寸</Button></div>:null}</div>;
 if(thumbnail)return <p>{asset.mediaType==='audio'?'音频文件':'视频文件'}</p>;
 const props={src:url,preload:'metadata',muted,autoPlay:false,onPlay:(event:React.SyntheticEvent<HTMLMediaElement>)=>start(event.currentTarget),onPause:()=>{setPlaying(false);onPlaybackPaused?.();},onEnded,onCanPlay,onTimeUpdate:(event:React.SyntheticEvent<HTMLMediaElement>)=>setPosition(event.currentTarget.currentTime),onError:()=>setFailed(true)};
 return <div className="asset-player">{asset.mediaType==='video'?<video {...props} ref={element=>{media.current=element;onMediaReady?.(element);}}/>:<audio {...props} ref={element=>{media.current=element;onMediaReady?.(element);}}/>}<div className="actions"><Button data-interaction-id="M-04" aria-label={(playing?'暂停 ':'播放 ')+asset.title} disabled={failed} disabledReason={failed?'无法解码，可在详情下载原文件。':undefined} onClick={toggle}>{playing?'暂停':'播放'}</Button><Button data-interaction-id="M-05" aria-label={(muted?'取消静音 ':'静音 ')+asset.title} onClick={()=>{sessionMuted=!muted;setMuted(!muted);}}>{muted?'静音中':'有声'}</Button></div><label>{asset.title} 音量<input type="range" min="0" max="1" step=".1" value={volume} onChange={event=>{sessionVolume=Number(event.target.value);setVolume(sessionVolume);}}/></label><label>{asset.title} 播放进度<input data-interaction-id="M-06" type="range" min="0" max={asset.durationSeconds??0} step="1" value={position} disabled={!asset.durationSeconds} onChange={event=>{if(media.current){media.current.currentTime=Number(event.target.value);setPosition(Number(event.target.value));}}} onKeyDown={event=>{if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();const next=Math.min(asset.durationSeconds??0,Math.max(0,position+(event.key==='ArrowRight'?5:-5)));if(media.current)media.current.currentTime=next;setPosition(next);}}}/></label>{failed?<p role="alert">媒体无法解码，请在详情下载原文件。</p>:null}</div>;
}
