import {expect,it,vi} from 'vitest';
import {createPageMemory} from '../../src/features/auth/page-memory';
import {createSessionStore} from '../../src/infrastructure/api/session';
import {defaultPreferences} from '../../src/features/settings/preferences-store';
const a={user:{id:'11111111-1111-4111-8111-111111111111',username:'Fake_Page_A'},contextId:'a'.repeat(43),csrfToken:'b'.repeat(43),onboardingCompletedAt:null};
const b={...a,user:{id:'22222222-2222-4222-8222-222222222222',username:'Fake_Page_B'},contextId:'c'.repeat(43)};
const {lastVisitedPage:_,defaultTextModel:__,defaultVideoModel:___,...preferences}=defaultPreferences;void _;void __;void ___;
const document=(lastVisitedPage='/projects',revision=0)=>({preferences,revision,lastVisitedPage,onboardingCompletedAt:null});
const response=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
it('page memory coalesces pending navigation to the latest page and uses the accepted revision',async()=>{
 let release!:(response:Response)=>void;const held=new Promise<Response>(resolve=>{release=resolve;});const fetcher=vi.fn<typeof fetch>().mockResolvedValueOnce(response(a)).mockResolvedValueOnce(response(document())).mockImplementationOnce(()=>held).mockResolvedValueOnce(response(document('/help',2)));const store=createSessionStore(fetcher);await store.refresh();const onResult=vi.fn();const memory=createPageMemory(store,a.contextId,onResult);try{memory.visit('/settings/connections');await vi.waitFor(()=>expect(fetcher).toHaveBeenCalledTimes(3));memory.visit('/settings/appearance');memory.visit('/help');release(response(document('/settings/connections',1)));await vi.waitFor(()=>expect(fetcher).toHaveBeenCalledTimes(4));expect(JSON.parse(fetcher.mock.calls[3][1]!.body as string)).toEqual({expectedRevision:1,lastVisitedPage:'/help'});await vi.waitFor(()=>expect(onResult).toHaveBeenCalledTimes(2));}finally{memory.dispose();}
});
it('page memory stops after a revision conflict and resumes only after a newer document is accepted',async()=>{
 const fetcher=vi.fn<typeof fetch>().mockResolvedValueOnce(response(a)).mockResolvedValueOnce(response(document())).mockResolvedValueOnce(response({code:'REVISION_CONFLICT'},409)).mockResolvedValueOnce(response(a)).mockResolvedValueOnce(response(document('/projects',1))).mockResolvedValueOnce(response(document('/help',2)));const store=createSessionStore(fetcher);await store.refresh();const onResult=vi.fn();const memory=createPageMemory(store,a.contextId,onResult);try{memory.visit('/help');await vi.waitFor(()=>expect(onResult).toHaveBeenCalledTimes(1));expect(onResult.mock.calls[0][0]).toMatchObject({code:'REVISION_CONFLICT'});memory.visit('/help');await store.checkSession();expect(fetcher).toHaveBeenCalledTimes(4);await store.reloadDocument();await vi.waitFor(()=>expect(onResult).toHaveBeenCalledTimes(2));expect(fetcher).toHaveBeenCalledTimes(6);expect(JSON.parse(fetcher.mock.calls[5][1]!.body as string)).toEqual({expectedRevision:1,lastVisitedPage:'/help'});}finally{memory.dispose();}
});
it('page memory drops queued A intent after a different account refresh even when transport ignores abort',async()=>{
 let release!:(response:Response)=>void;const held=new Promise<Response>(resolve=>{release=resolve;});const fetcher=vi.fn<typeof fetch>().mockResolvedValueOnce(response(a)).mockResolvedValueOnce(response(document())).mockImplementationOnce(()=>held).mockResolvedValueOnce(response(b)).mockResolvedValueOnce(response(document()));const store=createSessionStore(fetcher);await store.refresh();const onResult=vi.fn();const memory=createPageMemory(store,a.contextId,onResult);try{memory.visit('/settings/connections');await vi.waitFor(()=>expect(fetcher).toHaveBeenCalledTimes(3));memory.visit('/help');await store.refresh();release(response(document('/settings/connections',1)));await vi.waitFor(()=>expect(fetcher.mock.calls[2][1]!.signal!.aborted).toBe(true));await Promise.resolve();await Promise.resolve();expect(fetcher).toHaveBeenCalledTimes(5);expect(onResult).not.toHaveBeenCalled();const state=store.getState();expect(state.status).toBe('authenticated');if(state.status==='authenticated'){expect(state.session.user.id).toBe(b.user.id);expect(state.document.lastVisitedPage).toBe('/projects');}}finally{memory.dispose();}
});
