import {it,expect} from 'vitest';
import {preflightRun,type RunDraftInput} from '../../src/application/runs/preflight';
import {createAuthBinding} from '../../src/domain/authorization';
import {f} from '../helpers/fixtures';
const spec={modelId:'fake-video-only',durationSeconds:5,ratio:'9:16'},profile=f.connection();
function draft(patch:Partial<RunDraftInput>={}):RunDraftInput{return {graph:f.graph({nodes:[{id:'t1',type:'text',title:'文字',x:0,y:0,locked:false,data:{kind:'text',text:'原创测试',referenceTokens:[]}},{id:'v1',type:'video-generation',title:'视频',x:400,y:0,locked:false,data:{kind:'video-generation',draft:{...spec},inputBindings:[],stale:false}}],edges:[{id:'e1',sourceId:'t1',targetId:'v1',port:'text',order:0}]}),nodeIds:['v1'],assets:[],readableAssetIds:[],capability:f.caps({videoSpecs:[{...spec}],limits:{promptBytes:65536,imageReferences:0,videoReferences:0}}),connection:profile,binding:createAuthBinding(profile),canWrite:true,credentialAvailable:true,...patch};}
it('T26: preflight is pure and captures the exact visible text/spec/revision',()=>{const result=preflightRun(draft());expect(result.status).toBe('ready');if(result.status==='ready'){expect(result.plan.revision).toBe(1);expect(result.plan.nodes[0].inputSnapshot).toEqual({prompt:'原创测试',spec,references:[]});}});
it('T26: unknown capability, authorization and dirty inputs remain separate blockers',()=>{const result=preflightRun(draft({capability:f.unknownCaps(),credentialAvailable:false,dirty:true}));expect(result.status).toBe('blocked');expect(result.issues.map(i=>i.code)).toEqual(expect.arrayContaining(['capability_unverified','session_credential_required','unsaved_changes']));});
it('T26: unsupported duration is reported and the original draft stays intact',()=>{const input=draft();const node=input.graph.nodes.find(n=>n.type==='video-generation')!;if(node.type==='video-generation')node.data.draft.durationSeconds=15;const before=structuredClone(input);const result=preflightRun(input);expect(result.issues.map(i=>i.code)).toContain('video_spec_unsupported');expect(input).toEqual(before);});
it('T26: an unbound textual reference is blocked rather than silently removed',()=>{const input=draft();const node=input.graph.nodes.find(n=>n.type==='text')!;if(node.type==='text')node.data.referenceTokens=[{alias:'@图片1',mediaType:'image',role:'参考',description:'',available:false,unbound:true}];expect(preflightRun(input).issues.map(i=>i.code)).toContain('reference_unbound');});
it('T26: plain-text reference placeholders also need an explicit readable input binding',()=>{const input=draft();const node=input.graph.nodes.find(n=>n.type==='text')!;if(node.type==='text')node.data.text='按 @图片3 的人物拍摄';expect(preflightRun(input).issues.map(i=>i.code)).toContain('reference_alias_unbound');});
it('a refreshed tab with verified cached specs reports missing authorization without inventing capability or identity failures',()=>{const input=draft({credentialAvailable:false,connection:undefined,binding:undefined}),before=structuredClone(input),result=preflightRun(input);expect(result.status).toBe('blocked');expect(result.issues.map(i=>i.code)).toEqual(['session_credential_required']);expect(result.issues[0].message).toContain('刷新');expect(input).toEqual(before);});
it('actual identity mismatches and missing bindings with a claimed credential still block execution',()=>{for(const patch of [{binding:{...createAuthBinding(profile),connectionId:'another'}},{binding:undefined},{connection:undefined}]){const result=preflightRun(draft(patch));expect(result.status).toBe('blocked');expect(result.issues.map(i=>i.code)).toContain('original_authorization_required');}});
it('execution spec overrides contradictory prompt specs without altering source text or quoted dialogue',()=>{const input=draft();const text=input.graph.nodes[0];if(text.type!=='text')throw Error('fixture');text.data.text='生成10秒视频，画幅16:9，清晰度1080p。对白：“等待10秒，然后写16:9”。';const before=structuredClone(input),result=preflightRun(input);expect(result.status).toBe('ready');if(result.status!=='ready')return;const snapshot=result.plan.nodes[0].inputSnapshot;expect(snapshot.spec).toEqual(spec);expect(snapshot.prompt).toContain('以视频界面选择为准');expect(snapshot.prompt).toContain('5秒');expect(snapshot.prompt).toContain('9:16');expect(snapshot.prompt).toContain('对白：“等待10秒，然后写16:9”');expect(input).toEqual(before);});
it('bare duration in creative text cannot override the execution duration',()=>{const input=draft(),text=input.graph.nodes[0];if(text.type==='text')text.data.text='10秒，猴子摘苹果。';const result=preflightRun(input);expect(result.status).toBe('ready');if(result.status==='ready')expect(result.plan.nodes[0].inputSnapshot.prompt).toContain('总时长5秒');});
function referenceDraft(mediaType:'image'|'video',limit:number,assetBytes?:number){const input=draft(),asset=f.asset({mediaType,mimeType:mediaType==='image'?'image/png':'video/mp4',bytes:635965});input.assets=[asset];input.readableAssetIds=[asset.id];input.graph.nodes.push({id:'ref1',type:'asset',title:'原参考',x:0,y:300,locked:false,data:{kind:'asset',assetId:asset.id}});input.graph.edges.push({id:'ref-edge',sourceId:'ref1',targetId:'v1',port:mediaType,order:1});input.capability.limits={...input.capability.limits,[mediaType==='image'?'imageReferences':'videoReferences']:limit,...(assetBytes===undefined?{}:{assetBytes})};return input;}
it('a zero media-reference capability explains the service blocker without falsely reporting a readable small file as oversized',()=>{for(const media of ['image','video'] as const){const input=referenceDraft(media,0),before=structuredClone(input),result=preflightRun(input);expect(result.status).toBe('blocked');expect(result.issues).toHaveLength(1);expect(result.issues[0].code).toBe('reference_service_unavailable');expect(result.issues[0].message).toContain(media==='image'?'图片':'视频');expect(result.issues[0].message).toContain('网关');expect(input).toEqual(before);}});
it('enabled references still enforce genuine file-size and reference-count limits',()=>{const size=referenceDraft('image',1,100);expect(preflightRun(size).issues.map(i=>i.code)).toContain('reference_size_invalid');const count=referenceDraft('image',1,1000000);count.graph.nodes.push({id:'ref2',type:'asset',title:'第二张',x:0,y:600,locked:false,data:{kind:'asset',assetId:'a2'}});count.assets.push(f.asset({id:'a2',mediaType:'image',mimeType:'image/png',bytes:100,sha256:'b'.repeat(64)}));count.readableAssetIds.push('a2');count.graph.edges.push({id:'ref-edge2',sourceId:'ref2',targetId:'v1',port:'image',order:2});expect(preflightRun(count).issues.map(i=>i.code)).toContain('reference_limit_unverified_or_exceeded');});
it('unauthorized preflight does not invent a missing-blob failure when readability has not been checked',()=>{const input=referenceDraft('image',0);input.credentialAvailable=false;input.connection=undefined;input.binding=undefined;input.readableAssetIds=[];const result=preflightRun(input);expect(result.status).toBe('blocked');expect(result.issues.map(i=>i.code)).toEqual(['session_credential_required','reference_service_unavailable']);});
