import {it,expect} from 'vitest';
import {preflightRun,type RunDraftInput} from '../../src/application/runs/preflight';
import {createAuthBinding} from '../../src/domain/authorization';
import {f} from '../helpers/fixtures';
const spec={modelId:'fake-video-only',durationSeconds:5,ratio:'9:16'},profile=f.connection();
function draft(patch:Partial<RunDraftInput>={}):RunDraftInput{return {graph:f.graph({nodes:[{id:'t1',type:'text',title:'文字',x:0,y:0,locked:false,data:{kind:'text',text:'原创测试',referenceTokens:[]}},{id:'v1',type:'video-generation',title:'视频',x:400,y:0,locked:false,data:{kind:'video-generation',draft:{...spec},inputBindings:[],stale:false}}],edges:[{id:'e1',sourceId:'t1',targetId:'v1',port:'text',order:0}]}),nodeIds:['v1'],assets:[],readableAssetIds:[],capability:f.caps({videoSpecs:[{...spec}],limits:{promptBytes:65536,imageReferences:0,videoReferences:0}}),connection:profile,binding:createAuthBinding(profile),canWrite:true,credentialAvailable:true,...patch};}
it('T26: preflight is pure and captures the exact visible text/spec/revision',()=>{const result=preflightRun(draft());expect(result.status).toBe('ready');if(result.status==='ready'){expect(result.plan.revision).toBe(1);expect(result.plan.nodes[0].inputSnapshot).toEqual({prompt:'原创测试',spec,references:[]});}});
it('T26: unknown capability, authorization and dirty inputs remain separate blockers',()=>{const result=preflightRun(draft({capability:f.unknownCaps(),credentialAvailable:false,dirty:true}));expect(result.status).toBe('blocked');expect(result.issues.map(i=>i.code)).toEqual(expect.arrayContaining(['capability_unverified','session_credential_required','unsaved_changes']));});
it('T26: unsupported duration is reported and the original draft stays intact',()=>{const input=draft();const node=input.graph.nodes.find(n=>n.type==='video-generation')!;if(node.type==='video-generation')node.data.draft.durationSeconds=15;const before=structuredClone(input);const result=preflightRun(input);expect(result.issues.map(i=>i.code)).toContain('video_spec_unsupported');expect(input).toEqual(before);});
it('T26: an unbound textual reference is blocked rather than silently removed',()=>{const input=draft();const node=input.graph.nodes.find(n=>n.type==='text')!;if(node.type==='text')node.data.referenceTokens=[{alias:'@图片1',mediaType:'image',role:'参考',description:'',available:false,unbound:true}];expect(preflightRun(input).issues.map(i=>i.code)).toContain('reference_unbound');});
it('T26: plain-text reference placeholders also need an explicit readable input binding',()=>{const input=draft();const node=input.graph.nodes.find(n=>n.type==='text')!;if(node.type==='text')node.data.text='按 @图片3 的人物拍摄';expect(preflightRun(input).issues.map(i=>i.code)).toContain('reference_alias_unbound');});
