import {it,expect,beforeEach,afterEach} from 'vitest';import {f} from '../helpers/fixtures';import {openStudioDb,transact,requestResult,type StudioDb} from '../../src/infrastructure/storage/database';import {acquireProjectLease} from '../../src/infrastructure/storage/project-lease';import {inspectLocalCleanup,commitLocalCleanup} from '../../src/features/settings/local-cleanup';
import {IDBFactory} from 'fake-indexeddb';import type {LocalCleanupImpact} from '../../src/features/settings/local-cleanup';
let db:StudioDb;
beforeEach(async()=>{db=await openStudioDb({factory:new IDBFactory(),name:'local-cleanup'});await transact(db,db.tables.slice(),'readwrite',tx=>{for(const name of db.tables)tx.objectStore(name).clear();tx.objectStore('projects').put(f.project());tx.objectStore('graphs').put(f.graph({nodes:[{id:'asset',type:'asset',title:'在用',x:0,y:0,locked:false,data:{kind:'asset',assetId:'used'}}]}));tx.objectStore('assets').put(f.asset({id:'used',title:'在用素材',blobKey:'used-file'}));tx.objectStore('assets').put(f.asset({id:'unused',title:'未引用素材',blobKey:'unused-file'}));tx.objectStore('blobs').put({id:'used-file',blob:new Blob(['original'])});tx.objectStore('blobs').put({id:'unused-file',blob:new Blob(['unused'])});});});afterEach(()=>db.close());
async function state(){return transact(db,['projects','graphs','assets','blobs','runs','receipts'],'readonly',async tx=>Object.fromEntries(await Promise.all(['projects','graphs','assets','blobs','runs','receipts'].map(async name=>[name,await requestResult(tx.objectStore(name).getAll())]))));}
it('T44 D07 scans history before showing exact cleanup; only unreferenced original is removed',async()=>{await transact(db,['runs'],'readwrite',tx=>tx.objectStore('runs').put(f.run({inputSnapshot:{assetId:'used'},executionState:'succeeded'})));const before=await state(),impact=await inspectLocalCleanup('unreferenced-assets',db);expect(impact.items.map(i=>i.id)).toEqual(['unused']);expect(impact.protectedAssets).toBe(1);expect(await commitLocalCleanup(impact,{confirmed:true},{db})).toEqual({removed:1});const after=await state();expect(after.assets.map((a:{id:string})=>a.id)).toEqual(['used']);expect(after.blobs.map((b:{id:string})=>b.id)).toEqual(['used-file']);expect(after.runs).toEqual(before.runs);expect(after.graphs).toEqual(before.graphs);});
it('T44 D07 new references after inspection deny cleanup instead of erasing a newly referenced original',async()=>{const impact=await inspectLocalCleanup('unreferenced-assets',db);await transact(db,['receipts'],'readwrite',tx=>tx.objectStore('receipts').put({id:'historical-reference',assetId:'unused'}));const before=await state();await expect(commitLocalCleanup(impact,{confirmed:true},{db})).rejects.toThrow('cleanup_impact_changed');expect(await state()).toEqual(before);});
it('T44 cleanup rejects an unknown scope rather than allowing an asset-cleanup intent to clear projects',async()=>{const impact=await inspectLocalCleanup('unreferenced-assets',db),acquired=await acquireProjectLease('p1','cleanup-tab',Date.now(),{db});if(!acquired.ok)throw Error('fixture_lease');const before=await state();await expect(commitLocalCleanup({...impact,kind:'unknown-scope'} as unknown as LocalCleanupImpact,{confirmed:true},{db,leases:[acquired.token]})).rejects.toThrow();expect(await state()).toEqual(before);});
it('T44 D08 a stale withdrawal receipt never overrides a current unknown submission',async()=>{await transact(db,['runs','receipts'],'readwrite',tx=>{tx.objectStore('runs').put(f.run({executionState:'submit_unknown'}));tx.objectStore('receipts').put({id:'run-withdrawal:r1',kind:'local-unsent-withdrawal',runId:'r1'});});const impact=await inspectLocalCleanup('projects',db);expect(impact.deletable).toBe(false);expect(impact.blockers).toContain('受保护视频追踪 r1');});
it('T44 D08 blocks unknown tracking; after a known result requires typed phrase and all project writer leases, preserves media/history',async()=>{await transact(db,['runs'],'readwrite',tx=>tx.objectStore('runs').put(f.run({executionState:'submit_unknown'})));const blocked=await inspectLocalCleanup('projects',db);expect(blocked.deletable).toBe(false);await expect(commitLocalCleanup(blocked,{confirmed:true,text:'清空本地项目'},{db})).rejects.toThrow('cleanup_tracking_protected');await transact(db,['runs'],'readwrite',tx=>tx.objectStore('runs').put(f.run({executionState:'succeeded'})));const impact=await inspectLocalCleanup('projects',db),before=await state();await expect(commitLocalCleanup(impact,{confirmed:true,text:'错误确认词'},{db})).rejects.toThrow('cleanup_confirmation_required');await expect(commitLocalCleanup(impact,{confirmed:true,text:'清空本地项目'},{db})).rejects.toThrow();expect(await state()).toEqual(before);const acquired=await acquireProjectLease('p1','cleanup-tab',Date.now(),{db});if(!acquired.ok)throw Error('fixture_lease');await commitLocalCleanup(impact,{confirmed:true,text:'清空本地项目'},{db,leases:[acquired.token]});const after=await state();expect(after.projects).toHaveLength(0);expect(after.graphs).toHaveLength(0);expect(after.runs).toEqual(before.runs);expect(after.assets).toEqual(before.assets);expect(after.blobs).toEqual(before.blobs);});
