import {it,expect,vi} from 'vitest';
import {fetchRunMedia,triggerBrowserDownload} from '../../src/features/review/media-delivery';
import {acquireMediaUrl} from '../../src/features/review/object-url-pool';
import {videoHarness} from '../helpers/video-harness';
import {pollVideoOnce} from '../../src/application/runs/poll-video';
import {readRun} from '../../src/infrastructure/storage/run-repository';
import {transact,requestResult} from '../../src/infrastructure/storage/database';
async function completed(){const h=await videoHarness();await pollVideoOnce(h.runId,h.options);return h;}
it('T33-C02: actual authenticated GET becomes atomic original-Run cache without a new video POST',async()=>{const h=await completed();try{const result=await fetchRunMedia(h.runId,'cache',h.options);const rows=await transact(h.db,['runs','assets','blobs'],'readonly',async tx=>({run:await requestResult(tx.objectStore('runs').get(h.runId)),asset:await requestResult(tx.objectStore('assets').get(result.assetId)),blob:await requestResult(tx.objectStore('blobs').get(result.blobKey))}));expect(rows.asset.sourceRunId).toBe(h.runId);expect(rows.asset.sha256).toMatch(/^[a-f0-9]{64}$/);expect(rows.blob.blob.size).toBe(12);expect(rows.run).toMatchObject({executionState:'succeeded',billingState:'not_provided',deliveryState:'cached_local',resultAssetId:result.assetId});expect(h.mock.requests.filter(r=>r.method==='POST')).toHaveLength(1);expect(h.mock.requests.at(-1)).toMatchObject({method:'GET',path:'/v1/videos/'+h.run.taskId+'/content',credentialPresent:true});}finally{await h.close();}});
it('T33-C03/C04: unverified redirect is blocked, generation stays completed and retry only GETs content',async()=>{const h=await completed();try{h.mock.faults.contentRedirect='https://untrusted.invalid/file.mp4';await expect(fetchRunMedia(h.runId,'download',h.options)).rejects.toThrow('redirect_blocked');expect(await readRun(h.runId,h.db)).toMatchObject({executionState:'succeeded',billingState:'not_provided',deliveryState:'download_failed'});h.mock.faults.contentRedirect=undefined;await fetchRunMedia(h.runId,'cache',h.options);expect(h.mock.requests.filter(r=>r.method==='POST')).toHaveLength(1);}finally{await h.close();}});
it('T33-C05: verified local bytes remain usable offline without the original Key; cache reuse makes no HTTP request',async()=>{const h=await completed();try{const one=await fetchRunMedia(h.runId,'cache',h.options),count=h.mock.requests.length;const two=await fetchRunMedia(h.runId,'preview',{db:h.db});expect(two.assetId).toBe(one.assetId);expect(two.objectUrl).toMatch(/^blob:/);two.release?.();expect(h.mock.requests).toHaveLength(count);}finally{await h.close();}});
it('T33: other authorization and nonterminal generation are refused before content fetch',async()=>{const h=await videoHarness();try{await expect(fetchRunMedia(h.runId,'cache',h.options)).rejects.toThrow('media_not_ready');await pollVideoOnce(h.runId,h.options);await expect(fetchRunMedia(h.runId,'cache',{...h.options,client:{...h.client,binding:{...h.client.binding,id:'different'}}})).rejects.toThrow('original_authorization_required');expect(h.mock.requests.filter(r=>r.path.endsWith('/content'))).toHaveLength(0);}finally{await h.close();}});
it('T33: bounded response rejects over-budget header/stream and atomic quota failure leaves no orphan asset',async()=>{const h=await completed();try{await expect(fetchRunMedia(h.runId,'cache',{...h.options,cacheBudgetBytes:4})).rejects.toThrow('media_cache_budget_exceeded');const put=h.db.connection.transaction.bind(h.db.connection);vi.spyOn(h.db.connection,'transaction').mockImplementation((...args:Parameters<IDBDatabase['transaction']>)=>{const tx=put(...args);if(args[1]==='readwrite'&&Array.isArray(args[0])&&args[0].includes('assets')){const original=tx.objectStore.bind(tx);vi.spyOn(tx,'objectStore').mockImplementation(name=>{const store=original(name);if(name==='blobs')vi.spyOn(store,'put').mockImplementation(()=>{throw new DOMException('injected quota','QuotaExceededError');});return store;});}return tx;});await expect(fetchRunMedia(h.runId,'cache',h.options)).rejects.toThrow('storage_quota_exceeded');const rows=await transact(h.db,['assets','blobs'],'readonly',async tx=>({assets:await requestResult(tx.objectStore('assets').getAll()),blobs:await requestResult(tx.objectStore('blobs').getAll())}));expect(rows.assets).toEqual([]);expect(rows.blobs).toEqual([]);expect((await readRun(h.runId,h.db))?.executionState).toBe('succeeded');}finally{vi.restoreAllMocks();await h.close();}});
it('T33-C06: object URL explicitly released once, even when the owning component cleans up twice',()=>{const revoke=vi.spyOn(URL,'revokeObjectURL'),url=acquireMediaUrl(new Blob(['local-only']));expect(url.objectUrl).toMatch(/^blob:/);url.release();url.release();expect(revoke).toHaveBeenCalledTimes(1);revoke.mockRestore();});
it('T33-C07: missing local file is a failed download trigger, never a saved-to-Downloads state',async()=>{const h=await completed();try{expect(await triggerBrowserDownload('missing',{db:h.db})).toEqual({status:'failed'});}finally{await h.close();}});
it('T33: streamed content without length is counted; simultaneous native DB claims allow only one content GET',async()=>{const h=await completed();try{h.mock.faults.streamContent=true;await expect(fetchRunMedia(h.runId,'cache',{...h.options,cacheBudgetBytes:5})).rejects.toThrow('media_cache_budget_exceeded');const count=h.mock.requests.filter(r=>r.path.endsWith('/content')).length,results=await Promise.allSettled([fetchRunMedia(h.runId,'cache',h.options),fetchRunMedia(h.runId,'cache',h.options)]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.filter(r=>r.status==='rejected')).toHaveLength(1);expect(h.mock.requests.filter(r=>r.path.endsWith('/content'))).toHaveLength(count+1);expect(h.mock.taskCount()).toBe(1);}finally{await h.close();}});
it('T33: corrupted cached bytes are not shown as verified offline media or silently re-fetched',async()=>{const h=await completed();try{const cache=await fetchRunMedia(h.runId,'cache',h.options);await transact(h.db,['blobs'],'readwrite',tx=>tx.objectStore('blobs').put({id:cache.blobKey,blob:new Blob(['corrupt'])}));const count=h.mock.requests.length;await expect(fetchRunMedia(h.runId,'preview',h.options)).rejects.toThrow('media_cached_integrity_failed');expect(h.mock.requests).toHaveLength(count);}finally{await h.close();}});
