import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {IDBObjectStore} from 'fake-indexeddb';
import {videoHarness} from '../helpers/video-harness';
import {f} from '../helpers/fixtures';
import {saveDraft,readDraft} from '../../src/features/prompt-generation/draft-repository';
import {preparePromptOptimization,optimizePrompt} from '../../src/application/prompts/optimize-text';
import {parsePromptResponse,attachPromptRunResult} from '../../src/adapters/core/prompt-result-parser';
import {transact,requestResult} from '../../src/infrastructure/storage/database';
let h:Awaited<ReturnType<typeof videoHarness>>;
beforeEach(async()=>{h=await videoHarness();await saveDraft(f.draft({revision:0,sceneId:'product',userRequest:'品牌：康济健葆，5秒、9:16',requestedSpec:{durationSeconds:5,ratio:'9:16'},lockedConstraints:[{id:'brand',field:'brand',originalValue:'康济健葆',locked:true},{id:'dialogue',field:'dialogue',originalValue:'你好世界',locked:true}]}),0,{db:h.db});});afterEach(async()=>{vi.restoreAllMocks();await h.close();});
async function response(content=JSON.stringify(f.promptResult({finalPrompt:'另一品牌',suggestedSpec:{durationSeconds:5,ratio:'9:16'}}))){h.mock.faults.chatContent=content;const preview=await preparePromptOptimization('d1',{textModelId:'fake-text-only',referenceAliases:[]},h.options),run=await optimizePrompt({preview,decision:{confirmed:true,acknowledgeTextFee:true}},h.options);return {run,parsed:parsePromptResponse(content)};}
it('T31: late native response attaches to its original revision without overwriting new input, brand/dialogue changes need review',async()=>{const {run,parsed}=await response();const draft=(await readDraft('d1',h.db))!;await saveDraft({...draft,userRequest:'新的创意'},1,{db:h.db});const candidate=await attachPromptRunResult(run.id,parsed,h.options);expect(candidate?.sourceRevision).toBe(1);expect(candidate?.validationState).toBe('needs_review');expect((await readDraft('d1',h.db))?.userRequest).toBe('新的创意');const diagnostic=await transact(h.db,['diagnostics'],'readonly',tx=>requestResult(tx.objectStore('diagnostics').get('prompt-parse:'+run.id)));expect(diagnostic.issues.map((i:{code:string})=>i.code)).toEqual(expect.arrayContaining(['locked_brand_changed','locked_dialogue_changed']));});
it('T31: invalid response keeps raw diagnostic and original draft without fabricating a successful candidate',async()=>{const raw='{bad <script>untrusted</script>',{run,parsed}=await response(raw);expect(await attachPromptRunResult(run.id,parsed,h.options)).toBeUndefined();expect((await readDraft('d1',h.db))?.resultVersions).toHaveLength(0);const diagnostic=await transact(h.db,['diagnostics'],'readonly',tx=>requestResult(tx.objectStore('diagnostics').get('prompt-parse:'+run.id)));expect(diagnostic.parsed.raw).toBe(raw);expect(h.mock.requests.filter(r=>r.path==='/v1/chat/completions')).toHaveLength(1);});
it('T31: candidate cannot be substituted for the original response journal',async()=>{const {run}=await response();await expect(attachPromptRunResult(run.id,parsePromptResponse(JSON.stringify(f.promptResult({finalPrompt:'伪造候选'}))),h.options)).rejects.toThrow('prompt_candidate_mismatch');expect((await readDraft('d1',h.db))?.resultVersions).toHaveLength(0);});
it('T31: result storage quota is atomic and retrying local parsing sends no new chat',async()=>{const {run,parsed}=await response(),original=IDBObjectStore.prototype.put;vi.spyOn(IDBObjectStore.prototype,'put').mockImplementation(function(this:IDBObjectStore,...args:Parameters<typeof original>){if(this.name==='promptDrafts')throw new DOMException('injected quota','QuotaExceededError');return original.apply(this,args);});await expect(attachPromptRunResult(run.id,parsed,h.options)).rejects.toThrow('injected quota');expect((await readDraft('d1',h.db))?.resultVersions).toHaveLength(0);expect(await transact(h.db,['diagnostics'],'readonly',tx=>requestResult(tx.objectStore('diagnostics').get('prompt-parse:'+run.id)))).toBeUndefined();vi.restoreAllMocks();await attachPromptRunResult(run.id,parsed,h.options);await attachPromptRunResult(run.id,parsed,h.options);expect((await readDraft('d1',h.db))?.resultVersions).toHaveLength(1);expect(h.mock.requests.filter(r=>r.path==='/v1/chat/completions')).toHaveLength(1);});
