import {it,expect,beforeEach,afterEach} from 'vitest';import {videoHarness} from '../helpers/video-harness';import {f} from '../helpers/fixtures';
import {transact,requestResult} from '../../src/infrastructure/storage/database';import {preflightRun,sealRunPlan} from '../../src/application/runs/preflight';import {approveRun} from '../../src/application/runs/approval';import {createRunQueue,withdrawQueueItem,readQueue,executeQueue} from '../../src/application/runs/queue';import {submitVideo} from '../../src/application/runs/submit-video';import type {Run} from '../../src/domain/run';
import {prepareVideoRequest} from '../../src/application/runs/prepare-request';import {claimRunDispatch} from '../../src/infrastructure/storage/run-lease';
let h:Awaited<ReturnType<typeof videoHarness>>;
beforeEach(async()=>{h=await videoHarness();});afterEach(async()=>h.close());
async function seed(){const graph=f.graph({nodes:[{id:'text',type:'text',title:'文本',x:0,y:0,locked:false,data:{kind:'text',text:'本地撤回用例',referenceTokens:[]}},{id:'shot',type:'video-generation',title:'镜头',x:400,y:0,locked:false,data:{kind:'video-generation',draft:h.capability.videoSpecs[0],inputBindings:[],stale:false}}],edges:[{id:'edge',sourceId:'text',targetId:'shot',port:'text',order:0}]});await transact(h.db,['graphs'],'readwrite',tx=>tx.objectStore('graphs').put(graph));const checked=preflightRun({graph,nodeIds:['shot'],assets:[],readableAssetIds:[],capability:h.capability,connection:h.client.profile,binding:h.client.binding,canWrite:true,credentialAvailable:true});if(checked.status!=='ready')throw Error('fixture_plan');const plan=await sealRunPlan(checked.plan),approved=await approveRun(plan,{confirmed:true,kind:'video',planHash:plan.planHash,nodeCount:1,acknowledgeUnknownFee:true},h.options),queue=await createRunQueue({projectId:'p1',revision:1,nodeIds:['shot'],approved},h.options);return{queue,runId:approved.runIds[0]};}
const run=(id:string)=>transact(h.db,['runs'],'readonly',tx=>requestResult<Run>(tx.objectStore('runs').get(id)));
const posts=()=>h.mock.requests.filter(r=>r.method==='POST'&&r.path==='/v1/videos/generations').length;
it('T44 J06 unsent withdrawal retains original Run, approval and billing evidence but permanently prevents this attempt from POST',async()=>{const {queue,runId}=await seed(),before=await run(runId),count=posts();const after=await withdrawQueueItem(queue.queueId,'shot',{confirmed:true,epoch:queue.epoch},h.options);expect(after.items[0].status).toBe('withdrawn');expect(await run(runId)).toEqual(before);await expect(submitVideo(runId,h.options)).rejects.toThrow('run_locally_withdrawn');await expect(executeQueue(queue.queueId,h.options)).rejects.toThrow('queue_confirmation_required');expect(posts()).toBe(count);});
it('T44 J06 changed queue and already dispatched/unknown attempts cannot be locally removed',async()=>{const {queue,runId}=await seed();await expect(withdrawQueueItem(queue.queueId,'shot',{confirmed:true,epoch:queue.epoch+1},h.options)).rejects.toThrow('queue_changed');await transact(h.db,['runs'],'readwrite',async tx=>{const row=await requestResult<Run>(tx.objectStore('runs').get(runId));tx.objectStore('runs').put({...row,executionState:'submit_unknown'});});const before=await run(runId);await expect(withdrawQueueItem(queue.queueId,'shot',{confirmed:true,epoch:queue.epoch},h.options)).rejects.toThrow('queue_item_already_started');expect(await run(runId)).toEqual(before);expect((await readQueue(queue.queueId,h.options)).items[0].status).toBe('ready');});
it('T44 J06 a prepared but unsent withdrawal also fences the shared native dispatch claim',async()=>{const {queue,runId}=await seed();await prepareVideoRequest(runId,h.options);const before=await run(runId);await withdrawQueueItem(queue.queueId,'shot',{confirmed:true,epoch:queue.epoch},h.options);expect(await claimRunDispatch(runId,h.options.lease.tabId,{db:h.db})).toEqual({ok:false,errorCode:'run_locally_withdrawn'});expect(await run(runId)).toEqual(before);});
