import {it,expect,beforeEach,afterEach,vi} from 'vitest';
import {IDBFactory,IDBObjectStore} from 'fake-indexeddb';
import {openStudioDb,transact,requestResult,type StudioDb} from '../../src/infrastructure/storage/database';
import {acquireProjectLease,type ProjectLeaseToken} from '../../src/infrastructure/storage/project-lease';
import {preflightRun,sealRunPlan,planFingerprint,type RunPlan} from '../../src/application/runs/preflight';
import {approveRun,type ConfirmDecision} from '../../src/application/runs/approval';
import {createCoreClient,type CoreClient} from '../../src/adapters/core/http-client';
import {createAuthBinding} from '../../src/domain/authorization';
import {setSessionCredential,withCredential} from '../../src/security/credential-session';
import {f} from '../helpers/fixtures';
let db:StudioDb,lease:ProjectLeaseToken,plan:RunPlan,client:CoreClient;
const spec={modelId:'fake-video-only',durationSeconds:5,ratio:'9:16'},capability=f.caps({videoSpecs:[spec],limits:{promptBytes:65536,imageReferences:0,videoReferences:0}});
const options=()=>({db,lease,client,capability});
const decision=():ConfirmDecision=>({confirmed:true,kind:'video',planHash:plan.planHash,nodeCount:1,acknowledgeUnknownFee:true});
const counts=()=>transact(db,['runs','receipts'],'readonly',async tx=>({runs:await requestResult(tx.objectStore('runs').count()),approvals:(await requestResult<{id:string}[]>(tx.objectStore('receipts').getAll())).filter(r=>r.id.startsWith('approval:')).length}));
beforeEach(async()=>{
 db=await openStudioDb({factory:new IDBFactory(),name:'run-approval'});const graph=f.graph({nodes:[{id:'t1',type:'text',title:'文字',x:0,y:0,locked:false,data:{kind:'text',text:'原创批准正文',referenceTokens:[]}},{id:'v1',type:'video-generation',title:'视频',x:400,y:0,locked:false,data:{kind:'video-generation',draft:spec,inputBindings:[],stale:false}}],edges:[{id:'e1',sourceId:'t1',targetId:'v1',port:'text',order:0}]});
 await transact(db,['projects','graphs','diagnostics'],'readwrite',tx=>{tx.objectStore('projects').put(f.project());tx.objectStore('graphs').put(graph);tx.objectStore('diagnostics').put({id:'capability:current',capability});});
 const claimed=await acquireProjectLease('p1','approve-tab',Date.now(),{db});if(!claimed.ok)throw Error('test lease');lease=claimed.token;
 const profile=f.connection(),binding=createAuthBinding(profile);setSessionCredential(binding.id,'fake-approval-key');client=createCoreClient(profile,{binding,withCredential},{registry:[profile],browserOrigin:'http://127.0.0.1:4179'});
 const checked=preflightRun({graph,nodeIds:['v1'],assets:[],readableAssetIds:[],capability,connection:profile,binding,canWrite:true,credentialAvailable:true});if(checked.status!=='ready')throw Error('test plan');plan=await sealRunPlan(checked.plan);
});
afterEach(()=>{vi.restoreAllMocks();db.close();});
it('T26: simultaneous approval creates a single immutable Run and unique persisted idempotency key',async()=>{const results=await Promise.allSettled([approveRun(plan,decision(),options()),approveRun(plan,decision(),options())]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(await counts()).toEqual({runs:1,approvals:1});const rows=await transact(db,['runs'],'readonly',tx=>requestResult(tx.objectStore('runs').getAll()));expect(rows[0].idempotencyKey).toMatch(/^studio-video-/);expect(rows[0].authBindingId).toBe(plan.binding.id);expect(rows[0].finalBody).toBeUndefined();});
it('T26: changed plan body fails its fingerprint without creating records',async()=>{const altered=structuredClone(plan);altered.nodes[0].inputSnapshot.prompt='未显示的改写';await expect(approveRun(altered,decision(),options())).rejects.toThrow('plan_hash_mismatch');expect(await counts()).toEqual({runs:0,approvals:0});});
it('T26: node count and fee acknowledgment must match the exact confirmation',async()=>{await expect(approveRun(plan,{...decision(),nodeCount:2},options())).rejects.toThrow('confirmation_mismatch');expect(await counts()).toEqual({runs:0,approvals:0});});
it('T26: expired approval cannot be extended by resuming a saved dialog',async()=>{const expired={...plan,expiresAt:1};expired.planHash=await planFingerprint(expired);await expect(approveRun(expired,{...decision(),planHash:expired.planHash},options())).rejects.toThrow('approval_expired');expect(await counts()).toEqual({runs:0,approvals:0});});
it('T26: lease takeover denies old approval atomically',async()=>{await acquireProjectLease('p1','other-tab',Date.now(),{db,force:true});await expect(approveRun(plan,decision(),options())).rejects.toThrow('lease_epoch_invalid');expect(await counts()).toEqual({runs:0,approvals:0});});
it('T26: changed current capability invalidates the exact reviewed specifications',async()=>{await transact(db,['diagnostics'],'readwrite',tx=>tx.objectStore('diagnostics').put({id:'capability:current',capability:f.unknownCaps()}));await expect(approveRun(plan,decision(),options())).rejects.toThrow('capability_changed');expect(await counts()).toEqual({runs:0,approvals:0});});
it('T26: quota fault rolls back all approval records and Runs',async()=>{const original=IDBObjectStore.prototype.put;vi.spyOn(IDBObjectStore.prototype,'put').mockImplementation(function(this:IDBObjectStore,...args:Parameters<typeof original>){if(this.name==='runs')throw new DOMException('injected quota','QuotaExceededError');return original.apply(this,args);});await expect(approveRun(plan,decision(),options())).rejects.toThrow('storage_quota_exceeded');expect(await counts()).toEqual({runs:0,approvals:0});});
it('T26: a dirty in-memory edit revokes the approval before any storage side effect',async()=>{await expect(approveRun(plan,decision(),{...options(),isCurrent:()=>false})).rejects.toThrow('approval_expired');expect(await counts()).toEqual({runs:0,approvals:0});});
