import {it,expect,beforeEach,afterEach} from 'vitest';
import {videoHarness} from '../helpers/video-harness';
import {f} from '../helpers/fixtures';
import {planGraphRuns} from '../../src/application/runs/graph-plan';
import {createRunQueue,executeQueue,restoreQueue,pauseQueue,resumeQueue,readQueue} from '../../src/application/runs/queue';
import {createCoreClient} from '../../src/adapters/core/http-client';
import {withCredential} from '../../src/security/credential-session';
import {transact} from '../../src/infrastructure/storage/database';
import {preflightRun,sealRunPlan} from '../../src/application/runs/preflight';
import {approveRun} from '../../src/application/runs/approval';
import {pollVideoOnce} from '../../src/application/runs/poll-video';
import type {Graph} from '../../src/domain/graph';
let h:Awaited<ReturnType<typeof videoHarness>>;
function shots():Graph{return f.graph({nodes:[1,2,3].flatMap(n=>[{id:'text-'+n,type:'text' as const,title:'镜头正文'+n,x:0,y:n*100,locked:false,data:{kind:'text' as const,text:'原创镜头'+n,referenceTokens:[]}},{id:'shot-'+n,type:'video-generation' as const,title:'镜头'+n,x:400,y:n*100,locked:false,data:{kind:'video-generation' as const,draft:h.capability.videoSpecs[0],inputBindings:[],stale:false}}]),edges:[1,2,3].map(n=>({id:'edge-'+n,sourceId:'text-'+n,targetId:'shot-'+n,port:'text',order:0}))});}
async function approvedShots(nodeIds=['shot-1','shot-2','shot-3']){const graph=shots();await transact(h.db,['graphs'],'readwrite',tx=>tx.objectStore('graphs').put(graph));const checked=preflightRun({graph,nodeIds,assets:[],readableAssetIds:[],capability:h.capability,connection:h.client.profile,binding:h.client.binding,canWrite:true,credentialAvailable:true});if(checked.status!=='ready')throw Error('test plan');const plan=await sealRunPlan(checked.plan);return approveRun(plan,{confirmed:true,kind:'video',planHash:plan.planHash,nodeCount:nodeIds.length,acknowledgeUnknownFee:true},h.options);}
const posts=()=>h.mock.requests.filter(r=>r.method==='POST'&&r.path==='/v1/videos/generations');
beforeEach(async()=>{h=await videoHarness();});afterEach(async()=>{await h.close();});
it('T29-C04: selecting only the second shot never expands to the other shots or group media',()=>{const result=planGraphRuns(shots(),['shot-2']);expect(result.ok).toBe(true);if(result.ok)expect(result.value.map(p=>p.nodeId)).toEqual(['shot-2']);});
it('T29-C01: preparation concurrency defaults to one and values above three are rejected',async()=>{const approved=await approvedShots();const queue=await createRunQueue({projectId:'p1',revision:1,nodeIds:['shot-1','shot-2','shot-3'],approved},h.options);expect(queue.preparationConcurrency).toBe(1);await expect(createRunQueue({projectId:'p1',revision:1,nodeIds:['shot-1'],preparationConcurrency:4},h.options)).rejects.toThrow('queue_concurrency_invalid');expect(posts()).toHaveLength(1);});
it('T29-C02: pausing prevents pending sends and never cancels the already accepted task',async()=>{const approved=await approvedShots(),queue=await createRunQueue({projectId:'p1',revision:1,nodeIds:['shot-1','shot-2','shot-3'],approved},h.options);const paused=await pauseQueue(queue.queueId,h.options);expect(paused.state).toBe('paused');await expect(executeQueue(queue.queueId,h.options)).rejects.toThrow('queue_confirmation_required');expect(posts()).toHaveLength(1);expect(h.mock.requests.some(r=>r.path.includes('/cancel'))).toBe(false);});
it('T29-C03: refreshing a saved ready queue pauses it and never resumes pending submissions',async()=>{const approved=await approvedShots(),queue=await createRunQueue({projectId:'p1',revision:1,nodeIds:['shot-1','shot-2','shot-3'],approved},h.options);const restored=await restoreQueue(queue.queueId,h.options);expect(restored.state).toBe('paused');expect(restored.items.every(i=>i.status==='ready')).toBe(true);expect(posts()).toHaveLength(1);await expect(executeQueue(queue.queueId,h.options)).rejects.toThrow('queue_confirmation_required');});
it('T29-C05: failed original upstream blocks the downstream draft rather than automatically choosing new media',async()=>{h.mock.faults.queryStatus='failed';await pollVideoOnce(h.runId,h.options);const graph=shots();graph.nodes.push({id:'fixed-parent',type:'result',title:'原上游',x:0,y:0,locked:false,data:{kind:'result',runId:h.runId,assetId:'missing-original-result'}});graph.edges.push({id:'dependency',sourceId:'fixed-parent',targetId:'shot-2',port:'video',order:1});await transact(h.db,['graphs'],'readwrite',tx=>tx.objectStore('graphs').put(graph));const queue=await createRunQueue({projectId:'p1',revision:1,nodeIds:['shot-2']},h.options);expect(queue.items[0].status).toBe('blocked');expect(queue.items[0].errorCode).toBe('upstream_failed');expect(posts()).toHaveLength(1);});
it('T29-C06: changed graph revision invalidates the pending approval before the first queue video POST',async()=>{const approved=await approvedShots(['shot-2']),queue=await createRunQueue({projectId:'p1',revision:1,nodeIds:['shot-2'],approved},h.options);await transact(h.db,['projects','graphs'],'readwrite',tx=>{tx.objectStore('projects').put(f.project({revision:2}));tx.objectStore('graphs').put({...shots(),revision:2});});await expect(executeQueue(queue.queueId,h.options)).rejects.toThrow('queue_revision_changed');expect(posts()).toHaveLength(1);});
it('T29: three approved preparations use the same original approval, at most three in flight',async()=>{
 const approved=await approvedShots(),queue=await createRunQueue({projectId:'p1',revision:1,nodeIds:['shot-1','shot-2','shot-3'],approved,preparationConcurrency:3},h.options);let active=0,max=0;
 const client=createCoreClient(h.client.profile,{binding:h.client.binding,withCredential},{registry:[h.client.profile],browserOrigin:'http://127.0.0.1:4179',fetch:async(url,init)=>{active++;max=Math.max(max,active);try{const response=await fetch(h.mock.origin+new URL(String(url)).pathname.replace(/^\/core-api/,''),init);await new Promise(r=>setTimeout(r,30));return response;}finally{active--;}}});
 const done=await executeQueue(queue.queueId,{...h.options,client});expect(done.items.map(i=>i.status)).toEqual(['accepted','accepted','accepted']);expect(done.state).toBe('completed');expect(posts()).toHaveLength(4);expect(max).toBe(3);
});
it('T29: resume requires a fresh explicit approval for just the pending shots',async()=>{const approved=await approvedShots(['shot-2']),queue=await createRunQueue({projectId:'p1',revision:1,nodeIds:['shot-2'],approved},h.options);await pauseQueue(queue.queueId,h.options);await expect(resumeQueue(queue.queueId,{queueId:queue.queueId,planHashes:[approved.planHash],revision:1,explicitDecision:true,approvedRun:approved},h.options)).rejects.toThrow('queue_confirmation_required');const fresh=await approvedShots(['shot-2']);await resumeQueue(queue.queueId,{queueId:queue.queueId,planHashes:[fresh.planHash],revision:1,explicitDecision:true,approvedRun:fresh},h.options);const resumed=await readQueue(queue.queueId,h.options);expect(resumed.supersededRunIds).toEqual(approved.runIds);expect(posts()).toHaveLength(1);await executeQueue(queue.queueId,h.options);expect(posts()).toHaveLength(2);expect(posts()[1].idempotencyKey).not.toBe(h.run.idempotencyKey);});
it('T29: pause during the first response blocks further pending POSTs without cancelling that response',async()=>{const approved=await approvedShots(),queue=await createRunQueue({projectId:'p1',revision:1,nodeIds:['shot-1','shot-2','shot-3'],approved},h.options);const client=createCoreClient(h.client.profile,{binding:h.client.binding,withCredential},{registry:[h.client.profile],browserOrigin:'http://127.0.0.1:4179',fetch:async(url,init)=>{const response=await fetch(h.mock.origin+new URL(String(url)).pathname.replace(/^\/core-api/,''),init);await pauseQueue(queue.queueId,h.options);return response;}});const result=await executeQueue(queue.queueId,{...h.options,client});expect(result.state).toBe('paused');expect(posts()).toHaveLength(2);const restored=await restoreQueue(queue.queueId,h.options);expect(restored.items.filter(i=>i.status==='accepted')).toHaveLength(1);expect(h.mock.requests.some(r=>r.path.includes('/cancel'))).toBe(false);});
it('T29: graph change while a queue activates leaves a durable paused queue and sends nothing',async()=>{const approved=await approvedShots(['shot-2']),queue=await createRunQueue({projectId:'p1',revision:1,nodeIds:['shot-2'],approved},h.options);await expect(executeQueue(queue.queueId,{...h.options,onUpdate:async q=>{if(q.state==='active')await transact(h.db,['projects','graphs'],'readwrite',tx=>{tx.objectStore('projects').put(f.project({revision:2}));tx.objectStore('graphs').put({...shots(),revision:2});});}})).rejects.toThrow('queue_revision_changed');expect((await readQueue(queue.queueId,h.options)).state).toBe('paused');expect(posts()).toHaveLength(1);});
it('T29: default preparation is actually sequential, not just a stored setting',async()=>{const approved=await approvedShots(),queue=await createRunQueue({projectId:'p1',revision:1,nodeIds:['shot-1','shot-2','shot-3'],approved},h.options);let active=0,max=0;const client=createCoreClient(h.client.profile,{binding:h.client.binding,withCredential},{registry:[h.client.profile],browserOrigin:'http://127.0.0.1:4179',fetch:async(url,init)=>{active++;max=Math.max(max,active);try{const response=await fetch(h.mock.origin+new URL(String(url)).pathname.replace(/^\/core-api/,''),init);await new Promise(r=>setTimeout(r,5));return response;}finally{active--;}}});expect((await executeQueue(queue.queueId,{...h.options,client})).state).toBe('completed');expect(max).toBe(1);expect(posts()).toHaveLength(4);});
it('T29: unknown first response pauses later shots and preserves the original unknown request',async()=>{const approved=await approvedShots(),queue=await createRunQueue({projectId:'p1',revision:1,nodeIds:['shot-1','shot-2','shot-3'],approved},h.options);h.mock.faults.loseSubmitResponse=true;const result=await executeQueue(queue.queueId,h.options);expect(result.state).toBe('paused');expect(result.items.map(i=>i.status)).toEqual(['submit_unknown','ready','ready']);expect(posts()).toHaveLength(2);await expect(executeQueue(queue.queueId,h.options)).rejects.toThrow('queue_confirmation_required');expect(posts()).toHaveLength(2);});
