import {it,expect} from 'vitest';
import {getVideoWork,parseVideoWork} from '../../src/adapters/core/video-works';
import {prepareWorkRevision,type WorkRevisionInput} from '../../src/application/runs/work-context';
import {videoHarness} from '../helpers/video-harness';
import {f} from '../helpers/fixtures';
import {parseVideoTask} from '../../src/adapters/core/contracts';
import {observeVideoTask} from '../../src/domain/video-run-machine';
import {applyQueryObservation} from '../../src/domain/run-status';
const fixture={work_id:'work-1',versions:[{version_id:'version-1',work_id:'work-1',operation_request_id:'mock-core-1',ordinal:1,action:'create',state:'completed',parent_version_id:null,created_at_ms:1000,updated_at_ms:2000,deleted_at_ms:null}],created_at_ms:1000,updated_at_ms:2000};
async function harness(){const h=await videoHarness();const input:WorkRevisionInput={action:'continue',workId:'work-1',baseVersionId:'version-1',sourceRun:{...h.run,resultAssetId:'a1',requestedSpec:{modelId:'fake-video-only',durationSeconds:5,ratio:'9:16'}},sourceAsset:f.asset({id:'a1',sourceRunId:h.runId,mediaType:'video'}),work:{workId:'work-1',versions:[{versionId:'version-1',workId:'work-1',operationRequestId:h.run.coreRequestId!,state:'completed'}]},prompt:'继续走向远处',client:h.client,capability:{...h.capability,workContext:true,continuation:true}};return {...h,input};}
it('T32-C01: disabled continuation fails closed with no fallback paid submission',async()=>{const h=await harness();try{await expect(prepareWorkRevision({...h.input,capability:{...h.input.capability,continuation:false}})).rejects.toThrow('continuation_disabled');expect(h.mock.requests.filter(r=>r.method==='POST')).toHaveLength(1);}finally{await h.close();}});
it('T32-C05: different original binding is refused before any work query or paid call',async()=>{const h=await harness();try{await expect(getVideoWork('work-1',{connectionId:'c1',authBindingId:'different',originSnapshot:h.client.profile.originSnapshot},{client:h.client})).rejects.toThrow('original_authorization_required');expect(h.mock.requests).toHaveLength(1);}finally{await h.close();}});
it('T32-C02: genuine HTTP 404 cannot fall back to a normal generation',async()=>{const h=await harness();try{await expect(getVideoWork('work-1',h.input.sourceRun,{client:h.client})).rejects.toThrow('work_context_unavailable');expect(h.mock.requests.map(r=>r.method)).toEqual(['POST','GET']);}finally{await h.close();}});
it('T32: fixed-source parent fixture is read through the actual original-authorized HTTP route, without a paid call',async()=>{const h=await harness();try{h.mock.faults.workResponse=fixture;const work=await getVideoWork('work-1',h.input.sourceRun,{client:h.client});expect(work.versions[0].operationRequestId).toBe(h.run.coreRequestId);expect(h.mock.requests.map(r=>[r.method,r.path])).toEqual([['POST','/v1/videos/generations'],['GET','/v1/video-works/work-1']]);h.mock.faults.workResponse={...fixture,versions:[fixture.versions[0],fixture.versions[0]]};await expect(getVideoWork('work-1',h.input.sourceRun,{client:h.client})).rejects.toThrow('video_work_protocol_invalid');expect(h.mock.taskCount()).toBe(1);}finally{await h.close();}});
it('T32: fixed source fields are projected; URLs, ownership and sealed snapshots never enter local version view',()=>{const value=parseVideoWork({...fixture,apiKey:'do-not-store',download_url:'https://unknown.invalid',versions:[{...fixture.versions[0],sealed_snapshot:{ciphertext:[1,2,3]},owner_key_id:'private'}]},'work-1');expect(value.workId).toBe('work-1');expect(value.versions[0]).toMatchObject({versionId:'version-1',operationRequestId:'mock-core-1',state:'completed'});expect(JSON.stringify(value)).not.toMatch(/do-not-store|ciphertext|unknown.invalid|private/);expect(()=>parseVideoWork({...fixture,versions:[{...fixture.versions[0],work_id:'another'}]},'work-1')).toThrow('video_work_protocol_invalid');});
it('T32-C02: parent version belongs to the fixed source Run and asset, never latest work by key',async()=>{const h=await harness();try{await expect(prepareWorkRevision({...h.input,sourceAsset:{...h.input.sourceAsset,sourceRunId:'different'}})).rejects.toThrow('work_source_binding_mismatch');await expect(prepareWorkRevision({...h.input,work:{...h.input.work,versions:[]}})).rejects.toThrow('work_parent_unavailable');expect(h.mock.taskCount()).toBe(1);}finally{await h.close();}});
it('T32-C03/C04/C06: a readable completed identity without a proven parent spec cannot authorize regeneration or stitching',async()=>{const h=await harness();try{await expect(prepareWorkRevision(h.input)).rejects.toThrow('work_parent_spec_unverified');await expect(prepareWorkRevision({...h.input,action:'revise'})).rejects.toThrow('work_parent_spec_unverified');expect(h.mock.taskCount()).toBe(1);}finally{await h.close();}});
it('T32: parsed original work identity is saved separately from task ID; handles and URLs are excluded and changed work rejected',()=>{const task=parseVideoTask({task:{id:'task-1',status:'completed'},request_id:'operation-1',work_context:{work_id:'work-1',base_version_id:'version-1',context_handle:'private-handle',download_url:'https://unknown.invalid'}});const observed=observeVideoTask(f.run({executionState:'accepted'}),task);expect(observed.workContext).toEqual({workId:'work-1',baseVersionId:'version-1'});expect(observed.taskId).toBe('task-1');expect(JSON.stringify(observed)).not.toContain('private-handle');expect(()=>observeVideoTask({...observed,executionState:'running'},{...task,workContext:{workId:'different'}})).toThrow('video_work_identity_frozen');});
it('T32: original completed query can discover work version without changing billing or submission request ID',()=>{const run=f.run({taskId:'task-1',coreRequestId:'operation-1',executionState:'running'}),task=parseVideoTask({task:{id:'task-1',status:'completed'},request_id:'query-transport',work_context:{work_id:'work-1',base_version_id:'version-1'}}),next=applyQueryObservation(run,{ok:true,value:task});expect(next.workContext).toEqual({workId:'work-1',baseVersionId:'version-1'});expect(next.coreRequestId).toBe('operation-1');expect(next.billingState).toBe('not_provided');});
