import {it,expect,beforeEach,afterEach,vi} from 'vitest';
import {videoHarness} from '../helpers/video-harness';
import {pollVideoOnce,pausePolling,resumePolling,startVideoPolling,readPollSummary,type PollScheduler} from '../../src/application/runs/poll-video';
import {nextPollDelay,parseRetryAfter} from '../../src/adapters/core/retry-policy';
import {classifyCoreError} from '../../src/adapters/core/contracts';
import {readRun} from '../../src/infrastructure/storage/run-repository';
import {transact,requestResult} from '../../src/infrastructure/storage/database';
import {IDBObjectStore} from 'fake-indexeddb';
import type {Run} from '../../src/domain/run';
import {forgetSessionCredential} from '../../src/security/credential-session';
let h:Awaited<ReturnType<typeof videoHarness>>;
const videoPosts=()=>h.mock.requests.filter(r=>r.method==='POST'&&r.path==='/v1/videos/generations');
beforeEach(async()=>{h=await videoHarness();});afterEach(async()=>{vi.restoreAllMocks();await h.close();});
it('T28-C01: persistent pause only stops queries, preserving execution, delivery, billing and original key',async()=>{await pausePolling(h.runId,h.options);const saved=(await readRun(h.runId,h.db))!;expect(saved.queryState).toBe('paused_by_user');expect(saved.executionState).toBe(h.run.executionState);expect(saved.billingState).toBe(h.run.billingState);expect(saved.deliveryState).toBe(h.run.deliveryState);expect(saved.idempotencyKey).toBe(h.run.idempotencyKey);await pollVideoOnce(h.runId,h.options);expect(h.mock.requests.filter(r=>r.method==='GET')).toHaveLength(0);expect(videoPosts()).toHaveLength(1);});
it('T28-C02: 401 requires original authorization while the remote execution stays accepted',async()=>{h.mock.faults.statusErrorOnce=401;const run=await pollVideoOnce(h.runId,h.options);expect(run.queryState).toBe('auth_required');expect(run.executionState).toBe('accepted');expect(run.taskId).toBe(h.run.taskId);expect(videoPosts()).toHaveLength(1);});
it('T28-C03: 404 means inaccessible query, never free/cancelled/deleted generation',async()=>{h.mock.faults.statusErrorOnce=404;const run=await pollVideoOnce(h.runId,h.options);expect(run.queryState).toBe('interrupted');expect(run.executionState).toBe('accepted');expect(run.billingState).toBe('not_provided');expect(videoPosts()).toHaveLength(1);});
it('T28-C04: Retry-After accepts seconds and HTTP-date; invalid and past values are bounded',()=>{const now=Date.UTC(2026,9,1,0,0,0);expect(parseRetryAfter('2.5',now)).toBe(2500);expect(parseRetryAfter('Thu, 01 Oct 2026 00:00:07 GMT',now)).toBe(7000);expect(parseRetryAfter('nonsense',now)).toBeUndefined();expect(parseRetryAfter('Thu, 01 Oct 2026 00:00:00 GMT',now)).toBe(0);const result=classifyCoreError(429,{error:{code:'bridge_workers_busy'}},new Date(Date.now()+6000).toUTCString());expect(result.retryAfterMs).toBeGreaterThan(4000);expect(result.retryAfterMs).toBeLessThanOrEqual(6000);});
it('T28-C05/C06: a 5xx query cannot erase previously confirmed success or imply billing settlement',async()=>{const completed=await pollVideoOnce(h.runId,h.options);expect(completed.executionState).toBe('succeeded');expect(completed.billingState).toBe('not_provided');h.mock.faults.statusErrorOnce=503;const failed=await pollVideoOnce(h.runId,h.options);expect(failed.executionState).toBe('succeeded');expect(failed.queryState).toBe('interrupted');expect(failed.billingState).toBe('not_provided');expect(videoPosts()).toHaveLength(1);});
it('T28: normal 3s polling, 2/4/8/16/30s jittered backoff, Retry-After priority and hidden throttling',()=>{expect(nextPollDelay({ok:true},0)).toBe(3000);expect([0,1,2,3,4,100].map(n=>nextPollDelay({ok:false,random:()=>.5},n))).toEqual([2000,4000,8000,16000,30000,30000]);expect(nextPollDelay({ok:false,retryAfterMs:6500},4)).toBe(6500);expect(nextPollDelay({ok:true,hidden:true},0)).toBeGreaterThanOrEqual(15000);expect(nextPollDelay({ok:false,random:()=>1},4)).toBeLessThanOrEqual(30000);});
it('T28: explicit resume saves polling intent without a video POST; next query is only GET',async()=>{await pausePolling(h.runId,h.options);const resumed=await resumePolling(h.runId,h.options);expect(resumed.queryState).toBe('polling');expect(h.mock.requests.filter(r=>r.method==='GET')).toHaveLength(0);await pollVideoOnce(h.runId,h.options);expect(h.mock.requests.filter(r=>r.method==='GET')).toHaveLength(1);expect(videoPosts()).toHaveLength(1);});
it('T28: unfamiliar upstream state cannot regress a confirmed running execution',async()=>{await transact(h.db,['runs'],'readwrite',async tx=>{const run=await requestResult(tx.objectStore('runs').get(h.runId));tx.objectStore('runs').put({...run,executionState:'running'});});h.mock.faults.queryStatus='constructor';const next=await pollVideoOnce(h.runId,h.options);expect(next.executionState).toBe('running');expect(next.queryState).toBe('interrupted');expect(next.billingState).toBe('not_provided');});
it('T28: a real polling loop changes hidden frequency and stops on persistent pause without new POST',async()=>{const scheduled:{action:()=>Promise<void>;delay:number}[]=[],cleared:unknown[]=[],scheduler:PollScheduler={set:(action,delay)=>{scheduled.push({action,delay});return scheduled.length;},clear:id=>cleared.push(id)};let foreground=true;h.mock.faults.queryStatus='processing';const loop=startVideoPolling(h.runId,{...h.options,scheduler,isForeground:()=>foreground});expect(scheduled[0].delay).toBe(3000);await scheduled[0].action();expect(scheduled.at(-1)?.delay).toBe(3000);foreground=false;await scheduled.at(-1)!.action();expect(scheduled.at(-1)?.delay).toBeGreaterThanOrEqual(15000);await pausePolling(h.runId,h.options);const count=scheduled.length;await scheduled.at(-1)!.action();expect(scheduled).toHaveLength(count);expect(h.mock.requests.filter(r=>r.method==='GET')).toHaveLength(2);expect(videoPosts()).toHaveLength(1);loop.stop();});
it('T28: completed polling terminates rather than scheduling another GET',async()=>{const scheduled:{action:()=>Promise<void>;delay:number}[]=[],scheduler:PollScheduler={set:(action,delay)=>{scheduled.push({action,delay});return scheduled.length;},clear:()=>{}};const updates:string[]=[],loop=startVideoPolling(h.runId,{...h.options,scheduler,onUpdate:run=>{updates.push(run.executionState);}});await scheduled[0].action();expect(updates).toEqual(['succeeded']);expect(scheduled).toHaveLength(1);expect(h.mock.requests.filter(r=>r.method==='GET')).toHaveLength(1);loop.stop();});
it('T28: an actual 429 HTTP Retry-After header sets the loop delay and safe diagnostic summary',async()=>{h.mock.faults.statusErrorOnce=429;h.mock.faults.statusRetryAfter='6';const scheduled:{action:()=>Promise<void>;delay:number}[]=[],loop=startVideoPolling(h.runId,{...h.options,scheduler:{set:(action,delay)=>{scheduled.push({action,delay});return scheduled.length;},clear:()=>{}}});try{await scheduled[0].action();expect(scheduled[1].delay).toBe(6000);expect(await readPollSummary(h.runId,h.db)).toMatchObject({ok:false,httpStatus:429,errorCode:'bridge_workers_busy',retryAfterMs:6000});expect(videoPosts()).toHaveLength(1);}finally{loop.stop();}});
it('T28: pause during an in-flight GET wins over its late real HTTP completion',async()=>{let entered!:()=>void,release!:()=>void;const started=new Promise<void>(r=>{entered=r;}),gate=new Promise<void>(r=>{release=r;}),original=h.client.queryVideo,slow={...h.client,queryVideo:async(...args:Parameters<typeof original>)=>{const reply=await original(...args);entered();await gate;return reply;}};const pending=pollVideoOnce(h.runId,{...h.options,client:slow});await started;await pausePolling(h.runId,h.options);release();const late=await pending;expect(late.queryState).toBe('paused_by_user');expect((await readRun(h.runId,h.db))?.queryState).toBe('paused_by_user');expect((await readRun(h.runId,h.db))?.executionState).toBe('accepted');expect(videoPosts()).toHaveLength(1);});
it('T28: an active persisted query fence denies another GET even when the caller has tracking ownership',async()=>{await transact(h.db,['leases'],'readwrite',tx=>tx.objectStore('leases').put({id:'poll:'+h.runId,owner:'other-document',expiresAt:Date.now()+30000}));await expect(pollVideoOnce(h.runId,h.options)).rejects.toThrow('run_query_busy');expect(h.mock.requests.filter(r=>r.method==='GET')).toHaveLength(0);expect(videoPosts()).toHaveLength(1);});
it('T28: query save quota failure keeps original execution and only retries the GET after storage recovers',async()=>{const original=IDBObjectStore.prototype.put,fault=vi.spyOn(IDBObjectStore.prototype,'put').mockImplementation(function(this:IDBObjectStore,...args:Parameters<typeof original>){if(this.name==='runs'&&(args[0] as Run).executionState==='succeeded')throw new DOMException('injected query save quota','QuotaExceededError');return original.apply(this,args);});await expect(pollVideoOnce(h.runId,h.options)).rejects.toThrow('storage_quota_exceeded');expect((await readRun(h.runId,h.db))?.executionState).toBe('accepted');fault.mockRestore();expect((await pollVideoOnce(h.runId,h.options)).executionState).toBe('succeeded');expect(videoPosts()).toHaveLength(1);expect(h.mock.requests.filter(r=>r.method==='GET')).toHaveLength(2);});
it('T28: a forgotten ordinary Key becomes auth_required without contacting a different identity',async()=>{forgetSessionCredential(h.run.authBindingId);const run=await pollVideoOnce(h.runId,h.options);expect(run.queryState).toBe('auth_required');expect(run.executionState).toBe('accepted');expect(h.mock.requests.filter(r=>r.method==='GET')).toHaveLength(0);});
it.each(['aw_live_fake_terminal','constructor','unrecognized_provider_failure'])('QA042: unknown terminal code %s is not persisted or treated as a billing result',async code=>{const client={...h.client,queryVideo:async()=>({ok:true as const,value:{taskId:h.run.taskId!,status:'failed' as const,contentAvailable:false,billingState:'not_provided' as const,errorCode:code}})};const run=await pollVideoOnce(h.runId,{...h.options,client});expect(run).toMatchObject({executionState:'failed_confirmed',taskId:h.run.taskId,coreRequestId:h.run.coreRequestId,billingState:'not_provided',idempotencyKey:h.run.idempotencyKey});const summary=await readPollSummary(h.runId,h.db);expect(summary).toMatchObject({ok:true,errorCode:'video_failure_reason_unavailable'});expect(JSON.stringify(summary)).not.toContain(code);expect(videoPosts()).toHaveLength(1);});

it.each(['completed','failed'] as const)('QA58: %s execution keeps tracking pending billing and stops after final settlement without resubmitting',async status=>{
 const scheduled:{action:()=>Promise<void>;delay:number}[]=[],updates:Run[]=[];
 let reads=0;
 // Only the external read boundary is replaced. Real leases, transactions,
 // run state transitions and scheduling remain active.
 const client={...h.client,queryVideo:async()=>({ok:true as const,value:{taskId:h.run.taskId!,status,contentAvailable:status==='completed',billingState:reads++===0?'pending_reconciliation' as const:'settled' as const}})};
 const loop=startVideoPolling(h.runId,{...h.options,client,scheduler:{set:(action,delay)=>{scheduled.push({action,delay});return scheduled.length;},clear:()=>{}},onUpdate:run=>{updates.push(run);}});
 try{
  await scheduled[0].action();
  expect(updates[0]).toMatchObject({executionState:status==='completed'?'succeeded':'failed_confirmed',billingState:'pending_reconciliation'});
  expect(scheduled).toHaveLength(2);
  await scheduled[1].action();
  expect(updates[1]).toMatchObject({executionState:status==='completed'?'succeeded':'failed_confirmed',billingState:'settled'});
  expect(scheduled).toHaveLength(2);
  expect((await readRun(h.runId,h.db))?.idempotencyKey).toBe(h.run.idempotencyKey);
  expect(videoPosts()).toHaveLength(1);
 }finally{loop.stop();}
});
