import {IDBFactory} from 'fake-indexeddb';
import {startCompanion} from '../../companion/src/server';
import {registerTestMockOrigin} from './mock-network';
import {f} from './fixtures';
import {openStudioDb,transact,requestResult} from '../../src/infrastructure/storage/database';
import {acquireProjectLease,assertProjectWriter} from '../../src/infrastructure/storage/project-lease';
import {connectAgent,registerOpenedCanvas,authorizeAgent,disconnectAgent} from '../../src/features/agent/agent-client';
import type {Proposal} from '../../src/domain/proposal';
export async function agentHarness(){const db=await openStudioDb({factory:new IDBFactory(),name:'agent-harness-'+crypto.randomUUID()}),origin='http://127.0.0.1:4179',relay=await startCompanion({allowedOrigins:[origin]}),unregister=registerTestMockOrigin(relay.url);await transact(db,['projects','graphs','runs'],'readwrite',tx=>{tx.objectStore('projects').put(f.project());tx.objectStore('graphs').put(f.graph({nodes:[{id:'n1',type:'text',title:'允许节点',x:0,y:0,locked:false,data:{kind:'text',text:'原文字',referenceTokens:[]}},{id:'n2',type:'text',title:'未授权节点',x:400,y:0,locked:false,data:{kind:'text',text:'私人原稿',referenceTokens:[]}}]}));tx.objectStore('runs').put(f.run({executionState:'submit_unknown'}));});const acquired=await acquireProjectLease('p1','agent-tab',Date.now(),{db});if(!acquired.ok)throw Error(acquired.errorCode);const lease=acquired.token,release=registerOpenedCanvas({identity:async()=>{try{return await transact(db,['leases'],'readonly',async tx=>{await assertProjectWriter(tx,'p1',lease);return lease;});}catch{return undefined;}}}),session=await connectAgent({endpoint:relay.url,token:relay.token,origin,...lease});session.grant={...session.grant,access:'propose',nodeIds:['n1']};await authorizeAgent(session.id,session.grant);return {db,lease,session,relay,proposal:(patch:Partial<Proposal>={}):Proposal=>({id:crypto.randomUUID(),sessionId:session.id,projectId:'p1',baseRevision:1,status:'proposed',operations:[{id:'move-n1',type:'move_node',payload:{nodeId:'n1',x:80,y:120}}],...patch}),state:()=>transact(db,['graphs','proposals','runs','receipts'],'readonly',async tx=>({graph:await requestResult(tx.objectStore('graphs').get('p1')),proposals:await requestResult(tx.objectStore('proposals').getAll()),runs:await requestResult(tx.objectStore('runs').getAll()),receipts:await requestResult(tx.objectStore('receipts').getAll())})),close:async()=>{await disconnectAgent(session.id).catch(()=>{});release();await relay.close();unregister();db.close();}};}
