import {useEffect,useState} from 'react';
import {LocalLink,navigate} from '../../app/routes';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
import {buildRecoveryActions,recoveryCatalog,type RecoveryIssue} from './recovery-model';
import {listRecoveryIssues} from './recovery-service';
import {useMemoryRecoveries,downloadMemoryRecovery,saveConflictCopy,discardMemoryRecovery,type MemoryRecovery} from './memory-recovery';
export function MemoryRecoveryDialog({record,onClose,onReload}:{record:MemoryRecovery;onClose:()=>void;onReload:()=>Promise<void>}){const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[confirmReload,setConfirmReload]=useState(false),[fallback,setFallback]=useState('');function download(){try{downloadMemoryRecovery(record);setMessage('已触发浏览器下载；稿件尚未保存，媒体可能不完整。');}catch{import('../../infrastructure/packages/import-project').then(m=>m.exportMemoryDraft(record.project,record.graph).text()).then(setFallback).catch(()=>setMessage('下载和结构构建失败，请保留页面并手动复制当前文字。'));}}return <Dialog open title={record.issue.code==='E17'?'版本冲突恢复':'存储失败恢复'} onClose={()=>{if(!busy)onClose();}} width={800} footer={<Button disabled={busy} onClick={onClose}>继续编辑</Button>}><p>{recoveryCatalog[record.issue.code][0]}。当前内存稿保留；重载会丢失未保存内容，请先导出。</p><p>原项目 {record.project.id} · 内存来源修订 {record.graph.revision} · 结构导出不含执行授权或Key。</p><div className="actions"><Button data-interaction-id="F-06" onClick={download}>导出紧急内存草稿</Button><Button data-interaction-id="F-03" disabled={busy} onClick={async()=>{setBusy(true);try{const copy=await saveConflictCopy(record);setMessage('已另存冲突副本 '+copy.id+'；原项目没有覆盖，原任务只读历史保留，未自动执行。');}catch{setMessage('冲突副本未保存；当前内存稿仍保留，请先导出。');}finally{setBusy(false);}}}>保存为冲突副本</Button><Button data-interaction-id="F-04" disabled={busy} onClick={()=>setConfirmReload(true)}>丢弃本地草稿并重载</Button></div>{confirmReload?<div className="banner warning"><p>确认丢弃这份未保存的内存内容？原任务不会删除或重新提交。</p><Button disabled={busy} onClick={()=>setConfirmReload(false)}>返回保留草稿</Button><Button disabled={busy} onClick={async()=>{setBusy(true);try{await onReload();discardMemoryRecovery(record.project.id);onClose();}catch{setMessage('重载失败；内存稿仍保留，请导出后再试。');}finally{setBusy(false);}}}>确认丢弃并重载</Button></div>:null}{fallback?<label>可复制的紧急草稿JSON<textarea readOnly value={fallback}/></label>:null}<p role="status">{message}</p></Dialog>;}
export function RecoveryCenter(){const memory=useMemoryRecoveries(),[issues,setIssues]=useState<RecoveryIssue[]>([]),[selected,setSelected]=useState<MemoryRecovery>(),[error,setError]=useState('');useEffect(()=>{let active=true;listRecoveryIssues().then(rows=>{if(active)setIssues(rows);}).catch(()=>{if(active)setError('本地恢复记录读取失败，请保留页面和现有草稿。');});return()=>{active=false;};},[]);return <section aria-label="恢复中心"><h2>需要处理的本地问题</h2><p>只提供安全下一步；停止查询不等于取消或退款。未知提交不能清空、改身份或自动重发。</p><div className="actions"><LocalLink href="/activity">查看活动记录</LocalLink><LocalLink href="/projects/packages">从备份恢复</LocalLink></div>{error?<p role="alert">{error}</p>:null}{memory.map(row=><article className="card" key={row.project.id}><h3>未保存内存稿 · {row.project.title}</h3><p>{recoveryCatalog[row.issue.code][0]}</p><Button onClick={()=>setSelected(row)}>处理当前内存草稿</Button><Button onClick={()=>{downloadMemoryRecovery(row);}}>导出紧急内存草稿</Button></article>)}{issues.map(issue=><article className="card" key={issue.id} data-testid={'recovery-'+issue.id}><h3>{issue.code} · {recoveryCatalog[issue.code][0]}</h3><p>原服务 {issue.connectionId??'本地'} · 原授权绑定 {issue.authBindingId??'无'} · 原任务记录 {issue.runId??'无'}</p>{buildRecoveryActions(issue).map(action=><LocalLink key={action.type} href={action.href}>{action.label}</LocalLink>)}</article>)}{!memory.length&&!issues.length&&!error?<p>暂无已记录的待处理问题；本页没有发起业务查询。</p>:null}{selected?<MemoryRecoveryDialog record={selected} onClose={()=>setSelected(undefined)} onReload={async()=>{const {readProject,readGraph}=await import('../../infrastructure/storage/project-repository');if(!await readProject(selected.project.id)||!await readGraph(selected.project.id))throw Error('project_missing');navigate('/projects/'+encodeURIComponent(selected.project.id)+'/canvas');}}/>:null}</section>;}
