import type {SaveResult} from '../../domain/common';
export const recoveryCatalog={
 E01:['尚未连接或授权已失效','provide_auth','保留草稿，提供原授权'],E02:['当前授权不能执行此操作','manual','核对所需作用域，联系服务管理员'],E03:['任务、素材或作业不可访问','provide_auth','核对原服务与授权，保留任务编号'],E04:['恢复请求与原提交内容不一致','manual','保留原任务，查看冻结快照差异'],E05:['可用额度不足','manual','暂停后续提交，保留队列'],E06:['当前并发已满','manual','等待准入恢复，不新建收费任务'],E07:['服务暂未开放视频准入','manual','保留项目，核对服务状态'],E08:['生成或账务仍待确认','query','仅查询原任务，必要时由管理员核对'],E09:['暂时无法连接服务','manual','核对地址、TLS和已登记同源通道'],E10:['提交结果暂未确认','query','按原提交身份核对已知任务或本地回执'],E11:['参考素材不可用','manual','定位并恢复原素材后重新审阅'],E12:['当前服务不支持此参数组合','manual','定位字段，由你明确重新选择'],E13:['服务拒绝了此次内容请求','manual','查看脱敏原因，由你正常修改内容'],E14:['视频已完成，但获取文件失败','manual','仅重试原任务下载'],E15:['当前浏览器无法预览此文件','manual','下载原文件或使用兼容浏览器'],E16:['本地空间不足，未保存','export','导出内存草稿或清理可重建缩略图'],E17:['项目已在另一处修改','reload','先导出草稿，再确认重载或保存冲突副本'],E18:['项目版本高于当前客户端','export','保留原包，只读预览或安全导出'],E19:['导入包含不支持或不安全内容','manual','隔离未知节点，保留原包，不执行内容'],E20:['此任务需要原服务与原授权','provide_auth','提供此任务的原授权，不迁移到另一Key'],E21:['Agent连接中断','manual','保留提案，撤销会话写权限'],E22:['当前浏览器没有找到项目数据','manual','导入备份，核对本地浏览器数据范围'],E23:['尚未验证此功能是否可用','manual','查看能力页，等待契约核验'],E24:['遇到未分类问题','export','保留现场，导出脱敏诊断']
} as const;
export type RecoveryCode=keyof typeof recoveryCatalog;
export type RecoveryIssue={id:string;code:RecoveryCode;projectId?:string;runId?:string;draftId?:string;connectionId?:string;authBindingId?:string;originSnapshot?:string;at:number;source:'run'|'prompt'|'storage'|'diagnostic'|'session'};
export type RecoveryAction={type:'query'|'export'|'reload'|'provide_auth'|'manual';label:string;href:string};
const codes:Record<string,RecoveryCode>={core_api_key_required:'E01',session_credential_required:'E01',insufficient_scope:'E02',not_found:'E03',idempotency_conflict:'E04',quota_insufficient:'E05',key_concurrency_exceeded:'E06',video_billing_paused:'E07',reconcile_required:'E08',network_error:'E09',submit_timeout:'E10',reference_asset_unavailable:'E11',unsupported_parameter:'E12',safety_rejection:'E13',download_failed:'E14',media_decode_failed:'E15',quota_exceeded_storage:'E16',storage_quota_exceeded:'E16',save_conflict:'E17',project_revision_conflict:'E17',schema_too_new:'E18',import_unsafe:'E19',authorization_binding_mismatch:'E20',agent_disconnected:'E21',browser_storage_evicted:'E22',capability_unknown:'E23'};
export function recoveryCode(code:unknown):RecoveryCode{if(typeof code!=='string')return 'E24';if(Object.hasOwn(recoveryCatalog,code))return code as RecoveryCode;if(/quota.*storage|storage.*quota|quota_exceeded/i.test(code))return 'E16';if(/lease|writer|revision|conflict/.test(code))return 'E17';return codes[code]??'E24';}
export function saveRecoveryCode(result:SaveResult):RecoveryCode|undefined{return result.status==='saved'?undefined:result.status==='conflict'?'E17':recoveryCode(result.code);}
export function buildRecoveryActions(issue:RecoveryIssue):RecoveryAction[]{const [,type,label]=recoveryCatalog[issue.code];return [{type,label,href:type==='provide_auth'?'/settings/connections':type==='query'?'/tasks':issue.code==='E11'?'/assets':issue.code==='E14'||issue.code==='E15'?'/tasks':issue.code==='E16'?'/settings/storage':issue.code==='E22'||issue.code==='E18'||issue.code==='E19'?'/projects/packages':issue.code==='E23'?'/settings/capabilities':'/activity'}];}
