import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {viewportSchema,type CanvasNode,type Graph,type Viewport} from '../../domain/graph';
import {localText} from '../../domain/common';
import {readGraph,readProject} from '../../infrastructure/storage/project-repository';
import {withDatabase,transact,requestResult} from '../../infrastructure/storage/database';
import {getProjectWriter,studioTabId,projectError} from '../projects/project-service';
import {startProjectHeartbeat,releaseProjectLease,takeoverProjectLease,type ProjectLeaseToken} from '../../infrastructure/storage/project-lease';
import {TabChannel} from '../../infrastructure/storage/tab-channel';
import {applyUiCommand,type HistoryState} from '../../application/commands/apply-command';
import {undoProject,redoProject} from '../../application/commands/history';
import type {GraphOperation,CommandReceipt} from '../../application/commands/registry';
import {Button} from '../../ui/Button';
import {Dialog} from '../../ui/Dialog';
import {isEditableTarget} from '../../ui/copy.zh-CN';
import {navigate,setNavigationGuard} from '../../app/routes';
import {CanvasToolbar} from './CanvasToolbar';
import {NodeOutline} from './NodeOutline';
import {nodeBounds,nodeRect,nodeSize,visibleNodes,worldPosition} from './geometry';
import {selectNodes} from './selection';
import {updateViewport} from './viewport';
type Prefs={id:string;view:Viewport;background:'dots'|'grid'|'plain';minimap:boolean};
type Gesture={type:'pan'|'box'|'move';startX:number;startY:number;lastX:number;lastY:number;view:Viewport;graph:Graph;ids:string[];shift:boolean};
export function CanvasPage({projectId}:{projectId:string}){
 const [graph,setGraph]=useState<Graph>(),[title,setTitle]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[status,setStatus]=useState('已保存');
 const [lease,setLease]=useState<ProjectLeaseToken>(),[selected,setSelected]=useState<string[]>([]),[tool,setTool]=useState<'select'|'pan'>('select'),[view,setView]=useState<Viewport>({x:0,y:0,scale:1}),[prefs,setPrefs]=useState<{background:Prefs['background'];minimap:boolean}>({background:'dots',minimap:false});
 const [box,setBox]=useState<{left:number;top:number;width:number;height:number}>(),[addOpen,setAddOpen]=useState(false),[takeoverOpen,setTakeoverOpen]=useState(false),[leavePath,setLeavePath]=useState(''),[historyState,setHistoryState]=useState<HistoryState>();
 const stage=useRef<HTMLDivElement>(null),gesture=useRef<Gesture|undefined>(undefined),space=useRef(false),graphRef=useRef(graph),leaseRef=useRef(lease),dirty=useRef(false),busy=useRef(false),channel=useRef<TabChannel|undefined>(undefined),pendingOperations=useRef<GraphOperation[]>([]);
 graphRef.current=graph;leaseRef.current=lease;
 const canWrite=!!lease&&!busy.current&&(typeof matchMedia==='undefined'||!matchMedia('(max-width: 760px)').matches);
 async function reload(){const [g,p,h]=await Promise.all([readGraph(projectId),readProject(projectId),withDatabase(undefined,db=>transact(db,['receipts'],'readonly',tx=>requestResult<HistoryState|undefined>(tx.objectStore('receipts').get('history:'+projectId))))]);if(!p||p.trashedAt!==null||!g)throw new Error('project_not_available');setTitle(p.title);setGraph(g);graphRef.current=g;setHistoryState(h);return g;}
 useEffect(()=>{
  let alive=true,token:ProjectLeaseToken|undefined;const messages=new TabChannel();channel.current=messages;
  const lost=()=>{setLease(undefined);leaseRef.current=undefined;setStatus('只读 · 写权已失效');};
  const unsubscribe=messages.subscribe(message=>{if(message.projectId!==projectId)return;if(message.type==='lease-changed'&&leaseRef.current&&message.epoch>leaseRef.current.epoch)lost();if(message.type==='project-committed'&&!dirty.current)void reload().catch(()=>setError('项目更新读取失败，请重试。'));});
  void (async()=>{try{const g=await reload();const saved=await withDatabase(undefined,db=>transact(db,['diagnostics'],'readonly',tx=>requestResult<Prefs|undefined>(tx.objectStore('diagnostics').get('viewport:'+projectId))));if(!alive)return;setView(saved&&viewportSchema.safeParse(saved.view).success?saved.view:g.viewport);if(saved&&['dots','grid','plain'].includes(saved.background))setPrefs({background:saved.background,minimap:!!saved.minimap});try{token=await getProjectWriter(projectId);if(!alive){await releaseProjectLease(token);return;}setLease(token);leaseRef.current=token;}catch{setStatus('只读 · 另一标签持有写权');}}catch{if(alive)setError('项目无法读取，请返回项目主页检查数据。');}finally{if(alive)setLoading(false);}})();
  return()=>{alive=false;unsubscribe();messages.close();if(leaseRef.current)void releaseProjectLease(leaseRef.current);};
 },[projectId]);
 useEffect(()=>{if(!lease)return;const heartbeat=startProjectHeartbeat(lease,()=>{setLease(undefined);leaseRef.current=undefined;setStatus('只读 · 写权已失效');});return()=>heartbeat.stop();},[lease]);
 useEffect(()=>{if(loading)return;const snapshot:Prefs={id:'viewport:'+projectId,view,...prefs};void withDatabase(undefined,db=>transact(db,['diagnostics'],'readwrite',tx=>{tx.objectStore('diagnostics').put(snapshot);})).catch(()=>setError('视口偏好未保存，创作内容不受影响。'));},[view,prefs,projectId,loading]);
 useEffect(()=>{
  setNavigationGuard(path=>{if(dirty.current||busy.current){setLeavePath(path);return false;}return true;});
  const unload=(event:BeforeUnloadEvent)=>{if(dirty.current||busy.current){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',unload);
  return()=>{setNavigationGuard(undefined);window.removeEventListener('beforeunload',unload);};
 },[]);
 async function finish(receipt:CommandReceipt){if(receipt.status==='applied'||receipt.status==='replayed'){dirty.current=false;pendingOperations.current=[];const g=await reload();setStatus('已保存');setError('');if(leaseRef.current)channel.current?.publish({type:'project-committed',projectId,revision:g.revision,epoch:leaseRef.current.epoch});}else{setStatus('尚未保存 · 内存草稿保留');setError(receipt.status==='conflict'?'项目版本已变化，本次草稿未覆盖已保存版本。':projectError(new Error(receipt.errorCode)));if(/lease|writer/.test(receipt.errorCode??'')){setLease(undefined);leaseRef.current=undefined;}}}
 async function commit(operations:GraphOperation[]){const g=graphRef.current,token=leaseRef.current;if(!g||!token||busy.current)return;busy.current=true;dirty.current=true;pendingOperations.current=operations;setStatus('正在保存');try{await finish(await applyUiCommand({id:crypto.randomUUID(),projectId,baseRevision:g.revision,operations},{lease:token}));}catch{setError('本次修改尚未保存，内存草稿保留。');setStatus('尚未保存');}finally{busy.current=false;}}
 async function historyMove(direction:'undo'|'redo'){const g=graphRef.current,token=leaseRef.current;if(!g||!token||busy.current||dirty.current)return;busy.current=true;setStatus('正在保存');try{await finish(await (direction==='undo'?undoProject:redoProject)(projectId,g.revision,{lease:token,origin:'ui'}));}finally{busy.current=false;}}
 function size(){return {width:stage.current?.clientWidth??1,height:stage.current?.clientHeight??1};}
 function locate(ids?:string[]){const g=graphRef.current;if(!g)return;const nodes=visibleNodes(g).filter(n=>!ids||ids.includes(n.id));setView(current=>updateViewport(current,{type:ids?'locate':'fit',bounds:nodes.length?nodeBounds(nodes,g):null,...size()}));}
 function point(event:{clientX:number;clientY:number}){const rect=stage.current!.getBoundingClientRect();return {x:event.clientX-rect.left,y:event.clientY-rect.top};}
 function down(event:PointerEvent<HTMLDivElement>){if(!graph||document.querySelector('dialog[open]')||isEditableTarget(event.target)||busy.current)return;const p=point(event),element=(event.target as HTMLElement).closest<HTMLElement>('[data-node-id]'),node=graph.nodes.find(n=>n.id===element?.dataset.nodeId);let type:Gesture['type']='box',ids=selected;if(event.button===1||tool==='pan'||space.current){type='pan';event.preventDefault();}else if(event.button!==0)return;else if(node){ids=event.shiftKey?(selected.includes(node.id)?selected.filter(id=>id!==node.id):[...selected,node.id]):selected.includes(node.id)?selected:[node.id];setSelected(selectNodes(graph,{type:'ids',ids}));if(!canWrite||node.locked)return;type='move';dirty.current=true;}else if(!event.shiftKey)setSelected([]);gesture.current={type,startX:p.x,startY:p.y,lastX:p.x,lastY:p.y,view,graph:structuredClone(graph),ids,shift:event.shiftKey};event.currentTarget.setPointerCapture(event.pointerId);stage.current?.focus();}
 function move(event:PointerEvent<HTMLDivElement>){const g=gesture.current;if(!g)return;const p=point(event);g.lastX=p.x;g.lastY=p.y;const dx=p.x-g.startX,dy=p.y-g.startY;if(g.type==='pan')setView(updateViewport(g.view,{type:'pan',dx,dy}));else if(g.type==='box')setBox({left:Math.min(g.startX,p.x),top:Math.min(g.startY,p.y),width:Math.abs(dx),height:Math.abs(dy)});else {const ids=g.ids.filter(id=>!g.graph.nodes.some(group=>group.type==='group'&&g.ids.includes(group.id)&&group.data.childIds.includes(id)));setGraph({...g.graph,nodes:g.graph.nodes.map(node=>ids.includes(node.id)&&!node.locked?{...node,x:node.x+dx/g.view.scale,y:node.y+dy/g.view.scale}:node)});}}
 function up(event:PointerEvent<HTMLDivElement>){const g=gesture.current;if(!g)return;gesture.current=undefined;if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);const dx=g.lastX-g.startX,dy=g.lastY-g.startY;if(g.type==='box'){setBox(undefined);const rect={left:(Math.min(g.startX,g.lastX)-g.view.x)/g.view.scale,top:(Math.min(g.startY,g.lastY)-g.view.y)/g.view.scale,right:(Math.max(g.startX,g.lastX)-g.view.x)/g.view.scale,bottom:(Math.max(g.startY,g.lastY)-g.view.y)/g.view.scale};const ids=selectNodes(g.graph,{type:'rectangle',rect});setSelected(g.shift?[...new Set([...selected,...ids])]:ids);}else if(g.type==='move'){graphRef.current=g.graph;if(!dx&&!dy){dirty.current=false;setGraph(g.graph);return;}const ops:GraphOperation[]=g.ids.filter(id=>!g.graph.nodes.some(group=>group.type==='group'&&g.ids.includes(group.id)&&group.data.childIds.includes(id))).flatMap(id=>{const n=g.graph.nodes.find(n=>n.id===id);return n&&!n.locked?[{id:crypto.randomUUID(),type:'move_node',payload:{nodeId:id,x:n.x+dx/g.view.scale,y:n.y+dy/g.view.scale}}]:[];});void commit(ops);}}
 function addText(text=''){if(!localText.safeParse(text).success){setError('本地文本超过64KiB，未插入。');return;}const center=size(),id=crypto.randomUUID(),node:CanvasNode={id,type:'text',title:'文本节点',x:(center.width/2-view.x)/view.scale,y:(center.height/2-view.y)/view.scale,locked:false,data:{kind:'text',text,referenceTokens:[]}};setAddOpen(false);void commit([{id:crypto.randomUUID(),type:'add_node',payload:{node}}]);}
 function keyboard(event:React.KeyboardEvent){if(event.nativeEvent.isComposing||isEditableTarget(event.target)||document.querySelector('dialog[open]'))return;if(event.key===' '){event.preventDefault();space.current=true;}else if(event.key.toLowerCase()==='v')setTool('select');else if(event.key.toLowerCase()==='h')setTool('pan');else if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='a'){event.preventDefault();if(graph)setSelected(selectNodes(graph,{type:'ids',ids:graph.nodes.map(n=>n.id)}));}else if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();void historyMove(event.shiftKey?'redo':'undo');}else if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='y'){event.preventDefault();void historyMove('redo');}else if(event.key==='Escape'){setSelected([]);if(gesture.current){setGraph(gesture.current.graph);gesture.current=undefined;setBox(undefined);dirty.current=false;}}}
 if(loading)return <p role="status">正在读取画布…</p>;if(!graph)return <p role="alert" className="banner error">{error}</p>;
 const displayed=visibleNodes(graph),bounds=nodeBounds(displayed,graph),mapScale=displayed.length?Math.min(160/Math.max(1,bounds.right-bounds.left),100/Math.max(1,bounds.bottom-bounds.top)):.1;
 return <section className="canvas-workspace" onKeyDown={keyboard} onKeyUp={e=>{if(e.key===' ')space.current=false;}}><div className="canvas-heading"><h2>{title}</h2><span role="status">{status}</span>{!lease?<Button onClick={()=>setTakeoverOpen(true)}>接管编辑</Button>:null}{dirty.current&&!busy.current?<Button onClick={()=>void commit(pendingOperations.current)}>重试保存</Button>:null}</div>{error?<p role="alert" className="banner error">{error}</p>:null}
 <CanvasToolbar scale={view.scale} onZoom={scale=>setView(v=>updateViewport(v,{type:'zoom',scale,...size()}))} tool={tool} onTool={setTool} onFit={()=>locate()} onLocate={()=>locate(selected)} selectedCount={selected.length} minimap={prefs.minimap} onMinimap={()=>setPrefs(p=>({...p,minimap:!p.minimap}))} background={prefs.background} onBackground={background=>setPrefs(p=>({...p,background:background as Prefs['background']}))} onAdd={()=>setAddOpen(true)} canWrite={canWrite} canUndo={!!historyState?.undoStack.length&&!dirty.current} canRedo={!!historyState?.redoStack.length&&!dirty.current} onUndo={()=>void historyMove('undo')} onRedo={()=>void historyMove('redo')}/>
 <div className="canvas-layout"><div data-testid="canvas-stage" className={'canvas-stage background-'+prefs.background+' tool-'+(space.current?'pan':tool)} tabIndex={0} aria-label="创作画布" ref={stage} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{if(gesture.current){setGraph(gesture.current.graph);gesture.current=undefined;dirty.current=false;setBox(undefined);}}} onBlur={()=>{space.current=false;}} onWheel={e=>{if(document.querySelector('dialog[open]'))return;setView(v=>e.ctrlKey||e.metaKey?updateViewport(v,{type:'zoom',scale:Math.max(.25,Math.min(2,v.scale*(e.deltaY<0?1.1:1/1.1))),...size()}):updateViewport(v,{type:'pan',dx:-e.deltaX,dy:-e.deltaY}));}} onPaste={event=>{if(isEditableTarget(event.target)||!canWrite)return;event.preventDefault();const text=event.clipboardData.getData('text/plain');if(text)addText(text);else if(event.clipboardData.files.length)setError('请先在素材库导入文件，再插入画布。');}}>
 <div className="canvas-world" style={{transform:`translate(${view.x}px,${view.y}px) scale(${view.scale})`}}>{displayed.map(node=>{const p=worldPosition(node,graph),size=nodeSize(node);return <article key={node.id} data-testid={'node-'+node.id} data-node-id={node.id} data-node-type={node.type} aria-selected={selected.includes(node.id)} className={'canvas-node node-'+node.type+(selected.includes(node.id)?' selected':'')} style={{left:p.x,top:p.y,width:size.width,height:size.height}}><header data-testid="node-handle">{node.title}{node.locked?' · 已锁定':''}</header><div className="node-body">{node.type==='text'?<p>{node.data.text||'输入创作内容'}</p>:node.type==='group'?<p>{node.data.childIds.length} 个节点</p>:<p>本地创作节点</p>}</div></article>;})}</div>{box?<div className="selection-box" style={box}/>:null}
 {prefs.minimap?<svg data-testid="canvas-minimap" className="canvas-minimap" viewBox="0 0 180 120" role="img" aria-label="画布小地图" onClick={e=>{const rect=e.currentTarget.getBoundingClientRect(),x=((e.clientX-rect.left)/rect.width*180-10)/mapScale+bounds.left,y=((e.clientY-rect.top)/rect.height*120-10)/mapScale+bounds.top;setView(v=>({...v,x:size().width/2-x*v.scale,y:size().height/2-y*v.scale}));}}>{displayed.map(node=>{const r=nodeRect(node,graph);return <rect key={node.id} x={(r.left-bounds.left)*mapScale+10} y={(r.top-bounds.top)*mapScale+10} width={(r.right-r.left)*mapScale} height={(r.bottom-r.top)*mapScale}/>;})}</svg>:null}</div><NodeOutline graph={graph} selected={selected} onSelect={ids=>setSelected(selectNodes(graph,{type:'ids',ids}))} onLocate={locate}/></div>
 <Dialog open={addOpen} title="添加节点" onClose={()=>setAddOpen(false)} footer={<Button onClick={()=>setAddOpen(false)}>取消</Button>}><Button onClick={()=>addText()}>文本节点</Button><p>素材、视频草稿、固定结果引用与分组在对应节点实现后接入；未核验能力不会开放生成。</p></Dialog>
 <Dialog open={takeoverOpen} title="接管编辑" onClose={()=>setTakeoverOpen(false)} footer={<><Button onClick={()=>setTakeoverOpen(false)}>取消</Button><Button onClick={async()=>{const result=await takeoverProjectLease(projectId,studioTabId,Date.now());if(result.ok){setLease(result.token);leaseRef.current=result.token;await reload();dirty.current=false;pendingOperations.current=[];setStatus('已保存');channel.current?.publish({type:'lease-changed',projectId,epoch:result.epoch,revision:result.revision});setTakeoverOpen(false);}else setError('接管失败，请重试。');}}>确认接管</Button></>}><p>接管会使旧标签的写权失效。未保存草稿请先备份；任务追踪继续保留。</p></Dialog>
 <Dialog open={!!leavePath} title="离开前保存" onClose={()=>setLeavePath('')} footer={<><Button onClick={()=>setLeavePath('')}>继续编辑</Button><Button disabled={busy.current} onClick={()=>{dirty.current=false;setNavigationGuard(undefined);navigate(leavePath);}}>放弃本次未保存修改并离开</Button><Button disabled={busy.current||!lease||!pendingOperations.current.length} onClick={async()=>{await commit(pendingOperations.current);if(!dirty.current){setNavigationGuard(undefined);navigate(leavePath);}}}>保存并离开</Button></>}><p>本次修改尚未保存，离开可能丢失内存草稿。</p></Dialog>
 </section>;
}

