import {useState} from 'react';
import type {Graph,Edge} from '../../domain/graph';
import type {Asset} from '../../domain/asset';
import type {CapabilityProfile} from '../../domain/connection';
import {validateConnection,getOrderedInputs,type ReferenceLimits} from '../../domain/graph-validation';
import {Dialog} from '../../ui/Dialog';
import {Button} from '../../ui/Button';
import type {GraphOperation} from '../../application/commands/registry';
export function InputInspector({graph,nodeId,assets,capability,limits,readonly,onCommand}:{graph:Graph;nodeId:string;assets:Asset[];capability:CapabilityProfile;limits?:ReferenceLimits;readonly:boolean;onCommand:(ops:GraphOperation[])=>void}){
 const [picker,setPicker]=useState(false),[snapshot,setSnapshot]=useState(false),[query,setQuery]=useState(''),[error,setError]=useState('');const inputs=getOrderedInputs(graph,nodeId),incoming=graph.edges.filter(e=>e.targetId===nodeId).sort((a,b)=>a.order-b.order),candidates=graph.nodes.filter(n=>n.id!==nodeId&&['text','asset','result'].includes(n.type)&&n.title.includes(query));
 function port(id:string):Edge['port']|undefined{const node=graph.nodes.find(n=>n.id===id);if(node?.type==='text')return 'text';if(node?.type==='asset'||node?.type==='result'){const type=assets.find(a=>a.id===node.data.assetId)?.mediaType;return type==='image'||type==='video'?type:undefined;}}
 function connect(sourceId:string){const type=port(sourceId);if(!type){setError('该素材类型不可作为视频输入。');return;}const edge:Edge={id:crypto.randomUUID(),sourceId,targetId:nodeId,port:type,order:Math.max(-1,...incoming.map(e=>e.order))+1},valid=validateConnection(graph,edge,capability,{assets,limits});if(!valid.ok){setError(valid.issues[0].message);return;}onCommand([{id:crypto.randomUUID(),type:'add_edge',payload:{edge}}]);setPicker(false);setError('');}
 function reorder(index:number,delta:number){const a=incoming[index],b=incoming[index+delta];if(!a||!b)return;onCommand([{id:crypto.randomUUID(),type:'remove_edge',payload:{edgeId:a.id}},{id:crypto.randomUUID(),type:'remove_edge',payload:{edgeId:b.id}},{id:crypto.randomUUID(),type:'add_edge',payload:{edge:{...a,order:b.order}}},{id:crypto.randomUUID(),type:'add_edge',payload:{edge:{...b,order:a.order}}}]);}
 return <div><div className="node-actions"><Button data-interaction-id="N-14" disabled={readonly} onClick={()=>setPicker(true)}>选择输入</Button><Button data-interaction-id="V-06" onClick={()=>setSnapshot(true)}>查看输入快照</Button></div><ol data-interaction-id="V-05" aria-label="显式参考素材列表" data-testid="input-list">{inputs.map((input,index)=>{const node=graph.nodes.find(n=>n.id===input.nodeId);return <li key={input.nodeId+input.role}><span>{index+1} · {node?.title??'节点缺失'} · {input.role}</span><div className="node-actions"><Button data-interaction-id="N-16" aria-label={'上移 '+node?.title} disabled={readonly||index===0} onClick={()=>reorder(index,-1)}>↑</Button><Button data-interaction-id="N-16" aria-label={'下移 '+node?.title} disabled={readonly||index===inputs.length-1} onClick={()=>reorder(index,1)}>↓</Button><Button data-interaction-id="N-15" aria-label={'断开 '+node?.title} disabled={readonly} onClick={()=>onCommand([{id:crypto.randomUUID(),type:'remove_edge',payload:{edgeId:incoming[index].id}}])}>断开</Button></div></li>;})}</ol>
 <Dialog open={picker} title="选择输入" onClose={()=>setPicker(false)} footer={<Button data-interaction-id="ui:InputInspector:Button:c4bcbc7ff197" onClick={()=>setPicker(false)}>取消</Button>}><label>搜索上游节点<input data-interaction-id="ui:InputInspector:input:e873229100fc" value={query} onChange={e=>setQuery(e.target.value)}/></label>{error?<p role="alert">{error}</p>:null}{candidates.length?candidates.map(node=><Button data-interaction-id="ui:InputInspector:Button:c59b05bb8a22" key={node.id} disabled={inputs.some(input=>input.nodeId===node.id)||!port(node.id)} onClick={()=>connect(node.id)}>{'连接 '+node.title}</Button>):<p>没有可用节点，请先添加文本或素材节点。</p>}<small>{capability.verification==='unknown'?'参考上限尚未核验；可以保存本地草稿，执行须先核验。':'数量以当前已核验契约为准。'}</small></Dialog>
 <Dialog open={snapshot} title="输入快照" onClose={()=>setSnapshot(false)} footer={<Button data-interaction-id="ui:InputInspector:Button:5ae2fa4aec0b" onClick={()=>setSnapshot(false)}>关闭</Button>}><ol data-testid="input-order">{inputs.map((input,index)=>{const node=graph.nodes.find(n=>n.id===input.nodeId);return <li key={input.nodeId+input.role}>{index+1} · {node?.title} · {input.role}{node?.type==='text'?<pre>{node.data.text}</pre>:<p>素材 {input.assetId} {input.runId?'· 任务 '+input.runId:''}</p>}</li>;})}</ol><p>仅包含这些显式输入；执行保存快照后不会跟随布局或编辑变化。</p></Dialog></div>;
}
