import {randomUUID} from 'node:crypto';
import {beforeEach,afterEach,expect,it} from 'vitest';
import {fixture,type Fixture} from './account-fixture.js';
import {ApiSecrets} from '../src/security/api-secrets.js';
import {RestrictedOutbound,type OutboundRequest} from '../src/security/outbound.js';
let f:Fixture,calls:OutboundRequest[],mode:'success'|'unknown'|'denied',dependencies:{secrets:ApiSecrets;outbound:RestrictedOutbound};
beforeEach(async()=>{calls=[];mode='success';dependencies={secrets:new ApiSecrets({activeVersion:'test',keys:new Map([['test',Buffer.alloc(32,7)]])}),outbound:new RestrictedOutbound({resolve:async()=>[{address:'93.184.216.34',family:4}],request:async request=>{calls.push(request);if(mode==='unknown')throw Error('FAKE_AGENT_NETWORK_TIMEOUT');const body=JSON.parse(request.body!.toString()),input=JSON.parse(body.messages[1].content),node=input.nodes[0];return {status:200,body:Buffer.from(JSON.stringify({choices:[{message:{content:JSON.stringify({message:'建议已保存 '+request.apiKey,operations:[{id:'edit-1',type:mode==='denied'?'remove_node':'update_node',payload:mode==='denied'?{nodeId:node.id}:{nodeId:node.id,patch:{data:{kind:'text',text:'审阅后才应用的正文',referenceTokens:[]}}}}]})}}]}))};}})};f=await fixture({workspace:true,content:true,apiSettings:dependencies});});
afterEach(async()=>{await f?.close();});
async function setup(name:string,key:string){const account=await f.signup(name),h=f.headers(account);expect((await f.call('PATCH','/studio-api/me/model-configs/text',{...h,payload:{apiBase:'https://agent.example.test',model:'Vendor/Custom-Agent',apiKey:key,expectedRevision:null}})).statusCode).toBe(200);const project=(await f.call('POST','/studio-api/projects',{...h,payload:{title:'云端 Agent 项目'}})).json(),nodeId=randomUUID();expect((await f.call('POST','/studio-api/projects/'+project.id+'/commands',{...h,payload:{expectedRevision:0,idempotencyKey:randomUUID(),command:{type:'operations',operations:[{id:randomUUID(),type:'add_node',payload:{node:{id:nodeId,type:'text',title:'文本',x:0,y:0,locked:false,data:{kind:'text',text:'原始正文',referenceTokens:[]}}}}]}}})).statusCode).toBe(200);const response=await f.call('POST','/studio-api/projects/'+project.id+'/agent-conversations',{...h,payload:{title:'创作会话',idempotencyKey:randomUUID()}});expect(response.statusCode,response.body).toBe(201);return {account,h,projectId:project.id,nodeId,conversation:response.json()};}
async function grant(owner:Awaited<ReturnType<typeof setup>>,access:'read'|'propose'='propose'){const response=await f.call('POST','/studio-api/agent-conversations/'+owner.conversation.id+'/grant',{...owner.h,payload:{expectedRevision:owner.conversation.revision,scope:'project',nodeIds:[],access}});expect(response.statusCode,response.body).toBe(200);owner.conversation=response.json();}
async function preview(owner:Awaited<ReturnType<typeof setup>>){const response=await f.call('POST','/studio-api/agent-conversations/'+owner.conversation.id+'/preview',{...owner.h,payload:{expectedRevision:owner.conversation.revision,graphRevision:1,configRevision:1,description:'整理文本'}});expect(response.statusCode,response.body).toBe(201);return response.json();}
const confirm=(owner:Awaited<ReturnType<typeof setup>>,id:string)=>f.call('POST','/studio-api/agent-conversations/'+owner.conversation.id+'/runs',{...owner.h,payload:{approvalId:id,decision:{confirmed:true,acknowledgeTextFee:true}}});
async function work(){const {executeNextAgentTask}=await import('../src/agent/worker.js');await executeNextAgentTask(f.pool,dependencies,()=>new Date('2026-10-08T12:00:00Z'));}
it('persists complete owned conversations and notes and rejects foreign reads, writes and stale revisions',async()=>{
 const a=await setup('Agent_NotesA','MOCK_AGENT_A'),b=await setup('Agent_NotesB','MOCK_AGENT_B');const saved=await f.call('POST','/studio-api/agent-conversations/'+a.conversation.id+'/notes',{...a.h,payload:{expectedRevision:0,body:'完整的创作描述',context:{scope:'project',nodeIds:[],revision:1},idempotencyKey:randomUUID()}});expect(saved.statusCode,saved.body).toBe(200);expect(saved.json()).toMatchObject({revision:1,notes:[{body:'完整的创作描述'}]});expect((await f.call('GET','/studio-api/agent-conversations/'+a.conversation.id,b.h)).statusCode).toBe(404);expect((await f.call('POST','/studio-api/agent-conversations/'+a.conversation.id+'/notes',{...b.h,payload:{expectedRevision:1,body:'不能写入',context:{scope:'project',nodeIds:[],revision:1},idempotencyKey:randomUUID()}})).statusCode).toBe(404);expect((await f.call('POST','/studio-api/agent-conversations/'+a.conversation.id+'/notes',{...a.h,payload:{expectedRevision:0,body:'过期修改',context:{scope:'project',nodeIds:[],revision:1},idempotencyKey:randomUUID()}})).statusCode).toBe(409);expect(calls).toHaveLength(0);
});
it('freezes A/B agent requests and saves suggestions without applying the proposed graph change',async()=>{
 const a=await setup('Agent_RunA','MOCK_AGENT_A'),b=await setup('Agent_RunB','MOCK_AGENT_B');await grant(a);await grant(b);const pa=await preview(a),pb=await preview(b),ta=await confirm(a,pa.id),tb=await confirm(b,pb.id);expect(ta.statusCode).toBe(202);expect(tb.statusCode).toBe(202);await work();await work();expect(calls.map(call=>call.apiKey).sort()).toEqual(['MOCK_AGENT_A','MOCK_AGENT_B']);for(const [owner,created]of [[a,ta],[b,tb]] as const){const run=(await f.call('GET','/studio-api/runs/'+created.json().id,owner.h)).json();expect(run).toMatchObject({kind:'agent-advice',executionState:'succeeded',proposalId:expect.any(String)});expect(JSON.stringify(run)).not.toContain('MOCK_AGENT_A');expect((await f.call('GET','/studio-api/projects/'+owner.projectId+'/graph',owner.h)).json().nodes[0].data.text).toBe('原始正文');}expect((await f.call('GET','/studio-api/runs/'+ta.json().id,b.h)).statusCode).toBe(404);
});
it('applies only explicitly selected proposal operations and stores an atomic decision with graph history',async()=>{
 const a=await setup('Agent_Review','MOCK_AGENT_A');await grant(a);const run=await confirm(a,(await preview(a)).id);await work();const task=(await f.call('GET','/studio-api/runs/'+run.json().id,a.h)).json(),proposal=(await f.call('GET','/studio-api/agent-proposals/'+task.proposalId,a.h)).json();const response=await f.call('POST','/studio-api/agent-proposals/'+proposal.id+'/decision',{...a.h,payload:{expectedRevision:proposal.revision,decision:'apply',operationIds:['edit-1']}});expect(response.statusCode,response.body).toBe(200);expect(response.json()).toMatchObject({status:'applied',decisions:[{decision:'applied',operationIds:['edit-1']}]});const workspace=(await f.call('GET','/studio-api/projects/'+a.projectId+'/workspace',a.h)).json();expect(workspace.graph.nodes[0].data.text).toBe('审阅后才应用的正文');expect(workspace.history.undoDepth).toBe(2);
});
it('rejects a revoked grant at confirmation and at proposal application without sending or changing the graph',async()=>{
 const a=await setup('Agent_Revoke','MOCK_AGENT_A');await grant(a);const p=await preview(a),run=await confirm(a,p.id);await work();const task=(await f.call('GET','/studio-api/runs/'+run.json().id,a.h)).json();expect((await f.call('POST','/studio-api/agent-conversations/'+a.conversation.id+'/revoke',{...a.h,payload:{expectedRevision:a.conversation.revision}})).statusCode).toBe(200);expect((await f.call('POST','/studio-api/agent-proposals/'+task.proposalId+'/decision',{...a.h,payload:{expectedRevision:0,decision:'apply',operationIds:['edit-1']}})).statusCode).toBe(409);const c=(await f.call('GET','/studio-api/agent-conversations/'+a.conversation.id,a.h)).json();a.conversation=c;await grant(a);const newer=await preview(a);await f.call('POST','/studio-api/agent-conversations/'+a.conversation.id+'/revoke',{...a.h,payload:{expectedRevision:a.conversation.revision}});expect((await confirm(a,newer.id)).statusCode).toBe(409);expect(calls).toHaveLength(1);
});
it('uses the original frozen key after settings rotation and never replays an unknown agent request',async()=>{
 const a=await setup('Agent_Rotate','MOCK_AGENT_A');await grant(a);const p=await preview(a),created=await confirm(a,p.id);await f.call('PATCH','/studio-api/me/model-configs/text',{...a.h,payload:{apiBase:'https://agent.example.test',model:'New-Model',apiKey:'MOCK_AGENT_NEW',expectedRevision:1}});mode='unknown';for(let step=0;step<3;step++)await work();expect(calls).toHaveLength(1);expect(calls[0].apiKey).toBe('MOCK_AGENT_A');expect((await f.call('GET','/studio-api/runs/'+created.json().id,a.h)).json()).toMatchObject({executionState:'response_unknown',billingState:'pending_reconciliation'});expect((await confirm(a,p.id)).json().id).toBe(created.json().id);
});
it('rejects delete/generate actions from an agent result before storing an actionable proposal',async()=>{
 const a=await setup('Agent_Denied','MOCK_AGENT_A');await grant(a);const created=await confirm(a,(await preview(a)).id);mode='denied';await work();expect((await f.call('GET','/studio-api/runs/'+created.json().id,a.h)).json()).toMatchObject({executionState:'response_unknown',errorCode:'INVALID_UPSTREAM_RESULT'});expect((await f.pool.query('SELECT id FROM workspace_agent_proposals')).rows).toHaveLength(0);expect((await f.call('GET','/studio-api/projects/'+a.projectId+'/graph',a.h)).json().nodes[0].data.text).toBe('原始正文');
});
it('retries saving a durable sanitized agent reply without calling the model twice',async()=>{
 const a=await setup('Agent_ResultRetry','MOCK_AGENT_A');await grant(a);const created=await confirm(a,(await preview(a)).id);expect(created.statusCode).toBe(202);await f.pool.query("CREATE FUNCTION reject_agent_result() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'fake database failure'; END $$");await f.pool.query('CREATE TRIGGER reject_agent_result BEFORE INSERT ON workspace_agent_proposals FOR EACH ROW EXECUTE FUNCTION reject_agent_result()');await work();expect((await f.call('GET','/studio-api/runs/'+created.json().id,a.h)).json().executionState).toBe('response_received');expect(JSON.stringify((await f.pool.query('SELECT result_snapshot FROM workspace_agent_runs')).rows)).not.toContain('MOCK_AGENT_A');await f.pool.query('DROP TRIGGER reject_agent_result ON workspace_agent_proposals');await work();expect((await f.call('GET','/studio-api/runs/'+created.json().id,a.h)).json().executionState).toBe('succeeded');expect(calls).toHaveLength(1);
});
it('rolls back a proposed graph change when its decision cannot be stored',async()=>{
 const a=await setup('Agent_DecisionRollback','MOCK_AGENT_A');await grant(a);const created=await confirm(a,(await preview(a)).id);await work();const task=(await f.call('GET','/studio-api/runs/'+created.json().id,a.h)).json();await f.pool.query("CREATE FUNCTION reject_agent_decision() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'fake decision failure'; END $$");await f.pool.query('CREATE TRIGGER reject_agent_decision BEFORE UPDATE ON workspace_agent_proposals FOR EACH ROW EXECUTE FUNCTION reject_agent_decision()');expect((await f.call('POST','/studio-api/agent-proposals/'+task.proposalId+'/decision',{...a.h,payload:{expectedRevision:0,decision:'apply',operationIds:['edit-1']}})).statusCode).toBe(500);expect((await f.call('GET','/studio-api/projects/'+a.projectId+'/graph',a.h)).json()).toMatchObject({revision:1,nodes:[{data:{text:'原始正文'}}]});expect((await f.call('GET','/studio-api/agent-proposals/'+task.proposalId,a.h)).json().status).toBe('proposed');
});
it('blocks a revoked queued request before any model call and requires only selected owned nodes in the grant',async()=>{
 const a=await setup('Agent_QueuedRevoke','MOCK_AGENT_A'),b=await setup('Agent_ForeignScope','MOCK_AGENT_B');expect((await f.call('POST','/studio-api/agent-conversations/'+a.conversation.id+'/grant',{...a.h,payload:{expectedRevision:0,scope:'selection',nodeIds:[b.nodeId],access:'propose'}})).statusCode).toBe(422);await grant(a);const created=await confirm(a,(await preview(a)).id);await f.call('POST','/studio-api/agent-conversations/'+a.conversation.id+'/revoke',{...a.h,payload:{expectedRevision:a.conversation.revision}});await work();expect(calls).toHaveLength(0);expect((await f.call('GET','/studio-api/runs/'+created.json().id,a.h)).json()).toMatchObject({executionState:'failed_confirmed',errorCode:'GRANT_CHANGED'});
});
it('exports complete agent history and copies/imports it as readonly records without active permissions or automatic calls',async()=>{
 const a=await setup('Agent_Package','MOCK_AGENT_A');const note=await f.call('POST','/studio-api/agent-conversations/'+a.conversation.id+'/notes',{...a.h,payload:{expectedRevision:0,body:'应保留的完整历史描述',context:{scope:'project',nodeIds:[],revision:1},idempotencyKey:randomUUID()}});a.conversation=note.json();await grant(a);const created=await confirm(a,(await preview(a)).id);await work();const task=(await f.call('GET','/studio-api/runs/'+created.json().id,a.h)).json();expect((await f.call('POST','/studio-api/agent-proposals/'+task.proposalId+'/decision',{...a.h,payload:{expectedRevision:0,decision:'reject',operationIds:[]}})).statusCode).toBe(200);
 const exported=await f.call('GET','/studio-api/projects/'+a.projectId+'/export',a.h);expect(exported.statusCode,exported.body).toBe(200);const data=exported.json();expect(data.agentHistory[0]).toMatchObject({conversation:{grant:null,historical:true,notes:[{body:'应保留的完整历史描述'}]},proposals:[{historical:true,status:'rejected',decisions:[{decision:'rejected'}]}]});expect(data.agentHistory[0].versions.length).toBeGreaterThan(1);expect(data.taskHistory[0]).toMatchObject({kind:'agent-advice',historical:true});expect(exported.body).not.toMatch(/MOCK_AGENT|frozen_config|request_body/);
 const b=await setup('Agent_PackageB','MOCK_AGENT_B'),imported=await f.call('POST','/studio-api/projects/import',{...b.h,payload:{data,assets:{},idempotencyKey:randomUUID()}});expect(imported.statusCode,imported.body).toBe(201);const conversations=(await f.call('GET','/studio-api/projects/'+imported.json().project.id+'/agent-conversations',b.h)).json();expect(conversations).toHaveLength(1);expect(conversations[0]).toMatchObject({historical:true,grant:null,notes:[{body:'应保留的完整历史描述'}]});expect(conversations[0].id).not.toBe(a.conversation.id);expect((await f.call('POST','/studio-api/agent-conversations/'+conversations[0].id+'/grant',{...b.h,payload:{expectedRevision:conversations[0].revision,scope:'project',nodeIds:[],access:'propose'}})).statusCode).toBe(409);const proposals=(await f.call('GET','/studio-api/agent-conversations/'+conversations[0].id+'/proposals',b.h)).json();expect(proposals[0]).toMatchObject({historical:true,status:'rejected',conversationId:conversations[0].id});expect((await f.call('POST','/studio-api/agent-proposals/'+proposals[0].id+'/decision',{...b.h,payload:{expectedRevision:proposals[0].revision,decision:'apply',operationIds:['edit-1']}})).statusCode).toBe(409);const copy=await f.call('POST','/studio-api/projects/'+a.projectId+'/copy',{...a.h,payload:{expectedRevision:1,idempotencyKey:randomUUID()}});expect(copy.statusCode,copy.body).toBe(201);expect((await f.call('GET','/studio-api/projects/'+copy.json().project.id+'/agent-conversations',a.h)).json()[0]).toMatchObject({historical:true,grant:null,notes:[{body:'应保留的完整历史描述'}]});await work();expect(calls).toHaveLength(1);
});
