import {randomUUID,createHash} from 'node:crypto';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {afterEach,beforeEach,expect,it} from 'vitest';
import {fixture,origin,type Fixture,type Account} from './account-fixture.js';
import {ApiSecrets} from '../src/security/api-secrets.js';
import {RestrictedOutbound,type OutboundRequest} from '../src/security/outbound.js';
import {executeNextPromptTask} from '../src/tasks/prompt-worker.js';
let env:Fixture,root:string,calls:OutboundRequest[],dependencies:{secrets:ApiSecrets;outbound:RestrictedOutbound};
const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6nRAAAAAASUVORK5CYII=','base64');
beforeEach(async()=>{root=await mkdtemp(join(tmpdir(),'studio-frame-test-'));calls=[];dependencies={secrets:new ApiSecrets({activeVersion:'test',keys:new Map([['test',Buffer.alloc(32,7)]])}),outbound:new RestrictedOutbound({resolve:async()=>[{address:'93.184.216.34',family:4}],request:async input=>{calls.push(input);return {status:200,body:Buffer.from(JSON.stringify({choices:[{message:{content:JSON.stringify({finalPrompt:'从尾帧继续向前行进',shotPlan:[],improvements:[],warnings:[],suggestedSpec:{}})}}]}))};}})};env=await fixture({workspace:true,content:true,apiSettings:dependencies,assets:{root,maxAssetBytes:1024,userQuotaBytes:4096,maxThumbnailBytes:512}});});
afterEach(async()=>{await env?.close();if(root.startsWith(join(tmpdir(),'studio-frame-test-')))await rm(root,{recursive:true,force:true});});
async function setup(){const account=await env.signup('Frame_Context');const h=env.headers(account);await env.call('PATCH','/studio-api/me/model-configs/text',{...h,payload:{apiBase:'https://api.example.test',model:'Vision/Text',apiKey:'FAKE_CONTEXT_KEY',expectedRevision:null}});const asset=(await env.call('POST','/studio-api/assets',{...h,payload:{title:'尾帧',mimeType:'image/png',bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')}})).json();expect((await env.app.inject({method:'PUT',url:'/studio-api/assets/'+asset.id+'/content?variant=original',payload:bytes,headers:{cookie:h.cookie,'x-workspace-context':h.context,'x-csrf-token':h.csrf,origin,'content-type':'application/octet-stream'}})).statusCode).toBe(204);expect((await env.call('POST','/studio-api/assets/'+asset.id+'/complete',{...h,payload:{}})).statusCode).toBe(200);const draft=(await env.call('POST','/studio-api/prompt-drafts',{...h,payload:{type:'video',sceneId:'extension',userRequest:'原视频：沿街前进\n续写：从尾帧继续',requestedSpec:{},audioPlan:'',lockedConstraints:[],references:[{assetId:asset.id,alias:'@图片1',mediaType:'image',role:'尾帧',description:'上一段实际最后一帧',available:true,unbound:false}],ruleVersion:'studio-video-rules-v1',idempotencyKey:randomUUID()}})).json();return {account,asset,draft};}
const preview=(account:Account,id:string,aliases=['@图片1'])=>env.call('POST','/studio-api/prompt-drafts/'+id+'/optimization-preview',{...env.headers(account),payload:{expectedRevision:0,configRevision:1,referenceAliases:aliases}});
it('freezes the owned tail image in the confirmed text request and sends it once',async()=>{const a=await setup(),p=await preview(a.account,a.draft.id);expect(p.statusCode).toBe(201);const frozen=(await env.pool.query('SELECT request_body FROM workspace_prompt_previews WHERE id=$1',[p.json().id])).rows[0].request_body;const body=JSON.parse(frozen);expect(body.messages[1].content).toEqual(expect.arrayContaining([{type:'image_url',image_url:{url:'data:image/png;base64,'+bytes.toString('base64'),detail:'high'}}]));expect(body.messages[0].content).not.toContain('媒体没有上传');expect(body.messages[0].content).not.toContain('若未提供上一段结尾的文字说明');expect(body.messages[0].content).toContain('以所附尾帧的实际画面为准');expect(calls).toHaveLength(0);await writeFile(join(root,a.account.view.user.id,a.asset.id,'original'),Buffer.from('changed'));const response=await env.call('POST','/studio-api/prompt-drafts/'+a.draft.id+'/optimize',{...env.headers(a.account),payload:{approvalId:p.json().id,decision:{confirmed:true,acknowledgeTextFee:true}}});expect(response.statusCode).toBe(202);await executeNextPromptTask(env.pool,dependencies);await executeNextPromptTask(env.pool,dependencies);expect(calls).toHaveLength(1);expect(calls[0].body?.toString()).toBe(frozen);});
it('rejects an extension preview without its selected tail instead of silently sending text only',async()=>{const a=await setup();expect((await preview(a.account,a.draft.id,[])).statusCode).toBe(422);expect(calls).toHaveLength(0);expect((await env.pool.query('SELECT count(*)::int n FROM workspace_prompt_previews')).rows[0].n).toBe(0);});
it('rejects a tail whose owned bytes are missing or changed before approval',async()=>{const a=await setup();await writeFile(join(root,a.account.view.user.id,a.asset.id,'original'),Buffer.alloc(bytes.length));expect((await preview(a.account,a.draft.id)).statusCode).toBe(409);expect(calls).toHaveLength(0);});
it('never exposes another account tail through its preview',async()=>{const a=await setup(),other=await env.signup('Frame_Other');expect((await preview(other,a.draft.id)).statusCode).toBe(404);expect(calls).toHaveLength(0);});
