import {beforeEach,afterEach,expect,it} from 'vitest';
import {fixture,type Fixture} from './account-fixture.js';
let f:Fixture;beforeEach(async()=>{f=await fixture();});afterEach(async()=>{await f?.close();});
it('unauthenticated own-document and deep business APIs return401',async()=>{for(const path of ['/studio-api/me/document','/studio-api/projects/private-deep-resource'])expect((await f.call('GET',path)).statusCode).toBe(401);});
it('requires current workspace context for authenticated business reads',async()=>{const a=await f.signup();expect((await f.call('GET','/studio-api/me/document',{cookie:a.cookie})).statusCode).toBe(409);});
it('A context with B cookie rejects read/write/logout and does not disclose or mutate B',async()=>{
 const a=await f.signup('Fake_A'),b=await f.signup('Fake_B');const mixed={...f.headers(b),context:a.view.contextId};
 const before=await f.call('GET','/studio-api/me/document',f.headers(b));
 for(const [method,path,payload] of [['GET','/studio-api/me/document',undefined],['PATCH','/studio-api/me/document',{expectedRevision:0,lastVisitedPage:'/tasks'}],['POST','/studio-api/auth/logout',undefined]] as const){const response=await f.call(method,path,{...mixed,payload});expect(response.statusCode).toBe(409);expect(response.json()).toEqual({code:'SESSION_CHANGED'});expect(response.body).not.toContain('Fake_B');}
 expect((await f.call('GET','/studio-api/me/document',f.headers(b))).json()).toEqual(before.json());expect((await f.call('GET','/studio-api/session',{cookie:b.cookie})).statusCode).toBe(200);
});
it('forged owner/userId body or query is rejected and cannot alter other users',async()=>{const a=await f.signup('Fake_A'),b=await f.signup('Fake_B');for(const key of ['owner','userId','user_id']){expect((await f.call('PATCH','/studio-api/me/document',{...f.headers(b),payload:{expectedRevision:0,[key]:a.view.user.id,lastVisitedPage:'/tasks'}})).statusCode).toBe(400);expect((await f.call('GET',`/studio-api/me/document?${key}=${a.view.user.id}`,f.headers(b))).statusCode).toBe(400);}expect((await f.call('GET','/studio-api/me/document',f.headers(a))).json().revision).toBe(0);});
it('real repository ownership returns404 for B requesting A document ID',async()=>{const a=await f.signup('Fake_A'),b=await f.signup('Fake_B');const id=(await f.pool.query('SELECT id FROM user_documents WHERE user_id=$1',[a.view.user.id])).rows[0].id;expect((await f.call('GET',`/studio-api/test-documents/${id}`,f.headers(a))).statusCode).toBe(200);expect((await f.call('GET',`/studio-api/test-documents/${id}`,f.headers(b))).statusCode).toBe(404);});
it.each(['wrong-origin','missing-origin','missing-token','wrong-token','other-user-token'])('rejects unsafe authenticated writes %s',async(kind)=>{const a=await f.signup('Fake_A'),b=await f.signup('Fake_B');const options:{origin?:string|null;csrf?:string}={};if(kind==='wrong-origin')options.origin='https://other.test';if(kind==='missing-origin')options.origin=null;if(kind==='missing-token')options.csrf=undefined;if(kind==='wrong-token')options.csrf='FAKE_WRONG';if(kind==='other-user-token')options.csrf=b.view.csrfToken;expect((await f.call('PATCH','/studio-api/me/document',{...f.headers(a),...options,payload:{expectedRevision:0,lastVisitedPage:'/tasks'}})).statusCode).toBe(403);expect((await f.call('GET','/studio-api/me/document',f.headers(a))).json().revision).toBe(0);});

it('non-ASCII CSRF token is403 rather than an internal error',async()=>{const a=await f.signup();expect((await f.call('PATCH','/studio-api/me/document',{...f.headers(a),csrf:'é'.repeat(43),payload:{expectedRevision:0,lastVisitedPage:'/tasks'}})).statusCode).toBe(403);});


it('rejected cross-site write does not extend idle expiry',async()=>{const a=await f.signup();f.advance(23*3600000);expect((await f.call('PATCH','/studio-api/me/document',{...f.headers(a),origin:'https://other.test',payload:{expectedRevision:0,lastVisitedPage:'/tasks'}})).statusCode).toBe(403);f.advance(3600000);expect((await f.call('GET','/studio-api/session',{cookie:a.cookie})).statusCode).toBe(401);});
