import {beforeEach,afterEach,expect,it} from 'vitest';
import {fixture,fakePassword,type Fixture} from './account-fixture.js';
let f:Fixture;beforeEach(async()=>{f=await fixture();});afterEach(async()=>{await f?.close();});
it('stores independent A/B theme, sort and page and restores them in a new login',async()=>{
 const a=await f.signup('Fake_A'),b=await f.signup('Fake_B');const docA=(await f.call('GET','/studio-api/me/document',f.headers(a))).json();const docB=(await f.call('GET','/studio-api/me/document',f.headers(b))).json();
 const updateA=await f.call('PATCH','/studio-api/me/document',{...f.headers(a),payload:{expectedRevision:0,preferences:{...docA.preferences,theme:'light',projectSort:'title'},lastVisitedPage:'/tasks'}});const updateB=await f.call('PATCH','/studio-api/me/document',{...f.headers(b),payload:{expectedRevision:0,preferences:{...docB.preferences,theme:'dark'},lastVisitedPage:'/assets'}});
 expect(updateA.statusCode).toBe(200);expect(updateB.statusCode).toBe(200);expect(updateA.json()).toMatchObject({revision:1,lastVisitedPage:'/tasks',preferences:{theme:'light',projectSort:'title'}});expect(updateB.json()).toMatchObject({revision:1,lastVisitedPage:'/assets',preferences:{theme:'dark',projectSort:'updated'}});
 const boot=await f.bootstrap();const login=await f.call('POST','/studio-api/auth/login',{...boot,payload:{username:'Fake_A',password:fakePassword}});expect(login.statusCode).toBe(200);expect((await f.call('GET','/studio-api/me/document',{cookie:f.cookie(login,'__Host-aiwork-session'),context:login.json().contextId})).json()).toEqual(updateA.json());
});
it('concurrent same-revision edits have one winner and a409 conflict',async()=>{const a=await f.signup();const results=await Promise.all(['/tasks','/assets'].map(lastVisitedPage=>f.call('PATCH','/studio-api/me/document',{...f.headers(a),payload:{expectedRevision:0,lastVisitedPage}})));expect(results.map(r=>r.statusCode).sort()).toEqual([200,409]);expect((await f.call('GET','/studio-api/me/document',f.headers(a))).json().revision).toBe(1);});
it('onboarding returns a consistent new revision and session reads its current status',async()=>{const a=await f.signup();const completed=await f.call('PATCH','/studio-api/me/onboarding',{...f.headers(a),payload:{completed:true,expectedRevision:0}});expect(completed.statusCode).toBe(200);expect(completed.json()).toMatchObject({revision:1,onboardingCompletedAt:'2026-10-08T12:00:00.000Z'});expect((await f.call('GET','/studio-api/session',{cookie:a.cookie})).json().onboardingCompletedAt).toBe(completed.json().onboardingCompletedAt);expect((await f.call('PATCH','/studio-api/me/document',{...f.headers(a),payload:{expectedRevision:0,lastVisitedPage:'/tasks'}})).statusCode).toBe(409);});
it.each(['https://other.test','//other.test','/register','/not-a-work-page'])('rejects nonwhitelisted remembered page %s',async(lastVisitedPage)=>{const a=await f.signup();expect((await f.call('PATCH','/studio-api/me/document',{...f.headers(a),payload:{expectedRevision:0,lastVisitedPage}})).statusCode).toBe(400);});
it('model defaults are excluded from user preferences and unknown preferences rejected',async()=>{const a=await f.signup();const doc=(await f.call('GET','/studio-api/me/document',f.headers(a))).json();expect(doc.preferences).not.toHaveProperty('defaultTextModel');expect(doc.preferences).not.toHaveProperty('defaultVideoModel');expect(doc.preferences).not.toHaveProperty('lastVisitedPage');expect((await f.call('PATCH','/studio-api/me/document',{...f.headers(a),payload:{expectedRevision:0,preferences:{...doc.preferences,defaultTextModel:'FAKE_MODEL'}}})).statusCode).toBe(400);});
