import {afterEach,beforeEach,expect,it} from 'vitest';
import {randomUUID,createHash} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fixture,type Fixture,type Account} from './account-fixture.js';
import {ApiSecrets} from '../src/security/api-secrets.js';
import {RestrictedOutbound,type OutboundRequest} from '../src/security/outbound.js';
let f:Fixture,root:string,calls:OutboundRequest[],mode:'success'|'failed'|'unknown',time:Date;
const base='https://video.example.test',video=Buffer.from('000000186674797069736F6D0000020069736F6D69736F32','hex');
const contract={version:'mock-video-v1',verification:'reviewed' as const,evidence:[{kind:'mock' as const,reference:'isolated fake provider only'}],routes:{models:true,videoSubmit:true,videoQuery:true,videoContent:true,chat:false,assets:true,workContext:false,continuation:false,backup:false},textModels:[],videoModels:['seedance'],videoAliases:[],videoSpecs:[{modelId:'seedance',durationSeconds:5,ratio:'16:9',resolution:'480p'}],limits:{assetBytes:1024*1024,promptBytes:12288,imageReferences:1,videoReferences:0}};
let dependencies:{secrets:ApiSecrets;outbound:RestrictedOutbound};
const assets=()=>({root,maxAssetBytes:1024*1024,userQuotaBytes:8*1024*1024,maxThumbnailBytes:256*1024});
beforeEach(async()=>{root=await mkdtemp(join(tmpdir(),'aiwork-video-task-test-'));calls=[];mode='success';time=new Date('2026-10-08T12:00:00Z');dependencies={secrets:new ApiSecrets({activeVersion:'test',keys:new Map([['test',Buffer.alloc(32,8)]])}),outbound:new RestrictedOutbound({resolve:async()=>[{address:'93.184.216.34',family:4}],request:async request=>{calls.push(request);if(request.method==='POST'&&mode==='unknown')throw Error('FAKE_PRIVATE_TIMEOUT');if(request.url.endsWith('/v1/assets')){const input=JSON.parse(request.body!.toString()),bytes=Buffer.from(input.data_base64,'base64');return {status:200,body:Buffer.from(JSON.stringify({object:'asset',id:'owned-upload-'+createHash('sha256').update(bytes).digest('hex').slice(0,12),mime_type:input.mime_type,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),created_at:1791460800,expires_at:1791464400}))};}if(request.url.endsWith('/content'))return {status:200,body:video};if(request.url.endsWith('/generations'))return {status:200,body:Buffer.from(JSON.stringify({task:{id:'fake-'+createHash('sha256').update(request.apiKey).digest('hex').slice(0,12),status:'queued'}}))};return {status:200,body:Buffer.from(JSON.stringify({task:{id:'fake-'+createHash('sha256').update(request.apiKey).digest('hex').slice(0,12),status:mode==='failed'?'failed':'completed',content_url:'https://127.0.0.1/PRIVATE_SHOULD_NEVER_FETCH',...(mode==='failed'?{error:{code:'video_execution_failed',billing_state:'pending',message:'FAKE_PRIVATE_LOG',upstream:{code:3003,message:'input image content[1] may contain real person'}}}:{})}}))};}})};f=await fixture({workspace:true,content:true,apiSettings:dependencies,assets:assets(),videoContracts:new Map([[base,contract]])});});
afterEach(async()=>{await f?.close();if(root.startsWith(join(tmpdir(),'aiwork-video-task-test-')))await rm(root,{recursive:true,force:true});});
async function setup(name:string,key:string){const account=await f.signup(name);expect((await f.call('PATCH','/studio-api/me/model-configs/video',{...f.headers(account),payload:{apiBase:base,model:'seedance',apiKey:key,expectedRevision:null}})).statusCode).toBe(200);const project=(await f.call('POST','/studio-api/projects',{...f.headers(account),payload:{title:'视频任务项目'}})).json();const textId=randomUUID(),nodeId=randomUUID();const saved=await f.call('POST','/studio-api/projects/'+project.id+'/commands',{...f.headers(account),payload:{expectedRevision:0,idempotencyKey:randomUUID(),command:{type:'operations',operations:[{id:randomUUID(),type:'add_node',payload:{node:{id:textId,type:'text',title:'创意',x:0,y:0,locked:false,data:{kind:'text',text:'雨后街道',referenceTokens:[]}}}},{id:randomUUID(),type:'add_node',payload:{node:{id:nodeId,type:'video-generation',title:'视频',x:400,y:0,locked:false,data:{kind:'video-generation',draft:{modelId:'seedance',durationSeconds:5,ratio:'16:9',resolution:'480p'},inputBindings:[],stale:true}}}},{id:randomUUID(),type:'add_edge',payload:{edge:{id:randomUUID(),sourceId:textId,targetId:nodeId,port:'text',order:0}}}]}}});expect(saved.statusCode).toBe(200);return {account,projectId:project.id,nodeId,revision:1};}
async function preview(owner:Awaited<ReturnType<typeof setup>>){owner.revision=(await f.call('GET','/studio-api/projects/'+owner.projectId+'/workspace',f.headers(owner.account))).json().graph.revision;const response=await f.call('POST','/studio-api/projects/'+owner.projectId+'/video-run-preview',{...f.headers(owner.account),payload:{expectedRevision:owner.revision,configRevision:1,nodeIds:[owner.nodeId]}});expect(response.statusCode).toBe(201);return response.json();}
const confirm=(owner:Awaited<ReturnType<typeof setup>>,approvalId:string)=>f.call('POST','/studio-api/projects/'+owner.projectId+'/video-runs',{...f.headers(owner.account),payload:{approvalId,decision:{confirmed:true,acknowledgeVideoFee:true}}});
async function work(){const {executeNextVideoTask}=await import('../src/tasks/video-worker.js');const result=await executeNextVideoTask(f.pool,{...dependencies,assets:assets(),contracts:new Map([[base,contract]])},()=>new Date(time));time=new Date(time.getTime()+5000);return result;}
const read=(account:Account,id:string)=>f.call('GET','/studio-api/runs/'+id,f.headers(account));
it('places a completed result in its owned canvas exactly once while no browser is open',async()=>{
 const a=await setup('VideoTask_AutoPlace','MOCK_KEY_A'),b=await setup('VideoTask_AutoOther','MOCK_KEY_B'),created=await confirm(a,(await preview(a)).id);
 await work();await work();const run=(await read(a.account,created.json()[0].id)).json();
 const graph=(await f.call('GET','/studio-api/projects/'+a.projectId+'/workspace',f.headers(a.account))).json().graph;
 const result=graph.nodes.find((node:{type:string;data:{runId?:string}})=>node.type==='result'&&node.data.runId===run.id);
 expect(result).toBeDefined();expect(result.data.assetId).toBe(run.resultAssetId);
 expect(graph.edges).toEqual(expect.arrayContaining([expect.objectContaining({sourceId:a.nodeId,targetId:result.id,relation:'result'})]));
 for(let i=0;i<3;i++)await work();
 expect((await f.call('GET','/studio-api/projects/'+a.projectId+'/workspace',f.headers(a.account))).json().graph).toEqual(graph);
 expect((await f.call('GET','/studio-api/projects/'+b.projectId+'/workspace',f.headers(b.account))).json().graph.nodes).toHaveLength(2);
 expect(calls.filter(request=>request.method==='POST')).toHaveLength(1);
});
it('retries only the local canvas transaction after placement fails and never re-adds an undone result',async()=>{
 const a=await setup('VideoTask_PlaceRetry','MOCK_KEY_A'),created=await confirm(a,(await preview(a)).id);
 await f.pool.query("CREATE FUNCTION reject_auto_result() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic local save failure'; END $$");
 await f.pool.query('CREATE TRIGGER reject_auto_result BEFORE INSERT ON workspace_command_receipts FOR EACH ROW EXECUTE FUNCTION reject_auto_result()');
 await work();await work();const run=(await read(a.account,created.json()[0].id)).json();
 expect(run).toMatchObject({executionState:'succeeded',deliveryState:'available_for_preview'});
 expect((await f.call('GET','/studio-api/projects/'+a.projectId+'/workspace',f.headers(a.account))).json().graph.nodes).toHaveLength(2);
 await f.pool.query('DROP TRIGGER reject_auto_result ON workspace_command_receipts');const callsBefore=calls.length;await work();
 const ready=(await f.call('GET','/studio-api/projects/'+a.projectId+'/workspace',f.headers(a.account))).json();expect(ready.graph.nodes).toHaveLength(3);expect(calls).toHaveLength(callsBefore);
 expect((await f.call('POST','/studio-api/projects/'+a.projectId+'/commands',{...f.headers(a.account),payload:{expectedRevision:ready.graph.revision,idempotencyKey:randomUUID(),command:{type:'undo'}}})).statusCode).toBe(200);
 for(let i=0;i<3;i++)await work();expect((await f.call('GET','/studio-api/projects/'+a.projectId+'/workspace',f.headers(a.account))).json().graph.nodes).toHaveLength(2);expect(calls).toHaveLength(callsBefore);
});
it('freezes owned A/B video tasks and copies results from the fixed content endpoint into private assets',async()=>{
 const a=await setup('VideoTask_A','MOCK_KEY_A'),b=await setup('VideoTask_B','MOCK_KEY_B'),pa=await preview(a),pb=await preview(b),ta=await confirm(a,pa.id),tb=await confirm(b,pb.id);expect(ta.statusCode).toBe(202);expect(tb.statusCode).toBe(202);expect(calls).toHaveLength(0);
 for(let step=0;step<10;step++)await work();const posts=calls.filter(request=>request.method==='POST');expect(posts).toHaveLength(2);expect(posts.map(request=>request.apiKey).sort()).toEqual(['MOCK_KEY_A','MOCK_KEY_B']);expect(calls.every(request=>new URL(request.url).origin===base)).toBe(true);
 for(const [owner,created]of [[a,ta],[b,tb]] as const){const task=(await read(owner.account,created.json()[0].id)).json();expect(task).toMatchObject({kind:'video',executionState:'succeeded',deliveryState:'available_for_preview'});const asset=(await f.call('GET','/studio-api/assets/'+task.resultAssetId,f.headers(owner.account))).json();expect(asset).toMatchObject({sourceRunId:task.id,sha256:createHash('sha256').update(video).digest('hex')});const file=await f.call('GET','/studio-api/assets/'+asset.id+'/content',f.headers(owner.account));expect(file.rawPayload).toEqual(video);}
 expect((await read(b.account,ta.json()[0].id)).statusCode).toBe(404);
});
it('returns the same confirmed run and keeps its original key and request after API settings change',async()=>{
 const a=await setup('VideoTask_Rotate','MOCK_OLD_KEY'),p=await preview(a),created=await confirm(a,p.id);expect(created.statusCode).toBe(202);await f.call('PATCH','/studio-api/me/model-configs/video',{...f.headers(a.account),payload:{apiBase:base,model:'Different',apiKey:'MOCK_NEW_KEY',expectedRevision:1}});expect((await confirm(a,p.id)).json()[0].id).toBe(created.json()[0].id);for(let step=0;step<4;step++)await work();expect(calls.filter(request=>request.method==='POST')).toHaveLength(1);expect(calls.every(request=>request.apiKey==='MOCK_OLD_KEY')).toBe(true);expect(JSON.parse(calls.find(request=>request.method==='POST')!.body!.toString())).toMatchObject({model:'seedance',prompt:'雨后街道',duration:5});
});
it('persists the recognized 3003 failure safely and retains pending billing across subsequent reads',async()=>{
 const a=await setup('VideoTask_Failure','MOCK_KEY_A'),p=await preview(a),created=await confirm(a,p.id);expect(created.statusCode).toBe(202);mode='failed';await work();await work();const result=await read(a.account,created.json()[0].id);expect(result.json()).toMatchObject({executionState:'failed_confirmed',billingState:'pending_reconciliation',failure:{reasonCode:'video_reference_real_person_rejected',upstreamCode:'3003'}});expect(result.body).not.toContain('FAKE_PRIVATE');expect(result.body).not.toContain('input image');expect((await read(a.account,created.json()[0].id)).json().failure).toEqual(result.json().failure);
});
it('keeps uncertain submissions without automatically sending again',async()=>{
 const a=await setup('VideoTask_Unknown','MOCK_KEY_A'),p=await preview(a),created=await confirm(a,p.id);expect(created.statusCode).toBe(202);mode='unknown';for(let step=0;step<5;step++)await work();const result=await read(a.account,created.json()[0].id);expect(result.json()).toMatchObject({executionState:'submit_unknown',billingState:'pending_reconciliation'});expect(calls).toHaveLength(1);expect(result.body).not.toContain('FAKE_PRIVATE');expect((await confirm(a,p.id)).json()[0].id).toBe(created.json()[0].id);
});
it('rejects a stale preview and foreign confirmation before any upstream operation',async()=>{
 const a=await setup('VideoTask_Stale','MOCK_KEY_A'),b=await setup('VideoTask_Foreign','MOCK_KEY_B'),p=await preview(a);expect((await confirm(b,p.id)).statusCode).toBe(404);await f.call('PATCH','/studio-api/me/model-configs/video',{...f.headers(a.account),payload:{apiBase:base,model:'Changed',expectedRevision:1}});expect((await confirm(a,p.id)).statusCode).toBe(409);expect(calls).toHaveLength(0);
});
it('pauses and resumes only the original task query with the frozen key after a configuration rotation',async()=>{
 const a=await setup('VideoTask_Query','MOCK_OLD_KEY'),p=await preview(a),created=await confirm(a,p.id);expect(created.statusCode).toBe(202);await work();let run=(await read(a.account,created.json()[0].id)).json();
 const pause=await f.call('POST','/studio-api/runs/'+run.id+'/query-control',{...f.headers(a.account),payload:{expectedRevision:run.recordRevision,mode:'pause'}});expect(pause.statusCode).toBe(200);await work();expect(calls).toHaveLength(1);
 await f.call('PATCH','/studio-api/me/model-configs/video',{...f.headers(a.account),payload:{apiBase:base,model:'Different',apiKey:'MOCK_NEW_KEY',expectedRevision:1}});run=pause.json();const resumed=await f.call('POST','/studio-api/runs/'+run.id+'/reauthorize',{...f.headers(a.account),payload:{expectedRevision:run.recordRevision}});expect(resumed.statusCode).toBe(200);await work();expect(calls.filter(request=>request.method==='POST')).toHaveLength(1);expect(calls.every(request=>request.apiKey==='MOCK_OLD_KEY')).toBe(true);
});
it('withdraws a persisted run before any upstream request and preserves an explicit not-submitted outcome',async()=>{
 const a=await setup('VideoTask_Withdraw','MOCK_KEY_A'),p=await preview(a),created=await confirm(a,p.id);expect(created.statusCode).toBe(202);const run=created.json()[0],response=await f.call('POST','/studio-api/runs/'+run.id+'/withdraw',{...f.headers(a.account),payload:{expectedRevision:run.recordRevision}});expect(response.statusCode).toBe(200);await work();expect(calls).toHaveLength(0);expect(response.json()).toMatchObject({executionState:'failed_confirmed',billingState:'not_provided',failure:{reasonCode:'video_not_submitted'}});
});
it('marks an expired submit lease as unknown without a new submit or lookup with a new key',async()=>{
 const a=await setup('VideoTask_Restart','MOCK_KEY_A'),p=await preview(a),created=await confirm(a,p.id);expect(created.statusCode).toBe(202);await f.pool.query("UPDATE workspace_video_runs SET document=jsonb_set(document,'{executionState}','\"submitting\"'),lease_token=$1,lease_until=$2",[randomUUID(),new Date('2026-10-08T11:00:00Z')]);const {recoverExpiredVideoTasks}=await import('../src/tasks/video-worker.js');await recoverExpiredVideoTasks(f.pool,time);await work();expect(calls).toHaveLength(0);expect((await read(a.account,created.json()[0].id)).json()).toMatchObject({executionState:'submit_unknown',billingState:'pending_reconciliation'});
});
it('does not interrupt the submission lease through a query-control action before an upstream task exists',async()=>{
 const a=await setup('VideoTask_EarlyPause','MOCK_KEY_A'),p=await preview(a),created=await confirm(a,p.id);expect(created.statusCode).toBe(202);const run=created.json()[0];expect((await f.call('POST','/studio-api/runs/'+run.id+'/query-control',{...f.headers(a.account),payload:{expectedRevision:run.recordRevision,mode:'pause'}})).statusCode).toBe(409);await work();expect(calls.filter(request=>request.method==='POST')).toHaveLength(1);
});
async function addImage(owner:Awaited<ReturnType<typeof setup>>){
 const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6nRAAAAAASUVORK5CYII=','base64'),hash=createHash('sha256').update(bytes).digest('hex');const reserved=await f.call('POST','/studio-api/assets',{...f.headers(owner.account),payload:{title:'已确认参考图片',mimeType:'image/png',bytes:bytes.length,sha256:hash}});expect(reserved.statusCode).toBe(201);const assetId=reserved.json().id,h=f.headers(owner.account);expect((await f.app.inject({method:'PUT',url:'/studio-api/assets/'+assetId+'/content',payload:bytes,headers:{cookie:h.cookie,'x-workspace-context':h.context,'x-csrf-token':h.csrf,origin:'https://studio.test','content-type':'application/octet-stream'}})).statusCode).toBe(204);expect((await f.call('POST','/studio-api/assets/'+assetId+'/complete',{...h,payload:{}})).statusCode).toBe(200);
 const sourceId=randomUUID(),saved=await f.call('POST','/studio-api/projects/'+owner.projectId+'/commands',{...h,payload:{expectedRevision:1,idempotencyKey:randomUUID(),command:{type:'operations',operations:[{id:randomUUID(),type:'add_node',payload:{node:{id:sourceId,type:'asset',title:'图片参考',x:0,y:300,locked:false,data:{kind:'asset',assetId}}}},{id:randomUUID(),type:'add_edge',payload:{edge:{id:randomUUID(),sourceId,targetId:owner.nodeId,port:'image',order:1}}}]}}});expect(saved.statusCode,saved.body).toBe(200);owner.revision=2;return hash;
}
it('uploads exactly the explicitly connected owned image before submitting and freezes the remote mapping',async()=>{
 const a=await setup('VideoTask_Image','MOCK_KEY_A'),hash=await addImage(a),p=await preview(a),created=await confirm(a,p.id);expect(created.statusCode).toBe(202);await work();expect(calls.map(request=>new URL(request.url).pathname)).toEqual(['/v1/assets','/v1/videos/generations']);const body=JSON.parse(calls[1].body!.toString());expect(body.image_asset_ids).toEqual(['owned-upload-'+hash.slice(0,12)]);await work();expect(calls.filter(request=>request.url.endsWith('/v1/assets'))).toHaveLength(1);
});
it('does not send a generation or repeat an upload if the reference upload outcome is unknown',async()=>{
 const a=await setup('VideoTask_UploadUnknown','MOCK_KEY_A');await addImage(a);const p=await preview(a),created=await confirm(a,p.id);expect(created.statusCode).toBe(202);mode='unknown';for(let step=0;step<3;step++)await work();expect(calls).toHaveLength(1);expect(calls[0].url.endsWith('/v1/assets')).toBe(true);expect((await read(a.account,created.json()[0].id)).json()).toMatchObject({executionState:'submit_unknown',issueCode:'UPLOAD_UNKNOWN',billingState:'not_provided'});
});
it('retains separate result associations for two explicitly confirmed runs that return identical video bytes',async()=>{
 const a=await setup('VideoTask_SameBytes','MOCK_KEY_A'),first=await confirm(a,(await preview(a)).id);expect(first.statusCode).toBe(202);await work();await work();const one=(await read(a.account,first.json()[0].id)).json();const second=await confirm(a,(await preview(a)).id);expect(second.statusCode).toBe(202);await work();await work();const two=(await read(a.account,second.json()[0].id)).json();expect(one.resultAssetId).not.toBe(two.resultAssetId);for(const run of [one,two])expect((await f.call('GET','/studio-api/assets/'+run.resultAssetId,f.headers(a.account))).json().sourceRunId).toBe(run.id);expect(calls.filter(request=>request.url.endsWith('/generations'))).toHaveLength(2);
});
async function attachResult(owner:Awaited<ReturnType<typeof setup>>,run:{id:string;resultAssetId:string}){
 const snapshot=await f.call('GET','/studio-api/projects/'+owner.projectId+'/workspace',f.headers(owner.account));owner.revision=snapshot.json().graph.revision;
 if(snapshot.json().graph.nodes.some((node:{type:string;data:{runId?:string;assetId?:string}})=>node.type==='result'&&node.data.runId===run.id&&node.data.assetId===run.resultAssetId))return snapshot;
 const resultId=randomUUID();return f.call('POST','/studio-api/projects/'+owner.projectId+'/commands',{...f.headers(owner.account),payload:{expectedRevision:owner.revision,idempotencyKey:randomUUID(),command:{type:'operations',operations:[{id:randomUUID(),type:'add_node',payload:{node:{id:resultId,type:'result',title:'已生成视频',x:800,y:0,locked:false,data:{kind:'result',assetId:run.resultAssetId,runId:run.id}}}},{id:randomUUID(),type:'add_edge',payload:{edge:{id:randomUUID(),sourceId:owner.nodeId,targetId:resultId,port:'video',order:0,relation:'result'}}}]}}});
}
it('accepts the owned result lineage and rejects a foreign run in a graph command',async()=>{
 const a=await setup('VideoTask_Lineage','MOCK_KEY_A'),b=await setup('VideoTask_ForeignLineage','MOCK_KEY_B');const created=await confirm(a,(await preview(a)).id);await work();await work();const run=(await read(a.account,created.json()[0].id)).json();const attached=await attachResult(a,run);expect(attached.statusCode,attached.body).toBe(200);expect((await attachResult(b,run)).statusCode).toBe(404);
});
it('exports result bytes and readonly video history and imports new lineage without execution authorization',async()=>{
 const a=await setup('VideoTask_Package','MOCK_KEY_A'),b=await setup('VideoTask_PackageB','MOCK_KEY_B');const created=await confirm(a,(await preview(a)).id);await work();await work();const run=(await read(a.account,created.json()[0].id)).json();expect((await attachResult(a,run)).statusCode).toBe(200);
 const exported=await f.call('GET','/studio-api/projects/'+a.projectId+'/export',f.headers(a.account));expect(exported.statusCode,exported.body).toBe(200);const data=exported.json();expect(data.taskHistory[0]).toMatchObject({kind:'video',historical:true,resultAssetId:run.resultAssetId});expect(exported.body).not.toMatch(/MOCK_KEY|authBindingId|idempotencyKey|finalBody|taskId/);
 const h=f.headers(b.account),pending=(await f.call('POST','/studio-api/assets',{...h,payload:{title:'导入原件',mimeType:'video/mp4',bytes:video.length,sha256:createHash('sha256').update(video).digest('hex')}})).json();expect((await f.app.inject({method:'PUT',url:'/studio-api/assets/'+pending.id+'/content',payload:video,headers:{cookie:h.cookie,'x-workspace-context':h.context,'x-csrf-token':h.csrf,origin:'https://studio.test','content-type':'application/octet-stream'}})).statusCode).toBe(204);await f.call('POST','/studio-api/assets/'+pending.id+'/complete',{...h,payload:{}});
 const key=randomUUID(),input={data,assets:{[run.resultAssetId]:pending.id},idempotencyKey:key},imported=await f.call('POST','/studio-api/projects/import',{...h,payload:input});expect(imported.statusCode,imported.body).toBe(201);const result=imported.json().graph.nodes.find((node:{type:string})=>node.type==='result'),history=(await read(b.account,result.data.runId)).json();expect(history).toMatchObject({historical:true,projectId:imported.json().project.id,resultAssetId:result.data.assetId});expect(result.data.assetId).not.toBe(pending.id);expect((await f.call('GET','/studio-api/assets/'+result.data.assetId,h)).json().sourceRunId).toBe(history.id);expect((await f.call('POST','/studio-api/projects/import',{...h,payload:input})).json().project.id).toBe(imported.json().project.id);expect((await f.call('POST','/studio-api/runs/'+history.id+'/reauthorize',{...h,payload:{expectedRevision:0}})).statusCode).toBe(404);await work();expect(calls.filter(request=>request.method==='POST')).toHaveLength(1);
});
it('copies a graph with video results using new readonly history while preserving original result ownership',async()=>{
 const a=await setup('VideoTask_Copy','MOCK_KEY_A'),created=await confirm(a,(await preview(a)).id);await work();await work();const run=(await read(a.account,created.json()[0].id)).json();expect((await attachResult(a,run)).statusCode).toBe(200);const key=randomUUID(),copied=await f.call('POST','/studio-api/projects/'+a.projectId+'/copy',{...f.headers(a.account),payload:{expectedRevision:2,idempotencyKey:key}});expect(copied.statusCode,copied.body).toBe(201);const next=copied.json(),result=next.graph.nodes.find((node:{type:string})=>node.type==='result');expect(next.history).toEqual({undoDepth:0,redoDepth:0});expect((await read(a.account,result.data.runId)).json()).toMatchObject({historical:true,projectId:next.project.id,resultAssetId:result.data.assetId});expect((await f.call('GET','/studio-api/assets/'+run.resultAssetId,f.headers(a.account))).json().sourceRunId).toBe(run.id);expect((await f.call('POST','/studio-api/projects/'+a.projectId+'/copy',{...f.headers(a.account),payload:{expectedRevision:2,idempotencyKey:key}})).json().project.id).toBe(next.project.id);await work();expect(calls.filter(call=>call.method==='POST')).toHaveLength(1);
});
