import {randomUUID,createHash} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {beforeEach,afterEach,it,expect} from 'vitest';
import {fixture,origin,type Fixture,type Account} from './account-fixture.js';
import type {WorkspaceMigration} from '../../src/domain/workspace-migration.js';
let env:Fixture,root:string;
const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6nRAAAAAASUVORK5CYII=','base64'),sha256=createHash('sha256').update(bytes).digest('hex');
beforeEach(async()=>{root=await mkdtemp(join(tmpdir(),'aiwork-migration-test-'));env=await fixture({workspace:true,content:true,assets:{root,maxAssetBytes:1024,userQuotaBytes:8192,maxThumbnailBytes:512}});});
afterEach(async()=>{await env?.close();if(root.startsWith(join(tmpdir(),'aiwork-migration-test-')))await rm(root,{recursive:true,force:true});});
function data():WorkspaceMigration{return {format:'aiwork-workspace-migration',version:1,exportId:randomUUID(),createdAt:1,source:{database:'aiwork-studio:v1',schemaVersion:2},selection:{projectIds:['old-project'],includeStandalone:true,includeTrash:true,includePreferences:true},projects:[{project:{id:'old-project',schemaVersion:1,title:'旧故事',description:'旧描述',revision:1,createdAt:1,updatedAt:2,archived:false,tags:[],trashedAt:9},graph:{projectId:'old-project',revision:1,nodes:[{id:'old-node',type:'asset',title:'旧图片',x:5,y:6,locked:false,data:{kind:'asset',assetId:'old-asset'}}],edges:[],viewport:{x:20,y:30,scale:1.25}}}],assets:[{asset:{id:'old-asset',sha256,mediaType:'image',mimeType:'image/png',bytes:bytes.length,blobKey:'sha256:'+sha256,title:'旧原件',createdAt:1},original:{path:'media/'+sha256+'.original',sha256,bytes:bytes.length,mimeType:'image/png'},thumbnail:{path:'media/'+sha256+'.thumbnail',sha256,bytes:bytes.length,mimeType:'image/png'}}],records:[{kind:'prompt',id:'old-prompt',schemaVersion:1,readonly:true,document:{id:'old-prompt',title:'旧独立提示词',body:'完整正文',tags:[],variables:[],source:'自有',license:'自有',revision:0,starred:true,trashed:true}},{kind:'receipt-history',id:'agent-note:old',schemaVersion:1,readonly:true,document:{id:'agent-note:old',kind:'agent-local-note',projectId:'old-project',conversationId:'old-conversation',body:'旧 Agent 描述',context:{scope:'project',nodeIds:[],revision:1},createdAt:1}}],preferences:{theme:'light'}};}
const begin=(account:Account,input=data(),key=randomUUID())=>env.call('POST','/studio-api/me/imports',{...env.headers(account),payload:{data:input,idempotencyKey:key}});
const commit=(account:Account,id:string,preferences=false,revision=0)=>env.call('POST','/studio-api/me/imports/'+id+'/commit',{...env.headers(account),payload:{confirmedOwner:true,importPreferences:preferences,...(preferences?{expectedDocumentRevision:revision}:{})}});
async function upload(account:Account,batch:{id:string;files:{id:string}[]}){for(const file of batch.files){const h=env.headers(account),reply=await env.app.inject({method:'PUT',url:'/studio-api/me/imports/'+batch.id+'/files/'+file.id,payload:bytes,headers:{cookie:h.cookie,'x-workspace-context':h.context,'x-csrf-token':h.csrf,origin,'content-type':'application/octet-stream'}});expect(reply.statusCode).toBe(204);}}
it('stages owned files without visible workspace content, commits remapped documents and readonly history once, and preserves trash',async()=>{
 const a=await env.signup(),response=await begin(a);expect(response.statusCode).toBe(201);const batch=response.json();expect(batch.state).toBe('staged');expect((await env.call('GET','/studio-api/projects',env.headers(a))).json()).toEqual([]);expect((await env.call('GET','/studio-api/assets',env.headers(a))).json()).toEqual([]);
 expect((await commit(a,batch.id)).statusCode).toBe(409);await upload(a,batch);const result=await commit(a,batch.id);expect(result.statusCode).toBe(200);expect(result.json().state).toBe('committed');const mapped=result.json().mapping;expect(mapped.projects['old-project']).not.toBe('old-project');expect((await commit(a,batch.id)).json().mapping).toEqual(mapped);expect((await env.pool.query('SELECT id FROM workspace_projects WHERE user_id=$1',[a.view.user.id])).rows).toHaveLength(1);
 const graph=(await env.call('GET','/studio-api/projects/'+mapped.projects['old-project']+'/graph',env.headers(a))).json();expect(graph.nodes[0].id).not.toBe('old-node');expect(graph.nodes[0].data.assetId).toBe(mapped.assets['old-asset']);expect((await env.call('GET','/studio-api/projects?trashed=true',env.headers(a))).json()[0].title).toBe('旧故事');expect((await env.call('GET','/studio-api/prompts?trashed=true',env.headers(a))).json()[0].body).toBe('完整正文');
 const history=await env.call('GET','/studio-api/me/imports/'+batch.id+'/history',env.headers(a));expect(history.statusCode).toBe(200);expect(history.payload).toContain('旧 Agent 描述');expect((await env.call('GET','/studio-api/assets/'+mapped.assets['old-asset']+'/content?variant=thumbnail',env.headers(a))).rawPayload).toEqual(bytes);expect((await env.call('GET','/studio-api/me/document',env.headers(a))).json().preferences.theme).toBe('dark');
});
it('partitions the same import key and export ID by owner and rejects foreign batch reads, uploads, history and commit',async()=>{
 const a=await env.signup('Migration_A'),b=await env.signup('Migration_B'),input=data(),key=randomUUID(),batch=(await begin(a,input,key)).json();expect((await begin(a,input,key)).json().id).toBe(batch.id);const different=structuredClone(input);different.projects[0].project.title='不同内容';expect((await begin(a,different,key)).statusCode).toBe(409);expect((await begin(b,input,key)).json().id).not.toBe(batch.id);
 for(const path of ['', '/history'])expect((await env.call('GET','/studio-api/me/imports/'+batch.id+path,env.headers(b))).statusCode).toBe(404);expect((await commit(b,batch.id)).statusCode).toBe(404);const h=env.headers(b);expect((await env.app.inject({method:'PUT',url:'/studio-api/me/imports/'+batch.id+'/files/'+batch.files[0].id,payload:bytes,headers:{cookie:h.cookie,'x-workspace-context':h.context,'x-csrf-token':h.csrf,origin,'content-type':'application/octet-stream'}})).statusCode).toBe(404);
});
it('rejects invalid execution fields and media without altering cloud documents',async()=>{
 const a=await env.signup(),input=data();(input.records[0].document as Record<string,unknown>).apiKey='DO_NOT_STORE_KEY';expect((await begin(a,input)).statusCode).toBe(400);const batch=(await begin(a)).json(),h=env.headers(a);expect((await env.app.inject({method:'PUT',url:'/studio-api/me/imports/'+batch.id+'/files/'+batch.files[0].id,payload:Buffer.from('wrong'),headers:{cookie:h.cookie,'x-workspace-context':h.context,'x-csrf-token':h.csrf,origin,'content-type':'application/octet-stream'}})).statusCode).toBe(400);expect((await commit(a,batch.id)).statusCode).toBe(409);expect((await env.pool.query('SELECT id FROM workspace_projects')).rows).toHaveLength(0);
});
it('imports preferences only after explicit selection and revision verification, rolling back all documents on conflict',async()=>{
 const a=await env.signup(),batch=(await begin(a)).json();await upload(a,batch);expect((await commit(a,batch.id,true,99)).statusCode).toBe(409);expect((await env.pool.query('SELECT id FROM workspace_projects')).rows).toHaveLength(0);expect((await commit(a,batch.id,true,0)).statusCode).toBe(200);expect((await env.call('GET','/studio-api/me/document',env.headers(a))).json().preferences.theme).toBe('light');expect((await commit(a,batch.id,true,0)).statusCode).toBe(200);expect((await env.call('GET','/studio-api/me/document',env.headers(a))).json().revision).toBe(1);
});
it('counts staged import files against ordinary upload capacity',async()=>{
 const a=await env.signup();await begin(a);await env.pool.query('UPDATE workspace_imports SET reserved_bytes=8000 WHERE user_id=$1',[a.view.user.id]);
 const response=await env.call('POST','/studio-api/assets',{...env.headers(a),payload:{sha256:'a'.repeat(64),bytes:300,mimeType:'image/png',title:'新图片'}});
 expect(response.statusCode).toBe(413);expect(response.json()).toEqual({code:'USER_QUOTA_EXCEEDED'});expect((await env.pool.query('SELECT id FROM workspace_assets')).rows).toEqual([]);
});
